### PR TITLE
Add tests for Worker template 

### PR DESCRIPTION
**Pull request by Tratcher**
#7974

### CODE REVIEW

**Comment by Tratcher** [comment]
Blocked on getting a new SDK. https://github.com/aspnet/AspNetCore/pull/8670

**Comment by anurse** [comment]
Is more work needed here beyond just getting the new SDK? I want to know if we should move this over to someone else or punt it in order to make space for Kerberos :)

**Comment by Tratcher** [comment]
Hard to tell until we get the SDK update. Need to rebase and see if the existing tests work.

**Comment by jkotalik** [comment]
This should now be unblocked.

**Comment by anurse** [comment]
@Tratcher is the next step here as simple as rebasing/retriggering?

**Comment by Tratcher** [comment]
Rebased, but there's something wrong with my test that's causing a hang on all platforms.

**Comment by Tratcher** [comment]
@ryanbrandenburg already did most of this in https://github.com/aspnet/AspNetCore/pull/8628. I just need to re-enable the test. Closing this PR.

**Pull request closed without merging**
