### PR TITLE
Quarantine ClosingTheBrowserWindow_GracefullyDisconnects_TheCurrentCi…

### PR DESCRIPTION
**Pull request by brunolins16**
Addresses #44017

### CODE REVIEW

**Review by mkArtakMSFT — APPROVED** [review]
Thanks @brunolins16!

**Review by TanayParikh — CHANGES_REQUESTED** [review]
I believe we want to auto-retry these tests first: https://github.com/dotnet/aspnetcore/blob/main/eng/test-configuration.json#L5

https://github.com/dotnet/aspnetcore-internal/blob/main/docs/operations/quarantine_tests.md#instructions

**Comment by brunolins16** [comment]
> I believe we want to auto-retry these tests first: https://github.com/dotnet/aspnetcore/blob/main/eng/test-configuration.json#L5
> 
> https://github.com/dotnet/aspnetcore-internal/blob/main/docs/operations/quarantine_tests.md#instructions

They are not in helix. I think we need quarantine in this case.

**Review by TanayParikh — APPROVED** [review]
Ah I see, thanks!

**Pull request merged**
