### PR TITLE
Implement the async dispose pattern and the dispose pattern for JSObjectReference and JSInProcessObjectReference respectively

### PR DESCRIPTION
**Pull request by JinShil**
I believe the JS object reference ID that is disposed with the call to `DotNet.jsCallDispatcher.disposeJSObjectReferenceById` is an unmanaged resource, so `JSObjectReference` and `JSInProcessObjectReference` should implement [the async dispose pattern](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync#implement-the-async-dispose-pattern) and [the dispose pattern](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#implement-the-dispose-pattern) respectively.

### CODE REVIEW

**Review by javiercn — APPROVED** [review]

**Comment by javiercn** [comment]
The API changes need to be included in the shipped api files.

@dotnet/aspnet-build What's the best way to change the shipped APIs file? I've only done it through VS.

**Comment by dougbu** [comment]
> What's the best way to change the shipped APIs file? I've only done it through VS.

That's the best way.

**Comment by javiercn** [comment]
If you apply this patch [api-update.zip](https://github.com/dotnet/aspnetcore/files/5440435/api-update.zip) it should fix the build issues.

**Comment by javiercn** [comment]
@JinShil thanks for submitting a contribution.

Unfortunately, on further review we won't be taking this PR. We can't guarantee synchronous disposal of JS references and we already implement `IAsyncDisposable` on them, which should be enough.

**Pull request closed without merging**
