### PR TITLE
Update SignalR Endpoint pattern usage

### LINKED ISSUE #12218: Should MapHubConnections return a strongly-typed builder?
See: https://github.com/aspnet/AspNetCore/blob/a9a9298d4f2ae06b373090a0a0dacb1f0911fe93/src/SignalR/common/Http.Connections/ref/Microsoft.AspNetCore.Http.Connections.netcoreapp3.0.cs#L6

Generally we want `IEndpointRouteBuilder` extensions to return a specific type (more specific than `IEndpointConventionBuilder`). This way it can be targeted by framework-specific extension methods.

/cc @anurse @BrennanConroy @JamesNK

### LINKED ISSUE #12219: Should IEndpointConventionBuilder-derived types live in M.A.Builder?
See: https://github.com/aspnet/AspNetCore/blob/a9a9298d4f2ae06b373090a0a0dacb1f0911fe93/src/SignalR/server/SignalR/src/HubEndpointConventionBuilder.cs#L7

In MVC we put these in the `Microsoft.AspNetCore.Builder` namespace. It probably doesn't super matter because you wouldn't usually refer to one of these by type, but we should try to follow a convention.

I came across this during API review for components, which isn't in the `M.A.Builder` namespace.

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/aspnet/AspNetCore/issues/12218
Fixes https://github.com/aspnet/AspNetCore/issues/12219

cc @davidfowl @rynowak @JamesNK

### CODE REVIEW

**Review by rynowak — APPROVED** [review]

**Comment by JamesNK** [comment]
re: https://github.com/aspnet/AspNetCore/issues/12219

Are there other convention builder types that don't live in the builder namespace?

**Comment by BrennanConroy** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=269803

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2809

**Comment by BrennanConroy** [comment]
> Are there other convention builder types that don't live in the builder namespace?

A quick github search doesn't show any

**Review by halter73 — APPROVED** [review]

**Review by JamesNK — APPROVED** [review]
:shipit:

**Pull request merged**
