### PR TITLE
dotnet/runtime#1506 optimize huffman decoding

### PR DESCRIPTION
**Pull request by rokonec**
Optimized to use 8 bits lookup tables tree.

dotnet/runtime#1506

Shared with runtime. Already reviewed by @Tratcher in PR dotnet/runtime#43603

Fixes #18943

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Bot opened the same PR https://github.com/dotnet/aspnetcore/pull/28242

**Comment by Tratcher** [comment]
I thought you were going to send this PR and run the benchmarks before merging the change in runtime? Do we still have benchmarks we need to run here?

I'll close #28242 since it's redundant.

**Comment by rokonec** [comment]
@Tratcher benchmarks has been created and run in https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/tests/PerformanceTests/HPackHuffmanBenchmark/Program.cs
Latest version has been benchmarked with following result:

Method | Mean | Error | StdDev | Op/s | Ratio
-- | -- | -- | -- | -- | --
Old | 2,146.14 ns | 40.559 ns | 39.835 ns | 465,953.3 | 1.00
New | 537.22 ns | 2.607 ns | 2.439 ns | 1,861,447.5 | 0.25

Unfortunately https://github.com/dotnet/aspnetcore/blob/47138f9061f08af22f5df345051ff88354839a78/src/Servers/Kestrel/perf/Kestrel.Performance/HPackDecoderBenchmark.cs#L47
do not contain benchmarks for huffman encoded headers.

Shall I add it there?

**Comment by Tratcher** [comment]
Ok. I don't know if we need duplication of those benchmarks. @halter73 do you care?

**Comment by halter73** [comment]
I'm fine with not duplicating. Maybe we should remove the HPACK microbenchmarks from Kestrel if they're covered by the runtime so we don't waste time on the Kestrel versions.

**Review by Tratcher — APPROVED** [review]

**Pull request merged**
