### PR TITLE
Collect dumps for tests that seem to be flaky

### PR DESCRIPTION
**Pull request by davidfowl**
Lets see if we can find any blocking going on when these tests fail with timeouts.

### CODE REVIEW

**Review by halter73 — APPROVED** [review]

**Comment by davidfowl** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=210986

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2303

**Comment by anurse** [comment]
Does this... work now?

**Comment by davidfowl** [comment]
Only on windows. But it *can* also work on linux if we switch to event pipe (https://github.com/dotnet/diagnostics/blob/049d377673644e073b560da4a856532c58a09054/src/Microsoft.Diagnostics.Tools.RuntimeClient/DiagnosticHelpers.cs#L34)

**Comment by anurse** [comment]
Swanky

**Pull request merged**
