### PR TITLE
Update SDK

### PR DESCRIPTION
**Pull request by MackinnonBuck**

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Comment by RussKie** [comment]
```
.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.23463.1/tools/SourceBuild/AfterSourceBuild.proj#L68
.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.23463.1/tools/SourceBuild/AfterSourceBuild.proj(68,5): error : (NETCORE_ENGINEERING_TELEMETRY=AfterSourceBuild) 1 new pre-builts discovered! Detailed usage report can be found at /__w/1/s/artifacts/source-build/self/prebuilt-report/baseline-comparison.xml.
See https://aka.ms/dotnet/prebuilts for guidance on what pre-builts are and how to eliminate them.
Package IDs are:
Microsoft.NETCore.App.Ref.8.0.0-preview.7.23375.6
```

I'm calling a friend.... @wtgodbe are you there? :)

We couldn't find any direct mentions of "8.0.0-preview.7.23375.6", however looking through the [sourcebuild.binlog](https://artprodcus3.artifacts.visualstudio.com/A6fcc92e5-73a7-4f88-8d13-d9045b45fb27/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy1wdWJsaWMvcHJvamVjdElkL2NiYjE4MjYxLWM0OGYtNGFiYi04NjUxLThjZGNiNTQ3NDY0OS9idWlsZElkLzQzNTUzMS9hcnRpZmFjdE5hbWUvQnVpbGRMb2dzX1NvdXJjZUJ1aWxkX01hbmFnZWRfQXR0ZW1wdDE1/content?format=file&subPath=%2Fartifacts%2Fsource-build%2Fself%2Fsrc%2Fartifacts%2Fsourcebuild.binlog) I see that this version is everywhere...
Could it be because of this?
https://github.com/dotnet/aspnetcore/blob/34ef6922fb525dcecc8a3f9b7750414de93af438/eng/testing/linker/SupportFiles/Directory.Build.targets#L16-L36

**Comment by mthalman** [comment]
It's because the SDK being used for the build still points to the old 8.0 P7 version in its BundledVersions.props file causing this version to be loaded for net8.0. For now, this can be added to https://github.com/dotnet/aspnetcore/blob/main/eng/SourceBuildPrebuiltBaseline.xml as an allowed prebuilt.

**Comment by RussKie** [comment]
Thank you @mthalman for the suggestion.

**Comment by eerhardt** [comment]
@MackinnonBuck @javiercn @mkArtakMSFT - It looks like the test failures are in the Components E2E tests. Can someone from the Blazor team take a look?

**Comment by eerhardt** [comment]
@SteveSandersonMS @halter73 - any chance one of you could look at the failing tests here?

**Comment by MackinnonBuck** [comment]
It looks like at least part of the problem is that interactively-rendered `<script>` elements no longer execute. Some of our tests were depending on that working. I haven't been able to track down the reason just yet.

**Comment by MackinnonBuck** [comment]
Alright, hopefully this works :)

**Comment by SteveSandersonMS** [comment]
@MackinnonBuck I was expecting changes in `release/8.0` to flow into `main` automatically. Do you know if that's incorrect? If so there are a lot of 8.0 changes that need to get ported to main.

**Comment by MackinnonBuck** [comment]
> I was expecting changes in release/8.0 to flow into main automatically

@SteveSandersonMS I believe that's correct. I just opted to cherry-pick one of your commits from https://github.com/dotnet/aspnetcore/pull/51059 in order to unblock this SDK update without waiting for the next merge PR. However, I do see that there hasn't been an active `release/8.0` => `main` merge PR [in two weeks](https://github.com/dotnet/aspnetcore/pulls?q=is%3Apr+label%3A%22Type%3A+Merge+Forward+%3Afast_forward%3A%22+)...

@wtgodbe, do you know why this is the caase?

**Comment by wtgodbe** [comment]
I disabled automatic merges from 8.0 to main after RC2 locked down, I sent a couple emails to the team about it. I'm doing periodic mop-up merges between now and RTM to get any changes that got missed.

**Pull request merged**
