### PR TITLE
Update selenium chrome driver

### PR DESCRIPTION
**Pull request by BrennanConroy**

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
Much appreciated.

/fyi @dotnet/aspnet-build

**Comment by JunTaoLuo** [comment]
Woot, thanks!

**Comment by dougbu** [comment]
Really need a way to get the bot to at least leave branches, if not PRs, around when patching release branches fails. In any case, we also need a manual backport here if you can do it @BrennanConroy If not, I'll get to it eventually&hellip;

**Pull request merged**
