### PR TITLE
Disable async key ring update in Mvc.FunctionalTests

### PR DESCRIPTION
**Pull request by captainsafia**
I _think_ this is right place to set the app context switch to get it to apply to all tests.

### CODE REVIEW

**Comment by halter73** [comment]
Since it's an AppContext switch, we could also probably do this in a static constructor, but I don't think repeatedly setting it is that bad. How many successful runs do we think we'll need before we consider this strong evidence that the key ring updates cause of the timeouts?

**Comment by captainsafia** [comment]
> Since it's an AppContext switch, we could also probably do this in a static constructor, but I don't think repeatedly setting it is that bad. How many successful runs do we think we'll need before we consider this strong evidence that the key ring updates are the cause of the timeouts?

I suppose it depends on the current failure rate for these. What's that looking like?

**Comment by halter73** [comment]
After a quick spot check of https://dev.azure.com/dnceng-public/public/_build?definitionId=83&_a=summary&repositoryFilter=56&branchFilter=308%2C308, I'd say it's timing out in Mvc.FunctionalTests every 3 to 5 runs.

**Comment by captainsafia** [comment]
> After a quick spot check of [dev.azure.com/dnceng-public/public/_build?definitionId=83&_a=summary&repositoryFilter=56&branchFilter=308%2C308](https://dev.azure.com/dnceng-public/public/_build?definitionId=83&_a=summary&repositoryFilter=56&branchFilter=308%2C308), I'd say it's timing out in Mvc.FunctionalTests every 3 to 5 runs.

Got it. Let's see if we can get 5 straight passes in a row. First one seems to have passed. Gonna kick it again and see.

**Comment by captainsafia** [comment]
We had a good run but looks like this failed on the 3rd try:

image

The generated dump file was too large to store:

image

**Comment by BrennanConroy** [comment]
Looks like the same issue as the one caused by https://github.com/dotnet/runtime/pull/104126

**Comment by captainsafia** [comment]
Yep! This invalidates the data protection changes a culprit for the issue and bolsters the case that it's probably the cache-related changes in the runtime.

I'll close this PR out for now.

**Comment by BrennanConroy** [comment]
It doesn't invalidate the timeout issue though

**Comment by captainsafia** [comment]
> It doesn't invalidate the timeout issue being caused by data protection though

Is it worth retrying on here to validate that or should we wait until the cache fix flows through then shift gears to the timeout issue. Your logs PR might be more help there...

**Pull request closed without merging**
