### PR TITLE
Update cert that became valid and broke tests

### PR DESCRIPTION
**Pull request by HaoK**
We had a cert that wasn't supposed to valid until 5/17/2021, which passed, updated the cert to be valid in 10 years instead.  Will file another issue to generate these certs dynamically rather than relying on checked certs

### CODE REVIEW

**Comment by HaoK** [comment]
fyi @dotnet/aspnet-build all helix test runs will fail until this is fixed

**Review by blowdart — APPROVED** [review]

**Comment by HaoK** [comment]
In all branches...so let me know where this change needs to be merged

**Comment by HaoK** [comment]
https://github.com/dotnet/aspnetcore/issues/32813 to eventually fix the root issue (checked in certs) per @blowdart suggestion

**Review by Tratcher — APPROVED** [review]

**Comment by HaoK** [comment]
Fun stuff, we had two copies of these certs, the ones in shared/tests are the correct ones to update :)

**Comment by HaoK** [comment]
Test still failing only on ubuntu for some reason, skipping for now to unblock builds, will reenable in a future PR

**Comment by pranavkm** [comment]
@haok I'm going to merge this change once all the builds pass. There's a deadlock between getting this change in + getting the E2E changes which are both required to unblock the build. FYI @dotnet/aspnet-build

**Comment by dougbu** [comment]
Unless I'm off-base, these backports won't work yet. Should be a quick fix (ported from dotnet/runtime) but I haven't seen @wtgodbe's PR to do it yet.

**Comment by Tratcher** [comment]
@mkArtakMSFT any luck getting the github-actions[bot] to ignore team members? It seems to ignore Doug, but not Hao?

**Comment by HaoK** [comment]
So don't use the bot just manually port these?

**Comment by dougbu** [comment]
> So don't use the bot just manually port these?

For now, focus on preview5 please. Otherwise, we've got some time.

**Comment by HaoK** [comment]
This is already in preview5 I believe, I see it here: https://github.com/dotnet/aspnetcore/commit/2e20babb19f03e08278800a70c29728a6dd77b02

**Comment by dougbu** [comment]
> This is already in preview5 I believe,

👍 

Bottom line: I'd wait for @wtgodbe's fix before working about backports.

**Comment by halter73** [comment]
@HaoK I know this is old, but how did you decide on 10 years out instead of the original 50 years out (or longer)?

**Comment by HaoK** [comment]
I asked @blowdart for an appropriate expiration since he wrote these tests originally that's the number he suggested, I just randomly picked 50 to start since that seems safe enough that we would never have to worry about this cert test failing again :)

**Pull request merged**
