### PR TITLE
Add a few tests for generic JSInterop

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes https://github.com/aspnet/AspNetCore/issues/9061

### CODE REVIEW

**Comment by pranavkm** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=372132&view=ms.vss-test-web.build-test-results-tab&runId=11355818&resultId=100062&paneView=debug

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2859

**Comment by pranavkm** [comment]
Ping @SteveSandersonMS

**Review by SteveSandersonMS — APPROVED** [review]
Great!

**Pull request merged**
