### PR TITLE
ClientCollection builder methods returns with client

### PR DESCRIPTION
**Pull request by tibitoth**
Summary of the changes
 - `ClientCollection` `AddNativeApp`, `AddIdentityServerSPA` and `AddSPA` methods return with the client

Addresses #13435

### CODE REVIEW

**Comment by HaoK** [comment]
Closing and reopning to trigger new test runs

**Comment by tibitoth** [comment]
> Closing and reopning to trigger new test runs

I think I need to rebase/retarget these changes, am I right?

**Comment by HaoK** [comment]
master is fine, you might need to rebase against master though

**Comment by tibitoth** [comment]
@HaoK done and PR checks are fine now

**Review by HaoK — APPROVED** [review]

**Comment by HaoK** [comment]
Cool thanks @tibitoth

**Pull request merged**
