### PR TITLE
Quarantine CanRenderLargeComponentsWithServerRenderMode

### PR DESCRIPTION
**Pull request by captainsafia**

### CODE REVIEW

**Review by MackinnonBuck — APPROVED** [review]
🥲

**Comment by SteveSandersonMS** [comment]
@captainsafia @MackinnonBuck Does this bring the new product code's correctness into question, or is there a known reason for the test to fail that is separate from the product implementation?

**Comment by MackinnonBuck** [comment]
@SteveSandersonMS I haven't been able to reproduce the issue locally, but my guess is that the prerendered output is getting replaced with non-prerendered output in between the call to `Browser.FindElement()` and the subsequent access of the returned element's `Text` property, causing a `StaleElementReferenceException`. So I think this is more likely to be a test bug than a product bug.

**Comment by MackinnonBuck** [comment]
I wonder if it would be satisfactory to have the test render non-interactive components since we're specifically testing SSR functionality anyway.

**Pull request merged**
