### PR TITLE
Fix grammar in XML docs

### PR DESCRIPTION
**Pull request by martincostello**
Minor fixes to grammar in parameter documentation.

### CODE REVIEW

**Review by mkArtakMSFT — APPROVED** [review]
Thanks @martincostello.

**Comment by mkArtakMSFT** [comment]
@TanayParikh can you please look into the failing tests and get this merged? Thanks!

**Comment by mkArtak** [comment]
@TanayParikh can you please look into the failing test in the `aspnetcore-components-e2`? It's blocking multiple PRs. Feel free to quarantine it, if it's not straight forward to fix immediately. Thanks!

**Comment by TanayParikh** [comment]
> @TanayParikh can you please look into the failing test in the `aspnetcore-components-e2`? It's blocking multiple PRs. Feel free to quarantine it, if it's not straight forward to fix immediately. Thanks!

It looks like it may be a breaking change from a recent selenium update. Quarantined https://github.com/dotnet/aspnetcore/pull/38693.

**Pull request merged**
