### PR TITLE
Move .Components.Services namespace to .Components

### PR DESCRIPTION
**Pull request by adrianwright109**
Remove namespace `Microsoft.AspNetCore.Components.Services` and move all classes under this namespace to `Microsoft.AspNetCore.Components`.

Addresses #8892

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
Thanks @adrianwright109, this is great!

Once you're able to get the CI to pass, we can merge it right away.

**Comment by vertonghenb** [comment]
Also solves: https://github.com/aspnet/AspNetCore/issues/8494

**Comment by adrianwright109** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=137705&view=logs

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

I've triaged the above build.

**Comment by Eilon** [comment]
BTW this is the failure:

```
src\Components\Components\ref\Microsoft.AspNetCore.Components.netstandard2.0.cs(,): error : Generated code is not up to date in src/Components/Components/ref/Microsoft.AspNetCore.Components.netstandard2.0.cs.
PowerShell exited with code '1'.
```

**Comment by Eilon** [comment]
I think this info tells you how to fix it: https://github.com/aspnet/AspNetCore/blob/master/docs/ReferenceAssemblies.md

**Comment by adrianwright109** [comment]
I don't believe the build errors are related to my changes. Is there a way I can trigger a new build?

**Comment by Eilon** [comment]
Current failure seems to be some flaky test, so not due to your change:

```
/Users/vsts/agent/2.148.2/work/1/s/.dotnet/buildtools/korebuild/3.0.0-build-20190314.2/modules/vstest/module.targets(158,5): error : Test group Libuv.BindTests/netcoreapp3.0 failed with exit code '1'. [/Users/vsts/agent/2.148.2/work/1/s/.dotnet/buildtools/korebuild/3.0.0-build-20190314.2/KoreBuild.proj]
    16 Warning(s)
    1 Error(s)
```

**Comment by Eilon** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=137954&view=logs

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

I've triaged the above build.

**Comment by adrianwright109** [comment]
@SteveSandersonMS - The CI is now building.

Once this is merged into master I think @javiercn will need to rebase as #8911 has changes under the `Microsoft.AspNetCore.Components.Services` namespace which will no longer exist when this PR is merged.

**Comment by javiercn** [comment]
I merged my PR, so I'm going to be taking the patch on this PR an put it in a new PR along with more changes. It'll keep you as the author to recognize your contribution. I'll reference the new PR in here once I have it out.

Thanks for the contribution!

**Comment by javiercn** [comment]
New PR here https://github.com/aspnet/AspNetCore/pull/9001

**Comment by adrianwright109** [comment]
This PR is redundant as commits here have been moved into #9001 which has now been merged.

**Comment by javiercn** [comment]
@adrianwright109 Thanks for the contribution!

**Pull request closed without merging**
