### PR TITLE
Improve template Accessibility

### PR DESCRIPTION
**Pull request by ryanbrandenburg**
Fixes https://github.com/aspnet/AspNetCore/issues/12368.

**Description**
Improve accessibility of our templates by setting certain aria-attributes on elements which were identified as less accessible.

**Customer Impact**
This change improves accessibility of the templates, specifically for people using screen-readers.

**Regression?**
No, it was never the case that these elements were accessible.

**Risk**
Very low.

### CODE REVIEW

**Comment by ryanbrandenburg** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=295863.

**Comment by mkArtakMSFT** [comment]
Approved by tactics

**Review by mkArtakMSFT — APPROVED** [review]

**Review by dougbu — APPROVED** [review]
I haven't read up on `aria-live` or `aria-label`. If the accessibility folks agree w/ these additions, everything looks good to me.

**Comment by ryanbrandenburg** [comment]
`aria-live` lets a screen-reader know that it should check the given element for changes, which otherwise a user would not be alerted of. On double checking, `aria-label` is not the prefered solution here, but `aria-labelledby`, since we already have an element which labels it, just slightly about it in the context.

**Pull request merged**
