### PR TITLE
Make the test input a bit more reasonable

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes https://github.com/aspnet/AspNetCore-Internal/issues/2626

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @aspnet/build. We made this change in master: https://github.com/aspnet/AspNetCore/pull/11067.

**Review by natemcmaster — APPROVED** [review]
Changes look fine. @Pilchie this is a test-only fix, so is this a "tell" for shiproom? Might be good to review the related corefx bug in more detail to see if there is a customer-facing issue here, too.

**Comment by pranavkm** [comment]
CoreFx bug for reference: https://github.com/dotnet/corefx/issues/38455

**Comment by anurse** [comment]
> this is a test-only fix, so is this a "tell" for shiproom?

That's my understanding. You can merge (since the branch is open) but email `netcoreship` with the PR and brief context (couple of sentences) of the fix.

**Comment by Pilchie** [comment]
Yep, and I'll bring it up with CoreFx folks in shiproom today.  Can someone give me details on the environments where we're seeing problems?

**Comment by pranavkm** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=220385&view=logs&jobId=f31c9f97-4411-58e7-49ac-fc73f645e6b6

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2181

**Comment by pranavkm** [comment]
@Pilchie the issue is specific to Ubuntu machines. I reproduced this on 16.04, but it's the libicu64 version that surfaces it.

**Comment by Pilchie** [comment]
Thanks - we're good to go ahead and merge when you're ready.

**Comment by pranavkm** [comment]
@aspnet/build this is good to merge now.

**Review by mkArtakMSFT — APPROVED** [review]

**Pull request merged**
