### PR TITLE
[NO MERGE] use a hacky way to run all the tests using new FileStream implementation

### PR DESCRIPTION
**Pull request by adamsitnik**
Please ignore this PR, I just want to check if the most recent changes have not broken anything in ASP.NET **before** we enable them by default.

### CODE REVIEW

**Comment by davidfowl** [comment]
cc @sebastienros

**Comment by BrennanConroy** [comment]
FYI, I don't think this did what you wanted it to. You need to include the file in the build output otherwise it wont be included in the helix payloads and the tests wont run with this file.

You can look at https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-pull-31441-merge-aaf0039304e34f65bb/InMemory.FunctionalTests--net6.0/console.ff293fe0.log?sv=2019-07-07&se=2021-04-21T10%3A22%3A02Z&sr=c&sp=rl&sig=bLqpPJuMj8nDmM%2BvSgHzrfD%2FcbNe04iiLWPMyuWM54k%3D where we output the files in the directory of the helix payload and that file isn't included.

**Comment by BrennanConroy** [comment]
False alarm, looks like the eng folder got included, and the Directory.Build.props points to eng/.

**Comment by adamsitnik** [comment]
@BrennanConroy thank you for ensuring that it does what I was hoping it does!

**Comment by adamsitnik** [comment]
The change in runtime repo (https://github.com/dotnet/runtime/pull/50166) has been merged, I am closing the PR.

**Pull request closed without merging**
