### PR TITLE
Add missing app namespace to server-side Blazor template

### LINKED ISSUE #10239: Add missing @using in _Imports.razor to server-side Blazor template for the app namespace
The server-side Blazor app should include an `@using` in *_Imports.razor* for the app's namespace.

### PR DESCRIPTION
**Pull request by danroth27**
Fixes #10239

### CODE REVIEW

**Comment by danroth27** [comment]
This came up in the Blazor tutorial: https://github.com/aspnet/AspNetCore.Docs/issues/12404

**Review by rynowak — APPROVED** [review]
Just an issue with server-side?

**Comment by danroth27** [comment]
@rynowak The other Blazor templates look good:

https://github.com/aspnet/AspNetCore/blob/master/src/Components/Blazor/Templates/src/content/BlazorStandalone-CSharp/_Imports.razor#L6

https://github.com/aspnet/AspNetCore/blob/master/src/Components/Blazor/Templates/src/content/BlazorHosted-CSharp/BlazorHosted-CSharp.Client/_Imports.razor#L6

**Comment by danroth27** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=188726

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2521

**Pull request merged**
