### PR TITLE
Remove 2.2 package from the site extensions bundle

### PR DESCRIPTION
**Pull request by dougbu**
- prepare to include 5.0.0 content; but wait 'til 6.0.0 targets `net6.0`

### CODE REVIEW

**Comment by dougbu** [comment]
Split this out of #24983 because it's not really part of rebranding

**Review by wtgodbe — APPROVED** [review]

**Review by BrennanConroy — APPROVED** [review]

**Comment by dougbu** [comment]
Restarting but likely won't pass until #25650 merges

**Comment by dougbu** [comment]
@wtgodbe I think we're still seeing NU5118 errors even though 76fbd1a2831ae0d8c73afd2f3c7d8c531223a8b8 is in this branch. Seem to affect aspnetcore-quarantined-pr more than aspnetcore-ci e.g. https://dev.azure.com/dnceng/public/_build/results?buildId=809645&view=logs&j=48c285a2-daf4-5ecb-cb99-42232769ca29&t=1c30c545-4674-57a0-c50f-14816b5373e6&l=2122 What gives❔ For example, is aspnetcore-quarantined-pr not using the merge commit from GitHub❔

**Comment by wtgodbe** [comment]
Crap - the tree from the quarantined test jobs does appear to have https://github.com/dotnet/aspnetcore/commit/76fbd1a2831ae0d8c73afd2f3c7d8c531223a8b8, but doesn't produce binlogs. I'll see if I can find another public build since my commit that has the failures

**Comment by wtgodbe** [comment]
This one failed with the same error: https://dev.azure.com/dnceng/public/_build/results?buildId=809582&view=results. Looks like it isn't fully fixed yet. Looking at the logs now.

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/pull/25785

**Comment by NTaylorMullen** [comment]
Hmm public builds are now failing with:
image

Not expected is it?

**Comment by dougbu** [comment]
@NTaylorMullen where are you seeing that NU1102 error❔ I'm not seeing it in https://dev.azure.com/dnceng/public/_build/results?buildId=811653 and that built the site extension bundle and included this change.

**Comment by dougbu** [comment]
(Side note: Please paste wide error message text as text. Makes it easier to scroll.)

**Comment by NTaylorMullen** [comment]
Looks like the last 4 builds failed according to this: https://dev.azure.com/dnceng/public/_dashboards/dashboard/dfffdaf2-ad65-4a1c-a6b8-202469820e65
image

Failed builds:
- https://dev.azure.com/dnceng/public/_build/results?buildId=811575&view=logs&j=1b89928a-2219-5ef9-602f-f95beb3da4dc&t=39263dad-2be6-5f40-bde4-1bab0d7931b4
- https://dev.azure.com/dnceng/public/_build/results?buildId=811427&view=logs&j=1b89928a-2219-5ef9-602f-f95beb3da4dc&t=39263dad-2be6-5f40-bde4-1bab0d7931b4
- https://dev.azure.com/dnceng/public/_build/results?buildId=810924&view=logs&j=1b89928a-2219-5ef9-602f-f95beb3da4dc&t=39263dad-2be6-5f40-bde4-1bab0d7931b4
- https://dev.azure.com/dnceng/public/_build/results?buildId=810845&view=logs&j=1b89928a-2219-5ef9-602f-f95beb3da4dc&t=39263dad-2be6-5f40-bde4-1bab0d7931b4

**Comment by NTaylorMullen** [comment]
These seem to be failing for similar reasons too:
image

**Comment by dougbu** [comment]
Ah, this is an oddity due to a separate change I made in the release/5.0-rc2 branch. All of the builds you pointed out were on that branch but the change in this PR went into master.

Looking&hellip;

**Comment by dougbu** [comment]
@mmitche we updated Microsoft.AspNetCore.AzureAppServices.SiteExtension.2.2 to 2.2.5 in that release before shutting down 2.2.x. I saw the 2.2.5 package but it must have been in the https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json feed, which isn't used in this branch. Could you copy over the 2.2.5 package to the https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json feed please❔ That'll unblock our builds immediately.

**Comment by dougbu** [comment]
Thanks for the fix @mmitche❕

**Pull request merged**
