### PR TITLE
Do not always build the targeting pack archives

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by wtgodbe** [comment]
Would be interested to know why this didn't surface before servicing builds, but that's a question for later

**Review by wtgodbe — APPROVED** [review]

**Comment by wtgodbe** [comment]
CC @JunTaoLuo @dougbu

**Comment by dougbu** [comment]
This may work but is likely glossing over a deeper problem.

----
`$(OnlyPackPlatformSpecificPackages)` is no longer honoured for the .Ref package. The main problem is at https://github.com/aspnet/AspNetCore/blob/release/3.0/src/Framework/ref/Microsoft.AspNetCore.App.Ref.csproj#L211

Where before `$(OnlyPackPlatformSpecificPackages)` ensured `$(IsPackable)` was `false` for the generic .Ref project and therefore the package wasn't built, the new `$(IsTargetingPackPatching)` property takes precedence.

@JunTaoLuo @wtgodbe why do _both_ `$(IsTargetingPackPatching)` and `$(IsTargetingPackBuilding)` exist? And, if they're both necessary, why aren't both used to set `$(IsPackable)` earlier in the .Ref project ([here](https://github.com/aspnet/AspNetCore/blob/release/3.0/src/Framework/ref/Microsoft.AspNetCore.App.Ref.csproj#L7-L8))?

----
@mmitche I recommend changing https://github.com/aspnet/AspNetCore/blob/release/3.0/src/Framework/ref/Microsoft.AspNetCore.App.Ref.csproj#L7-L8 (to include `$(IsTargetingPackPatching)` in the condition) instead of anything in Publishing .props. Also back out the use of `$(IsTargetingPackPatching)` at https://github.com/aspnet/AspNetCore/blob/release/3.0/src/Framework/ref/Microsoft.AspNetCore.App.Ref.csproj#L211

We can remove `$(IsTargetingPackPatching)` later&hellip;

**Comment by wtgodbe** [comment]
`IsTargetingPackPatching` really means "Is this 3.0.1?", we use it for some special logic in ResolveReferences.targets

**Comment by mmitche** [comment]
@wtgodbe @JunTaoLuo @dougbu I'll leave it to you to decide whether this is okay to take or whether another fix is needed. Merge as desired.

**Comment by wtgodbe** [comment]
@dougbu I'm confused by your suggestion - `IsTargetingPackPatching` is just based off of whether or not we're building 3.0.1. Adding it as a condition to https://github.com/aspnet/AspNetCore/blob/release/3.0/src/Framework/ref/Microsoft.AspNetCore.App.Ref.csproj#L7-L8 wouldn't change the behavior

**Comment by wtgodbe** [comment]
Ah, never mind, I missed the part about https://github.com/aspnet/AspNetCore/blob/602cb1dea59751a1297d674cddf7f0729c23e6ca/Directory.Build.targets#L5. I think all we need to do is back out `IsTargetingPackPatching` from https://github.com/aspnet/AspNetCore/blob/release/3.0/src/Framework/ref/Microsoft.AspNetCore.App.Ref.csproj#L211, as the `IsPackable` setting from https://github.com/aspnet/AspNetCore/blob/release/3.0/src/Framework/ref/Microsoft.AspNetCore.App.Ref.csproj#L7-L8 will be overwritten by d.b.t. Does that sound correct?

**Comment by dougbu** [comment]
> Does that sound correct?

Yup, glad I wasn't delusional. Let me know if you want me to create another PR for that one-liner. Not sure reusing this PR makes sense.

**Comment by mmitche** [comment]
I've changed this PR to use will's suggestion and run an internal build to test.

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
thanx @mmitche❕❕

**Review by JunTaoLuo — APPROVED** [review]
Rerunning flaky test.

**Pull request merged**
