### PR TITLE
Remove preview LangVersion from empty project template

### PR DESCRIPTION
**Pull request by halter73**
Addresses #33813

### CODE REVIEW

**Review by DamianEdwards — APPROVED** [review]

**Review by davidfowl — APPROVED** [review]
I assume we don't have the SDK yet.

**Comment by DamianEdwards** [comment]
This doesn't need to be merged anymore, it was [already removed](https://github.com/dotnet/aspnetcore/commit/9f71b1af0883a3834c151cbff078ff03a78d53b7#diff-5db70304ceb6f76c5a4fc9831259d7dea2b11802a40ca239f9dc781858dd9d03).

**Pull request closed without merging**
