### PR TITLE
Add last class last

### PR DESCRIPTION
**Pull request by vanillajonathan**
This changes the order of the CSS classes so that the last class added gets appended to the end instead of prepended to the start.

This makes it behave more as expected as well as more in line with the documentation which states:
> If there are already CSS classes on the tag then a space character and the new class will be appended to the existing list.

Previously:
```cs
var button = new TagBuilder("input");
button.AddCssClass("btn");
button.AddCssClass("btn-success");
```
would result in:
```html
<input class="btn-success btn" ... />
```

With this patch the result is:
```html
<input class="btn btn-success" ... />
```

### CODE REVIEW

**Comment by captainsafia** [comment]
@vanillajonathan Thanks for this contribution. The change looks good, however, there are some test failures that need to be resolved before we can merge.

You can find a list of the failing tests at https://github.com/dotnet/aspnetcore/pull/31711/checks?check_run_id=2325026782.

**Comment by vanillajonathan** [comment]
Oh, shoot!
This don't work, and I don't know why!

I tried looking in:
- AspNetCore/src/Mvc/test/Mvc.FunctionalTests/compiler/resources/BasicWebSite.Area1.RemoteAttribute_Home.Create.html 
- AspNetCore/src/Mvc/test/Mvc.FunctionalTests/compiler/resources/BasicWebSite.Root.RemoteAttribute_Home.Create.html 

It says it expects:

    <span class="field-validation-valid text-danger" data-···

And that's how it looks in those files, but it says it's actually:

     <span class="text-danger field-validation-valid" data-···

Can someone help me out?

**Comment by vanillajonathan** [comment]
@captainsafia Can you or someone help me out?

**Comment by campersau** [comment]
The expected values come from those files, that's why they are the same. You need to update the `RemoteAttribute_Home.Create.html` files and change the order of the classes to match the actual value.

E.g. change the class here to `text-danger field-validation-valid`:
https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Mvc/test/Mvc.FunctionalTests/compiler/resources/BasicWebSite.Root.RemoteAttribute_Home.Create.html#L36
And so on as you have already done so with the `HtmlGenerationWebSite.HtmlGeneration_Home.Order.Encoded.html` file.

**Comment by vanillajonathan** [comment]
Thank you @campersau ! 🙏

**Review by captainsafia — APPROVED** [review]

**Comment by pranavkm** [comment]
@vanillajonathan there's still a few more tests failing.

**Comment by vanillajonathan** [comment]
@campersau, I changed, but now it says:

```
Assert.Equal() Failure
                                 ↓ (pos 1198)
Expected: ···       <span class="field-validation-valid text-danger" data-···
Actual:   ···       <span class="text-danger field-validation-valid" data-···
                                 ↑ (pos 1198)
```

Maybe I changed it from right to wrong, or changed the wrong file, I don't know.

**Comment by campersau** [comment]
@vanillajonathan It was the correct file but there are two of them as you have also mentioned here https://github.com/dotnet/aspnetcore/pull/31711#issuecomment-820743668.

Here is the other one:
https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Mvc/test/Mvc.FunctionalTests/compiler/resources/BasicWebSite.Area1.RemoteAttribute_Home.Create.html#L36

**Comment by captainsafia** [comment]
@vanillajonathan Looks like there is still a couple more test failures that need template updates.

You can run the tests locally instead of relying on CI which might be faster for you.

Clone the repo then executing the following should do the trick.

```
$ source activate.sh // or ./activate.ps1
$ cd src/Mvc/test/Mvc.FunctionalTests
$ dotnet test
```

**Comment by vanillajonathan** [comment]
It seems that when I edited the files on the GitHub website it appended a new to end of the files and that is why the test fails.

@captainsafia 
The `dotnet test` command fails, it says there is a certificate error for dotnet.myget.org

**Comment by captainsafia** [comment]
> @captainsafia
> The dotnet test command fails, it says there is a certificate error for dotnet.myget.org

Hm. We don't use the MyGet servers anywhere in the repo so this is a little surprising. You can check the [build instructions](https://github.com/dotnet/aspnetcore/blob/3e46e68821157961e3b49359068447538bead6b3/docs/BuildFromSource.md) to confirm that you've got the right setup.

> It seems that when I edited the files on the GitHub website it appended a new to end of the files and that is why the test fails.

You can always try making the changes locally and building and continue to rely on CI to test.

**Comment by captainsafia** [comment]
@vanillajonathan So close!

Getting the local tests working will certainly improve the dev loop for this. If the option is available to you, you can try making the modifications using GitHub codespaces.

image

It'll open the repo in a cloud-based VS Code instance. Once you've check out the change you can do the following to run the tests:

```
$ ./restore.sh
$ cd src/Mvc
$ ./build.sh
$ source ../../activate.sh
$ cd test/Mvc.FunctionalTests
$ dotnet test
```

**Review by captainsafia — APPROVED** [review]

**Comment by vanillajonathan** [comment]
@captainsafia My patch-1 was from my old vanillajonathan/aspnetcore that was outdated, so after updating it I got rid of the MyGet errors, but then I ran into some other errors.

The codespaces thing seems great, but as it is in beta, I do not have access to it yet.

I had some problems with VS Code reformatting the document on save, hence removing whitespace. Editing the files in gedit I had an issue with gedit appending a newline at the end of the file. I was able to find a command in VS Code to save without formatting-on-save.

Thank you and @campersau for all the help and encouragement!

**Pull request merged**
