### PR TITLE
Use WORKITEM_ROOT instead of CORRELATIONPAYLOAD for helix workloads

### PR DESCRIPTION
**Pull request by jkotalik**
Better way of fixing https://github.com/aspnet/AspNetCore/pull/9186, but not certain it will work yet. CORRELATION_PAYLOAD is readonly on these new helix payloads.

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
Helix build succeeded -- as did the main AzDO pipeline. So, this looks good.

But why are there no test results in the Helix run? That seems pretty major though it's not a new problem. See if there's a bug tracking that gap or create one please @jkotalik.

/cc @HaoK?

**Comment by HaoK** [comment]
Maybe still need to update a few other env variables like `DOTNET_CLI_HOME="$HELIX_CORRELATION_PAYLOAD/home"`

Looks like its still trying to write to the read only directory
```
System.IO.IOException: Read-only file system
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateDirectory(String path)
   at Microsoft.DotNet.Configurer.FirstTimeUseNoticeSentinel.CreateIfNotExists()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean hasSuperUserAccess, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Running non-flaky tests.
```

**Comment by jkotalik** [comment]
Receiving some bad image pulls (https://github.com/dotnet/core-eng/issues/5883).

**Comment by jkotalik** [comment]
Minus the IISExpress failures, this PR is working.

**Pull request closed without merging**
