### PR TITLE
Improved for loop for faster negotiate response

### PR DESCRIPTION
**Pull request by BrennanConroy**
Started auditing SignalR's `for`/`foreach` loops to look for obvious perf gains and found this one immediately.

Before:

Method |     Mean |    Error |   StdDev |   Median |        Op/s |  Gen 0 | Allocated |
--------------------------------- |---------:|---------:|---------:|---------:|------------:|-------:|----------:|
WriteResponse_MemoryBufferWriter | 595.1 ns | 14.50 ns | 33.90 ns | 583.1 ns | 1,680,415.1 | 0.0048 |     144 B |

After:

Method |     Mean |    Error |   StdDev |        Op/s |  Gen 0 | Allocated |
--------------------------------- |---------:|---------:|---------:|------------:|-------:|----------:|
WriteResponse_MemoryBufferWriter | 503.4 ns | 9.909 ns | 14.21 ns | 1,986,464.1 | 0.0019 |      64 B |

### CODE REVIEW

**Review by davidfowl — APPROVED** [review]

**Comment by BrennanConroy** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=245276

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2585

**Comment by anurse** [comment]
@BrennanConroy can you confirm if this was in before branching? (Because I wasn't here). Just want to make sure the milestone is correct.

**Comment by BrennanConroy** [comment]
I'll check, but I'm 90% sure it is since I merged it early in the morning

**Pull request merged**
