### PR TITLE
Do not configure nullablePublicOnly for tests and samples

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Review by dougbu — COMMENTED** [review]
@pranavkm what is the purpose of this PR❔ It's unclear whether your aim is to
1. allow projects to extend the compiler features
2. scope the `nullablePublicOnly` feature to a subset of projects
3. both

**Comment by dougbu** [comment]
Somewhat separately, I recommend emptying the default verbiage in the description if you're going to ignore it

**Comment by pranavkm** [comment]
The goal is to avoid configuring a compiler feature for samples and tests.

**Review by dougbu — APPROVED** [review]
Well, alright then 😺 

Let's hope `BasicTestApp` (our troublesome test app ☹️) builds when you retry the failed job.

**Pull request merged**
