### PR TITLE
Pass ReadOnlySequence<byte> via in

### PR DESCRIPTION
**Pull request by benaadams**
Update on https://github.com/aspnet/AspNetCore/pull/7953

Contributes to https://github.com/aspnet/AspNetCore/issues/7180

### CODE REVIEW

**Comment by benaadams** [comment]
Rebased

**Review by jkotalik — APPROVED** [review]

**Comment by anurse** [comment]
If we can get a nice clean build today @jkotalik , go ahead and update the milestone to preview7 and merge. Otherwise we'll have to hold for preview8 post-branching.

**Comment by jkotalik** [comment]
I'm going to wait on https://github.com/aspnet/AspNetCore/pull/11675 being merged as it's a high priority for preview7 (don't want to hit merge conflicts).

**Comment by jkotalik** [comment]
Thanks @benaadams as always.

**Pull request merged**
