### PR TITLE
Fix license

### PR DESCRIPTION
**Pull request by Eilon**

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
WFM

**Comment by dougbu** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=130590

**Comment by ryanbrandenburg** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

I've triaged the above build.

**Comment by Eilon** [comment]
Sent:
* https://github.com/aspnet/EntityFrameworkCore/pull/15131
* https://github.com/aspnet/Extensions/pull/1297
* https://github.com/aspnet/AspNetCore-Tooling/pull/358

**Pull request merged**
