### PR TITLE
Updating titles in project templates

### PR DESCRIPTION
**Pull request by sayedihashimi**
Issue #25576 

Updating titles in project templates because in Visual Studio the templates will be showing the templates directly in the New Project Dialog instead in the One ASP.NET dialog.

In this PR I have updated the English titles. For localized strings we will need to get those from the localization team. I believe we are not setup for that to be automated here.

I think we should merge the English strings because they are the most used, and for other locales we will show the old localized names for now. If it's difficult to get those localized, I can work with @phenning to see if we can localize those files this time.

I will send another PR once I have the updated icons.

@mkArtakMSFT @Pilchie @timheuer @KathleenDollard

### CODE REVIEW

**Comment by sayedihashimi** [comment]
Forgot to mention, when the build completes I will install the updated templates and verify them in Visual Studio 2019.

**Comment by timheuer** [comment]
RE: localization -- since you are adding "ASP.NET Core" to everything, I'm not sure that is a localized 'brand' name anyway?  Agree to merge english for now and take loc change in next release.

**Comment by sayedihashimi** [comment]
Can someone tell me where I can find the .nupkg file from this PR? I looked through the first two checks here, but didn't see anything like a .nupkg.

@phenning can you test this as well? I'll try it out when I can figure out where the .nupkg file is, but would also like for you to take a look.

**Comment by sayedihashimi** [comment]
Replaced by https://github.com/dotnet/aspnetcore/pull/25630

**Pull request closed without merging**
