### PR TITLE
Callsite rendermodes

### LINKED ISSUE #48793: RenderModeServer doesn't work when applied to App component
Repro steps:

- Install .NET 8 Preview 5
- Create a Blazor Web App
- Enable server interactivity by adding `AddServerComponents()`
- Add `@attribute [RenderModeServer]` to the `App` component

Expected result: The entire app renders interactively using Blazor Server
Actual result:

```
Uncaught (in promise) Error: Found malformed component comment at Blazor:{"sequence":0,"type":"server","prerenderId":"40b364ab2f6c4a128a60a3540610ab4b","descriptor":"CfDJ8F4wj4CPUDJJpKiv/dArKQrAAIXkDXV447RobZzMe9NoVPi13ySUCzRMCnR\u002BuG2VqaE7yhBykOgcr6Wv5VC6uuA58dahIttUOgLWTTZNR0rPCAldAYQJQmdu3qO6mdkHr6KKBRbe9udw9hI27AgCHp087lrYE81BmVVk2dv0SihheePH8aPqh/VtKhsgUwS6WA0FFiCuvHZoZb2hKz4HBIFpp7dbjMHL75GhCz5tjZczoJEZm2o\u002BV/EJWrwQJD0f05t8oMehODNNSu0svvsx\u002BZ5IBUF5WBuRSqH8cpKmoV2mMMvZm1PI6F\u002BCNBrl2leG0GnSp1zF/U9GkVN0GleOFDkSpa0T8kdNfLX198A7er7V"}
    at vr (blazor.web.js:1:131254)
    at yr (blazor.web.js:1:129626)
    at blazor.web.js:1:128924
    at fr (blazor.web.js:1:129096)
    at blazor.web.js:1:148075
    at Co (blazor.web.js:1:153116)
    at blazor.web.js:1:153281
    at blazor.web.js:1:153287
```

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
# Add callsite rendermodes for Blazor full-stack web apps

Allows Blazor components to have a rendermode specified at the usage site. Among other use cases, this allows us to simplify the default project template by removing an otherwise pointless wrapper component.

We want to do this in preview 6 (to get customer feedback) but didn't land it in time for the normal code-complete cutoff.

## Description

We already support specifying a fixed rendermode on a component type, e.g.:

```razor
@page "/my-component"
@attribute [RenderModeServer]

<h1>Here's some interactive stuff</h1>
...
```

However, it's commonly also desirable to specify a rendermode at the callsite for a component, e.g.:

```razor
<h1>Here's some interactive stuff</h1>
<Counter @rendermode="@RenderMode.Server" />
```

This allows the consumer to vary the rendermode according to their own preferences without having to do so on the parent component. In the default project template, it means that developers can have an interactive `<HeadOutlet>` just by writing:

```razor
<HeadOutlet @rendermode="@RenderMode.Server" />
```

... whereas without this change, they have to define some new component e.g., called `AppHeadOutlet` containing just:

```razor
@attribute [RenderModeServer]
<HeadOutlet />
```

... and then place `<AppHeadOutlet />` at the intended call site.

Fixes #48793

## Customer Impact

Allows the default migration experience from Blazor Server/WebAssembly to the new full-stack architecture to be more streamlined and not involve a weird, pointless-seeming wrapper component.

## Regression?

- [ ] Yes
- [x] No

[If yes, specify the version the behavior has regressed from]

## Risk

- [ ] High
- [ ] Medium
- [x] Low

Low because this only impacts completely new code using the new functionality. It shouldn't be possible for this to break existing apps.

## Verification

- [x] Manual (required)
- [x] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS do you want to retarget this to preview6? Or will there be a port PR?

**Comment by javiercn** [comment]
@SteveSandersonMS overall looks good.

Are we checking at some point that users don't intermingle server/webasembly components?

**Comment by SteveSandersonMS** [comment]
> Are we checking at some point that users don't intermingle server/webasembly components?

Yes, both the server and webassembly renderers reject instructions to render the other type of component.

**Review by javiercn — APPROVED** [review]

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS feel free to merge!

**Pull request merged**
