### PR TITLE
[Blazor] Fix redirect to login

### PR DESCRIPTION
**Pull request by javiercn**
Addresses https://github.com/aspnet/AspNetCore-ManualTests/issues/1557

### CODE REVIEW

**Review by TanayParikh — APPROVED** [review]

**Review by TanayParikh — APPROVED** [review]

**Comment by Pilchie** [comment]
Approved for .NET 7 RC2.

**Comment by dougbu** [comment]
@javiercn please use `@aspnet-admins` when requesting servicing merges.

**Pull request merged**
