### PR TITLE
Backport Blazor Fix Missing EventArgs.Type (#38792) to 6.0.2

### LINKED ISSUE #38782: Blazor - MouseEventArgs.Type property is always null in .NET 6.0
Hi,
In my Blazor .NET 5.0 project, I used one delegate function for several mouse events, e.g .: 

@code {
async Task OnMouseEvent(MouseEventArgs e)    {
        switch (e.Type)
        {
            case "click": 
            //...
            break;
            case "dblclick": 
            //...
            break;
            case "mousemove": 
            //...
            break;
//...

After upgrading the project to .NET 6.0, the Type property of MouseEventArgs parameter is always null.
Is it intentional or is it a bug?

Thanks a lot

### PR DESCRIPTION
**Pull request by TanayParikh**
# HTML DOM Events Missing Event `Type`

A regression in .NET 6 caused HTML DOM Events to provide a `null` `*EventArgs.Type` when an event handler was invoked. 

## Description

The `Type` represents the specific event type from a general event source. For instance, the `MouseEventArgs` have types of `click`, `mouseover`, `mouseout`, `mousemove`, etc. This `Type` is currently `null` in .NET 6. 

Fixes #38782

## Customer Impact

This issue was customer reported (via #38782). If customers wish to have a single event handler for multiple events from the same source (ex. one event handler for `@onclick`, `@onmouseover`) they can't currently do so as the `MouseEventArgs.Type` is null. With this fix, the `MouseEventArgs.Type` would be `click` and `mouseover` respectively so customers may add appropriate logic to react to the events.

Impacted event args are:
- `MouseEventArgs`
- `TouchEventArgs`
- `ClipboardEventArgs`
- `FocusEventArgs`
- `ProgressEventArgs`
- `ErrorEventArgs`
- `KeyboardEventArgs`

## Regression?

- [x] Yes
- [ ] No

Regression from behavior in .NET 5. 

## Risk

- [ ] High
- [ ] Medium
- [x] Low

This is a low risk change as the fix simply extends the `*EventArgs` definitions to include the `type` property which was previously missing.

## Verification

- [x] Manual (required)
- [x] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

### CODE REVIEW

**Comment by TanayParikh** [comment]
`aspnetcore-components-e2e` pipeline is failing due to missing CI updates we've implemented in the `main` branch: https://github.com/dotnet/aspnetcore/pull/38693 & https://github.com/dotnet/aspnetcore/pull/38704. Backporting those fixes as well in a saperate PR.

**Comment by TanayParikh** [comment]
Update: This has been servicing approved, will have to wait till Tuesday to merge https://github.com/dotnet/aspnetcore/pull/38815, after which this PR can be merged in as well.

**Review by pranavkm — APPROVED** [review]
Looks like a e2e test failure.

**Comment by TanayParikh** [comment]
> #38815

Yep, the release branch in missing the CI fixes made in main. Backporting those via https://github.com/dotnet/aspnetcore/pull/38815.

**Pull request merged**
