### PR TITLE
Switch to the new Server20H2 queue

### PR DESCRIPTION
**Pull request by Tratcher**
Testing out the new 20H2 queue that should have been deployed yesterday. This should bring our testing up to the latest supported Windows release.

See [here](https://github.com/dotnet/core-eng/issues/11474#issuecomment-746499001) for details (internal).

### CODE REVIEW

**Comment by Tratcher** [comment]
@jkotalik three IIS tests failed due to shutdown hangs, but that's a lot fewer than I was expecting 😁.

**Comment by jkotalik** [comment]
Are tests now skipped due to the IIS/IISExpress shutdown issues we've been seeing?

**Comment by Tratcher** [comment]
> Are tests now skipped due to the IIS/IISExpress shutdown issues we've been seeing?

Many are, but it seems like we missed a few.

**Review by wtgodbe — APPROVED** [review]

**Review by jkotalik — APPROVED** [review]

**Pull request merged**
