### PR TITLE
Add ignored http headers to SpaProxy

### PR DESCRIPTION
**Pull request by ChristopherHaws**
Ignore **Connection** header when using `UseProxyToSpaDevelopmentServer`

Addresses #16797

### CODE REVIEW

**Review by javiercn — COMMENTED** [review]
The original issue only mentions the Connection header, why are we also ignoring cookies?

**Comment by mkArtakMSFT** [comment]
Thanks for your PR, @ChristopherHaws.
`Cookie` headers can be important in some cases, and we don't feel that it's the right thing to do to always remove these. For the `Connection` headers, we like your proposal. Can you tweak your PR to remove only the `Connection` headers?
As for the `Cookie` header, you can have a custom middleware registered in the middleware pipeline, which can remove the `Cookie` header for your specific application.

**Comment by ChristopherHaws** [comment]
I have removed the cookie header from the `NotForwardedHttpHeaders`.

**Review by javiercn — APPROVED** [review]
Changes look good. Seems like the build got stuck somewhere, re-triggered to see what happens. Will merge once it passes.

**Comment by mkArtakMSFT** [comment]
Thanks for your contribution, @ChristopherHaws.

**Pull request merged**
