### PR TITLE
Selenium updates.

### PR DESCRIPTION
**Pull request by mitchdenny**
Selenium updates (build ops)

### CODE REVIEW

**Comment by wtgodbe** [comment]
Javier is working on a broader update in https://github.com/dotnet/aspnetcore/pull/50809 - @javiercn should this PR be closed?

**Comment by javiercn** [comment]
@wtgodbe I believe the next selenium update requires more work. I do believe that the clients in Helix are too old for it, so while my changes work locally, they don't work on CI. 

I took a stab at making it work on https://github.com/dotnet/aspnetcore/pull/50809 but it's not something I currently have cycles for, so either someone on build ops try to figure out the CI bit or we'll have to wait until it gets updated on Helix machines.

It will be good if we can somehow get updated versions of this on helix machines. Do you have any idea on how to do that @wtgodbe?

**Comment by wtgodbe** [comment]
@javiercn what exact components need to get updated, and to what versions? The helix images are generally controlled by @dotnet/dnceng

**Comment by dkurepa** [comment]
@javiercn let us know if we you need us to update some packages. You can see a list of images and artifacts installed on them at https://helix.dot.net/

**Comment by javiercn** [comment]
@dkurepa I don't have any idea on how to find the chromedriver that gets placed on the image. I've looked at the image we are technically using, but I don't know where else to look inside helix.dot.net

image

**Comment by dkurepa** [comment]
Ah, this image isn't controlled by us, this is a microsoft hosted agent. You can see the installed software at https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md

**Pull request closed without merging**
