### PR TITLE
Update appSettings.json to have a comment for org auth cases

### PR DESCRIPTION
**Pull request by sayedihashimi**
I have modified the `appSettings.json` to have a comment that will help users configure Azure settings that are needed for org auth scenarios.

Note: the FWLink that the comment points to will be updated before these are released.

Before merging we will need to test the nuget packages that come out of the build. @phenning and @vijayrkn will assist in testing.

### CODE REVIEW

**Comment by vijayrkn** [comment]
@sayedihashimi - Main should be targeting .NET 6.0, so this change will have to be re-targeted to the right branch. @pranavkm ?

**Comment by sayedihashimi** [comment]
I wasn't sure which branch to target. I can update this PR, or create a new one, once I know the correct branch to target.

**Comment by vijayrkn** [comment]
I would assume this will have to target the 'release/5.0' branch but will wait for @pranavkm to confirm.

**Comment by captainsafia** [comment]
@sayedihashimi Correct -- if you'd like this to be released for .NET 5, it'll need to target `release/5.0` and go through the servicing process.

**Comment by sayedihashimi** [comment]
Thanks, I will get it updated.

**Comment by sayedihashimi** [comment]
New PR submitted https://github.com/dotnet/aspnetcore/pull/29610

**Pull request closed without merging**
