### PR TITLE
Add CreateXmlReader overload - adds Type parameter

### PR DESCRIPTION
**Pull request by bfriesen**
This change allows inheritors of `XmlSerializerInputFormatter` to return a different `XmlReader` depending on the type being serialized. For example, an inheritor could return XSD-validating readers that validate against one schema or another (or perhaps not validate at all), depending on the value of the type parameter.

For backwards compatibility, the original `CreateXmlReader` method is left intact - the base implementation of the new overload simply calls the original `CreateXmlReader` method.

This pull request does not include any additional tests because no functionality has been changed. Also, there were no tests around the original `CreateXmlReader` method.

### CODE REVIEW

**Comment by pranavkm** [comment]
@bfriesen the changes look good. Could you sign the CLA - https://github.com/aspnet/AspNetCore/pull/13302#issuecomment-523202058?

**Comment by bfriesen** [comment]
@pranavkm The legal team at my company hasn't given their official blessing yet. Will sign as soon as that happens.

**Comment by bfriesen** [comment]
@pranavkm CLA signed.

**Comment by pranavkm** [comment]
Thanks for the PR!

**Pull request merged**
