### PR TITLE
fix issue #6669 in release/2.2

### PR DESCRIPTION
**Pull request by JipingWang**
- fix wrong scheme name in B2C and AD

Addresses #6669

### CODE REVIEW

**Comment by Tratcher** [comment]
@muratg

**Comment by muratg** [comment]
cc @Eilon

**Comment by Eilon** [comment]
@muratg - do you want to start a mail thread about this? We could look at patching in 2.2, but 2.1 is unlikely.

**Comment by javiercn** [comment]
@Eilon @muratg I've incorporated the changes from the customer into https://github.com/aspnet/AspNetCore/pull/7096 so that we can add things on top.

**Comment by natemcmaster** [comment]
Closing in favor of https://github.com/aspnet/AspNetCore/pull/7096. The issue will be address in ASP.NET Core 3.0. See https://github.com/aspnet/AspNetCore/issues/6669 for a workaround in the meantime.

**Pull request closed without merging**
