### PR TITLE
Disable validation steps

### PR DESCRIPTION
**Pull request by mmitche**
These steps can be run as part of the nightly Validate-DotNet runs, as well as the Release-DotNet pipeline that is run to prep for validation+release

### CODE REVIEW

**Comment by mmitche** [comment]
@jcagme Has aspnetcore opted into Validate-DotNet yet?

**Comment by jcagme** [comment]
> @jcagme Has aspnetcore opted into Validate-DotNet yet?

Yes aspnetcore-tooling as well

**Review by dougbu — APPROVED** [review]
We're opted into Validate-DotNet but does that pipeline do signing and NuGet validation now? More importantly, are there additional switches we need to throw so that more than SDL validation runs on our repo?

**Comment by mmitche** [comment]
> We're opted into Validate-DotNet but does that pipeline do signing and NuGet validation now? More importantly, are there additional switches we need to throw so that more than SDL validation runs on our repo?

https://dev.azure.com/dnceng/internal/_build/results?buildId=672789&view=results

Yep, it does sourcelink (which you were missing before), as well as symbols, nuget, etc.

**Comment by dougbu** [comment]
Build looks reasonable.

@jcagme are exceptions / exemptions we have in eng/Signing.props applied when doing the signing validation in this pipeline?

Could you please enable a summary at the bottom of the logs? I can't see what went wrong in the 'Validate Symbols' step. (And, I'd forget if you told me a string to search for 😃)

**Comment by jcagme** [comment]
@Tohron can provide more details on implementation. Short answer is probably? The validation here is basically a port of validation done in builds.

**Comment by jcagme** [comment]
@adiaaida can you look at the error summary for symbols validation?

**Comment by Tohron** [comment]
The signing validation script currently checks eng/SignCheckExclusionsFile.txt.
The signing validation script that it calls from arcade may check other files, I'm not sure.

**Comment by dougbu** [comment]
@Tohron that's odd because I saw errors about a .js file that looked familiar to me. We have `*.js;; ...` in our eng/SignCheckExclusionsFile.txt file. But, we don't have a similar file in aspnetcore-tooling however. Are the errors easily linked to a particular package or at least specific repo? The filename is often not enough.

**Pull request merged**
