### PR TITLE
Swap installer names

### PR DESCRIPTION
**Pull request by jkotalik**
Fixes the windows hosting bundle build. The wrong variable was being set for each installer.

### CODE REVIEW

**Comment by jkotalik** [comment]
@muratg @shirhatti @Eilon let's figure out if/how we are going to deliver this to the preview3 hosting bundle.

**Comment by jkotalik** [comment]
Fixes: https://github.com/aspnet/AspNetCore/issues/8249

**Review by pakrym — APPROVED** [review]

**Comment by jkotalik** [comment]
We decided we wouldn't fix this in preview3. Changing to master.

**Review by muratg — APPROVED** [review]

**Comment by jkotalik** [comment]
@mikaelm12 another failure 
```
  com.microsoft.signalr.HubConnectionTest > TransportAllUsesLongPollingWhenServerOnlySupportLongPolling() FAILED
      java.lang.RuntimeException at HubConnectionTest.java:1518
          Caused by: java.lang.Exception at HubConnectionTest.java:1518
```

**Pull request merged**
