### PR TITLE
Unquarantine CanSendAndReceiveBytes

### LINKED ISSUE #23366: Flaky CanSendAndReceiveBytes
There were four blazor test failures in https://dev.azure.com/dnceng/public/_build/results?buildId=704666&view=ms.vss-test-web.build-test-results-tab&runId=21834978&resultId=100374&paneView=debug. All of them look fairly similar, seems more likely to be a general issue.

Failure:
```
  | OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.TrueException: Assert.True() Failure\r\nExpected: True\r\nActual: False\r\n at Xunit.Assert.True(Nullable1 condition, String userMessage) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\BooleanAsserts.cs:line 95\r\n at Xunit.Assert.True(Boolean condition) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\BooleanAsserts.cs:line 62\r\n at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass5_0.<True>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 30\r\n at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass16_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 77\r\n at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_01.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 103\r\nScreen shot captured at 'F:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\802524f612c74cb3b73db104eeb550a3.png'\r\nEncountered browser errors\r\n[2020-06-25T18:18:26Z] [Debug] http://127.0.0.1:52317/_framework/dotnet.5.0.0-preview.6.20305.6.js 0:124605 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"\r\n[2020-06-25T18:18:28Z] [Debug] http://127.0.0.1:52317/_framework/dotnet.5.0.0-preview.6.20305.6.js 0:124605 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"\r\n[2020-06-25T18:18:32Z] [Debug] http://127.0.0.1:52317/_framework/dotnet.5.0.0-preview.6.20305.6.js 0:124605 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"\r\n[2020-06-25T18:18:37Z] [Debug] http://127.0.0.1:52317/_framework/dotnet.5.0.0-preview.6.20305.6.js 0:124605 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"\r\n[2020-06-25T18:18:42Z] [Debug] http://127.0.0.1:52317/_framework/dotnet.5.0.0-preview.6.20305.6.js 0:124605 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"\r\n[2020-06-25T18:18:47Z] [Info] http://127.0.0.1:52317/_framework/blazor.webassembly.js 0:38153 "Refresh Time 63728705927218"\r\n[2020-06-25T18:18:48Z] [Info] http://127.0.0.1:52317/_framework/blazor.webassembly.js 0:38153 "Refresh Time 63728705928121"\r\n[2020-06-25T18:18:50Z] [Info] http://127.0.0.1:52317/_framework/blazor.webassembly.js 0:38153 "Refresh Time 63728705929998"\r\n[2020-06-25T18:19:01Z] [Info] http://127.0.0.1:52317/_framework/blazor.webassembly.js 0:38153 "Refresh Time 63728705941484.01"\r\n[2020-06-25T18:19:04Z] [Info] http://127.0.0.1:52317/_framework/blazor.webassembly.js 0:38153 "Refresh Time 63728705944285.01"\r\n[2020-06-25T18:19:08Z] [Info] http://127.0.0.1:52317/_framework/blazor.webassembly.js 0:38153 "Refresh Time 63728705948035.99"Page content:\r\n<head>\r\n <meta charset="utf-8">\r\n <title>E2EPerformance</title>\r\n <link href="benchmarks/lib/bootstrap.min.css" rel="stylesheet">\r\n <link href="benchmarks/lib/minibench/style.css" rel="stylesheet">\r\n</head>\r\n<body style="overflow: scroll;">\r\n <div class="container" id="display"><div class="d-flex align-items-center"><h2 class="mx-3 flex-grow-1">E2E Performance<label class="ml-auto mr-5"><input type="checkbox" class="mr-2">Verify only</label><button class="btn btn-success ml-auto px-4 run-button" id="runAll" style="display: block;">Run all</button><button class="btn btn-danger ml-auto px-4 stop-button" style="display: none;">Stop</button><div class="my-3 py-2 bg-white rounded shadow-sm"><div class="d-flex align-items-baseline px-4"><h5 class="py-2">App Startup<a class="ml-auto run-button" href="" style="display: block;">Run all<table class="table mb-0 benchmarks">
-- | --
Executions: 1 | Duration: 17300ms

 at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 123
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore(IWebDriver driver, Action assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 77
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.True(IWebDriver driver, Func`1 actual, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 30
   at Microsoft.AspNetCore.Components.E2ETest.Tests.PerformanceTest.BenchmarksRunWithoutError() in /_/src/Components/test/E2ETest/Tests/PerformanceTest.cs:line 51
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass5_0.<True>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 30
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass16_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 77
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 103
```

@pranavkm mentioned:

> I wonder if the issue is that we're not waiting for the component to be ready before doing work. We should quarantine these until we've had a chance to investigate.

### PR DESCRIPTION
**Pull request by TanayParikh**
This test has been passing consistently for the past 30 days now:
image

(the 4 failures in the past 24 hours are due to an unrelated CI issue which has been separately investigated).

This is just an extension of: https://github.com/dotnet/aspnetcore/pull/31156

Underlying test stability issues should've been resolved in the October/November 2020 timeframe via https://github.com/dotnet/aspnetcore/pull/26519.

**Edit:** Also added independent Browser instances between `CanSendAndReceiveBytes` and `BenchmarksRunWithoutError`. The flakiness seems to have been rooted in shared Browser instances between tests. 

Fixes: https://github.com/dotnet/aspnetcore/issues/23366

### CODE REVIEW

**Review by HaoK — APPROVED** [review]

**Comment by TanayParikh** [comment]
Looks like a legitimate CI failure. `BenchmarksRunWithoutError` is another test which was quarantined due to https://github.com/dotnet/aspnetcore/issues/23366 but was later unquarantined via https://github.com/dotnet/aspnetcore/pull/31156. So it seems the tests fail when they're both "active". @HaoK wondering if you have any context on the relation here?

```
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.EmptyException: Assert.Empty() Failure
Collection: [Element (id = 998de1bd-fcd8-4799-8dad-14a452284a07), Element (id = 55fd5e9a-f85d-4d58-9b66-bfb75ed57e14), Element (id = 78b326ec-137d-4fee-ae58-12912cd24578), Element (id = b126de36-52b2-46c1-bdd7-fa9fad7381a5), Element (id = a3d7b7a9-4a29-42ae-9219-4656f8626ca6), ...]
   at Xunit.Assert.Empty(IEnumerable collection) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 284
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 83
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 109
Screen shot captured at 'D:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\92efa74db8e842dca7b5c80a40d6154b.png'
Encountered browser errors
[2021-04-29T21:49:31Z] [Debug] http://127.0.0.1:53201/_framework/dotnet.6.0.0-preview.4.21221.4.js 0:142749 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"
[2021-04-29T21:49:32Z] [Debug] http://127.0.0.1:53201/_framework/dotnet.6.0.0-preview.4.21221.4.js 0:142749 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"
[2021-04-29T21:49:33Z] [Severe] http://127.0.0.1:53201/benchmarks/lib/minibench/minibench.js 218:28 Error: Wrong number of items rendered
    at measureRenderList (http://127.0.0.1:53201/benchmarks/renderListBenchmark.js:22:11)
    at async ExecutionTimer._runBlock (http://127.0.0.1:53201/benchmarks/lib/minibench/minibench.js:149:17)
    at async ExecutionTimer.run (http://127.0.0.1:53201/benchmarks/lib/minibench/minibench.js:121:56)
    at async Benchmark._measureTimings (http://127.0.0.1:53201/benchmarks/lib/minibench/minibench.js:248:9)
    at async http://127.0.0.1:53201/benchmarks/lib/minibench/minibench.js:201:21
[2021-04-29T21:49:33Z] [Severe] http://127.0.0.1:53201/benchmarks/lib/minibench/minibench.js 218:28 Error: Wrong number of items rendered
    at measureRenderList (http://127.0.0.1:53201/benchmarks/renderListBenchmark.js:22:11)
    at async ExecutionTimer._runBlock (http://127.0.0.1:53201/benchmarks/lib/minibench/minibench.js:149:17)
    at async ExecutionTimer.run (http://127.0.0.1:53201/benchmarks/lib/minibench/minibench.js:121:56)
    at async Benchmark._measureTimings (http://127.0.0.1:53201/benchmarks/lib/minibench/minibench.js:248:9)
    at async http://127.0.0.1:53201/benchmarks/lib/minibench/minibench.js:201:21
[2021-04-29T21:49:33Z] [Debug] http://127.0.0.1:53201/_framework/dotnet.6.0.0-preview.4.21221.4.js 0:142749 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"
[2021-04-29T21:49:35Z] [Debug] http://127.0.0.1:53201/_framework/dotnet.6.0.0-preview.4.21221.4.js 0:142749 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"
[2021-04-29T21:49:36Z] [Debug] http://127.0.0.1:53201/_framework/dotnet.6.0.0-preview.4.21221.4.js 0:142749 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"
[2021-04-29T21:49:37Z] [Severe] http://127.0.0.1:53201/_framework/blazor.webassembly.js 0:27256 "crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Failed to execute 'setAttribute' on 'Element': '@bind' is not a valid attribute name.
      Error: Failed to execute 'setAttribute' on 'Element': '@bind' is not a valid attribute name.
          at V.applyAttribute (http://127.0.0.1:53201/_framework/blazor.webassembly.js:1:20408)
          at V.insertElement (http://127.0.0.1:53201/_framework/blazor.webassembly.js:1:19455)
          at V.insertFrame (http://127.0.0.1:53201/_framework/blazor.webassembly.js:1:18439)
          at V.insertFrameRange (http://127.0.0.1:53201/_framework/blazor.webassembly.js:1
```

**Comment by HaoK** [comment]
Right I don't have any context, but I noticed this too, our tests seem to interact with each other, my feeling is that there's too much parallelization/sharing of servers between our tests.  It seems better to run our tests in a sandbox or at the least where its not possible to have this kind of interaction.  I filed https://github.com/dotnet/aspnetcore/issues/31195 which was another set of tests that I encountered that cause each other to fail.  You can probably add these tests to that list, and maybe you can try to identify what's causing the test interactions in our E2E tests

**Comment by HaoK** [comment]
Actually that bind error, is that our old caching friend @captainsafia ?

**Comment by HaoK** [comment]
I've made this suggestion before but got opposition from DOI, I think the quarantine runs should be running the full set of tests, not just the quarantined tests, that would dramatically increase the confidence that unquarantining tests actually is safe.

**Comment by captainsafia** [comment]
> Actually that bind error, is that our old caching friend @captainsafia ?

The other issue occurs as a build error. This one is happening during runtime so I believe it is different.

**Review by HaoK — APPROVED** [review]

**Pull request merged**
