### PR TITLE
Fix Microsoft.AspNetCore version in baseline

### PR DESCRIPTION
**Pull request by dougbu**
- odd that Microsoft.AspNetCore.Server.IISIntegration didn't have correct version before&hellip;

### CODE REVIEW

**Comment by natemcmaster** [comment]
By chance, have you done anything to verify that we aren't missing any other out-of-date baseline entries?

**Comment by dougbu** [comment]
> By chance, have you done anything to verify that we aren't missing any other out-of-date baseline entries?

I was about to do that. Wanted to get this fixed while it was in our faces 😸

**Review by natemcmaster — APPROVED** [review]

**Comment by natemcmaster** [comment]
Will let @Eilon decide if this is a shiproom ask or tell.

**Review by mikaelm12 — APPROVED** [review]

**Comment by Eilon** [comment]
Definitely needs to go through shiproom because this affects what we ship. Please have the test ready in the PR, add the shiproom template to the top of the PR, and send mail.

**Comment by Eilon** [comment]
Oh and when  you add the test, please run the test on the reverted files to see that it found what you found!

**Comment by dougbu** [comment]
#### Description
As described in aspnet/AspNetCore#7546, the 2.1.8 release downgraded Microsoft.AspNetCore dependencies to version 2.1.6. This in turn leads to `FileLoadExceptions` as in https://github.com/aspnet/AspNetCore/issues/3503#issuecomment-463134356

#### Customer impact
As one commenter said, we're entering ASP.NET Core version hell 😦

Users have multiple workarounds:
1. add `<PackageReference Include="Microsoft.AspNetCore" Version="2.1.7" />` (NB: this is NOT the .App package)
2. Remove version from AspNetCore.App `<PackageReference Include="Microsoft.AspNetCore.App" />`
2. Update AspNetCore.App: `<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.8" />`

#### Regression?
Yes. Earlier 2.1.x releases did not have this issue.

#### Risk
Minimal. We are adding tests to ensure this issue does not occur going forward.

**Comment by vivmishra** [comment]
Approved for 2.1.9.

**Pull request merged**
