### PR TITLE
[CORS] Remove E2E functional tests

### PR DESCRIPTION
**Pull request by javiercn**
* The tests are low value.
* The tests are flaky.
* The tests cover mostly browser behavior not spec compliance.
* It's an area that doesn't change often.
* We have unit tests to cover the casuistic.

### CODE REVIEW

**Comment by Tratcher** [comment]
> The tests cover mostly browser behavior not spec compliance. 

Browser interop is ultimately more important. Having zero coverage is hazardous. How much coverage do we get from CTI testing?

**Comment by pranavkm** [comment]
@Tratcher we don't have a CTI issue for this yet. We run these tests against a fixed version of chromium, so it doesn't really test any "new" browser interop scenarios, only changes to the middleware which we have ample test coverage for. 

I'm a little hesitant about having a CTI scenario for this, just because it's non-trivial set up work.

**Review by pranavkm — APPROVED** [review]

**Comment by Tratcher** [comment]
Then how else do we deal with the integration testing gap?

**Comment by javiercn** [comment]
The other alternative is to move all these tests to use Selenium instead as that is what we've converged the infrastructure on, and see what extra steps we have to take to address flakiness here.

That's additional work we would have to take here and is not a trivial amount I think, but we can discuss it.

In their current form the tests don't add much value and testing the browser behavior is of limited value. We already have integration tests to validate the protocol level details.

And finally, this is not an area that changes neither on our side nor in browsers (AFAIK)

**Comment by Tratcher** [comment]
> In their current form the tests don't add much value and testing the browser behavior is of limited value.

Our customers use browsers. We need at least one end-to-end test using a browser to ensure we don't regress something major. How and where we test that is negotiable.

**Comment by javiercn** [comment]
> Our customers use browsers. We need at least one end-to-end test using a browser to ensure we don't regress something major. How and where we test that is negotiable.

What would we be testing? our implementation, he browsers implementation?

Lets assume that a browser decides to change their implementation in a way that is incompatible with ours in some way (either restricts to little or restricts too much).

* Wouldn't we get bug reports from customers in that case?
* What action would we take in that situation?
* How do our current tests help in this scenario?

I agree with you in that we need to test things E2E when we make changes, but that doesn't mean that those E2E tests need to be automated. Otherwise we would write E2E browser tests for each and every feature we create, which we don't. This change is acknowledging that reality.

* The tests are flaky and cause build reliability issues.
* They don't add value because they test against a fixed browser version.
* They are in an area that doesn't change often, so running them on every build has little/no value.
* We already have unit tests to cover our implementation compliance.

All that I'm trying to say is that these tests have drawbacks and they offer no benefit. That's the reason we are removing them.

Why not change the testing approach/update the tests? We have compelling reasons not to do this that are stated above.
* We don't expect this area to change, when/if (unlikely) it does, we can rely on our existing tests and validate the E2E browser behavior for the things that we changed, which is not covered today by these E2E tests.
* When/if (unlikely) a browser changes their implementation it would result in one of the following scenarios:
  * We don't notice (the change is not significant or customers are not using that part of the spec), so why would we care?
  * We get a bug report from a customer.
    * We open a bug against the specific browser and wait for a response. At this point of maturity on the spec/implementations I don't expect accidental changes in this area, but deliberate ones.

What I'm saying with this is that it is not our responsibility to test browser compatibility across browser versions. That places a huge burden on us for little/no benefit. Instead we simply do what we do today, which is test for spec compliance with unit/functional tests and perform sanity testing when we make changes by performing manual tests on different browsers. For that reason we are removing these tests.

If you think this is not good enough, I would suggest you open a new issue describing what problem you want us to solve and we can discuss how we can approach it.

What we are saying here/with this PR is that the current solution is not a valid/working solution and hence not only does not add value but it hurts our build reliability and that's why we are taking it out.

I hope that helps make things clear.

**Comment by Tratcher** [comment]
> and perform sanity testing when we make changes by performing manual tests on different browsers.

If we disabled these tests on the CI and only ran them locally would they be helpful for sanity testing changes? Kestrel has a group of tests like that (`SkipOnCI`), they cause too many resource conflicts on the CI (default ports) but are useful locally testing for regressions.

Otherwise don't block this PR, I agree the tests as is are not in a great state at the moment. I'm asking what we should do next to cover this gap.

> it is not our responsibility to test browser compatibility across browser versions. 

It's our responsibility to make sure our product works in scenarios our customers are most likely to use it, e.g. current, common browsers.

> and perform sanity testing when we make changes by performing manual tests on different browsers.

Manual testing only accounts for intentional changes on our end, not our accidental regressions due to changes here or elsewhere in the stack, nor any changes on the client. Ultimately it's the end-to-end scenario that matters and we want some minimal coverage somewhere to verify that.

**Comment by javiercn** [comment]
> If we disabled these tests on the CI and only ran them locally would they be helpful for sanity testing changes? Kestrel has a group of tests like that (`SkipOnCI`), they cause too many resource conflicts on the CI (default ports) but are useful locally testing for regressions.

That was my preference too, but we decided against this because unlike Kestrel, this is not an area that gets looked often and the tests will simply rot very quick.

**Pull request merged**
