### PR TITLE
**Do not merge** Test what validations run

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Comment by dougbu** [comment]
Oddly, last AzDO command _did_ kick off an aspnetcore-pr-validation-temp run -- https://dev.azure.com/dnceng/public/_build/results?buildId=480543. That's the second run of the pipeline for this PR but neither shows up here. And, the list of pipelines to make required in the repo's branch protection rules shows only the older, capitalized pipeline. Hoping there's just a delay somewhere because I don't see anything wrong in the configurations.

@mmitche @MattGal this isn't a big deal at the moment (we're not doing many (any?) new 'release/2.1' PRs in the next couple of days). But, do you have any ideas on the delay or perhaps actual problem -- beyond AzDO and GitHub using pipeline IDs instead of names or at least making name matching case-insensitive?

**Comment by mmitche** [comment]
Wrong service connection. Fixed.

**Comment by dougbu** [comment]
Thanks @mmitche. In case we see this with other less-used pipelines, where is the relevant service connection specified?

**Comment by mmitche** [comment]
Click edit pipeline, then the little dropdown and click "Triggers", then under the main page where you select the repository you can set the service connection. There may still be others set to "aspnet" instead of "dotnet".

**Comment by dougbu** [comment]
@mmitche the pipeline won't trigger on a closed PR, especially because I deleted the branch. In any case, the pipeline now shows up for use in branch protection rules and all is well.

On the service connection, I suspect I don't have sufficient permissions to see the service connection setting unless you mean the `system.collectionid` variable. Even the repo name is visible but not something I can edit. Ah well.

**Pull request closed without merging**
