### PR TITLE
Quarantine LinkedApplicationTests

### PR DESCRIPTION
**Pull request by jkotalik**
https://github.com/dotnet/aspnetcore/issues/24594

### CODE REVIEW

**Comment by davidfowl** [comment]
Wait what? LOL

**Comment by jkotalik** [comment]
Yeah the error was wack. Do we need to reach out to HttpClient folks?

**Comment by davidfowl** [comment]
I'm like 98% sure this isn't a bug with the test itself. It looks like an issue in the SocketsHttpHandler

**Comment by Tratcher** [comment]
Yeah, that error is too general to warrant quarantining a specific test.

**Comment by jkotalik** [comment]
Closing as I agree.

**Pull request closed without merging**
