### PR TITLE
Add environment property to override built-in setting

### PR DESCRIPTION
**Pull request by michaelrp**
Add an `environment` property for `WebAssemblyStartOptions` and pass the value to `BootConfigResult.initAsync`.

Addresses #20935

### CODE REVIEW

**Comment by captainsafia** [comment]
@michaelrp This is a great start. We'll need to add some tests for this. For this particular scenario, I think it would be sensible to add a unit test for this particular method. We don't currently have unit tests for our `Blazor.start` methods and an E2E test seems like too much infrastructure for this particular change.

You can create a new `test/Boot.WebAssembly.test.ts` file that calls the `Blazor.start` function and checks to see if the returned `BootConfigResult` object has the right properties.

**Comment by pranavkm** [comment]
@captainsafia we might be ok getting this change in as-is. We don't have coverage for how evironments work, so it might suffice to eye ball this. We would need to update the blazor.webassembly.js file before accepting this PR.

**Comment by captainsafia** [comment]
@pranavkm That's fine by me. This is a straight-forward enough change that testing might be overkill and I doubt we'll be changing this codepath much.

@michaelrp Looks like all you need to do is run `npm run build` in the `src/Components/Web.JS` and commit the generated source files and htis PR should be good to go.

**Comment by michaelrp** [comment]
@captainsafia Done!

**Comment by captainsafia** [comment]
@michaelgsharp Looks like you need to rebase and regenerate the built artifact again!

We commit our built sources to the repo to make it easier to package the framework. One of the consequences is that you might end up having to rebase and regenerate the file multiple times, especially on a day like today where we have a lot of PRs being merged.

**Comment by michaelrp** [comment]
@captainsafia Hm...I maybe mangled the rebase. Suggestions on how to repair?

**Comment by captainsafia** [comment]
@michaelgsharp You can run `git rebase -i HEAD~9` to start an interactive rebase. Then replace `pick` with `drop` for all the commits you want to remove.

**Comment by michaelrp** [comment]
@captainsafia Ok, looking more like it should now, thank you!

**Review by captainsafia — APPROVED** [review]
Looks good! Thank you.

**Comment by javiercn** [comment]
@michaelrp merged!

Thanks for the contribution!

**Pull request merged**
