### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by natemcmaster**
This will suppress automatic review requests to @aspnet/build for bot-generated PRs

### CODE REVIEW

**Comment by dougbu** [comment]
I would rather we _not_ do this until the bot can notify us when checks fail. Can use Outlook to ignore 90% of the bot's updates:
image

**Comment by natemcmaster** [comment]
I personally find GitHub emails useless altogether and use octobox to manage notifications...so outlook rules don't help me. @dougbu if you still want to receive emails, I can add you as a co-owner with dotnet-maestro-bot so you still get email notifications for review requests.

**Comment by dougbu** [comment]
How will we monitor invalid manual changes to the files the bot changes w/o these notifications? And, I understand you're willing to hand a lot of info and power over to Octobox but I am not.

So, yes, if you don't want email notifications and pare them down on receipt, add me as a code owner.

Separately, should we let the bot own /global.json in our Arcade repos?

**Comment by natemcmaster** [comment]
> How will we monitor invalid manual changes to the files the bot changes w/o these notifications?

Sounds like a good question for a separate conversation about how much we trust the bot. Pinging @aspnet/build for every PR is sufficient to answer this question, though, as human review of Versions.Details.xml is often error prone anyways.

**Comment by natemcmaster** [comment]
> Separately, should we let the bot own /global.json in our Arcade repos?

Actually, that one I want our team to still review. Changes to global.json are more likely to lead to build errors and problems than other version files since global.json controls the version of the .NET Core SDK and Arcade SDK.

**Comment by dougbu** [comment]
> Pinging @aspnet/build for every PR is sufficient to answer this question

With this change to CODEOWNERS, who or what will ping @aspnet/build ?

**Review by dougbu — APPROVED** [review]
Note that the ownership changes to /eng/Versions* mean I'll be the only human who's notified about merge requests that affect only dependencies e.g. from future `3.0-previewX` branches. (What we really want is to own and hear about all zee filez but ignore success messages _from_ the bot.)

I'm also curious what the bot will do with these notifications. Wondering if GitHub has a `/dev/null` owner we could use for this 😺

**Comment by natemcmaster** [comment]
I'm assuming no one is monitoring the dotnet-maestro-bot inbox for notifications.

As always, if you want to adjust this file, send a PR. :)

**Pull request merged**
