### PR TITLE
Revert bad merge in React app

### PR DESCRIPTION
**Pull request by ryanbrandenburg**
I just want full CI testing for now.

### CODE REVIEW

**Review by javiercn — APPROVED** [review]

**Comment by javiercn** [comment]
This doesn't require design.
just do git diff hashbeforemerge -- pathsToCheck and make sure that comes out as empty and you would have removed everything

**Comment by ryanbrandenburg** [comment]
When I say "Design" in my PR's what I usually mean is "This isn't ready for review, I only want the CI verification". I'll probably start using [draft pull requests](https://github.blog/2019-02-14-introducing-draft-pull-requests/) for that instead.

**Comment by ryanbrandenburg** [comment]
Fixes #7686.

**Comment by ryanbrandenburg** [comment]
Also fixes https://github.com/aspnet/AspNetCore-Internal/issues/1745.

**Review by mkArtakMSFT — APPROVED** [review]

**Comment by ryanbrandenburg** [comment]
@mkArtakMSFT if we look at the latest failure it's caused by [this issue](https://github.com/aspnet/AspNetCore-Internal/issues/1826). Can I get you to do the thing to merge it past the failing PR check since I've already tried retrying?

**Comment by javiercn** [comment]
Can you wait to merge this if it's not critical? I'm about to merge the spa templates change.

**Review by dougbu — APPROVED** [review]

**Pull request merged**
