### PR TITLE
**DISABLE_SECRET_SCANNING**

### PR DESCRIPTION
**Pull request by dougbu**
- see discussion in #41013

### CODE REVIEW

**Review by MattGal — APPROVED** [review]

**Review by wtgodbe — APPROVED** [review]
Should at least unblock us for now

**Comment by wtgodbe** [comment]
This worked but I had to trigger the mirror manually - @dotnet/dnceng does it ignore empty commits?

**Comment by dagood** [comment]
> does it ignore empty commits?

Yep.

* https://github.com/dotnet/versions/issues/110

**Comment by mmitche** [comment]
Maestro ignores push events with no changed files, so that's why it had to be queued manually. this is the same reason that you need to manually push a new preview branch to internal if no files are chagned.

**Comment by MattGal** [comment]
Check out https://dnceng.visualstudio.com/internal/_git/dotnet-versions?path=/Maestro/src/Microsoft.DotNet.Maestro.WebApi/Controllers/CommitPushedController.cs&version=GBmain&line=36&lineEnd=53&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents for why this is true.  I think this version of code mirroring is on its last legs.

**Comment by MattGal** [comment]
@mmitche jinx :)

**Comment by dougbu** [comment]
> I think this version of code mirroring is on its last legs.

what's coming❔ enquiring minds 🤯 and all that&hellip;

**Comment by MattGal** [comment]
> > I think this version of code mirroring is on its last legs.
> 
> what's coming❔ enquiring minds 🤯 and all that…

It's not funded yet but it will be something that doesn't use build pipelines, possibly inside the modern maestro.

**Pull request merged**
