### PR TITLE
Bump down-level SiteExtension versions

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Comment by dougbu** [comment]
@HaoK @Tratcher is at least the first error a known problem in our 'main' branch❔

Fairly consistent failures of `Templates.Test.BlazorWasmTemplateTest.BlazorWasmHostedTemplate_IndividualAuth_Works_WithOutLocalDB()`

``` text
 | /datadisks/disk1/work/ADDF094F/w/B3DB0952/e/Templates/BaseFolder/AspNet.g4jvm5b2hhm/Server/Data/ApplicationDbContext.cs(4,7): error CS0246: The type or namespace name 'IdentityServer4' could not be found (are you missing a using directive or an assembly reference?) [/datadisks/disk1/work/ADDF094F/w/B3DB0952/e/Templates/BaseFolder/AspNet.g4jvm5b2hhm/Server/AspNet.g4jvm5b2hhm.Server.csproj]
 | /datadisks/disk1/work/ADDF094F/w/B3DB0952/e/Templates/BaseFolder/AspNet.g4jvm5b2hhm/Server/Data/ApplicationDbContext.cs(13,22): error CS0246: The type or namespace name 'OperationalStoreOptions' could not be found (are you missing a using directive or an assembly reference?) [/datadisks/disk1/work/ADDF094F/w/B3DB0952/e/Templates/BaseFolder/AspNet.g4jvm5b2hhm/Server/AspNet.g4jvm5b2hhm.Server.csproj]
```

Also an odd ordering issue in `Microsoft.AspNetCore.Authentication.DataHandler.SecureDataFormatTests.UnprotectWithDifferentPurposeFails()` on Windows Helix agent:

``` text
  Failed Microsoft.AspNetCore.Authentication.DataHandler.SecureDataFormatTests.UnprotectWithDifferentPurposeFails [82 ms]
  Error Message:
   System.Security.Cryptography.CryptographicException : An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information.
---- System.IO.IOException : The process cannot access the file 'C:\Users\runner\AppData\Local\ASP.NET\DataProtection-Keys\key-e1b9213e-93ea-4577-a1b5-b19393548ef7.xml' because it is being used by another process.
```

<details>
<summary>Stack trace</summary>

     at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext) in /_/src/DataProtection/DataProtection/src/KeyManagement/KeyRingBasedDataProtector.cs:line 141
   at Microsoft.AspNetCore.Authentication.SecureDataFormat`1.Protect(TData data, String purpose) in /_/src/Security/Authentication/Core/src/SecureDataFormat.cs:line 46
   at Microsoft.AspNetCore.Authentication.DataHandler.SecureDataFormatTests.UnprotectWithDifferentPurposeFails() in /_/src/Security/Authentication/test/SecureDataFormatTests.cs:line 60
----- Inner Stack Trace -----
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options) in System.Private.CoreLib.dll:token 0x6000125+0xa1
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) in System.Private.CoreLib.dll:token 0x6000124+0x6
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) in System.Private.CoreLib.dll:token 0x60062b9+0x24
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) in System.Private.CoreLib.dll:token 0x600623c+0xa
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize) in System.Private.CoreLib.dll:token 0x6006234+0x0
   at System.IO.File.OpenRead(String path) in System.Private.CoreLib.dll:token 0x6005df4+0x0
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.ReadElementFromFile(String fullPath) in /_/src/DataProtection/DataProtection/src/Repositories/FileSystemXmlRepository.cs:line 103
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElementsCore()+MoveNext() in /_/src/DataProtection/DataProtection/src/Repositories/FileSystemXmlRepository.cs:line 84
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) in System.Private.CoreLib.dll:token 0x6006cf0+0x71
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) in System.Linq.dll:token 0x600011b+0x14
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElements() in /_/src/DataProtection/DataProtection/src/Repositories/FileSystemXmlRepository.cs:line 69
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys() in /_/src/DataProtection/DataProtection/src/KeyManagement/XmlKeyManager.cs:line 158
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded) in /_/src/DataProtection/DataProtection/src/KeyManagement/KeyRingProvider.cs:line 64
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded) in /_/src/DataProtection/DataProtection/src/KeyManagement/KeyRingProvider.cs:line 110
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now) in /_/src/DataProtection/DataProtection/src/KeyManagement/KeyRingProvider.cs:line 278
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh) in /_/src/DataProtection/DataProtection/src/KeyManagement/KeyRingProvider.cs:line 205
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRing() in /_/src/DataProtection/DataProtection/src/KeyManagement/KeyRingProvider.cs:line 149
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext) in /_/src/DataProtection/DataProtection/src/KeyManagement/KeyRingBasedDataProtector.cs:line 102
```
</details>

**Comment by HaoK** [comment]
I'm going to undo my identity server upgrade, I think that broke templaes

**Comment by dougbu** [comment]
Thanks @HaoK. Please let the world know when that's in. Or `/azp run` all PRs that may have been busted since your merge 😀

**Comment by dougbu** [comment]
Just waiting for #34317 to get in

**Pull request merged**
