### PR TITLE
[Blazor WebAssembly] Change web app manifest extension to “webmanifest”

### LINKED ISSUE #43755: [Blazor WebAssembly Project Template] Change web app manifest extension to “webmanifest”
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

_No response_

### Describe the solution you'd like

The official file extension for the Web Application Manifest is `webmanifest`. This helps servers to deliver the file with the official media type (`application/manifest+json`). I propose changing the manifest's file extension in the Blazor WebAssembly project templates from "json" to "webmanifest".

Sources:
- [Web Application Manifest spec](https://www.w3.org/TR/appmanifest/#h-note-0)
- [IANA media type registration](https://www.iana.org/assignments/media-types/application/manifest+json)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by christianliebel**
# [Blazor WebAssembly] Change web app manifest extension to “webmanifest”

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Changes web app manifest extension from "json" to "webmanifest"

## Description

Changes the extension of the web application manifest included by the Blazor WebAssembly project templates from "json" to "webmanifest", the official file extension. This helps servers to deliver the file with the official media type (`application/manifest+json`).

Fixes #43755

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=43756) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=43756) before we can accept your contribution.<br/><br/>:x: christianliebel [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=43756)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=43756) it.</sub>

**Review by javiercn — COMMENTED** [review]
Looks like the tests likely need to be updated and the docs might also need to be updated.

We should ping guardrex about the docs after this is merged.

**Comment by christianliebel** [comment]
@javiercn I have updated the tests. A Blazor Server test still fails because `dotnet publish` does not work. But this should have nothing to do with my changes. Could you look into this for me?

Let me know if you need any help with the docs.

**Comment by TanayParikh** [comment]
Hey @christianliebel, thanks for the PR. We're ready to take this in now. Could you please resolve the merge conflict, and I'll look into any CI flakiness if required.

**Comment by christianliebel** [comment]
@TanayParikh Done!

**Review by TanayParikh — APPROVED** [review]
:shipit:

**Comment by TanayParikh** [comment]
Thanks @christianliebel!

I think thats all the `webmanifest` PRs. Please let me know if I missed any!

**Comment by christianliebel** [comment]
@TanayParikh Looks good, thanks!!

**Pull request merged**
