### PR TITLE
Adds an analyzer and code fix for closure over a loop variable

### PR DESCRIPTION
**Pull request by SQL-MisterMagoo**
Summary of the changes (Less than 80 chars)
 - Adds a Roslyn analyzer to detect use of a for loop variable in a lambda
 - Adds a Roslyn code fix to introduce a local variable and replace it in the lambda

Addresses #10476

### CODE REVIEW

**Comment by SQL-MisterMagoo** [comment]
@javiercn Agreed , the code fix will not currently be available in a Razor file - It's just I wanted to make sure the option was there if it ever becomes a possibility.

I have no idea how to fix the tests that are failing on some of the checks - it appears to be CR/LF issues - should I just make sure there are no CRs in the test data?

**Comment by SteveSandersonMS** [comment]
Thanks for contributing this, @SQL-MisterMagoo!

We'll discuss this on the team and figure out whether we think this is something we should include. I totally appreciate why there are cases when this would benefit people. However it's unclear this should be done as a Blazor-specific thing, since the same issue applies in any C# code in which a `for` iteration variable is used in an enclosed lambda.

Also, just to help clarify things for me: are you sure it's valid to be matching variables based on their names? Won't it get confused and report a problem in the following code, even though there isn't a problem?

```cs
for (var myVar = 0; myVar < 100; myVar++)
{
    DoSomething(() =>
    {
        var myVar = "Hello";
        Console.WriteLine(myVar);
    });
}
```

**Comment by SQL-MisterMagoo** [comment]
@SteveSandersonMS Ok, thanks - I'll go and learn a bit more about how Roslyn can help me identify the actual instance of the variable (even if only for my own learning as this has been an interesting exercise).

**Comment by NTaylorMullen** [comment]
> I'm not sure the code fix will work over the '.razor' file. @NTaylorMullen do you have thoughts on this?

The codefix wont work in the .razor file today. However, with our LSPification of that world it's very likely it will be possible to make work.

**Comment by pranavkm** [comment]
At the very least, we think we want to wait until 6.0 before considering this. It's a little too late in 5.0 for us to introduce an analyzer in the SDK. 

Sorry @SQL-MisterMagoo we should have better clarified this in before marking the issue as up-for-grabs

**Comment by SQL-MisterMagoo** [comment]
@pranavkm That's ok - it's a great learning exercise for me no matter what :smile:

**Comment by mkArtakMSFT** [comment]
Thanks for your PR, @SQL-MisterMagoo.
Given that we're going to consider this only for .NET 6, we better to close this PR for now as it'll go stale for sure.

**Pull request closed without merging**
