### PR TITLE
Fix mismatch of connection ID between SignalR C++ client and hub

### PR DESCRIPTION
**Pull request by wegylexy**
Summary of the changes
 - Append negotiated connection ID to connection URL

Addresses #6980

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Thanks for fixing this!

Would it be possible for you to add a test or two?

**Comment by wegylexy** [comment]
I lack experience in writing automated tests for client. It'd require a method in the hub to return the actual connection ID so the client can compare, or another way for connections without hubs. And it needs a server running to test the client.

**Comment by BrennanConroy** [comment]
We currently only have unit tests for the C++ client. You could try it out if you'd like by looking at some of the current tests and copying one that's similar to the functionality we want to test. https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/clients/cpp/test/signalrclienttests/connection_impl_tests.cpp#L53

Or I can do it later if you'd like 😄

**Comment by wegylexy** [comment]
I'll let you do it.

**Review by BrennanConroy — APPROVED** [review]

**Comment by BrennanConroy** [comment]
Thanks for the PR!

**Pull request merged**
