### PR TITLE
Remove ProcessExtensions.KillTree

### LINKED ISSUE #29014: Replace use of ProcessExtensions.KillTree with Process.Kill(entireProcessTree: true)
Removes a bunch of jank code which has external dependencies.

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes https://github.com/dotnet/aspnetcore/issues/29014

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]
oooooo

**Review by jkotalik — APPROVED** [review]
Make sure the runtime knows that we are now depending on this and need them to fix KillTree for 6.0

**Review by BrennanConroy — APPROVED** [review]

**Comment by Tratcher** [comment]
> Make sure the runtime knows that we are now depending on this and need them to fix KillTree for 6.0

@jkotalik what's wrong with it? If it's still broken then we should wait to adopt it.

**Comment by pranavkm** [comment]
@Tratcher here's the issue: https://github.com/dotnet/runtime/issues/45017. It appears limited to containers although I'm not super sure going by some of the test failures in this PR 😕

**Comment by pranavkm** [comment]
@adamsitnik @eiriktsarpalis I tried updating our repo to use `Kill(true)` in lieu of shelling out. We use `Kill(true)` in a few of our tests to shutdown processes that were launched as part of the test. In particular, I'm seeing that in some cases, selenium processes launched end up hanging in the `Kill` method call. I'm not able to put together a trivial example, but is this branch something you'd be able to investigate?

**Pull request closed without merging**
