### PR TITLE
Fix E2E test use of logs (#27114)

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
This is a test-only change that ports the existing PR https://github.com/dotnet/aspnetcore/pull/27114 from `master` to `release/5.0`. If this is not meant to be done manually like this, please let me know.

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT This is just porting a test fix from `master` to `release/5.0`. Are you able to approve and merge it?

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT Ping on this.

**Review by captainsafia — APPROVED** [review]

**Comment by wtgodbe** [comment]
@SteveSandersonMS branches are open for February, do you want me to merge this?

**Comment by SteveSandersonMS** [comment]
@wtgodbe Yes, that would be great! Thanks.

**Comment by wtgodbe** [comment]
@SteveSandersonMS well, now they are closed again 😆. We can get this merged for next month

**Comment by SteveSandersonMS** [comment]
@wtgodbe Are we in a position to include this in 5.0.4?

**Comment by wtgodbe** [comment]
> @wtgodbe Are we in a position to include this in 5.0.4?

Yep, branches are open until EOD today. Want me to merge this?

**Pull request merged**
