### PR TITLE
Include more template baselines

### PR DESCRIPTION
**Pull request by ryanbrandenburg**
Fixes https://github.com/aspnet/Templating/issues/725.

Replaces https://github.com/aspnet/Templating/pull/829.

### CODE REVIEW

**Comment by natemcmaster** [comment]
It looks like this PR has gone stale. @ryanbrandenburg who should be assigned to review?

**Review by SteveSandersonMS — APPROVED** [review]
Looks reasonable to me. If the baseline file is just listing all the files that the templates are expected to generate, then I approve this 👍

**Comment by SteveSandersonMS** [comment]
@ryanbrandenburg I notice that none of the baselines mention what `csproj` files that should generate. Why is that?

Does our baseline verification system just assume there will be exactly 1 csproj and its name will match the name of the project? If so we should reconsider this. When we have multiproject templates, it will be relevant to assert what collection of `sln` and `csproj` files they generate.

**Comment by ryanbrandenburg** [comment]
> When we have multiproject templates, it will be relevant to assert what collection of `sln` and `csproj` files they generate.

I mean, the real test of if the csproj's exist and are right is if the functional tests succeed. When people are adding multi-project templates are they including slns? I didn't think they were but maybe I missed something.

Feel free to file the issue though, it wouldn't actually hurt anything for those to be checked.

**Pull request merged**
