### PR TITLE
Try windows-2019 AzDO (hosted) queues

### PR DESCRIPTION
**Pull request by dougbu**
- aspnet/AspNetCore-Internal#2538

PR currently includes an extra commit for debugging in case PR validation fails

### CODE REVIEW

**Comment by dougbu** [comment]
Trial official build: https://dnceng.visualstudio.com/internal/_build/results?buildId=221506

**Comment by dougbu** [comment]
Trial official build succeeded but PR checks failed due to hanging builds. Retrying PR validation&hellip;

**Comment by dougbu** [comment]
:up::date: to remove debugging information from CodeCheck.ps1. VS BuildTools edition on hosted machines is sufficient for our builds and information is no longer needed.

**Review by natemcmaster — APPROVED** [review]

**Comment by dougbu** [comment]
Still waiting for the build to succeed. Now trying attempt #3.

@jkotalik @JunTaoLuo @natemcmaster are the following common warnings when building the site extensions? Got this from attempt #2's x64 build. The Windows test jobs showed similar warnings and then errors about inaccessible files.
```
CSC : warning CS2008: No source files specified. [D:\a\1\s\src\SiteExtensions\LoggingBranch\LoggingBranch.csproj]
D:\a\1\s\.dotnet\sdk\3.0.100-preview5-011568\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ComposeStore.targets(347,5): warning MSB3026: Could not copy "D:\a\1\s\.nuget\packages\runtime.win-x64.microsoft.netcore.app\3.0.0-preview7-27810-02\runtimes\win-x64\native\mscorrc.debug.dll" to "D:\a\1\s\artifacts\obj\LoggingBranch\Release\net461\win-x64\se\rs\win-x64\x64\netcoreapp3.0\mscorrc.debug.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'D:\a\1\s\artifacts\obj\LoggingBranch\Release\net461\win-x64\se\rs\win-x64\x64\netcoreapp3.0\mscorrc.debug.dll' because it is being used by another process.  [D:\a\1\s\artifacts\obj\LoggingBranch\Release\net461\win-x64\se\rs.csproj]
```

**Comment by natemcmaster** [comment]
This is one of the problems with the way site extension build code currently works. I believe it stems from bugs in the ‘dotnet store’ command, which @nguerrera is working on fixing for 3.0. https://github.com/dotnet/sdk/issues/1211, https://github.com/dotnet/sdk/issues/1072

**Comment by dougbu** [comment]
@natemcmaster does that explain the hanging builds as well as the warnings?

The three Windows jobs look stuck after succeeding again in this last attempt. Since we've seen this behaviour in many other PRs lately, I'm leaning toward merging now. Thoughts?

**Comment by natemcmaster** [comment]
I don't think that explains the hang. I think the hanging is a regression in Azure Pipelines' handling of background processes, but John is looking into it.

**Comment by dougbu** [comment]
Since #11230 this PR can't work because `tar` is not available. The agents in this queue must be older than Windows 10, version 1803. Try again in a couple of weeks&hellip;

**Pull request closed without merging**
