### PR TITLE
Update version for Azure Services App Authentication

### PR DESCRIPTION
**Pull request by ajcvickers**
See https://github.com/aspnet/Configuration/pull/881/files

/cc @HaoK @joshgav @nonik0

### CODE REVIEW

**Review by Eilon — APPROVED** [review]
I guess this is fine?

**Comment by ajcvickers** [comment]
@joshgav @nonik0 Could you give some more details on why the original PR was sent?

**Comment by natemcmaster** [comment]
See also https://github.com/aspnet/Extensions/blob/master/eng/Dependencies.props#L63. The config packages don't build from this repo anymore.

**Comment by joshgav** [comment]
@ajcvickers from the thread in https://github.com/aspnet/Configuration/pull/881:

to pick up this update: https://github.com/Azure/azure-sdk-for-net/pull/4427, which updates the IMDS endpoint used. The old one no longer works.

Workaround is to manually `dotnet add package ...` with latest version but I didn't recognize the issue for a while :)

Thanks!

**Review by natemcmaster — APPROVED** [review]

**Comment by natemcmaster** [comment]
Yes, I think we have multiple packages that use this dependency.

**Pull request merged**
