### PR TITLE
Update branding to 3.1.12

### PR DESCRIPTION
**Pull request by wtgodbe**
Also update SDK and baseline

### CODE REVIEW

**Comment by wtgodbe** [comment]
nonshipping packages are still in the process of being uploaded to the transport feed, will re-run when that's done

**Review by JunTaoLuo — APPROVED** [review]
When CI passes.

**Review by dougbu — APPROVED** [review]
Seems fine once the CI can find something other than Microsoft.Extensions.Logging.Testing 5.0.0-preview.2.20124.5.

**Pull request merged**
