### PR TITLE
Fixed an html syntax error

### PR DESCRIPTION
**Pull request by mkArtakMSFT**
Fixing a minor html syntax error

Addresses #5206 (in this specific format)

### CODE REVIEW

**Review by pranavkm — APPROVED** [review]

**Comment by mkArtakMSFT** [comment]
Testing something

**Comment by mkArtakMSFT** [comment]
Test something

**Comment by mkArtakMSFT** [comment]
Test something

**Comment by mkArtakMSFT** [comment]
Test 2

**Comment by mkArtakMSFT** [comment]
Test 2

**Pull request merged**
