### PR TITLE
[WIP] Try running tests on helix

### PR DESCRIPTION
**Pull request by HaoK**
🍿 🔥 🚒 🎆

### CODE REVIEW

**Comment by natemcmaster** [comment]
Looks like the Helix SDK isn't loading correctly in MSbuild.exe. It's likely this problem: https://natemcmaster.com/blog/2017/11/11/msbuild-task-with-dependencies/#binding-redirects-and-version-conflicts

**Comment by HaoK** [comment]
Looks like there are a lot of failures due to missing 'sln' file, I will start mass skipping those tests

Identity tests are failing due to no local db on the helix machines (same issue as EF core functionals)

**Comment by natemcmaster** [comment]
I'm uncomfortable with how many `Skip`'s this adds. I would be okay with making them `ConditionalFact` and skipping when running in Helix, but as-is, this decreases our regression coverage significantly.

**Comment by HaoK** [comment]
Yeah I'm just skipping them in this PR for now so its easier for me to see what tests are failing that still need to be investigated.

**Comment by natemcmaster** [comment]
Oh, ok nvm. That's fine. We can fixup when this gets closer to merging.

**Comment by HaoK** [comment]
Yeah there are a lot of failures and this isn't even running the functional tests yet, the vast majority seem to be looking for a sln file at least, hopefully there can be a general fix for that pattern.

I'm just trying to do an initial pass to see what tests are fine, and I'll for now stop running them and just focus on the tests with issues first.

**Comment by HaoK** [comment]
Replaced by https://github.com/aspnet/AspNetCore/pull/6728

**Pull request closed without merging**
