### PR TITLE
Skip failing Libuv test on Alpine

### PR DESCRIPTION
**Pull request by wtgodbe**
https://dev.azure.com/dnceng-public/public/_build/results?buildId=504874&view=results

Fixes https://github.com/dotnet/aspnetcore/issues/50403

### CODE REVIEW

**Review by amcasey — APPROVED** [review]

**Comment by wtgodbe** [comment]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=504970&view=results

**Comment by amcasey** [comment]
I'm confused - do these fail every run or are they flaky?  Maybe they're failing every run and the test runner aborts before discovering other broken tests?

**Comment by wtgodbe** [comment]
> I'm confused - do these fail every run or are they flaky? Maybe they're failing every run and the test runner aborts before discovering other broken tests?

They fail every time

**Comment by amcasey** [comment]
> > I'm confused - do these fail every run or are they flaky? Maybe they're failing every run and the test runner aborts before discovering other broken tests?
> 
> They fail every time

Okay, then keep fighting the good fight. 😆

**Comment by wtgodbe** [comment]
That did it. Will merge this once branches open

**Pull request merged**
