### PR TITLE
adds DynamicComponent.Instance property

### LINKED ISSUE #33504: DynamicComponent should contains property with component instance
Usually all types will implement some common interface through which it is possible to control the component.

### Without this property solution is:
parent component:
```
@page "/before"
@implements IParent
<h3>DynamicBefore</h3>
<CascadingValue Name="Parent" Value="this">
    <DynamicComponent Type="_type"></DynamicComponent>
</CascadingValue>
<button class="btn btn-primary" @onclick="Refresh">Refresh</button>
@code {
    Type _type;
    private IGrid _grid;

    protected override void OnInitialized()
    {
        var type = typeof(string); // dynamically created at runtime type
        _type = typeof(DynamicGrid<>).MakeGenericType(type);
    }

    private void Refresh()
    {
        _grid.Refresh();
    }

    public void SetGrid(IGrid grid)
    {
        _grid = grid;
    }

}

```
DynamicGrid component:
```
@typeparam T
@implements IGrid
<h3>DynamicGrid: @typeof(T).FullName</h3>
@if (_refreshed)
{
    <div>refreshed</div>
}
@code {
    bool _refreshed;

    public void Refresh()
    {
        _refreshed = true;
        StateHasChanged();
    }

    [CascadingParameter(Name = "Parent")]
    public IParent Parent { get; set; }

    protected override void OnParametersSet()
    {
        base.OnParametersSet();
        Parent?.SetGrid(this);
    }

}
```
interfaces:
```
    public interface IGrid
    {
        void Refresh();
    }
    public interface IParent
    {
        void SetGrid(IGrid grid);
    }
```
### with property:
parent:
```
@page "/after"
<h3>DynamicAfter</h3>
<DynamicComponent Type="_type" @ref="_dynamicGrid"></DynamicComponent>
<button class="btn btn-primary" @onclick="Refresh">Refresh</button>
@code {
    Type _type;
    private DynamicComponent _dynamicGrid;

    protected override void OnInitialized()
    {
        var type = typeof(string); // dynamically created at runtime type
        _type = typeof(DynamicGrid<>).MakeGenericType(type);
    }

    private void Refresh()
    {
        ((IGrid)_dynamicGrid.Instance).Refresh();
    }
}
```
DynamicGrid:
```
@typeparam T
@implements IGrid
<h3>DynamicGrid: @typeof(T).FullName</h3>
@if (_refreshed)
{
    <div>refreshed</div>
}
@code {
    bool _refreshed;

    public void Refresh()
    {
        _refreshed = true;
        StateHasChanged();
    }
}
```
interfaces:
```
    public interface IGrid
    {
        void Refresh();
    }
```

### PR DESCRIPTION
**Pull request by proff**
**adds DynamicComponent.Instance property**

fixes #33504

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=33505) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=33505) before we can accept your contribution.<br/><br/>:x: proff [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=33505)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=33505) it.</sub>

**Comment by mkArtakMSFT** [comment]
Thanks for your PR.
To avoid potentially wasting effort, we recommend community members to first get an agreement from the team on whether we are willing to make such a change or not. Only if the team agrees and likes the design discussed in the issue and think it's a good fit for the community to provide a PR for we will accept PRs.
Given that this PR didn't go through that process, we will first evaluate whether the issue is something we'd like to change and then, if we think so, we will review this.

**Comment by proff** [comment]
this is not waste effort, i'm already use it in real .net 5 project

**Comment by SteveSandersonMS** [comment]
> this is not waste effort, i'm already use it in real .net 5 project

Thanks for contributing! Just to clarify, @mkArtakMSFT wasn't suggesting that he thought your contribution was a waste. He was only saying that, as a general principle for how we accept PRs, we normally first expect to have a conversation in a GitHub issue about the problem and the design for solving it. After that conversation and when we're agreed on the approach, *then* it's good to submit a PR. Otherwise there's a risk that we might disagree about the approach taken and then there would have been wasted effort.

However, in this specific case, we agree with you that it's a valuable feature to add. We still need to resolve a question about the perf impact, but we can have this discussion on your PR, so I'll post there.

**Review by SteveSandersonMS — APPROVED** [review]
This, including the tests, all looks good to me.

We discussed the [perf concern here](https://github.com/dotnet/aspnetcore/issues/33504#issuecomment-860636164) and decided it's no different from the Input* components that already do this, and tend to show up in even higher numbers in typical apps, so we're OK with it as-is.

@javiercn Do you have any other concerns?

**Comment by javiercn** [comment]
Nope, good to go as long as you are happy with it.

**Comment by proff** [comment]
@SteveSandersonMS i developed same component before i learned DynamicComponent. With dynamic generic argument type only and static parameters list, but with instance property. I mean that this is not waste, because i'll use merged version in any case.

P.S. should i ignore latest bot comment?

**Comment by SteveSandersonMS** [comment]
Yes, please ignore the latest bot comment. I will take care of the API review process. 

Thanks again for contributing!

**Pull request merged**
