### PR TITLE
Deploy Microsoft.Web.Xdt.Extensions.pdb

### PR DESCRIPTION
**Pull request by dougbu**
- #10495
- add a general mechanism to publish "loose" PDBs

also, correct a typo from af2f647d635d: always publish the log artifacts

### CODE REVIEW

**Comment by dougbu** [comment]
@jkotalik FYI, this might allow you to simplify Microsoft.AspNetCore.ANCMSymbols.csproj

**Comment by dougbu** [comment]
@JunTaoLuo trial internal runs:
- build https://dnceng.visualstudio.com/internal/_build/results?buildId=227139
- release https://dnceng.visualstudio.com/internal/_releaseProgress?releaseId=9329

**Comment by jkotalik** [comment]
Interesting. I'd be curious to see if this works with native projects!

Just to be sure I understand, we do want to publish symbols for this package, correct? IIRC, this package is used by the aspnetcore site extension to change the applicationhost.config file.

**Comment by dougbu** [comment]
> Interesting. I'd be curious to see if this works with native projects!

Symbol .nupkg files are just a transport mechanism. This approach avoids the extra wrapper when the actual package isn't needed.

> we do want to publish symbols for this package, correct? IIRC, this package is used by the aspnetcore site extension to change the applicationhost.config file.

We should publish symbols for every assembly we publish. In this case, it may be unlikely any user would debug the code but that doesn't matter much. (For one thing, checking symbol deployment doesn't allow exclusions and this assembly is shipped in much larger bundles.)

**Review by JunTaoLuo — APPROVED** [review]

**Comment by dougbu** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=227209

**Comment by dougbu** [comment]
Regular AspNetCore-ci build completed successfully but was not reported back to GitHub

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2489

**Comment by dougbu** [comment]
As the Hello bot just confirmed, Helix failure was due to known-flaky tests

**Pull request merged**
