### PR TITLE
HybridCache: reflect API merge into runtime - preview 7 backport

### PR DESCRIPTION
**Pull request by mgravell**
# HybridCache: reflect API merge into runtime

In [runtime 103103](https://github.com/dotnet/runtime/pull/103103), the proposed HybridCache API was moved from a placeholder in aspnetcore into runtime (which owns the Microsoft.Extensions.Caching.Abstractions library). This means that the original API in aspnetcore is now duplicated and redundant. Additionally, runtime requested some minor last-minute API changes (mainly: prefer `cancellationToken` over `token` naming, and prefer `IEnumerable<string>` over `IReadOnlyCollection<string>` for tags parameter)

This PR reflects this merge - removing the duplicated APIs, and fixing the changes impacted by the API delta.

Since 103103 was merged immediately before the preview 7 snap, this will need applying both in `main` and `release/9.0-preview7` after the runtime deps are updated (this is the `release/9.0-preview7` version). Until runtime is built and the deps are updated, aspnetcore may be unbuildable.

Cross-reference: https://github.com/dotnet/aspnetcore/pull/56945/ (`main`)

### CODE REVIEW

**Review by mitchdenny — APPROVED** [review]

**Review by captainsafia — APPROVED** [review]
Changes look good to me as far as reflecting the API that was ultimately approved into runtime.

**Review by wtgodbe — APPROVED** [review]

**Comment by wtgodbe** [comment]
Should cherry-pick this into https://github.com/dotnet/aspnetcore/pull/56962

**Comment by mgravell** [comment]
@wtgodbe  lets see if this works... changed target/base from `release/9.0-preview7` to `darc-release/9.0-preview7-c259b2cd-b00e-4c3b-b2fb-6b98cf9f247a`

**Comment by mgravell** [comment]
tested locally - needed to add back a few more "unshipped" (I guess I got carried away with the <kbd>del</kbd>) - should build now

**Comment by mgravell** [comment]
@wtgodbe definitely improving - https://github.com/dotnet/aspnetcore/pull/56946/checks?check_run_id=27868375271 now just has some unrelated (I hope!) errors in `AesGcmAuthenticatedEncryptor`

**Pull request merged**
