### PR TITLE
Remove extra English installer files

### PR DESCRIPTION
**Pull request by dougbu**
- generally redundant and confusing
- not needed now that OneLocBuild picks up the 1033/thm.wxl files
  - see <https://github.com/dotnet/aspnetcore/blob/95ed45c6710e4e4fa878c4d76e8f5a83eeaf1c3b/eng/common/generate-locproject.ps1#L37-L46>

### CODE REVIEW

**Review by joeloff — APPROVED** [review]

**Comment by wtgodbe** [comment]
Looks like something is still looking for those files:

> light.exe : error LGHT0103: The system cannot find the file 'D:\a\_work\1\s\src\Installers\Windows\SharedFrameworkBundle\thm.wxl'. [D:\a\_work\1\s\src\Installers\Windows\SharedFrameworkBundle\SharedFrameworkBundle.wixproj]
##[error]light.exe(0,0): error LGHT0103: (NETCORE_ENGINEERING_TELEMETRY=Build) The system cannot find the file 'D:\a\_work\1\s\src\Installers\Windows\SharedFrameworkBundle\thm.wxl'.

**Comment by dougbu** [comment]
@joeloff, I'm reading through the WiX sources to find where this error is coming from, but not having much luck. For both bundles, we mention `thm.wxl` in three places
- in [`WixStandardBootstrapperApplication.LocalizationFile`](https://github.com/dotnet/aspnetcore/blob/main/src/Installers/Windows/SharedFrameworkBundle/Bundle.wxs#L10) (bare `thm.wxl`)
- as a [`Payload`](https://github.com/dotnet/aspnetcore/blob/main/src/Installers/Windows/SharedFrameworkBundle/Bundle.wxs#L10) (localized path, including one for 1033 i.e. English)
- as an [`EmbeddedResource`](https://github.com/dotnet/aspnetcore/blob/main/src/Installers/Windows/SharedFrameworkBundle/SharedFrameworkBundle.wixproj#L28) (bare `thm.wxl`)

I'd expect everything to **Just Work :tm:** -- if the `Payload` items get run first. Since that isn't the case, which of the above should change❔ One possibility is that the `EmbeddedResource` is causing this issue but isn't actually needed&hellip;

**Comment by joeloff** [comment]
Hmm, not sure why there's an embedded resource. The bootstrapper application will need to reference the proper file you want, and the payload as well so you may need to update those to only reference the 1033 copy, otherwise it will look for the file adjacent to the bundle's .wxs file.

**Comment by joeloff** [comment]
> Alright, I'm trying removal of the `EmbeddedResource`s first because I've seen online examples where `WixStandardBootstrapperApplication.LocalizationFile` has no locale in the path, but the file exists only in the localized subdirectories.
> 
> I'm also nervous about changing this to be `1033\thm.wxl`, in case that causes the installer to unconditionally display in English. I _think_ `WixStandardBootstrapperApplication` automatically uses the current locale when resolving `LocalizationFile`.

You can test the other locales locally by running the installer from the commandline and passing `/lang <LCID>`, e.g. `/lang 1036` should pop up the French translations. Of course for the case you're mentioning you want to run a non-ENU OS and let the bundle select the locale. I think you can simulate partially by creating a process and setting the Thread cultture and ui culture. Otherwise, you can try Windows Sandbox or a VM and change the OS locale and then just run the installer

**Comment by dougbu** [comment]
Created bundles work fine on a Chinese VM:
image

image

**Pull request merged**
