### PR TITLE
Update stress app

### PR DESCRIPTION
**Pull request by jkotalik**

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]
This is a direct import again?

**Comment by jkotalik** [comment]
Yep.

**Comment by jkotalik** [comment]
I need to rebase this on master now that we have new deps!

Either way things, were hanging in the new stress runs. I'll check if it's a client or server issue in this PR too.

**Comment by jkotalik** [comment]
Going to put this on hold as all scenarios that were added would need to be disabled.

**Comment by jkotalik** [comment]
Closing as we don't need this update.

**Pull request closed without merging**
