### PR TITLE
Fix InputRadioGroupsWithNamesNestedInteractWithEditContext

### PR DESCRIPTION
**Pull request by MackinnonBuck**
### Summary

Fixed an issue where `InputRadio` E2E tests were referencing stale elements. These test failures were caused by a recent bug fix that changed how `InputRadio` components were updated. Only `InputRadioGroupsWithNamesNestedInteractWithEditContext` was reported to be flaky, but I've applied my fixes to `InputRadioGroupWithoutNameInteractsWithEditContext` as well. The fixes remove all instances where `input` elements were being cached, and all browser asserts re-query the elements to avoid using stale element references.

Addresses #24850

### CODE REVIEW

**Review by captainsafia — COMMENTED** [review]
The test changes look good.

Are the changes to the built JavaScript intentional?

**Review by ryanbrandenburg — APPROVED** [review]
Talked offline with @MackinnonBuck, he's reverting  the .js. If @captainsafia is cool with the test changes and he's marking them as Quarantined anyway then I'm good with this.

**Review by captainsafia — APPROVED** [review]

**Comment by BrennanConroy** [comment]
Could we move this to release/5.0 and merge? :)

**Comment by mkArtakMSFT** [comment]
@Pilchie merging this as this is test-only fix.

**Pull request merged**
