### PR TITLE
Naming and template updates

### LINKED ISSUE #6826: Update Razor Components template to use quotes around all attributes in markup
Razor Component template review feedback - required for Preview 2.

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
Fixes #6826, #6824, #6827

### CODE REVIEW

**Review by rynowak — APPROVED** [review]

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT This should be ready. Could it be merged? The AspNetCore-ci failure is unrelated.

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT  Actually please wait. Just spotted a problem.

**Review by rynowak — APPROVED** [review]
Cool, this looks like the fix for what I ran into while trying these out in VS. Once this is merged, I'll confirm again that it works when driven by VS.

**Comment by SteveSandersonMS** [comment]
OK, ready now.

**Review by mkArtakMSFT — APPROVED** [review]

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT As usual, the AspNetCore-ci failure is unrelated, so this should be good to merge now.

**Pull request merged**
