### PR TITLE
Use PackageConflictPreferredPackages for analyzers from transport package

### LINKED ISSUE #34048: Source generators from M.E.Logging.Abstractions conflict with source generators in the transport package
Two copies get added

* microsoft.aspnetcore.internal.transport\6.0.0-preview.7.21352.2\analyzers\dotnet\cs\Microsoft.Extensions.Logging.Generators.dll
* microsoft.extensions.logging.abstractions\6.0.0-preview.7.21352.2\analyzers\dotnet\cs\Microsoft.Extensions.Logging.Generators.dll

which results in conflicts.

### PR DESCRIPTION
**Pull request by wtgodbe**
Should fix https://github.com/dotnet/aspnetcore/issues/34048. Still some open discussion here: https://github.com/dotnet/aspnetcore/issues/34048#issuecomment-1039680290

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
Change looks fine but file lock issues do not 😦

**Comment by wtgodbe** [comment]
> Change looks fine but file lock issues do not 😦

I actually saw that in my local build too - seems like this change makes the file contention issue work (FYI @ericstj) - in light of that it may not be worth doing

**Pull request closed without merging**
