### PR TITLE
Set InvariantGlobalization in api template

### LINKED ISSUE #47029: Consider setting InvariantGlobalization in api template
API server applications often don't need to consider culture behavior. The data flowing in and out of the application is created and consumed by other applications (not humans). This data is typically in a culture independent format because it is consumed by other applications.

We should consider adding `<InvariantGlobalization>true</InvariantGlobalization>` to the `dotnet new api` template. This can easily be removed by the app developer, if their API app needs culture aware behavior. Alternatively, if we really thought the decision should be directly made by the user, we can make it an optional checkbox in the template dialog in VS.

Enabling InvariantGlobalization brings with it some nice performance benefits.

On Windows x64, the [BasicMinimalApi](https://github.com/aspnet/Benchmarks/tree/main/src/BenchmarksApps/BasicMinimalApi) using `EnableRequestDelegateGenerator=true`, the app size goes from:

**main**: `9.70 MB (10,179,072 bytes)`
**InvariantGlobalization**: `9.48 MB (9,945,600 bytes)`

It also appears to help with startup times (linux-x64):

**main**: `Start Time (ms)       | 40`
**InvariantGlobalization**: `Start Time (ms)       | 37`

And memory consumption (linux-x64):

**main**: `Working Set (MB)      | 47`
**InvariantGlobalization**: `Working Set (MB)      | 43`

cc @DamianEdwards @davidfowl @mangod9 @tarekgh

### PR DESCRIPTION
**Pull request by eerhardt**
API server applications do not typically need culture aware behavior. A better default is to use invariant globalization mode for API apps.

This allows for the globalization code to be trimmed away, making the final executable size smaller. It also reduces startup and memory consumption because ICU isn't loaded.

This also allows the apps to run with consistent behavior on container images that don't include ICU, making the container image smaller as well.

Fix #47029

### CODE REVIEW

**Comment by mitchdenny** [comment]
I'm onboard with this. Just want to represent @DamianEdwards opinion that we need to make sure that we've done the right thing in terms of MSBuild docs. We need that checklist in an issue so we can finalize this.

**Comment by captainsafia** [comment]
> I'm onboard with this. Just want to represent @DamianEdwards opinion that we need to make sure that we've done the right thing in terms of MSBuild docs. We need that checklist in an issue so we can finalize this.

I went ahead and took care of this in https://github.com/dotnet/msbuild/pull/8543 since it was fairly straightforward to do.

**Comment by DamianEdwards** [comment]
>>I'm onboard with this. Just want to represent @DamianEdwards opinion that we need to make sure that we've done the right thing in terms of MSBuild docs. We need that checklist in an issue so we can finalize this.

>I went ahead and took care of this in https://github.com/dotnet/msbuild/pull/8543 since it was fairly straightforward to do.

Right, we just need to follow up on VS property page support.

**Review by JamesNK — DISMISSED** [review]
Update other templates? webapi, grpc, worker?

Figure out how to test that culture is disabled. I'm not sure how to easily do this. The default template endpoints are returning invariant data already.

**Review by captainsafia — APPROVED** [review]

**Comment by eerhardt** [comment]
> @eerhardt If enabled by default,SqlClient will throw an [exception](https://github.com/dotnet/SqlClient/issues/1913)

The simple workaround in that case is to just remove this line from the .csproj then.

**Comment by AlmightyLks** [comment]
Breaks usage with EFC (Or [SqlClient](https://github.com/dotnet/SqlClient/issues/2239)?) and thus makes ASP.NET Core 8 incompatible with EFC (/ SqlClient) by default

**Comment by roji** [comment]
FYI this is purely a SqlClient-related issue that has nothing to do with EF per se.

**Pull request merged**
