### PR TITLE
Clean up some stale comments

### PR DESCRIPTION
**Pull request by Pilchie**
Addresses AzDO Bug #890301 (https://dev.azure.com/devdiv/DevDiv/_workitems/edit/890301/)

### CODE REVIEW

**Review by jkotalik — APPROVED** [review]

**Comment by SteveSandersonMS** [comment]
For the change in MonoProxy.cs (which I totally understand, this is not the style of commenting we use!), we get this file on a “shared source” basis from https://github.com/mono/mono/blob/master/sdks/wasm/Mono.WebAssembly.DebuggerProxy/MonoProxy.cs

So it would be fine to merge this change in our repo, but to be sure it doesn’t come back next time we update, it would be ideal to also do a PR to the Mono repo to fix the underlying source.

**Review by SteveSandersonMS — APPROVED** [review]

**Comment by Eilon** [comment]
Who will do the PR to Mono?

**Comment by Pilchie** [comment]
I will.

**Comment by jkotalik** [comment]
Also the code from IIS is shared source too. I'll file a PR there too.

**Comment by Pilchie** [comment]
Since I'm new here, do I need more than this, or can I go ahead and hit Merge?

**Comment by jkotalik** [comment]
Go ahead and merge. Just make sure that you squash and merge on github:
image

**Comment by Pilchie** [comment]
First PR to AspNetCore, and first time using the squash functionality both at once.

**Comment by rynowak** [comment]
> First PR to AspNetCore, and first time using the squash functionality both at once.

image

**Pull request merged**
