### PR TITLE
Actually use correct versions in vs packages

### PR DESCRIPTION
**Pull request by jkotalik**
Missed some dollar signs when passing in the version to the package name.

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
Oops 😈

**Comment by dougbu** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=240388

**Comment by dougbu** [comment]
@jkotalik are you going to mark `ResponseBodyWriteExceptions_ClientDisconnectsBeforeFirstWriteAsync_WriteThrows` as flaky? If not I can retry the failing leg of the build.

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2314

**Comment by jkotalik** [comment]
Chris already resolved the test failure here https://github.com/aspnet/AspNetCore/pull/11628

**Pull request merged**
