### PR TITLE
Remove aspnet/Scaffolding submodule

### PR DESCRIPTION
**Pull request by dougbu**
- aspnet/AspNetCore-Internal#1341

### CODE REVIEW

**Comment by dougbu** [comment]
@natemcmaster I'm seeing the following errors in the CI checks. We previously got versions for these packages from the Scaffolding submodule. 

I see references to these `Microsoft.VisualStudio.Web.CodeGeneration.*` packages in `build\artifacts.props` and `src\PackageArchive\Scenario.WebApp\Scenario.WebApp.csproj` but we no longer have anything that sets e.g. `$(MicrosoftVisualStudioWebCodeGenerationContractsPackageVersion)`. **Should those lines be removed?**

```
2019-01-31T20:30:52.8075783Z /home/vsts/work/1/s/build/repo.targets(135,5): error : Could not detect version information for package id: [/home/vsts/work/1/.dotnet/buildtools/korebuild/2.1.7-build-20190110.2/KoreBuild.proj]
2019-01-31T20:30:52.8077273Z /home/vsts/work/1/s/build/repo.targets(135,5): error :  * dotnet-aspnet-codegenerator [/home/vsts/work/1/.dotnet/buildtools/korebuild/2.1.7-build-20190110.2/KoreBuild.proj]
2019-01-31T20:30:52.8078068Z /home/vsts/work/1/s/build/repo.targets(135,5): error :  * Microsoft.VisualStudio.Web.CodeGeneration.Contracts [/home/vsts/work/1/.dotnet/buildtools/korebuild/2.1.7-build-20190110.2/KoreBuild.proj]
2019-01-31T20:30:52.8078844Z /home/vsts/work/1/s/build/repo.targets(135,5): error :  * Microsoft.VisualStudio.Web.CodeGeneration.Core [/home/vsts/work/1/.dotnet/buildtools/korebuild/2.1.7-build-20190110.2/KoreBuild.proj]
2019-01-31T20:30:52.8079570Z /home/vsts/work/1/s/build/repo.targets(135,5): error :  * Microsoft.VisualStudio.Web.CodeGeneration.Design [/home/vsts/work/1/.dotnet/buildtools/korebuild/2.1.7-build-20190110.2/KoreBuild.proj]
2019-01-31T20:30:52.8080537Z /home/vsts/work/1/s/build/repo.targets(135,5): error :  * Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore [/home/vsts/work/1/.dotnet/buildtools/korebuild/2.1.7-build-20190110.2/KoreBuild.proj]
2019-01-31T20:30:52.8081384Z /home/vsts/work/1/s/build/repo.targets(135,5): error :  * Microsoft.VisualStudio.Web.CodeGeneration.Templating [/home/vsts/work/1/.dotnet/buildtools/korebuild/2.1.7-build-20190110.2/KoreBuild.proj]
2019-01-31T20:30:52.8082555Z /home/vsts/work/1/s/build/repo.targets(135,5): error :  * Microsoft.VisualStudio.Web.CodeGeneration.Utils [/home/vsts/work/1/.dotnet/buildtools/korebuild/2.1.7-build-20190110.2/KoreBuild.proj]
2019-01-31T20:30:52.8083884Z /home/vsts/work/1/s/build/repo.targets(135,5): error :  * Microsoft.VisualStudio.Web.CodeGeneration [/home/vsts/work/1/.dotnet/buildtools/korebuild/2.1.7-build-20190110.2/KoreBuild.proj]
2019-01-31T20:30:52.8085184Z /home/vsts/work/1/s/build/repo.targets(135,5): error :  * Microsoft.VisualStudio.Web.CodeGenerators.Mvc [/home/vsts/work/1/.dotnet/buildtools/korebuild/2.1.7-build-20190110.2/KoreBuild.proj]
```

**Comment by dougbu** [comment]
Separately, has something regressed on the agents we're using? File locking conflict warnings now seem common.

**Comment by natemcmaster** [comment]
You'll need to remove Scaffolding from these files too:

https://github.com/aspnet/AspNetCore/blob/release/2.1/build/submodules.props
https://github.com/aspnet/AspNetCore/blob/release/2.1/build/buildorder.props

**Comment by dougbu** [comment]
> We will treat the scaffolding packages like any other 'external dependency'.

Hmm, I don't see any references to Scaffolding packages except in src\PackageArchive\Scenario.WebApp\Scenario.WebApp.csproj. Would it be "better" to remove that dependency?

**Comment by dougbu** [comment]
> with their value set to 2.1.7 ~~(and 2.2.1 for release/2.2)~~

@natemcmaster I see no need for these version variables in `release/2.2`. Am I missing something?

**Comment by dougbu** [comment]
No longer a WIP and required CI checks have passed.

**Review by natemcmaster — APPROVED** [review]

**Pull request merged**
