### PR TITLE
Port ANCM current directory changes to 2.2

### PR DESCRIPTION
**Pull request by pakrym**
Ports #6066 #4798  #4369

# Description:

In `InProcess` hosting mode process current directory is not set to application physical path location like it was in `OutOfProcess` causing hard to diagnose exception in `Program.Main` for a lot of customers. (https://github.com/aspnet/AspNetCore/issues/6118 https://github.com/aspnet/AspNetCore/issues/6117 https://github.com/aspnet/AspNetCore/issues/4206 https://github.com/aspnet/AspNetCore/issues/5961  https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore/issues/55 and more)

This change makes process current directory to be application physical path by default.

# Regression?

Regression from OutOfProcess hosting mode.

# Risk:

Medium-Low. It's hard to predict all the effects changing current directory might have on IIS worker process but testing didn't show any negative ones.
Some things to consider:

1. IIS Express and Hostable Web Core that share most of the code with `w3wp` support working from any current directory
1. We reset DllDirectory to point to the original CurrentDirectory to restore dll lookup order.
1. There is a `handlerSetting` option to opt-out of new behaviour.
1. This change was in master for some time now and didn't reveal any issues.
1. Workaround we provide to customers changes current directory process-wide and no side-effects were reported.

### CODE REVIEW

**Review by jkotalik — APPROVED** [review]

**Comment by natemcmaster** [comment]
Needs to be rebased on release/2.2 code reorganization.

**Comment by vivmishra** [comment]
We should bring this back to Shiproom with ANCM folks present.

**Comment by jamshedd** [comment]
@muratg The PR needs to be cleaned up. Cherry pick just the needed commit.

**Comment by muratg** [comment]
@pakrym This PR shouldn't have the file renames, keep that in master. And there are conflicts as seen above. Please do the needful and let me know.

**Comment by pakrym** [comment]
@muratg release/2.2 was force pushed from under my PR. I'll remerge.

**Comment by jamshedd** [comment]
Approved for 2.2.2.

**Comment by dougbu** [comment]
Before merging, please update the 2.2.2 section of eng/PatchConfig.props: https://github.com/aspnet/Extensions/blob/d8407116d183debaadb801c0cbc41d65927999d6/eng/PatchConfig.props#L7-L10

**Comment by pakrym** [comment]
Did it in https://github.com/aspnet/AspNetCore/pull/6483

**Comment by pakrym** [comment]
Test failure: https://github.com/aspnet/AspNetCore/issues/6691

**Pull request merged**
