### PR TITLE
Add hidden input for easier binding in static edit forms

### PR DESCRIPTION
**Pull request by garrettlondon1**
Addresses https://github.com/dotnet/aspnetcore/issues/55720

### CODE REVIEW

**Comment by garrettlondon1** [comment]
I figured people will be binding hidden inputs to primary keys that will vary by type which is the reason for generic param TValue

**Comment by mkArtakMSFT** [comment]
Thanks for your PR, @garrettlondon1. Please make sure you include tests with your change. Here is InputNumber tests as an example: https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/test/Forms/InputNumberTest.cs

**Comment by SteveSandersonMS** [comment]
While I'm personally fine with us adding this, I'd add that AFAICT this is exactly the same as:

```razor
<InputText type="hidden" @bind-Value="..." />
```

So it's not like it's difficult to create a hidden input already, but I agree it's nonobvious to do it via `InputText`. Creating a dedicated `InputHidden` seems reasonable to me.

**Comment by SteveSandersonMS** [comment]
> I figured people will be binding hidden inputs to primary keys that will vary by type which is the reason for generic param TValue

That seems reasonable, but this PR would need E2E tests showing that working with a range of types, being clear about what are the supported conditions for it working (e.g., does it work with custom `ToString`, custom typeconverters, etc.).

**Pull request closed without merging**
