### PR TITLE
Skip WebSocketOutOfProcessTests on Windows.Amd64.Server2022.Open

### PR DESCRIPTION
**Pull request by captainsafia**
Addresses https://github.com/dotnet/aspnetcore/issues/59111.

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Huh, maybe skip attributes on abstract classes aren't discovered
https://github.com/dotnet/aspnetcore/blob/3ba179ad088127e35a2a3e4ca8bc24bfc099fef2/src/Servers/IIS/IIS/test/Common.FunctionalTests/WebSocketTests.cs#L32-L37

This is what we should do in both WebSocketsOutOfProcess and WebSocketsInProcess then.
{4CDAF7EB-1C97-44FC-B5E6-D6E9FDC56A0B}

**Comment by BrennanConroy** [comment]
WebSocketsInProcess too

**Comment by captainsafia** [comment]
> WebSocketsInProcess too

I didn't spot any failures in the in-process tests. Do we want to update the annotation as a proactive measure since they use the same base class?

**Comment by BrennanConroy** [comment]
The screenshot I shared in https://github.com/dotnet/aspnetcore/pull/59112#issuecomment-2494440376 shows in process failing as well. It was from the latest Helix run.

**Review by BrennanConroy — APPROVED** [review]

**Pull request merged**
