### PR TITLE
Fix typo in RequestImageFileAsync argument name

### PR DESCRIPTION
**Pull request by scoizzle**
Argument name should be 'maxWidth' not 'maxWith'.

### CODE REVIEW

**Comment by Eilon** [comment]
BTW this is a source-code breaking change because this API already shipped: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.forms.browserfileextensions.requestimagefileasync?view=aspnetcore-5.0

Still a good change, though.

**Comment by scoizzle** [comment]
It's unfortunate, that's for sure. I won't be surprised if the change is declined but at least it was documented.

**Comment by captainsafia** [comment]
@scoizzle We're interested in taking this change so thanks for the PR!

You'll need to modify the PublishedAPI.txt file in this directory, as referenced in the build errors, to get this PR in a green state. We use those text files to track what public APIs are produced from each namespace so it should match the function signatures.

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=29245) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=29245) before we can accept your contribution.<br/><br/>:x: scoizzle [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=29245)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=29245) it.</sub>

**Review by captainsafia — APPROVED** [review]
This was approved during API review today.

Since it is _technically_ a breaking change, we will be making an announcement alongisde this. I'll draft up the announcement issue.

**Pull request merged**
