### PR TITLE
chore - Use `HttpMethods`

### PR DESCRIPTION
**Pull request by ShreyasJejurkar**
Use `HttpMethods` instead of hardcoding.

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
Thanks for your PR, @ShreyasJejurkar.
@javiercn can you please review this? Thanks!

**Comment by pranavkm** [comment]
@ShreyasJejurkar looks like this change triggers some sort of bug in Moq / Castle.Core e.g.

```C#
System.TypeLoadException : Could not load type 'System.Threading.Tasks.MethoMicrosoft.AspNetCore.Http.Abstractions' from assembly 'System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.

   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
...  Castle.DynamicProxy.Contributors.InterfaceProxyWithoutTargetContributor.CollectElementsToProxyInternal(IProxyGenerationHook hook)+MoveNext()
   at Moq.CastleProxyFactory.CreateProxy(Type mockType, IInterceptor interceptor, Type[] interfaces, Object[] arguments)
   at Moq.Mock`1.InitializeInstancePexProtected()
   at Moq.PexProtector.Invoke(Action action)
   at Moq.Mock`1.InitializeInstance()
   at Moq.Mock`1.OnGetObject()
   at Moq.Mock.get_Object()
   at Moq.Mock`1.get_Object()
   at Microsoft.AspNetCore.Authorization.Test.AuthorizationMiddlewareResultHandlerTests.CallRequestDelegate_If_PolicyAuthorizationResultSucceeded() in /_/src/Security/Authorization/test/AuthorizationMiddlewareResultHandlerTests.cs:line 26
--- End of stack trace from previous location ---
```

One option might be to update the tests to not use Moq to produce a `RequestDelegate:


```diff
- var requestDelegate = new Mock<RequestDelegate>();
+ RequestDelegate requestDelegate = (_, _) => Task.CompletedTask;
```

FYI @HaoK

**Comment by ShreyasJejurkar** [comment]
@pranavkm This is so surprising and unexpected. The change is quite small and ideally should not affect any kind of unwanted behavior. We are just changing hardcoded Http Method string values to the constant that we have in the system. 

Not sure how this affects the tests!?

Waiting for @HaoK for more info on this!

**Comment by HaoK** [comment]
Yeah I don't know why this causes moq to blow up, can you try what @pranavkm suggested and swap out the mock request delegate with a no-op one?

**Comment by ShreyasJejurkar** [comment]
@pranavkm Based on your suggestions, I changed the method like below. But now how I can verify `requestDelegate` as it's not `Moq` object now. 

image

image

**Comment by ShreyasJejurkar** [comment]
One more thing, with the previous change, I ran the tests on the code and it worked just fine. 

image

I think CI was facing some temporary issues. Can we re-trigger the CI to see, does it still fails!?

**Review by pranavkm — APPROVED** [review]

**Pull request merged**
