### PR TITLE
Update template icons to higher resolution versions

### LINKED ISSUE #51417: Template icons appear blurry in Visual Studio on high DPI monitors
The majority of our project templates are configured to use fixed resolution PNG files of fairly small dimensions as their icons. This results in them appearing blurry in Visual Studio when using high resolution monitors, e.g. 4K running at 150% scale.

The templates should be using ICO files containing multiple versions of the icon at different dimensions.

### PR DESCRIPTION
**Pull request by DamianEdwards**
Updates the templates to use ICO files containing multiple resolutions of the image instead of PNG files.

Fixes #51417

### CODE REVIEW

**Comment by danmoseley** [comment]
just curious why png as well as ico?
eg
image

**Comment by danmoseley** [comment]
for what its worth, for C# class library, VS seems to use PNG's of various sizes in two different transparencies. (I am looking at resources in csproj.dll which seems to be where they come from?)

I am not familiar with authoring templates, but does VS offer any guidance? I don't see any guidance eg on dotnet/templating or dotnet/templates.

**Comment by phenning** [comment]
> for what its worth, for C# class library, VS seems to use PNG's of various sizes in two different transparencies. (I am looking at resources in csproj.dll which seems to be where they come from?)
> 
> I am not familiar with authoring templates, but does VS offer any guidance? I don't see any guidance eg on dotnet/templating or dotnet/templates.
> 
> perhaps a q for @phenning

We actually include many of the non-web templates inside a "fallback" template pack that we ship in VS, this allows us to override some metadata for templates from within Visual Studio, including providing icons for cases where the original template pack does not contain any icon.

Example in this source tree (there is a readme.md at the FallbackHostData folder) which explains where certain icons came from.
https://devdiv.visualstudio.com/DevDiv/_git/WebTools?path=/src/TemplateEngine/FallbackHostDataPackage/content/Microsoft.Common.Console.CSharp/.template.config/ide/ConsoleApplicationCS.ico

We needed to do this when we first implemented the new project experience, since prior to this, the console template was based on a vstemplate file which referenced a VS package and resource ID, while the web templates always had icons, since before then we had our own custom wizard for web templates and icons were used there.  

Note that If the template actually supplies the icon inside template content, we will use the template from the pack instead.

**Review by phenning — APPROVED** [review]
Technically, you could leave the "icon" property from the host file, Ide/icon.ico is one of the files we will automatically find, but being explicit is OK too.

**Comment by DamianEdwards** [comment]
> just curious why png as well as ico?
@danmoseley typo? Did you mean to say "png as well as bmp"? And you mean inside the ICO itself? If so, it's because PNG supports transparency and is used for 32-bit color-depth (24-bits for color, 8-bits for alpha) scenarios, whereas BMP is used for 8-bit (256 color) scenarios.

**Comment by danmoseley** [comment]
> Did you mean to say "png as well as bmp"? And you mean inside the ICO itself?

Yes, oops.

>  PNG supports transparency and is used for 32-bit color-depth (24-bits for color, 8-bits for alpha) scenarios, whereas BMP is used for 8-bit (256 color) scenarios.

I see 32 bit BMP's in there, above?

**Comment by DamianEdwards** [comment]
> I see 32 bit BMP's in there, above?

Ah right you are. These assets were provided by the UX design team so not sure of the reason behind different internal formats.

**Comment by danmoseley** [comment]
@phenning thanks for the info. It sounds like then there is no documented guidance for the content of the ico's in item/project templates (wrt format, size, transparency)?

Not suggesting this change is wrong, I just like understanding things. (When I worked on Windows stuff, we had size budgets and even trimmed some entries from the ico's.)

**Pull request merged**
