### PR TITLE
Transport.Sockets.IOQueue -> IThreadPoolWorkItem

### PR DESCRIPTION
**Pull request by benaadams**
Resolves https://github.com/aspnet/AspNetCore/issues/4357

In combination with https://github.com/dotnet/coreclr/pull/21159 this is the final piece to bring the steady state allocations for Plaintext Platform to 0 bytes/s (for 7M+ request/s) in .NET Core 3.0

image

Which fits with the goals of aspnet applications being able to run under lower memory conditions (See: ["Proposal for .NET Core GC Support for Docker Limits"](https://github.com/dotnet/designs/blob/261698cb9c56bab0bc7b54b938fa097d729a144f/proposed/support-for-docker-limits.md))

/cc @sebastienros @halter73 @pakrym @davidfowl @Tratcher

### CODE REVIEW

**Comment by pakrym** [comment]
LGTM

**Review by halter73 — APPROVED** [review]

**Comment by halter73** [comment]
@sebastienros Can you benchmark this?

**Comment by benaadams** [comment]
In combination with https://github.com/dotnet/coreclr/pull/21159 this is the final piece to bring the steady state allocations for Plaintext Platform to 0 bytes/s for 7M+ request/s in .NET Core 3.0

Which fits with the goals of aspnet applications being able to run under lower memory conditions (See: ["Proposal for .NET Core GC Support for Docker Limits"](https://github.com/dotnet/designs/blob/261698cb9c56bab0bc7b54b938fa097d729a144f/proposed/support-for-docker-limits.md))

**Review by davidfowl — APPROVED** [review]

**Comment by davidfowl** [comment]
We need to collect a profile on Linux. To make sure we slash the allocations across the board.

**Comment by sebastienros** [comment]
Benchmarking PlatformPlaintext on Windows with 512 connections

|         Description |       RPS | CPU (%) | Memory (MB) | Avg. Latency (ms) | Startup (ms) | First Request (ms) | Latency (ms) | Ratio |
| ------------------- | --------- | ------- | ----------- | ----------------- | ------------ | ------------------ | ------------ | ----- |
|            Baseline | 3,411,048 |      80 |         327 |               5.3 |          250 |               27.7 |          0.4 |  1.00 |
| IThreadPoolWorkItem | 3,439,712 |      80 |         282 |               5.2 |          248 |               30.1 |          0.5 |  1.01 |

**Comment by benaadams** [comment]
Memory 327 MB -> 282 MB suggests a positive impact 😄

**Comment by pakrym** [comment]
@benaadams do you mind rebasing this?

**Comment by benaadams** [comment]
Rebased

**Comment by benaadams** [comment]
CI errors https://github.com/aspnet/AspNetCore/issues/6127,  #6135 and #6136

**Pull request merged**
