### PR TITLE
Update check for 413 in IIS

### PR DESCRIPTION
**Pull request by jkotalik**
Fixes currently failing Helix tests which test the status code returned by an IIS module. A recent patch was released that changed the status code from 404 to 413.

This is affecting Windows.10.Amd64.ClientRS4.VS2017.Open and Windows.10.Amd64.Open. Windows.10.Amd64.ClientRS4.VS2017.Open is still being used in 3.0/3.1 @HaoK should that be changed?

### CODE REVIEW

**Comment by jkotalik** [comment]
@anurse tellmode change to fix a test that was broken by a windows patch.

**Review by Tratcher — APPROVED** [review]

**Comment by HaoK** [comment]
Helix tests passing isn't required in any of the other branches, so I don't think its particularly worth porting changes to the checks unless there's a reason to?  I'm trying to get more helix tests required as part of the PR checks in master, but I don't think we get any benefit of doing that for past releases.

**Comment by jkotalik** [comment]
> Helix tests passing isn't required in any of the other branches, so I don't think its particularly worth porting changes to the checks unless there's a reason to? I'm trying to get more helix tests required as part of the PR checks in master, but I don't think we get any benefit of doing that for past releases.

I'd rather have helix at least sometimes be green than never. If this fix isn't backported, helix will never pass on 3.0 and 3.1.

**Comment by HaoK** [comment]
Oh, I wasn't talking about this fix, I was just referring to changing the helix queues being run in master

**Comment by jkotalik** [comment]
> Oh, I wasn't talking about this fix, I was just referring to changing the helix queues being run in master

Got it. I didn't know if the policy was to have all infrastructure between 3.0, 3.1, and 5.0 be the same or not. IIRC, we want as many infrastructure changes to be the same across all three, but if this isn't one you want to backport, I'm fine with that.

**Comment by anurse** [comment]
Good to go for me. Are we doing this in 3.0? It's tell mode for infra so it's fine, I just need to know what to put in my tactics mail ;P.

**Comment by jkotalik** [comment]
Yeah, 3.0 as these tests were introduced there. Otherwise, these tests would always fail in 3.0.

**Pull request merged**
