### PR TITLE
Remove user id from logs in order to comply GDPR

### PR DESCRIPTION
**Pull request by Kahbazi**
- Remove user id and username from logs
- Remove user id from exceptions since they are most likely to end up in logs as well.  

Addresses https://github.com/aspnet/AspNetCore/issues/16864

@blowdart @HaoK

### CODE REVIEW

**Comment by jkotalik** [comment]
@Kahbazi looks like there are a good number of tests that need to be updated as well. https://dev.azure.com/dnceng/public/_build/results?buildId=442763&view=ms.vss-test-web.build-test-results-tab&runId=14114370&resultId=105121&paneView=debug

**Comment by HaoK** [comment]
Looks good now just need to update the ref assembly to account for the async being removed

**Comment by HaoK** [comment]
@Kahbazi do you mind rebasing against master and I can get this in? Sorry for the delay

**Comment by NinoFloris** [comment]
Could potentially log all messages at the current level AND at trace where only the latter contains a user id? @HaoK Many of these messages are useless without knowing who the actor is.

**Comment by HaoK** [comment]
@blowdart thoughts?  @NinoFloris has a good point that I'm not really sure there's even a point logging these without the user id.  Should we just change everything to a different level?

**Comment by HaoK** [comment]
@blowdart final check on what we want to do here?

**Comment by blowdart** [comment]
Trace doesn't seem enough to be honest. Proceed with removal, and if there are gaps anywhere where a dev can't put their own message via an event in we should look at addressing those in 6.

**Comment by HaoK** [comment]
Ok I will merge this once this is unstale and green again

**Review by HaoK — APPROVED** [review]

**Comment by HaoK** [comment]
@blowdart do we need an announcement for this change?

**Comment by HaoK** [comment]
Thanks @Kahbazi

**Comment by blowdart** [comment]
Yes, I would, preferably with samples of how to log PII if they need to via events

**Comment by HaoK** [comment]
Via events?  They would likely have to override the managers and methods

**Comment by HaoK** [comment]
This is identity not cookie auth unfortunately

**Comment by NinoFloris** [comment]
Couldn't it get a switch like EF Core has?

https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontextoptionsbuilder.enablesensitivedatalogging?view=efcore-3.1

**Comment by Kahbazi** [comment]
@blowdart @HaoK Is there any announcement for this change? I couldn't find any. I thought maybe it's necessary for 5.0.

**Pull request merged**
