### PR TITLE
Adding community identity providers to the /src/Identity/README.md

### PR DESCRIPTION
**Pull request by dlmelendez**
Summary of the changes (Less than 80 chars)
 - Adding Azure Table Storage project site to /src/Identity/README.md
 - Adding CosmosDB SQL repository link to /src/Identity/README.md

Documentation only, no real code here.

### CODE REVIEW

**Comment by dlmelendez** [comment]
Any feedback on this yet? Just a simple readme.md change to some identity providers. Thanks!

**Comment by dlmelendez** [comment]
Any feedback on this yet? Just a simple readme.md change to some identity providers. Thanks!

**Review by pranavkm — APPROVED** [review]
FYI @HaoK

**Review by pranavkm — APPROVED** [review]
Thanks!

FYI @blowdart \ @HaoK

**Pull request merged**
