### PR TITLE
[release/2.1] Correct and streamline internal builds

### PR DESCRIPTION
**Pull request by dougbu**
- correct manual internal builds
    - need to explicitly set `$(BuildNumber)` property in all build steps
    - change `$(BuildScriptArgs)` name to avoid circular reference
- skip tests by default in internal non-PR builds

nits:
- include new `$(BuildNumberArg)` in `$(SharedFxArgs)`
- run all test jobs in internal pull requests

Also includes overall build fix, copied from #30164

### CODE REVIEW

**Comment by dougbu** [comment]
Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1026844

**Comment by dougbu** [comment]
Purely infrastructure and therefore `tell-mode`

**Comment by dougbu** [comment]
Any objection to `tell-mode` @Pilchie❔

**Comment by dougbu** [comment]
Baselines: https://dev.azure.com/dnceng/internal/_build/results?buildId=1026812 (internal build of #30639 containing some overlapping commits to this PR) and https://dev.azure.com/dnceng/public/_build/results?buildId=1026843 (public build of this PR) _did_ run tests.

Unfortunately, https://dev.azure.com/dnceng/internal/_build/results?buildId=1026844 (internal build of this PR) also run tests. Suspect `env:` is in the wrong place&hellip;

**Comment by dougbu** [comment]
New sample build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1026905

**Comment by dougbu** [comment]
Latest internal build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1026917

**Review by wtgodbe — APPROVED** [review]

**Comment by wtgodbe** [comment]
Thanks!

**Comment by Pilchie** [comment]
No objection to `tell-mode`.

**Comment by dougbu** [comment]
@wtgodbe what are the SharedFx-{platform}.ProjectImports.zip files e.g. https://dev.azure.com/dnceng/_apis/resources/Containers/6457484/artifacts-Linux-Musl-SharedFx?itemPath=artifacts-Linux-Musl-SharedFx%2Flogs%2FSharedFx-linux-musl-x64.ProjectImports.zip for❔ I downloaded one and it seems to contain all files from the repo.

**Comment by dougbu** [comment]
Do **not** merge proactively. I want to double-check https://dev.azure.com/dnceng/internal/_build/results?buildId=1030342

**Comment by dougbu** [comment]
Official builds still hit a lot of NU5123 errors with `*.map` files e.g. in the "Build linux-musl-x64 SharedFX" job, 
``` text
/code/build/.dotnet/sdk/2.1.522/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(202,5): error NU5123: The file 'runtimes/linux-musl-x64/lib/netcoreapp2.1/Microsoft.AspNetCore.Authentication.Abstractions.ni.{da691088-1d16-422b-a976-0053e603d4f0}.map' path, name, or both are too long. Your package might not work without long file path support. Please shorten the file path or file name. [/code/build/.w/linux-musl-x64/Symbols/Microsoft.AspNetCore.App/runtime.linux-musl-x64.Microsoft.AspNetCore.App.csproj]
/code/build/.dotnet/sdk/2.1.522/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(202,5): error NU5123: The file 'runtimes/linux-musl-x64/lib/netcoreapp2.1/Microsoft.AspNetCore.Authentication.Cookies.ni.{01c9a2c7-89e3-403b-b097-ce406b540626}.map' path, name, or both are too long. Your package might not work without long file path support. Please shorten the file path or file name. [/code/build/.w/linux-musl-x64/Symbols/Microsoft.AspNetCore.App/runtime.linux-musl-x64.Microsoft.AspNetCore.App.csproj]
/code/build/.dotnet/sdk/2.1.522/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(202,5): error NU5123: The file 'runtimes/linux-musl-x64/lib/netcoreapp2.1/Microsoft.AspNetCore.Authentication.Core.ni.{4af1c091-57c0-49c5-a035-75c3c519737b}.map' path, name, or both are too long. Your package might not work without long file path support. Please shorten the file path or file name. [/code/build/.w/linux-musl-x64/Symbols/Microsoft.AspNetCore.App/runtime.linux-musl-x64.Microsoft.AspNetCore.App.csproj]
/code/build/.dotnet/sdk/2.1.522/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(202,5): error NU5123: The file 'runtimes/linux-musl-x64/lib/netcoreapp2.1/Microsoft.AspNetCore.Authentication.Facebook.ni.{be6811cc-b147-466b-bd83-ba94e19dfd9d}.map' path, name, or both are too long. Your package might not work without long file path support. Please shorten the file path or file name. [/code/build/.w/linux-musl-x64/Symbols/Microsoft.AspNetCore.App/runtime.linux-musl-x64.Microsoft.AspNetCore.App.csproj]
/code/build/.dotnet/sdk/2.1.522/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(202,5): error NU5123: The file 'runtimes/linux-musl-x64/lib/netcoreapp2.1/Microsoft.AspNetCore.Authentication.Google.ni.{5ae50644-1b1e-43b9-a99c-9ca496015af1}.map' path, name, or both are too long. Your package might not work without long file path support. Please shorten the file path or file name. [/code/build/.w/linux-musl-x64/Symbols/Microsoft.AspNetCore.App/runtime.linux-musl-x64.Microsoft.AspNetCore.App.csproj]
/code/build/.dotnet/sdk/2.1.522/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(202,5): error NU5123: The file 'runtimes/linux-musl-x64/lib/netcoreapp2.1/Microsoft.AspNetCore.Authentication.JwtBearer.ni.{b632600f-0bd1-495c-a691-51d0834d6306}.map' path, name, or both are too long. Your package might not work without long file path support. Please shorten the file path or file name. [/code/build/.w/linux-musl-x64/Symbols/Microsoft.AspNetCore.App/runtime.linux-musl-x64.Microsoft.AspNetCore.App.csproj]
/code/build/.dotnet/sdk/2.1.522/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(202,5): error NU5123: The file 'runtimes/linux-musl-x64/lib/netcoreapp2.1/Microsoft.AspNetCore.Authentication.MicrosoftAccount.ni.{b2764031-766d-4b69-b176-1a71358d06bd}.map' path, name, or both are too long. Your package might not work without long file path support. Please shorten the file path or file name. [/code/build/.w/linux-musl-x64/Symbols/Microsoft.AspNetCore.App/runtime.linux-musl-x64.Microsoft.AspNetCore.App.csproj]
/code/build/.dotnet/sdk/2.1.522/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(202,5): error NU5123: The file 'runtimes/linux-musl-x64/lib/netcoreapp2.1/Microsoft.AspNetCore.Authentication.OAuth.ni.{d5257217-e971-42a8-aed2-3647ba158c07}.map' path, name, or both are too long. Your package might not work without long file path support. Please shorten the file path or file name. [/code/build/.w/linux-musl-x64/Symbols/Microsoft.AspNetCore.App/runtime.linux-musl-x64.Microsoft.AspNetCore.App.csproj]
/code/build/.dotnet/sdk/2.1.522/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(202,5): error NU5123: The file 'runtimes/linux-musl-x64/lib/netcoreapp2.1/Microsoft.AspNetCore.Authentication.OpenIdConnect.ni.{f76515da-ed02-4451-be2f-4d1dd921dab7}.map' path, name, or both are too long. Your package might not work without long file path support. Please shorten the file path or file name. [/code/build/.w/linux-musl-x64/Symbols/Microsoft.AspNetCore.App/runtime.linux-musl-x64.Microsoft.AspNetCore.App.csproj]
/code/build/.dotnet/sdk/2.1.522/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(202,5): error NU5123: The file 'runtimes/linux-musl-x64/lib/netcoreapp2.1/Microsoft.AspNetCore.Authentication.Twitter.ni.{61db7198-c831-4ead-8b7a-28d5f7af68af}.map' path, name, or both are too long. Your package might not work without long file path support. Please shorten the file path or file name. [/code/build/.w/linux-musl-x64/Symbols/Microsoft.AspNetCore.App/runtime.linux-musl-x64.Microsoft.AspNetCore.App.csproj]
/code/build/.dotnet/sdk/2.1.522/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(202,5): error NU5123: The file 'runtimes/linux-musl-x64/lib/netcoreapp2.1/Microsoft.AspNetCore.Authentication.WsFederation.ni.{bf9053aa-f446-483e-8988-508db4377689}.map' path, name, or both are too long. Your package might not work without long file path support. Please shorten the file path or file name. [/code/build/.w/linux-musl-x64/Symbols/Microsoft.AspNetCore.App/runtime.linux-musl-x64.Microsoft.AspNetCore.App.csproj]
/code/build/.dotnet/sdk/2.1.522/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(202,5): error NU5123: The file 'runtimes/linux-musl-x64/lib/netcoreapp2.1/Microsoft.AspNetCore.Authorization.Policy.ni.{7092d54d-984f-401a-aa87-d1166d542c29}.map' path, name, or both are too long. Your package might not work without long file path support. Please shorten the file path or file name. [/code/build/.w/linux-musl-x64/Symbols/Microsoft.AspNetCore.App/runtime.linux-musl-x64.Microsoft.AspNetCore.App.csproj]
/code/build/.dotnet/sdk/2.1.522/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(202,5): error NU5123: The file 'runtimes/linux-musl-x64/lib/netcoreapp2.1/Microsoft.AspNetCore.Connections.Abstractions.ni.{02d0d6a0-92c4-41eb-8d3e-d84e75f33180}.map' path, name, or both are too long. Your package might not work without long file path support. Please shorten the file path or file name. [/code/build/.w/linux-musl-x64/Symbols/Microsoft.AspNetCore.App/runtime.linux-musl-x64.Microsoft.AspNetCore.App.csproj]
/code/build/.dotnet/sdk/2.1.522/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(202,5): error NU5123: The file 'runtimes/linux-musl-x64/lib/netcoreapp2.1/Microsoft.AspNetCore.Cryptography.Internal.ni.{a53d44c1-5ce2-4bd2-a4aa-e7b93bf1101e}.map' path, name, or both are too long. Your package might not work without long file path support. Please shorten the file path or file name. [/code/build/.w/linux-musl-x64/Symbols/Microsoft.AspNetCore.App/runtime.linux-musl-x64.Microsoft.AspNetCore.App.csproj]
/code/build/.dotnet/sdk/2.1.522/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(202,5): error NU5123: The file 'runtimes/linux-musl-x64/lib/netcoreapp2.1/Microsoft.AspNetCore.Cryptography.KeyDerivation.ni.{fc774452-f0ff-4c30-9142-7370c005c69b}.map' path, name, or both are too long. Your package might not work without long file path support. Please shorten the file path or file name. [/code/build/.w/linux-musl-x64/Symbols/Microsoft.AspNetCore.App/runtime.linux-musl-x64.Microsoft.AspNetCore.App.csproj]
/code/build/.dotnet/sdk/2.1.522/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(202,5): error NU5123: The file 'runtimes/linux-musl-x64/lib/netcoreapp2.1/Microsoft.AspNetCore.DataProtection.Abstractions.ni.{d28c1fbc-79e1-43e2-aebf-5016282178ec}.map' path, name, or both are too long. Your package might not work without long file path support. Please shorten the file path or file name. [/code/build/.w/linux-musl-x64/Symbols/Microsoft.AspNetCore.App/runtime.linux-musl-x64.Microsoft.AspNetCore.App.csproj]
/code/build/.dotnet/sdk/2.1.522/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(202,5): error NU5123: The file 'runtimes/linux-musl-x64/lib/netcoreapp2.1/Microsoft.AspNetCore.DataProtection.Extensions.ni.{52a32ce4-1196-4f05-8fab-de99ae130603}.map' path, name, or both are too long. Your package might not work without long file path support. Please shorten the file path or file name. [/code/build/.w/linux-musl-x64/Symbols/Microsoft.AspNetCore.App/runtime.linux-musl-x64.Microsoft.AspNetCore.App.csproj]
```

@rrelyea what suppresses these errors❔ I ask because the package layout seems to be consistent between e.g. runtime.linux-musl-x64.Microsoft.AspNetCore.All.2.1.17-servicing-31324.symbols.nupkg and Microsoft.AspNetCore.App.Runtime.linux-musl-arm64.3.1.14.symbols.nupkg but NU5123 don't show up in our release/3.1 builds and we don't mention "NU5123" in our release/3.1 branch.

Alternatively, @tmat is there another (shorter) way we could name the `*.map` files that would still work for the symbol servers❔

**Comment by dougbu** [comment]
I'm having trouble getting to the root cause of some warnings and errors in internal 2.1.x builds such as https://dev.azure.com/dnceng/internal/_build/results?buildId=1051784

1. /ping @rrelyea and @tmat on the `*.map` packaging issues. Should we just place the `*.map` files in or near the root of the package layout❔

2. @rrelyea similarly, complaints about `licenseURL` use in our packages are infrequent but show up consistently w/ projects copied from https://github.com/dotnet/aspnetcore/blob/release/2.1/build/tools/templates/SharedFxSymbols/SharedFrameworkSymbols.csproj We don't want to change the 2.1.x licenses at this late date. So, how are we suppressing / hiding problems in our other shipping projects❔ (There isn't much special about that project and we don't mention "NU5125" in this repo.)
    ``` text
    [...\.dotnet\x64\sdk\2.1.522\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(202,5): error NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead. [...\.w\win-x64\Symbols\Microsoft.AspNetCore.App\runtime.win-x64.Microsoft.AspNetCore.App.csproj]
    [...\.dotnet\x64\sdk\2.1.522\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(202,5): error NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead. [...\.w\win-x64\Symbols\Microsoft.AspNetCore.App\runtime.win-x64.Microsoft.AspNetCore.All.csproj]
    ```

3. @trylek @AntonLapounov our 2.1 builds hit a problem that sound like a recurrence of dotnet/sdk#9305. We also see a lot of `E_FAIL` output (as documented in #30760). Is there something we can change to clean this up in our 2.1.x builds❔
    Relevant command is
    ``` text
    /code/build/.w/linux-musl-x64/CrossGenTool/crossgen @/code/build/.w/linux-musl-x64/CrossGenRsp/shared/Microsoft.AspNetCore.App/2.1.27-servicing-1051784/Microsoft.CodeAnalysis.rsp
    ```
    with `COMPlus_PartialNGen=0` passed in the environment. The response file contains e.g.
    ``` text
    -nologo
    -readytorun
    -in /code/build/.w/linux-musl-x64/Publish/shared/Microsoft.AspNetCore.App/2.1.27-servicing-1051784/Microsoft.CodeAnalysis.dll
    -out /code/build/.w/linux-musl-x64/CrossGen/shared/Microsoft.AspNetCore.App/2.1.27-servicing-1051784/Microsoft.CodeAnalysis.dll
    -platform_assemblies_paths /code/build/.w/linux-musl-x64/CrossGenTool/:/code/build/.w/linux-musl-x64/Publish/shared/Microsoft.AspNetCore.App/2.1.27-servicing-1051784/:/code/build/.w/linux-musl-x64/Publish/shared/Microsoft.AspNetCore.All/2.1.27-servicing-1051784/
    -JITPath /code/build/.w/linux-musl-x64/CrossGenTool/libclrjit.so
    ```
    Output is
    ``` text
    EXEC Method not found: 'Void Microsoft.DiaSymReader.ISymUnmanagedWriter8._VtblGap1_33()'. while resolving 0x60007b7 - Microsoft.DiaSymReader.ISymUnmanagedWriter8._VtblGap1_33. [/code/build/.dotnet/buildtools/korebuild/2.1.7-build-20210309.1/KoreBuild.proj]
    ...
    Error 2147500037 (Exception from HRESULT: 0x80004005 (E_FAIL)) while compiling method AnalysisState.GenerateSimulatedCompilationEventsAsync
    Error 2147500037 (Exception from HRESULT: 0x80004005 (E_FAIL)) while compiling method AnalysisState.OnCompilationEventsGeneratedAsync
    Error 2147500037 (Exception from HRESULT: 0x80004005 (E_FAIL)) while compiling method AnalysisState.EnsureAnalyzerActionCountsInitializedAsync
    Error 2147500037 (Exception from HRESULT: 0x80004005 (E_FAIL)) while compiling method AnalyzerDriver.AttachQueueAndProcessAllEventsAsync
    ...
    Native image /code/build/.w/linux-musl-x64/CrossGen/shared/Microsoft.AspNetCore.App/2.1.27-servicing-1051784/Microsoft.CodeAnalysis.dll generated successfully.
    ```
    The `E_FAIL` messages happen with a lot of assemblies but the "Method not found" error seems specific to Microsoft.CodeAnalysis.dll.

Any help much appreciated❕

**Comment by trylek** [comment]
I believe that Anton recently updated the DiaSymReader to resolve some arm64-related issues but this thread mostly seems to refer to the <code>x64</code> platform whereas the issue https://github.com/dotnet/sdk/issues/9305 is about <code>arm64</code>. I defer to Anton to provide more detail as I must admit I'm not super familiar with details of this work; the Crossgen executions still use the "old native" Crossgen that hasn't changed for months, it seems to me that the root cause is clearly related to the DiaSymReader upgrade; changing the compilation to use Crossgen2 is actually a line of work I need to finally make progress on after having been long delayed with various issues hitting the runtime framework switch-over.

**Comment by dougbu** [comment]
@trylek thanks for your response. Has `crossgen` changed in 2.1 builds at all❔ And, are we planning to move to `crossgen2` in servicing branches too❔

**Comment by trylek** [comment]
We certainly don't plan to "backport Crossgen2" to the servicing branches, it would be next to impossible and I believe there's no reason in "rewriting history". It's not like Crossgen1 committed a heinous crime and any mention of it has to be erased from everywhere, we just wrote a newer version and we're switching over to it in the releases to come. Please keep in mind that Crossgen1 / 2 is part of the .NET SDK, it's not an "external" compiler or build tool in the sense of being released independently (like Roslyn, MSVC, or cmake) where we need to update to newer versions once in a while even in the servicing branches.

**Comment by AntonLapounov** [comment]
`Microsoft.DiaSymReader.ISymUnmanagedWriter8` is Windows-only.  Have we crossgened Microsoft.CodeAnalysis.dll before on Linux or has it recently taken a dependency on `Microsoft.DiaSymReader`?

**Comment by trylek** [comment]
And for your other question, I don't see any recent semantic changes to Crossgen in the 2.1 branch, please see here:

https://github.com/dotnet/coreclr/commits/release/2.1/src

I believe it's been mostly infra goo and bits of mostly managed stuff unrelated to the Crossgen compiler at least for a year, maybe more.

**Comment by trylek** [comment]
Good point Anton, we shouldn't be calling into DiaSymReader on Linux at all, that just doesn't make sense. Doug, could you please share the entire offending response file? Crossgen1 has two command-line parameters controlling symbol output - <code>/CreatePDB</code> and <code>/CreatePerfMap</code>; the former should be called on Windows (and use DiaSymReader) and the latter on Unix (Linux / OSX). Knowing which variant was used should let us divide the problem space - if we're doing /CreatePDB, that's a bug in the code or scripts calling Crossgen, if we're doing /CreatePerfMap then that's indeed a Crossgen bug but I find that possibility very far-fetched.

**Comment by AntonLapounov** [comment]
@trylek It is not `crossgen.exe` who calls DiaSymReader, it is the library being compiled by `crossgen2.exe` who references it.

**Comment by dougbu** [comment]
> Have we crossgened Microsoft.CodeAnalysis.dll before on Linux or has it recently taken a dependency on Microsoft.DiaSymReader?

I don't know anything about the history of Microsoft.CodeAnalysis and don't even know where the 2.1.x version of that assembly or package is / was built. We could exclude it from our `crossgen` operations but the larger question of platform compatibility would remain. We have a number of CodeAnalysis projects in this repo e.g. src/Razor/CodeAnalysis.Razor/src/Microsoft.CodeAnalysis.Razor.csproj and believe they're supposed to work everywhere. If a Microsoft.CodeAnalysis dependency is Windows-only, what operations won't work on (say) Linux❔

/fyi we do the `crossgen` operation for every assembly that ends up in our Microsoft.AspNetCore.App or Microsoft.AspNetCore.All meta-packages. This hasn't changed. Main new bit is our move from TeamCity to AzDO for 2.1 builds; we noticed the many messages (~1000 `E_FAIL` messages per build❕) but believe they've happened for a while.

/cc @jaredpar in case something has changed and @pranavkm for awareness.

**Comment by trylek** [comment]
Thanks Anton, you're right, I misread the error message. For Microsoft.CodeAnalysis, I see that the current "live" version in the runtime repo indeed uses pinvokes against DiaSymReader. This would constitute an important change if previously Microsoft.CodeAnalysis had been using dynamic resolution of DiaSymReader methods (LoadLibraryEx & GetProcAddress & Marshal.GetDelegateForFunctionPointer. I don't know if such transformation happened in the past. Why would have we changed the version of Microsoft.CodeAnalysis to something recent in the old servicing branch?

**Comment by AntonLapounov** [comment]
> If a Microsoft.CodeAnalysis dependency is Windows-only, what operations won't work on (say) Linux❔

Speculating: it might call Windows interfaces only when executed on Windows and `crossgen.exe` might be not smart enough.  If it is not a regression in 2.1, do we care?

**Comment by dougbu** [comment]
> could you please share the entire offending response file?

This might be the key @trylek. We run `crossgen` against all of our assemblies twice, once to handle the assemblies themselves and once to generate the appropriate PDBs or MAPs. The target that contains `E_FAIL` output and complaints about DiaSymReadder is [`CrossGenAssemblies`](https://github.com/dotnet/aspnetcore/blob/release/2.1/build/SharedFx.targets#L364-L387). Note it doesn't pass _either_ `-CreatePDB` or `-CreatePerfMap`.

The [`CrossGenSymbols`](https://github.com/dotnet/aspnetcore/blob/release/2.1/build/SharedFx.targets#L389-L412) target seems to work fine.

Can one command do what we need on Linux and macOS❔ Or, should we just add the appropriate `-CreateXYZ` option in `CrossGenAssemblies`❔

**Comment by dougbu** [comment]
> If it is not a regression in 2.1, do we care?

Our main concern is the unreadability of our 2.1 builds due to the `E_FAIL` spew. We may find an underlying issue in Microsoft.CodeAnalysis but my question for @jaredpar was intended as an aside.

**Comment by trylek** [comment]
Calling the compiler twice is the right thing to do - in fact that's one of Crossgen1 drawbacks we fixed in Crossgen2 which is able to generate the PDB or perfmap directly alongside the compiled native executable, simplifying the overall workflow and increasing compilation throughput. My current working theory is that Crossgen1 simply looks at the targeting DLL for pinvokes (I doubt it actually needs to but it just might). So I'm guessing that in the "past when it was working" either the DiaSymReader was (perhaps erroneously) available even to Linux builds or the version of Microsoft.CodeAnalysis wasn't using pinvokes to the library at that time.

**Comment by dougbu** [comment]
Thanks, I think that's it for the `Method not found` part. We don't see it that in later release branches because our analyzers don't get `crossgen`ed.

However many other assemblies from Microsoft.AspNetCore.App and Microsoft.AspNetCore.All _do_ still land in Microsoft.AspNetCore.App.Runtime packages and are `crossgen`ed. But, I don't see the `E_FAIL` output. Main difference in the newer MSBuild code seems to be `<Exec ... />` versus `<Exec ...  IgnoreStandardErrorWarningFormat="true" StandardOutputImportance="High" />` (in our 'main' branch). Is adding those attributes safe for the 2.1.x copy of `crossgen`❔

**Comment by AntonLapounov** [comment]
> Is adding those attributes safe for the 2.1.x copy of `crossgen`❔

Probably yes; however, my knowledge of the old `crossgen` is limited.

**Comment by dougbu** [comment]
> > Is adding those attributes safe for the 2.1.x copy of `crossgen`❔

> Probably yes; however, my knowledge of the old `crossgen` is limited.

The added attributes on the `Exec` task didn't change anything. @trylek @AntonLapounov let's take further discussion of the `crossgen` output (`E_FAIL` and otherwise) to #30760.

**Comment by AntonLapounov** [comment]
@dougbu Have you tried `<Exec StandardOutputImportance="Low" StandardErrorImportance="Low" ...`?

**Comment by dougbu** [comment]
I'll reopen this after restoring the fixes lost here

**Pull request closed without merging**
