### PR TITLE
React to breaking changes with M.A.Internal

### PR DESCRIPTION
**Pull request by jkotalik**
Reacting to https://github.com/aspnet/AspNetCore/issues/8637.

I think the following will break once we get new deps for aspnetcore.

### CODE REVIEW

**Review by sebastienros — APPROVED** [review]

**Comment by jkotalik** [comment]
@sebastienros updated.

**Comment by jkotalik** [comment]
I'll file a follow up issue if this passes to decide whether we should keep certain things public.

**Comment by jkotalik** [comment]
@sebastienros can you confirm this change works?

**Comment by sebastienros** [comment]
Currently verifying this

**Comment by sebastienros** [comment]
I can't binary check the changes because the dll replacement happens once the app is published. But this is a compilation issue with the current runtime. However I checked that all the error messages have the corresponding change in this PR.

**Pull request merged**
