### PR TITLE
[blazor-wasm] Update hosted and BYOC agents used in our builds

### PR DESCRIPTION
**Pull request by dougbu**
- dotnet/aspnetcore-internal#3540
- nit: Consistently use in / notin with Build.Reason
  - YAML was inconsistent and this aligns w/ the Arcade code

### CODE REVIEW

**Comment by dougbu** [comment]
This change is independent of other PRs doing the same thing because the 'blazor-wasm' branch is too isolated for successful merges.

**Comment by dougbu** [comment]
@mkArtakMSFT once approved, is the 'blazor-wasm' branch open for infrastructure changes❔

**Review by JunTaoLuo — APPROVED** [review]

**Comment by mkArtakMSFT** [comment]
Looks like this will have no any functional impact so go ahead and merge it!

**Comment by dougbu** [comment]
I'll merge simultaneously with the PRs going into the servicing branches in case they hit conflicts or otherwise need to change. Want to ensure the main commit is included in all of these merges.

**Comment by dougbu** [comment]
Actually, belay that. I forgot this PR was isolated because 'blazor-wasm' is an island.

**Pull request merged**
