### PR TITLE
Try specifying session timeout in helix runsettings

### PR DESCRIPTION
**Pull request by HaoK**

### CODE REVIEW

**Comment by HaoK** [comment]
Example of timeout:

  https://helix.dot.net/api/2019-06-17/jobs/ed73bc1e-346d-472f-8750-649a1f9470fe/workitems/Microsoft.AspNetCore.Identity.Test--netcoreapp5.0/files/console.79c6af61.log

```
Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Aborting test run: test run timeout of 180000 milliseconds exceeded.
Results File: C:\h\w\B0120955\w\A4A708E3\e\TestResults\TestResults.xml

Test Run Aborted.
Total tests: Unknown
     Passed: 248
 Total time: 3.0357 Minutes

```

**Comment by HaoK** [comment]
So doesn't look like dotnet vstest respects the runner config files, but it does accept runtimesettings.  Thoughts on what our default timeout should be for tests?  5 minutes?

**Comment by BrennanConroy** [comment]
Not sure how useful this is, it gives us a little bit more info in that it creates a testResults.xml file with the completed tests. But it still doesn't show which test was hanging.

Take a look at https://github.com/dotnet/aspnetcore/pull/19922 which will print out which test is taking too long.

**Comment by HaoK** [comment]
Closing in favor of #19922

**Comment by HaoK** [comment]
I guess we could do both if we wanted to if we want the testResults.xml

**Pull request closed without merging**
