### PR TITLE
Rename area-runtime in fabricbot

### PR DESCRIPTION
**Pull request by BrennanConroy**
I don't know if this is automatically applied to fabricbot or if someone needs to manually update it and this is just a record of what the bot does.

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Comment by wtgodbe** [comment]
Doing it manually is right

**Comment by wtgodbe** [comment]
[dotnet-issue-labeler](https://github.com/apps/dotnet-issue-labeler) is the one that trains itself

**Comment by amcasey** [comment]
Interesting.  This seems like it would be more reliable than the AI one.  If we think this is sufficient, I believe we can opt out of automatic PR labelling, since the PR model is separate from the Issue model.

**Review by amcasey — APPROVED** [review]

**Comment by wtgodbe** [comment]
I think at the moment there are some things that the AI bot labels that aren't covered by fabricbot, and there's definitely functionality in fabricbot that isn't handled by the AI bot. Unless it's causing anybody any undue harm I think it's fine to keep both

**Pull request merged**
