### PR TITLE
Remove nameof for log event name

### PR DESCRIPTION
**Pull request by Kahbazi**

### CODE REVIEW

**Review by analogrelay — APPROVED** [review]
Thanks!

**Comment by anurse** [comment]
Re-running the builds. Likely just build flakiness :(

**Comment by anurse** [comment]
I'm going to override branch protection and merge this.

1. It's a trivial nameof fix in `master`. I doubt there's an issue
2. It appears we've got a clean build but the GitHub checks haven't been updated properly.

**Pull request merged**
