### PR TITLE
Show user friendly message for streaming rendering failures

### LINKED ISSUE #51619: Streaming Rendering Renders Poor Errors if an Exception Happens After Streaming Started
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using Streaming Rendering, if an exception happens after it has started delivering the page, it renders a simple page with the exception (or a more generic message in production) rather than the full error page or a user-friendly error indicator.

A plain white page with black error text

### Expected Behavior

The expected behavior would be that it render the normal error page as it does when the exception happens before it has started delivering the page or that it would show the "unhandled exception" `blazor-error-ui` box.

A normally rendered error page

A Blazor page showing a message saying that an unhandled problem has occurred

### Steps To Reproduce

* Create a new project with `dotnet new blazor`
* Edit `Weather.razor` and add `throw new Exception()` on the line after `await Task.Delay(500)`
* Navigate to the weather page
* You see the page load with the "Loading..." and then flash over to the stark black-on-white text error page

https://github.com/tuttidormer/Blazor-Error/blob/main/Components/Pages/Weather.razor#L42-L46

If you put the `throw new Exception()` before the `await Task.Delay(500)`, you get the "correct" error rendering rather than the poor black-on-white text display.

### Exceptions (if any)

_No response_

### .NET Version

8.0.100-rtm.23524.4

### Anything else?

This has been tested on 8.0.100-rc.2.23502.2, 8.0.100-rtm.23524.4 (nightly), and 8.0.200-preview.23523.27 (nightly). All were fresh installs of dotnet on VMs and the nightly NuGet config was added for the nightly ones.

```
.NET SDK:
 Version:           8.0.100-rtm.23524.4
 Commit:            5bc5eecc5a
 Workload version:  8.0.100-manifests.ea856202

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.0
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.100-rtm.23524.4/

.NET workloads installed:
 Workload version: 8.0.100-manifests.ea856202
There are no installed workloads to display.

Host:
  Version:      8.0.0-rtm.23519.13
  Architecture: arm64
  Commit:       86c949374e

.NET SDKs installed:
  8.0.100-rtm.23524.4 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-rtm.23520.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0-rtm.23519.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```

### PR DESCRIPTION
**Pull request by LilahTovMoon**
# Show user friendly message for streaming rendering failures

- [X] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Description

When an error happens in streaming rendering, it currently shows an unfriendly message. This shows the regular Blazor error UI and logs the error message to the JS console

| 278160168-aac731b5-f3ca-47f5-af75-cd4b0d4757fe Before | 278160465-a376a1d3-c13a-4869-be33-dadcea27ec9f After |
|-------|-------|

Fixes #51619

### CODE REVIEW

**Comment by LilahTovMoon** [comment]
@dotnet-policy-service agree

**Comment by MackinnonBuck** [comment]
This change seems good to me. It at least prompts the user to reload the page in case this case happens during production.

Not sure whether this meets the bar for a servicing fix, or if we would take this for .NET 9.

@SteveSandersonMS @javiercn @danroth27 what do you think?

**Comment by SteveSandersonMS** [comment]
@MackinnonBuck I might be wrong, but I thought we didn't use the yellow bar for any other SSR-specific errors, and didn't rely on it being present in the page. Generally that's because:

* If an error occurs during the initial server rendering, the output is the ASP.NET Core error page
* If an error occurs during enhanced nav, then as with other aspects of enhanced nav, the ideal is to produce the same outcome as non-enhanced nav (and hence we'd also want to see the ASP.NET Core error page)

So the remaining case is during the streaming phase of streaming SSR. Again the ideal would be outputting the ASP.NET Core error page, but we considered that out of scope in the short term due to the complexity. Longer term we might still want to do that.

If the long-term goal is for the yellow bar UI to be specific to interactive rendering, then it's probably not desirable to introduce it here. But if that's not the case and you (and @javiercn) are both happy with treating yellow-bar UI as a required part of SSR, then it would be fine to do this - I'm OK with whatever you decide.

Last point: the logic in `NavigationEnhancement.ts` may assume that streaming SSR always results in one of these two outcomes:

 * It completed successfully and ran any post-streaming clean up logic
 * Or if not (e.g., we redirected away, or there was an error), the entire page was torn down so that none of the old state remains and needs to be cleaned up

The change in this PR would add a third possibility (we finished streaming SSR but left incomplete state in the DOM). It would be good to check through the `NavigationEnhancement.ts` logic to make sure that doesn't leave any other weirdness to be dealt with.

**Comment by MackinnonBuck** [comment]
@SteveSandersonMS that all makes sense to me. Maybe we should hold off on this and see if we want to create a better overall error page experience in the future. Do you agree @javiercn?

**Comment by javiercn** [comment]
I don't have strong feelings about this, to be fair. I think more than anything, we either need to:
1) Provide the same experience as non-streaming rendering (which I think is hard)
2) Make it configurable so that people can provide their own consistent experience if they choose to do so. The default yellow bar sounds acceptable to me.

**Comment by LilahTovMoon** [comment]
> So the remaining case is during the streaming phase of streaming SSR. Again the ideal would be outputting the ASP.NET Core error page. Longer term we might still want to do that.

One thing I'd say is that this might depend on what is happening in the streaming phase. For example, let's say that you're creating a Mastodon clone. You're stream rendering the feed page which has different pieces in it. The feed of recent posts renders fine and gets displayed to the user. Then there's an exception getting the trending-now hashtags. I'd say that it's better to display the page given that the user probably just wants to look at the feed. Most users don't even look at the trending-now hashtags.

One of the things I've noticed is that stream rendering doesn't respect `<ErrorBoundary>`. Non-streaming server rendering does use `<ErrorBoundary>`, but when streaming it won't display the `<ErrorContent>` (however it will swallow the exception so nothing gets shown to the user).

It seems like it would be good if it would use the `<ErrorContent>`, but that seems like a bigger issue.

> Maybe we should hold off on this and see if we want to create a better overall error page experience in the future.

I don't mind either way (since I can just patch it for myself). Implementing this now doesn't preclude creating a better overall error experience in the future.

For #51690, network failures create zero feedback to the user which seems like a bigger issue. In this case, at least the user sees a message that something went wrong. In this case, exceptions are something that can be fixed by those responsible for the app. Presumably, one would log the errors and fix them so this plain-text message shouldn't happen frequently. However, network failures are out of the control of those running the app.

> The change in this PR would add a third possibility (we finished streaming SSR but left incomplete state in the DOM). It would be good to check through the NavigationEnhancement.ts logic to make sure that doesn't leave any other weirdness to be dealt with.

showing that the blazor-error-ui getting a display:block style added to it

When navigating away, the `blazor-error-ui` gets re-rendered without the `display:block` style added to it so the div just goes back to being hidden (but I don't know all the ins and outs of the code, I'm just reporting what I'm seeing).

-------

Again, I can patch this for myself so I don't want to seem pushy or anything. I think #51690 fixes an issue where there is zero feedback at the moment so having any sort of message would make things better. I think that this PR might not be the ideal solution, but it seems to present something nicer/less jarring than the current behavior where you see the partly rendered page and then it flashes to a "kind of brutal" plain-text page.

**Comment by MackinnonBuck** [comment]
Hi @LilahTovMoon, thanks for your contribution. We're going to close this out and revisit the problem in the future so we can have an error page solution that works more consistently between enhanced and non-enhanced nav.

**Pull request closed without merging**
