### PR TITLE
[release/7.0] Fix Blazor RemoteAuthenticatorView processing the same action multiple times

### LINKED ISSUE #39507: Blazor RemoteAuthenticatorView OnLogInSucceeded event firing multiple times
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This issue was closed, but the problem has never been resolved: 
https://github.com/dotnet/aspnetcore/issues/29235

Me and a lot of other people are reporting the same issue. 

### Expected Behavior

Callback fired only once

### Steps To Reproduce

The original (closed) issue has all steps to reproduce

### Exceptions (if any)

_No response_

### .NET Version

6.0.200-preview.21617.4

### Anything else?

  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  5.0.402 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]
  6.0.200-preview.21617.4 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### PR DESCRIPTION
**Pull request by MackinnonBuck**
# Fix Blazor `RemoteAuthenticatorView` processing the same action multiple times

Fixes an issue where the `<RemoteAuthenticatorView/>` component would sometimes fire the login callback more than once.

## Description

The previous logic processed the current authentication action each time the component was re-rendered. Depending on the authentication service used, this could result in the login callback firing more than once. This PR fixes the problem by caching the last processed action and disabling authentication processing until the action changes.

Fixes #39507

## Customer Impact

It causes difficulty for customers to write their own logic in a way that accounts for login callbacks firing more than once. In addition, other expensive authentication actions may get invoked unnecessarily behind the scenes, which can degrade the experience of the customer's app. Multiple customers have reported being affected by this issue, so fixing it has a relatively high impact.

## Regression?

- [ ] Yes
- [X] No

## Risk

- [ ] High
- [ ] Medium
- [X] Low

The fix for this issue is simple, and we have extensive existing test coverage. New tests have been added validating the fix.

## Verification

- [X] Manual (required)
- [X] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [X] N/A

### CODE REVIEW

**Review by javiercn — APPROVED** [review]

**Comment by MackinnonBuck** [comment]
@Pilchie This is ready to be merged - would you take a look please?

**Comment by Pilchie** [comment]
Approved for .NET 7 RC2.

**Comment by stephajn** [comment]
Are there any plans on back-porting this fix to .NET 6 since it's an LTS release? Looking at the PR for this fix, it doesn't look like it took a whole bunch of wicked re-engineering to resolve it.

**Pull request merged**
