### PR TITLE
Fix flaky FlowControl_ParallelStreams_FirstInFirstOutOrder

### PR DESCRIPTION
**Pull request by JamesNK**
re: https://github.com/dotnet/aspnetcore/pull/19949

### CODE REVIEW

**Comment by anurse** [comment]
Love it when a flaky test gets a quick fix ;).

**Review by halter73 — APPROVED** [review]

**Comment by halter73** [comment]
Should we unquarantine this or wait for that to happen naturally?

**Comment by JamesNK** [comment]
Let it happen naturally 🙏

**Comment by BrennanConroy** [comment]
I don't think this fixed it. Build from today https://dev.azure.com/dnceng/public/_build/results?buildId=565796&view=ms.vss-test-web.build-test-results-tab&runId=17789734&paneView=debug&resultId=100024

**Comment by JamesNK** [comment]
😭

**Comment by halter73** [comment]
Can you still reproduce this locally @JamesNK?

**Comment by JamesNK** [comment]
Not anymore. Even with 16 tasks running the test concurrently 1,000,000 times, it passes.

**Pull request merged**
