### PR TITLE
Make the dev-server log less

### LINKED ISSUE #18981: Make the blazor dev-server output less noisy
The dev-server logs info level content which is typically off by for the "Microsoft" filter in other templates.

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
LessLog

**Comment by javiercn** [comment]
Is there an associated issue?

I'm not against in principle, but I think this should be configurable so that users can tune this if they run into issues.

**Comment by pranavkm** [comment]
> but I think this should be configurable so that users can tune this if they run into issues.

Do you know what they would want to debug from the dev-server? It's just static files, no?

**Review by mkArtakMSFT — APPROVED** [review]

**Comment by mkArtakMSFT** [comment]
We will wait for the config provider work to happen to handle this through the appsettings.json file.

**Comment by pranavkm** [comment]
🆙 📅 per offline discussion

**Review by mkArtakMSFT — APPROVED** [review]

**Pull request merged**
