### PR TITLE
Add AddHubOptions extension on IServiceCollection

### LINKED ISSUE #54116: Add `AddHubOptions<>` SignalR extension to `IServiceCollection`
## Background and Motivation

In the SignalR library, we are able to configure the hub options using the `AddHubOptions<>` extensions on the `ISignalRServerBuilder` interface. This is great when you are adding the hub from the same project that adds the server. However, in a modular infrastructure, it hubs maybe defined in a module that does not register the server.

Today, in order for one to register a hub from a project that does not register the server, we would have to do the following

```csharp
services.AddSingleton<IConfigureOptions<HubOptions<CustomHub>>, HubOptionsSetup<CustomHub>>();
services.Configure(op => {
 // ...
});
```

It would be helpful if we can add `AddHubOptions<>` extension to the `IServiceCollection` to allow us to easily add and configure hub specific options from a project that does not register the server.

## Proposed API

Change the `AddHubOptions<>` extension 

https://github.com/dotnet/aspnetcore/blob/5c17b92560953e86f1ea8502a567bcb3a1be4a2f/src/SignalR/server/SignalR/src/SignalRDependencyInjectionExtensions.cs#L24-L31

To this instead

```csharp
    /// <summary>
    /// Adds hub specific options to an <see cref="ISignalRServerBuilder"/>.
    /// </summary>
    /// <typeparam name="THub">The hub type to configure.</typeparam>
    /// <param name="signalrBuilder">The <see cref="ISignalRServerBuilder"/>.</param>
    /// <param name="configure">A callback to configure the hub options.</param>
    /// <returns>The same instance of the <see cref="ISignalRServerBuilder"/> for chaining.</returns>
    public static ISignalRServerBuilder AddHubOptions<THub>(this ISignalRServerBuilder signalrBuilder, Action<HubOptions<THub>> configure) where THub : Hub
    {
        ArgumentNullException.ThrowIfNull(signalrBuilder);

        signalrBuilder.Services.AddHubOptions<THub>(configure);
        return signalrBuilder;
    }

    /// <summary>
    /// Adds hub specific options to an <see cref="IServiceCollection"/>.
    /// </summary>
    /// <typeparam name="THub">The hub type to configure.</typeparam>
    /// <param name="services">The <see cref="IServiceCollection"/>.</param>
    /// <param name="configure">A callback to configure the hub options.</param>
    /// <returns>The same instance of the <see cref="IServiceCollection"/> for chaining.</returns>
    public static IServiceCollection AddHubOptions<THub>(this IServiceCollection services, Action<HubOptions<THub>> configure) where THub : Hub
    {
        ArgumentNullException.ThrowIfNull(services);

        services.AddSingleton<IConfigureOptions<HubOptions<THub>>, HubOptionsSetup<THub>>();
        services.Configure(configure);
        return services;
    }
```

## Usage Examples

In module "A" we can use `services.AddSignalR()` and define global hub options.

In module "B" that depends on module "A", we can use `services.AddHubOptions<CustomHub>(options => ... )`

## Risks

None

I can submit a PR for this.

### PR DESCRIPTION
**Pull request by MikeAlhayek**
# Add AddHubOptions extension on IServiceCollection

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

{Detail}

Fixes #54116 (Add AddHubOptions<> SignalR extension to IServiceCollection #54116)

### CODE REVIEW

**Comment by amcasey** [comment]
CI is failing because there needs to be a change to the PublicAPI.Unshipped.txt listing the new APIs.  The easiest way to add those entries is with the code fix in Visual Studio (Code).

**Comment by MikeAlhayek** [comment]
@amcasey I updated it. Just not very sure I did it correctly.

**Comment by halter73** [comment]
Thanks for submitting this PR, but I'm closing it since we did not approve [the API proposal](https://github.com/dotnet/aspnetcore/issues/54116).

**Pull request closed without merging**
