### PR TITLE
Add slack channel

### PR DESCRIPTION
**Pull request by benaadams**
Improves community x8 and support x2 and overall .NET throughput 15 fold on the techempower tests :wink:

### CODE REVIEW

**Comment by muratg** [comment]
cc @glennc

**Comment by Eilon** [comment]
We're having some discussions on this.

**Comment by spboyer** [comment]
@Eilon let me know if there is anything I need to do to help the discussion along, or make it easier.
@shanselman @DamianEdwards

**Comment by Daniel15** [comment]
Why Slack rather than JabbR or Gitter? .NET Core is using Gitter (eg. https://gitter.im/dotnet/corefx).

**Comment by benaadams** [comment]
@Daniel15 gitter is already on page, this just adds the slack next to it, channel is already at 1700 members an it seems ok. JabbR was having having major responsiveness issues else we'd still be there :cry:

**Comment by glennc** [comment]
Closing this, re-open if it still needs to happen but I think @shanselman has settled on only Gitter.

**Pull request closed without merging**
