### PR TITLE
Support binding short values to InputNumber component

### PR DESCRIPTION
**Pull request by captainsafia**
**Changes in this PR**
 - Adds binding for Int16 values to BindConverters
 - Adds two-way data binding for on change events for number inputs with Int16 values
- Updates static constructor and format cases in InputNumber
- Updates reference assemblies
- Add tests for short values in InputNumber component
- Add tests for short values in BindTests

Addresses #15437

### CODE REVIEW

**Review by rynowak — CHANGES_REQUESTED** [review]
Thanks for figuring this out. There's a lot of boilerplate involved in the built-in `bind-` stuff, and it all looks right!

Can you also update https://github.com/dotnet/aspnetcore/blob/master/src/Components/test/testassets/BasicTestApp/BindCasesComponent.razor#L327 - this is where most of the detailed bind testing takes place.

**Comment by SteveSandersonMS** [comment]
This looks superb - thanks @captainsafia!

**Comment by captainsafia** [comment]
Thanks for the reviews, @rynowak  and @SteveSandersonMS!

I've added more tests for this addition. Let me know what you think.

**Review by SteveSandersonMS — APPROVED** [review]
This is excellent - thanks very much!

**Review by rynowak — APPROVED** [review]
Awesome! Thanks for working through all this.

**Comment by shanselman** [comment]
:shipit:

**Pull request merged**
