### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by natemcmaster**
Manual update to workaround problems with the bot.

### CODE REVIEW

**Comment by natemcmaster** [comment]
Generated this update using this script: https://github.com/aspnet/AspNetCore-Internal/pull/1830

**Review by dougbu — APPROVED** [review]
See a fair number of warnings about changed package references and test failures that indicate behaviour of memory requests has changed. But, the versions look like they're consistent given how far the build got.

Probably need to file a bug on the relevant team and get another set of consistent packages ☹️

**Comment by natemcmaster** [comment]
Failing tests in Kestrel. Possibly related to changes in corefx? Here is what changed

https://github.com/dotnet/corefx/compare/c38c10d28e223aeea2f363a6ef0bf4a63d00a776...0abec4390b30fdda97dc496594f9b1f9c9b20e17

**Comment by natemcmaster** [comment]
I'll let @jkotalik take over this PR. Sounds like we need changes in Kestrel.

**Comment by jkotalik** [comment]
@Tratcher passing the mic to you to fix IApplicationLifetime.

**Comment by Tratcher** [comment]
@jkotalik can you look at the ChunksWithGetMemoryWithInitialFlushWorks test failures?

**Comment by benaadams** [comment]
> @jkotalik can you look at the ChunksWithGetMemoryWithInitialFlushWorks test failures?

Its returning a 4005 chunk rather than a 4089 chunk for some reason (actual `fa5` expected `ff9`); the number of `a`s matches the hex value so its consistent with the data and works happily locally in isolation

**Comment by benaadams** [comment]
ah is without dep update, so maybe that changes things?

**Comment by benaadams** [comment]
Ah, is it the change in this PR not to pass in a size hint?
```diff
-    var memory = response.BodyPipe.GetMemory(5000); // This will return 4089
+    var memory = response.BodyPipe.GetMemory(); // This will return 4089
```

**Comment by benaadams** [comment]
Should be fixed with https://github.com/aspnet/AspNetCore/pull/7668 ?

**Comment by Tratcher** [comment]
Superseded by https://github.com/aspnet/AspNetCore/pull/7671

**Pull request closed without merging**
