### PR TITLE
Updated icons for ASP.NET Core projects that appear in VS

### LINKED ISSUE #25973: Update VS icons to have language adornment for the projects that appear in VS
This is the second part to https://github.com/dotnet/aspnetcore/issues/25576. The titles have [already been fixed](https://github.com/dotnet/aspnetcore/pull/25630).

There are some screenshots of how the NPD appears with the preview feature to show all CLI tempaltes. Without the language adornment it is very hard to tell the difference between C# and F# templates.

### Before
image

For comparison here is how some other templates appear that already have the language adornment.
image

I will send a PR to address this soon.
Once the PR build is completed, I will screenshot the results and update this description.

### PR DESCRIPTION
**Pull request by sayedihashimi**
#### Description
In VS 16.9 we have an option to show all CLI templates in the New Project Dialog. One impact that has is that the "One ASP.NET" dialog will no longer appear for ASP.NET Core projects. Instead those templates will be directly in the New Project Dialog (NPD) list. Because we have C# and F# variants for most ASP.NET Core templates, it is very hard to tell which template is for C# and which is for F#. It's very easy for a user to pick the wrong template.
Other templates that are in the NPD already have language adornments for templates that support multiple languages.

Compare what we have today, when the show all CLI templates option is enabled, to the console project that does have language adornments.

image

image

For the Console app, the language adornment really pops and makes it easy for users to pick the correct template. For the ASP.NET Core templates, it honestly looks like a bug because you have to really inspect it to tell its C# & F#.

#### Customer Impact

Without this update, I believe users will be frustrated by not being able to easily tell what language a template is for.

#### Regression

Not a regression, but a change in behavior from what we had before when the One ASP.NET 

#### Risk

I believe this PR to be very low risk. All I did was change the icon files. I tried to minimize changes, so I left all the existing file names as they were.

Some things that I noticed that should probably be addressed at a later date.
 - There is a starterweb F# template, but there is no vs host file so it doesn't appear in VS. @LadyNaggaga 
 - We should add language adornments to the worker template. I didn't do that for this PR because the worker template was not in the One ASP.NET dialog. We will need to work with UX to get the icons created for us. @bradygaster

### CODE REVIEW

**Comment by pranavkm** [comment]
Could we add one for these: 
https://github.com/dotnet/aspnetcore/tree/336cc120dde341a7d2e305960858b865cc7d4812/src/ProjectTemplates/Web.ProjectTemplates/content/StarterWeb-FSharp? 

Also, worker templates have a C# and F# option if you'd like to add icons for those.

**Review by pranavkm — APPROVED** [review]

**Comment by sayedihashimi** [comment]
@pranavkm

I didn't add the Starter web C#/F# because we only show the C# variant. The F# template is missing a VS host file so it doesn't appear in the VS. That should be a separate issue that gets addressed after RC2.

For worker, I didn't update those because they were already in the NPD (not in the One ASP.NET dialog). I didn't request icons for worker because at that time I wasn't aware we needed a new icon. Since this behavior is exactly the same as it always has been, I would argue it doesn't meet the bar for RC2. For the templates that I addressed, those were previously in the One ASP.NET dialog and are moving into the NPD (behind a preview flag for now).

**Comment by sayedihashimi** [comment]
After getting the .nupkg file and running VS I noticed that these icons are not consistent with our other templates.
I have removed the milestone and servicing-consider tags for now. I will get some updated icons, and bring this back. I've also marked the PR as Draft until I get the correct icons.

**Comment by sayedihashimi** [comment]
Just got the updated icons, when the .nupkg is ready I will test it to see if it's looking good. If so, I'll add tags and set milestone.

**Comment by sayedihashimi** [comment]
Got the updated icons in, I think it's looking good now. Screenshots below.

Some things to note:
 - I went ahead and updated Worker tempalte icons to have lang adornment because I got those icons as well
 - MVC F# doesn't have an icon w Lang adornment. This is because the F# MVC template doesn't have a vs host file. The changes needed to give it the proper icon would introduce more risk so I left it off. I think we should fix this at a later time

image

image

image

**Comment by sayedihashimi** [comment]
I have moved the PR from Draft to Ready for review, added the servicing-consider tag and assigned RC2 milestone.

From my perspective, I think we are ready to merge. Please let me know if we need any further changes.

@mkArtakMSFT @timheuer @phenning

**Comment by mkArtakMSFT** [comment]
Thanks @sayedihashimi.
Please also notify Tactics about this so that this gets approved.

**Comment by sayedihashimi** [comment]
@mkArtakMSFT I sent an email shortly after submitting the PR.

**Comment by mkArtakMSFT** [comment]
Thanks Sayed. Merging this as this was approved by Tactics.

**Comment by mkArtakMSFT** [comment]
@sayedihashimi is this intentional that you've removed the F# WebAPI icon:
image

**Comment by sayedihashimi** [comment]
@mkArtakMSFT I think that message is stating that the new file is smaller than the previous file. I didn't intend for the file to be deleted. Form what I can tell the file is still there. See https://github.com/dotnet/aspnetcore/tree/sayedha/icons-in-npd-01/src/ProjectTemplates/Web.ProjectTemplates/content/WebApi-FSharp/.template.config/vs-2017.3

When I run `git diff 9506101c40b0d2f428126d736ae3791b2919c4a7~ 9506101c40b0d2f428126d736ae3791b2919c4a7` locally here is what I see.

image

**Comment by pranavkm** [comment]
As @sayedihashimi mentioned, it's still there, just smaller in size. Deleted files appear differently

**Review by pranavkm — APPROVED** [review]

**Pull request merged**
