### PR TITLE
Fix route pattern analyzer false positive with catch-all parameter

### LINKED ISSUE #52628: ASP0018 complains about catch-all parameter without proposing any solutions
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```cs
// ASP0018 Unused route parameter 'any'
[HttpOptions, Route("some/api/{*any}")]
public IActionResult CORSPreflight()
{ ... }
```

### Expected Behavior

As route template parameter is [required to have name](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-8.0#route-templates) I expect analyzer to support `catch-all` parameters for rest of template.

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

8.0.100

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ghost**
Fixes #52628.

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

### CODE REVIEW

**Comment by joegoldman2** [comment]
Hum, maybe the right fix is not to ignore catch-all parameters during the analysis, but rather fix the code fixer to add the missing parameter to the handler. But in this case it already seems to work with the latest preview of .NET 9 for both minimal API and MVC.

https://github.com/dotnet/aspnetcore/assets/147369450/5763f355-9517-4b77-b000-8929d7521494

**Comment by joegoldman2** [comment]
Hum, maybe the right fix is not to ignore catch-all parameters during the analysis, but rather fix the code fixer to add the missing parameter to the handler. But in this case it already seems to work with the latest preview of .NET 9 for both minimal API and MVC.

https://github.com/dotnet/aspnetcore/assets/147369450/028251a1-74d8-4bc3-a92d-915f2db72875

**Comment by joegoldman2** [comment]
@JamesNK should we close this PR and the associated issue in this case?

**Comment by JamesNK** [comment]
Yes. I'll do that now.

**Pull request closed without merging**
