### PR TITLE
Make IntegrationTesting not depend on M.A.Hosting.Abstractions

### LINKED ISSUE #14085: IIS Benchmarks don't run
/cc @jkotalik @shirhatti 

Needs investigation on the server as even the windows log is useless in this case .

### PR DESCRIPTION
**Pull request by jkotalik**
Fixes https://github.com/aspnet/AspNetCore/issues/14085

The Microsoft.AspNetCore.Server.IntegrationTesting package depends on Microsoft.AspNetCore.Hosting.Abstractions. If someone were referencing the integration testing package outside of AspNetCore, it would be broken as there is a missing dependency. This is exactly what the benchmarks repo was doing to pull in ANCM. It takes a dependency on this package to pull in ANCM into the right location, sxs with the app: https://github.com/aspnet/Benchmarks/blob/master/src/Benchmarks/Benchmarks.csproj#L70. So if we can remove the dependency on M.A.Hosting.Abstractions, we can now use this package outside of the repo.

This package only used M.A.Hosting.Abstractions for a single, one-line extension method. I decided to remove it and create a helper class instead.

Few things:
- I'd rather not create a separate internal package to carry ANCM at this point. We have custom logic in the csprojs to copy ANCM to the right locations on publish and on pack: https://github.com/aspnet/AspNetCore/blob/master/src/Servers/IIS/IntegrationTesting.IIS/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS.csproj#L45. 

@sebastienros I'll need some help verifying this change on Benchmarks.

Also, this change should be backported to 3.x

### CODE REVIEW

**Comment by sebastienros** [comment]
Not that easy to test, as the issue occurs during build, and ideally you would put this patched assembly in the output folder once the app is published. We'll have to wait for a build to be available on a feed and use this specific aspnet version to test.

**Comment by jkotalik** [comment]
> We'll have to wait for a build to be available on a feed and use this specific aspnet version to test.

I came up with the same conclusion, unfortunately. One thing I tried to do was remove the package reference in benchmarks.csproj and use --output-file on the ANCM folder, but that failed, reporting an empty failure.

**Comment by sebastienros** [comment]
One thing however, would be to create a refrence to a local .dll file, and use `--build-file [path_to_local_file]` such that your local file would be pushed on the same folder as the csproj on the server, before the build, so your project can reference it. Or add it to your branch yourself and reference it locally.

**Comment by Tratcher** [comment]
I'm surprised that was the only reference.

**Comment by jkotalik** [comment]
I verified that there are no dependencies in AspNetCore for the integration testing package, meaning the error we were seeing should be gone. I wasn't able to verify that benchmarks works by referencing this package as the package isn't published yet. So I'd prefer to actually publish this package via merging with master first and then verifying benchmarks. Afterwards, I can make a PR to 3.0/3.1 to fix it there as well. Everything else has been solved (see https://github.com/aspnet/Benchmarks/pull/1415).

**Review by Tratcher — APPROVED** [review]

**Pull request merged**
