### PR TITLE
SocketSender/Receiver: also Inline continuations on Windows

### PR DESCRIPTION
**Pull request by tmds**
Some benchmarks we ran on Linux indicate this may be interesting on Windows.

cc @halter73 @davidfowl @sebastienros @adamsitnik

### CODE REVIEW

**Comment by anurse** [comment]
Triage: we do have some hunch that there's a reason we didn't inline continuations on Windows. @davidfowl @halter73 does that ring a bell?

**Comment by davidfowl** [comment]
@halter73 wrote up the reason we use IOQueues here https://github.com/dotnet/runtime/pull/2346#issuecomment-582198050.

**Comment by tmds** [comment]
In theory, `Inline` should be faster than `IOQueue`, and `IOQueue` should be faster than `ThreadPool`.
In practice, it doesn't seem to always work that way.
So let's measure and see the effect.

**Comment by tmds** [comment]
Can we run a benchmark to see the effect?

**Comment by shirhatti** [comment]
Triage: We've tried this before, and it didn't end well https://github.com/aspnet/KestrelHttpServer/issues/2573

**Comment by tmds** [comment]
> Triage: We've tried this before, and it didn't end well aspnet/KestrelHttpServer#2573

@shirhatti that issue says it didn't end well on Linux.

**Comment by shirhatti** [comment]
Ah shoot @halter73?

**Comment by tmds** [comment]
@halter73 if you know it is faster to use IoQueue here on Windows, I'm fine if the issue gets closed. Otherwise we can run a benchmark and find out.

**Comment by halter73** [comment]
For SocketReceiver at least, dispatching receive continuations on Windows, even to the threadpool significantly improved perf in the plaintext and . @davidfowl first proved that with https://github.com/aspnet/KestrelHttpServer/pull/2366.

Dispatching to the IOQueue which was introduced by https://github.com/aspnet/KestrelHttpServer/pull/2368 showed even further improvement compared to dispatching to the threadpool. You can look at both PRs for the benchmark results we got at the time on Windows.

For the SocketSender, the difference was within the noise level IIRC, but that makes sense since sends should always completely immediately when there's no backpressure like in the plaintext and json benchmarks.

**Pull request closed without merging**
