### PR TITLE
Update DbgProxy to https://github.com/mono/mono/commit/c8cbcaad

### PR DESCRIPTION
**Pull request by pranavkm**
https://github.com/mono/mono/commit/c8cbcaad

### CODE REVIEW

**Comment by pranavkm** [comment]
We can skip this, there aren't any interesting updates for preview5 looking at this diff

**Comment by SteveSandersonMS** [comment]
@pranavkm But the whitepaces!

**Comment by lewing** [comment]
It fixes setting breakpoints in delegates.

**Comment by lewing** [comment]
https://github.com/mono/mono/pull/19449
https://github.com/mono/mono/pull/19576

**Comment by SteveSandersonMS** [comment]
@pranavkm Is it worth waiting until https://github.com/mono/mono/pull/19592 flows in too? That's the last item we're hoping to include in the RC.

Approving anyway so you're free to merge when you feel it's time!

**Review by SteveSandersonMS — APPROVED** [review]

**Comment by pranavkm** [comment]
@SteveSandersonMS we could do it as soon as we pick up the corresponding runtime. This commit will correspond with what's currently in our runtime: https://github.com/dotnet/blazor/commit/0c8fc91418991d752139355d6bce8d26b857bde0

**Pull request merged**
