### PR TITLE
Update templates for 3.1

### PR DESCRIPTION
**Pull request by ryanbrandenburg**
Fixes https://github.com/aspnet/AspNetCore/issues/14486.

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
@aspnet/build folks,I assume the `<TargetFramework>` in the change in `.csproj` files will happen as part of rebranding work? Currently it's defined as below:
```csproj
<TargetFramework>${DefaultNetCoreTargetFramework}</TargetFramework>
```

**Review by mkArtakMSFT — APPROVED** [review]
Thanks for quickly handling this, @ryanbrandenburg.
Let's get this merged after getting confirmation from the Build folks first.

**Comment by wtgodbe** [comment]
> I assume the <TargetFramework> in the change in .csproj files will happen as part of rebranding work?

Yes, it should just get the right value from root dir.build.props:
https://github.com/aspnet/AspNetCore/blob/release/3.1/Directory.Build.props#L55

**Comment by dougbu** [comment]
> it should just get the right value from root dir.build.props

And, the value is correct in every branch 😺

**Review by dougbu — COMMENTED** [review]
@ryanbrandenburg please also update 'master' to use 5.0 identities and perhaps a still-higher precedence

**Review by JunTaoLuo — APPROVED** [review]

**Comment by ryanbrandenburg** [comment]
Closing in favor of https://github.com/aspnet/AspNetCore/pull/14637 which uses the new branch.

**Pull request closed without merging**
