### PR TITLE
Don't exclude System.IO.Pipelines from TargetingPack version check

### PR DESCRIPTION
**Pull request by wtgodbe**
First part of https://github.com/dotnet/aspnetcore/issues/31074. Also check that `Version.Build == 0` in addition to `Version.Revision`

### CODE REVIEW

**Review by dougbu — COMMENTED** [review]
If it works, great❕

Does this change imply we no longer have incoming assemblies w/ versions that aren't like `7.0.0.0`❔

**Comment by wtgodbe** [comment]
> Does this change imply we no longer have incoming assemblies w/ versions that aren't like 7.0.0.0❔

That's what I saw locally

**Comment by wtgodbe** [comment]
@dougbu you alright with this change?

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
> you alright with this change?

Yes, I meant to approve the PR yesterday ☹️

**Pull request merged**
