### PR TITLE
[Helix] Try out the new dotnet test blame functionality

### PR DESCRIPTION
**Pull request by HaoK**
Add a hanging test to see if dmps work now

### CODE REVIEW

**Comment by HaoK** [comment]
cc @davidfowl

**Comment by davidfowl** [comment]
@HaoK we need to configure the blame collector. I'll look into that

**Comment by HaoK** [comment]
Right, I just kicked this off as the initial PR starting point

**Comment by HaoK** [comment]
So looks like at as a starting point we already get ubuntu and windows dumps https://dev.azure.com/dnceng/public/_build/results?buildId=724969&view=ms.vss-test-web.build-test-results-tab&runId=22437750&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab&resultId=121647

MacOS is the only one that's missing the dmp

**Comment by HaoK** [comment]
Replaced by https://github.com/dotnet/aspnetcore/pull/25010

**Pull request closed without merging**
