### PR TITLE
Added configureConnection delegate to CircuitStartOptions

### LINKED ISSUE #18840: Customizable serverTimeoutInMilliseconds in Server-Side Blazor
When debugging a server-side blazor app we often see this error pop up in the client (browser) while stepping through code:

Error: Connection disconnected with error 'Error: Server timeout elapsed without receiving a message from the server.'.

This can be pretty disruptive, requiring a refresh of the browser to recover after continuing the debug session.

Presumably, this happens because the server isn't sending keepalives on the SignalR connection while I'm stepping through code in the debugger. When running in a 'development' environment, I'd like to be able to customize the serverTimeoutInMilliseconds on the HubConnection to prevent this. I see examples of how to customize the SignalR settings for a server-side Blazor app using code like this:

    <environment exclude="Development">
        <script src="_framework/blazor.server.js"></script>
    </environment>
    <environment include="Development">
        <script src="_framework/blazor.server.js" autostart="false"></script>
        <script>
            (function start() {
                Blazor.start({
                    logLevel: 1, // LogLevel.Debug
                    configureSignalR: builder => builder.configureLogging("debug") // LogLevel.Debug
                });
            })();
        </script>
    </environment>

However, I'm unable to change the serverTimeoutInMilliseconds setting. This setting is available on the HubConnection object, but I don't have access to that object. I only have access to HubConnectionBuilder. And HubConnectionBuilder doesn't have a serverTimeoutInMilliseconds property. 

It seems like adding support for configuring the serverTimeoutInMilliseconds via HubConnectionBuilder would be the simplest solution.

Even nicer would be some way to configure this setting in my Startup.cs, probably with a new property available somewhere under the AddServerSideBlazor call, similar to how I can customize the server-side hub settings via AddServerSideBlazor().AddHubOptions(options => ... ).

### PR DESCRIPTION
**Pull request by surayya-MS**
# Added configureConnection delegate to CircuitStartOptions

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

Fixes #18840 by enabling user to configure HubConnection object like this:

```html
<script>
        Blazor.start({
            configureConnection: function (connection) {
                connection.serverTimeoutInMilliseconds = 120000;
            }
        });
</script>
```

### CODE REVIEW

**Comment by surayya-MS** [comment]
No automated tests for this. Tested manually:
1. Add configureConnection to the script in _Layout.chhtml inside BlazorServerApp sample:

<script>
        Blazor.start({
            logLevel: 1, // LogLevel.Debug
            configureSignalR: builder => builder.configureLogging("debug"), // LogLevel.Debug
            **configureConnection: function (connection) {
                connection.serverTimeoutInMilliseconds = 120000;
            }**
        });
    </script>

2. Start debugging with breakpoint on IncrementCount method in Pages/Counter.razor and wait

Result: 'Error: Server timeout elapsed without receiving a message from the server.' appeared in 2 minutes.

**Comment by TanayParikh** [comment]
I'm probably missing some context here, so apologies if this has already been discussed. Given we can already configure the server timeout as follows:

```js
<script>
  Blazor.start({
    configureSignalR: function (builder) {
      builder.serverTimeoutInMilliseconds = 30000;
      builder.keepAliveIntervalInMilliseconds = 15000;
    }
});
</script>
```

As we have [documented here](https://learn.microsoft.com/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0#configure-signalr-server-timeout-and-keep-alive-on-the-client). What's the motivation to provide a separate `configureConnection` method? Is it to potentially abstract away the concept of the builder object / SignalR?

**Comment by javiercn** [comment]
I think those docs are wrong.

The HubConnectionBuilder does not have those properties. See ***@***.***/signalr/hubconnectionbuilder?view=signalr-js-latest

**Comment by javiercn** [comment]
I think those docs are wrong.

The HubConnectionBuilder does not have those properties. See ***@***.***/signalr/hubconnectionbuilder?view=signalr-js-latest)

**Comment by TanayParikh** [comment]
Is the HTTP timeout the same thing?

builder.[httpConnectionOptions](https://github.com/dotnet/aspnetcore/blob/5e42cca2fab63c051be3a5c6104b8dce8add852c/src/SignalR/clients/ts/signalr/src/HubConnectionBuilder.ts#L45).[timeout](https://github.com/dotnet/aspnetcore/blob/5e42cca2fab63c051be3a5c6104b8dce8add852c/src/SignalR/clients/ts/signalr/src/IHttpConnectionOptions.ts#L69-L75) may be useful?

cc/ @guardrex

**Comment by guardrex** [comment]
Seemed ok per Brennan's feedback at ...

https://github.com/dotnet/AspNetCore.Docs/pull/27197#issuecomment-1270345517

I'm OOF this evening, but I'll work it first thing Wednesday morning and sort it out.

**Comment by TanayParikh** [comment]
I believe that one you linked is the `HubConnection`, whereas `configureSignalR` provides the `HubConnectionBuilder`. If it works, that's great, however the above distinction probably means the API isn't available as it's currently presented.

**Comment by guardrex** [comment]
I see. Ok ... I think Brennan was perhaps looking at the text and didn't spot my code problem. I have time first thing in the morning to fix it up. Now tracked by ...

**Foul SignalR code example fix needed**
https://github.com/dotnet/AspNetCore.Docs/issues/27320

**Comment by surayya-MS** [comment]
> I'm probably missing some context here, so apologies if this has already been discussed. Given we can already configure the server timeout as follows:
> 
> ```js
> <script>
>   Blazor.start({
>     configureSignalR: function (builder) {
>       builder.serverTimeoutInMilliseconds = 30000;
>       builder.keepAliveIntervalInMilliseconds = 15000;
>     }
> });
> </script>
> ```
> 
> As we have [documented here](https://learn.microsoft.com/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0#configure-signalr-server-timeout-and-keep-alive-on-the-client). What's the motivation to provide a separate `configureConnection` method? Is it to potentially abstract away the concept of the builder object / SignalR?

I tried to set serverTimeoutInMilliseconds through configuresignalR method. It doesn't work. We need to fix the docs

**Comment by guardrex** [comment]
I'm working on that right now, @surayya-MS, on the cross-linked docs issue.

**Pull request closed without merging**
