### PR TITLE
[SPA] Updates npm dependencies

### PR DESCRIPTION
**Pull request by javiercn**
image

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Comment by wtgodbe** [comment]
@Pilchie are you ok with this for tell-mode?

**Comment by dougbu** [comment]
> @Pilchie are you ok with this for tell-mode?

/ping (This PR updates dependencies used in our _shipping_ templates.)

**Comment by dougbu** [comment]
@mkArtakMSFT reminded me that dependency updates should always be treated as `tell-mode`. Discussion in Tactics probably took place a year or more ago.

**Comment by Pilchie** [comment]
> dependency updates should always be treated

Except if they introduce some interesting risk.

**Pull request merged**
