### PR TITLE
Revert "Update IdentityServer4 -> Duende (#33590)"

### PR DESCRIPTION
**Pull request by HaoK**
This reverts commit c754959e7133c4cf9e1fbaa610a2db2a7cb1399d.

There's some template tests that are failing due to this, reverting for now to address those before trying again

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
Looks good to unblock our builds

**Comment by dougbu** [comment]
@HaoK

1. Any idea why template tests are failing now and weren't in #33590❔
2. Are you optimistic about redoing #33390 before preview7 cut-off❔

**Comment by HaoK** [comment]
Yes, I added the template tests back to ProjectTemplates yesterday, since we had no coverage of the blazor templates...  So I caught myself breaking them...  It works!

**Comment by HaoK** [comment]
See https://github.com/dotnet/aspnetcore/commit/dcae2a696a7b76051f69ad7b0ef4541d607d3b3f

**Comment by HaoK** [comment]
I guess I didn't rebase from main after I merged that PR as I had both in flight doh

**Comment by HaoK** [comment]
> Are you optimistic about redoing Add mariner queue to helix matrix #33390 before preview7 cut-off❔

What's the ask here @dougbu I wasn't aware of anything about mariner/helix that i needed to do still?

**Comment by dougbu** [comment]
> What's the ask here @dougbu I wasn't aware of anything about mariner/helix that i needed to do still?

The ask was a typo. I meant #33590. Correcting in earlier comments&hellip;

**Comment by HaoK** [comment]
When's the cutoff?  At this point I think its more prudent to get it in early rc1

**Comment by HaoK** [comment]
This seems like a unrelated to this PR failure...  Maybe we should force merge this @dougbu ?

```
Microsoft.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SNI_PN11, error: 52 - Unable to locate a Local Database Runtime installation. Verify that SQL Server Express is properly installed and that the Local Database R
```

**Comment by dougbu** [comment]
> Maybe we should force merge this @dougbu ?

If the problem is consistent, I'd be fine w/ that. Didn't come to mind when I hit the "Rerun failed jobs" button but I leave the choice to you. Lemme know.

**Comment by HaoK** [comment]
Can see if it automerges after this run, but if it still is failing due to network access to sql server, we should just force merge this since its just a revert

**Comment by HaoK** [comment]
I actually do have the template changes ready, which also might fix the build break now :)  https://github.com/dotnet/aspnetcore/pull/34321

**Pull request merged**
