### PR TITLE
Update SDK

### PR DESCRIPTION
**Pull request by wtgodbe**
Brings in an SDK with https://github.com/dotnet/sdk/pull/17290, which should fix errors like the following that come from the new razor language version:

> ##[error]/datadisks/disk1/workspace/_work/1/s/src/Components/benchmarkapps/Wasm.Performance/TestApp/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/_Pages_GridRendering_razor.cs(202,78): error CS0305: (NETCORE_ENGINEERING_TELEMETRY=Build) Using the generic type 'Grid<TRowData>' requires 1 type arguments

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
Looks like we haven't been updating the SDK on Mondays as planned in any case.

**Review by captainsafia — APPROVED** [review]
LGTM.

I spotted some CI failures in the dotnet-api tests. Hopefully those are flakes. It looks like CI has bee rekicked now anyways.

**Comment by JunTaoLuo** [comment]
Blocked by https://github.com/dotnet/msbuild/issues/6377.

**Comment by JunTaoLuo** [comment]
Let's wait on the MSBuild issue investigation. Alternative is to downgrade our SDK version to one that work but that's not ideal.

**Pull request merged**
