### PR TITLE
Bump karma-sauce-launcher and saucelabs versions

### PR DESCRIPTION
**Pull request by sebastienros**
Fixing component governance.

The karma-sauce dependency is moved to the root `packages.json` file because npm is unable to take overrides into account in a workspace (bug?). `saucelabs` is the package that need to be bumped to remove a dependency on the `decompress` package which has the vulnerability.

We could just have ignored the CG alert since it's just for testing but it's better to update it to a supported version and in case other components require it for non-testing purposes.

### CODE REVIEW

**Comment by sebastienros** [comment]
packages-lock doesn't get updated if the override is in a workspace so the main dep is now in the root.

**Comment by javiercn** [comment]
> packages-lock doesn't get updated if the override is in a workspace so the main dep is now in the root.

Did you run `npm install` after setting the override?

**Comment by sebastienros** [comment]
> Did you run `npm install` after setting the override?

Yes. The override was only taken into account in the main package file. Even when running npm install from the FunctionaTests folder. I had to update nodejs too (20.10)

**Comment by javiercn** [comment]
> Yes. The override was only taken into account in the main package file. Even when running npm install from the FunctionaTests folder. I had to update nodejs too (20.10)

What did you put in the override field? The syntax can be tricky, and we might not be putting the right thing. Just want to make sure, because it's preferrable we don't push the dependencies all the way to the root unless they are common to two or more packages.

**Comment by sebastienros** [comment]
@javiercn exactly what this PR is doing, but in the FunctionalTests/packages.json

**Comment by javiercn** [comment]
@sebastienros Did you try recreating the package-lock.json? (Delete it and run npm install at the root to re-create it)

**Review by javiercn — APPROVED** [review]

**Comment by sebastienros** [comment]
@javiercn just tried and the override is not taken into account (also the "resolved" and "integrity" fields are being removed)

**Comment by javiercn** [comment]
> @javiercn just tried and the override is not taken into account (also the "resolved" and "integrity" fields are being removed)

Thanks for giving it a try. @wtgodbe this is something we should document for build-ops

**Comment by wtgodbe** [comment]
> @wtgodbe this is something we should document for build-ops

It's not clear to me from the PR change _exactly_ what the issue is - something like "If there's a CG alert in a npm project, move the dependency to `devdependencies` in the root `package.json` ?

**Comment by javiercn** [comment]
> It's not clear to me from the PR change exactly what the issue is - something like "If there's a CG alert in a npm project, move the dependency to devdependencies in the root package.json ?

The process in general to resolve the GC, not this individual case.

**Comment by sebastienros** [comment]
Since npm doesn't like comments in json I updated the description of this PR to reflect the details of this change.

**Comment by wtgodbe** [comment]
Spoke with Sebastien, I'll update the docs to describe the process. Something like:

When there is a CG alert on an npm component that is brought in transitively via one of our direct dependencies, remove that dependency from the project-level package.json, move it to the root-level package.json `devDependencies` section, and add an entry in the `Overrides` section for the updated version of the transitive dependency. See https://github.com/dotnet/aspnetcore/pull/53116 for an example.

**Comment by BrennanConroy** [comment]
That would work, but if we're trying to keep dependencies in individual projects then that should be the last resort. The first step should be updating the local dependency and see if that fixes it. Second is adding an override. Third would be moving to the root project.

**Comment by wtgodbe** [comment]
> That would work, but if we're trying to keep dependencies in individual projects then that should be the last resort. The first step should be updating the local dependency and see if that fixes it. Second is adding an override. Third would be moving to the root project.

Sebastien said that he tried adding an override in the local package.json, but that the package-lock.json file didn't get updated after doing that & running `npm ci` - only updating the root `package.json` got the lock file updated.

**Pull request merged**
