### PR TITLE
[release/5.0] Upload ProductVersion.txt to blob feed

### PR DESCRIPTION
**Pull request by wtgodbe**
5.0 part of https://github.com/dotnet/aspnetcore/issues/16859

Test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=910953&view=results

Test build against master, where the version is non-stable: https://dev.azure.com/dnceng/internal/_build/results?buildId=910961&view=results

### CODE REVIEW

**Review by mmitche — APPROVED** [review]

**Comment by wtgodbe** [comment]
Just realized we only want to upload this file from 1 configuration otherwise we'll get duplicates - just pushed a commit so it only gets created in the windows job. New builds:

5.0: https://dev.azure.com/dnceng/internal/_build/results?buildId=910992&view=results
master: https://dev.azure.com/dnceng/internal/_build/results?buildId=910993&view=results

**Review by JunTaoLuo — APPROVED** [review]

**Comment by wtgodbe** [comment]
Had to dedupe a property name, new builds:

5.0: https://dev.azure.com/dnceng/internal/_build/results?buildId=911241&view=results
master: https://dev.azure.com/dnceng/internal/_build/results?buildId=911242&view=results

**Comment by wtgodbe** [comment]
Failure in the one running against master: 

> ##[error].packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20601.2\tools\SdkTasks\PublishArtifactsInManifest.proj(99,5): error : (NETCORE_ENGINEERING_TELEMETRY=Publish) Some extensions have conflicting FileExtensionSignInfo: .msi

@mmitche is this the arcade thing that your PR is fixing?

**Comment by wtgodbe** [comment]
`productVersion.txt` against 5.0 contains `5.0.1`, against master it contains `6.0.0-alpha.1.20607.11`

**Pull request merged**
