### PR TITLE
Added Tag attribute to NavLink in Blazor.

### PR DESCRIPTION
**Pull request by korayturk**
I should be able to use the NavLink component with the Tag I want.

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
Thanks for your PR, @korayturk.
Can you please share a scenario where / how you would use this?

**Comment by mkArtakMSFT** [comment]
Thanks for your PR.
We're currently busy wrapping up our upcoming Blazor WASM release, which is planned to go out in May. That forces us to delay some community PR reviews which target ASP.NET Core 5.0, so please expect some delays here. We will get to this as soon as we wrap up the Blazor work.

**Comment by korayturk** [comment]
> Thanks for your PR, @korayturk.
> Can you please share a scenario where / how you would use this?

Thank you for your reply.
I made my NavBar with "li" tag so i need "active" class for "li" tag. I can also do it with another tag.
I thought it could be such a feature.

for example:
NavLink

**Comment by pranavkm** [comment]
@korayturk we discussed this and would prefer introducing a different type for this instead - something like `NavigationHighlight` which allows configuring the tag. Adding a tag to `NavLink` doesn't seem like the right design.

**Comment by mbvnkorayturk** [comment]
@pranavkm you are right. I will be waiting for the NavigationHighlight feature :)
Thanks for reviewing.

**Comment by korayturk** [comment]
@pranavkm you are right. I will be waiting for the NavigationHighlight feature :)
Thanks for reviewing.

**Pull request closed without merging**
