### PR TITLE
Update EF submodule to head of its 'release/2.2' branch

### PR DESCRIPTION
**Pull request by dougbu**
- should include this in next 2.2.x release
- EF submodule is at least one (no-op) merge behind w/o this

/cc @Pilchie

### CODE REVIEW

**Comment by dougbu** [comment]
@Pilchie do we need servicing approval to flow the latest EF commit into this repo?

**Comment by Pilchie** [comment]
I would treat this as a tell-mode change.

**Comment by dougbu** [comment]
> I would treat this as a tell-mode change.

:ok: I'll send the requisite email after branding updates are done and we get this in

**Comment by dougbu** [comment]
/ping @JunTaoLuo I'd like to merge this soon after your branding updates

**Comment by dougbu** [comment]
@JunTaoLuo ?

**Review by JunTaoLuo — APPROVED** [review]

**Pull request merged**
