### PR TITLE
Revert "Add an option to SignalR to guarantee ordering of send events…

### PR DESCRIPTION
**Pull request by pranavkm**
… (#10506)"

This reverts commit 4646c4a5e4412dbff6e40ade887792241f5a2c94.

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Well... we can keep the change in SignalR and just remove all the infrastructure stuff.

**Comment by pranavkm** [comment]
Just keeping this prepped. I'd like to take a stab at fixing the build if I can with the change.

**Comment by BrennanConroy** [comment]
>Just keeping this prepped. I'd like to take a stab at fixing the build if I can with the change.

Sure, but a better prep is to not remove the feature you made :D

**Comment by pranavkm** [comment]
@aspnet/build could you merge this in? The official build is currently broken due to this change.

cc @Pilchie \ @mkArtakMSFT

**Review by natemcmaster — APPROVED** [review]
:shipit: We haven't had a successful build since the original PR went in, and it's blocking preview6 dependency flow. Let's avoid rushing in a fix and target preview7.

**Pull request merged**
