### PR TITLE
Reorganize Versions files to indicate compilers is not automated

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
👍

BTW I'm not sure it matters but aspnetcore-tooling uses Microsoft.Net.Compilers.Toolset v3.8.0-3.20454.4. May want to match the more recent version here.

**Comment by pranavkm** [comment]
I think we're newer than them:

```
AspNetCore-Tooling: 3.8.0-3.20454.4
AspNetCore: 3.8.0-3.20458.6
```

**Comment by dougbu** [comment]
> I think we're newer than them:

Agreed. I meant we may want to update aspnetcore-tooling to match aspnetcore

**Comment by pranavkm** [comment]
@dougbu could you merge this please?

**Comment by dougbu** [comment]
Please prepare a 'release/5.0' PR since this didn't make the cut off.

**Pull request merged**
