### PR TITLE
Fix summary formatting

### PR DESCRIPTION
**Pull request by martincostello**
# Update build from source docs

Fix the formatting of the interlude to render the link correctly and be a bit easier to read.

/cc @captainsafia

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Comment by mkArtakMSFT** [comment]
@wtgodbe would you please work with @martincostello as necessary to get this PR merged? You've already signed off on it anyway, so it's a matter of getting the CI to pass.

**Comment by captainsafia** [comment]
@mkArtakMSFT This is actually a PR that Martin has opened on one of my own branches. I've been working on updating the build docs and have requested feedback from community members on my branch.

I can get this merged.

**Comment by martincostello** [comment]
Yep sorry, that was my bad. I read Safia’s tweet and didn’t realise it was against a branch, rather than something already on `main`.

**Comment by captainsafia** [comment]
> Yep sorry, that was my bad. I read Safia’s tweet and didn’t realise it was against a branch, rather than something already on `main`.

No worries! If you're interested, you can submit a PR against main too. In any case, this update will funnel up eventually as part of the changes in this branch.

**Pull request merged**
