### PR TITLE
Backport Use CDN for .NET Assets for release/3.1

### PR DESCRIPTION
**Pull request by TanayParikh**
https://github.com/dotnet/aspnetcore/pull/39007

### CODE REVIEW

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
@MattGal is this change correct for release/3.1❔ Seeing errors like the following in most build jobs:

``` text
error : Problems downloading file from 'https://dotnetbuilds.azureedge.net/public/Runtime/3.1.21-servicing.21522.1/dotnet-runtime-3.1.21-win-x64.zip'. Does the resource exist on the storage? NotFound : Not Found
```

**Comment by MattGal** [comment]
> @MattGal is this change correct for release/3.1❔ Seeing errors like the following in most build jobs:
> 
> ```
> error : Problems downloading file from 'https://dotnetbuilds.azureedge.net/public/Runtime/3.1.21-servicing.21522.1/dotnet-runtime-3.1.21-win-x64.zip'. Does the resource exist on the storage? NotFound : Not Found
> ```

No it's not, I'm not sure how far back it goes but I wouldn't expect anywhere @alexperovich didn't plan for it to go.  I'll peek at what's in there and report back.

**Comment by MattGal** [comment]
@dougbu / @TanayParikh there's nothing earlier than 6.x in dotnetbuilds, so you can't use this approach.  Instead just use the existing CDN versus blob storage URL (`dotnetcli.azureedge.net`)

**Comment by TanayParikh** [comment]
Not working with `dotnetcli.azureedge.net` either, leaving as is.

**Comment by TanayParikh** [comment]
@dotnet/aspnet-build requesting merge please.

**Pull request merged**
