### PR TITLE
Touch up installation instructions

### PR DESCRIPTION
**Pull request by dougbu**
- fixes for BuildFromSource.md
- a replacement for #18082

### CODE REVIEW

**Comment by kp2017** [comment]
Doug, 
The changes you made in 581925 clarify the required versions of the software. The original issue was concerned with instructing the user how to perform a clone after instructions using those files were referenced. While your change is nice, it doesn't resolve the issue of the user needing to perform a clone prior to reaching the clone instructions.

**Comment by dougbu** [comment]
@kp2017 my changes do clarify the requirements for a VS installation. More importantly for your concern, the changes make it clear there's no requirement to use the scripts from the repo.

What are you suggesting adding to the two references to those scripts?

**Comment by kp2017** [comment]
The code in my PR moved the clone instructions before the statements requiring the files which is why it solved the issue. Your response again does not acknowledge the original issue.

**Comment by dougbu** [comment]
@kp2017 your original request was misleading because the repo does not normally need to be cloned before acquiring the prerequisites -- something you have not acknowledged. I suggested making it even clearer that using the scripts is not required. Now, just as you asked me for a _different_ specific recommendation, I'm asking you for one.

For example, would you be satisfied if I added a link from the bullets using the repo's scripts to the cloning section?

**Comment by kp2017** [comment]
@dougbu I have not acknowledged "clone is normally not required prior to prerequisites" because that is not a norm. Prerequisites are intended to prepare the reader for whats to come. In this particular case, cloning is required since developers have written optional scripts to help automate some of the prerequisites.

My original change was to move the clone information above were the scripts were references. This brought the repository into scope and gave access for the reader to run the scripts. This is still a viable solution in my perspective. I requested you provide an alternative so because I didn't understand what you were communicating in your comments. From your proposed change, I recognized you were not referring to wording around cloning the repositories; instead you were notifying other versions of software was acceptable. This was not related to the original issue. So I still think my original change is better because it is valid.

In your latest comment, you suggested adding links to the cloning instruction. While this is a valid alternative to the issue, it seems to break the natural flow of reading (top down) and requires duplicate entries and additional steps if new scripts are added. You haven't provided a tangible implementation of this suggestion, so this is my perspective of it without seeing the actual wording. 

Ultimately I don't understand your concerns. Adding the clone to the top resolves all ambiguity with very little work. There isn't a standard that says cloning should not be included in prerequisites because prerequisites are supposed to be fluid to the needs of the project. I guess we could take of the scripts because the users code do these tasks manually, but what is our goal here?

**Comment by dougbu** [comment]
Despite what you've say, cloning is _not_ required to be done first. The "optional scripts to help" are just that -- _optional_. My concern is about making a change which implies otherwise.

If users choose to use the scripts the first time they follow the instructions, it's rather obvious they need to have cloned the repo first. But, that's not the "norm". IOW I understand your concern but disagree about it's severity (or that anything is ambiguous).

I'm not willing to make the drastic change you suggested. So, please make another suggestion.

**Comment by kp2017** [comment]
I am fine the way it is. I was just trying to help others be providing my
perspective of when I first ran through it. Ultimately, this is not life
changing to me or as important as it seems to be to you. I am fine
expressing my opinion and leaving it for others to do as they please.

**Comment by dougbu** [comment]
Thanks @kp2017.

@dotnet/aspnet-build please review -- all checks have passed.

**Review by wtgodbe — APPROVED** [review]

**Pull request merged**
