### PR TITLE
Allow null arguments from HubConnection

### LINKED ISSUE #11239: Null ref in HubConnection if parameter is null
```C#
   at System.Object.GetType()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.PackageStreamingParams(ConnectionState connectionState, Object[]& args, List`1& streamIds)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.SendCoreAsyncCore(String methodName, Object[] args, CancellationToken cancellationToken)
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.SendCoreAsync(String methodName, Object[] args, CancellationToken cancellationToken)
   at BenchmarksClient.Workers.BlazorIgnitor.<>c__DisplayClass23_2.<<Clicker>b__1>d.MoveNext() in D:\work\Benchmarks\src\BenchmarksClient\Workers\BlazorIgnitor.cs:line 160
```

I did `connection.SendAsync("foo", 1, null);`

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/aspnet/AspNetCore/issues/11239

### CODE REVIEW

**Review by pranavkm — APPROVED** [review]

**Comment by pranavkm** [comment]
Does the Java client need to be fixed?

**Comment by BrennanConroy** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=225978&view=logs

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2489
https://github.com/aspnet/AspNetCore-Internal/issues/1979

**Comment by mikaelm12** [comment]
> Does the Java client need to be fixed?

https://github.com/aspnet/AspNetCore/blob/f652c222028ebd504203dce6a68e67b416465aab/src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/HubConnection.java#L582
`instanceof` works with `null` so I think it should be fine. I'll add a test though to be sure.

**Review by mikaelm12 — APPROVED** [review]

**Pull request merged**
