### PR TITLE
Clean up obsolete types in Razor

### PR DESCRIPTION
**Pull request by captainsafia**
Part of #27529.

**Summary of Changes**
- Remove `IRazorEngineBuilder` references and tests since it has been obsoleted for a while.
  - Didn't remove interface because `RazorEngine` takes dependency on it.
- Obsoleted `RazorEngine` type.
   - We were planning on removing this type but it looks like our tests rely on it extensively. If we were to remove it we'd have to do an extensive refactor of the tests.
- Un-obsolete `GetItem` since it was recently obsoleted.

### CODE REVIEW

**Comment by ajaybhargavb** [comment]
> Did not remove obsolete IRazorCodeGenerationOptionsFeature or IRazorParserOptionsFeature. Will removing these cause issues with older Razor engines?

@NTaylorMullen, do you recall whether we still use these for anything or can they be safely removed? Context [here](https://github.com/dotnet/aspnetcore/blob/master/src/Razor/Microsoft.AspNetCore.Razor.Language/src/RazorProjectEngine.cs#L160)

> Did not remove obsolete [GetItem](https://github.com/dotnet/aspnetcore/blob/b795ac3546eb3e2f47a01a64feb3020794ca33bb/src/Razor/Microsoft.AspNetCore.Razor.Language/src/RazorProject.cs#L32) since it was recently obsoleted.

@NTaylorMullen, this was obsoleted around April 2019. Can we safely remove it now but do you think we should wait for another release? I'm not sure if this is something customers will be depending on.

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen, do you recall whether we still use these for anything or can they be safely removed? Context [here](https://github.com/dotnet/aspnetcore/blob/master/src/Razor/Microsoft.AspNetCore.Razor.Language/src/RazorProjectEngine.cs#L160)

Hmmm you can validate to see if they're consumed at all in the Mvc 1_x / 2_x projects: https://github.com/dotnet/aspnetcore/tree/master/src/Razor/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X



> @NTaylorMullen, this was obsoleted around April 2019. Can we safely remove it now but do you think we should wait for another release? I'm not sure if this is something customers will be depending on.

Actually I think I was stupid for obsoleting this at all. I'd actually say it's probably worth "unobsoleting" it. There's still value.

**Comment by captainsafia** [comment]
> Actually I think I was stupid for obsoleting this at all. I'd actually say it's probably worth "unobsoleting" it. There's still value.

Fair point. Un-obsoleted.

> Hmmm you can validate to see if they're consumed at all in the Mvc 1_x / 2_x projects: https://github.com/dotnet/aspnetcore/tree/master/src/Razor/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X

There's not consumed there. Just the Razor tests. I guess that means safe to remove?

**Comment by NTaylorMullen** [comment]
> There's not consumed there. Just the Razor tests. I guess that means safe to remove?

Yup

**Review by ajaybhargavb — APPROVED** [review]

**Comment by pranavkm** [comment]
* Leave the extension methods alone if we aren't removing the interfaces. Feel free to obsolete the extension methods and consider removing them post 6.0.
* Feel free to remove everything from the 1_x and 2_x projects since they are tooling only.

**Comment by captainsafia** [comment]
Closing in favor of https://github.com/dotnet/aspnetcore/pull/28706.

**Pull request closed without merging**
