### PR TITLE
Suggested addition to PR 34000

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
I was making sure I fully understood the changes to the event serialization mechanism and as part of it, noticed a couple of opportunities to make it cheaper:

 * On WebAssembly, the change in #34000 meant we were double-JSON-encoding the event details in JS and then doing an extra manual UTF8-decoding in .NET. We can bypass that by using @TanayParikh's binary interop so we get the UTF8 `byte[]` data directly in .NET. The only extra cost then is doing UTF8 encoding in JS, but (1) that's incredibly inexpensive, and (2) it's offset by making the wrapper JSON so much smaller.
    * As a side-benefit, now when we're sending event payloads like a "textbox change to have this new massive string", the .NET side no longer has to marshal it through an extra encoding. It receives bytes for the UTF8-JSON from which STJ can UTF8-decode a .NET string, whereas before it received a .NET string for the JSON that we then UTF8 encoded in .NET and then UTF8 decoded back into the user-supplied string.
 * On Server, #34000 was already using binary interop, but was sending two args when we could send one. This makes a (small) difference because each `byte[]` value is sent as a separate SignalR message.
   * ~~My change in this PR very slightly reduces the maximum size of string you can send, because now it has to fit alongside the event metadata in a single SignalR message. However that was already the case in 5.0, and in fact the move to binary serialization in 6.0 means we can now send 33% more data free (or something like that).~~ Update: no that's not true, since we limit the total size of all the binary messages to equal roughly 1 SignalR message, so in fact my suggestion here is just a pure win.

### CODE REVIEW

**Review by javiercn — APPROVED** [review]
Looks great!

**Comment by javiercn** [comment]
@SteveSandersonMS In addition to this, do you think we should consider "unstringifying" the methods on ComponentHub to deserialize the types directly? That sounds like another potential big win (we avoid all the intermediate string copy).

Not saying you do this here, just bring in it up for discussion/possible follow up.

**Comment by SteveSandersonMS** [comment]
@javiercn Do you mean the methods like `BeginInvokeDotNetFromJS`?

If so, I did consider that but didn't because the big drawback to changing this is that we'd only get a benefit if we also change the underlying JS interop contract (or completely break the layering). JS interop is defined in terms of exchanging JSON strings. We could redefine it in terms of exchanging byte arrays, but that would be very breaking for anyone who's built anything custom with `Microsoft.JSInterop`, or potentially very confusing if we did it in an additive way - i.e., becoming able to exchange either strings or byte arrays and having to support all combinations to have a valid implementation.

On balance I'd be happy with the improvements we're getting in 6.0 while retaining back-compat. There's always the option to change this in the future and perhaps give the ecosystem more time to react if we did it early in 7.0. @pranavkm What do you think?

**Comment by javiercn** [comment]
> @javiercn Do you mean the methods like `BeginInvokeDotNetFromJS`?
> 
> If so, I did consider that but didn't because the big drawback to changing this is that we'd only get a benefit if we also change the underlying JS interop contract (or completely break the layering). JS interop is defined in terms of exchanging JSON strings. We could redefine it in terms of exchanging byte arrays, but that would be very breaking for anyone who's built anything custom with `Microsoft.JSInterop`, or potentially very confusing if we did it in an additive way - i.e., becoming able to exchange either strings or byte arrays and having to support all combinations to have a valid implementation.
> 
> On balance I'd be happy with the improvements we're getting in 6.0 while retaining back-compat. There's always the option to change this in the future and perhaps give the ecosystem more time to react if we did it early in 7.0. @pranavkm What do you think?

JS interop is likely the most prevalent case, there are other places that might also be interesting like StartCircuit and so on. In general, it could help reduce the pressure on the GC, although I would say JS interop would likely be the most common case.

We could potentially do this in a non-breaking way for server only if we wanted to (for JS interop at least) if we provide the necessary hooks in JSRuntime. 

The biggest drawback of a breaking change here, would be unit testing, which could be "solved" by providing a backwards compatible implementation on the base class that delegated to the string version. 

TBH. I think that the "mechanics" of JS interop are low level enough that it is unlikely someone else can effectively customize them (you certainly not use this in Blazor wasm or server since we require to use our own internal implementations) and I doubt anyone has actually done that in a way that wouldn't be marginally used.

**Comment by pranavkm** [comment]
IMO, if we really want to think about this as a perf improvement, we should start getting some profiles and measure the improvement. The current changes happened to remove a couple of allocations, but the only motivator for these changes were to remove STJ reflection / source generator for browser events.

**Pull request merged**
