### PR TITLE
Make IQueryableUserStore async

### PR DESCRIPTION
**Pull request by stefannikolei**
Summary of the changes (Less than 80 chars)
 - Detail 1
 - Detail 2

Addresses #bugnumber (in this specific format)

### CODE REVIEW

**Comment by pranavkm** [comment]
@reaction1989 is there a specific issue you're trying to address? In particular given this is a breaking change, it's valuable to understand how you got to this particular change.

**Comment by reaction1989** [comment]
@pranavkm There is a issue for this: #6331 

Should I continue on it or is it not wanted? If I should continue I would also recommend to look at IQueryableRoleStore

**Comment by HaoK** [comment]
Seems like it might be worth considering doing this as a non breaking change and just add a new async IAsyncQueryableUserStore interface with the new method there.  Thoughts @ajcvickers ?

**Comment by ajcvickers** [comment]
@HaoK Doesn't make sense to me. The `IQueryable` can be used for async queries in the normal way.

**Comment by HaoK** [comment]
@ajcvickers so if I'm understanding you correctly, you are saying we don't really need an async way to get an `IQueryable` because you can already use the async variants of APIs off of it, i.e. `ToListAsync()`

**Comment by HaoK** [comment]
Sounds like we should just close the underlying issue then

@blowdart you ok with closing out this PR and https://github.com/aspnet/AspNetCore/issues/6331 as won't fix since (at least for EF) you can already do async with IQueryable and realistically we don't expect other implementations of this store (is there any we know of today even?)

**Comment by blowdart** [comment]
Closing as EF already allows async. If another store not based on EF comes through we may reconsider.

**Pull request closed without merging**
