### PR TITLE
Move `System.ComponentModel.Annotations` To Manual Dependency Update

### PR DESCRIPTION
**Pull request by TanayParikh**
It's not possible to remove this dependency (https://github.com/dotnet/aspnetcore/pull/32447) so making it so we no longer try to automatically update it. With automated updates enabled, it's leading to a 'stale' dependency tree as this package uses a commit that's different from the rest of our dotnet/runtime ingestion.

### CODE REVIEW

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
also /fyi @BrennanConroy

**Comment by Pilchie** [comment]
Why do we have a pinned dependency for this in the first place? This doesn't seem to be one of the dead-ended packages?

**Comment by TanayParikh** [comment]
Automerged before I could address the comment.

> Why do we have a pinned dependency for this in the first place? This doesn't seem to be one of the dead-ended packages?

The dependency was no longer being updated, I didn't see any recent packages for it either. @dougbu do you know if it is in fact EOL?

**Comment by dougbu** [comment]
Must have been EOL'ed fairly recently. `6.0.0-preview.5.21227.3` remains the newest package version in the dotnet6 feed even though e.g. System.Text.Json is at `6.0.0-preview.5.21256.5`. @Anipik @ericstj is that correct❔

**Comment by dougbu** [comment]
@Anipik and @ericstj, should we be pinning the 5.0.0 version of this package to get the latest and greatest assembly when targeting `netstandard2.0` or `net461`❔  We shouldn't use the `6.0.0-preview.5.21227.3` version when we get to RTM.

**Comment by Pilchie** [comment]
Also tagging @ViktorHofer as the author of https://github.com/dotnet/runtime/pull/51891

**Comment by ericstj** [comment]
@ViktorHofer removed this package with https://github.com/dotnet/runtime/pull/51891.  

> should we be pinning the 5.0.0 version of this package

Yes

**Pull request merged**
