### PR TITLE
Update SQLitePCL.raw version to 1.1.12

### PR DESCRIPTION
**Pull request by bricelam**

### CODE REVIEW

**Comment by natemcmaster** [comment]
Duplicate of https://github.com/aspnet/AspNetCore/pull/9391?

**Comment by natemcmaster** [comment]
correction, duplicate of https://github.com/aspnet/AspNetCore/pull/9390?

**Comment by ajcvickers** [comment]
@natemcmaster @bricelam I closed the other one because I misunderstood what was needed.

**Review by natemcmaster — CHANGES_REQUESTED** [review]
Same as the other PR. Additional steps are required as described in https://github.com/aspnet/AspNetCore/blob/release/2.1/docs/PreparingPatchUpdates.md to actually get new EF Core packages built.

* Update submodules.props https://github.com/aspnet/AspNetCore/blob/release/2.1/build/submodules.props#L40
* Update versions.props in the EFCore code to ship a new patch version
* Update the EF Core submodule in this repo

**Comment by bricelam** [comment]
Closing. Going to pin the versions in aspnet/EntityFrameworkCore instead.

**Pull request closed without merging**
