### PR TITLE
arcade requires MSBuild 16.3

### PR DESCRIPTION
**Pull request by k1iguchi**
Summary of the changes (Less than 80 chars)
change vs required version 16.0 to 16.3

Addresses #bugnumber (in this specific format)
#16684

(Previously I did wrong request(at #21868) merge to master, but this should be PR to rel3.1. )

### CODE REVIEW

**Comment by dougbu** [comment]
We should not need a newer VS version when building the release/3.1 branch. Our master branch requires only 16.5, not the most recent version.

What is the exact error you see when using something earlier than 16.3?

**Comment by dougbu** [comment]
I just saw #23569 which reports the .NET SDK we're using in release/3.1 requires VS 16.3.0 or later. Do you get a similar error to that reported in #23569❔

@dsplaisted / @wli3 am I correct on the minimum version of `msbuild` the "3.1.103" SDK requires❔ Will this change in newer 3.1 SDKs❔

**Comment by dsplaisted** [comment]
Yes, the 3.1.1xx series of SDKs require VS 16.3 or higher.  That won't change within a given SDK band (3.1.1xx), but can change for higher version bands.  For example, 3.1.4xx requires VS 16.7.

This is because the SDK may depend on new MSBuild features, so we have the capability to bump the minimum required version of MSBuild / VS if that's the case.

**Review by dougbu — APPROVED** [review]
Alright, let's get this into the release/3.1 branch the next time it's open.

**Comment by dougbu** [comment]
@dotnet/aspnet-build please help me remember to get this into 3.1.7.

**Comment by BrennanConroy** [comment]
@dougbu Reminder

**Comment by dougbu** [comment]
Thanks very much @k1iguchi❕ Also @BrennanConroy thanks for the reminder -- I needed it❕

**Pull request merged**
