### PR TITLE
Support Custom Classes for ValidationMessage

### LINKED ISSUE #38528: Customize ValidationMessage classes
### Is your feature request related to a problem? Please describe.

Using Blazor/Razor, there is a way to override the CSS classes that are using when validating form components, like `<InputText>` (read the docs [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0#custom-validation-css-class-attributes-1)).

The custom CSS rules only work for form fields, but not for the `<ValidationMessage>` component. The class attribute is overridden/set in the `ValidationMessage` component (see [here](https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Components/Web/src/Forms/ValidationMessage.cs#L77)).

### Describe the solution you'd like

I would expect to be able to override the css classes used for the `ValidationMessage` in the same way I can override the other input's css using the `FieldCssClassProvider`. Even better would be to be able to override the CSS directly in the `ValidationMessage` component using the `class`-attribute.

### PR DESCRIPTION
**Pull request by eluchsinger**
# Support Custom Classes for ValidationMessage

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Change the sequence of the attributes added to the ValidationMessage, so that the custom `class` attributes don't get overwritten by the default `class` attribute.

## Description

The ValidationMessage component does not allow to set custom `class` attributes. If a custom `class` attribute is set, it will get overridden by the default one.

This change permits custom `class` attributes to be set and take precedence over the default ones.

Fixes #38528

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
Thanks @eluchsinger.
@SteveSandersonMS can you please look into this PR and work with @eluchsinger to get it merged? Thanks!

**Comment by eluchsinger** [comment]
@mkArtakMSFT I couldn't get the repository to run on my M1 Mac. That is why I only have created this PR as a draft, as I haven't checked the tests for the changes or run the changes themselves.

**Comment by TanayParikh** [comment]
> @mkArtakMSFT I couldn't get the repository to run on my M1 Mac. That is why I only have created this PR as a draft, as I haven't checked the tests for the changes or run the changes themselves.

Hey @eluchsinger, feel free to try out the GitHub Codespaces environment which automatically sets up the repository for you :)

**Comment by eluchsinger** [comment]
@TanayParikh do I need to setup the Codespaces myself? I have tried them out already, but it was on my own repo.

**Comment by TanayParikh** [comment]
> @TanayParikh do I need to setup the Codespaces myself? I have tried them out already, but it was on my own repo.

We have Codespaces setup scripts that run when the Codespaces instance is created. It'll restore all the dependencies and install the requisite extensions for you. So you should just be able to start a Codespace from this repo and everything will be setup for you.

**Comment by eluchsinger** [comment]
Thanks @TanayParikh . It worked a charm!

I have verified and there are no tests for ValidationMessage at all. Since this is a really small change, probably I wouldn't add more tests now.

**Comment by SteveSandersonMS** [comment]
It would be good to have an equivalent change in https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Components/Web/src/Forms/ValidationSummary.cs#L78-L79 to keep this functionality consistent. And E2E tests of course.

> I have verified and there are no tests for ValidationMessage at all. 

There are various tests in https://github.com/dotnet/aspnetcore/blob/main/src/Components/test/E2ETest/Tests/FormsTest.cs that look for `ValidationMessage` output (e.g., via `appElement.FindElements(By.ClassName("validation-message"))`).

**Comment by pranavkm** [comment]
@SteveSandersonMS are we fine merging this without a test? I'd rather not keep the PR open for too long.

**Comment by SteveSandersonMS** [comment]
@pranavkm I know it's a relatively simple PR, but I was still feeling a bit uncomfortable about no-tests if people are going to take a dependency on this behavior that just comes down to the almost arbitrary-looking ordering of lines.

So I went digging and ended up discovering we have a bigger gap around `ValidationSummary`, so I have implemented tests for this and that in https://github.com/dotnet/aspnetcore/pull/39990

As such we can close the PR in favour of https://github.com/dotnet/aspnetcore/pull/39990. OK?

**Pull request closed without merging**
