### PR TITLE
Update 5.0/6.0 SiteExtension versions

### PR DESCRIPTION
**Pull request by wtgodbe**

### CODE REVIEW

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
Whoa what gives on the CI validation❔

**Comment by wtgodbe** [comment]
> ##[error]The agent did not connect within the alloted time of 45 minute(s).

@dotnet/dnceng is there a known outage in the windows machines?

**Comment by ulisesh** [comment]
The pool is at max capacity (750 machines), @ilyas1974, did we make any decisions about the capacity of NetCore1ESPool-Public
pool?

**Comment by ulisesh** [comment]
@wtgodbe we increase the capacity of the pool and your job should get a machine soon. Sorry for the inconvenience

**Comment by ilyas1974** [comment]
Unfortunately, we do not have additional budget at this time to increase the capacity on this queue. Do we know what is causing this increase in usage? Is there anything that can be done to reduce the amount of work or to re-distribute the workloads throughout the day?

**Comment by ulisesh** [comment]
@ilyas1974 let's discuss it in our teams channel

**Pull request merged**
