### PR TITLE
Build aspnetcore for win-arm64 (#19317)

### PR DESCRIPTION
**Pull request by JunTaoLuo**
Addresses https://github.com/dotnet/aspnetcore/issues/21146

### CODE REVIEW

**Comment by ryanbrandenburg** [comment]
https://dev.azure.com/dnceng/public/_build/results?buildId=618748&view=logs&j=e3a5384c-bb27-5334-a10c-747a68c0a4ee&t=a6b98f8e-728d-56fa-dab1-81115ea86b79&l=2046 seems crossgen doesn't support ARM64 as of yet.

**Comment by JunTaoLuo** [comment]
Turns out our logic was updated in master to pick the correct crossgen but this is not the case in release/3.1. In any case, it looks like the build is successful, however, we don't really have a good way to verify the assets we produce. @tommcdon do you know if anyone can help us test the aspnetcore runtime?

**Review by dougbu — APPROVED** [review]

**Comment by tommcdon** [comment]
> Turns out our logic was updated in master to pick the correct crossgen but this is not the case in release/3.1. In any case, it looks like I fixed that issue, however, we don't really have a good way to verify the assets we produce. @tommcdon do you know if anyone can help us test the aspnetcore runtime?

Hi @JunTaoLuo! Yes my team will take on the testing. Thank you very much for pulling together this PR!

**Comment by JunTaoLuo** [comment]
@tommcdon Any updates on testing?

**Comment by tommcdon** [comment]
@JunTaoLuo  testing is complete

**Pull request merged**
