### PR TITLE
[Blazor] Constructor injection

### LINKED ISSUE #18088: Constructor injection for Blazor components
### Is your feature request related to a problem? Please describe.
Constructor injection in Components was ruled out previously as "we don't plan to do this" but now that we have partials is there any change in this attitude?
see #15779 , #5497

### Describe the solution you'd like
If Blazor could be modified to optionally use DI to source components, then constructor injection would be possible,

If you would be open to at least reviewing a PR, I'm sure the community would do the groundwork to make it happen.

### PR DESCRIPTION
**Pull request by javiercn**
Fixes #18088

Reverts 87f870d65900f1d7bb0f54efae9e5f75b7b4a9dd

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
Can you document how we know this doesn't reintroduce the problems we had with constructor injection before? https://github.com/dotnet/aspnetcore/issues/40521

**Comment by javiercn** [comment]
@SteveSandersonMS https://github.com/dotnet/aspnetcore/issues/18088#issuecomment-1520774074

**Comment by javiercn** [comment]
@SteveSandersonMS I suspect is https://github.com/dotnet/runtime/commit/a48e73a3187d8d040b698cba7b6c5542ef3c7db8

**Comment by SteveSandersonMS** [comment]
> I haven't done size testing myself, but given we are early in the release, I think we can make this go in, and observe if we find any regression in our regular runs. Are you ok with that?

It's less for us to keep track of if you just do a one-off manual publish locally to see the impact on final sizes, otherwise if some regression appears two weeks from now, we have to go through a whole detective process to trace it back to the cause.

**Review by MackinnonBuck — APPROVED** [review]

**Comment by javiercn** [comment]
> It's less for us to keep track of if you just do a one-off manual publish locally to see the impact on final sizes, otherwise if some regression appears two weeks from now, we have to go through a whole detective process to trace it back to the cause.

I did measure the change for the Blazor hosted app in release configuration between main and this branch and the size is the same.

**Pull request merged**
