### PR TITLE
Clean cmd/powershell commands to install dnvm

### PR DESCRIPTION
**Pull request by twsouthwick**
This change switches it to use built in types and piping.  There was also a branch variable set that was never used.

### CODE REVIEW

**Comment by Eilon** [comment]
@glennc @anurse

**Comment by glennc** [comment]
This needs to work on Powershell v2 (the default on Windows 7 machines). AFAIK Invoke-WebRequest only works on 3, right?

**Comment by twsouthwick** [comment]
Ah I didn't realize that.  Yeah, Invoke-WebRequest is a v3+ cmdlet.  Is v2 supported just because it is the default on Win7?

**Comment by Eilon** [comment]
@twsouthwick yep I believe that's the reason. We don't want to require Win7 users to update their PowerShell installation.

**Comment by twsouthwick** [comment]
Okay.  So much nicer in PowerShell v3+ :) I'll close this PR

**Pull request closed without merging**
