### PR TITLE
skip flaky SignalR test: ErrorDuringPollWillCloseConnection

### PR DESCRIPTION
**Pull request by analogrelay**
see #8138 for discussion on test priority and re-enabling

### CODE REVIEW

**Review by BrennanConroy — APPROVED** [review]
\*grumble\*pipes\*grumble\*

**Review by mikaelm12 — APPROVED** [review]
😕

**Review by halter73 — APPROVED** [review]

**Comment by anurse** [comment]
Blocked by https://github.com/aspnet/AspNetCore/issues/8182 (ironic...)

**Pull request merged**
