### PR TITLE
Microsoft.AspNetCore.App =>Ref in the platform manifest

### LINKED ISSUE #13108: Platform Manifest in ASP.NET Core targeting pack should use the targeting pack package name
In the ASP.NET Core targeting pack (Microsoft.AspNetCore.App.Ref), there is a `data/PlatformManifest.txt` file which includes assembly and file versions for the contents of the targeting pack.  This is an optimization so that the files don't need to be read from disk to get these versions for conflict resolution.  The format looks like this:

```
aspnetcorev2_inprocess.dll|Microsoft.AspNetCore.App||13.0.19219.0
Microsoft.AspNetCore.Antiforgery.dll|Microsoft.AspNetCore.App|3.0.0.0|3.0.19.40702
Microsoft.AspNetCore.Authentication.Abstractions.dll|Microsoft.AspNetCore.App|3.0.0.0|3.0.19.40702
```

The second element is interpreted as the package name.  This should be updated to match the targeting pack package name, or Microsoft.AspNetCore.App.Ref.  As it is currently, the versions from the platform manifest aren't being used by conflict resolution, as it thinks they apply to files from a different package name.

### PR DESCRIPTION
**Pull request by jkotalik**
Fixes #13108. This is an infrastructure change, so this may fall under tell mode. @anurse ?

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]
Looks reasonable

**Review by dougbu — APPROVED** [review]

**Comment by jkotalik** [comment]
Slapping tell mode on this for now, @dsplaisted @anurse if this deserves an ask mode label, I'll adjust and add the template.

**Comment by dsplaisted** [comment]
@jkotalik  As far as I know this should go through ask mode.

**Comment by anurse** [comment]
Doesn't hurt to run it through the process. I'll send an email.

**Review by JunTaoLuo — APPROVED** [review]

**Comment by jkotalik** [comment]
I _believe_ this was approved. @anurse you may do the honors.

**Comment by anurse** [comment]
I concur with your assessment :)

**Pull request merged**
