### PR TITLE
Unquarantine Tests

### PR DESCRIPTION
**Pull request by TanayParikh**
Found a bunch of tests running for 30+ days with 100% pass rate.

Are these fine to unquarantine?

### CODE REVIEW

**Review by BrennanConroy — APPROVED** [review]
SignalR and dotnet-watch tests look good to unquarantine :+1:

**Comment by TanayParikh** [comment]
@halter73 / @SteveSandersonMS / @Tratcher / @jkotalik are the rest of the tests (Kestrel, IIS, etc.) fine to unquarantine?

**Comment by pranavkm** [comment]
The dotnet-watch ones are slightly suspect. I don't think it's been investigated why they were failing and they might very well be intrinsically flaky.

**Comment by BrennanConroy** [comment]
> The dotnet-watch ones are slightly suspect.

I investigated some of them and there were a couple issues, one of which was the process crash on Mac that was fixed by Runtime, and there were some test changes made for another issue.

**Comment by pranavkm** [comment]
Thanks @BrennanConroy !

**Comment by TanayParikh** [comment]
> I investigated some of them and there were a couple issues, one of which was the process crash on Mac that was fixed by Runtime, and there were some test changes made for another issue.

So is it safe to unquarantine, or should I remove them from this PR?

**Review by halter73 — APPROVED** [review]
I can't say for certain that the Kestrel tests won't start failing again since we haven't done anything specifically to fix them, but at least all unquarantied the Kestrel tests are "InMemory". Typically these are more reliable, and when even they're not, they're at least easier to debug than tests that hit the network stack.

**Review by halter73 — APPROVED** [review]
Double approved!

**Comment by TanayParikh** [comment]
Thanks. Merging this in now, if there are any issues let me know and I can do a revert/ update PR to address comments.

**Pull request merged**
