### PR TITLE
Quarantine failing HTTP3 tests

### PR DESCRIPTION
**Pull request by BrennanConroy**
And fix a tiny timeout

https://github.com/dotnet/aspnetcore/issues/42967

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Comment by JamesNK** [comment]
I'd rather these tests were quarantined instead of retried. I merged a bunch of HTTP/3 changes yesterday, and they might have broken something.

TBH I'm not a fan of retrying failing tests by default.

**Comment by dougbu** [comment]
> TBH I'm not a fan of retrying failing tests by default.

Why not❔ I suspect your opinion here is something that didn't come up in @dotnet/aspdoi conversations and we could use your input if the build ops process (that we landed on a few weeks ago) is incorrect in some way. See <https://github.com/dotnet/aspnetcore-internal/pull/4074/files>.

**Comment by JamesNK** [comment]
What prevents retry from hiding a flaky product bug?

**Comment by HaoK** [comment]
There are kusto queries we can use to look for tests that are flaky pass with retries, so the fact that a test is flaky is not lost, so the main benefit is that builds aren't as likely to fail

So if there's a desire to investigate flaky tests to see if there are product bugs, the data is all still there in kusto

**Comment by BrennanConroy** [comment]
I was under the impression that someone was supposed to **write guidance** on how to use the kusto queries to find specific flakyness data. And the original change in https://github.com/dotnet/aspnetcore-internal/pull/4074/files was just the **first step** of "let's start using retry".

**Comment by HaoK** [comment]
Yeah that's on my plate to follow up and add the more details for how to easily see the flaky tests (as well potentially using flaky rates to preemptively disable / reenable tests)

**Comment by dougbu** [comment]
See also <https://github.com/dotnet/arcade/blob/main/Documentation/AzureDevOps/TestReportingQueries.md>, though the closest queries available there display the history of failures rather than statistics such as whether they pass on retry.

In this case,

<details>
<summary>A TestResportingQueries query</summary>

``` kusto
let started = 30d;                    // Timespan value to find test results after. 
let definition = "";    // Optional: The name of the build definition, leave as empty string for all build definitions.
let reason = "";            // Optional: The Azure DevOps build reason value (e.g. PullRequest, BatchedCI, et cetera)
let targetBranch = "";           // Optional: The name of the target branch the test is ran against.
let name = "Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.WebHostTests.Listen_Http3AndSocketsCoexistOnSameEndpoint_AltSvcEnabled_Upgrade";                       // Optional: The name of the test
let jobName = "";                    // Optional: The name of the job
let message = "";  // Optional: Error message to search for
let workItemName = "";               // Optional: Work item name
AzureDevOpsTests
| where RunCompleted >= ago(started)
| where isempty(definition) or BuildDefinitionName has definition
| where isempty(reason) or BuildReason has reason
| where isempty(targetBranch) or Branch has targetBranch
| where isempty(name) or TestName has name
| where isempty(message) or Message has message
| where isempty(workItemName) or WorkItemName has workItemName;
```
</details>

shows only a few failures over the last month.

I prefer to look at (for example)

<details>
<summary>My 30d summary queury</summary>

``` kusto
let ts = 30d;
let definition = "";
let repo = "dotnet/aspnetcore";
let branch = "";
let testName="Listen_Http3AndSocketsCoexistOnSameEndpoint_AltSvcEnabled_Upgrade";
let excludeAlwaysPassing = "";
let subtable = AzureDevOpsTestsSummary
    | where ReportDate >= ago(ts)
    | where isempty(definition) or BuildDefinitionName has definition
    | where isempty(repo) or Repository has repo
    | where isempty(branch) or Branch has branch
    | where isempty(testName) or TestName has testName
    | summarize
        numerator=sum(PassCount),
        denomerator=sum(PassCount) + sum(FailCount) + sum(PassOnRetryCount),
        passOnRetryCount=sum(PassOnRetryCount)
        by TestName, ArgumentHash;
let argumentHashMap = AzureDevOpsTestsSummary
    | where ReportDate >= ago(ts)
    | summarize by ArgumentHash, Arguments;
subtable
| where denomerator > 0 and (isempty(excludeAlwaysPassing) or (todouble(numerator) / todouble(denomerator)) < 1)
| lookup (argumentHashMap) on ArgumentHash
| project
    TestName,
    Arguments,
    MeanPassRate=(todouble(numerator) / todouble(denomerator)),
    PassCount=numerator,
    PassOnRetryCount=passOnRetryCount,
    TotalRunCount=denomerator;
```
</details>

which shows the test has not yet passed on retry.

/cc @ChadNedzlek @missymessa @AlitzelMendez since we might want something like the second query in the <https://github.com/dotnet/arcade/blob/main/Documentation/AzureDevOps/TestReportingQueries.md> doc. That query is closer to the mark for a historical check of tests in our test-configuration.json file.

**Comment by dougbu** [comment]
Note information for longer durations likely remains somewhat off for many tests since the data lacked information about passing tests wasn't included until either June 22 (when dotnet/arcade/#9650 fix was deployed) or June 29 (about when a fix for the big increase in data was deployed -- may have been the 27th).

**Comment by HaoK** [comment]
Filed https://github.com/dotnet/aspnetcore/issues/42998 for tracking work specifically involving follow up / improvements to the new flaky 2.0 test process we use on build ops, feel free to add more things to that issue.  The first thing I'll try to do is see how well the current process is doing

**Pull request merged**
