### PR TITLE
Update npm dev dependencies to support Node.js 18

### LINKED ISSUE #36921: SignalR tests fail against OpenSSL 3.0
### Describe the bug

I am trying to build and run ASP.NET Core tests with OpenSSL 3.0. The test fail with OpenSSL errors.

This is https://github.com/dotnet/aspnetcore sha 277e42f4dcf1ee41c8a1b61a6aaa3e17ef15a1d9.

```
$ eng/build.sh --arch x64 --test
...
...
  $ node ../common/node_modules/typescript/bin/tsc --project ./tsconfig.json --module commonjs --outDir ./dist/cjs
  $ node ../common/node_modules/webpack-cli/bin/cli.js
  /home/tester/aspnetcore/src/SignalR/clients/ts/common/node_modules/loader-runner/lib/LoaderRunner.js:146
  		if(isError) throw e;
  		            ^
  
Error : error : 0308010C:digital envelope routines::unsupported [/home/tester/aspnetcore/src/SignalR/clients/ts/signalr/signalr.npmproj]
      at new Hash (node:internal/crypto/hash:67:19)
      at Object.createHash (node:crypto:130:10)
      at BulkUpdateDecorator.hashFactory (/home/tester/aspnetcore/src/SignalR/clients/ts/common/node_modules/webpack/lib/util/createHash.js:144:18)
      at BulkUpdateDecorator.update (/home/tester/aspnetcore/src/SignalR/clients/ts/common/node_modules/webpack/lib/util/createHash.js:46:50)
      at SourceMapSource.updateHash (/home/tester/aspnetcore/src/SignalR/clients/ts/common/node_modules/webpack-sources/lib/SourceMapSource.js:233:8)
      at NormalModule._initBuildHash (/home/tester/aspnetcore/src/SignalR/clients/ts/common/node_modules/webpack/lib/NormalModule.js:853:17)
      at handleParseResult (/home/tester/aspnetcore/src/SignalR/clients/ts/common/node_modules/webpack/lib/NormalModule.js:918:10)
      at /home/tester/aspnetcore/src/SignalR/clients/ts/common/node_modules/webpack/lib/NormalModule.js:1009:4
      at processResult (/home/tester/aspnetcore/src/SignalR/clients/ts/common/node_modules/webpack/lib/NormalModule.js:732:11)
      at /home/tester/aspnetcore/src/SignalR/clients/ts/common/node_modules/webpack/lib/NormalModule.js:792:5 {
    opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
    library: 'digital envelope routines',
    reason: 'unsupported',
    code: 'ERR_OSSL_EVP_UNSUPPORTED'
  }

```

Is this a bug in nodejs, in an (external) node module or in SignalR itself? this a known issue? Is OpenSSL 3.0 supported?

### To Reproduce

Here's a Dockerfile to reproduce the issue:

```Dockerfile
FROM quay.io/centos/centos:stream9-development

RUN cat /etc/os-release && \
    dnf install -y dnf-plugins-core && \
    dnf repolist --all && \
    dnf config-manager --set-enabled crb && \
    dnf install -y findutils git glibc-langpack-en libicu nodejs

CMD git clone https://github.com/dotnet/aspnetcore && \
    cd aspnetcore && \
    git submodule update --init && \
    ./eng/build.sh --arch x64 --test
```

FWIW, CentOS Stream 9 is the in-development version of RHEL 9. RHEL 9 will have OpenSSL 3.0 as the default version of OpenSSL.

### LINKED ISSUE #41571: The respository does not build with `node` version 18 installed.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The latest ASP.NET Core doesn't build on an entirely newly paved Windows 11 machine, with node version 18.

### Expected Behavior

After following all the instructions in [BuildFromSource.md](https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md), the restore and build work.

### Steps To Reproduce

```
git clone --recursive https://github.com/dotnet/aspnetcore
git checkout main
.\restore.cmd
```

### Exceptions (if any)

```
aspnetcore\eng\targets\Npm.Common.targets(45,5): error : eslint-plugin-jsdoc@37.9.7: The engine "node" is incompatible with this module. Expected v
ersion "^12 || ^14 || ^16 || ^17". Got "18.0.0"
```

### .NET Version

7.0.100-preview.5.22228.6

### Anything else?

ASP.NET Core latest from `main`.

Visual Studio 2022 Preview latest.

`dotnet --info` is lying because I didn't run `.\activate.ps1` yet - the error happens in `.\restore.cmd`.

### PR DESCRIPTION
**Pull request by halter73**
Without updating these dependencies, the build fails with errors like the following with Node.js 18.

```
aspnetcore\eng\targets\Npm.Common.targets(45,5): error : eslint-plugin-jsdoc@37.9.7: The engine "node" is incompatible with this module. Expected version "^12 || ^14 || ^16 || ^17". Got "18.0.0"
aspnetcore\eng\targets\Npm.Common.targets(45,5): error : Found incompatible module.
Time Elapsed 00:00:53.57
Build failed with exit code 1. Check errors above.
```

```
[webpack-cli] Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
```

Fixes #41571
Fixes #36921

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Fixes https://github.com/dotnet/aspnetcore/issues/36921 too?

**Comment by halter73** [comment]
> Fixes #36921 too?

Yes.

**Comment by wtgodbe** [comment]
Might as well update this to use 18.x now too: https://github.com/dotnet/aspnetcore/blob/db4c946395c6bef2e5d65ebd2d2de7d261bdc136/.azure/pipelines/jobs/default-build.yml#L172-L176

**Comment by BrennanConroy** [comment]
Does this still build with node 16? If not we should update the docs: https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md#nodejs-on-windows

**Comment by dougbu** [comment]
> Might as well update this to use 18.x now too: &hellip;

On second thought, 16.15.0 is LTS while 18.2.0 is Current. May want to keep our CI using LTS while (as this PR should do) allowing use of the Current release

**Comment by halter73** [comment]
Node 16 is active LTS. I'm just trying to get it working with node 18 because that's what I have installed locally. Given that the build is passing with default-build.yml node 16, I'd say we're okay there. I'd be extremely surprised if any of these packages required a non-LTS version of node.

Can someone approve this? It's annoying to have to apply this patch myself when I switch branches.

**Review by BrennanConroy — APPROVED** [review]

**Pull request merged**
