### PR TITLE
Default the timezone to UTC if it is not resolved.

### PR DESCRIPTION
**Pull request by pranavkm**
### Description

Browsers may not correctly resolve the machine's timezone in some cases. In the current implementation,
this results in an exception being thrown by .NET Core (WASM). This code defaults the timezone to UTC
when the timezone cannot be resolved.

Fixes https://github.com/dotnet/runtime/issues/44154
Port of https://github.com/dotnet/aspnetcore/pull/27444

### Customer impact

Blazor WASM applications may not start on some browsers that do not correctly resolve timezone information

### Regression
No.

### Risk
We default the app to using UTC timezone which makes it a fairly low risk change. This does not affect browsers / apps where timezones can be correctly resolved which is the majority of our users.

### CODE REVIEW

**Review by captainsafia — APPROVED** [review]

**Comment by mkArtakMSFT** [comment]
@pranavkm, @lewing is this the correct fix? Shouldn't the actual fix be in the runtime instead?

**Review by mkArtakMSFT — APPROVED** [review]
Thanks!

**Review by SteveSandersonMS — APPROVED** [review]

**Review by enisn — APPROVED** [review]

**Comment by wtgodbe** [comment]
@pranavkm can you resolve the conflicts?

**Comment by wtgodbe** [comment]
@mkArtakMSFT is there someone from @dotnet/aspnet-blazor-eng who can work on the conflicts here?

**Comment by pranavkm** [comment]
🆙 📅

**Pull request merged**
