### PR TITLE
Replace calls to get first span to using FirstSpan method

### PR DESCRIPTION
**Pull request by nrkirby**
Summary of the changes (Less than 80 chars)
 - Replace calls to `buffer.First.Span` with `buffer.FirstSpan`

Addresses #18587

### CODE REVIEW

**Comment by anurse** [comment]
```
src/SignalR/common/Shared/Utf8BufferTextReader.cs(72,38): error CS1061: 'ReadOnlySequence<byte>' does not contain a definition for 'FirstSpan' and no accessible extension method 'FirstSpan' accepting a first argument of type 'ReadOnlySequence<byte>' could be found (are you missing a using directive or an assembly reference?)
```

Looks like we might not have the version of the runtime with this property yet?

(I think the in-GitHub error reporting is a little funky since it's repeating the same line numbers, but I expect all the references are failing with the same problem)

**Comment by BrennanConroy** [comment]
I would guess that `FirstSpan` is a new property and isn't present in netstandard2.0 which some projects target.

**Comment by anurse** [comment]
> I would guess that `FirstSpan` is a new property and isn't present in netstandard2.0 which some projects target.

Ah yeah. We'll either have to `#if` that, or skip this optimization in those projects.

Do we know what the performance gain is? Is it worth cross-targeting?

**Comment by halter73** [comment]
> Do we know what the performance gain is? Is it worth cross-targeting?

We should measure, but my feeling is we should back out this change in SignalR. The rest is an easy win.

**Comment by NRKirby** [comment]
@anurse @halter73  shall I remove the change for SignalR?

**Comment by halter73** [comment]
> @anurse @halter73 shall I remove the change for SignalR?

Yes. We can look at cross targeting SignalR later if we think it's worth it.

**Comment by NRKirby** [comment]
> 
> 
> > @anurse @halter73 shall I remove the change for SignalR?
> 
> Yes. We can look at cross targeting SignalR later if we think it's worth it.

I've force pushed a commit that doesn't touch SignalR

**Review by halter73 — APPROVED** [review]

**Comment by halter73** [comment]
Thanks @NRKirby!

**Pull request merged**
