### PR TITLE
Dispost CancellationTokenSource in WebHostExtensions

### LINKED ISSUE #23967: CTS should be disposed
A static analysis tool identified this CancellationTokenSource as a resource that needs to be disposed.
https://github.com/dotnet/aspnetcore/blob/38126419b803c6fd1946645aabff98aa239d2b79/src/Hosting/Hosting/src/WebHostExtensions.cs#L24
It should be as easy as making this method async/await and adding a using statement.

### PR DESCRIPTION
**Pull request by Kahbazi**
Fixes https://github.com/dotnet/aspnetcore/issues/23967

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]

**Comment by Tratcher** [comment]
*sigh* making the method async adds an attribute that gets included in the ref assembly for some reason. That will need to be updated.
https://dev.azure.com/dnceng/public/_build/results?buildId=731426&view=logs&j=efda9e5f-cf98-536e-4181-9b6c13ac35b3&t=de5280bb-c511-517b-1959-798dcf9a84da&l=1729

**Comment by davidfowl** [comment]
This change is fine, that static analysis tool is bogus though. Disposing a CTS is dubious at best.

**Comment by Tratcher** [comment]
> This change is fine, that static analysis tool is bogus though. Disposing a CTS is dubious at best.

This case was legitimate, we need to stop the timer so it doesn't try to cancel something after we succeed.

**Comment by Tratcher** [comment]
Thanks

**Pull request merged**
