### PR TITLE
Update branding to 3.1.8

### PR DESCRIPTION
**Pull request by dougbu**
- build targeting pack to pick up NuGet/Home#8599 fix
    - dotnet/extensions#2750 and #24200 2/2
    - requires follow-up after next official extensions build
- fake the baseline update
    - remainder must be done after the 3.1.7 release
- do not run hostname tests on macOS

!!! Include code merge and baseline generation before merge !!!

### CODE REVIEW

**Review by wtgodbe — CHANGES_REQUESTED** [review]
This needs to be combined with the code merge, on Tuesday

**Comment by dougbu** [comment]
> This needs to be combined with the code merge, on Tuesday

Yup. Also needs the "skip the "Host" AddressRegistrationTests on macOS in release/3.1" fix @halter73 suggested. Working on that to be ready for Tuesday&hellip;

**Comment by wtgodbe** [comment]
@dougbu please update w/ the code merge

**Comment by dougbu** [comment]
This PR is no longer blocked

**Comment by dougbu** [comment]
Just waiting on you @wtgodbe

**Review by Tratcher — APPROVED** [review]

**Review by wtgodbe — APPROVED** [review]

**Pull request merged**
