### PR TITLE
[Hosting] Add {OriginalFormat} to start & stop log state objects

### PR DESCRIPTION
**Pull request by CodeBlanch**
## Description

The `ILogger` extensions and source generator return the [original template logged as the {OriginalFormat} key on the IReadOnlyList<KeyValuePair<string, object>> state](https://github.com/dotnet/runtime/blob/9cafe8f23295b5c7f4718eaaebee6dddc2e7dda6/src/libraries/Microsoft.Extensions.Logging.Abstractions/src/FormattedLogValues.cs#L69) representing the log being written.

AspNetCore has a couple custom log states which do not mirror the `{OriginalFormat}` behavior. By default [OpenTelemetry](https://github.com/open-telemetry/opentelemetry-dotnet) only captures message templates but for these logs it must either have empty template/body (confusing for users) or invoke `ToString` (and incur allocations) to generate a formatted string because no template is available.

In order to make these high value logs play nicely with structured logging and to enable high performance capture I'm proposing we should mirror the `{OriginalFormat}` behavior.

## Changes

* Returns `{OrignalFormat}` as the last key on `HostingRequestStartingLog` & `HostingRequestFinishedLog` state objects
* Tweaks the log messages to be more consistent & deterministic...
   * Start log now writes content type & length after a "-" character
   * Stop log no longer writes out request content type & length

Final templates look like this:

Start:
`Request starting {Protocol} {Method} {Scheme}://{Host}{PathBase}{Path}{QueryString} - {ContentType} {ContentLength} `

Stop:
`Request finished {Protocol} {Method} {Scheme}://{Host}{PathBase}{Path}{QueryString} - {StatusCode} {ContentLength} {ContentType} {ElapsedMilliseconds}ms`

/cc @davidfowl @tarekgh @noahfalk @cijothomas @utpilla @reyang

### CODE REVIEW

**Comment by BrennanConroy** [comment]
If we're going to do this, we should do it for all our custom logging:
https://grep.app/search?q=IReadOnlyList%3CKeyValuePair%3Cstring%2C%20object%3F%3E%3E&filter[repo][0]=dotnet/aspnetcore

**Comment by CodeBlanch** [comment]
@BrennanConroy Thanks for the link! I don't think `{OriginalFormat}` is really needed on scopes. `HttpRequestLog` & `HttpResponseLog` probably need it, but not sure what the template would be exactly. In any case, happy to look into those things if this goes in 👍

**Comment by adityamandaleeka** [comment]
cc @samsp-msft

**Review by halter73 — APPROVED** [review]
Agreed about the scopes. Even for the HttpLogging middleware, I don't think there's a great {OriginalFormat} since it's so dynamic. I think we should just take this as a starting point. If someone else has a good idea for the other logs, we can merge that separately.

**Pull request merged**
