### PR TITLE
Stabilize package versions

### PR DESCRIPTION
**Pull request by dougbu**
- fix some versioning assumptions
- mark all installers as shipping

### CODE REVIEW

**Comment by dougbu** [comment]
See also https://dev.azure.com/dnceng/internal/_build/results?buildId=355665

**Comment by dougbu** [comment]
May still have issues with shared Fx and installer tests. Also need to double-check installer versioning on all platforms. Will deal with both in the morning.

**Comment by dougbu** [comment]
@mmitche and @aspnet/build I'll be away for a few hours. If this passes, please address any review comments and get this in. If it doesn't pass due to ProjectTemplates test failures, first add `continueOnError: true` in [this step of ci.yml](https://github.com/aspnet/AspNetCore/blob/release/3.0/.azure/pipelines/ci.yml#L447-L448).

**Comment by dougbu** [comment]
BTW the internal build created enough artifacts that I'm fairly confident everything is versioned correctly.

**Comment by mmitche** [comment]
Adding continueOnError and merging.

**Pull request merged**
