### PR TITLE
Use ClaimTypes instead of IdentityOptions.ClaimsIdentity in SignInManager

### PR DESCRIPTION
**Pull request by Marusyk**
Used Options.ClaimsIdentity.UserIdClaimType instead of ClaimTypes.NameIdentifier

Addresses #26279

### CODE REVIEW

**Comment by HaoK** [comment]
This needs tests, as I'm pretty sure the reason these aren't configurable is that the external providers are the ones writing out the external cookie, identity options.claims identity is soley for configuring the cookie that identity produces.  Its not meant to try and configure sign in manager.  Sign in manager methods are not really able to be configured like that as its responsible for coordinating between different auth providers.  If no tests fail from this PR, this is likely a test hole :/

**Comment by Marusyk** [comment]
Could you please help me where to start with tests for this?

**Comment by HaoK** [comment]
You can start with something like this https://github.com/dotnet/aspnetcore/blob/master/src/Identity/test/Identity.Test/SignInManagerTest.cs#L530 where you mock the external calls to auth, to verify that the claims are updated properly.  The tricker tests that would show the issue of why I don't think this will work, is that Google and the other OAuth providers are hardcoded 

https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authentication/OAuth/src/OAuthHandler.cs#L246

So this change would basically break the other external sign in flows if you used the option

**Comment by mkArtakMSFT** [comment]
@Marusyk thanks for your PR.
It looks like @HaoK has asked for some more changes. Do you plan to address his feedback? If not, we'd prefer to close this PR to not keep stale PRs around.

**Comment by Marusyk** [comment]
Sorry, I don't have time for this now. No problem if you close it

**Pull request closed without merging**
