### PR TITLE
gRPC JSON transcoding - msbuild includes proto dependencies

### LINKED ISSUE #43376: Grpc.JsonTranscoding requires manually copying annotations.proto and http.proto into projects
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When using AspNetCore.Grpc.JsonTranscoding I have to manually copy Google API annotations.proto and http.proto into my projects so that they can e.g. `import "google/api/annotations.proto";`.

### Describe the solution you'd like

A NuGet package that I can reference that contains the correct version of these files compatible with the version of AspNetCore.Grpc.JsonTranscoding I'm using and will make these files available in the build process so that e.g. `import "google/api/annotations.proto";` works.

### Additional context

An alternative solution might be to contain these files in another existing package e.g. discussed in https://github.com/grpc/grpc/issues/18214. Maybe the landscape has changed and they would reconsider including in Grpc.Tools.

I've made a suggestion as to how this might be achieved in https://github.com/grpc/grpc-dotnet/issues/167#issuecomment-1214192168. Example here: https://github.com/rars/JsonTranscodingDemo
This uses GeneratePathProperty="true" on the PackageReference and then AdditionalImportDirs="$(PkgJsonTranscoding_Protos)\content" on the relevant Protobuf elements that need to import google/api/annotations.proto.

Thanks.

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/aspnetcore/issues/43376

This PR changes the gRPC JSON transcoding package to:
* Include the required proto dependencies in the NuGet package.
* Adds `Microsoft.AspNetCore.Grpc.JsonTranscoding.targets` to the NuGet package. It automatically add proto dependencies to `Grpc.Tooling` protoc compilation.
* Adds a switch `<IncludeHttpRuleProtos>true</IncludeHttpRuleProtos>` to control adding dependencies. Defaults to false.

This change eliminates the biggest obstacle to setting up gRPC JSON transcoding: acquiring the proto files and placing them in the right location. Now a dev just sets `IncludeHttpRuleProtos` to true in the csproj 🥳 🎈 🎉 

@danmoseley The proto files are under Apache license to Google. I think the entries in https://github.com/dotnet/aspnetcore/blob/main/src/Grpc/THIRD-PARTY-NOTICES covers that license already. Is there other reaction to third-party code that needs to happen?

### CODE REVIEW

**Comment by JamesNK** [comment]
@jtattermusch This is what I discussed in our sync. It works well.

**Comment by bemafred** [comment]
@JamesNK awesome!

**Review by BrennanConroy — APPROVED** [review]

**Comment by danmoseley** [comment]
> @danmoseley The proto files are under Apache license to Google. I think the entries in https://github.com/dotnet/aspnetcore/blob/main/src/Grpc/THIRD-PARTY-NOTICES covers that license already. Is there other reaction to third-party code that needs to happen?

Answered offline, but for others -- we can freely use third party code that is permissively licensed (at least Apache/MIT) but they must appear in a TPN and that TPN must end up packaged in the relevant packages/installers. I know there is some debt wrt the installer/shared frameworks (https://github.com/dotnet/runtime/issues/74779) but our individual packages should be inspected to ensure their TPN goes in.

**Comment by zidad** [comment]
This is excellent! Can it be back-ported to 7.0 so we don't have to wait until .NET 8.0? ;p

**Comment by tobiashoeft** [comment]
Any news to downgrade it to .net 6.0 ? 

Or how do i do it in .net 6 try so much ways, but it doesnt work at all

**Comment by zidad** [comment]
@tobiashoeft Yeah I also tried to back port this feature to our own .net 7.0 nuget package but didn't manage to get it working unfortunately.

**Pull request merged**
