### PR TITLE
Add MediaTypeHeaderValue parsing overloads accepting IList of StringSegment

### LINKED ISSUE #2695: MediaTypeHeaderValue accepts a list of strings instead of a list of StringSegments
_From @jkotalik on Monday, August 21, 2017 6:09:48 PM_

With our efforts to remove usages of strings in favor of string segments, it seems incomplete that [MediaTypeHeaderValue.ParseList](https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Net.Http.Headers/MediaTypeHeaderValue.cs#L377-L395) only accepts a list of strings rather than a list of StringSegment. We should consider adding an overload to accept a list of StringSegment too. 

_Copied from original issue: aspnet/HttpAbstractions#920_

### PR DESCRIPTION
**Pull request by david-acker**
## Add MediaTypeHeaderValue parsing overloads accepting IList of StringSegment

Adds `ParseList`, `ParseStrictList`, `TryParseList`, and `TryParseStrictList` overloads which accept `IList<StringSegment>`. 

Fixes #2695

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
Hey @david-acker this will need to go through the [API review process](https://github.com/dotnet/aspnetcore/blob/main/docs/APIReviewProcess.md) before being accepted since it's updating public API.

Can you please add a comment in the issue https://github.com/dotnet/aspnetcore/issues/2695 with your proposed API following the format in the [API Proposal template](https://github.com/dotnet/aspnetcore/issues/new?assignees=&labels=api-suggestion&template=30_api_proposal.md&title=)? That will get it ready for going through the API review.

**Comment by david-acker** [comment]
@adityamandaleeka Thanks for the heads up! I've added a comment to #2695 with the proposed API.

**Comment by david-acker** [comment]
Marking as draft while this goes through API review.

**Comment by adityamandaleeka** [comment]
Thanks @david-acker! We'll review it and get back to you.

**Comment by david-acker** [comment]
Closing for now as the details regarding the new APIs (and if/where these new APIs would be used) are still being worked out.

**Pull request closed without merging**
