### PR TITLE
Update branding to 7.0.0-rc2

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Comment by dougbu** [comment]
Holding until Monday&hellip;

**Review by wtgodbe — APPROVED** [review]

**Review by venkataprasadm — APPROVED** [review]

**Comment by dougbu** [comment]
Closing in favour of #43307

**Comment by dougbu** [comment]
(Will need to do this in release/7.0 once that branch exists however.)

**Comment by dougbu** [comment]
Reopening in hopes retargeting won't require a CI rerun

**Comment by dougbu** [comment]
Needs #43321 before this will pass. Will rerun validation once that's in.

**Pull request merged**
