### PR TITLE
Avoid failed authN log when the endpoint has IAllowAnonymous metadata

### LINKED ISSUE #43042: MapHealthChecks().AllowAnonymous() not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Health check does not work when you use `OpenIdConnect` for authentication and authorization. The health check endpoint returns the expected result. But OpenIdConnect logs the request as an unauthorized one.
Here is log: `OpenIdConnect was not authenticated. Failure message: Not authenticated`.

### Expected Behavior

`OpenIdConnect` should not treat the request as unauthorized one.

### Steps To Reproduce

- Create new .net 6 web application and use the code added below.
- Run the application
- From your browser go to `{ApplicationUrl}:{Port}/live`
- Check console output

**Program.cs**
```
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Diagnostics.HealthChecks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Authorization;
using Microsoft.Identity.Web;
using Microsoft.Identity.Web.UI;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddRazorPages();


// Add services to the container.
builder.Services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme)
    .AddMicrosoftIdentityWebApp(builder.Configuration.GetSection("AzureAd"));


builder.Services.AddControllersWithViews(options =>
{
    var policy = new AuthorizationPolicyBuilder()
        .RequireAuthenticatedUser()
        .RequireRole("user")
        .Build();
    options.Filters.Add(new AuthorizeFilter(policy));
    options.Filters.Add(new AutoValidateAntiforgeryTokenAttribute());
});

builder.Services.AddRazorPages()
    .AddMicrosoftIdentityUI();
builder.Services.AddHealthChecks();

var app = builder.Build();

app.UseHttpLogging();

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

app.UseAuthentication();
app.UseAuthorization();
app.MapHealthChecks("/live", new HealthCheckOptions { Predicate = r => r.Tags.Contains("live") }).AllowAnonymous();
app.MapHealthChecks("/ready", new HealthCheckOptions { Predicate = r => r.Tags.Contains("ready") }).AllowAnonymous();
app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");
app.MapRazorPages();

app.Run();
```

**appsettings.json**
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning",
      "Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler": "Information"
    }
  },
  "AllowedHosts": "*",
  "AzureAd": {
  }
}
```

**Application.csproj**
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.7" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="6.0.7" />
		<PackageReference Include="Microsoft.AspNetCore.DataProtection.StackExchangeRedis" Version="6.0.7" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="6.0.7" />
		<PackageReference Include="Microsoft.Identity.Web.UI" Version="1.25.1" />
	</ItemGroup>

</Project>
```

### Exceptions (if any)

_No response_

### .NET Version

6.0.201

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Kahbazi**
Fixes https://github.com/dotnet/aspnetcore/issues/43042

### CODE REVIEW

**Review by abuzaforfagun — APPROVED** [review]

**Review by halter73 — APPROVED** [review]

**Comment by Tratcher** [comment]
@Kahbazi I tracked down the reason for the original log and I think we can prevent it without this new anonymous check.

The following should be changed from Fail to NoResult.
https://github.com/dotnet/aspnetcore/blob/9eb6ad444271be42c320b35ccc5218de44857642/src/Security/Authentication/Core/src/RemoteAuthenticationHandler.cs#L202

Can you try that?

**Review by Tratcher — CHANGES_REQUESTED** [review]
See my prior comment.

**Comment by HaoK** [comment]
So isn't this a subtle breaking change/behavior change?  Users are able to check the authenticate result directly, and now we would be returning NoResult instead of Fail... Arguably there's no difference, but it still seems a bit risky

**Comment by Tratcher** [comment]
It is a minor behavior change, but I think it's a beneficial one. Auth didn't fail, there's just no user available. Also, I would not expect users to be directly saying Authenticate(OIDC), it would be Authenticate(Cookies) to get the current user and that doesn't go down this code path.

**Comment by davidfowl** [comment]
I agree with @Tratcher on the fix, this code shouldn't be checking for allow anonymous.

**Comment by davidfowl** [comment]
I marked it as a breaking change. @Tratcher can you write up the breaking change after this PR gets merged?

**Review by Tratcher — APPROVED** [review]

**Comment by Tratcher** [comment]
Done: https://github.com/aspnet/Announcements/issues/491

**Pull request merged**
