### PR TITLE
Merge release/2.1 into release/2.2

### PR DESCRIPTION
**Pull request by jkotalik**
Should be the same change for release/2.2

### CODE REVIEW

**Comment by jkotalik** [comment]
@anurse can you merge this?

**Comment by anurse** [comment]
Can you cite the original 2.1 PR and give an review approval (I actually do need that to merge on these branches ;))?

**Comment by jkotalik** [comment]
I can't review my own PR... here is my original PR: https://github.com/aspnet/AspNetCore/pull/11616

**Comment by jkotalik** [comment]
I didn't actually verify this on aspnetci yet. If you'd prefer I do that, I can, but I believe it should be exactly the same change.

**Comment by anurse** [comment]
> I can't review my own PR

Lol. Ok, I can override it.

**Comment by anurse** [comment]
Merging as this is infrastructure only and the change was previously approved for 2.1

**Pull request merged**
