### PR TITLE
Fix: InputRadioGroup not registering initial click in some circumstances

### LINKED ISSUE #31610: InputRadioGroup does not support state preservation for child content
### Describe the bug

A `InputRadioGroup` will _always_ re-render all children and does not support state preservation at all.
The consequence of this, is that focus within a InputRadioGroup will not be retained.

### To Reproduce

https://gist.github.com/Sebazzz/dc33bb9e984774407aa9b9644f356cca

Run and click the button. You will see that the child components of the radio button will show a new date, indicating a re-render happens.

### Further technical details
- ASP.NET Core version: 5.0

This happens because in `OnParametersSet` always a new `_context` is initialized:

https://github.com/dotnet/aspnetcore/blob/368fa1df576be483a8f1e77ecd890ff5d08fef1b/src/Components/Web/src/Forms/InputRadioGroup.cs#L32-L39

In the rendering procedure, this is used as a key value. Always being a new instance, the children will always be deleted and new children created:

https://github.com/dotnet/aspnetcore/blob/368fa1df576be483a8f1e77ecd890ff5d08fef1b/src/Components/Web/src/Forms/InputRadioGroup.cs#L42-L47

### Possible fix

`_context` should be initialized once in the `OnInitialized` *or* only be changed if the groupname or other parameters change.

### LINKED ISSUE #39145: InputRadioGroup not registering initial click in some circumstances
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I have made an edit to an input field, if I click a button afterward, the button click does not fire.
 
This seems similar to #30875 but the solution is not the same. In the simple demo, wrapping the string in a model does seem to resolve the issue. However, in my production issue, I have a radio button that cannot be bound directly to the model. It needs to be translated first. It exhibits the same behavior, where clicking on an option the first time does not select it if I have first made an edit to an input field. The second click works.

### Expected Behavior

When I edit a text file and then click (using the mouse) on the next field or on a button, that click should be registered.

### Steps To Reproduce

Here are the repo steps:
1.	Go to [https://blazorformsample.azurewebsites.net/](https://blazorformsample.azurewebsites.net/)
2.	Click the submit button. Notice the counter increments.
3.	Modify the text in the text field.
4.	Click (don’t tab or hit enter) on the Submit button. Nothing happens.
5.	Click the button again and it fires.

Here is the sample repo: [https://github.com/TimCorey/BlazorFormSample](https://github.com/TimCorey/BlazorFormSample)

### Exceptions (if any)

_No response_

### .NET Version

6.0.101

### Anything else?

I have reproduced this on Mac and Windows 10, on FireFox, Chrome, and Edge. Some people seem to not experience it at first, but then will encounter it after a few attempts.

Here is a demo showing off the bug:

.

### PR DESCRIPTION
**Pull request by MariovanZeist**
# Fixes InputRadioGroup not registering initial click

I have created a simple repo to show the issue: https://github.com/MariovanZeist/InputRadioGroupDoubleClick

The problem was the use of an ``InputContext`` as a key for the renderer.
As this Context was recreated every time the ``InputRadioGroup`` was rendered, all its Content was also recreated.

When you have an ``InputText`` for example, and you would edit the text and without pressing enter or tab out of the input would click on a ``InputRadio`` element, first the ``OnChange`` of the ``InputText`` would fire, forcing a rerender of the ``InputRadioGroup`` which in turn would rebuild its content, and would lose the ``click`` event (As the HTML that was clicked on is now gone)

## Description

The solution was to change the way ``InputContext`` was created, but also honor #24762 where the issue was introduced.

The biggest hurdle was to fix the Issue with no breaking changes, 
Most of the changes are to internal classes so won't affect other developers.
The only change that could be considered breaking is the addition of the IDisposable interface to a ``InputRadio`` component, but I could not find a solution without it.

2 e2e tests have been added

Fixes #31610

Fixes: https://github.com/dotnet/aspnetcore/issues/39145#issuecomment-999744378

### CODE REVIEW

**Comment by MariovanZeist** [comment]
The main challenge with this PR was the fact that if you use a primitive value for ``TValue`` Due to how blazor detects changes in ``ChangeDetection``  
https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Components/Components/src/ChangeDetection.cs#L39-L45

An ``InputRadio`` component would never rerender as its parameters would not change (When using an enum as a ``TValue``, the InputRadio would rerender), creating an issue that #24762 was created to fix.

The solution here was to maintain a list of actions to call when an ``InputRadioGroup`` was rerendered, so it could also rerender its children.

**Comment by mkArtakMSFT** [comment]
Thanks for your PR, @MariovanZeist.
@SteveSandersonMS could you please review this when you're back? Thanks!

**Comment by MariovanZeist** [comment]
@SteveSandersonMS The issue https://github.com/dotnet/aspnetcore/issues/39145 has 2 different (Nonrelated issues)
That's why I am referring to the comment in that Issue which states a different issue than the one in the Title, https://github.com/dotnet/aspnetcore/issues/39145#issuecomment-999744378
Which describes the problem I am fixing here.
Sorry for the confusion.

**Comment by MariovanZeist** [comment]
Fixed in [@40148](https://github.com/dotnet/aspnetcore/pull/40148)

**Pull request closed without merging**
