### PR TITLE
Use Random.Shared property

### PR DESCRIPTION
**Pull request by martincostello**
**PR Title**

Use the new `Random.Shared` where appropriate.

**PR Description**

Use the new .NET 6 `Random.Shared` static property (dotnet/runtime#50297) where possible in the repo.

Almost all of the usages where in tests, samples or benchmarks. [`KeyRingProvider`](https://github.com/dotnet/aspnetcore/blob/2afcac2d152c0faca2f0f43407e71820408dc614/src/DataProtection/DataProtection/src/KeyManagement/KeyRingProvider.cs#L262) was the only product class usage I could find.

The only usages left are in the download files repo task:

https://github.com/dotnet/aspnetcore/blob/2afcac2d152c0faca2f0f43407e71820408dc614/eng/tools/RepoTasks/DownloadFile.cs#L99

and in the Razor tests derived from this code:

https://github.com/dotnet/aspnetcore/blob/2afcac2d152c0faca2f0f43407e71820408dc614/src/Razor/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/FunctionsBlock.cshtml#L5-L10

### CODE REVIEW

**Comment by martincostello** [comment]
Looks like running `./eng/build.cmd` locally didn't find some of the project templates not compiling with the change. Will fix.

**Comment by halter73** [comment]
Is there ever a reason not to use the shared property if we are targeting .NET 6 or later?

**Review by halter73 — APPROVED** [review]
Unless someone tells me a reason otherwise, this should probably be the new standard pattern whenever we don't need the ability to specify the seed.

**Comment by martincostello** [comment]
> Is there ever a reason not to use the shared property if we are targeting .NET 6 or later?

As far as I'm aware the only reasons would be if you need a specific seed for some reason, or if you wanted to inject an instance so you could use a derived type that changed the behaviour (such as a test implementation that is actually deterministic).

**Comment by Tratcher** [comment]
oooh, it's even thread-safe.

**Review by Tratcher — APPROVED** [review]

**Pull request merged**
