### PR TITLE
Mark ReactTemplate_IndividualAuth_NetCore_LocalDb flaky

### PR DESCRIPTION
**Pull request by Tratcher**
https://github.com/aspnet/AspNetCore-Internal/issues/2348

This has been failing on all of my PRs today and looks like a regression in @halter73's change yesterday.

### CODE REVIEW

**Review by natemcmaster — APPROVED** [review]

**Review by halter73 — APPROVED** [review]

**Comment by halter73** [comment]
@anurse We might want to reprioritize https://github.com/aspnet/AspNetCore-Internal/issues/2348 since it looks like the test has gotten a lot more flaky since I merged https://github.com/aspnet/AspNetCore/pull/10165.

If we cannot figure out the root cause, we might want to look at reverting my PR is it isn't reverted already be then for perf reasons.

**Comment by Tratcher** [comment]
@halter73 now AngularTemplate_IndividualAuth_Works is failing with the same error. Time to revert.

**Comment by ryanbrandenburg** [comment]
Oh is THAT what causes the 
```
[Severe] https://localhost:14615/Identity/lib/bootstrap/dist/js/bootstrap.bundle.js - Failed to load resource: net::ERR_CONNECTION_CLOSED
```
stuff? I was operating under the assumption that it was something wrong with the certificates.

**Comment by anurse** [comment]
@halter73 Sounds good, thanks for volunteering :).

**Pull request closed without merging**
