### PR TITLE
Identity stores tests fixes

### LINKED ISSUE #39050: Identity Specification Tests Issues
## Failing Test(s)
For target `netcoreapp3.1` any test checking logging fails due to the removal of logging user IDs in [this commit](
https://github.com/dotnet/aspnetcore/commit/71fef28e47db385efee14f80135391cf9ab516b6#diff-510a59e10134ab112b6061fbd305108dfb7ebf37210bb15edfebb503b61d8b83).

These are the tests that fail:

-    IdentitySpecificationTestBase.AddUserToRoleFailsIfAlreadyInRole
-   IdentitySpecificationTestBase.CanGetRolesForUser
-    IdentitySpecificationTestBase.CanQueryableRoles
-    IdentitySpecificationTestBase.RemoveUserNotInRoleFails
-    UserManagerSpecificationTestBase.AddDupeLoginFails
-    UserManagerSpecificationTestBase.AddPasswordFailsIfAlreadyHave
-    UserManagerSpecificationTestBase.CanChainUserValidators
-    UserManagerSpecificationTestBase.CanEnableLockoutManuallyAndLockout
-    UserManagerSpecificationTestBase.CanFindUsersViaUserQuerable
-    UserManagerSpecificationTestBase.CanGenerateAndVerifyUserTokenWithStaticTokenProvider
-    UserManagerSpecificationTestBase.CanUpdatePasswordUsingHasher
-    UserManagerSpecificationTestBase.CanVerifyPhoneNumber
-    UserManagerSpecificationTestBase.ChangeEmailFailsWithEmail
-    UserManagerSpecificationTestBase.ChangeEmailFailsWithWrongToken
-    UserManagerSpecificationTestBase.ChangePasswordFallsIfPasswordWrong
-    UserManagerSpecificationTestBase.ChangePhoneNumberFailsWithWrongToken
-    UserManagerSpecificationTestBase.CheckSetUserNameValidatesUser
-    UserManagerSpecificationTestBase.ConfirmEmailWithStaticTokenFailsWithWrongToken
-    UserManagerSpecificationTestBase.ConfirmTokenFailsAfterPasswordChange
-    UserManagerSpecificationTestBase.EmailFactorFailsAfterSecurityStampChangeTest
-    UserManagerSpecificationTestBase.LockoutFailsIfNotEnabled
-    UserManagerSpecificationTestBase.PasswordValidatorCanBlockAddPassword
-    UserManagerSpecificationTestBase.PasswordValidatorCanBlockChangePassword
-    UserManagerSpecificationTestBase.PasswordValidatorCanBlockCreateUser
-    UserManagerSpecificationTestBase.PasswordValidatorCanBlockResetPasswordWithStaticTokenProvider
-    UserManagerSpecificationTestBase.PhoneFactorFailsAfterSecurityStampChangeTest
-    UserManagerSpecificationTestBase.ResetPasswordWithStaticTokenProviderFailsWithWrongToken
-    UserManagerSpecificationTestBase.SingleFailureLockout
-    UserManagerSpecificationTestBase.TwoFailureLockout
-    UserManagerSpecificationTestBase.UserValidatorCanBlockCreate
-    UserManagerSpecificationTestBase.UserValidatorCanBlockUpdate
-    UserManagerSpecificationTestBase.VerifyTokenFromWrongTokenProviderFails
-    UserManagerSpecificationTestBase.VerifyWithWrongSmsTokenFails

## Error Message

Example: Assert.Contains() Failure
Not found: User d27a6851-ffac-40e6-82ef-21bae2332e2d is already in role addUserDupeTest968bcd82-58e2-429d-a40e-c45096ac09d0.
In value:  List<String> ["User is already in role addUserDupeTest968bcd82-58"...]

## Additional Test Issues

`CanQueryableRoles` in `IdentitySpecificationTestBase` is not virtual so for some `IQueryable` implementations (Comsos) that don't implement all expressions in the base test, I can't override it to adjust the test. In contrast `CanFindUsersViaUserQuerable` on `UserManagerSpecificationTestBase` is virtual and I can work around this issue via an override.

~~`CanGetRolesForUser` in `IdentitySpecificationTestBase` is also failing. Issue seems to be that `UserManager` will add the role to the user in normalized form, but the test retrieves the `RoleId` un-normalized for the Assert comparison:~~
```cs
removed```

Thanks!

### PR DESCRIPTION
**Pull request by AndrewTriesToCode**
# Identity stores tests fixes

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

Minor fixes to Identity store specification tests.

## Description
- Fixes typo in test comments and variables names
- Fixes Tests for Queryable functionality which break with some `IQueryable` implementations (i.e. Cosmos)
- Make `CanQueryableRoles` virtual to match its queryable user counterpart test

Fixes #39050

### CODE REVIEW

**Comment by AndrewTriesToCode** [comment]
If possible it would be great to get this backported to 3.1, 5.0 and 6.0 as well.

**Comment by HaoK** [comment]
fyi @AndrewTriesToCode looks like you have to fix some other derived mispellings for the build to pass

**Comment by AndrewTriesToCode** [comment]
Thanks @HaoK, updated and seems to be passing now.

**Review by HaoK — APPROVED** [review]

**Comment by HaoK** [comment]
Thanks for the PR @AndrewTriesToCode this won't likely meet the servicing bar for backport, but we'll get this in for 7.0

**Comment by AndrewTriesToCode** [comment]
Thanks I appreciate it.

**Pull request merged**
