### PR TITLE
Turn off SDL validation

### PR DESCRIPTION
**Pull request by pranavkm**
Based on the discussion here: https://github.com/dotnet/arcade/issues/5219
Re-enabling tracked by https://github.com/dotnet/aspnetcore/issues/20690

### CODE REVIEW

**Review by JohnTortugo — APPROVED** [review]

**Review by Pilchie — APPROVED** [review]
Can we make sure an issue is filed to re-enable this or move it to another parallel pipeline?

**Comment by pranavkm** [comment]
@Pilchie already filed an issue to re-enable it: https://github.com/dotnet/aspnetcore/issues/20690

**Review by sunandabalu — APPROVED** [review]

**Comment by wtgodbe** [comment]
@pranavkm can you backport this to 3.1 as well?

**Comment by pranavkm** [comment]
Sure @wtgodbe. Could you use your magic build-admin powers to merge this in? We're investigating the Ubuntu failures, but it clearly could not be responsible for this failure

**Pull request merged**
