### PR TITLE
[Blazor][Desktop] Fixes nullable annotations on the public API baselines

### PR DESCRIPTION
**Pull request by javiercn**

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
Please add src/Components/WebView/WebView/src/PublicAPI.Shipped.txt fix. Crossing my fingers the files don't need to be completely recreated to include nullable annotations

**Review by pranavkm — APPROVED** [review]

**Comment by javiercn** [comment]
@dougbu Is the codecheck failure issue here?

**Comment by dougbu** [comment]
> @dougbu Is the codecheck failure issue here?

Changing PublicApi.Shipped.txt files requires admin approval. Once you've added src/Components/WebView/WebView/src/PublicAPI.Shipped.txt to the PR and we confirm there are no other problems, I'll merge

**Comment by javiercn** [comment]
Done, I'm done for the day, so if there are issues I'll look at them on Monday

**Comment by dougbu** [comment]
Thanks @javiercn❕

**Pull request merged**
