### PR TITLE
[AOT] Remove AOT warning suppressions

### PR DESCRIPTION
**Pull request by amcasey**
...introduced in #45604 now that https://github.com/dotnet/runtime/pull/79425 is available.

### CODE REVIEW

**Comment by JamesNK** [comment]
Some more:
* https://github.com/dotnet/aspnetcore/blob/dfab67748084f120472e634a975b3c45150f608b/src/DataProtection/Extensions/src/DataProtectionProvider.cs#L149
* https://github.com/dotnet/aspnetcore/blob/dfab67748084f120472e634a975b3c45150f608b/src/DefaultBuilder/src/WebApplicationBuilder.cs#L36

**Comment by amcasey** [comment]
Oops, forgot I had a solution filter open.

**Review by eerhardt — APPROVED** [review]
LGTM. Thanks!

**Review by JamesNK — APPROVED** [review]

**Pull request merged**
