### PR TITLE
Mark API from 7 as shipped

### PR DESCRIPTION
**Pull request by wtgodbe**
Took all of the .shipped files from https://github.com/dotnet/aspnetcore/pull/46042, built the repo, and fixed errors one-by-one.

### CODE REVIEW

**Comment by dougbu** [comment]
> Took all of the .shipped files from https://github.com/dotnet/aspnetcore/pull/46042, built the repo, and fixed errors one-by-one.

I checked `git diff wtgodbe:wtgodbe/Api7..wtgodbe:wtgodbe/Api8 -- **/PublicApi.Shipped.txt` and got no output. Am I correct you haven't (yet) had to update the Shipped files for nullability reasons❔

But, from the CI errors, it looks like some symbols are missing from the Unshipped files still&hellip;

I also get the same lack of output from `... -- **/PublicApi.Unshipped.txt`. Since the wtgodbe/Api7 Unshipped files are empty (I checked), are the right files in wtgodbe/Api8❔

**Comment by wtgodbe** [comment]
> I checked git diff wtgodbe:wtgodbe/Api7..wtgodbe:wtgodbe/Api8 -- **/PublicApi.Shipped.txt and got no output. Am I correct you haven't (yet) had to update the Shipped files for nullability reasons❔

Correct, I didn't encounter any instances where I'd have to do this. Which makes sense, if those nullability changes should never have been in Unshipped in the first place, this PR wouldn't have to touch them (if they're already in Shipped, they'll stay there)

> But, from the CI errors, it looks like some symbols are missing from the Unshipped files still…

Argh, yep, something's wrong. Weird, it passed for me locally. Will take a look.

> I also get the same lack of output from ... -- **/PublicApi.Unshipped.txt. Since the wtgodbe/Api7 Unshipped files are empty (I checked), are the right files in wtgodbe/Api8❔

Something's up there, there's definitely differences - e.g.:

https://github.com/wtgodbe/aspnetcore/blob/wtgodbe/Api7/src/Components/Components/src/PublicAPI.Unshipped.txt
https://github.com/wtgodbe/aspnetcore/blob/wtgodbe/Api8/src/Components/Components/src/PublicAPI.Unshipped.txt

**Review by mkArtakMSFT — APPROVED** [review]
I've spot-checked some of the changes. Thanks @wtgodbe !

**Review by dougbu — APPROVED** [review]
Checked a few things locally:
1. Very few (7) Shipped files differ from what's now in release/7.0. The differences relate to
  1. Renaming for the `net7.0` -> `net8.0` transition
  2. Slight ordering changes in renamed files
  3. Newly-nullable public surface
  4. The new src/Servers/Kestrel/Transport.NamedPipes/src/ project
2. 24 Unshipped files contain various changes. Most seem to be removals or small additions. That's fine as long as the CI agrees.

**Comment by wtgodbe** [comment]
Only failure is the expected one in Code Check - merging

**Pull request merged**
