### PR TITLE
Backport selenium fix dotnet/aspnetcore#30576 to 5.0

### PR DESCRIPTION
**Pull request by TanayParikh**
Original PR: https://github.com/dotnet/aspnetcore/pull/30576

### CODE REVIEW

**Comment by TanayParikh** [comment]
@JunTaoLuo / @dougbu can this be merged?

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
> can this be merged?

Definitely❕

**Comment by dougbu** [comment]
My bad. Should have reminded you to wait 'til branch was open for this. @wtgodbe will this 'release/5.0' change cause CQB issues❔

**Comment by wtgodbe** [comment]
Thanks for catching it quickly, just need to cancel the build to avoid any fallout (which I just did: https://dev.azure.com/dnceng/internal/_build/results?buildId=1023916&view=results)

**Pull request merged**
