### PR TITLE
Use VS from env if specified

### PR DESCRIPTION
**Pull request by Pilchie**

### CODE REVIEW

**Review by dougbu — COMMENTED** [review]
When would `%VSINSTALLDIR%` be defined and what problem does using it solve❔

**Comment by Pilchie** [comment]
> When would %VSINSTALLDIR% be defined

If you run startvs from a VS command/Powershell prompt

> what problem does using it solve

Makes startvs start the VS you want it to if you have multiple installed.

**Review by dougbu — APPROVED** [review]
Sounds good

**Comment by Pilchie** [comment]
Merging since this change isn't used in the build, and the test that failed is quarantined in `release/5.0-rc2`

**Comment by sumuis** [comment]
Хорошо.

**Pull request merged**
