### PR TITLE
Change HubConnection UriEndpount

### PR DESCRIPTION
**Pull request by mikaelm12**
Needs tests still.
Also need to find a good way to message to users who don't use the `UpdateUrl` method properly.

### CODE REVIEW

**Comment by mikaelm12** [comment]
I don't see a good way to do this without messing up the layering. We need a way to expose a way to edit the url knowing that it would noop/throw in non http scenarios.

**Comment by mikaelm12** [comment]
Any ideas on this one? How do we allow for an easy way to change the url, while also not tying the HubConnection to the Http scenario to tightly?

**Comment by rynowak** [comment]
> Any ideas on this one? How do we allow for an easy way to change the url, while also not tying the HubConnection to the Http scenario to tightly?

I have no context, but URIs don't have to be limited to HTTP

**Comment by anurse** [comment]
Closing for now.

**Pull request closed without merging**
