### PR TITLE
Port "Lock around Http3Stream data frame processing" to `main`

### PR DESCRIPTION
**Pull request by MackinnonBuck**
Cherry-picks some of the changes from https://github.com/dotnet/aspnetcore/pull/56693 into `main`.

### CODE REVIEW

**Comment by MackinnonBuck** [comment]
cc @BrennanConroy

**Review by BrennanConroy — APPROVED** [review]

**Comment by BrennanConroy** [comment]
😆  you don't need to rerun the quarantined runs unless you suspect an issue caused by the PR.

**Comment by MackinnonBuck** [comment]
> 😆 you don't need to rerun the quarantined runs unless you suspect an issue caused by the PR.

You're right, I autopiloted and didn't realize it was only the quarantined check failing. I'll merge this 😄

**Pull request merged**
