### PR TITLE
Remove some unused code from installers

### PR DESCRIPTION
**Pull request by HaoK**
Remove unreferenced and unused code from installers

### CODE REVIEW

**Comment by sebastienros** [comment]
That's a lot of code. Did we actually remove a feature that makes it unused?

**Comment by HaoK** [comment]
Nope, I believe this was just relics from IIS codebase that were copied over and just unused, I couldn't find any references to any of these directories being built or used, and nothing seems to break...

**Comment by HaoK** [comment]
Maybe they were used in ancm v1?

**Review by wtgodbe — APPROVED** [review]
I don't know of anywhere this is used - if it's really needed, we still have it in the servicing branches

**Review by adityamandaleeka — APPROVED** [review]
I see deleted code, I approve.

**Pull request merged**
