### PR TITLE
Cleanup Blazor standalone publish output

### PR DESCRIPTION
**Pull request by pranavkm**
* Remove stray content from Blazor's publish output.
* Introduce BlazorPrunePublishOutput as a way for users to opt-out of this.

Fixes https://github.com/dotnet/aspnetcore/issues/17018

### CODE REVIEW

**Comment by pranavkm** [comment]
Same PR as https://github.com/dotnet/aspnetcore/pull/20334, just a different base branch

**Review by javiercn — APPROVED** [review]

**Review by SteveSandersonMS — APPROVED** [review]
This is great, and I'd be totally happy with shipping this as-is. But one question! :)

Do you think it's definitely desirable to have the `wwwroot` subfolder within the publish output? Is it worth considering rewriting the target paths to strip off the `wwwroot` prefix? As well as being easier to understand, it means we could simplify the web.config file to stop rewriting incoming requests to prefix `wwwroot` into all the URLs.

On the other hand, I guess this might complicate other MSBuild stuff if there are other targets that try to dynamically write stuff into `wwwroot` after the `_BlazorCleanup` target runs independently of this logic, or if they produce output in some other itemgroup besides `<ResolvedFileToPublish>`. Don't know if there is anything that does that.

**Comment by javiercn** [comment]
> On the other hand, I guess this might complicate other MSBuild stuff if there are other targets that try to dynamically write stuff into `wwwroot` after the `_BlazorCleanup` target runs independently of this logic, or if they produce output in some other itemgroup besides `<ResolvedFileToPublish>`. Don't know if there is anything that does that.

If we were to do something like that lets just please make sure that it is done at the very end of the pipeline (if we can enforce that somehow) to prevent it with interfering with the existing MSBuild pipeline, which as you mentioned already is quite complicated.

**Comment by pranavkm** [comment]
Let me give the cleanup a try in preview5. I'll leave the issue open for tracking.

**Pull request merged**
