### PR TITLE
[release/3.1] Update hosted (AzDO) and BYOC (dnceng) agents used in our builds

### PR DESCRIPTION
**Pull request by dougbu**
- dotnet/aspnetcore-internal#3540
- nit: Consistently use in / notin with Build.Reason
  - YAML was inconsistent and this aligns w/ the Arcade code

### CODE REVIEW

**Comment by dougbu** [comment]
@Pilchie the most important part of this (given the March 23 deadline) is the macOS switch. Any objection to the rest (nits and using faster Windows Server agents) in a `tell-mode` fix?

**Comment by dougbu** [comment]
**NO-MERGE** because the branches aren't open

**Review by JunTaoLuo — APPROVED** [review]

**Review by Pilchie — APPROVED** [review]
LGTM :shipit:

**Comment by dougbu** [comment]
Redid the work to avoid later conflicts; actual changes are the same as before but based on a later `git merge-base` commit because 'release/2.1' is no longer relevant here.

**Pull request merged**
