### PR TITLE
Add missing OffsetX and OffsetY events to MouseEventArgs.

### PR DESCRIPTION
**Pull request by Valks**
Added missing ```OffsetX``` and ```OffsetY``` values to the ```MouseEventArgs```

Addresses #15440

Notes:
  - (WIP) I haven't been able to build the artifacts (build itself passes) locally so I'm not sure if this is all the changes required.
  - Couldn't find any tests to append. If there are tests for events some advise would be appreciated.

### CODE REVIEW

**Comment by Valks** [comment]
Thanks for the feedback.

I've taken a look using the ```BasicTestApp``` and it's working as expected.

Taking a look at the E2E tests they all seem to check if the event triggers but there's no tests to check the output values.

**Comment by captainsafia** [comment]
> Taking a look at the E2E tests they all seem to check if the event triggers but there's no tests to check the output values.

I think it is fine if we don't add test cases for this particular scenario if we don't already validate individual keys. Let me know if you think otherwise @dotnet/aspnet-blazor-eng.

**Comment by captainsafia** [comment]
Refing this to https://github.com/dotnet/aspnetcore/issues/8241.

**Comment by SteveSandersonMS** [comment]
Looks totally reasonable to me. Thanks, @Valks!

**Comment by captainsafia** [comment]
@Valks Since this PR contained a code change that modified the public interface, it had to undergo an API review. Luckily, it has passed API review and is approved for merge.

There's a few things to do before merging:

1. There's now a merge conflict in the blazor.server.js file. To resolve this build issue, you will need to rebase or merge against master, then run:

```
$ cd src/Components/Web.JS
$ npm run build
```

To regenerate the built JavaScript asset with both your changes and the changes that have been pushed into master.

Also, it looks like the build failure in this PR is due to a flaky test. Pushing anew commit with the changes from #2 should resolve this.

Let me know if you have follow-up questions.

**Comment by Valks** [comment]
Hi @captainsafia, thanks for all your help.

Just wanting to understand should I create a commit adding kvm.cmd from #2? If I've misunderstood please elaborate because it feels a little strange adding code from a 6-year-old pull request.

**Comment by captainsafia** [comment]
> Just wanting to understand should I create a commit adding kvm.cmd from #2? If I've misunderstood please elaborate because it feels a little strange adding code from a 6-year-old pull request.

Typo on my part. That was meant to say #1. The merge commit should've triggered a rebuild. This is ready for merging now. Thanks for making the change and addressing the follow-ups.

**Review by captainsafia — APPROVED** [review]

**Comment by Xaeco** [comment]
Hi everyone, firstly I'd like to say a big **THANK YOU** for the great work on Blazor and DotNet Core, I'm loving it!
Second, what preview/nightly builds do I need to download to get the OffsetX and OffsetY working in my app.

Thanks
Mat

**Comment by captainsafia** [comment]
The fix has not been released yet but will be released as part of the preview in May.

**Comment by KieranDevvs** [comment]
@captainsafia Has this been released yet as I'm currently on the latest version of Blazor and do not see Offset X/Y within the `MouseEventArgs` class? 
image

**Comment by captainsafia** [comment]
@KieranDevvs What preview have you installed? I am not able to repro the issue on 5.0.0-preview5.

**Comment by jackbond** [comment]
I'm trying to implement some drag-drop functionality, and the lack of OffsetX and OffsetY led me here.

Is it safe to assume these properties will be included in the .NET 5 release, but not before?

**Comment by captainsafia** [comment]
> Is it safe to assume these properties will be included in the .NET 5 release, but not before?

Correct. This will be shipped in .NET 5. If you use one of the previews, you should be able to play around with this change.

**Comment by jackbond** [comment]
@captainsafia I downloaded the preview, and am now seeing the properties. The issue I am encountering now I'd like to handle the ondragover event. It looks like I need to call event.preventDefault(), but I'd also like to get the offsetX and offsetY properties during that event. Is there a way to call preventDefault from c#, such that I can use @ondragover instead of ondragover. Or do I have to use ondragover and do some sort of interop? Thanks.

**Comment by captainsafia** [comment]
@jackbond I see. Can you open a new issue with this question? Include a description of your goal and a repro if possible. The team will address it during triage.

**Pull request merged**
