### PR TITLE
Update to react 17.0

### LINKED ISSUE #5432: Update to React 17
Unknown release date: https://github.com/facebook/react/milestone/40

### PR DESCRIPTION
**Pull request by HaoK**
For https://github.com/dotnet/aspnetcore/issues/5432#event-4627545655

### CODE REVIEW

**Comment by HaoK** [comment]
Open issues to follow up on:

Angular:
ng run test - fails due to office tabs popping up
ng run e2e - fails with selneium/web driver issues
npm run build:ssr - fails with "Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(vendorChunk)."

React

**Comment by HaoK** [comment]
@javiercn here's a project that's the output of these changes with individual auth: https://github.com/HaoK/Random/tree/haok/temp/reactind

I verified that things seemed to work via 
dotnet run
npm run build
npm run test
npm run lint
npm run start

There are a bunch of npm audit errors related to https://npmjs.com/advisories/1677 but its not clear to me how to manually fix those, we can do that in a follow up PR since things are working right now

**Review by javiercn — APPROVED** [review]

**Comment by javiercn** [comment]
Looks great! I imagine this one is much easier to update because the react template is pretty much barebones

**Comment by f-nicefield-esdc** [comment]
Why not use UseReactDevelopmentServer anymore

**Pull request merged**
