### PR TITLE
Correct spacing

### PR DESCRIPTION
**Pull request by minhtaile2712**
Make relevant code line closer to its comment

# Correct spacing between comment and code

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

Correct spacing between comment and code.
`builder.Services.AddControllers();` will be closer to the comment `// Add services to the container.` rather than the next section's irrelevant comment.

### CODE REVIEW

**Comment by minhtaile2712** [comment]
@dotnet-policy-service agree

**Comment by minhtaile2712** [comment]
@dotnet-policy-bot agree

**Comment by minhtaile2712** [comment]
@dotnet-policy-service agree

**Comment by mkArtakMSFT** [comment]
Thanks for your PR. I'm going to close this as there is no value-add from this change. Someone will get this fixed as part of some other change in the same file at some point.

**Pull request closed without merging**
