### PR TITLE
Remove dead-lettered Centos.7.Amd64.Open queue

### PR DESCRIPTION
**Pull request by dougbu**
- was breaking Helix full matrix tests

### CODE REVIEW

**Comment by dougbu** [comment]
Kicked off https://dev.azure.com/dnceng/public/_build/results?buildId=828064 for extra validation

**Review by HaoK — APPROVED** [review]
Is there a non dead centos queue we should replace with?

**Comment by dougbu** [comment]
> Is there a non dead centos queue we should replace with?

I asked the same question in Teams and mentioned I don't see one. @halter73 is there a recommendation for centos testing these days❔

**Comment by halter73** [comment]
Is the Redhat.7.Amd64.Open queue sufficient? CentOS is meant to be binary compatible with RHEL.

**Comment by dougbu** [comment]
@halter73 I dunno. Who would we ask (besides you)❔

**Comment by HaoK** [comment]
If we already have another binary compatible queue in the matrix, seems like that would be good enough for now

**Review by wtgodbe — APPROVED** [review]

**Comment by halter73** [comment]
> Who would we ask (besides you)❔

I just pinged "First Responders" on Teams. It looks like this was a transient issue. Maybe we should just leave it. From the Teams conversation:

> @sunandabalu: @MattGal deadletettered a bunch of work items in Centos.7.Amd64.Open that had a 15 min timeout and were making the machines in the queue to die - https://github.com/dotnet/core-eng/issues/10908#issuecomment-697638974. but the queue should be functional now
>> @MattGal: that was me, sorry.   The queue was 14K deep and we wanted people's PRs to flow
>>    if you see that message for a queue that still exists, that will usually be the root cause... there was a mono PR going through that was wrecking machines and using up days of machine time stuck in the queue.

**Comment by halter73** [comment]
@MattGal pointed out that https://dev.azure.com/dnceng/public/_build/results?buildId=827134 took nearly 7 hours to fail and didn't timeout. Can we reduce the timeout?

**Comment by MattGal** [comment]
> > Who would we ask (besides you)❔
> 
> I just pinged "First Responders" on Teams. It looks like this was a transient issue. Maybe we should just leave it. From the Teams conversation:
> 
> > @sunandabalu: @MattGal deadletettered a bunch of work items in Centos.7.Amd64.Open that had a 15 min timeout and were making the machines in the queue to die - [dotnet/core-eng#10908 (comment)](https://github.com/dotnet/core-eng/issues/10908#issuecomment-697638974). but the queue should be functional now
> > > @MattGal: that was me, sorry.   The queue was 14K deep and we wanted people's PRs to flow
> > > if you see that message for a queue that still exists, that will usually be the root cause... there was a mono PR going through that was wrecking machines and using up days of machine time stuck in the queue.

It's more than transient, it was me cleaning up.  Your pattern is just unusual (if you really don't care about time, internal queues have fewer machines but also way fewer users).  The queue will continue to exist for the immediate future (EOL 2024!) but at some point we might encourage users to use docker queues to run most linux-es.

**Comment by dougbu** [comment]
We decided this is basically redundant

**Pull request merged**
