### PR TITLE
Update to Bootstrap5.1

### PR DESCRIPTION
**Pull request by HaoK**
Bootstrap just released 5.1 a few days ago too (sigh)

Cleanup to address spacing/layout regressions

cc @DamianEdwards @blowdart

### CODE REVIEW

**Comment by HaoK** [comment]
Doesn't look like changing the form groups affected the spacing on the Register button, when comparing against: https://getbootstrap.com/docs/5.0/examples/sign-in/ if I adopt the floating text and make the button 100, what do you think about this for the register?

image

**Comment by HaoK** [comment]
Basically do we want to use the `new class="form-floating"` for all the forms?

**Review by javiercn — APPROVED** [review]
I assume you've done due diligence.

**Comment by HaoK** [comment]
Yep thanks, coordinated with @blowdart on the iterative plan for the UI tweaks

**Pull request merged**
