### PR TITLE
Refactor Routing to use ProjectReference and move into src/Http folder

### PR DESCRIPTION
**Pull request by natemcmaster**
This implements https://github.com/aspnet/AspNetCore/issues/4246 for projects that were under src/Routing.

Changes:

* Stop producing Microsoft.AspNetCore.Routing.DecisionTree.Sources. I could not find any usages of  outside of the Microsoft.AspNetCore.Routing assembly, so I've moved this to be a subfolder of code in the Microsoft.AspNetCore.Routing project.
* Stop building src/Routing as a submodule. Use ProjectReference instead
* Move projects from src/Routing into src/Http/Routing/ and src/Http/Routing.Abstractions/
* Update package baselines and dependencies to support building routing projects and samples

### CODE REVIEW

**Comment by natemcmaster** [comment]
Two test failures in HttpSys: FYI @jkotalik @muratg 

* Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.Microsoft.AspNetCore.Server.HttpSys.Listener.ResponseCachingTests.Caching_SendFileWithFullContentLength_Cached
* Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.Microsoft.AspNetCore.Server.HttpSys.ServerTests.Server_MultipleStopAsyncCallsWaitForRequestsToDrain_Success

These appear to be unrelated to Routing.

**Comment by Tratcher** [comment]
I'm torn between putting this in Http vs Middleware. @JamesNK @rynowak?

**Comment by JamesNK** [comment]
While routing has middleware, it does feel more fundamental than other middleware. Plus routing has link generation, and that isn't middleware specific. I prefer Http.

**Review by JamesNK — APPROVED** [review]

**Comment by natemcmaster** [comment]
If there are no more objections, I'd like to merge this later today.

**Review by Tratcher — APPROVED** [review]

**Review by rynowak — APPROVED** [review]

**Pull request merged**
