### PR TITLE
Quarantining tests

### PR DESCRIPTION
**Pull request by sebastienros**
https://github.com/dotnet/aspnetcore/issues/30700
~~https://github.com/dotnet/aspnetcore/issues/30701~~

### CODE REVIEW

**Review by JamesNK — APPROVED** [review]

**Review by Tratcher — DISMISSED** [review]
https://github.com/dotnet/aspnetcore/pull/30672 already addresses the hosting issues.

**Comment by sebastienros** [comment]
@Tratcher is quarantining other tests though

**Comment by sebastienros** [comment]
And now it's StartupConfigureServicesThrows_Fallback that is also in `WebHostBuilderTests` that is failing.

**Comment by sebastienros** [comment]
@JunTaoLuo so it's a side effect of the other test that you are disabled? I will remove this then, I understand what you meant now @Tratcher.

**Comment by shirhatti** [comment]
I don't enough about how we quarantine tests, but in this instance the test was failing due to shared global state in the process. I assume after quarantining, the test now runs in a separate process, making it unlikely to ever fail while quarantined 😄

I'll file a work item to make our Activity tests more resilient by preferably moving them into a separate process.

**Comment by Tratcher** [comment]
> I don't enough about how we quarantine tests, but in this instance the test was failing due to shared global state in the process. I assume after quarantining, the test now runs in a separate process, making it unlikely to ever fail while quarantined 😄

Not quite. I think quarantined tests are skipped in normal runs but run normally in our special quarantine build. Quarantine is inadequate for tests that can cause side-effects for other tests.

**Pull request merged**
