### PR TITLE
Mark AspNetCore projects that aren't packaged explicitly

### PR DESCRIPTION
**Pull request by dougbu**
- avoid NU5104 warnings due to confusing versioning
- `$(IsShippingPackage)` was semantically incorrect in any case

### CODE REVIEW

**Comment by dougbu** [comment]
@Pilchie I'm proposing this as tell-mode cleanup for 3.1.3 because the versions in AspNetCore.App projects that _don't_ ship as packages aren't used -- they just cause 30 or so NU5104 without this change. For example, our custom `RemoveSharedFrameworkDependencies` task removes SharedFx / non-package dependencies regardless of the dependency's version.

**Review by wtgodbe — APPROVED** [review]

**Comment by wtgodbe** [comment]
Any corresponding cleanup needed in `Directory.Build.targets`, where we used to calculate `IsPackable` based off of `IsShippingPackage`?

**Comment by Pilchie** [comment]
Sounds good to me.

**Comment by wtgodbe** [comment]
Or maybe we should change https://github.com/dotnet/aspnetcore/blob/release/3.1/Directory.Build.targets#L8 to only set this property if it isn't already set

**Comment by dougbu** [comment]
> Or maybe we should change https://github.com/dotnet/aspnetcore/blob/release/3.1/Directory.Build.targets#L8 to only set this property if it isn't already set

With this PR, `$(IsPackable)` will only be set if `$(IsShippingPackage)` is not set explicitly for an AspNetCore.App project. It's a no-op because we're explicit about that too i.e.
``` msbuild
<IsAspNetCoreApp>true</IsAspNetCoreApp>
<IsShippingPackage>true</IsShippingPackage>
```
appears in all of the package+SharedFx projects. I left the line around to provide a reasonable default if someone leaves both `<IsShippingPackage>true</IsShippingPackage>` and `<IsPackable>false</IsPackable>` out in 'master' (once this merges forward). Any objections?

**Comment by dougbu** [comment]
@wtgodbe lease give this PR another once-over.

I changed this a fair amount since your approval. It's now building successfully 😺 and removes NU1504 errors except the one @JunTaoLuo fixed in #18790 as well as all MSB3277 warnings and some redundancy.

**Review by wtgodbe — APPROVED** [review]
(Still) looks good

**Review by JunTaoLuo — APPROVED** [review]

**Comment by dougbu** [comment]
@wtgodbe I see branding is done; any reason I should wait on this?

**Pull request merged**
