### PR TITLE
Merge from 'release/6.0-rc1' into 'release/6.0'

### PR DESCRIPTION
**Pull request by dougbu**
- bot couldn't do this automatically

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Why couldn't it do it? https://github.com/dotnet/aspnetcore/pull/35556

Also, I'm guessing this PR will fail on code check because of a unshipped.txt file being updated in a release/x.x branch
https://github.com/dotnet/aspnetcore/pull/35588/files#diff-fcf0cf86c8fe3f7f872569404cd06a4be7e6f51fb364e8102fc752def6d34731R216

**Comment by dougbu** [comment]
I believe the "bot" (actually a pipeline build kicked off after merges into source branches) was attempting to update #35556. It failed because versions have changed in both branches. I'll close #35556 in favour of this one.

We admins can ignore Code Check failures when necessary. This is a weird case caused by creating the RTM branch so early in the release cycle.

**Comment by BrennanConroy** [comment]
Sounds good! Thanks for the explanation.

**Comment by dougbu** [comment]
The only failures here are the expected Code Check complaints about 4 modified PublicAPI.Unshipped.txt files and the continued problems in the optional dotnet.aspnetcore-components pipeline. That's fine prior to RTM. (API stability in RC1 would have been nice but that ship has sailed.)

/ping reviewers

----

PS. @SteveSandersonMS @HaoK why isn't the new pipeline named `aspnetcore-components`❔ We don't prefix `aspnetcore` in any other pipelines and, while some teams use the `dotnet.` prefix, more use `dotnet-` and still more (like us) forgo prefixes entirely.

**Review by wtgodbe — APPROVED** [review]
Looks good, did you make any changes other than merge conflict resolution?

**Comment by wtgodbe** [comment]
> I believe the "bot" (actually a pipeline build kicked off after merges into source branches) was attempting to update #35556. It failed because versions have changed in both branches. I'll close #35556 in favour of this one.

It doesn't fail because versions changed in both branches, it fails after somebody pushes a commit resolving merge conflicts. In those cases the bot keeps failing until the old PR is merged, then opens a catch-up PR.

**Comment by dougbu** [comment]
>  did you make any changes other than merge conflict resolution?

No

**Pull request merged**
