### PR TITLE
[release/7.0] Backport pr 48892 to 7.0

### PR DESCRIPTION
**Pull request by mitchdenny**
Backport of #48892

### CODE REVIEW

**Comment by davidfowl** [comment]
Custom request to backport

**Comment by danmoseley** [comment]
approved by tactics

**Comment by mitchdenny** [comment]
There is a fix we need for this PR. The unit test itself has a bug. I'll update it this morning.

**Comment by mitchdenny** [comment]
Latest commit was to fix up a test case that was flakey (we picked up on main so have applied it to the backport as well so we don't make the servicing branch flakey.

**Comment by wtgodbe** [comment]
@mitchdenny I can merge this once it is review-approved

**Comment by mitchdenny** [comment]
Forwarded you an e-mail where approval was given.

**Comment by danmoseley** [comment]
@mitchdenny I believe he means, someone signed off on the review

**Review by danmoseley — APPROVED** [review]
appears to be accurate port

**Pull request merged**
