### PR TITLE
Use SemVer2 in packaging

### LINKED ISSUE #4339: Switch package versions to SemVer 2.0
In 3.0, most other .NET Core packages have started using semver 2.0. This solves a common problem with semver v1, which sorts pre-release labels alphabetically instead of numerically. We've worked around this by zero padding, but still occasionally get this wrong.

e.g. (semver 2) `3.0.0-preview.18572.1` vs (semver 1) `3.0.0-preview-18572-01`

Depends on https://github.com/dotnet/core-setup/issues/4795

**Requirements**

- [ ] We used semver v1 in 3.0 preview 1. Ensure NuGet, npm, and Maven would sort preview 2 packages higher. e.g. ensure `3.0.0-preview.18580.1` > `3.0.0-preview-18579-0056`
- [x] Make sure corehost can handle semver2 - tracking https://github.com/dotnet/core-setup/issues/4795
- [ ] Ensure Maven supports semver2.  If not, keep versioning .jar's with semver v1   (Update: it does not, so keep semver1.)
- [x] Ensure npm supports semver2. If not, keep versioning npm packages with semver v1

### PR DESCRIPTION
**Pull request by natemcmaster**
Resolves #4339 

Internal validation build: https://dev.azure.com/dnceng/internal/_build/results?buildId=205179&_a=summary

### CODE REVIEW

**Comment by anurse** [comment]
I'll grab the JARs and publish them to a private feed so we can do a quick sanity check on them.

**Comment by anurse** [comment]
Though I see the PR build doesn't use these build numbers :). Still, it's trivial to hack it up so I can still run a quick test.

**Comment by natemcmaster** [comment]
You can get the jar from https://dev.azure.com/dnceng/internal/_build/results?buildId=205179&_a=summary

**Comment by anurse** [comment]
The main thing I actually want to test is that it's treated like SemVer 2 (i.e. integer comparisons), so I need to hack something up anyway. Fortunately it's pretty trivial to do.

**Comment by anurse** [comment]
It looks good (Maven can download a version with `.`s in the pre-release tag) based on a MyGet feed I tried (https://myget.org/F/maven-semver-test/maven/). MyGet doesn't produce the right metadata to check that `3.0.0-foo.10` is offered as an update for `3.0.0-foo.2` but I know how we could test that. I don't feel a need to block this PR on that though.

Java packages look good to me!

**Review by analogrelay — APPROVED** [review]

**Pull request merged**
