### PR TITLE
Update 'release/5.0' branch for GA

### PR DESCRIPTION
**Pull request by dougbu**
- primarily a simple `git merge --strategy-option theirs release/5.0-rc2 --no-ff`
- only the last commit is new compared to release/5.0-rc2

### CODE REVIEW

**Review by mmitche — APPROVED** [review]

**Review by JunTaoLuo — APPROVED** [review]
Assuming CI passes.

**Comment by dougbu** [comment]
> Assuming CI passes.

Bien sûr sir

**Comment by dougbu** [comment]
@epananth @mmitche this update or something in the `darc` configuration caused the Maestro Channels Consistency post-build check to fail. See https://dev.azure.com/dnceng/internal/_build/results?buildId=831952&view=logs&j=a13e9384-d6d3-5a14-7a96-79282fc11262&t=62b78796-390e-5a19-0957-0b46593907e3&l=13 Is the `.NET 5` channel perhaps set up incorrectly❔
``` text
"C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\a69f05e2-2351-4055-bc68-4d593534662e.ps1'"
##[error]Channel 1299 is not present in the post-build YAML configuration! This is an error scenario. Please contact @dnceng.
##[error]PowerShell exited with code '1'.
Finishing: Maestro Channels Consistency
```

**Comment by epananth** [comment]
@mmitche already did a fix for this here -> https://github.com/dotnet/arcade/pull/6232

So I think if you got the latest arcade update to your branch. This should work for you

**Comment by epananth** [comment]
I have an issue to look into this -> https://github.com/dotnet/arcade/issues/6254

I will create a work around fix for your repo to get you unblocked now.

**Comment by epananth** [comment]
Actually @mmitche created a fix for this last week.
Also, looks like you didnt get the latest update from arcade 

image

So I updated subscription, it should have the fix.

**Comment by dougbu** [comment]
To confirm: release/5.0-rc2 is working because it uses a channel that's consistent but release/5.0 doesn't have that luck❔

**Comment by mmitche** [comment]
Right, the RC2 channel is in that list of valid channels, but .NET 5 is not.

**Pull request merged**
