### PR TITLE
Changing `@functions` block to `@code` block

### PR DESCRIPTION
**Pull request by mkArtakMSFT**
Addresses #10527

### CODE REVIEW

**Review by rynowak — APPROVED** [review]

**Review by ryanbrandenburg — COMMENTED** [review]
Code looks fine, someone with Razor knowledge should do the approval.

**Comment by mkArtakMSFT** [comment]
@aspnet/build folks, can somebody please look at what's going on here? Thanks

**Comment by dougbu** [comment]
@artak it appears your `@functions` -> `@code` changes borked something:
```
F:\workspace\_work\1\s\src\Components\test\testassets\TestServer\Pages\Authentication.cshtml(54,7): error CS0103: The name 'code' does not exist in the current context [F:\workspace\_work\1\s\src\Components\test\testassets\TestServer\Components.TestServer.csproj]
```

In addition, `yarn install` failed in the Code Check job and the Windows test job timed out. But, I doubt those errors will be repeated. The above error occurs in every job that does not fail much earlier.

**Comment by mkArtakMSFT** [comment]
Thanks @dougbu. I couldn't actually find that error. I saw some timeouts with npm earlier but not that one. Anyway, will resolve it now.

**Comment by mkArtakMSFT** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=204600

**Pull request merged**
