### PR TITLE
Consolidated JsonPatchDocument extensions into ApplyTo method overloads, updated relevant tests

### PR DESCRIPTION
**Pull request by WhitWaldo**
Summary of the changes (Less than 80 chars)
- Consolidated JsonPatchDocument extensions into ApplyTo method overloads, updated relevant tests

**Background**
I moved the extension methods for JsonPatchDocument out of /src/Features/Mvc/Mvc.NewtonsoftJson and converted into overloads on the JsonPatchDocumentOfT class. Moved relevant tests as well and added the relevant using statement.

The [documentation](https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-3.1#jsonpatch-in-aspnet-core) references the use of ApplyTo with ModelState, but the Microsoft.AspNetCore.JsonPatch NuGet package does not actually contain a method with this signature. I [reported](https://github.com/aspnet/AspNetCore.Docs/issues/16286) this inconsistency earlier this evening.

Rather, the corresponding extension method lives within the Microsoft.AspNetCore.Mvc.NewtonsoftJson package for unknown reasons, as there are no dependencies on NewtonsoftJson for its implementation.

This pull request aims to both make the documentation accurate and consolidate JsonPatchDocument functionality, moving it out of an irrelevant package.

### CODE REVIEW

**Comment by WhitWaldo** [comment]
I'm not entirely sure what's necessary in order to make this compatible with .NET 5, but if someone can point me in the right direction to get it to pass the build checks, I'd be happy to make the appropriate change(s).

**Comment by WhitWaldo** [comment]
Unfortunately, it looks as though there's a project reference issue. I suspect it has to do with the ref/ files not updating since the public API has changed, but when I run `dotnet msbuild /t:GenerateReferenceSource` per the [documentation](https://github.com/aspnet/AspNetCore/blob/master/docs/ReferenceAssemblies.md), I get an error indicating that I lack a compatible .NET Core SDK for 5.0.100-alpha-1-105536 (and I'm not sure how to get that installed).

If someone can point me in the right direction at this point, I'd appreciate it!

**Comment by pranavkm** [comment]
Thanks for your PR @WhitWaldo. Unfortunately the layering of JsonPatch and MVC disallows this code change. MVC depends on JsonPatch, you've effectively introduced a circular dependency. In addition, this looks like a great addition as a third party extension rather than being baked in to the framework. I'd recommend publishing a NuGet package that does what you have here.

**Comment by pranavkm** [comment]
Looking further, this feature already exists: https://github.com/dotnet/aspnetcore/blob/c565386a3ed135560bc2e9017aa54a950b4e35dd/src/Mvc/Mvc.NewtonsoftJson/src/JsonPatchExtensions.cs#L21-L42. You might be missing a reference to the `Microsoft.AspNetCore.Mvc.NewtonsoftJson` package or a using if you don't see the API show up.

**Comment by WhitWaldo** [comment]
@pranavkm Coincidentally, it's because it exists in the Newtonsoft.Json package that I created this in the first place. First of all, there are no dependencies in this code on anything in Newtonsoft.Json. It appears to have been stuck there during some previous refactoring (likely because of the JSON patch concept and Newtonsoft.Json being the only thing JSON-related at the time).

Since ASP.NET Core is moving towards the use of System.Text.Json, it both doesn't make sense to keep this functionality in a module that presumable may be dropped at some point in the future when there's 1) no dependency on the particular JSON serializer used and 2) it can instead live on in the original JsonPatch implementation itself.

**Pull request closed without merging**
