### PR TITLE
Validation to use the correct argument syntax when using npm or yarn

### PR DESCRIPTION
**Pull request by jguizarj**
**PR Title**
Validation to use the correct argument syntax when using npm or yarn

**PR Description**
"npm run" command syntax differs from "yarn run" when sending arguments to the script. As described by @denschub in #30654. That difference cause a warning when yarn is used as a package manager.

"npm-run-script" command syntax:
`#npm run-script <command> [--silent] [-- <args>...]`

'yarn run' command syntax:
`#yarn run [script] [<args>]`

**PR Changes**
- Added validation code to use the right syntax according to the package manager (npm or yarn)

Addresses #30654

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=31790) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=31790) before we can accept your contribution.<br/><br/>:x: jguizarj [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=31790)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=31790) it.</sub>

**Comment by dougbu** [comment]
@AndriySvyryd @javiercn please review soon so we know it's ready well in advance of the 5.0.8 merge window (if it's intended for that milestone)

**Comment by javiercn** [comment]
Thanks for the PR. 

Unfortunately this does not meet our bar for patching so we are not going to take it. 

We are significantly changing the way SPA frameworks are setup in our 6.0 release to more closely align to the recommended approach by the frameworks and we recommend following that approach moving forward.

**Pull request closed without merging**
