### PR TITLE
Stop paying attention to PatchConfig.props

### PR DESCRIPTION
**Pull request by dougbu**
- part of aspnet/AspNetCore-Internal#3024

### Summary
The ASP.NET Core team has hit repeated issues in servicing with merging fixes and not shipping the affected packages. 3.0 and later branches ship far fewer packages than 2.x and we have no (LZMA) downsides to shipping everything. The ASP.NET Core team thus decided to simplify the infrastructure and remove the previous ship / no-ship controls (in PatchConfig.props). This PR ~~does the minimum change to simply ignore that file~~ completely removes the PatchConfig.props file and all references to it.

We will probably follow up in 2.x branches to change the approach, automating what ships more extensively and removing the need for manual PatchConfig.props changes. That is _not_ this change.

#### Small exception
"Everything" does not include the targeting packs or Microsoft.AspNetCore.App.Ref. We do not normally service those.

### Customer Impact
Never miss a fix after a servicing upgrade

### Regression?
No

### Testing
PR validation build includes stable versioning and published everything. This can be observed in the Source_Build_Packages and Windows_Packages listings at https://dev.azure.com/dnceng/public/_build/results?buildId=415240&view=artifacts

#### Small exception
Microsoft.AspNetCore.App.Ref and the targeting packs _were_ produced in that build. That's due to the 3.0.1 special case.

### Risk
Low.

### CODE REVIEW

**Review by JunTaoLuo — APPROVED** [review]
I don't think this build will have any effect though since the branch doesn't have stabilized build set to true.

**Comment by dougbu** [comment]
> I don't think this build will have any effect though since the branch doesn't have stabilized build set to true.

Agreed. I rebased on current 'release/3.0' to pick up stabilization setting.

**Comment by dougbu** [comment]
Fired off a new additional test build at https://dev.azure.com/dnceng/internal/_build/results?buildId=423518&view=results

**Comment by dougbu** [comment]
/bump reviewers
(All checks successful, including the test internal build.)

**Comment by dougbu** [comment]
Asking for another review because this is no longer a one-liner

**Review by wtgodbe — APPROVED** [review]

**Pull request merged**
