### PR TITLE
Quarantine Microsoft.AspNetCore.Components.E2ETests

### PR DESCRIPTION
**Pull request by wtgodbe**
https://github.com/dotnet/aspnetcore/issues/29553

### CODE REVIEW

**Comment by HaoK** [comment]
@dotnet/aspnet-blazor-eng this seems pretty risky to quarantine all component tests, would we have any pr validation of components at all if we quarantine the whole project?

**Comment by pranavkm** [comment]
@HaoK are you able to figure out if this is a infrastructure / product / dependency issue? It's very worrying to quarantine all of Blazor's end-to-end test coverage.

**Comment by captainsafia** [comment]
There was a thread on this over on the Teams channel. Apparently, these tests have been failing frequently since the 22nd.

We triaged the issue for this for preview2, but not sure when it will be assigned/worked on.

> It's very worrying to quarantine all of Blazor's end-to-end test coverage.

Ditto. If we can figure out the root issue soon, we can address instead of quarantining. If not, I'm favor of quarantining and following up with the fix. Especially because aggressive failures here will end up increasing the amount of time people need to wait before being able to merge their PRs.

Is it possible that these failures are related to the recent changes in component tests?

**Comment by HaoK** [comment]
Do we think the jump in failures might be related to the unquarantine of a bunch of tests in https://github.com/dotnet/aspnetcore/commit/3f7b205c7c7316ae683e6d4386d04b685e0b9a61#diff-161948171825dc8c1b30fdc7c517d8e960d462359d1959cd30aa428ad16172f2 that was 6 days ago?

**Comment by HaoK** [comment]
Maybe we just try rolling back that PR as a first step to see if that brings us back to a better place?

**Comment by HaoK** [comment]
I opened https://github.com/dotnet/aspnetcore/pull/29652 to see if that helps, basically it requarantines only the component tests in that commit

**Comment by captainsafia** [comment]
Are they the same tests that are currently failing?

I'd find it rather surprising if the tests currently failing are the ones that were unquarantined since they would've had to pass the 30+ days passing requirement.

**Comment by HaoK** [comment]
I think maybe we should tweak our quarantined runs to run all tests not just quarantined tests, it wouldn't be surprising if there are tests that behave differently when we only run a small set of tests, we for sure would miss any poorly written tests that affect other tests intentionally or not.

**Comment by HaoK** [comment]
But at this point it seems like we have the pretty bad option of just not testing components at all, or trying to rollback to some kind of known good state.

**Comment by HaoK** [comment]
At least 3 of the 10 component tests that failed in the last week were in the batch we recently unquarantined:

EventDuringBatchRendering_CanTriggerDOMEvents()
BubblingStandardEvent_FiredOnElementWithoutHandler
CanUploadAndConvertImageFile

**Comment by mkArtakMSFT** [comment]
@wtgodbe thanks for the PR. Let'stake the PR @HaoK has instead. We want to continue improving the stability here and this won't help much.

**Pull request closed without merging**
