### PR TITLE
Use the `JoinItems` task rather than faking it in an item group

### PR DESCRIPTION
**Pull request by dougbu**
- may speed the build and reduce the size of our binary logs

### CODE REVIEW

**Comment by dougbu** [comment]
#### Time
- 30 day 80%th percentile pipeline duration was **2h 17m 35s**
- shortest run for 'master' branch I saw ran about 1h 38m
- [PR validation of this change](https://dev.azure.com/dnceng/public/_build/results?buildId=626032) ran **1h 23m 35s**

#### Largest artifact
- Windows_Logs [Build of 'master'](https://dev.azure.com/dnceng/public/_build/results?buildId=626086) artifact **1097 MB**
  - build.x86.binlog file **507 MB**
- Windows_Logs [PR validation build](https://dev.azure.com/dnceng/public/_build/results?buildId=626032) artifact **874 MB** (20.3% smaller)
  - build.x86.binlog file **462 MB** (8.9% smaller)

**Comment by dougbu** [comment]
@mmitche this follows up on our recent conversation. Time savings look better than I expected😺

**Comment by Pilchie** [comment]
Wow - that *is* some savings.  Nice work.

**Comment by mmitche** [comment]
> Wow - that _is_ some savings. Nice work.

Oh there is for sure more coming. I did some analysis with the binlog guy yesterday and there is major low hanging fruit.  For context:
- If you remove the binlog (~140 MB) from roslyn (~6 million LOC), the build time stays at about 10 minutes
- If you remove the binlog from aspnetcore, the build time drops 30%

**Review by mmitche — APPROVED** [review]

**Comment by wtgodbe** [comment]
:shipit:

**Review by wtgodbe — APPROVED** [review]

**Comment by dougbu** [comment]
> there is major low hanging fruit

I was glad to see something I'd played with in an unrelated local change worked so well. Great to hear we have more room to improve❕

To that end, I'm wondering about removing extra cleanup like the following or moving it above where `@(Bletch)` is used. This would worsen `msbuild`'s memory use but save on IO because the removals wouldn't be logged as much. Is that likely a reasonable tradeoff?
``` msbuild
<ItemGroup>
  <Bletch Remove="@(Bletch)" />
</ItemGroup>
```

Any other suggestions from "the binlog guy"❔

**Comment by mmitche** [comment]
I think you'd be better off removing it altogether.

**Comment by dougbu** [comment]
> I think you'd be better off removing it altogether.

In targets that are only called once per `<MSBuild />` context, sure. But, doing it everywhere may cause correctness issues. I'll see what breaks 😈

**Pull request merged**
