### PR TITLE
Update tests to reflect change of web app manifest extension in React C# template

### PR DESCRIPTION
**Pull request by christianliebel**
# Update tests to reflect change of web app manifest extension in React C# template

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Update tests when React C# template in spa-templates uses "webmanifest" as manifest extension

## Description

The React project template in spa-templates uses "json" as the extension for the Web Application Manifest. "webmanifest" is the recommended one (see https://github.com/dotnet/aspnetcore/issues/43755 and https://github.com/dotnet/aspnetcore/pull/43756 for context). If https://github.com/dotnet/spa-templates/pull/80 gets merged and the submodule updated, the tests in this repository will fail. This PR would fix them again.

### CODE REVIEW

**Comment by TanayParikh** [comment]
Just merged https://github.com/dotnet/spa-templates/pull/80.

**Review by TanayParikh — APPROVED** [review]

**Comment by TanayParikh** [comment]
@christianliebel could you please take a look at any additional potential test changes required now that https://github.com/dotnet/spa-templates/pull/80 is merged?

**Comment by TanayParikh** [comment]
> If [dotnet/spa-templates#80](https://github.com/dotnet/spa-templates/pull/80) gets merged and the submodule updated, the tests in this repository will fail. This PR would fix them again.

@dotnet/aspnet-build did I potential miss a build break? https://github.com/dotnet/spa-templates/pull/80 was merged and should've automatically(?) been reflected in our aspnetcore builds due to the submodule setup?

**Comment by wtgodbe** [comment]
@javiercn fixed some tests in https://github.com/dotnet/aspnetcore/pull/46122 but looks like they're still failing

**Comment by TanayParikh** [comment]
Thanks, will take a look

**Comment by TanayParikh** [comment]
Closing given https://github.com/dotnet/aspnetcore/pull/46122. Thanks @christianliebel!

**Pull request closed without merging**
