### PR TITLE
Use spans for complex segments

### PR DESCRIPTION
**Pull request by davidfowl**
Small change to spanify matching on complex segments

### CODE REVIEW

**Comment by rynowak** [comment]
Do we have any perf tests that cover this?

**Comment by davidfowl** [comment]
> Do we have any perf tests that cover this?

Doesn't look like it.

**Comment by davidfowl** [comment]
@rynowak what do you want to do here?

**Review by JamesNK — APPROVED** [review]

**Comment by rynowak** [comment]
I want James to approve it and you to merge it.

**Comment by rynowak** [comment]
Now I want someone to delete the branch.

**Pull request merged**
