### PR TITLE
CanCachePolicy=>AllowsCachingPolicies

### PR DESCRIPTION
**Pull request by HaoK**
React to API review: https://github.com/dotnet/aspnetcore/issues/43227

We added a new API last week, and this is just renaming the new property to a better name which came out of the API review for this feature.

### CODE REVIEW

**Review by davidfowl — APPROVED** [review]

**Comment by HaoK** [comment]
@dotnet/aspnet-build do I need to worry about the code check API files failing?

**Comment by wtgodbe** [comment]
> https://github.com/orgs/dotnet/teams/aspnet-build do I need to worry about the code check API files failing?

No, that's expected for changing API in release branches. If this gets servicing-approved one of us will just force-merge it.

**Comment by adityamandaleeka** [comment]
Approved. This is brand new API.

**Review by captainsafia — APPROVED** [review]

**Comment by dougbu** [comment]
> Approved. This is brand new API.

Thanks @adityamandaleeka. Suggest using the `servicing-approved` label to make this visible in PR lists 😉

**Comment by renatoklypz** [comment]
I don't understand why the `AllowsCachingPolicies` property is only available in NETCOREAPP `#if NETCOREAPP`, if you are using it in the middleware in a mandatory way. When you run an API unit test (using `WebApplicationFactory`), the property is not found, throwing an exception.

**Pull request merged**
