### PR TITLE
Use dotnet certificate

### PR DESCRIPTION
**Pull request by mmitche**
Use the dotnet certificate instead of Microsoft400.

https://github.com/dotnet/announcements/issues/184

### CODE REVIEW

**Comment by mmitche** [comment]
Merged manifest looks good.

**Comment by mmitche** [comment]
@dougbu What to do about the compile errors in the quarantined tests?

**Review by dougbu — APPROVED** [review]

**Comment by mmitche** [comment]
> Separately, GitHub makes it look like you're updating the MessagePack-CSharp submodule and restoring the NuGet.config file there. Please do **not** do that.

Agh...one sec let me fix that...I use `git commit -a` a lot.

**Comment by mmitche** [comment]
> > I use `git commit -a` a lot.
> 
> No, never do that because it's an extra character to type😀 `git commit .` all day, every day.
> 
> But, you might want to use ` git submodule update --init --force --recursive` a lot too😉

Option B: never use submodules :D

**Comment by captainsafia** [comment]
> I thought we fixed the Razor compilation errors everywhere @captainsafia❔ Either way, it's nothing related to your change @mmitche

Not yet. We've been trying different things. The latest hammer attempt is https://github.com/dotnet/aspnetcore/pull/32581

**Pull request merged**
