### PR TITLE
Create WebView2 abstraction for sharing code between ASP.NET Core and .NET MAUI

### LINKED ISSUE #32770: Create WebView2 abstraction for sharing code between ASP.NET Core and .NET MAUI
Due to this type identity difference: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1193

We should create an abstraction that can be implemented once in ASP.NET Core and once in .NET MAUI so that we can have common code across all platforms instead of copying hundreds of lines of code and duplicating bugs.

### PR DESCRIPTION
**Pull request by Eilon**
_Most_ of this change is quite un-interesting because it's creating an abstraction, implementing it, and then calling it. The most fundamental change is that the WebView2 package _no longer references Edge WebView2_. Instead, the WPF and WinForms packages reference it in order to implement the abstractions. This allows .NET MAUI's implementation to reference the WinUI WebView2 package, which has different type identities (and some slightly different APIs, too).

What's actually interesting here?

1. WebView2 package reference moved from Components WebView2 package into WPF and WinForms packages
2. `EnsureCoreWebView2Async` no longer takes in an Environment because that's not allowed in WinUI. So the WPF/WinForms implementation store their created Environment and then pass it in. (Not a big deal.)
3. The event handler pattern is abstracted and simplified instead of trying to wrap the exact WebView2 API. For BlazorWebView we use a limited set of APIs so they are simplified to the usage. Because event handlers are wrapped, they changed to a pattern `Action AddXYZHandler(my_handler)` where the returned `Action` is a removal callback because otherwise the caller couldn't actually un-hook the event. We don't actually use the removal callbacks right now, but when we do proper disposal, we'll want to unhook event handlers.
4. A new `QueueBlazorStart()` method was added that isn't used in WPF/WinForms, but is used in .NET MAUI WinUI, because it uses autostart='false' and needs to queue Blazor startup. If we choose to always use autostart='false' then we could remove this method and always do it in the common WebView2WebViewManager class.
5. I tried this out in .NET MAUI by copying the WebView2 abstractions over and updating the implementations and it works great. I will later update .NET MAUI by commiting those changes so that it's already using this new pattern and when .NET MAUI starts referencing the new types, all we have to do is delete the copied code, and it will continue to work.

The net result is that `WebView2WebViewManager` changed relatively little, which shows the the abstractions Do The Needful™.

Fixes #32770

### CODE REVIEW

**Comment by Eilon** [comment]
Pushed a change that should fix the CI failures. It's a bug in the WebView2 packages.

**Review by javiercn — COMMENTED** [review]
I have more high level questions than anything else.

* Are customers supposed to interact with these "wrappers"?
* Can we put a comment like [this](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/RenderTree/Renderer.cs#L21-L24) otherwise?

**Comment by Eilon** [comment]
@javiercn - no & yes. I will add a comment like that on top of the other comments that I have for all the public APIs.

**Comment by Eilon** [comment]
Comments added.

**Review by javiercn — APPROVED** [review]

**Pull request merged**
