### PR TITLE
Added an extension method for setting up IUserConfirmation type

### PR DESCRIPTION
**Pull request by pavinan**
Summary of the changes (Less than 80 chars)
 - Added an extension method for setting up IUserConfirmation type.

### CODE REVIEW

**Comment by HaoK** [comment]
Seems ok to add, any opposition @blowdart ?  Just a new sugar method off IdentityBuilder

**Comment by blowdart** [comment]
Sure. There's even tests, thank you @pavinan !

**Comment by pavinan** [comment]
@HaoK any updates?

**Comment by HaoK** [comment]
Thanks @pavinan !

**Pull request merged**
