### PR TITLE
Fix API baselines after 5.0 merge

### PR DESCRIPTION
**Pull request by JunTaoLuo**
I removed APIs from Shipped if a new one replaced the old one. The proper way of doing this is to add the API to Unshipped and add a *REMOVED* prefix. This PR fixes this merge mistake.

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
ping @dougbu

**Review by dougbu — CHANGES_REQUESTED** [review]
This PR is way too large. Just need to restore the lines shown by
``` powershell
git diff release/5.0..master -- **/PublicAPI.Shipped.txt
```
then add `*REMOVED*` to the restored lines.

**Comment by JunTaoLuo** [comment]
Superseded by https://github.com/dotnet/aspnetcore/pull/28253

**Pull request closed without merging**
