### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by benaadams**
Combine https://github.com/aspnet/AspNetCore/pull/7640 and https://github.com/aspnet/AspNetCore/pull/7668

### CODE REVIEW

**Comment by benaadams** [comment]
Debian dockerhub TLS timeout
```
Sending build context to Docker daemon  5.632kB

Step 1/12 : FROM microsoft/dotnet:2.1-runtime-deps-bionic
Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout
##[error]Bash exited with code '1'.
##[section]Finishing: Build Debian installers
```

**Comment by benaadams** [comment]
Don't know the correct incantation to retrigger 😢

**Comment by Tratcher** [comment]
@benaadams I'll handle re-runs as needed.

**Review by Tratcher — APPROVED** [review]

**Comment by Tratcher** [comment]
Thanks

**Pull request merged**
