### PR TITLE
Use Azure Artifacts instead of MyGet

### PR DESCRIPTION
**Pull request by garath**
As part of [moving to Azure Artifacts from MyGet](https://github.com/dotnet/arcade/blob/master/Documentation/MigrationPlan/MyGetFeeds.md), point all MyGet feed sources to new Azure Artifacts feed.

@dougbu FYI, from email.

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
Wondering a bit whether some of the "added" feeds in a few directories can be removed. But, that's fairly minor and I'm not sure where we block use of the usual build/sources.props file.

**Comment by markwilkie** [comment]
Thanks for approving @dougbu.  Would you mind merging please?  We don't have permission...

**Comment by dougbu** [comment]
Build in a weird state. Setting `auto-merge` and will start the validation build from scratch.

**Comment by dougbu** [comment]
Ah well, I'll come back and do the final merge

**Pull request merged**
