### PR TITLE
Remove site-extension workarounds

### PR DESCRIPTION
**Pull request by JunTaoLuo**
Working on https://github.com/aspnet/AspNetCore/issues/11701

Opening up multiple PRs since running multiple isolated builds is a bit slow.

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
The dotnet store related workarounds can be removed. The change regarding transitive dependencies cannot since that's a behaviour change in preview 6 that we'll need to continue to disable going forward.

**Review by dougbu — COMMENTED** [review]
Something still isn't working. Please ping when the changes build correctly.

If the workarounds are both still necessary, please find out why e.g. fixes might actually be in VS or missed the preview 7 SDK. Whatever is going on, please make the comment as specific as you can.

Separately, please file an issue to move to the preview 8 SDK everywhere. If that would help here, combine the two fixes in this PR.

**Comment by JunTaoLuo** [comment]
It is building correctly. The failures are build flakiness (yarn) and template test failures. Will re-run

**Comment by JunTaoLuo** [comment]
Woops, didn't tag @aspnet/build

**Comment by JunTaoLuo** [comment]
cc @dougbu @wtgodbe please like and subscribe!

**Review by dougbu — APPROVED** [review]

**Pull request merged**
