### PR TITLE
Support generic array parameters in components

### LINKED ISSUE #34711: Blazor component with generics incorrectly invokes Func<T[]> that is a parameter
If a generic component has a parameter property:
```csharp 
@typeparam T

@code {
    [Parameter]
    public Func<T[]> GetItems { get; set; }
}
```

When you use the component the GetItems will cause a build fail with the error "The type or namespace name T could not be found" since it generates this code for the page:
```csharp 
__builder.OpenComponent<BlazorTest.Client.Shared.GenericComponent<string>>(0);
__builder.AddAttribute(1, "GetItems", new System.Func<T[]>(GetItems)
````

But there is no definition of T there as T is defined on the comonent, it should generate as string[] not T[]

### To Reproduce
With the component above create the following page
```csharp
@page "/"

<GenericComponent T="string" GetItems="GetItems" />

@code {
    string[] GetItems() => new[]
    {
        "Foo", "Bar"
    };
}
```

As soon as you try to compile it will fail

I have tested this on 6.0.0-preview.6.21355.2

### PR DESCRIPTION
**Pull request by campersau**
**PR Title**
Using generic arrays as component parameters resulted in compilation failures which are now fixed.

**PR Description**
Before it was only possible to have generic parameters like `IList<T>` / `Func<T>` but not `T[]` / `IList<T[]>` / `Func<T[]>` because a different check for arrays is required.

Fixes https://github.com/dotnet/aspnetcore/issues/34711

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging @captainsafia @pranavkm @NTaylorMullen

**Comment by SteveSandersonMS** [comment]
When merging, check if this fixes https://github.com/dotnet/aspnetcore/issues/29105

**Review by pranavkm — APPROVED** [review]

**Pull request merged**
