### PR TITLE
Disable static web assets from identity

### PR DESCRIPTION
**Pull request by javiercn**

### CODE REVIEW

**Comment by pranavkm** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=274599&view=logs&jobId=f2f63060-d9d6-52d0-adee-b97db5a9ab91

**Review by pranavkm — APPROVED** [review]

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2794
https://github.com/aspnet/AspNetCore-Internal/issues/2744

**Review by ryanbrandenburg — APPROVED** [review]
:shipit: from the Templating perspective.

**Comment by javiercn** [comment]
Actually, I completed a separate PR, so closing this

**Pull request closed without merging**
