### PR TITLE
Better implementation of EventCallback.Equals

### LINKED ISSUE #53361: EventCallback.Equals is not giving correct results
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We noticed after upgrading our blazor application to .net 8.0 that some EventCallback keep being modified. Eventhough the value was the same, the same target component, the same method.
The generated code that renders the component seems to fabricate a new MulticastDelegate, having the same Type, Target and Method. The implementation of EventCallback uses Object.ReferenceEquals, so it concludes it is different every render. 
 

### Expected Behavior

The component should see EventCallbacks as equal when the delegate and Target are the same. MulticastDelegate has the Equals method overridden, so use that instead of ReferenceEquals.

### Steps To Reproduce

I will make a PR with a fix

### Exceptions (if any)

_No response_

### .NET Version

8.0.101

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JelleHissink**
# Better implementation of EventCallback.Equals

We noticed after upgrading our blazor application to .net 8.0 that some EventCallback keep being modified. Eventhough the value was the same, the same target component, the same method.

The generated code that renders the component seems to fabricate a new MulticastDelegate, having the same Type, Target and Method. The implementation of EventCallback uses Object.ReferenceEquals, so it concludes it is different every render.

Fixes #53361

### CODE REVIEW

**Comment by JelleHissink** [comment]
@dotnet-policy-service agree

**Comment by JelleHissink** [comment]
I wanted to reproduce the build error locally, however I am having issues running all tests locally because I get this error when I execute restore.cmd: 
```
C:\Work\github\aspnetcore\eng\targets\Npm.Common.targets(46,5): error : eslint-plugin-jsdoc@39.9.1: The engine "node" i
s incompatible with this module. Expected version "^14 || ^16 || ^17 || ^18 || ^19". Got "20.11.0" [C:\Work\github\aspn
etcore\src\SignalR\clients\ts\common\common.npmproj]
```

**Comment by SteveSandersonMS** [comment]
Would it be OK to retarget this to `main` so it goes in .NET 9? Targeting `release/8.0` is much more complicated as we need a much more definite justification for risking other behavioral changes in a patch release.

Bear in mind that the change being introduced here doesn't only affect `EventCallback.Equals`; it also affects rendering as it can change which set of components get detected as needing an update according to the diffing system. It doesn't just revert to .NET 7 behavior; it creates a different behavior for rendering than existed in .NET 7 or 8. I agree that the change is a desirable one in the long term, but we try to be extremely careful about introducing subtle behavioral changes in patch releases.

I know you need a solution for your own app before then, but perhaps you could work around by calling your own `EventCallback` comparison utility function.

**Comment by JelleHissink** [comment]
Sorry, I managed to totally get stuck in changing the target branch, I made a new PR #53395
@SteveSandersonMS Could you assign the same properties there?

**Pull request closed without merging**
