### PR TITLE
Revert "Update dependencies from https://github.com/dotnet/runtime build 20201029.3 (#27353)"

### PR DESCRIPTION
**Pull request by dougbu**
- do _not_ restore feeds in NuGet.config that aren't needed post-release

This reverts commit bc6c953506108d31d33f71633504506758eef1fc.

### CODE REVIEW

**Comment by dougbu** [comment]
It's possible the current release/5.0 build issues are due to us picking up newer non-stable dotnet/runtime packages (Microsoft.Extensions.Internal.Transport in particular) from the dotnet5-transport feed than the 5.0.0 packages from the NuGet.org feed. That is, root cause may be this dependency flow PR that occurred _after_ the commit we decided to release.

**Review by wtgodbe — APPROVED** [review]

**Comment by dougbu** [comment]
/fyi @ericstj @dsplaisted @jaredpar the commit I'm removing may explain all. Something similar likely happened in the branch we had the email thread about i.e. my dougbu/5.0.2 branch for the servicing readiness exercise.

/cc @mmitche there's a downside to flowing dependencies then deciding not to publish them but we might not have noticed if I hadn't removed the darc-pub-dotnet-runtime-7ef6d50 feed as part of rebranding. Of course, I can't explain why the PR build containing that change _succeeded_.

**Comment by mmitche** [comment]
> /fyi @ericstj @dsplaisted @jaredpar the commit I'm removing may explain all. Something similar likely happened in the branch we had the email thread about i.e. my dougbu/5.0.2 branch for the servicing readiness exercise.
> 
> /cc @mmitche there's a downside to flowing dependencies then deciding not to publish them but we might not have noticed if I hadn't removed the darc-pub-dotnet-runtime-7ef6d50 feed as part of rebranding. Of course, I can't explain why the PR build containing that change _succeeded_.

@dougbu You can wait on this change for now if you want. Once we get an actual runtime 5.0.1 build, I am planning on going through all repos and verifying that the remaining 5.0.0 versioned items point to the RTM build.

**Comment by sebastienros** [comment]
Can it explain why some tests are now failing when it checks which assemblies are part of the shared framework?

```
[xUnit.net 00:00:00.71]     Microsoft.AspNetCore.SharedFxTests.SharedFrameworkContainsListedAssemblies [FAIL]
[xUnit.net 00:00:00.71]       Assert.Empty() Failure
[xUnit.net 00:00:00.71]       Collection: ["System.Formats.Asn1", "Microsoft.Win32.Registry", "System.Security.Principal.Windows", "System.Security.AccessControl", "System.Security.Cryptography.Cng"]
[xUnit.net 00:00:00.71]       Stack Trace:
[xUnit.net 00:00:00.71]         /_/src/Framework/test/SharedFxTests.cs(59,0): at Microsoft.AspNetCore.SharedFxTests.SharedFrameworkContainsListedAssemblies()
```

**Comment by dougbu** [comment]
>> /fyi @ericstj @dsplaisted @jaredpar the commit I'm removing may explain all. Something similar likely happened in the branch we had the email thread about i.e. my dougbu/5.0.2 branch for the servicing readiness exercise.
>> 
>> /cc @mmitche there's a downside to flowing dependencies then deciding not to publish them but we might not have noticed if I hadn't removed the darc-pub-dotnet-runtime-7ef6d50 feed as part of rebranding. Of course, I can't explain why the PR build containing that change _succeeded_.

> @dougbu You can wait on this change for now if you want. Once we get an actual runtime 5.0.1 build, I am planning on going through all repos and verifying that the remaining 5.0.0 versioned items point to the RTM build.

I'll look for a dependency PR before merging this. My aim is to unblock building PRs targeting this branch ASAP.

**Pull request merged**
