### PR TITLE
Fix wasm caching on localhost and various E2E test issues

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
In https://github.com/dotnet/aspnetcore/pull/24012 we introduced a regression whereby `localhost`/`127.0.0.1` was excluded from Blazor WebAssembly caching. The result is that the behavior is different when running locally compared with in production, which risks hard-to-detect bugs.

This is particularly frustrating because our E2E tests actually tell us that there's a defect here, but the relevant ones are marked as quarantined.

### Update

I've also added fixes for various E2E test issues I found while investigating the above (and E2E tests generally). As of this PR, all the E2E tests pass locally for me, at least after working around various unrelated build issues.

### CODE REVIEW

**Review by javiercn — APPROVED** [review]

**Comment by SteveSandersonMS** [comment]
@Pilchie Can this be approved for RC2?

I'm aware of the build failure - it's happening for all PRs.

**Comment by SteveSandersonMS** [comment]
@javiercn I've repurposed this PR to include, in addition to what was there before, various other test fixes. You may want to re-review as there's quite a bit more here now :)

**Comment by javiercn** [comment]
@SteveSandersonMS re-reviewed. :shipit:

**Comment by Pilchie** [comment]
Approved for .NET 5 RC2.

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT Ready to merge.

**Pull request merged**
