### PR TITLE
Remove Microsoft.Components.Web.Extensions

### PR DESCRIPTION
**Pull request by pranavkm**
The package was marked as non-shipping but we continued to build and test it. This change
removes it. A copy of this code exists in asplabs so all is not lost.

### CODE REVIEW

**Review by HaoK — APPROVED** [review]

**Comment by pranavkm** [comment]
@dotnet/aspnet-build we could port this change this from the 5.0 branch to reduce build times and remove some tests that are currently quarantined. Could I get this in to the rc2 branch?

**Comment by dougbu** [comment]
@pranavkm I don't see why not but I'm tagging @Pilchie since this removal isn't pure infrastructure. Believe the deadline for RC2 changes is COB tomorrow, preferably earlier (every change means new dependency flow from that point in the graph).

**Comment by Pilchie** [comment]
I'm generally supportive. What are the changes to the .js files about?

**Comment by pranavkm** [comment]
The JS files are checked-in build outputs of our TS files. The ones in master are incorrect (looks like a bad merge).

**Comment by pranavkm** [comment]
Let me prep a rc2 change. The JS changes shouldn't be part oif it.

**Pull request merged**
