### PR TITLE
Report Java client test results

### PR DESCRIPTION
**Pull request by mikaelm12**
Testing on AzDo

### CODE REVIEW

**Comment by jkotalik** [comment]
Not sure why the test run failed (current test run was aborted), but I just enabled verbose xunit logs for Kestrel. This should help with the failure you just hit.

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=149280

**Comment by dougbu** [comment]
Have seen similar test run failures lacking `[fail]` or reported test failures in other builds. No solid idea on the root cause; just a mild suspicion we or VSTest have a general issue with either writing or parsing .trx files.

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

I've triaged the above build.

**Comment by mikaelm12** [comment]
SignalRJavaClientTestReporting

**Comment by BrennanConroy** [comment]
What does a failure look like?

**Comment by mikaelm12** [comment]
I'd imagine like the other failures. Unless you want me to re-run with a forced failure, and then re-run again to merge.

**Comment by BrennanConroy** [comment]
I want to know if a failure shows enough info to diagnose a failure. Because you aren't putting the java test logs in the artifacts.

**Comment by BrennanConroy** [comment]
You could make a new draft PR with a new branch and force a failure, then if it looks good you don't have to rebuild this PR

**Review by natemcmaster — APPROVED** [review]

**Comment by mikaelm12** [comment]
Okay, I'll open a new draft

**Comment by mikaelm12** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=150261&view=logs&jobId=a89a2a8c-213d-51e6-fe71-933481fa439c

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

I've triaged the above build.

**Comment by mikaelm12** [comment]
Forced 3 tests to fail and this is what the error report looks like
SignalRTestReport

**Pull request merged**
