### PR TITLE
Ensure PlatformBenchmark is compiled for .NET Core 3.0

### PR DESCRIPTION
**Pull request by benaadams**
/cc @sebastienros not sure you use it on earlier frameworks?

### CODE REVIEW

**Review by analogrelay — APPROVED** [review]
LGTM, we'll merge this after the preview 5 branching.

**Comment by anurse** [comment]
Whoops, this one fell through the cracks. I learned my lesson though. Respinning the build and will merge after that's done.

**Comment by anurse** [comment]
Though @sebastienros I'd appreciate a confirm from you that this is OK.

**Comment by sebastienros** [comment]
The build doesn't handle this project. But you need it to see enable the merge button 😒 
We only run this one on 3.0. TE has its own version for 2.2.

**Comment by anurse** [comment]
Soooo, OK with you?

**Pull request merged**
