### PR TITLE
Fixup OpenAPI displayed param type when using TryParse

### PR DESCRIPTION
**Pull request by BrennanConroy**
Backport of https://github.com/dotnet/aspnetcore/pull/36526

### CODE REVIEW

**Review by captainsafia — APPROVED** [review]

**Comment by captainsafia** [comment]
@BrennanConroy This needs a rebase to make it in before the branching deadline.

**Comment by BrennanConroy** [comment]
> This needs a rebase

Yep, working on it.

> make it in before the branching deadline

**Comment by BrennanConroy** [comment]
In 6.0 via rc2->6.0 merge

**Pull request closed without merging**
