### PR TITLE
Update branding to 3.1.0-preview2

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Comment by dougbu** [comment]
Blocked just 'til we branch

**Comment by dougbu** [comment]
:up::date: to include dotnet/core-eng#7970 workaround
- have not yet worked around dotnet/arcade#4021

**Comment by dougbu** [comment]
Success modulo a missing `New-Item -ItemType Directory .\.tools\ -ErrorAction SilentlyContinue` and a macOS agent disappearing ❕❕

**Review by Pilchie — APPROVED** [review]

**Pull request merged**
