### PR TITLE
Re-structure Blazor Project Templates

### LINKED ISSUE #51103: Blazor WebAssembly Template Project Structure Is Inconsistent With Blazor Web App Template In .NET 8 RC1
## Summary

In the new **Blazor Web App** template all the Razor Components including **Pages**, **Layouts** are moved to the top level **Components** directory. However the **Blazor WebAssembly** template still has the old structure (Separate top level **Pages** directory, **Layouts** in the top level **Shared** directory etc.). I don't know if I like to put everything on the **Components** directory. But having to deal with two different structure confuses me.

## Motivation and goals

- Update the **Blazor WebAssembly** template structure to remove confusion.

- Maybe improve the **Blazor Web App** template further.

## In scope

I have two separate **Blazor Web App** and **Blazor Web Assembly**  project.

## Out of scope

I'm not sure.

## Risks / unknowns

Not sure.

## Examples

All of the Blazor template structure should be the same.

# Detailed design

I have come to know about @danroth27 and @SteveSandersonMS's case of the **Shared** folder but I would like to propose using the top level directory to be **Views** instead of **Components** as components sound too generic and needs additional context. 

My proposed project structure for both **Blazor Web App** and **Blazor WebAssembly** looks like:

Screenshot 2023-10-03 at 8 43 56 PM

**Explanation**: 
- The top level **Views** directory contains all the view/UI codes and directly contains the **_Imports.razor**, **App.razor** and **Routes.razor** files.
- The second-level **Components** directory contains all the reusable UI components.
- The second-level **Layouts** (Pluralized because I think one project can have multiple layout) directory contains all the layout files.
- The second-level **Pages** directory contains all the routable components/pages.

### PR DESCRIPTION
**Pull request by smjxpro**
# Re-structured Blazor Project Templates

- [.] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [.] You've included unit or integration tests for your change, where applicable.
- [.] You've included inline docs for your change, where applicable.
- [.] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Re-structured Blazor project templates to improve maintainability and remove confusion.

## Description

Renamed the **Components** directory to **Views**, **Layout** to **Layouts** and added a **Components** directory inside the new **Views** directory which will contain re-usable and non-routable components.
Fixes #51103

### CODE REVIEW

**Comment by smjxpro** [comment]
@dotnet-policy-service agree

**Comment by smjxpro** [comment]
> @smjxpro please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@dotnet-policy-service agree

**Comment by mkArtakMSFT** [comment]
Thanks for your PR, @smjxpro.

@SteveSandersonMS this is similar to the other template change, so I'll leave it up to you to decide whether we take this or not. Thanks!

**Comment by smjxpro** [comment]
> Thanks for your PR, @smjxpro.
> 
> @SteveSandersonMS this is similar to the other template change, so I'll leave it up to you to decide whether we take this or not. Thanks!

Besides renaming and re-organizing structures, the **CounterComponent.razor**
in the **Views/Components** directory in combination with the **Counter.razor** page in the **Views/Pages** directory demonstrates passing parameters to child components, which I think very useful for a starter.

**Comment by SteveSandersonMS** [comment]
Thanks for proposing this, @smjxpro. However I'm afraid we're not really looking for these kinds of changes to the project template at the moment.

The file structure we have in place is deliberate and we don't have a plan to change the terminology in these kinds of ways (e.g., using the term `Views`). I do appreciate that the term `Components` could be seen as "generic" (as you mention in your issue), however it's consistent with how we use that term for Razor components much more broadly, and so is well understood.

Currently I'd recommend closing the PR since we're not planning to make such changes, especially not for .NET 8 as it's too late and we're very strongly in need of minimizing churn at this stage. For .NET 9 we want to make some broader redesigns for the templates, and might even reconsider the [unified/single-project option](https://github.com/dotnet/aspnetcore/issues/49079), so at that point we would definitely be open to your input on the structure.

**Comment by smjxpro** [comment]
Understood that the term **Component** is well understood in Razor (i.e. all files with _.razor_ extension belong to the Components category), however I think it gets confusing when the project has a bunch of re-usable components.

Sure we can use a component library project  (one would do that or whatever structure they would prefer anyway) but the starter project template's purpose may be to give a good start and give a head start about the terminologies (i.e. routable components/pages, re-usable components, layout components etc.)

It would be nice if we have a common project structure for Blazor. And I'm looking forward to it.

**Pull request closed without merging**
