### PR TITLE
Prepare to build the 2.1.7 patch

### PR DESCRIPTION
**Pull request by natemcmaster**
Prepare the repo to build the 2.1.7 patch.

Depends on 

* https://github.com/aspnet/Templating/pull/824
* https://github.com/aspnet/Scaffolding/pull/924

### CODE REVIEW

**Comment by jkotalik** [comment]
@natemcmaster will 2.1.7 be open after this is merged?

**Comment by natemcmaster** [comment]
Yes.

**Comment by natemcmaster** [comment]
Also depends on https://github.com/aspnet/MetaPackages/pull/296

**Review by muratg — APPROVED** [review]

**Comment by muratg** [comment]
Thanks Nate!

**Pull request merged**
