### PR TITLE
Don't pack .version file in SiteExtensions pkg

### LINKED ISSUE #22247: Fix warning "File 'F:\workspace_work\1\s\artifacts\obj\RedistSharedFx.Layout\Release\win-x64\shared\Microsoft.AspNetCore.App\5.0.0-preview.6.20275.3.version' was not added to the package."
Part of https://github.com/dotnet/aspnetcore/issues/22240

Happens during the SiteExtension build. Full text below:

> F:\workspace\_work\1\s\.dotnet\sdk\5.0.100-preview.5.20258.4\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): warning NU5119: File 'F:\workspace\_work\1\s\artifacts\obj\RedistSharedFx.Layout\Release\win-x64\shared\Microsoft.AspNetCore.App\5.0.0-preview.6.20275.3\.version' was not added to the package. Files and folders starting with '.' or ending with '.nupkg' are excluded by default. To include this file, use -NoDefaultExcludes from the commandline [F:\workspace\_work\1\s\src\SiteExtensions\Runtime\Microsoft.AspNetCore.Runtime.SiteExtension.pkgproj]

> F:\workspace\_work\1\s\.dotnet\sdk\5.0.100-preview.5.20258.4\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): warning NU5119: File 'F:\workspace\_work\1\s\artifacts\obj\RedistSharedFx.Layout\Release\win-x64\shared\Microsoft.NETCore.App\5.0.0-preview.6.20271.10\.version' was not added to the package. Files and folders starting with '.' or ending with '.nupkg' are excluded by default. To include this file, use -NoDefaultExcludes from the commandline [F:\workspace\_work\1\s\src\SiteExtensions\Runtime\Microsoft.AspNetCore.Runtime.SiteExtension.pkgproj]

### PR DESCRIPTION
**Pull request by wtgodbe**
Attempts to resolve https://github.com/dotnet/aspnetcore/issues/22247

Internal build: https://dev.azure.com/dnceng/internal/_build/results?buildId=667121&view=results

### CODE REVIEW

**Comment by wtgodbe** [comment]
Internal build doesn't have the 2 warnings

**Review by dougbu — APPROVED** [review]
This works but I defer to @BrennanConroy and @jkotalik on all things site extensions. Please confirm w/ them that we don't need the .version file.

**Comment by wtgodbe** [comment]
ping @jkotalik @BrennanConroy

**Review by BrennanConroy — APPROVED** [review]

**Comment by jkotalik** [comment]
Thanks for doing it @wtgodbe

**Pull request merged**
