### PR TITLE
Indicates that SaveTokens is not supported for WsFederation

### PR DESCRIPTION
**Pull request by Kahbazi**
#7955

### CODE REVIEW

**Comment by Tratcher** [comment]
Does this really prevent the base class intellisense from showing up?

The reference assemblies need to be updated because you added public API.
```
error : Generated code is not up to date in src/Security/Authentication/WsFederation/ref/Microsoft.AspNetCore.Authentication.WsFederation.netcoreapp3.0.cs. You might need to regenerate the reference assemblies or project list (see docs/ReferenceAssemblies.md ...)
```

**Comment by anurse** [comment]
> Does this really prevent the base class intellisense from showing up?

I believe it will as long as the variable you are dereferencing is actually of the derived type (`WsFederationOptions`)

@Kahbazi could you verify this and post a quick screenshot?

**Comment by Kahbazi** [comment]
It's working!
image

**Comment by Tratcher** [comment]
Nice. And if you type in SaveTokens manually and hover over it does the right test come up?

**Comment by Kahbazi** [comment]
yep
image

**Review by Tratcher — APPROVED** [review]

**Review by analogrelay — APPROVED** [review]
Very nice! Thanks @Kahbazi ! We should be able to take it from here.

**Comment by PinpointTownes** [comment]
Why not implementing proper `SaveTokens` support rather than hiding the config' property? 😄

**Comment by Tratcher** [comment]
@PinpointTownes What would you save? I was under the impression that the wsfed token wasn't useful beyond sign-in.

**Comment by anurse** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=210299

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2620

**Comment by Tratcher** [comment]
@PinpointTownes Reading through the prior thread (https://github.com/aspnet/Security/issues/1716#issuecomment-384528952) it ended because the tokens were too large and caused the cookie to hit header size limits.

I'm merging this change for now and we can revisit if there's enough interest in those tokens.

**Pull request merged**
