### PR TITLE
Merge/release/3.1 to master

### PR DESCRIPTION
**Pull request by wtgodbe**
Opening in favor of https://github.com/aspnet/AspNetCore/pull/14779, where the git history had become muddled.

This PR merges commits made on release/3.1 by the following committers:

@dougbu
@JamesNK
@wtgodbe
@dotnet-maestro[bot]
@pranavkm
@mkArtakMSFT
@Pilchie

### CODE REVIEW

**Comment by dougbu** [comment]
@wtgodbe please ping when this is building and ready to review.

**Comment by wtgodbe** [comment]
> &#x2F;home&#x2F;vsts&#x2F;work&#x2F;1&#x2F;s&#x2F;eng&#x2F;AfterSolutionBuild.targets(14,5): error MSB4018: The &quot;RepoTasks.RemoveSharedFrameworkDependencies&quot; task failed unexpectedly. [&#x2F;home&#x2F;vsts&#x2F;work&#x2F;1&#x2F;s&#x2F;.packages&#x2F;microsoft.dotnet.arcade.sdk&#x2F;1.0.0-beta.19510.3&#x2F;tools&#x2F;AfterSolutionBuild.proj]‌
/home/vsts/work/1/s/eng/AfterSolutionBuild.targets(14,5): error MSB4018: System.IO.FileLoadException: Could not load file or assembly 'NuGet.Packaging, Version=5.3.0.4, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (0x80131621) [/home/vsts/work/1/s/.packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19510.3/tools/AfterSolutionBuild.proj]
/home/vsts/work/1/s/eng/AfterSolutionBuild.targets(14,5): error MSB4018: File name: 'NuGet.Packaging, Version=5.3.0.4, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [/home/vsts/work/1/s/.packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19510.3/tools/AfterSolutionBuild.proj]
/home/vsts/work/1/s/eng/AfterSolutionBuild.targets(14,5): error MSB4018:    at RepoTasks.RemoveSharedFrameworkDependencies.Execute() [/home/vsts/work/1/s/.packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19510.3/tools/AfterSolutionBuild.proj]
/home/vsts/work/1/s/eng/AfterSolutionBuild.targets(14,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/home/vsts/work/1/s/.packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19510.3/tools/AfterSolutionBuild.proj]
/home/vsts/work/1/s/eng/AfterSolutionBuild.targets(14,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/home/vsts/work/1/s/.packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19510.3/tools/AfterSolutionBuild.proj]
/home/vsts/work/1/s/eng/AfterSolutionBuild.targets(14,5): error MSB4018:  [/home/vsts/work/1/s/.packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19510.3/tools/AfterSolutionBuild.proj]
/home/vsts/work/1/s/eng/AfterSolutionBuild.targets(14,5): error MSB4018:  [/home/vsts/work/1/s/.packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19510.3/tools/AfterSolutionBuild.proj]

Will fix when I can

**Comment by dougbu** [comment]
Looks like the test issue hasn't changed:
```
/home/vsts/work/1/s/eng/AfterSolutionBuild.targets(14,5): error MSB4018: The "RepoTasks.RemoveSharedFrameworkDependencies" task failed unexpectedly. [/home/vsts/work/1/s/.packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19510.3/tools/AfterSolutionBuild.proj]
/home/vsts/work/1/s/eng/AfterSolutionBuild.targets(14,5): error MSB4018: System.IO.FileLoadException: Could not load file or assembly 'NuGet.Packaging, Version=5.3.0.4, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (0x80131621) [/home/vsts/work/1/s/.packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19510.3/tools/AfterSolutionBuild.proj]
/home/vsts/work/1/s/eng/AfterSolutionBuild.targets(14,5): error MSB4018: File name: 'NuGet.Packaging, Version=5.3.0.4, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [/home/vsts/work/1/s/.packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19510.3/tools/AfterSolutionBuild.proj]
/home/vsts/work/1/s/eng/AfterSolutionBuild.targets(14,5): error MSB4018:    at RepoTasks.RemoveSharedFrameworkDependencies.Execute() [/home/vsts/work/1/s/.packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19510.3/tools/AfterSolutionBuild.proj]
/home/vsts/work/1/s/eng/AfterSolutionBuild.targets(14,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/home/vsts/work/1/s/.packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19510.3/tools/AfterSolutionBuild.proj]
/home/vsts/work/1/s/eng/AfterSolutionBuild.targets(14,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/home/vsts/work/1/s/.packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19510.3/tools/AfterSolutionBuild.proj]
/home/vsts/work/1/s/eng/AfterSolutionBuild.targets(14,5): error MSB4018:  [/home/vsts/work/1/s/.packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19510.3/tools/AfterSolutionBuild.proj]
/home/vsts/work/1/s/eng/AfterSolutionBuild.targets(14,5): error MSB4018:  [/home/vsts/work/1/s/.packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19510.3/tools/AfterSolutionBuild.proj]
##[error]eng/AfterSolutionBuild.targets(14,5): error MSB4018: The "RepoTasks.RemoveSharedFrameworkDependencies" task failed unexpectedly.
System.IO.FileLoadException: Could not load file or assembly 'NuGet.Packaging, Version=5.3.0.4, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (0x80131621)
File name: 'NuGet.Packaging, Version=5.3.0.4, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at RepoTasks.RemoveSharedFrameworkDependencies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

@mmitche @riarenas @tmat @JohnTortugo does the above error look familiar to any of you? It appears the latest 3.0 Arcade SDK isn't getting along well with a repo task we have at https://github.com/aspnet/AspNetCore/blob/master/eng/tools/RepoTasks/RemoveSharedFrameworkDependencies.cs (hitting different issues that seem Arcade-related in #15192, where we're upgrading to the latest Arcade SDK).

**Comment by dougbu** [comment]
For the AfterSolutionBuild.targets failure to load NuGet.Packaging, I suspect something broke with the NuGet.Build.Tasks update (to 5.3.0) we did in 'release/3.1' but am not sure why the Linux-specific problem didn't show up there. Nothing evident in https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/release-notes/NuGet-5.3.md either.

@rrelyea are we now doing something wrong in https://github.com/aspnet/AspNetCore/blob/master/eng/tools/RepoTasks/RemoveSharedFrameworkDependencies.cs ? Other than the target framework, our RepoTasks project is unchanged between 'release/3.1' and 'master'.

**Comment by mmitche** [comment]
Doesn't look familiar to me.

**Comment by rrelyea** [comment]
@zivkan - can you please engage on the question above that @dougbu asked me.

**Comment by zivkan** [comment]
@dougbu I don't think any of the NuGet APIs changed, but the failures are saying:

> System.IO.FileLoadException: Could not load file or assembly 'NuGet.Packaging, Version=5.3.0.4, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file.

so it sounds like an assembly versioning issue. I see in the PR that the version of NuGet was updated to 5.3.0 in `eng/tools/RepoTasks/RepoTasks.csproj`. Are you able to check the test's output directory, or deps file, to see what version of NuGet assemblies it's using at runtime? It sounds like it's using a different version at runtime than what was compiled against.

**Comment by dougbu** [comment]
I'll look more but can't understand how a ref / impl difference would show up only on Linux. There's no GAC there to mess things up. But, I'll test more and fire up a Linux VM&hellip;

**Comment by pranavkm** [comment]
The PR is merged, but a quick update to understand why the PR was failing: the version of NuGet's binaries in the SDK was older than the one RepoTasks was referencing. Changing it to an older version unblocked this: https://github.com/aspnet/AspNetCore/pull/15084/commits/a3349381d345d256ebe4edc3f8122a7201ff2c98

**Pull request merged**
