### PR TITLE
Update reconnection E2E tests

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
I was too hasty when merging #12361. There was still a commit to go for updating the E2E tests. It's here now.

### CODE REVIEW

**Review by javiercn — APPROVED** [review]
I assume this just fix the test.

**Comment by SteveSandersonMS** [comment]
That’s right.

**Review by pranavkm — APPROVED** [review]

**Comment by rynowak** [comment]
Merging this because it's currently 4:18am in the UK (I assume) and steve is a asleep (or at a warehouse rave)

**Comment by SteveSandersonMS** [comment]
Yes, another warehouse rave as usual. Thanks for merging.

**Pull request merged**
