### PR TITLE
Revert "Use 1es-windows-2019 again"

### PR DESCRIPTION
**Pull request by wtgodbe**
Reverts dotnet/aspnetcore#41547

### CODE REVIEW

**Comment by dougbu** [comment]
What's going wrong at the moment @wtgodbe❔

**Review by dougbu — APPROVED** [review]
Saw offline conversation. Are you running any internal validation❔

**Comment by wtgodbe** [comment]
Here's a test build, but it likely won't try to install Microbuild either: https://dev.azure.com/dnceng/internal/_build/results?buildId=1760563&view=results

**Comment by wtgodbe** [comment]
Actually it did try (and succeed) to install Microbuild, not sure why the other internal build didn't

**Comment by dougbu** [comment]
We were testing different things because our prior problems w/ the `Build.Server.Amd64.VS2019` image was missing a native VS component while the issue w/ `1es-windows-2019` was the cert problem.

The difference was probably my test being an internal PR (https://dev.azure.com/dnceng/internal/_git/dotnet-aspnetcore/pullrequest/22742) and yours being a manual run. Arcade's job.yml skips the `Install MicroBuild plugin` step for all PRs.

**Pull request merged**
