### PR TITLE
Fix test discovery

### PR DESCRIPTION
**Pull request by BrennanConroy**

### CODE REVIEW

**Review by halter73 — APPROVED** [review]

**Comment by jkotalik** [comment]
I don't think that fixed it. https://mc.dot.net/#/user/aspnetcore/pr~2Faspnet~2Faspnetcore/ci/20190304.47/workItem/Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests-netcoreapp3.0/wilogs

Still failed with the same error.

**Comment by BrennanConroy** [comment]
It was actually a slightly different error

**Comment by BrennanConroy** [comment]
Ok, now it's fixed

**Comment by BrennanConroy** [comment]
The 2 test failures in Helix already have PRs to skip them

**Pull request merged**
