### PR TITLE
Updating KVM on the home/dev repo

### PR DESCRIPTION
**Pull request by Praburaj**
@suhasj This change is for dev branch. I'm sending out another PR for the master branch. 

We can close a few bugs with these merges.

### CODE REVIEW

**Comment by davidfowl** [comment]
Can't we automate this thing once and for all?

**Comment by Praburaj** [comment]
@pranavkm I remember there were some discussions around this. Not sure what we decided on that though.

**Comment by pranavkm** [comment]
We never did come to a consensus on what needs to be done.

**Comment by suhasj** [comment]
:shipit:

**Pull request merged**
