### PR TITLE
Update branding to 5.0.15

### PR DESCRIPTION
**Pull request by vseanreesermsft**

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Comment by dougbu** [comment]
Seems like the Razor.IntegrationTests suite remains flaky on the release/5.0 branch. Could anything be back-ported here to improve reliability❔ (@rafikiassumani-msft @mkArtakMSFT @adityamandaleeka who owns Razor in servicing, specifically bits like this that we've moved elsewhere❔)

From From first run of [build 20220201.28](https://dev.azure.com/dnceng/public/_build/results?buildId=1585745&view=results):
<details>
<summary>Microsoft.NET.Sdk.Razor.IntegrationTests_net5.0_x64.log</summary>

``` text
xUnit.net Console Runner v2.4.1 (64-bit .NET 5.0.13)
  Discovering: Microsoft.NET.Sdk.Razor.IntegrationTests
  Discovered:  Microsoft.NET.Sdk.Razor.IntegrationTests
  Starting:    Microsoft.NET.Sdk.Razor.IntegrationTests
    Build_Components_WithDesktopMSBuild_Works [SKIP]
      https://github.com/dotnet/aspnetcore/issues/24427
Unhandled exception. System.AggregateException: One or more errors occurred. (Shutting down the build server at pipe 4e8394ad-54b2-47a1-b455-91fa89cbf6e6 took longer than expected.
Output: .)
 ---> System.TimeoutException: Shutting down the build server at pipe 4e8394ad-54b2-47a1-b455-91fa89cbf6e6 took longer than expected.
Output: .
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.BuildServerTestFixtureBase.<>c__DisplayClass5_0.<Dispose>b__0() in /_/src/Razor/Microsoft.NET.Sdk.Razor/integrationtests/BuildServerTestFixtureBase.cs:line 36
   at System.Threading.CancellationToken.<>c.<.cctor>b__26_0(Object obj)
   at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.CancellationTokenSource.CallbackNode.ExecuteCallback()
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.<>c.<.cctor>b__56_0(Object obj)
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
=== COMMAND LINE ===
"D:\a\_work\1\s\.dotnet\dotnet.exe" exec --depsfile "D:\a\_work\1\s\artifacts\bin\Microsoft.NET.Sdk.Razor.IntegrationTests\Release\net5.0\Microsoft.NET.Sdk.Razor.IntegrationTests.deps.json" --runtimeconfig "D:\a\_work\1\s\artifacts\bin\Microsoft.NET.Sdk.Razor.IntegrationTests\Release\net5.0\Microsoft.NET.Sdk.Razor.IntegrationTests.runtimeconfig.json"  "D:\a\_work\1\s\.packages\xunit.runner.console/2.4.1/tools/netcoreapp2.0/xunit.console.dll" "D:\a\_work\1\s\artifacts\bin\Microsoft.NET.Sdk.Razor.IntegrationTests\Release\net5.0\Microsoft.NET.Sdk.Razor.IntegrationTests.dll" -noautoreporters -xml "D:\a\_work\1\s\artifacts\TestResults\Release\Microsoft.NET.Sdk.Razor.IntegrationTests_net5.0_x64.xml" -html "D:\a\_work\1\s\artifacts\TestResults\Release\Microsoft.NET.Sdk.Razor.IntegrationTests_net5.0_x64.html" -notrait "Quarantined=true"  -nocolor > "D:\a\_work\1\s\artifacts\log\Release\Microsoft.NET.Sdk.Razor.IntegrationTests_net5.0_x64.log" 2>&1
```
</summary>

I also see JS and xUnit results were published in that failing job but nothing shows up in the Tests tab yet. Thoughts on why that may happen @wtgodbe❔ (I'm hopeful information will be visible for those on-build-agent tests after the Helix job completes.)

**Comment by wtgodbe** [comment]
> I also see JS and xUnit results were published in that failing job but nothing shows up in the Tests tab yet. Thoughts on why that may happen @wtgodbe❔

I'm not sure, the pipeline seems to be using the `Publish test results` task in the normal way, but the link it gives to the test results page gives a 404:

https://dev.azure.com/dnceng/public/_build/results?buildId=1585745&view=logs&j=0f60fc7e-fa11-55bb-be72-9b3827ae14af&s=ff05ad62-bb9a-53b6-ce9f-72f329a63e7c&t=59e6970e-758d-59f0-7d6f-1753c59c4195&l=62

@dotnet/dnceng are we doing something wrong?

In any case, merging this as it's green now (going to merge-commit to preserve Brennan/Hao's commits)

**Comment by adiaaida** [comment]
I don't know about the link, but that task is meant to publish test results to the test tab: https://dev.azure.com/dnceng/public/_build/results?buildId=1585745&view=ms.vss-test-web.build-test-results-tab

**Comment by adiaaida** [comment]
@wtgodbe I've confirmed that the test results have been uploaded to the test tab (but it takes forever to load because you have so many tests. You may want to try using the filtering to view whichever tests you are interested in). We believe the 404 issue to be an internal AzDO issue, and have opened an IcM with them to get it looked at (we see the same 404 in other repo's ci runs as well).

**Pull request merged**
