### PR TITLE
[release/8.0] Update SDK

### PR DESCRIPTION
**Pull request by captainsafia**

### CODE REVIEW

**Comment by halter73** [comment]
I think you're also going to need to cherry-pick my CodeGen.proj change from the other SDK update or you'll get errors due to TrimmableProjects.props being generated incorrectly. [`71bb235` (#49911)](https://github.com/dotnet/aspnetcore/pull/49911/commits/71bb235aec0f99954929b345fc1024be3cd36f9b)

**Comment by captainsafia** [comment]
> I think you're also going to need to cherry-pick my CodeGen.proj change from the other SDK update or you'll get errors due to TrimmableProjects.props being generated incorrectly. [`71bb235` (#49911)](https://github.com/dotnet/aspnetcore/pull/49911/commits/71bb235aec0f99954929b345fc1024be3cd36f9b)

Ah TY! I was wondering why the original PR contained the change (the comment wasn't super clear) and figured I would find out the hard way 😅

**Comment by captainsafia** [comment]
@mitchdenny Should be good to merge!

**Review by mitchdenny — APPROVED** [review]

**Comment by SteveSandersonMS** [comment]
Since this SDK update I'm not able to build locally:

```
Build FAILED.

C:\path\to\aspnetcore\Directory.Build.props(95,31): error MSB4242: SDK Resolver Failure: "The SDK resolver "Microsoft.D
otNet.MSBuildSdkResolver" failed while attempting to resolve the SDK "Microsoft.DotNet.Arcade.Sdk". Exception: "Microsoft.
NET.Sdk.WorkloadManifestReader.WorkloadManifestCompositionException: Manifest provider Microsoft.NET.Sdk.WorkloadManifestR
eader.SdkDirectoryWorkloadManifestProvider returned a duplicate manifest ID '16.4.8646-net8-p6' [C:\path\to\aspnetcore\
.dotnet\sdk-manifests\8.0.100-preview.6\microsoft.net.sdk.maccatalyst\16.4.8646-net8-p6\WorkloadManifest.json] that confli
cts with existing manifest [C:\path\to\aspnetcore\.dotnet\sdk-manifests\8.0.100-preview.6\microsoft.net.sdk.ios\16.4.86
46-net8-p6\WorkloadManifest.json] [C:\path\to\aspnetcore\src\Servers\IIS\AspNetCoreModuleV2\AspNetCore\AspNetCore.vcxpr
oj]
C:\path\to\aspnetcore\Directory.Build.props(95,31): error MSB4242:    at Microsoft.NET.Sdk.WorkloadManifestReader.Workl
oadResolver.LoadManifestsFromProvider(IWorkloadManifestProvider manifestProvider) [C:\path\to\aspnetcore\src\Servers\II
S\AspNetCoreModuleV2\AspNetCore\AspNetCore.vcxproj]
C:\path\to\aspnetcore\Directory.Build.props(95,31): error MSB4242:    at Microsoft.NET.Sdk.WorkloadManifestReader.Workl
oadResolver.Create(IWorkloadManifestProvider manifestProvider, String dotnetRootPath, String sdkVersion, String userProfil
eDir) [C:\path\to\aspnetcore\src\Servers\IIS\AspNetCoreModuleV2\AspNetCore\AspNetCore.vcxproj]
C:\path\to\aspnetcore\Directory.Build.props(95,31): error MSB4242:    at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.C
achingWorkloadResolver.Resolve(String sdkReferenceName, String dotnetRootPath, String sdkVersion, String userProfileDir, S
tring globalJsonPath) [C:\path\to\aspnetcore\src\Servers\IIS\AspNetCoreModuleV2\AspNetCore\AspNetCore.vcxproj]
C:\path\to\aspnetcore\Directory.Build.props(95,31): error MSB4242:    at Microsoft.DotNet.MSBuildSdkResolver.DotNetMSBu
ildSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext context, SdkResultFactory factory) [C:\path\to\asp
netcore\src\Servers\IIS\AspNetCoreModuleV2\AspNetCore\AspNetCore.vcxproj]
```

This is after deleting `.dotnet` and then running `build.cmd` in `src\Components`. I also tried a full `git clean -xdf` and even set up a new local working copy in a new directory, but get the same result. Could you confirm it builds locally for you?

I'm not blocked currently: after reverting to the previous commit 03e7512 it builds.

**Comment by captainsafia** [comment]
Responding to this here for posterity since we discussed the resolution in a separate thread. With this change, VS 17.8+ is required to work on the repo.

**Pull request merged**
