### PR TITLE
Revert "[main] Update dependencies from dotnet/runtime"

### PR DESCRIPTION
**Pull request by javiercn**
Reverts dotnet/aspnetcore#49075

This is breaking the blazor E2E tests. Filed issue to track https://github.com/dotnet/runtime/issues/88250

### CODE REVIEW

**Comment by Tratcher** [comment]
What's the actual policy around components-e2e? It's not considered required because it's too flaky. But then why would we revert for a failure in a non-required pipeline?

**Comment by javiercn** [comment]
@Tratcher I don't think that's the case.

We've done a bunch of work on stability with retries and it has been stable for quite a while, @SteveSandersonMS do you know if/why this is not required?

**Comment by Tratcher** [comment]
Given there are only 6 tests affected and we understand the issue, we should skip those tests rather than reverting the runtime. Rolling back and pausing runtime updates affects other workflows and means we don't find other breaks in a timely manner.

**Review by Tratcher — CHANGES_REQUESTED** [review]
Suggest skipping the affected tests instead. https://github.com/dotnet/aspnetcore/issues/49127 https://github.com/dotnet/aspnetcore/pull/49109

**Comment by maraf** [comment]
The issue is resolved. Next flow from runtime should fix components-e2e tests

**Pull request closed without merging**
