### PR TITLE
Add 'private' access modifier to RC/Blazor templates

### PR DESCRIPTION
**Pull request by guardrex**
* Templates only.
* Not test assets or MVC. (Can add if you wish.)

Sister PR in docs :point_right: https://github.com/aspnet/AspNetCore.Docs/pull/11897

cc: @danroth27 @SteveSandersonMS

### CODE REVIEW

**Comment by ryanbrandenburg** [comment]
Removing myself as a reviewer as this is really just a mater of Blazor best practices, and I don't have much background on that.

**Comment by guardrex** [comment]
Note: https://github.com/aspnet/AspNetCore.Docs/pull/11897#issuecomment-481045436

Do you also want `[Parameter]` on a line above the property in all cases on this PR? If so, I'll add it here.

**Comment by danroth27** [comment]
> Do you also want `[Parameter]` on a line above the property in all cases on this PR? If so, I'll add it here.

Yup, I think we should be consistent with our C# coding guidelines.

**Comment by guardrex** [comment]
Will work it now (just wrapped up the draft on https://github.com/aspnet/AspNetCore.Docs/pull/11924).

**Comment by StevenTCramer** [comment]
Should `dotnet_style_require_accessibility_modifiers` be added to `.editorconfig` ?

**Comment by SteveSandersonMS** [comment]
This looks good to me. Sorry @guardrex that we took forever to merge it.

If you'd be able to rebase this on `master` I would merge it right after.

**Comment by guardrex** [comment]
I'll try by EOD ... but I'm buried in **_Razor syntax_**, so I might brain fry 😵 by EOD and get to it on Friday morning.

**Comment by guardrex** [comment]
Stand-by until I give the signal ... I have a few more conflicts to fix up.

**Comment by guardrex** [comment]
Moved to https://github.com/aspnet/AspNetCore/pull/12596.

**Pull request closed without merging**
