### PR TITLE
Change nint -> IntPtr

### PR DESCRIPTION
**Pull request by davidfowl**
- Forgot to change this back as part of function pointer changes

### CODE REVIEW

**Comment by En3Tho** [comment]
@davidfowl Can I ask you why this change is needed? To explicitly indicate that callback is a some kind of pointer? Just to know.

**Comment by davidfowl** [comment]
Which change? Using intptr instead of nint? Or using function pointers?

**Comment by En3Tho** [comment]
@davidfowl nint -> IntPtr change
 The one which this pr is addressing

**Comment by davidfowl** [comment]
I don't think it changes anything. I'm just reverting it to what it used to be because there's no advantage to using nint

**Comment by En3Tho** [comment]
I see. Thanks.

**Review by JamesNK — APPROVED** [review]

**Pull request merged**
