### PR TITLE
blazor.boot.json - don't set physicalpath

### PR DESCRIPTION
**Pull request by nicksull123**
#10068

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
Thanks, @nicksull123!

I agree it shouldn't be hardcoded to `"/_framework/blazor.boot.json"`. What I'm less sure of is whether it makes a different whether it has the value `null` or whether we pass in a value for `PhysicalPath` to the constructor.

@javiercn You have a lot of background knowledge in this area. Do you know whether it makes a difference to the static files middleware whether a given `IFileInfo` has a valid `PhysicalPath` or not?

**Comment by javiercn** [comment]
Seems like a valid concern to me. @Tratcher for confirmation.

**Review by javiercn — APPROVED** [review]

**Review by Tratcher — APPROVED** [review]
Null is the correct value here. PhysicalPath must either be a valid path on disk or null.

**Comment by SteveSandersonMS** [comment]
Thanks for confirming, @Tratcher!

Also thanks for the contribution, @nicksull123! It's now merged.

**Pull request merged**
