### PR TITLE
Revert breaking KestrelServer ctor change

### PR DESCRIPTION
**Pull request by halter73**
3.1 ctor:

https://github.com/dotnet/aspnetcore/blob/c75b3f7a2fb9fe21fd96c93c070fdfa88a2fbe97/src/Servers/Kestrel/Core/src/KestrelServer.cs#L32

Example of working around breaking change:

https://github.com/davidfowl/BedrockFramework/commit/aef398815f7cf100ab18c883603b3cdf47a95a74#diff-b117c6945defc7c70c329af1f9a0671bL55

### CODE REVIEW

**Comment by davidfowl** [comment]
This doesn’t break http3 right?

**Comment by halter73** [comment]
This does not break HTTP/3. We register [KestrelServerImpl](https://github.com/dotnet/aspnetcore/blob/40cc4e4a3db349a63520f025f64e7d7681f6ce47/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs) with DI now.

**Comment by davidfowl** [comment]
That means you can't do HTTP/3 if you new up the server manually. I think that's fine for now. We need to design an API for this in the future though.

Let's get this into 5.0

**Review by Tratcher — APPROVED** [review]

**Review by davidfowl — APPROVED** [review]

**Review by jkotalik — APPROVED** [review]

**Comment by Pilchie** [comment]
@halter73 - can you fill out the shiproom template here, and we'll talk about it at Tactics.

**Comment by halter73** [comment]
#### Description

This reverts a breaking change to the KestrelServer constructor signature.

3.1 ctor:

```c#
public KestrelServer(
    IOptions<KestrelServerOptions> options,
    IConnectionListenerFactory transportFactory,
    ILoggerFactory loggerFactory)
```

5.0-rc2 ctor:

```c#
public KestrelServer(
    IOptions<KestrelServerOptions> options,	
    IEnumerable<IConnectionListenerFactory> transportFactories,	
    ILoggerFactory loggerFactory)
```

The difference is in the second `transportFactory` parameter. When working on HTTP/3 we made the second parameter an `IEnumerable<IConnectionListenerFactory>` instead of `IConnectionListenerFactory`. This was done for DI reasons which are no longer relevant because we now register the internal KestrelServerImpl class instead of KestrelServer class with DI.

This PR reverts the KestrelServer constructor back to its 3.1 signature.

#### Customer Impact

Most customers will not be impacted because it's uncommon to "new up" KestrelServer directly. Kestrel is usually activated by DI.

However, the KestrelServer class and this constructor are public, and any code that does new it up directly would be broken if we don't revert the change. [Here's one example](https://github.com/davidfowl/BedrockFramework/commit/aef398815f7cf100ab18c883603b3cdf47a95a74#diff-b117c6945defc7c70c329af1f9a0671bL55) that was reported by @davidfowl. Though I'm not sure if he counts as a customer. 😆 

The linked example shows the workaround which involves wrapping the second parameter in an IEnumerable:

```diff
-            var server = new KestrelServer(serverOptions, socketTransportFactory, _loggerFactory);
+            var server = new KestrelServer(serverOptions, new[] { socketTransportFactory }, _loggerFactory);
```

#### Regression?

Yes. This regressed between 3.1 and 5.0-preview1.

#### Risk

Very low.

The only reason KestrelServer still exists in 5.0 is for developers who new it up directly. This change has no effect on developers who don't. A different class, KestrelServerImpl, is registered with DI. It makes no sense to keep KestrelServer around for backwards compatibility while breaking its only public constructor.

**Comment by Pilchie** [comment]
Merging, since this was approved at Tactics today.

**Pull request merged**
