### PR TITLE
Identity UI: Input forms' `form-floating` broken styles fixed.

### LINKED ISSUE #40887: Form fields in web pages in project templates appear squished together
**Affected versions**: .NET 6 and .NET 7

Seems as part of the migration to Bootstrap 5.x the styling in our templates has resulted in form fields being squashed together in a very unattractive way, e.g.:

image

Compare this to example form on the [Bootstrap docs](https://getbootstrap.com/docs/5.1/forms/overview/):

image

Both screenshots were taken in Edge latest running on Windows 11 running full screen at 4K at 150% scaling. The templates used were latest from the `main` branch but this reproduces in .NET 6 too.

The effect is exacerbated when an input text field has focus as its border highlight is clipped by the next element in the form, e.g. the button is overlapping the focus border effect of the input field:'

image

### PR DESCRIPTION
**Pull request by TanvirArjel**
All the broken `form-floating` thought the Identity UI forms have been fixed.

Fixes #40887

### CODE REVIEW

**Comment by TanvirArjel** [comment]
@HaoK Please review the pull request. I have fixed all other remaining broken `form-floating` through the Identity UI.

**Comment by HaoK** [comment]
Thanks @TanvirArjel!

@blowdart how does the new placeholder text values look to you?  I'll try this PR locally and attach some before/after screen shots for ease of review for the UI diffs

**Comment by adityamandaleeka** [comment]
Should the placeholders be in the form they are now (e.g. "Please enter your email")? It seems like the more common form is either "Email" or "example@example.org" or something.

**Comment by adityamandaleeka** [comment]
Should the placeholders be in the form they are now (e.g. "Please enter your email")? It seems like the more common form is either "Email" or "example@example.org" or something.

**Review by HaoK — APPROVED** [review]

**Comment by HaoK** [comment]
Thanks for doing this work @TanvirArjel !

**Pull request merged**
