### PR TITLE
Update DbgProxy to https://github.com/mono/mono/commit/ae8e4b5b044

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
FYI @lewing

**Review by SteveSandersonMS — APPROVED** [review]
Assuming this matches the runtime we’re using. 

Seems this update doesn’t include the navigator.webdriver change still though.

**Comment by pranavkm** [comment]
@SteveSandersonMS according to https://github.com/mono/mono/commit/ae8e4b5b044bc8d6ea70fcda83ac9fd5e6ed5317, this should include some sort of navigator.webdriver fix. It's also the most recent commit. Do we expect another change incoming?

**Comment by SteveSandersonMS** [comment]
https://github.com/mono/mono/commit/ae8e4b5b044bc8d6ea70fcda83ac9fd5e6ed5317 is the commit after c8cbcaad

**Comment by pranavkm** [comment]
I think I had the right contents, just the wrong sha earlier.  Just to be safe, I've redone this PR.

**Comment by SteveSandersonMS** [comment]
Looks right now. Thanks!

**Pull request merged**
