### PR TITLE
Always build App.Ref and the targeting packs

### PR DESCRIPTION
**Pull request by dougbu**
- remove `$(IsTargetingPackBuilding)` entirely

### CODE REVIEW

**Comment by RussKie** [comment]
How do we verify API surface isn't changed between the current ref pack (e.g. X.Y.3) and the original ref pack (X.Y.0). @ericstj mentioned we should do an APICompat safeguard (https://github.com/dotnet/windowsdesktop/pull/2362#issuecomment-982923789).

**Comment by dougbu** [comment]
> How do we verify API surface isn't changed between the current ref pack (e.g. X.Y.3) and the original ref pack (X.Y.0).

APICompat is one way. Other options include exercising extreme diligence when reviewing servicing code changes (not the surest choice) and using Microsoft.CodeAnalysis.PublicApiAnalyzers in your builds (what we do in aspnetcore).

**Comment by RussKie** [comment]
> Other options include exercising extreme diligence when reviewing servicing code changes (not the surest choice)

If all fails, yes. Hahah :) 

> ...and using Microsoft.CodeAnalysis.PublicApiAnalyzers in your builds (what we do in aspnetcore).

We use these too in Windows Forms, but I don't think these are used in WPF.

**Review by wtgodbe — APPROVED** [review]

**Comment by ericstj** [comment]
APICompat is pretty easy to setup.  Here's a sample of manual run. https://github.com/dotnet/runtime/blob/6de5c5ba25886270bddfbd827b6cf0b7f8a178a2/src/libraries/shims/ApiCompat.proj#L103

Basically you want to set up the latest build as the "contract" and the GA build as that "implementation".  That ensures that anyone who compiles against surface area in the latest will have their references satisified by the GA build.  You can use a `PackageDownload` to ensure you pull down the GA build.

**Pull request merged**
