### PR TITLE
[Refactor] StatusCodes: apply 1DR, improve doc

### PR DESCRIPTION
**Pull request by yecril71pl**
# StatusCodes: apply 1DR, improve doc

- [X] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [X] You've included unit or integration tests for your change, where applicable.
- [X] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

HTTP status codes are now defined in runtime, so let&rsquo;s use them!  Also, they are documented there, so add references to the existing documentation.

Refactor, no observable changes expected (except for the docs).

### CODE REVIEW

**Comment by Tratcher** [comment]
Thanks for the contribution, but I don't think we'll make this change. It was a conscious decision not to use HttpStatusCode due to their poor naming conventions and data type.

**Comment by yecril71pl** [comment]
> Thanks for the contribution, but I don't think we'll make this change. It was a conscious decision not to use HttpStatusCode due to its poor naming conventions and data type.

What is wrong about the data type?

**Comment by Tratcher** [comment]
HttpStatusCode is an enum which doesn't fit the scenario well. Status codes are a range of integers, they allow custom values, and there are even overlapping values (HttpStatusCode has some duplicate entries).

**Comment by yecril71pl** [comment]
> HttpStatusCode is an enum which doesn't fit the scenario well. Status codes are a range of integers, 

Status codes are a _set_ of integers.

> they allow custom values,

You cannot add custom values to [StatusCodes](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.statuscodes).

> and there are even overlapping values (HttpStatusCode has some duplicate entries).

I cannot see any harm in that.  There are duplicate entries in [StatusCodes](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.statuscodes) too.

**Pull request closed without merging**
