### PR TITLE
[release/8.0] Fix NavigationManager.Refresh() on SSR-only pages

### PR DESCRIPTION
**Pull request by surayya-MS**
# Fix NavigationManager.Refresh() on SSR-only pages

Manual backport of https://github.com/dotnet/aspnetcore/pull/52559

## Description

1. This PR fixes NavigationManager.Refresh() on SSR-only pages
```razor
@page "/"
@inject NavigationManager Nav

<form @onsubmit="@(() => Nav.Refresh())" @formname="myform" method="post">
    <AntiforgeryToken />
    <button>Submit</button>
</form>
```

- When trying the example above in Blazor Web App with no interactivity it results in browser showing NotImplementedException
- When trying same thing in Blazor Web App with Server interactivity then the console shows System.ArgumentNullException and no Refresh is happenning.

2. This PR changes the behavior in case when enhanced navigation is on and the location doesn't change then do not push new history entry. This affects `NavigationManager.Refresh()` and`NavigationManager.NavigateTo({current url})`.

Fixes https://github.com/dotnet/aspnetcore/issues/51222
Fixes https://github.com/dotnet/aspnetcore/issues/51482

## Customer Impact

Without this change customers will not be able to use `NavigationManager.Refresh()` in SSR-only pages. Also, the behavior for `NavigationManager.NavigateTo({current url})` changes - no history entry is pushed.

## Regression?

- [ ] Yes
- [x] No

[If yes, specify the version the behavior has regressed from]

## Risk

- [ ] High
- [ ] Medium
- [x] Low

This is a minor change. There are e2e tests for this change as well as manual testing was done.
The important thing is that newly introduced enhanced navigation feauture's behavior is changed in this PR: when enhanced navigation is on `NavigationManager.NavigateTo({current url}) doesn't push new history entry (it did that before). Hence this should be patched as soon as possible.

## Verification

- [x] Manual (required)
- [x] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

----

## When servicing release/2.1

- [ ] Make necessary changes in eng/PatchConfig.props

### CODE REVIEW

**Review by mkArtakMSFT — APPROVED** [review]
Approved as this is a backport PR which was approved already.

**Comment by surayya-MS** [comment]
This test fails `Microsoft.AspNetCore.Components.E2ETest.Tests.EventTest.Cancel_CanTrigger`. 

I think it is a flaky test because I merged this same change to `main` branch 2 weeks ago https://github.com/dotnet/aspnetcore/pull/52559 and this test was passing. I then found out that this test was quarantined in `main` a week after https://github.com/dotnet/aspnetcore/commit/15194b0a34157cdaf7c0e6e0813929aff2356986

cc @dotnet/aspnet-blazor-eng, @wtgodbe

**Comment by wtgodbe** [comment]
@MackinnonBuck @mkArtakMSFT there's a merge conflict here, who can take a look at it now that Surayya is off the team?

**Comment by MackinnonBuck** [comment]
The test failures seem to be caused by EF migrations not being able to apply:

```text
2024-01-09T22:55:20.8760092Z   Failed Templates.Mvc.Test.RazorPagesTemplateTest.RazorPagesTemplate_IndividualAuth(useProgramMain: True, noHttps: False) [7 s]
2024-01-09T22:55:20.8760123Z   Error Message:
2024-01-09T22:55:20.8761067Z    Project new razor  --auth Individual --use-program-main failed to run EF migrations. Exit code 150.
2024-01-09T22:55:20.8761127Z dotnet-ef --verbose --no-build migrations add razorpages\nStdErr: You must install or update .NET to run this application.
```

Not yet sure why this would suddenly start happening.

**Comment by wtgodbe** [comment]
Test failures are unrelated

**Pull request merged**
