### PR TITLE
Change SameSite default to None

### PR DESCRIPTION
**Pull request by Tratcher**
#2675 #4661 Note this changes the basic infrastructure defaults but does not change any given component's behavior as each component already specified their SameSite config.

SameSite defaults:
- Session: Lax
- CookieTempDataProvider: Lax
- Antiforgery: Strict
- CookieAuth: Lax
- Twitter state cookie: Lax
- Remote auth corrilation cookie (OAuth): None
- OIDC nonce cookie: None

[WIP] Running tests to make sure I didn't miss any.

### CODE REVIEW

**Comment by blowdart** [comment]
If this doesn't affect any of our components anyway, then why do the change from "most secure" at all? We'd still be broken.

**Comment by Tratcher** [comment]
The point here is that SameSite has been breaking arbitrary components that aren't aware of it so we're changing to an opt-in model. Our components have already opted in as far as they're able.

**Comment by blowdart** [comment]
Opt-in to security is generally not the route we take though

**Review by HaoK — APPROVED** [review]
Looks fine code wise, I defer to @blowdart if this is something that's safe or good to do

**Comment by Tratcher** [comment]
If it was a stable security feature I'd agree, but it's not, Apple keeps breaking it.

**Comment by blowdart** [comment]
So now I ask the impossible, if it's affecting other components can I get an idea of how widespread this is?

**Comment by Tratcher** [comment]
We have three datapoints:
1. The CookiePolicy SameSite default broke all remote auth and had to be [disabled](https://github.com/aspnet/AspNetCore/pull/8043/files#diff-2575214c43b0d5764ba24c1978a59c6dL61) in the templates. People still regularly break this if they don't have that line.
1. Anyone calling Response.Cookies.Append also defaulted to Lax. There haven't been as many direct reports of this issue.
1. Anyone using Lax on IOS is broken and they've had to disable it [everywhere](https://github.com/aspnet/AspNetCore/issues/4647). We've gotten a lot of hits on this one and it's not just auth cookies, it affects session, app cookies (See 2), etc..

This change fixes the first two. It doesn't fix the 3rd.

**Comment by blowdart** [comment]
OK fair, I submit :)

**Review by blowdart — APPROVED** [review]
Looks meh to me, but what can I do? :D

**Comment by anurse** [comment]
@Tratcher please rebase on `master` ASAP. This is failing due to a flaky test that has been skipped in `master`

**Pull request merged**
