### PR TITLE
Feature Request Issue Template

### PR DESCRIPTION
**Pull request by TanayParikh**
[Preview](https://github.com/dotnet/aspnetcore/blob/ffa26fd85b038aa718dc2beeeadb89277ddbedd3/.github/ISSUE_TEMPLATE/20_feature_request.yml)

### CODE REVIEW

**Comment by TanayParikh** [comment]
Retry not working due to https://github.com/dotnet/aspnetcore/issues/39477, need to do a full re-run.

**Comment by javiercn** [comment]
@TanayParikh don't re-trigger the build for these types of changes as its wasteful. 

Suggest you ask the build team to merge once you get sign-off instead.

**Comment by dougbu** [comment]
@TanayParikh one downside of using forms in more issue templates is the inability to completely clear out the description. People who want to start from scratch need to go to <https://github.com/dotnet/aspnetcore/issues/new> or choose a template still using .md files. Is your plan to remove all .md templates, removing the second option❔ If yes, why❔

**Comment by TanayParikh** [comment]
> @TanayParikh one downside of using forms in more issue templates is the inability to completely clear out the description. People who want to start from scratch need to go to https://github.com/dotnet/aspnetcore/issues/new or choose a template still using .md files. 

There's also a button at the bottom left of the issues page to create a blank issue:

image


That's what I normally use. If I'm running into an issue, I generally have a good idea of what details I may need to provide to either reproduce or debug the issue in the future. I suspect other repo contributors are also using the blank template via this or the methods you described. The template isn't too necessary for repo members/core contributors as we can always reach out and quickly get clarity if required. The template is primarily targeted for members of the community as it ensures the standard reporting process is followed (check for duplicate issues, issue details, repro steps, versions, etc.). Overall I really like the templates as I'm finding the quality of the issues (in terms of details provided and clarity) has improved after we switched to issue templates. This is likely an effect of them being easier to parse and complete, in comparison to editing a markdown textarea with a bunch of comments.

> Is your plan to remove all .md templates, removing the second option❔ If yes, why❔

No, this was the last template I was planning on replacing as this (along with the main bug issue) are the most used templates.

**Review by dougbu — APPROVED** [review]
Thanks for the additional details @TanayParikh

**Comment by TanayParikh** [comment]
Merged & validated: https://github.com/dotnet/aspnetcore/issues/39534

**Pull request merged**
