### PR TITLE
Bump selenium-standalone to 8.3.0 - allow E2E testing on osx-arm64

### LINKED ISSUE #45838: Build fails on Mac M1 with "ENOENT: no such file or directory" due to selenium-standalone
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Building _/src/Components_ via `/src/Components $ ./build.sh` fails on a Mac M1 in `selenium-standalone` due to a recent-ish change to the ARM64-based `chromedriver` archive's filename convention on the Chromium distribution site.

The first clue was a download failure at some point (possibly during dependency restore when I first opened the project) on `https://chromedriver.storage.googleapis.com/108.0.5359.71/chromedriver_mac64_m1.zip`, which I cannot for the life of me find in my build logs.

However, this error now repros reliably on every `/src/Components $ ./build.sh` execution because the script tries to `chmod` a nonexistent `chromedriver` archive:

```bash
  -----
  selenium-standalone installation finished
  -----
/Users/mmacy/repos/aspnetcore/src/Shared/E2ETesting/E2ETesting.targets(23,5): error : in "chmod".  [/Users/mmacy/repos/aspnetcore/src/Components/test/E2ETest/Microsoft.AspNetCore.Components.E2ETests.csproj]
  See more details below:
  ENOENT: no such file or directory, chmod '/Users/mmacy/repos/aspnetcore/src/Components/test/E2ETest/node_modules/selenium-standalone/.selenium/chromedriver/108.0.5359.71-arm64/chromedriver'
  node:internal/process/promises:289
              triggerUncaughtException(err, true /* fromPromise */);
              ^
  
  [Error: ENOENT: no such file or directory, chmod '/Users/mmacy/repos/aspnetcore/src/Components/test/E2ETest/node_modules/selenium-standalone/.selenium/chromedriver/108.0.5359.71-arm64/chromedriver'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'chmod',
    path: '/Users/mmacy/repos/aspnetcore/src/Components/test/E2ETest/node_modules/selenium-standalone/.selenium/chromedriver/108.0.5359.71-arm64/chromedriver'
  }
  
  Node.js v19.3.0
  info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
/Users/mmacy/repos/aspnetcore/src/Shared/E2ETesting/E2ETesting.targets(23,5): error : Command failed with exit code 1. [/Users/mmacy/repos/aspnetcore/src/Components/test/E2ETest/Microsoft.AspNetCore.Components.E2ETests.csproj]
```

### Expected Behavior

Executing `/src/Components $ ./build.sh` should download all the project's dependencies including _those_ dependencies' dependencies, and complete successfully.

### Steps To Reproduce

1. On a Mac M1 machine, follow the steps in [_BuildFromSource.md_](https://github.com/dotnet/aspnetcore/blob/main/docs/BuildFromSource.md) to prepare your local build environment.
2. Execute the _/src/Components/build.sh_ script.

### Exceptions (if any)

_No response_

### .NET Version

8.0.100-alpha.1.22531.1

### Anything else?

As of version `106.0.5249.61`, the filename suffix for the ARM64-based `chromedriver` ZIP archive changed. The change causes the version of `selenium-standalone` used by the current build config to fail to download the archive.

- [Old format (106.0.5249.21)](https://chromedriver.storage.googleapis.com/index.html?path=106.0.5249.21/): `chromedriver_mac64_m1.zip`
- [New format (106.0.5249.61](https://chromedriver.storage.googleapis.com/index.html?path=106.0.5249.61/): `chromedriver_mac_arm64.zip`

The _compute-download-urls.js_ file in the version of `selenium-standalone` used by the current aspnetcore build/test toolchain does _not_ accommodate the new chromedriver filename convention:

```javascript
// Busted version - from selenium-standalone in current build/test toolchain
platform = 'mac64' + (process.arch === 'arm64' ? '_m1' : '');
```

The upstream `selenium-standalone` repo includes a fix for this in the current [_compute-download-urls.js_](https://github.com/webdriverio/selenium-standalone/blob/2a924c1fca2ff8f5fa8193e27fcbc0ebf8fbb6be/lib/compute-download-urls.js#L119):

```javascript
// Fixed in upstream selenium-standalone repo
platform = parseInt(major, 10) > 105 ? 'mac_arm64' : 'mac64_m1';
```

Happy to provide more information if you need it, just say the word. 🙂 

> ℹ️ To get unblocked, M1 Mac users can manually download and extract the right `chromedriver` to the expected location.

### PR DESCRIPTION
**Pull request by lambdageek**
# Bump selenium-standalone to 8.3.0

## Description

Fixes #45838

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Good luck, see previous attempt at this
https://github.com/dotnet/aspnetcore/pull/44834

**Comment by lambdageek** [comment]
> Good luck, see previous attempt at this #44834

Oh well that's depressing...

I'll give it a couple more tries, but I'm fairly close to giving up - the changes in this PR are enough to unblock local development for me for the one patch that I need to try out, but I have no real idea what i'm doing...

**Comment by lambdageek** [comment]
oh, it's failing now because of https://github.com/webdriverio/selenium-standalone/issues/736 that @MackinnonBuck noticed back in November.  I wonder if we can specify the java options in some other way

**Comment by lambdageek** [comment]
It looks like the only other package.json+yarn.lock that mentions selenium-standalone is in `src/ProjectTemplates/test/Templates.Tests`

I'll try to update it when i'm on a machine where I can do the vsts auth thing

**Comment by lambdageek** [comment]
well the e2e tests run, but it looks like at some point chrome just crashes and selenium can't restart it.  No clue why, yet.

**Comment by lambdageek** [comment]
@amcasey no, sorry. I gave up.

**Pull request closed without merging**
