### PR TITLE
Update references to System.IO.Pipelines

### PR DESCRIPTION
**Pull request by wtgodbe**
Fixes some CG alerts

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
This is 🆗 but why not use `<Reference Include="System.IO.Pipelines" />` for consistency, brevity, and readability❔

**Comment by wtgodbe** [comment]
> This is 🆗 but why not use <Reference Include="System.IO.Pipelines" /> for consistency, brevity, and readability❔

This is 2.1, they'd all get resolved to BaselineReferences (except in the case where the project is being patched):

https://github.com/dotnet/aspnetcore/blob/3aa8235a83ab29d7af8f4878872a53cd37b905cc/eng/targets/ResolveReferences.targets#L28-L38

**Comment by davidfowl** [comment]
Why is this?

**Comment by wtgodbe** [comment]
> Why is this?

There are component governance alerts in 2.1 because these projects get transitive references to an old version of System.IO.Pipelines. Since 2.1 still has support for full framework, we're stuck having to fix the alerts.

**Pull request merged**
