### PR TITLE
feat: add StringSyntaxAttribute for guid and timespan args

### PR DESCRIPTION
**Pull request by abc516**
#44535 (GuidFormat and TimeSpanFormat)

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Description

Adds the StringSyntaxAttribute for guid and timespan string function parameters, to specify syntax adherence.

### CODE REVIEW

**Comment by abc516** [comment]
@dotnet-policy-service agree

**Comment by abc516** [comment]
@dotnet-policy-service agree



> @abc516 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

**Comment by BrennanConroy** [comment]
This is test code, applying the string syntax attribute isn't very interesting in these cases.

**Comment by divyeshio** [comment]
> I added it to the timespan strings to enhance the content of the PR.

Those are private methods, adding string syntax attribute to them isn't helpful.

**Comment by abc516** [comment]
@BrennanConroy @mkArtakMSFT I had some issues resolving upstream changes in the codebase. I will re-open a PR for this issue once they are fixed.

**Pull request closed without merging**
