### PR TITLE
Update to Ms.Id.Web 1.14.1

### PR DESCRIPTION
**Pull request by jmprieur**
**PR Title**
Update the web project templates to Microsoft.Identity.Web 1.14.1

**PR Description**
- Update the version of Microsoft.Identity.Web
- Simplify the web API controlers

### CODE REVIEW

**Review by javiercn — APPROVED** [review]
Looks great!

**Review by jennyf19 — APPROVED** [review]
:shipit:

**Review by HaoK — APPROVED** [review]

**Comment by jmprieur** [comment]
cc: @blowdart
@HaoK: should I do anything more?

**Comment by HaoK** [comment]
Assuming you have tried these changes, I think its safe to get into rc1 as we have plenty of time to react to any issues given that we just branched for preview7 last week  

@dougbu its safe to start merging rc1 fixes right?

**Comment by jmprieur** [comment]
With tested with preview 5.
Is it possible to get the NuGet package for the affected templates?

**Comment by HaoK** [comment]
Yep you go to https://dev.azure.com/dnceng/public/_build/results?buildId=1246063&view=artifacts&pathAsName=false&type=publishedArtifacts although I don't see the Windows shipped packages in the artifacts for some reason...  cc @dotnet/aspnet-build did we move the cheese?  Where would @jmprieur be able to find the matching templates nupkgs for this build?

**Comment by dougbu** [comment]
> @dougbu its safe to start merging rc1 fixes right?

Right

> Where would @jmprieur be able to find the matching templates nupkgs for this build?

The package won't be available until after this PR is merged. We don't upload package artifacts for forks.

**Comment by dougbu** [comment]
Once this is merged, the packages will be available in https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json

**Comment by HaoK** [comment]
I thought in the past the nupkgs for templates were available as artifacts but maybe that was a side effect of template testing?

**Pull request merged**
