### PR TITLE
Update System.IdentityModel.Tokens.Jwt to 6.6

### LINKED ISSUE #22764: Finally a chance to get rid of claim type mappings!
With the 6.x release of the MS JWT handler, the mapping of artisanally crafted, spec-compliant claim types to their WS-* counterparts from the late 90ies is finally gone!

That means you can now get rid of this behavior in your OIDC and JWT handlers for v5! That's great!

I can totally understand that this is a breaking change, and you probably want to keep the wrong behavior by default for a little while. But maybe a simple opt-out switch is now possible? 

e.g.
```
// behave like a claims-based gentleman (defaults to false though)
options.LeaveMyClaimTypesAloneFfs = true;
```

Alternatively maybe

```
options.ClaimsActions.Clear();
```

Also imagine how many backlog issues you can finally close that are related to that problem. It's a win-win.

### PR DESCRIPTION
**Pull request by HaoK**
here goes nothing :)

### CODE REVIEW

**Comment by HaoK** [comment]
Guess it appears fine :)

**Comment by HaoK** [comment]
@dougbu can you confirm that I don't need to update anything else other than the version to pick up a new version of the jwt package?

**Comment by dougbu** [comment]
@HaoK you're all set.

**Review by dougbu — APPROVED** [review]
I know nothing about the different versions but looks good 😈

**Comment by Tratcher** [comment]
Oh dear... Now I'm worried.

How about running some of the OIDC and JwtBearer samples manually?

We should make a breaking change announcement, but we'd have to know what actually changed.

**Comment by HaoK** [comment]
We don't have any OIDC or JwtBearer e2e tests anywhere in our full stack?  I would assume the identity   api servers use jwt at least

**Comment by JunTaoLuo** [comment]
So what's the next steps here to validate the change?

**Comment by HaoK** [comment]
Chris was suggesting these samples: https://github.com/dotnet/aspnetcore/tree/master/src/Security/Authentication/JwtBearer/samples/JwtBearerSample
https://github.com/dotnet/aspnetcore/tree/master/src/Security/Authentication/OpenIdConnect/samples

**Comment by kinosang** [comment]
Is there any plan to update Microsoft.IdentityModel.Protocols.* packages to 6.6?

**Comment by Tratcher** [comment]
> Is there any plan to update Microsoft.IdentityModel.Protocols.* packages to 6.6?

@HaoK oh yeah.... there's three more packages here to update:
https://github.com/dotnet/aspnetcore/blob/44739424dbaa4cedef6fb3ba11cb8ba0a703c9f9/eng/Versions.props#L191-L193

**Comment by Tratcher** [comment]
This needs to retarget from master to preview7.

**Comment by Tratcher** [comment]
Oh look, there's a failure we were kindof expecting. The new packages no longer have a transitive dependency on Newtonsoft.Json so several test projects broke. That's worth including in the announcement.

**Comment by JunTaoLuo** [comment]
I've been able to verify that the OIDC and JwtBearer samples work as expected and I've updated the samples/readmes a bit based on some of the issues I ran into. I'm running into some errors for the WsFed samples though. I'm going to see if it's due to the updated packages or not.

**Comment by JunTaoLuo** [comment]
Ok @Tratcher and I also worked out how to run the WsFed sample. I'll update our docs to reflect the new AAD portal UI. but otherwise, I suppose we can consider this change verified.

**Review by JunTaoLuo — APPROVED** [review]
Anyone want to spot check the changes I made to the Readme?

**Review by Tratcher — APPROVED** [review]
@JunTaoLuo can you also file a doc bug for the issues you ran into?

**Comment by JunTaoLuo** [comment]
Actually I just made a PR: https://github.com/dotnet/AspNetCore.Docs/pull/18931

**Comment by Tratcher** [comment]
Was a migrations guide doc bug filed for this. Or a breaking change announcement?

**Comment by HaoK** [comment]
I'll file the breaking change announcement now, I think that auto gets them to notice?

**Comment by HaoK** [comment]
Filed https://github.com/aspnet/Announcements/issues/428

**Pull request merged**
