### PR TITLE
Adds ability to use a custom css class

### PR DESCRIPTION
**Pull request by XmlmXmlmX**
Summary of the changes
 - Adds condition to check if `class` attribute was set

Addresses #19278 and #8695

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
Thanks for suggesting this, @XmlmXmlmX!

The way we'd prefer to do this, to be consistent with other parts of the framework, is to combine any developer-supplied `class` attribute value with the built-in default `"validation-message"`. We have this kind of behavior in `NavLink`, for example (though NavLink does it in a more complicated way than you'd need to here).

Developers who aren't using the CSS class `"validation-message"` can simply ignore it. Longer term we might provide a mechanism to change that default class, but we don't want to do that in the upcoming release so for now it's best to just make CSS classes able to combine together with the fixed default.

Additionally, for us to accept this PR, we'd need it to come with suitable test coverage. At minimum this would mean adding an example of a `ValidationMessage` that supplies its own `class` into [this test component](https://github.com/dotnet/aspnetcore/blob/master/src/Components/test/testassets/BasicTestApp/FormsTest/TypicalValidationComponent.razor) and writing assertions for it in [the corresponding E2E test class](https://github.com/dotnet/aspnetcore/blob/master/src/Components/test/E2ETest/Tests/FormsTest.cs).

Is that OK? Thanks again for contributing!

**Comment by XmlmXmlmX** [comment]
> Thanks for suggesting this, @XmlmXmlmX!
> 
> The way we'd prefer to do this, to be consistent with other parts of the framework, is to combine any developer-supplied `class` attribute value with the built-in default `"validation-message"`. We have this kind of behavior in `NavLink`, for example (though NavLink does it in a more complicated way than you'd need to here).
> 
> Developers who aren't using the CSS class `"validation-message"` can simply ignore it. Longer term we might provide a mechanism to change that default class, but we don't want to do that in the upcoming release so for now it's best to just make CSS classes able to combine together with the fixed default.
> 
> Additionally, for us to accept this PR, we'd need it to come with suitable test coverage. At minimum this would mean adding an example of a `ValidationMessage` that supplies its own `class` into [this test component](https://github.com/dotnet/aspnetcore/blob/master/src/Components/test/testassets/BasicTestApp/FormsTest/TypicalValidationComponent.razor) and writing assertions for it in [the corresponding E2E test class](https://github.com/dotnet/aspnetcore/blob/master/src/Components/test/E2ETest/Tests/FormsTest.cs).
> 
> Is that OK? Thanks again for contributing!

Alright, I will have a look on these tests.

**Comment by mkArtakMSFT** [comment]
Thanks for your PR.
We're currently busy wrapping up our upcoming Blazor WASM release, which is planned to go out in May. That forces us to delay some community PR reviews which target ASP.NET Core 5.0, so please expect some delays here. We will get to this as soon as we wrap up the Blazor work.

**Comment by mkArtakMSFT** [comment]
Thanks for your PR, @XmlmXmlmX.
We would like to propose some design for this issue before community can handle it so people don't spend time in wrong direction. We are closing this PR for now as it is not aligned with how we envision this to work.

**Pull request closed without merging**
