### PR TITLE
Try adding arm helix queues

### PR DESCRIPTION
**Pull request by HaoK**

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
Change looks fine. However, should we hold off until Helix builds are passing more reliably in this repo? Looks like this check fails ~50% of the time -- still.

**Review by Eilon — APPROVED** [review]

**Comment by HaoK** [comment]
Curl not found on 1604 arm ubuntu for some reason, removing that queue for now

**Comment by HaoK** [comment]
Rerunning helix tests, like 40% of debian 9 arm tests failed with a weird malformed json parsing error in dotnet-install

**Comment by Eilon** [comment]
@HaoK well that doesn't sound right at all!

**Comment by HaoK** [comment]
Rerun looks better, 3 non arm ubuntu 1604 failures which look like issues on their helix queue side as the payload didn't download and run.

One debian arm failure due to total number of unit tests being unknown, as opposed to any failures.

Rerunning one more time

**Comment by HaoK** [comment]
Adding the fedora queues back for this run as well as the disk issue has been fixed on their end

**Comment by HaoK** [comment]
Merging, new arm queues and fedora queues are green now

**Comment by HaoK** [comment]
rip helix is green but normal ci failed now...retrying

**Pull request merged**
