### PR TITLE
Bump the Microsoft.NET.Test.Sdk version

### PR DESCRIPTION
**Pull request by dougbu**
- should resolve problems testing on Arm64 Helix agents

### CODE REVIEW

**Comment by dougbu** [comment]
Trying out an alternative to #38346 that should allow us to continue moving our .NET SDK forward until microsoft/vstest#3170 flows into the SDK and back to us.

**Review by wtgodbe — APPROVED** [review]
If it works!

**Comment by dougbu** [comment]
[`aspnetcore-helix-matrix` build 20211115.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1470008&view=results) is the main one that matters, especially it's Arm64 job.

**Comment by pranavkm** [comment]
@dougbu just to confirm, does this mean we no longer have to try roll back the SDK (since that seemed to fix the ARM64 issue)?

**Comment by pranavkm** [comment]
Downgrade warning:

```
/home/vsts/work/1/s/src/Tools/Microsoft.dotnet-openapi/test/dotnet-microsoft.openapi.Tests.csproj : error NU1605: Detected package downgrade: NuGet.Frameworks from 5.11.0 to 5.10.0-rc.7240. Reference the package directly from the project to select a different version.  [/home/vsts/work/1/s/.dotnet/sdk/7.0.100-alpha.1.21555.1/NuGet.targets]
/home/vsts/work/1/s/src/Tools/Microsoft.dotnet-openapi/test/dotnet-microsoft.openapi.Tests.csproj : error NU1605:  Microsoft.DotNet.Open.Api.Tools.Tests -> Microsoft.NET.Test.Sdk 17.1.0-preview-20211109-03 -> Microsoft.TestPlatform.TestHost 17.1.0-preview-20211109-03 -> Microsoft.TestPlatform.ObjectModel 17.1.0-preview-20211109-03 -> NuGet.Frameworks (>= 5.11.0)  [/home/vsts/work/1/s/.dotnet/sdk/7.0.100-alpha.1.21555.1/NuGet.targets]
/home/vsts/work/1/s/src/Tools/Microsoft.dotnet-openapi/test/dotnet-microsoft.openapi.Tests.csproj : error NU1605:  Microsoft.DotNet.Open.Api.Tools.Tests -> NuGet.Frameworks (>= 5.10.0-rc.7240) [/home/vsts/work/1/s/.dotnet/sdk/7.0.100-alpha.1.21555.1/NuGet.targets]
    0 Warning(s)
    1 Error(s)
```

**Comment by dougbu** [comment]
> does this mean we no longer have to try roll back the SDK (since that seemed to fix the ARM64 issue)?

Yes, once I get this working. Need to bump NuGet.Framework too&hellip;

**Comment by dougbu** [comment]
Now, [`aspnetcore-helix-matrix` build 20211115.4=5](https://dev.azure.com/dnceng/public/_build/results?buildId=1470045&view=results) is the main one that matters. Again, especially its Arm64 job.

**Comment by dougbu** [comment]
Hurray 🎉

**Pull request merged**
