### PR TITLE
Update dependencies from 5 repositories

### PR DESCRIPTION
**Pull request by dougbu**
* Update dependencies from build '20190706.1' of 'https://github.com/dotnet/arcade'
  - 'Microsoft.DotNet.Arcade.Sdk': '1.0.0-beta.19351.4' => '1.0.0-beta.19356.1'
  - 'Microsoft.DotNet.GenAPI': '1.0.0-beta.19351.4' => '1.0.0-beta.19356.1'
  - 'Microsoft.DotNet.Helix.Sdk': '2.0.0-beta.19351.4' => '2.0.0-beta.19356.1'

* Update dependencies from build '20190706.2' of 'https://github.com/dotnet/roslyn'
  - 'Microsoft.Net.Compilers.Toolset': '3.3.0-beta1-19351-01' => '3.3.0-beta2-19356-02'

* Update dependencies from build '20190706.5' of aspnet/AspNetCore-Tooling
  - 'Microsoft.AspNetCore.Mvc.Razor.Extensions': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19356.5'
  - 'Microsoft.AspNetCore.Razor.Language': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19356.5'
  - 'Microsoft.CodeAnalysis.Razor': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19356.5'
  - 'Microsoft.NET.Sdk.Razor': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19356.5'

* Update dependencies from build '20190705.1' of 'https://github.com/aspnet/Blazor'
  - 'Microsoft.AspNetCore.Blazor.Mono': '0.10.0-preview8.19351.2' => '0.10.0-preview8.19355.1'

* Update dependencies from from build '20190704.5' of 'https://github.com/aspnet/EntityFrameworkCore'
  - 'Microsoft.EntityFrameworkCore.Tools': '3.0.0-preview8.19353.14' => '3.0.0-preview8.19354.5'
  - 'Microsoft.EntityFrameworkCore.SqlServer': '3.0.0-preview8.19353.14' => '3.0.0-preview8.19354.5'
  - 'dotnet-ef': '3.0.0-preview8.19353.14' => '3.0.0-preview8.19354.5'
  - 'Microsoft.EntityFrameworkCore': '3.0.0-preview8.19353.14' => '3.0.0-preview8.19354.5'
  - 'Microsoft.EntityFrameworkCore.InMemory': '3.0.0-preview8.19353.14' => '3.0.0-preview8.19354.5'
  - 'Microsoft.EntityFrameworkCore.Relational': '3.0.0-preview8.19353.14' => '3.0.0-preview8.19354.5'
  - 'Microsoft.EntityFrameworkCore.Sqlite': '3.0.0-preview8.19353.14' => '3.0.0-preview8.19354.5'

Coherency updates...
  - 'Microsoft.AspNetCore.Analyzer.Testing': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.AspNetCore.BenchmarkRunner.Sources': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.ActivatorUtilities.Sources': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Caching.Abstractions': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Caching.Memory': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Caching.SqlServer': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Caching.StackExchangeRedis': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.CommandLineUtils.Sources': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Configuration.Abstractions': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Configuration.AzureKeyVault': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Configuration.Binder': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Configuration.CommandLine': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Configuration.EnvironmentVariables': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Configuration.FileExtensions': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Configuration.Ini': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Configuration.Json': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Configuration.KeyPerFile': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Configuration.UserSecrets': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Configuration.Xml': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Configuration': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.DependencyInjection.Abstractions': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.DependencyInjection': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.DiagnosticAdapter': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Diagnostics.HealthChecks': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.FileProviders.Abstractions': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.FileProviders.Composite': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.FileProviders.Embedded': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.FileProviders.Physical': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.FileSystemGlobbing': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.HashCodeCombiner.Sources': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Hosting.Abstractions': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Hosting': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.HostFactoryResolver.Sources': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Http': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Localization.Abstractions': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Localization': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Logging.Abstractions': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Logging.AzureAppServices': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Logging.Configuration': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Logging.Console': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Logging.Debug': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Logging.EventSource': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Logging.EventLog': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Logging.TraceSource': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Logging.Testing': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.ObjectPool': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Options.ConfigurationExtensions': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Options.DataAnnotations': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Options': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.ParameterDefaultValue.Sources': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.Primitives': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.TypeNameHelper.Sources': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.ValueStopwatch.Sources': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Extensions.WebEncoders': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Internal.Extensions.Refs': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.JSInterop': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Mono.WebAssembly.Interop': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Internal.AspNetCore.Analyzers': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'
  - 'Microsoft.AspNetCore.Testing': '3.0.0-preview8.19353.10' => '3.0.0-preview8.19354.4'

  - 'Microsoft.Extensions.DependencyModel': '3.0.0-preview8-27903-07' => '3.0.0-preview8-27904-06'
  - 'Microsoft.NETCore.App.Ref': '3.0.0-preview8-27903-07' => '3.0.0-preview8-27904-06'
  - 'Microsoft.NETCore.App.Runtime.win-x64': '3.0.0-preview8-27903-07' => '3.0.0-preview8-27904-06'
  - 'NETStandard.Library.Ref': '2.1.0-preview8-27903-07' => '2.1.0-preview8-27904-06'

  - 'Microsoft.Bcl.AsyncInterfaces': '1.0.0-preview8.19353.3' => '1.0.0-preview8.19354.4'
  - 'Microsoft.CSharp': '4.6.0-preview8.19353.3' => '4.6.0-preview8.19354.4'
  - 'Microsoft.NETCore.Platforms': '3.0.0-preview8.19353.3' => '3.0.0-preview8.19354.4'
  - 'Microsoft.Win32.Registry': '4.6.0-preview8.19353.3' => '4.6.0-preview8.19354.4'
  - 'System.ComponentModel.Annotations': '4.6.0-preview8.19353.3' => '4.6.0-preview8.19354.4'
  - 'System.Diagnostics.EventLog': '4.6.0-preview8.19353.3' => '4.6.0-preview8.19354.4'
  - 'System.IO.Pipelines': '4.6.0-preview8.19353.3' => '4.6.0-preview8.19354.4'
  - 'System.Net.Http.WinHttpHandler': '4.6.0-preview8.19353.3' => '4.6.0-preview8.19354.4'
  - 'System.Net.WebSockets.WebSocketProtocol': '4.6.0-preview8.19353.3' => '4.6.0-preview8.19354.4'
  - 'System.Reflection.Metadata': '1.7.0-preview8.19353.3' => '1.7.0-preview8.19354.4'
  - 'System.Runtime.CompilerServices.Unsafe': '4.6.0-preview8.19353.3' => '4.6.0-preview8.19354.4'
  - 'System.Security.Cryptography.Cng': '4.6.0-preview8.19353.3' => '4.6.0-preview8.19354.4'
  - 'System.Security.Cryptography.Pkcs': '4.6.0-preview8.19353.3' => '4.6.0-preview8.19354.4'
  - 'System.Security.Cryptography.Xml': '4.6.0-preview8.19353.3' => '4.6.0-preview8.19354.4'
  - 'System.Security.Permissions': '4.6.0-preview8.19353.3' => '4.6.0-preview8.19354.4'
  - 'System.Security.Principal.Windows': '4.6.0-preview8.19353.3' => '4.6.0-preview8.19354.4'
  - 'System.ServiceProcess.ServiceController': '4.6.0-preview8.19353.3' => '4.6.0-preview8.19354.4'
  - 'System.Text.Encodings.Web': '4.6.0-preview8.19353.3' => '4.6.0-preview8.19354.4'
  - 'System.Text.Json': '4.6.0-preview8.19353.3' => '4.6.0-preview8.19354.4'
  - 'System.Threading.Channels': '4.6.0-preview8.19353.3' => '4.6.0-preview8.19354.4'

### CODE REVIEW

**Comment by dougbu** [comment]
@rynowak did you say something recently about an AspNetCore-Tooling breaking change? Does that breaking change relate to `LayoutAttribute`? If yes, this PR is the one for you❕ (If not, please redirect as needed.)

**Comment by rynowak** [comment]
@dougbu - added a commit. I'll continue to keep my eye on this PR.

**Comment by rynowak** [comment]
```txt
Build FAILED.

Components/Shared/MainLayout.razor(1,39): error CS0234: The type or namespace name 'Layouts' does not exist in the namespace 'Microsoft.AspNetCore.Components' (are you missing an assembly reference?) [/Users/vsts/agent/2.153.2/work/1/s/src/Mvc/samples/MvcSandbox/MvcSandbox.csproj]
    0 Warning(s)
    1 Error(s)

```

@dougbu - any tips on knowing where this is coming from? I did a search of the repo and can't find any remaining usage.

**Comment by rynowak** [comment]
Nevermind. Found it!

**Comment by dougbu** [comment]
thx @rynowak. I should go to lunch more often 😺

**Comment by dougbu** [comment]
This looks much better w/ @rynowak's commits. Could someone please approve, in hopes the validation builds succeed?

**Review by ryanbrandenburg — APPROVED** [review]
:ship::it:

**Comment by dougbu** [comment]
@MattGal not sure if it matters much. But, this PR seems to be hitting https://github.com/dotnet/core-eng/issues/6907. Is closing and reopening at all likely to get validation going?

**Comment by dougbu** [comment]
@dagood have .NET Core transitive dependencies changed in the last few days (between core-setup versions 3.0.0-preview8-27903-07 and 3.0.0-preview8.19354.4)?

We're seeing a few unexpected assemblies show up (though microsoft.netcore.app.runtime.win-x64 looks unchanged):
- Microsoft.Win32.SystemEvents
- System.Drawing.Common
- System.Windows.Extensions

**Comment by dagood** [comment]
> core-setup versions 3.0.0-preview8-27903-07 and 3.0.0-preview8.19354.4

Core-Setup uses semver v1, looks like this PR is really `3.0.0-preview8-27903-07` => `3.0.0-preview8-27904-06`. I'm guessing this is just a miscopy.

The tests are actually testing the AspNetCore shared framework. The assemblies listed are platform extension libraries, not included in the netcoreapp sharedfx. It is interesting that they are included in the WindowsDesktop sharedfx, and I wouldn't expect them in aspnet's sharedfx... I'm not able to find the aspnet platform manifest generation tooling to guess at whether that's related.

**Comment by MattGal** [comment]
@dougbu my understanding (may have had to close/reopen too) is that anything after ~5:45 PST yesterday should succeed, though there was fairly epic backup.  The issue is (at least for now) resolved, but the root cause is not understood and this was the second time we've observed the symptom.

**Comment by dougbu** [comment]
> The assemblies listed are platform extension libraries, not included in the netcoreapp sharedfx

Agreed. The set of assemblies listed include the transitive closure of everything we put into Microsoft.AspNetCore.App, excluding what ships in Microsoft.NETCore.App. What's surprising is that transitive closure has changed.

The dependency chain is System.Security.Permissions ➡️ System.Windows.Extensions ➡️ System.Drawing.Common ➡️ Microsoft.Win32.SystemEvents. We've had transitive references to System.Security.Permissions for a while and therefore include it in Microsoft.AspNetCore.App's runtime packs. Seems like the rest of that chain is new. What changed?

(side note: The new dependencies show up on macOS and Linux too. Seems strange&hellip;)

> they are included in the WindowsDesktop sharedfx,

We have never had to exclude the Microsoft.WindowsDesktop.App content. I don't think it makes sense for us to do so. Users reference Microsoft.AspNetCore.App in their projects and would be very surprised if that brought in Microsoft.WindowsDesktop.App  dependencies. As-is, I'm surprised System.Drawing.Common (for example) is part of our transitive closure now.

**Comment by dagood** [comment]
> We have never had to exclude the Microsoft.WindowsDesktop.App content. I don't think it makes sense for us to do so.

I agree, it's just an interesting coincidence that might help investigation.

Via search, I see this recent CoreFX PR added a ProjectReference that sounds like the difference you're seeing: https://github.com/dotnet/corefx/pull/38908. Those folks will know more.

**Pull request merged**
