### PR TITLE
[release/6.0] Build .rpm packages for linux arm64

### PR DESCRIPTION
**Pull request by wtgodbe**
Part of https://github.com/dotnet/aspnetcore/issues/40253, https://github.com/dotnet/aspnetcore/issues/40252.

CC @NikolaMilosavljevic

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
Looks good but I apparently need to learn how to validate the new RPMs&hellip;

**Comment by dougbu** [comment]
Test build matching this iteration: https://dev.azure.com/dnceng/internal/_build/results?buildId=1647211&view=results

**Comment by dougbu** [comment]
Latest test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1650772&view=results

**Comment by dougbu** [comment]
Now: https://dev.azure.com/dnceng/internal/_build/results?buildId=1650783&view=results

**Comment by dougbu** [comment]
Fixed `x64` names. New build is https://dev.azure.com/dnceng/internal/_build/results?buildId=1651827&view=results

**Comment by wtgodbe** [comment]
Validation confirmed the install works - thanks for the help @dougbu and @NikolaMilosavljevic!

**Pull request merged**
