### PR TITLE
Update area-owners.md

### PR DESCRIPTION
**Pull request by danmoseley**
@mkArtakMSFT @adityamandaleeka @joperezr I noticed some of this is out of date.

Can we pull content in from https://github.com/dotnet/aspnetcore-internal/wiki/Team-Ownership and delete the internal page? I'm happy to do this but where is, eg., the list of triagers for gRPC defined?

cc @ericstj @jeffhandley 

Edit: Preview - https://github.com/dotnet/aspnetcore/blob/danmoseley-patch-1/docs/area-owners.md

### CODE REVIEW

**Comment by danmoseley** [comment]
BTW the runtime team differentiates leads from owners, and also has GitHub teams set up for each one. We don't need to do those things, but I do like having IC's listed here rather than only leads.

**Review by javiercn — COMMENTED** [review]
Looks good, just one potentially unrelated  change.

**Review by wtgodbe — APPROVED** [review]

**Comment by danmoseley** [comment]
I've updated the table to add missing areas, add hyperlinks, and distinguish leads from owners. It would be great to have engineers listed here. I think @adityamandaleeka is going to add his.

**Comment by danmoseley** [comment]
added our team of community triagers

**Comment by mitchdenny** [comment]
Looping @amcasey and @captainsafia into this conversation. We should probably add our triagers list to the list of owners in this table. For minimal you could put @captainsafia and @mitchdenny as owners since we mostly do the triage there. You can put us down for middleware as well.

**Comment by amcasey** [comment]
> Looping @amcasey and @captainsafia into this conversation. We should probably add our triagers list to the list of owners in this table. For minimal you could put @captainsafia and @mitchdenny as owners since we mostly do the triage there. You can put us down for middleware as well.

Sorry, updating this file was on my todo list when I got pulled off for something urgent.  While more updates may come later, you can put me down for `area-networking`, `area-dataprotection`, `area-commandlinetools`, and `area-runtime`.

**Comment by danmoseley** [comment]
@amcasey you have the right prioritization 😄 done.

**Comment by danmoseley** [comment]
@wtgodbe can you review the yml here? I was wondering why it hadn't worked -- then realized that of course yml changes trigger validation..

**Comment by danmoseley** [comment]
```
##[error]Exit code 134 returned from process: file name '/Users/runner/runners/3.220.5/externals/node16/bin/node', arguments '"/Users/runner/work/_tasks/Bash_6c731c3c-3c68-459a-a5c9-bde6e6595b5b/3.224.0/bash.js"'.
``` 
no more info.

**Comment by JamesNK** [comment]
There are empty cells in the community triagers section.

Screenshot:
image

**Comment by danmoseley** [comment]
> There are empty cells in the community triagers table.

Github markdown flavor does not support headerless tables. This is the only way to lay stuff out horizontally

**Comment by JamesNK** [comment]
Use a bullet point list?

**Comment by captainsafia** [comment]
I've update area ownership for myself and added a row for `area-openapi`.

I think we can remove `area-web-frameworks` since it is now defunct.

**Comment by danmoseley** [comment]
@mkArtakMSFT OK with me removing area-webframeworks? I looked and it seems everything falls under some other area- label. It really was a team label, which is orthogonal

**Comment by danmoseley** [comment]
Ideally we'd have 2-3 engineers for each row. 
Who tends to most often look at security stuff, beyond @blowdart ?

**Comment by danmoseley** [comment]
I'm going to merge this for now (nice to have the yaml changes) and let's continue to fill this out..

**Pull request merged**
