### PR TITLE
Set AuthenticationMethod for first Identity external login

### LINKED ISSUE #10970: Creation of an Identity User via External Login doesn't set AuthenticationMethod
When signing in with an external provider for the first time, the Default UI for Identity doesn't set the `ClaimTypes.AuthenticationMethod` claim.

In [`ExternalLoginModel<TUser>.OnPostConfirmationAsync`](https://github.com/aspnet/AspNetCore/blob/master/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/ExternalLogin.cshtml.cs#L174), I think the [call to `SignInAsync`](https://github.com/aspnet/AspNetCore/blob/master/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/ExternalLogin.cshtml.cs#L206) should include an `authenticationMethod` argument, like this:

```cs
await _signInManager.SignInAsync(user, isPersistent: false, info.LoginProvider);
```

### PR DESCRIPTION
**Pull request by serpent5**
Addresses #10970.

If this change is OK, I will submit a corresponding PR to aspnet/scaffolding.

### CODE REVIEW

**Comment by serpent5** [comment]
Is it possible to kick the build for this? I don't think that the changes I made would have caused build failures like those.

**Comment by HaoK** [comment]
Retriggered it @serpent5

**Comment by serpent5** [comment]
Thanks @HaoK. That didn't work, so I rebuilt against the latest and it's all green now. Thanks again.

**Comment by HaoK** [comment]
Can you add a functional test to verify that the claim is showing up now?

**Comment by serpent5** [comment]
Yes, of course. Can you point me at an existing test that asserts a claim value? I couldn't find one myself, so I've come up with something like this:

```csharp
string authenticationMethod = null;

void ConfigureTestServices(IServiceCollection services) =>
    services.SetupGetUserClaimsPrincipal(x =>
        authenticationMethod = x.FindFirstValue(ClaimTypes.AuthenticationMethod), IdentityConstants.ApplicationScheme);

// ...

await UserStories.RegisterNewUserWithSocialLoginAsync(client, userName, email);
Assert.Equal("Contoso", authenticationMethod);
```

That feels dirty, using a closure to track the value, so I'd appreciate a nudge towards an already established pattern.

**Comment by serpent5** [comment]
Sure, that's done. It's the first time I've worked with those functional tests...

**Comment by HaoK** [comment]
Yep you got it, looks good, assuming tests go green, i'll merge, thanks @serpent5 !

**Review by HaoK — APPROVED** [review]

**Pull request merged**
