### PR TITLE
Accessibility fixes

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
Provides fixes for:

 * https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1163117
 * https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1163184
 * https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1162890
 * https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1163642

This tweaks the templates for Blazor, Angular, MVC, Razor Pages, and Identity. So if someone from each of those product areas could please take a look, that would be valuable!

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
See individual commit messages for details about what each change fixes.

**Comment by javiercn** [comment]
LGTM, some of these fixes are applicable to other templates I imagine, isn't that the case? (Like the navmenu one). I'm not asking you to do anything, just checking in case we need a separate bug to deal with them.

**Review by javiercn — APPROVED** [review]

**Comment by SteveSandersonMS** [comment]
The navmenu fix only applies in the cases I’ve applied it, as far as I see.

**Comment by mkArtakMSFT** [comment]
@Pilchie

**Review by mkArtakMSFT — APPROVED** [review]

**Comment by Pilchie** [comment]
Approved for .NET 5 RC2.

**Review by HaoK — APPROVED** [review]

**Pull request merged**
