### PR TITLE
Extract property AutoSaveChanges into new interface (#7648)

### PR DESCRIPTION
**Pull request by michaeldz**
Just extract AutoSaveChanges property in new interface. See #7648 for details.

### CODE REVIEW

**Comment by HaoK** [comment]
Issue was closed https://github.com/aspnet/AspNetCore/issues/7648

**Comment by michaeldz** [comment]
@HaoK Hao could you explain little bit more what's wrong with this change?

**Comment by HaoK** [comment]
If you are trying to enable AutoSaveChanges in your app, just derive from the appropriate UserStore class and set it to true.  We aren't going to adding an interface for this

**Comment by michaeldz** [comment]
@HaoK In my case it doesn't work. Because it is like a "3rd party component" .. all what I know - there is some store that is UserStore, but I don't know which class is it exactly, and of course I cannot derive it.
So there are two solution - use complex and not fast reflection or change AspNet because open-source ... I hope.

**Comment by michaeldz** [comment]
@HaoK Probably I explained my issue not well. Let's try one more time. I'm developing a framework. This framework **extends** base functionality of ASP.Net Identity. It adds couple of new things - providers, services etc.
It should be applicable for other applications. We do not want to limit users in customization - they can provide custom user, roles and other things that they usually do with regular Identity framework.
This approach works well. There is only one issue. We require to apply changes for service-level operations in scope of single transaction for related entities. 
In Identity framework there is good mechanism - the AutoSaveChanges property.
But as I mentioned early because there is no interface - just property of base User/Role Store - I cannot use this mechanism.
Could you provide workaround for implement this functionality?

Thank you.

**Comment by HaoK** [comment]
You can try doing some kind of reflection/base type inspection to set AutoSaveChanges, we do that ourselves to do things like determine what's the appropriate store class to put in DI based on the user/dbcontext types.

See https://github.com/aspnet/AspNetCore/blob/master/src/Identity/EntityFrameworkCore/src/IdentityEntityFrameworkBuilderExtensions.cs#L33

**Comment by michaeldz** [comment]
@HaoK You be able to do it more or less easy because you have user (or role) type. You can receive the types from the builder, but in my case I don't have the types, unfortunately. This is problem.

**Comment by michaeldz** [comment]
@HaoK So am I right that there is no solution for my case?

**Comment by HaoK** [comment]
Not really, to do anything with identity you need to know the user type for the app, once you have the user type you can do reflection against the store just like we do

**Pull request closed without merging**
