### PR TITLE
Added missing post-DNVM-install step for OSX

### PR DESCRIPTION
**Pull request by chrisbrinkman**
Added missing post-DNVM-install instructions for OSX

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@chrisbrinkman__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, MSOTBOT;

**Comment by jasonwilliams200OK** [comment]
IMO, the title of PR should depict what has changed, instead of "Update README.md". (you can still edit the title)

**Comment by chrisbrinkman** [comment]
Fixed

**Comment by slowmove** [comment]
@chrisbrinkman thank you

**Comment by jasonwilliams200OK** [comment]
Thanks @chrisbrinkman. :+1: 
IMO, this PR is ready for merging.

**Comment by jasonwilliams200OK** [comment]
Also, this closes #505.

**Comment by glennc** [comment]
This would clarify what was in the other PR, right? Can we rebase and I'll merge it?

**Comment by PatrickNausha** [comment]
See #684 for a more minimal fix of the `source dnvm.sh` issue.

**Comment by Eilon** [comment]
Closing because this is no longer needed. Thanks!

**Pull request closed without merging**
