### PR TITLE
Renamed brew tap to `aspnet/dnx`

### PR DESCRIPTION
**Pull request by henkmollema**
Should be `aspnet/dnx` since the [Homebrew repo](https://github.com/aspnet/homebrew-dnx) was renamed from `homebrew-k` to `homebrew-dnx`

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@henkmollema__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft Open Technologies, Inc. and real humans are currently evaluating your PR.</p>

TTYL, MSOTBOT;

**Comment by Eilon** [comment]
@glennc @BrennanConroy do you know what this is supposed to be?

**Comment by Eilon** [comment]
@moozzyk too.

**Comment by BrennanConroy** [comment]
aspnet/dnx is the new one, Glenn must have mistyped :D

**Comment by Eilon** [comment]
This does look right to me though.

**Comment by Eilon** [comment]
Merged https://github.com/aspnet/Home/pull/492 instead because it had some other small fixes.

@BrennanConroy got it :smile:

**Comment by henkmollema** [comment]
:+1:

**Pull request closed without merging**
