### PR TITLE
Add 'dotnet new' web item templates (razor view, api controller, mvc controller)

### PR DESCRIPTION
**Pull request by deepchoudhery**
# Add dotnet new web item templates
Summary of the changes (Less than 80 chars)

## Description

added new `dotnet new` web item templates
Razor View:
- added `view` (maybe should be `razorview`? feedback pls)
- adds an empty razor view (Index.cshtml) to the project.
- ConEmu64_pMamlKQhCQ

API Controller:
- added `apicontroller`
- adds an empty API Controller.
- use `--actions` to add one with read/write actions.
- ConEmu64_6rz00QQnZi

MVC Controller:
- added `mvccontroller`
- adds an empty MVC Controller.
- use `--actions` to add one with read/write actions.
- ConEmu64_UXdzbOuePN

Update the doc [here](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new) for .NET 8??

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

### CODE REVIEW

**Comment by sebastienros** [comment]
This PR is failing on `Failed Templates.Test.ByteOrderMarkTest.RazorFilesInWebProjects_ShouldContainBOM(projectName: "Web.ItemTemplates") `

**Comment by deepchoudhery** [comment]
> RazorFilesInWebProjects_ShouldContainBOM

Looking at tyty

**Comment by deepchoudhery** [comment]
> This PR is failing on `Failed Templates.Test.ByteOrderMarkTest.RazorFilesInWebProjects_ShouldContainBOM(projectName: "Web.ItemTemplates") `

changed encoding in VS Code for the template causing the issue, hoping that fixes it.

**Comment by mkArtakMSFT** [comment]
@MackinnonBuck can you please review this? Thanks!

**Review by mkArtakMSFT — APPROVED** [review]

**Comment by mkArtakMSFT** [comment]
@deepchoudhery do you have permissions to merge or do you want me to merge this?

**Pull request merged**
