### PR TITLE
Remove blazor template content projects from .sln. Can still run directly from commandline.

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
This is a quick way of sidestepping [the Win7 "path too long" build error](https://github.com/aspnet/AspNetCore-Internal/issues/1578#issuecomment-450937444) in the short term. Once we've reorganized the `src/Components/*` file layout the issue would go away on its own too, but that may take more time.

This PR is to stop building the Blazor templates **content** projects in CI. To be clear, by "content projects", I mean the projects that the templates produce, not the template project itself. There is no strict reason why we need the content projects to get built. It is kind of nice to do so (could catch some regression theoretically) but it's irrelevant if we also have E2E tests on the template projects anyway, so we're OK without it.

### CODE REVIEW

**Review by rynowak — APPROVED** [review]

**Review by rynowak — APPROVED** [review]

**Comment by SteveSandersonMS** [comment]
The CI failure has nothing to do with this PR.

**Comment by rynowak** [comment]
I retried it. I think there's been some flakiness with the identity UI packages on *nix the past few days. @haok - I thought this was resolved?

**Review by ryanbrandenburg — APPROVED** [review]
If this is a short-term fix that we should revert eventually (to get that extra regression protection) there should be an issue filed to track reverting it. Approved once that's done.

**Comment by HaoK** [comment]
Nate has a fix for the identity UI views sometimes being missing in https://github.com/aspnet/AspNetCore/pull/6369 but I'm not sure if that's the same issue you were referring to @rynowak

**Pull request merged**
