### PR TITLE
Revert "[main] Update dependencies from dotnet/arcade"

### PR DESCRIPTION
**Pull request by wtgodbe**
Breaks local builds: https://github.com/dotnet/arcade/issues/13911

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
@wtgodbe Do we have any CI jobs failing with this build break? Looks like none of the PR jobs actually build these IIS tests so it's a blindspot in coverage.

**Comment by wtgodbe** [comment]
I think the Helix job builds them: https://github.com/dotnet/aspnetcore/blob/bf303a1092f83d789031fdafac60f3fc454cfc49/.azure/pipelines/ci.yml#L710-L711

**Comment by wtgodbe** [comment]
e.g. https://dev.azure.com/dnceng-public/public/_build/results?buildId=345374&view=logs&j=3f6d4e0f-1b71-56b5-361e-d95b6e6da15a&t=9605d305-57d3-55b8-ba79-e50442d32137&l=1993

**Comment by adityamandaleeka** [comment]
Uh, looks like `-ci` makes it pass. 😖

**Comment by wtgodbe** [comment]
> Uh, looks like -ci makes it pass. 😖

Weird - at least that's a datapoint 😆. I mentioned that in the Arcade issue. Could you approve this PR?

**Review by adityamandaleeka — APPROVED** [review]

**Pull request merged**
