### PR TITLE
Adjust shared framework and targeting pack tests to check _all_ assembly versions

### PR DESCRIPTION
**Pull request by dougbu**
- check against potentially-different versions for dotnet/aspnetcore and dotnet/runtime assemblies
- backport parts of 416b981cc484
  - was "Update branding to 8.0.0-alpha1 (#43307)"

### CODE REVIEW

**Comment by dougbu** [comment]
Aside from minimizing merge conflicts, this PR expands the assemblies checked in a couple of our App.UnitTests tests and avoids some updates the next time we do major / minor rebranding.

**Comment by dougbu** [comment]
@wtgodbe at this point, we don't need to worry about `tell-mode` labeling in this branch, do we❔

**Review by wtgodbe — APPROVED** [review]

**Comment by wtgodbe** [comment]
> @wtgodbe at this point, we don't need to worry about tell-mode labeling in this branch, do we❔

I'm not sure, but my guess would be yes since it's for rc2. I'll see if I can get a bar check in tactics today

**Comment by dougbu** [comment]
> I'll see if I can get a bar check in tactics today

To be clear, the bar isn't really the issue because this is (and #43357 was) a test-only change. The bar's interesting of course but I was just wondering whether we needed to label PRs that pass pretty much any bar.

**Comment by wtgodbe** [comment]
Whoops, didn't mean to disable auto-merge

**Comment by wtgodbe** [comment]
RC2 isn't in ask mode yet, so no need for tell-mode label here.

**Pull request merged**
