### PR TITLE
Preserve client order of activity baggage items

### PR DESCRIPTION
**Pull request by AndreyTretyak**
AddBaggage in reverse order to be the same as on the client

Addresses #26303

### CODE REVIEW

**Comment by Tratcher** [comment]
Test failure:
https://dev.azure.com/dnceng/public/_build/results?buildId=830373&view=ms.vss-test-web.build-test-results-tab&runId=26468712&resultId=105063&paneView=debug
Microsoft.AspNetCore.Hosting.Tests.HostingApplicationDiagnosticsTests.ActivityBaggagePreservesItemsOrder
```
Assert.Equal() Failure
Expected: KeyValuePair`2[] [[Key1, value1], [Key2, value2], [Key1, value3]]
Actual:   <<get_Baggage>g__Iterate|71_0>d [[Key1, value3], [Key2, value2], [Key1, value1]]
```

**Comment by AndreyTretyak** [comment]
Sorry, I forgot to mention. 
There is a bug now in Activity for net5.0 https://github.com/dotnet/runtime/pull/42659
After it would be fixed we would get previous behaivour of the `Activity` and UT should start working :)

**Comment by Tratcher** [comment]
@shirhatti @davidfowl @Pilchie is this a 5.0 candidate? It looks like the runtime PR was backported to 5.0.

**Comment by davidfowl** [comment]
This is broken in 3.x as well no?

**Comment by AndreyTretyak** [comment]
So `HostingApplicationDiagnostics.cs` behaivour was changing `Activity.Baggage` order in version 3.x, but in net5.0 preview version of the `Activity` there was a breaking change and in combination they worked properly. After `Activity` bug will be fixed in would be broken again (if we won't make the change).

**Comment by AndreyTretyak** [comment]
As far as I understand you are quite close to the 5.0 release, but in case if for some reason you're still considering including this fix I'll add some details why it's more important before `net6.0`. 

Currently, the only way of changing `Activity.Baggage` is to call `AddBagggage` and if you call it twice for the same key it would look like the value was updated, but you're actually getting two values with the same key and after transfer `GetBaggageItem` will start returning the old value. So this case might be more common then it looks. 

`net6.0` should have an API for updating `Baggage`(https://github.com/dotnet/runtime/issues/42706) and it might reduce the number of cases with the duplicated keys.

**Review by Tratcher — APPROVED** [review]

**Comment by Tratcher** [comment]
I don't see folks pushing to get this into 5.0 so it's been merged into master for 6.0.

**Comment by AndreyTretyak** [comment]
Okay, thanks, do I need to do something with the bug attached or it's up to you?

**Comment by shirhatti** [comment]
We should create a breaking change announcement for this behavior change

**Pull request merged**
