### PR TITLE
Added ResourcesAssembly property to LocalizationOptions to set different Assembly for localization resources.

### PR DESCRIPTION
**Pull request by caioliberali**
Added **ResourcesAssembly** property  to **LocalizationOptions** to set different Assembly for localization resources.
_It falls back to default Assembly if the resource is not found_.

So we can avoid **RootNamespaceAttribute** [https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-5.0#rootnamespaceattribute-2](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-5.0#rootnamespaceattribute-2) ( which I was unable to use ) and _keep the location settings in a single place_.

### Summary of the changes
Implementation:

**aspnetcore\src\Localization\Localization\src**
- Microsoft.Extensions.Localization.LocalizationOptions 
- Microsoft.Extensions.Localization.ResourceManagerStringLocalizerFactory
 
Tests:

**aspnetcore\src\Mvc\test\WebSites\RazorWebSite**
- RazorWebSite.StartupDataAnnotations 
- RazorWebSite.StartupDataAnnotationsProvider
- RazorWebSite.StartupDataAnnotationsLocalization
- RazorWebSite.StartupDataAnnotationsLocalizationProvider
- RazorWebSite.Controllers.ViewEngineController.cs
- RazorWebSite.Views.ViewEngineViewWithLocalization.cshtml
- RazorWebSite.Views.ViewEngineViewWithLocalizationAssembly.cshtml 
- RazorWebSite.Models.ContactModel.cs
- RazorWebSite.Models.ContactLocalizationModel.cs ( resource in **RazorWebSite.Localization** )
- RazorWebSite.Resources.Views.ViewEngineViewWithLocalization.resx

**aspnetcore\src\Mvc\test\WebSites\RazorWebSite.Localization**
- RazorWebSite.Localization ( **Class Library** for different resources ) 

### How to test
Building RazorWebSite change to StartupDataAnnotations* class in Startup.
Urls:
- localhost:<port>/enum/enum ( DataAnnotation provider local/separate Assembly )
- localhost:<port>/viewengine/viewwithlocalization ( local resources )
- localhost:<port>/viewengine/viewwithlocalizationassembly ( separate Assembly )

### Example of use
`services.AddLocalization((options) =>
 {
 options.ResourcesAssembly = typeof(SingleTypeLocalization).Assembly;
 });`

### Issues with RootNamespaceAttribute
[https://stackoverflow.com/questions/37286285/how-to-set-the-root-namespace-in-project-json-for-net-core](https://stackoverflow.com/questions/37286285/how-to-set-the-root-namespace-in-project-json-for-net-core)
[https://stackoverflow.com/questions/50925615/how-to-set-default-namespace-in-a-net-core-2-1-project](https://stackoverflow.com/questions/50925615/how-to-set-default-namespace-in-a-net-core-2-1-project)
[https://stackoverflow.com/questions/35602236/how-to-set-the-default-namespace-in-projects-using-project-json-xproj](https://stackoverflow.com/questions/35602236/how-to-set-the-default-namespace-in-projects-using-project-json-xproj)

### Issues with resources in different Assembly
[https://stackoverflow.com/questions/42044458/asp-net-core-localized-resource-in-separate-assembly](https://stackoverflow.com/questions/42044458/asp-net-core-localized-resource-in-separate-assembly)
[https://stackoverflow.com/questions/45167350/localization-in-external-class-libraries-in-asp-net-core](https://stackoverflow.com/questions/45167350/localization-in-external-class-libraries-in-asp-net-core)
[https://stackoverflow.com/questions/58293607/asp-net-core-data-annotation-localization-when-models-are-in-a-different-assembl](https://stackoverflow.com/questions/58293607/asp-net-core-data-annotation-localization-when-models-are-in-a-different-assembl)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=28972) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=28972) before we can accept your contribution.<br/><br/>:x: caioliberali [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=28972)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=28972) it.</sub>

**Comment by pranavkm** [comment]
Thanks for the PR @caioliberali. We usually prefer starting with an issue discussing a feature request and suggesting a design before looking at code. 

From the StackOverflow links you provided, the answer in https://stackoverflow.com/a/50668267 would appear to solve the problem you're trying to tackle here. Is there a reason that answer does not work?

**Comment by caioliberali** [comment]
Thank you @pranavkm! When creating the Pull Request I saw about the issue discussions.
I really should have looked for/created an issue about it but I was looking for answers instead. I'm sorry!

> From the StackOverflow links you provided, the answer in https://stackoverflow.com/a/50668267 would appear to solve the problem you're trying to tackle here. Is there a reason that answer does not work?

The answer is as a "workaround" to the problem, you can see in the discussion that it is not a complete solution:

> what about attribute based localizations? (data annotations on viewmodels or enums)

> I tried this it refuses to work in 3.1 unless the resources our in the main assemlby any ideas

When changing the code, I was trying to do something that worked the same way that it works for the local assembly. For Models, Views, DataAnnotations, etc.

Thank you again @pranavkm !

**Comment by mkArtakMSFT** [comment]
Hi. Looks like there is no activity on this PR for quite some time now. @pranavkm is there anything pending here from our side? If not, it's quite old and we should probably close this.

**Comment by pranavkm** [comment]
Unfortunately I hadn't looked at this PR, but given it's fairly out of date (lots of conflicting files) and there isn't a associated issue discussing it, I'll close it.

**Pull request closed without merging**
