### PR TITLE
[TS Client] Catch exception in onreceive and close connection

### PR DESCRIPTION
**Pull request by BrennanConroy**
Backport https://github.com/aspnet/AspNetCore/pull/15082 to 3.1

@Pilchie for 3.1 bug approval

### CODE REVIEW

**Comment by Pilchie** [comment]
Can you explain the justification for the backport?  This issue is not a regression from 2.2 at least, is it from 2.1?   Are there workarounds customers can apply?

**Comment by BrennanConroy** [comment]
The original customer reported issue is [here](https://github.com/aspnet/AspNetCore/issues/13276).

Pretty sure this has always been an issue (2.1+), but no one noticed until recently with 2.2.

**Comment by Pilchie** [comment]
In that case, I don't see how it meets the bar for 3.1 at this point.  We're trying to only take fixes that we would service for.

**Comment by BrennanConroy** [comment]
I could be convinced to port this to 2.1 as well or to just leave the fix in 5.0

**Comment by Pilchie** [comment]
We don't take fixes for 2.1 unless a customer asks us for the fix through CSS.

**Pull request closed without merging**
