### PR TITLE
Revert "Switch to CreateAsyncScope (#32849)"

### PR DESCRIPTION
**Pull request by JunTaoLuo**
This reverts commit be26b8fc70c7a43419307b6aec6b61a1aff0e3bd.

It looks like the original PR https://github.com/dotnet/aspnetcore/pull/32849 is breaking the build so here's a revert PR. Will merge if CI passes to unblock build.

### CODE REVIEW

**Review by captainsafia — APPROVED** [review]
Just ran into this on a PR of mine. Thanks for opening the PR.

Is there a reason this didn't happen in the checks for the original PR?

**Comment by BrennanConroy** [comment]
What was the break?

**Comment by BrennanConroy** [comment]
> Is there a reason this didn't happen in the checks for the original PR?

The last build of that PR was 15 days ago, so if anything changed that didn't cause a merge conflict but caused behavioral changes it wouldn't have been caught. This is one reason folks should re-run the CI on stale PRs.

**Comment by JunTaoLuo** [comment]
Looks like the break was caused because a test was added parallel to the original PR and the combined changes started to fail the build. @pranavkm will send a fix soon so I won't proceed with this revert.

**Comment by JunTaoLuo** [comment]
Fix at https://github.com/dotnet/aspnetcore/pull/33256.

**Pull request closed without merging**
