### PR TITLE
Make IDE0055 formatting rules suggestions

### PR DESCRIPTION
**Pull request by dougbu**
- alternate to #40173

### CODE REVIEW

**Comment by dougbu** [comment]
Not sure what `area-` label to use here. Suggestions❔

**Review by pranavkm — APPROVED** [review]

**Comment by dougbu** [comment]
Whoa, that's a regression. I can't enable auto-squish here ☹️ @dotnet/aspnet-build @mmitche has something changed under the covers❔ The "enable auto-merge" setting is still on in this repo's settings.

**Comment by sharwell** [comment]
@dougbu This sounds like a serious regression in the SDK. Have you filed a bug report or looked for a resolution with the Roslyn team?

**Comment by mmitche** [comment]
> > Whoa, that's a regression. I can't enable auto-squish here ☹️ https://github.com/orgs/dotnet/teams/aspnet-build @mmitche has something changed under the covers❔ The "enable auto-merge" setting is still on in this repo's settings.
> 
> Not sure, I still see it as an option on other PRs

I think it's a bug. I have seen it in a few other repos too but I can't figure out what the pattern is yet.

**Comment by dougbu** [comment]
Circling back: My issue was apparently me having `git config --global --add core.autocrlf true` in the WSL Ubuntu environments. This feels like an analyzer bug because `csc` is fine w/ Windows line endings in every environment but the analyzer is not.

**Pull request merged**
