### PR TITLE
Workaround template fix for incorrect file encoding when the first line is a conditional statement

### PR DESCRIPTION
**Pull request by ajaybhargavb**
Fixes https://github.com/dotnet/aspnetcore/issues/18058

This is a workaround for the issue https://github.com/dotnet/templating/issues/2217.

### CODE REVIEW

**Comment by ajaybhargavb** [comment]
### Description

When creating a new Blazor project from template, App.razor is generated as ANSI instead of UTF-8. This is an issue with our templating engine which is tracked [here](https://github.com/dotnet/templating/issues/2217)

### Customer Impact

Reported by two customers. Unicode characters in App.razor are not rendered in the browser correctly.

### How found

Customer report

### Test coverage

Manually verified the workaround. Working on adding a recurring test to be run by vendors.

### Regression?

Yes, from 3.0 to 3.1

### Risk

Low

**Comment by timheuer** [comment]
Suggest a quick re-title of this to explain better. "Workaround template fix for incorrect code page when conditionals are first line"

**Review by mkArtakMSFT — APPROVED** [review]
Thanks Ajay!

**Comment by mkArtakMSFT** [comment]
This is approved by tactics for February release. I'll merge this when it's time.

**Comment by mkArtakMSFT** [comment]
@wtgodbe the checks have passed, however the build failed with a warning: https://dev.azure.com/dnceng/public/_build/results?buildId=483124&view=logs&j=0bc77094-9fcd-5c38-f6e4-27d2ae131589&t=f08468a4-3967-5028-87bf-6754c351b1e1

Can you please have a look at it?

**Comment by wtgodbe** [comment]
@mkArtakMSFT the build you linked is an internal build of Blazor's master branch. This PR did have some warnings, but none that failed the build - would you like me to take a look at those?

**Comment by mkArtakMSFT** [comment]
> @wtgodbe the checks have passed, however the build failed with a warning: https://dev.azure.com/dnceng/public/_build/results?buildId=483124&view=logs&j=0bc77094-9fcd-5c38-f6e4-27d2ae131589&t=f08468a4-3967-5028-87bf-6754c351b1e1
> 
> Can you please have a look at it?

This is not urgent, as the package is produced successfully.

**Comment by mkArtakMSFT** [comment]
> @mkArtakMSFT the build you linked is an internal build of Blazor's master branch. This PR did have some warnings, but none that failed the build - would you like me to take a look at those?

No need to do anything yet, actually. Given that the package is produced, I would like to first understand why the warning is there. I'll follow up with the team. If help will be needed, I'll ask separately. For now - ignore this request please. Thanks!

**Pull request merged**
