### PR TITLE
Update SDK

### PR DESCRIPTION
**Pull request by wtgodbe**

### CODE REVIEW

**Review by dougbu — APPROVED** [review]

**Comment by wtgodbe** [comment]
Starting to see `CS8981`:

> D:\a\_work\1\s\artifacts\obj\Microsoft.AspNetCore.Grpc.JsonTranscoding\Release\net7.0\Internal\Protos\Errors.cs(8,7): error CS8981: The type name 'pb' only contains lower-cased ascii characters. Such names may become reserved for the language. [D:\a\_work\1\s\src\Grpc\JsonTranscoding\src\Microsoft.AspNetCore.Grpc.JsonTranscoding\Microsoft.AspNetCore.Grpc.JsonTranscoding.csproj]
D:\a\_work\1\s\artifacts\obj\Microsoft.AspNetCore.Grpc.JsonTranscoding\Release\net7.0\Internal\Protos\Errors.cs(9,7): error CS8981: The type name 'pbc' only contains lower-cased ascii characters. Such names may become reserved for the language. [D:\a\_work\1\s\src\Grpc\JsonTranscoding\src\Microsoft.AspNetCore.Grpc.JsonTranscoding\Microsoft.AspNetCore.Grpc.JsonTranscoding.csproj]
D:\a\_work\1\s\artifacts\obj\Microsoft.AspNetCore.Grpc.JsonTranscoding\Release\net7.0\Internal\Protos\Errors.cs(10,7): error CS8981: The type name 'pbr' only contains lower-cased ascii characters. Such names may become reserved for the language. [D:\a\_work\1\s\src\Grpc\JsonTranscoding\src\Microsoft.AspNetCore.Grpc.JsonTranscoding\Microsoft.AspNetCore.Grpc.JsonTranscoding.csproj]
D:\a\_work\1\s\artifacts\obj\Microsoft.AspNetCore.Grpc.JsonTranscoding\Release\net7.0\Internal\Protos\Errors.cs(11,7): error CS8981: The type name 'scg' only contains lower-cased ascii characters. Such names may become reserved for the language. [D:\a\_work\1\s\src\Grpc\JsonTranscoding\src\Microsoft.AspNetCore.Grpc.JsonTranscoding\Microsoft.AspNetCore.Grpc.JsonTranscoding.csproj]

Looks like that's this sample: https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/SignalR/samples/SocialWeather/Protobuf/WeatherReport.cs#L8-L11. The sample claims to be auto-generated but I don't see anything that looks like the mentioned variables in `WeatherReport.proto` - @JamesNK how should we update those vars?

**Comment by wtgodbe** [comment]
Hmm, maybe it wasn't the sample, it could be something in protobuf always auto-generates `using`s with lowercase naming (hence the error being from `artifacts\obj\Microsoft.AspNetCore.Grpc.JsonTranscoding\Release\net7.0\Internal\Protos\Errors.cs`) . @JamesNK do you know if that's the case?

**Comment by JamesNK** [comment]
I raised it as something to fix in Grpc.Tools here: https://github.com/grpc/grpc/issues/29672

For now, this warning needs to be suppressed in csproj.

**Comment by JamesNK** [comment]
image

Warnings are showing up in the gRPC template test. I think you need to temporarily quartine it. I have created a PR to fix this in Protobuf sourcegen, but I think it'll take a couple of months to flow through to a package we can reference to fix this warning.

**Comment by wtgodbe** [comment]
@JamesNK I opened https://github.com/dotnet/aspnetcore/issues/41716 & assigned it to both of us

**Pull request merged**
