### PR TITLE
Remove FormatScope from FacebookHandler

### PR DESCRIPTION
**Pull request by Kahbazi**
Remove overridden `FormatScope` method since all it's doing is calling its base.

### CODE REVIEW

**Comment by Tratcher** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=449180

**Comment by Tratcher** [comment]
@anurse this is binary breaking but should be acceptable across a major version. This is not an API apps call directly, it's only called from within the base class.

**Review by Tratcher — APPROVED** [review]

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2730
https://github.com/aspnet/AspNetCore-Internal/issues/3241

**Comment by anurse** [comment]
Background context for API/Breaking change review:

* This class *used* to override this base class method and do something different
* We removed that need in a previous version but left the empty override in place to be non-breaking
* This **does** technically break in IL for anyone deriving from `FacebookHandler` and calling `base.FormatScope`

**Comment by anurse** [comment]
API review sentiment is: If we're just removing the override, it doesn't seem to have enough value to make it worth it. It's been justified because "nobody should really be deriving from `FacebookHandler`" but the type is not `sealed`, so that's not really what's expressed in the code. We *could* consider a change to make this type `sealed`, if we truly believe these types should not be derived from.

Otherwise, we should treat derivation as an intended scenario and evaluate breaking changes based on that context. Since this has almost no value aside from code clean-up (that we can tell), it doesn't feel worth the break.

@Tratcher @davidfowl for thoughts on if we should just decline this change or consider making it `sealed`. My hunch is we don't want to make these types `sealed`.

**Comment by anurse** [comment]
After discussions with @Tratcher I think we'll close this. This was a good test case for how we want to handle breaking changes moving forward (even though it's a fairly trivial change, it gave us a chance to really test our understanding of the cost/benefit analysis here).

Thanks for the contribution @Kahbazi ! I know it probably seems like we over-discussed this a bit ;).

**Pull request closed without merging**
