### PR TITLE
fix #11114 by setting DesignerCategory for WebHostService

### LINKED ISSUE #11114: Mark WebHostService with DesignerCategory("Code")
If a user derives from `WebHostService`, VS tries to open the file in the Component designer, which is the wrong experience. We can stop this easily by just applying to `[DesignerCategory("Code")]` attribute to the class to suppress this behavior.

cc @Pilchie @Tratcher

### PR DESCRIPTION
**Pull request by analogrelay**
This time for reals. We're doing the 2.1/2.2 fixes via fixing the doc (https://github.com/aspnet/AspNetCore.Docs/pull/12823).

Fixes #11114

### CODE REVIEW

**Review by Pilchie — APPROVED** [review]

**Comment by anurse** [comment]
From @Pilchie in [a different thread](https://github.com/aspnet/AspNetCore.Docs/pull/12823):

> Just a note that the reason this is surfacing now is that the .NET Core Project system didn't used to obey the [DesignerCategory] attribute, but it now needs to in order for Winforms to work properly in 3.0, so that was done in VS 2019.

Yes, I realize this type is no longer the intended way to do this in 3.0 (use Worker Service instead). The [doc does reflect that in the 3.0 pivot](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-3.0&tabs=visual-studio). Still, this type is here and we don't want to break people if they use it.

**Comment by Tratcher** [comment]
```
src\Hosting\WindowsServices\ref\Microsoft.AspNetCore.Hosting.WindowsServices.netcoreapp3.0.cs(,): error : Generated code is not up to date in src/Hosting/WindowsServices/ref/Microsoft.AspNetCore.Hosting.WindowsServices.netcoreapp3.0.cs. You might need to regenerate the reference assemblies or project list (see docs/ReferenceAssemblies.md and docs/ReferenceResolution.md)
```

**Comment by anurse** [comment]
Boo! Yeah, ref-asms do something with attributes so I guess that makes sense.

**Comment by anurse** [comment]
@aspnet/build it seems unlikely that my change cause the build to start hanging (especially only the Windows x86 build)... is there a known issue with hanging builds right now?

**Comment by dougbu** [comment]
> is there a known issue with hanging builds right now?

Yes, we've seen this a lot and it may be limited to this repo. @JunTaoLuo is looking into the issue.

**Comment by anurse** [comment]
Merging as Helix shouldn't be affected by this.

**Pull request merged**
