### PR TITLE
[release/5.0] Update dependencies from dnceng/internal/dotnet-runtime

### PR DESCRIPTION
**Pull request by dougbu**
- cherry-pick from internal/release/5.0
- needed to get internal merges going again
- also correct confusion in NuGet.config from e9a385d

### CODE REVIEW

**Comment by wtgodbe** [comment]
I expect this will fail because it references 5.0.4 packages

**Comment by dougbu** [comment]
> I expect this will fail because it references 5.0.4 packages

Yes. I'll see what I can undo without introducing additional conflicts&hellip;

**Comment by dougbu** [comment]
Working better now

**Comment by dougbu** [comment]
Approval plz

**Review by pranavkm — APPROVED** [review]

**Pull request merged**
