### PR TITLE
Remove use of legacy interop preventing CSP compliance in Blazor WebAssembly

### LINKED ISSUE #37787: Validate CSP for Blazor WASM
Runtime made the necessary changes that `unsafe-eval` may no longer be required for Blazor WASM: https://github.com/dotnet/runtime/issues/59416

Note, there's also a Chrome bug which may come into play here (WebAssembly/content-security-policy#7)

This issue tracks validating this fix, and the associated documentation updates.

Original CSP Issue: https://github.com/dotnet/aspnetcore/issues/34428

### LINKED ISSUE #48042: [blazor][wasm] Remaining legacy interop
Below is list of usages of legacy interop.

- [x] Usage of `BINDING.call_assembly_entry_point`
   - https://github.com/dotnet/aspnetcore/blob/730dac21a5991eb8f130717c12de22f46715b8c7/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L68
   - this one is most problematic because it uses `eval()` which is [CSP blocker](https://github.com/dotnet/aspnetcore/issues/37787)
- [ ] Usage of `BINDING.js_string_to_mono_string` in `invokeJSFromDotNet`
   - https://github.com/dotnet/aspnetcore/blob/730dac21a5991eb8f130717c12de22f46715b8c7/src/Components/Web.JS/src/Boot.WebAssembly.ts#L124
   - https://github.com/dotnet/aspnetcore/blob/730dac21a5991eb8f130717c12de22f46715b8c7/src/Components/Web.JS/src/Boot.WebAssembly.ts#L138
   - this is potentially just dead code, if the user code doesn't use the obsolete `IJSUnmarshalledRuntime`
   - but I don't fully understand `jsCallDispatcher` and `invokeJSJson` use-cases
- [ ] usage of `BINDING.unbox_mono_obj` and `BINDING.conv_string` in `readStringField` which is part of `renderBatch`
   - https://github.com/dotnet/aspnetcore/blob/730dac21a5991eb8f130717c12de22f46715b8c7/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L127
   - https://github.com/dotnet/aspnetcore/blob/730dac21a5991eb8f130717c12de22f46715b8c7/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L138
   - https://github.com/dotnet/aspnetcore/blob/730dac21a5991eb8f130717c12de22f46715b8c7/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L142
   - this is problematic from GC safety, for which we do have stop-gap solution.
   - this is probably not a problem for CSP as there is no bind/invoke and no `eval()`
- [x] `MonoHeapLock.stringCache` is pointer hazard
   - https://github.com/dotnet/aspnetcore/blob/730dac21a5991eb8f130717c12de22f46715b8c7/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L139
   - because `BINDING.conv_string` is already caching interned strings by their pointer (because they never move on GC)
   - any other strings do move and could be even collected, so the pointer could be pointing at different object and produce a) invalid value or b) crash even in single threaded app
   - this is problematic from MT GC safety, for which we do have stop-gap solution.

All of the uses prevent users trimming legacy interop dead code with `<WasmEnableLegacyJsInterop>false</WasmEnableLegacyJsInterop>`

### PR DESCRIPTION
**Pull request by MackinnonBuck**
# Remove use of legacy interop preventing CSP compliance in Blazor WebAssembly

Opening as a draft until some open questions are resolved.

Contributes to #48042
Fixes #37787

### CODE REVIEW

**Comment by MackinnonBuck** [comment]
Regarding the removal of [`invokeJSFromDotNet`](https://github.com/dotnet/aspnetcore/blob/4afe7f612d104b43b690e71d83c18a8bc48aae2d/src/Components/Web.JS/src/Boot.WebAssembly.ts#L110): This function doesn't get invoked within the framework except in some E2E tests, so we could remove it easily. That said, eliminating this function will break [external usage](https://grep.app/search?q=IJSUnmarshalledRuntime) of `IJSUnmarshalledRuntime`. Are we okay with taking that step now?

**Comment by MackinnonBuck** [comment]
By the way: According to my testing, this change will mean `unsafe-eval` is no longer required when specifying a CSP `script-src`.

**Comment by pavelsavara** [comment]
This PR should just contribute to the issue 48042, not close it. 

>  `IJSUnmarshalledRuntime`. Are we okay with taking that step now?

Perhaps we could make it throw exceptions when `WasmEnableLegacyJsInterop=false` and trim it. 
Removing it completely need to be next LTS release, I think.

**Review by pavelsavara — APPROVED** [review]

**Review by javiercn — APPROVED** [review]

**Comment by pavelsavara** [comment]
We discussed with @MackinnonBuck  that it would be good to do some perf testing before we remove that `stringCache`. 
Is it possible that there are many identical non-interned strings in the `renderBatch` ?

**Comment by MackinnonBuck** [comment]
I've marked this PR to close https://github.com/dotnet/aspnetcore/issues/37787. It should be noted that 'wasm-unsafe-eval' is still required, but that's true for any WebAssembly app.

**Review by maraf — APPROVED** [review]

**Pull request merged**
