### PR TITLE
Update to scaffolding submodules for dotnet tool resolution workaround

### PR DESCRIPTION
**Pull request by seancpeters**
Summary of the changes (Less than 80 chars)
- Update the scaffolding submodule

Addresses dotnet/sdk#2698

### CODE REVIEW

**Review by natemcmaster — APPROVED** [review]

**Comment by seancpeters** [comment]
@natemcmaster @wli3 @vijayrkn

**Comment by natemcmaster** [comment]
Once PR checks pass, feel free to merge.

FYI @muratg @mmitche @Eilon - this should resolve the last 2.2.1 bug we're expecting to take. Once it, we're ready to re-build 2.2.1

**Review by muratg — APPROVED** [review]

**Comment by seancpeters** [comment]
We got some test failures in the ci build, but they don't look related to scaffolding. I don't know much about this repo, perhaps someone who knows it better has a better understanding of what may have caused these errors.

Also, I don't have rights to merge in this repo, so once we're good, someone else will have to.

**Comment by natemcmaster** [comment]
Test failures in HttpSys and Kestrel are known, right @Tratcher @muratg ?

Merging so we can get a 2.2.1 build going.

**Comment by muratg** [comment]
Yeah, I think there are issues tracking the failures. Thanks for unblocking the 2.2.1 build!

**Pull request merged**
