### PR TITLE
Update Google Auth UserInfo endpoint

### PR DESCRIPTION
**Pull request by Tratcher**
#6069 for 2.1. The same change can be used for 2.2 and 3.0.

#### Description 
Google is [shutting down](https://developers.google.com/+/web/signin/) Google+ APIs that we were using for authentication. We need to move to a new API ASAP.
 
#### Customer Impact 
Without this change web applications will no longer be able to log users in with Google accounts starting as soon as Jan 28th.
 
#### Regression?
Yes, by Google.
 
#### Risk
Moderate, the new APIs use a different data format and users may get subtly different results.

### CODE REVIEW

**Comment by Tratcher** [comment]
@natemcmaster I assume the branches aren't open yet for Feb?

**Comment by natemcmaster** [comment]
Can you fill out the shiproom template? Shiproom meets at 11.

https://microsoft.sharepoint.com/teams/netfx/CLR/ProjectK/_layouts/OneNote.aspx?id=%2Fteams%2Fnetfx%2FCLR%2FProjectK%2FDocuments%2FTactics%2FNET%20Core%20Release%2Fnet-core-release&wd=target%28net-core-release.one%7C0CF34A20-F342-FA43-8944-18B555589A6B%2FShiproom%20Info%20and%20Templates%7C30A2770F-73EF-A74D-9C01-0D0B4BEAC431%2F%29

**Comment by natemcmaster** [comment]
@Eilon since @muratg is oof, are you going to rep for this in shiproom?

**Comment by Eilon** [comment]
Yes I will.

**Review by HaoK — APPROVED** [review]

**Review by Eilon — APPROVED** [review]

**Comment by natemcmaster** [comment]
Please wait until the release/2.1 branch has been updated to build for 2.1.8. I'll add my approval when that is done.

**Comment by Tratcher** [comment]
Offline notes: Add a quirk to revert to the prior behavior.

**Review by Eilon — CHANGES_REQUESTED** [review]
Un-signing off

**Comment by Tratcher** [comment]
Updated with the quirks switch `AppContext.SetSwitch("Switch.Microsoft.AspNetCore.Authentication.Google.UsePlus", true);`

**Review by Eilon — APPROVED** [review]
I re-approve this.

**Review by muratg — COMMENTED** [review]
Note for the shiproom: 2.2.x change will be identical to this, and it'll be a merge-PR.

**Comment by natemcmaster** [comment]
Please wait until https://github.com/aspnet/AspNetCore-Internal/issues/1610 is resolved before merging.

**Comment by jamshedd** [comment]
Approved for 2.1.8

**Comment by Tratcher** [comment]
@mikaelm12 do you want to bump the version and clear out the old packages from the list first?

**Comment by mikaelm12** [comment]
>do you want to bump the version and clear out the old packages from the list first?

Sure

**Comment by Tratcher** [comment]
Updated, but needs to rebase.

**Comment by Tratcher** [comment]
@mikaelm12 ready when you are.

**Comment by mikaelm12** [comment]
Great. The 2.1.8 branch will be ready today.

**Pull request merged**
