### PR TITLE
HybridCache: relocate to dotnet/extensions

### PR DESCRIPTION
**Pull request by mgravell**
# `HybridCache`: relocate to dotnet/extensions

Plan agreed in "tactics", 2024-08-27; `HybridCache` is jumping from dotnet/aspnetcore to dotnet/extensions and will not ship in the framework build of NET 9 RC1+. The library-specific NET 9 RC1 ship-stop is manual; this PR is to clean up for NET 9 RC2 onwards.

- remove src/Caching/Hybrid (leaves relocation README.md)
- remove from sln[f]
- remove from eng files (via automated rebuild)
- remove minimal usage from tangential benchmark project

### CODE REVIEW

**Comment by mgravell** [comment]
cross-reference: https://github.com/dotnet/extensions/pull/5391

**Comment by BrennanConroy** [comment]
Retarget PR to release/9.0 unless someone explicitly said we can re-spin RC1.

**Comment by mgravell** [comment]
@BrennanConroy will do; looks like trivial change wanted to do more than I wanted - will look on Monday

**Comment by mgravell** [comment]
@BrennanConroy  closing this, giving favor to https://github.com/dotnet/aspnetcore/pull/57670

**Pull request closed without merging**
