### PR TITLE
[Blazor][debugging] Support Debug on Chromium

### LINKED ISSUE #78907: Cannot debug Blazor Webassembly on Chromium.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Cannot debug Blazor Webassembly on Chromium.
image

### Expected Behavior

Debugging on Chromium should work just like on Chrome.

### Steps To Reproduce

On Visual Studio debug any Blazor Webassembly project with Chromium. On the browser console you can see the error message.

### Exceptions (if any)

"DEBUGGING IS NOT ENABLED" (blazor.webassembly.js)

### .NET Version

7.0

### Anything else?

ASP.NET 7.0 on VS 2022

### PR DESCRIPTION
**Pull request by thaystg**
I tested locally and these changes are enough to make it work.

Fixes https://github.com/dotnet/runtime/issues/78907

### CODE REVIEW

**Review by javiercn — APPROVED** [review]
Looks great!

**Comment by thaystg** [comment]
@javiercn do you think we should backport it?

**Comment by javiercn** [comment]
@thaystg how critical do you think it is?

**Comment by thaystg** [comment]
Probably not a lot of users will use it(maybe only the one that opened the issue), but I think there is no risk of backporting it, if I should decide, I would probably backport :)

**Comment by hiyelbaz** [comment]
Playwright comes with Chromium by default. So I think a lot of users will use it. We can setup Playwright to use installed Chrome but then webdriver version will not match. So, it can work or may break things. Anyway, thank you for the response. Is there any way to apply the patch to the current version of Blazor?

**Comment by thaystg** [comment]
> Playwright comes with Chromium by default. So I think a lot of users will use it. We can setup Playwright to use installed Chrome but then webdriver version will not match. So, it can work or may break things. Anyway, thank you for the quick response. Is there any way to apply the patch to the current version of Blazor?

Thanks for the explanation, so I vote to backport!!! :)
For workaround: maybe editing the blazor.webassembly.js file in the .nuget package folder?

**Review by TanayParikh — APPROVED** [review]
🎉

**Comment by thaystg** [comment]
Can I merge and open the backport?

**Comment by javiercn** [comment]
@thaystg no problem from my side, but we will have to fill in the servicing template.

**Comment by hiyelbaz** [comment]
```
using var playwright = await Microsoft.Playwright.Playwright.CreateAsync();

var browserConn = await playwright.Chromium.LaunchAsync(new()
{
    Headless= false,
    Channel = "chrome",
    Args= new[] { $@"--remote-debugging-port=9222" }
});

var page = await browserConn.NewPageAsync();
await page.GotoAsync($"http://localhost:{port}/counter", new() { Timeout = 10000, WaitUntil = WaitUntilState.NetworkIdle });
```
Now you can attach Blazor Wasm to VS / VS Code. In our case we use blazor wasm with native bindings (cpp/rust). There is no other way we can test them. Thank you.

**Pull request merged**
