### PR TITLE
Remove old redis packages

### PR DESCRIPTION
**Pull request by BrennanConroy**
https://github.com/aspnet/Caching/pull/437 and https://github.com/aspnet/SignalR/pull/3241 should go in at the same time

### CODE REVIEW

**Comment by natemcmaster** [comment]
PR validation is failing. Can you also update the submodules before merging this?

**Comment by natemcmaster** [comment]
Btw, I think you can remove this line too: https://github.com/aspnet/AspNetCore/blob/51c32dc4dcd9c571fd7d437472afa4f584c4b079/build/CodeSign.props#L14

**Comment by BrennanConroy** [comment]
Hmm, I don't know our story for `.All` and `.App` so maybe I shouldn't remove the dependency?

**Comment by Eilon** [comment]
`.All` is dead. It's gone.

**Comment by BrennanConroy** [comment]
:up: 📅

**Review by natemcmaster — APPROVED** [review]

**Pull request merged**
