### PR TITLE
Remove obsolete HttpContextFactory

### LINKED ISSUE #7148: Remove obsolete member in src/Http/Http/src/HttpContextFactory.cs
Remove this obsolete member in [src/Http/Http/src/HttpContextFactory.cs](https://github.com/aspnet/AspNetCore/blob/master/src/Http/Http/src/HttpContextFactory.cs#L11):

```c#
    [Obsolete("This is obsolete and will be removed in a future version. Use DefaultHttpContextFactory instead.")]
    public class HttpContextFactory : IHttpContextFactory
    {
```

And file a new issue in https://github.com/aspnet/Announcements/issues/ if this is a notable breaking change.

### PR DESCRIPTION
**Pull request by jkotalik**
Fixes https://github.com/dotnet/aspnetcore/issues/7148

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]

**Review by JamesNK — APPROVED** [review]

**Comment by davidfowl** [comment]
When we remove APIs we should to find all the nuget packages that use it and notify them (if they have an issue tracker).

**Comment by jkotalik** [comment]
I searched for the term "HttpContextFactory" and the term is also used by other packages. Doing a basic search returns thousands of matches in C# files. I believe there was a type in System.Web called HttpContextFactory, which had methods like Current/SetCurrentContext.

I went through 10 pages and I only found two examples of usage (both in tests)
https://github.com/seleningchan/dotnetcoreangularblog/blob/23dad894671fb7d040b9d3fcb1d61eb6789403e5/Ancorazor.Tests.Common/TestApplication.cs
https://github.com/Charliekalle/dotnetapp/blob/5780e9f28e642d77a90a799f170bfa6b2b5f78b5/test/Dotnetapp.Test/Setup/MockHttpContextFactory.cs

I haven't found any nuget packages using this type. Do we have a tool for checking that?

**Comment by jkotalik** [comment]
Checked with the nuget package tool, all hits were already addressed in prior versions. No package with more than 10k downloads are affected by removing this type.

**Pull request merged**
