### PR TITLE
Rename StreamPipeReaderOptions to StreamPipeReaderAdapterOptions 

### PR DESCRIPTION
**Pull request by jkotalik**
### Description

Changes the name of StreamPipeReaderOptions to StreamPipeReaderAdapterOptions to avoid a name collision with System.IO.Pipelines.

### Reason for change

Builds will fail without this change, saying that there is a nameconflict on StreamPipeReaderOptions.

### What commit caused this failure

https://github.com/dotnet/corefx/commit/dc965e16c4f71163df9de013951c95916992c908 caused this name conflict and upgrading dependencies caught it.

### Why wasn't it caught earlier?

Upgrading dependencies takes too long and no one was on top of this earlier.

### Any concerns of breaking changes?

This is a breaking change, but the type was unused and will be removed within the timeframe of preview4 to preview5.

cc @Eilon @DamianEdwards

### CODE REVIEW

**Review by dougbu — CHANGES_REQUESTED** [review]
Do not attempt to merge this into the preview 4 branch. We don't have coherent builds of EntityFrameworkCore or AspNetCore-Tooling that have pushed into the `.NET Core 3 Release` channel available yet. (The versions will actually go _backwards_.)

Suggest opening a PR that only changes the names of our methods to avoid conflicts. That'll work now and when we get new dependencies.

**Comment by anurse** [comment]
Don't worry, we also need QB approval ;). I'll sync up with you before we attempt to merge anything to preview 4.

**Comment by jkotalik** [comment]
🆙 📅

**Review by dougbu — APPROVED** [review]
Works for me but must wait for QB approval

**Comment by anurse** [comment]
QB approved. Continue to **hold** until I confirm the branch status.

**Comment by Eilon** [comment]
**QB approved for Preview 4. Please check in and watch the build stay green.**

And please also resolve https://devdiv.visualstudio.com/DevDiv/_workitems/edit/843068 when done.

**Pull request merged**
