### PR TITLE
Respect -noBuildNative for Kestrel

### PR DESCRIPTION
**Pull request by sebastienros**

### CODE REVIEW

**Comment by sebastienros** [comment]
Related comment https://github.com/dotnet/aspnetcore/pull/22017#discussion_r432738208

Without this change, Kestrel/build.cmd triggers native builds even with `-noBuildNative` which takes much more time while it's not necessary.

**Comment by sebastienros** [comment]
Another mitigation for the issue is to add `/p:BuildIisNativeProjects=false` to the command line when calling `Kestrel/build.cmd`

**Comment by BrennanConroy** [comment]
I think https://github.com/dotnet/aspnetcore/pull/39655 fixed this, now -nobuildnative works with build.cmd in kestrel

**Comment by sebastienros** [comment]
Not sure, it was just a property which got renamed. But will try with and without `/p:BuildIisNativeProjects=false`.

**Pull request closed without merging**
