### PR TITLE
Updated Angular from 7.2.5 to 8.0 using ng update #5431

### PR DESCRIPTION
**Pull request by isaacrlevin**
Summary of the changes 
 - Updated Angular from 7.2.5 to 8.0 using ng update
 - Most diffs are related to optimizations by the upgrade

Addresses #5431

### CODE REVIEW

**Comment by ryanbrandenburg** [comment]
Don't forget to add `ClientApp/browserslist` to the list of baseline files. This one is going to require closer review since it involves a fairly significant change, so it might take me a bit longer to get to.

**Comment by isaac2004** [comment]
@ryanbrandenburg sounds good, added baseline

**Review by ryanbrandenburg — COMMENTED** [review]
Couple of comments, nothing huge, mostly just formatting suggestions.

Over-all this looks good, I need to poke around at a running version to make sure everything still works, compare it to a default angular 8 app (we try to keep them similar) and get approval for the new version, but I suspect this is in a good place.

**Comment by ryanbrandenburg** [comment]
The project already had a browserslist int the ClientApp\src directory, we should remove that when we add the new one.

**Comment by ryanbrandenburg** [comment]
@isaac2004 it looks like your baseline update commit didn't have a diff? Tests still fail due to baselines.

**Comment by isaac2004** [comment]
@ryanbrandenburg super bizarre here, look at the change in baseline

image


That is where the browserslist file is, yet in the CI, it is looking at the old location, thoughts?
image

**Comment by ryanbrandenburg** [comment]
@isaac2004 that means that there's an extra browserslist file in the src directory (it existed before your PR). Delete ClientApp/src/browserslist and those tests should pass.

**Comment by ryanbrandenburg** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=218946&view=results

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2181
https://github.com/aspnet/AspNetCore-Internal/issues/2614
https://github.com/aspnet/AspNetCore-Internal/issues/2465

**Comment by isaac2004** [comment]
@ryanbrandenburg helix failed but all else passed, let me know if you have any questions.

**Comment by ryanbrandenburg** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=218947&view=results

**Review by ryanbrandenburg — APPROVED** [review]

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2489
https://github.com/aspnet/AspNetCore-Internal/issues/2648
https://github.com/aspnet/AspNetCore-Internal/issues/1979

**Comment by isaac2004** [comment]
@ryanbrandenburg can you look at this CI failure?

**Comment by ryanbrandenburg** [comment]
@isaac2004 looks like you have some peer dependencies missing/of the wrong version:
```
npm WARN @angular/core@8.0.0 requires a peer of zone.js@~0.9.1 but none is installed. You must install peer dependencies yourself.\r\n
npm WARN @nguniversal/module-map-ngfactory-loader@7.1.0 requires a peer of @angular/common@^7.1.4 but none is installed. You must install peer dependencies yourself.\r\n
 npm WARN @nguniversal/module-map-ngfactory-loader@7.1.0 requires a peer of @angular/core@^7.1.4 but none is installed. You must install peer dependencies yourself.\r\n
 npm WARN @nguniversal/module-map-ngfactory-loader@7.1.0 requires a peer of @angular/platform-server@^7.1.4 but none is installed. You must install peer dependencies yourself.\r\n
```

**Comment by ryanbrandenburg** [comment]
@isaac2004 seems we've also run into merge conflicts from one of my PR's that updates versions. Select the angular 8 versions for conflicts in package.json and rather than trying to resolve the package-lock.json file by hand just delete it and run `npm install` in that directory, then add the file back.

**Pull request merged**
