### PR TITLE
Revert "Skip AddressRegistrationTests Hostname tests on macOS (#30012)"

### PR DESCRIPTION
**Pull request by pranavkm**
This reverts commit 6dc17a44650a0056959a5cd49e7530d835ae65ec.

### CODE REVIEW

**Comment by jkotalik** [comment]
😢

**Review by jkotalik — APPROVED** [review]

**Comment by Tratcher** [comment]
I know you've talked about it elsewhere, but please include the "why" here for tracking.

**Comment by jkotalik** [comment]
Still failing on Ubuntu 16.04

**Comment by pranavkm** [comment]
Do we need an issue tracking this being quarantined?

**Comment by dougbu** [comment]
> Do we need an issue tracking this being quarantined?

Suggest reopening #27377 then getting this in ASAP since failures seem pretty frequent

**Comment by dougbu** [comment]
(failures in aspnetcore-helix-matrix can be ignored; that's not required for PRs and @JunTaoLuo is getting rid of its execution in #30077)

**Pull request merged**
