### PR TITLE
Remove unused directory in ANCM installers

### PR DESCRIPTION
**Pull request by HaoK**
Might be unused, build succeeds without them so safe to delete? There's a wix3 directory which seems to be the newer and referenced version...

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]
I think this is fine, but please make sure installing the hosting bundle still works as expected. And please wait for @joeloff's signoff as well

**Comment by joeloff** [comment]
If you're not relying on these custom actions it should be fine. It looks like the full IIS set was just pulled into the build in case they were needed.

**Review by joeloff — APPROVED** [review]
Building the MSI is one thing, but please verify that the MSI still runs properly or compare a previous copy of ANCM with one built with this changes and look at the custom action and InstallExecute tables to see if there are obvious differences. You can use Orca for that

**Comment by HaoK** [comment]
I'm just going to close this PR unless either one of you feel strongly that this is worth doing

**Comment by joeloff** [comment]
I

> Okay, this sounds scary for minimial gain, so are you saying this has functional behavior differences in that the msi potentially will fail in some code paths without these wix? I was counting on compilation detecting if it was being used.
> 
> If that's not the case I don't think its worth doing this as a preemptive cleanup

All of this was written by the IIS team and pulled into ANCM. It's very likely that it's unused, but since I don't know the code well, I was just saying to do additional checks to be safe.

**Pull request closed without merging**
