### PR TITLE
Update http3 RequiresPreviewFeatures attributes with message/URL

### LINKED ISSUE #36450: HTTP/3: Improve the preview features warning message.
The preview attribute supports a custom error message and URL. This is supported in latest .NET 6 runtime - https://github.com/dotnet/runtime/issues/56498

We should update the attribute with a user-friendly error message and include the aka.ms a link to the docs - https://aka.ms/aspnet/kestrel/http3reqs

- [ ] Update Kestrel preview attribute with custom error message and URL
- [ ] Verify error message works in VS2022

### PR DESCRIPTION
**Pull request by adityamandaleeka**
Fixes https://github.com/dotnet/aspnetcore/issues/36450

Keeping in draft while we confirm this actually works "for real" in VS. It doesn't work yet with the current SDK.

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
@pgovind Is this feature ready for use?

**Comment by pgovind** [comment]
> Is this feature ready for use?

.NET 6 is not going to support showing a message/URL in the analyzer diagnostic. All diagnostic currently point to `aka.ms/dotnet-warnings/preview-features`. We just didn't have enough time to bake that into RC2. The analyzer itself will be turned on with a severity of Error by default in RC2 though. As a workaround, we could consider adding some blurbs specific to Http3 at aka.ms/dotnet-warnings/preview-features when it comes online?

cc @jeffhandley

**Comment by adityamandaleeka** [comment]
Thanks @pgovind. So if we were to merge this now, the feature would light up at some point in the future?

I don't have a strong preference on whether we need to include http3-specific messaging on the general "what are preview features" link, though it may be interesting to have a page for each release going forward that has a list of features that are considered preview in that release, and to point to that from the general preview features link.

**Comment by adityamandaleeka** [comment]
@pgovind Can you confirm if this is correct:

> So if we were to merge this now, the feature would light up at some point in the future?

**Comment by pgovind** [comment]
>  So if we were to merge this now, the feature would light up at some point in the future?

Apologies, I missed the notification for the previous comment. Indeed, this will light up in the future as soon as https://github.com/dotnet/roslyn-analyzers/pull/5502 is merged and the bits flow everywhere.

**Review by wtgodbe — APPROVED** [review]

**Review by JamesNK — APPROVED** [review]

**Pull request merged**
