### PR TITLE
Dougbu/check.solution.filters

### PR DESCRIPTION
**Pull request by dougbu**
- clean up CodeCheck.ps1
  - avoid aliases
  - rework long lines
  - avoid deprecated `dotnet run -p`
  - improve output a bit
  - correct whitespace
- there can be only one
  - we have just one solution file
  - solution file should mention projects _once_
- check solution filters
  - confirm all mentioned projects are in AspNetCore.sln
- add missing projects to AspNetCore.sln
  - Middleware.slnf contained projects that no longer exist eg. NodeServices
    - VS also sorted the file and VS 2019 added ARM64 configurations
  - a few other solution filters still referenced removed and moved projects
  - correct capitalization in some solution filters

Note: Unable to load some WiX projects in VS 2019 or _any_ in VS 2022 (WiX extension unavailable for 2022)
- gave up on getting those into AspNetCore.sln; removed them from the relevant solution filters

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]

**Comment by wtgodbe** [comment]
What did you do to regenerate the .sln/.slnf files? Also, what do you mean by "we have just one solution file"?

**Comment by dougbu** [comment]
> What did you do to regenerate the .sln/.slnf files?

A combination of VS 2019 and 2022. WiX doesn't have a VS extension for `*.wixproj` projects yet ☹️ but they should have something by the time 2022 reaches RTM 😄

I suspect people made manual changes to solution filters and neglected AspNetCore.sln for a bit.

> Also, what do you mean by "we have just one solution file"?

CodeCheck.ps1 previously checked for solution files throughout the repo, wasting time and complicating the PowerShell. I cleaned that up.

**Review by wtgodbe — APPROVED** [review]

**Pull request merged**
