### PR TITLE
 Add Description to ProducesResponseType (and others) for better OpenAPI document creation

### LINKED ISSUE #55656: Add Description to ProducesResponseType (and others) for better OpenAPI documents
## Background and Motivation

The purpose of this API Change is to make it easier for developers to add the `Description` properties to their OpenAPI documents using the `[ProducesResponseType], [Produces] and [ProducesDefaultResponseType]` attributes in controller actions.

Developers currently use these properties to enrich the OpenAPI document of the API. It tells the reader the possible return values from an endpoint, like a status code, response model type and content type:

<details>
<summary>See code + OpenAPI example</summary>

```csharp
[HttpGet("{id:int:min(1)}")]
[ProducesResponseType<Talk>(StatusCodes.Status200OK)]
[ProducesResponseType(StatusCodes.Status404NotFound)]
public ActionResult<Talk> GetTalk(int id)
{
    var talk = _talks.FirstOrDefault(x => x.Id == id);
    if (talk == null)
    {
        return NotFound();
    }

    return Ok(talk);
}
```

OpenAPI document is generated using NSwag (I used a JSON to YAML converter)
```yaml
paths:
  "/api/talks/{id}":
    get:
      tags:
      - Talks
      operationId: Talks_GetTalk
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
        x-position: 1
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Talk"
        '404':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ProblemDetails"
```
</details>

However, there is currently no way to map [OpenAPIs `description`](https://swagger.io/docs/specification/describing-responses) using attributes, which is the easiest way to enrich your methods with OpenAPI information which also works well with the [OpenAPI analyzers](https://learn.microsoft.com/en-us/aspnet/core/web-api/advanced/analyzers?view=aspnetcore-8.0).

It's important to make it easy for developers to set up the `Description` property because this adds a lot of important information to a specific response. For example, if an API returns `HTTP 422`, it would be useful to add a description explaining why/when this error is returned. Without this, handling this error in the client becomes more difficult because the meaning is lost.

There are other ways to set the `Description` right now, but I'm not a big fan of them. I explain why in _Alternative designs_ below.

I've wanted this feature in ASP.NET Core for a while. I've created this API proposal after talking to @captainsafia about this at the MVP Summit 2024, and she agreed that this would be a worthy addition. I had already created #54064 for this at some point. I hope the rest of the team/community agrees!

## Proposed API

```diff
// Assembly: Microsoft.AspNetCore.Mvc.Core

namespace Microsoft.AspNetCore.Mvc.ApiExplorer;

public interface IApiResponseMetadataProvider : IFilterMetadata
{
+	string? Description { get; }
}
```

```diff
// Assembly: Microsoft.AspNetCore.Mvc.Core

namespace Microsoft.AspNetCore.Mvc;

public class ProducesAttribute : Attribute, IResultFilter, IOrderedFilter, IApiResponseMetadataProvider
{
+	public string? Description { get; set; }
}
```

```diff
// Assembly: Microsoft.AspNetCore.Mvc.Core

namespace Microsoft.AspNetCore.Mvc;

public class ProducesResponseTypeAttribute : Attribute, IResultFilter, IOrderedFilter, IApiResponseMetadataProvider
{
+	public string? Description { get; set; }
}
```

```diff
// Assembly: Microsoft.AspNetCore.Mvc.Abstractions

namespace Microsoft.AspNetCore.Mvc.ApiExplorer;

public class ApiResponseType
{
+   public string? Description { get; set; }

     // Existing code here
}
```

```diff
// Assembly:  Microsoft.AspNetCore.Http.Abstractions;

namespace Microsoft.AspNetCore.Http.Metadata;

public interface IProducesResponseTypeMetadata
{
+	string? Description { get; }
}
```

```diff
// Assembly:  Microsoft.AspNetCore.Http.Abstractions;

namespace Microsoft.AspNetCore.Http;

public sealed class ProducesResponseTypeMetadata : IProducesResponseTypeMetadata
{
+	string? Description { get; private set; }
}
```

```diff
// Assembly: Microsoft.AspNetCore.Routing

namespace Microsoft.AspNetCore.Http;

public static class OpenApiRouteHandlerBuilderExtensions
{
+   public static RouteHandlerBuilder Produces(
+       this RouteHandlerBuilder builder,
+       int statusCode,
+       Type? responseType = null,
+		 string? description = null,
+       string? contentType = null,
+        params string[] additionalContentTypes)

+   public static RouteHandlerBuilder Produces<T>(
+       this RouteHandlerBuilder builder,
+       int statusCode,
+		 string? description = null,
+       string? contentType = null,
+        params string[] additionalContentTypes)

+ public static RouteHandlerBuilder ProducesProblem(
+		this RouteHandlerBuilder builder,
+		int statusCode,
+		string? description = null,
+		string? contentType = null)

+ public static TBuilder ProducesProblem<TBuilder>(
+		this TBuilder builder,
+		int statusCode,
+		string? description = null,
+		string? contentType = null)

+    public static RouteHandlerBuilder ProducesValidationProblem(
+        this RouteHandlerBuilder builder,
+        int statusCode = StatusCodes.Status400BadRequest,
+		  string? description = null,
+        string? contentType = null)

+    public static TBuilder ProducesValidationProblem(
+        this TBuilder builder,
+        int statusCode = StatusCodes.Status400BadRequest,
+		  string? description = null,
+        string? contentType = null)
}
```

## Usage Examples

```diff
-/// <response code="200">A talk entity when the request is succesful</response>
-/// <response code="422">The entity is unprocessable because SOME_REASON_HERE</response>
[HttpGet("{id:int:min(1)}")]
-[Produces<Talk>]
+[Produces<Talk>(Description = "A talk entity when the request is succesful")]
-[ProducesResponseType<Talk>(StatusCodes.Status200OK)]
+[ProducesResponseType<Talk>(StatusCodes.Status200OK, Description = "A talk entity when the request is succesful")]
-[ProducesResponseType(StatusCodes.Status422UnprocessableEntity)]
+[ProducesResponseType(StatusCodes.Status422UnprocessableEntity, Description = "The entity is unprocessable SOME_REASON_HERE")]
// I do not think there is currently a way to specify a description for the default error response type, so this is a nice bonus!
-[ProducesDefaultResponseType]
+[ProducesDefaultResponseType(Description = "The response for all other errors that might be thrown")]
public ActionResult<Talk> GetTalk(int id)
{
    var talk = _talks.FirstOrDefault(x => x.Id == id);
    if (talk == null)
    {
        return NotFound();
    }

    if (someCondition)
    {
        return UnprocessableEntity();
    }

    return Ok(talk);
}

```

### XML comments
An alternative design is to do nothing and use the built-in solution, which are [XML comments](https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-8.0&tabs=visual-studio#describe-response-types):

```csharp
/// <response code="201">Returns the newly created item</response>
/// <response code="400">If the item is null</response>
[HttpPost]
[ProducesResponseType(StatusCodes.Status201Created)]
[ProducesResponseType(StatusCodes.Status400BadRequest)]
public async Task<IActionResult> Create(TodoItem item)
{
    _context.TodoItems.Add(item);
    await _context.SaveChangesAsync();

    return CreatedAtAction(nameof(Get), new { id = item.Id }, item);
}
```

This will fill the `description` properties with the values from the `<response>` tags.

However:

- This becomes quite verbose when you're combining `[ProducesResponseType]` (and the other ones mentioned above) and XML comments.
-  We're duplicating XML comments and produces response type attributes, which isn't ideal because now we need to manage the same code twice, which will get out of sync over time.
- I do not believe that the `<response>` can set a description for `[ProducesDefaultResponseType]`

To summarize: I do not think that XML comments is the correct one.

### Library specific attributes
Both [Swashbuckle.AspNetCore](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.Annotations/SwaggerResponseAttribute.cs) and [NSwag](https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Annotations/SwaggerResponseAttribute.cs) have their own versions of `[ProducesResponseType]` called `[SwaggerResponse]` that do support the OpenAPI `Description` property.

However, there are several downsides to this:

- They are library specific, wheras `[ProducesResponseType]` is library agnostic. By using `[ProducesResponseType]` I could switch from Swashbuckle to NSwag and the OpenAPI document generation should keep working, which isn't guaranteed if I used a library specific attribute.
- Trying to combine NSwag's `[SwaggerResponse]` with `[ProducesResponseType]` to set up response descriptions doesn't work. When `[SwaggerResponse]` is used, all instances of `[ProducesResponseType]` are ignored for that method.
  - This means that some methods need to use `[SwaggerResponse]` for description support and others can still use `[ProducesResponseType]`, which makes things more difficult to read because their method signature is different.
- The OpenAPI analyzer doesn't work with library-specific attributes like `[SwaggerResponse]`, which means I need to disable those warnings for specific methods, which is annoying and makes code more difficult to read.

If ASP.NET Core's `[ProducesResponseType]` would support things like Description, the library-specific versions attributes might not be needed anymore, which makes it even easier to switch libraries in the future.

## Risks

[Swashbuckle.AspNetCore's SwaggerResponse](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.Annotations/SwaggerResponseAttribute.cs) `[ProducesResponseType]` and already has its own Description property, which means that this change might cause some issues for them. However, .NET 9 won't ship Swashbuckle anymore by default, reducing the impact this has. Regardless, Swashbuckle's authors should be informed of this change.

### PR DESCRIPTION
**Pull request by sander1095**
#  Add Description to ProducesResponseType (and other types) for better OpenAPI documents in Controllers

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Description

This pull request introduces the concept of adding OpenAPI's description to responses returned by ASP.NET Core. The changes include adding a `Description` property to response metadata interfaces, classes, and attributes, as well as updating related tests.

As discussed in #55656 , Minimal API's are not (or minimally) addressed in this PR. This should instead be built in #57963 (which I would love to work on in the future!)

Fixes #55656

### CODE REVIEW

**Comment by sander1095** [comment]
Hey @captainsafia, ASP.NET Core team and community!

I'm extremely excited to be able to create this PR! I'm dedicating this to the .NET and OpenAPI community, and I shouldn't forget to mention **hacktoberfest** as well! I'd love to get this merged or marked as accepted in the month of October, so keep the PR feedback coming!

I've been working on this for a while since talking to Safia about it at the MVP Summit 2024, and I'm very grateful for the opportunity.

Now, let's talk about some details 😁.

## The state of the PR
I believe the PR is coming along nicely, but I find it difficult to say if it is **done**. I would need help from the ASP.NET Core team or community to get the following answered:

- How can I test these changes? I have added unit tests, but because I do not know how I can test this functionally in an ASP.NET Core project, I do not know what I still might need to do.
  - I couldn't find any docs about this, so perhaps it'd be useful to add some documentation about this in the future?
- How can `Swashbuckle.AspNetCore`, `NSwag` and `Microsoft.AspNetCore.OpenAPI` benefit from this change? Are there code changes needed on their side, if so, how do we coordinate this? Library authors, let me know if I can help!
- I've already mentioned this in the PR description, but I believe we also need to get feature parity on the Minimal API side (#57963). However, this still needs some discussion as implementing it could apparently lead to source incompatibility issues. I'd love assistance with this.

And **finally**:

Please let me know what other changes need to be made to make this work functionally! Again, my goal is to get this to an accepted (or even merged!) state in october, if possible!

**Comment by sander1095** [comment]
@dotnet-policy-service agree

**Comment by sander1095** [comment]
Hi @mkArtakMSFT and @adityamandaleeka ! When can I expect a review and response to my comment with questions? I am very excited to get started :)

**Review by captainsafia — COMMENTED** [review]
Great start! We'll also want to update the OpenAPI implementation to respect this new property. The code for constructing OpenAPI responses is located [here](https://github.com/dotnet/aspnetcore/blob/6a40a23cd9242fc7ea01a9ae4f58886068f7257c/src/OpenApi/src/Services/OpenApiDocumentService.cs#L319). Tests for this area are [here]( https://github.com/dotnet/aspnetcore/blob/6a40a23cd9242fc7ea01a9ae4f58886068f7257c/src/OpenApi/test/Microsoft.AspNetCore.OpenApi.Tests/Services/OpenApiDocumentService/OpenApiDocumentServiceTests.Responses.cs).

**Comment by sander1095** [comment]
Hey @captainsafia! Thanks so much! I will look into this as soon as possible.

**Comment by sander1095** [comment]
Hi @captainsafia ! I've implemented your suggestions, please see the new commit and let me know what else I still need to do.

**Review by captainsafia — APPROVED** [review]
LGTM! Thanks for adding tests and the M.A.OpenApi changes.

**Pull request merged**
