### PR TITLE
Turn on new confirmation flow in templates

### PR DESCRIPTION
**Pull request by HaoK**
Depends on https://github.com/aspnet/AspNetCore/pull/8577

### CODE REVIEW

**Review by ryanbrandenburg — COMMENTED** [review]
The code looks fine but are we sure this is a scenario we want as a default experience for the templates?

**Comment by HaoK** [comment]
@blowdart ?

**Comment by blowdart** [comment]
As discussed, after branching happens.

**Comment by HaoK** [comment]
@blowdart still good to merge and turn this on for preview 7?

**Comment by blowdart** [comment]
Yes, we want the feedback.

**Review by blowdart — APPROVED** [review]
Do it, let's get the feedback

**Pull request merged**
