### PR TITLE
Fix “must comprised of”

### PR DESCRIPTION
**Pull request by jnm2**
The first commit fixes a grammatical error.
The second commit avoids the newer sense of the word ‘comprise’:

> Although it has been in use since the late 18th century, sense 2 is still attacked as wrong. Why it has been singled out is not clear, but until comparatively recent times it was found chiefly in scientific or technical writing rather than belles lettres. Our current evidence shows a slight shift in usage: sense 2 is somewhat more frequent in recent literary use than the earlier senses. You should be aware, however, that if you use sense 2 you may be subject to criticism for doing so, and you may want to choose a safer synonym such as _compose_ or _make up_.

https://www.merriam-webster.com/dictionary/comprise#usage-1-anchor

### CODE REVIEW

**Comment by jnm2** [comment]
Oops, deleted the wrong branch in my fork. Sorry!

**Comment by Eilon** [comment]
Hmm, does this change improve readability in a substantial way? Grammar/usage "rules" are typically descriptive, not prescriptive, so the question is: what wording would most people be able to mostly understand, as opposed to "does a rule exist somewhere that says this is right/wrong." I don't know the answer to that, though.

**Comment by jnm2** [comment]
Yes, great point! Descriptivism is the only realistic or useful philosophy in my opinion. I'm in favor of whatever is the most readable or professional from your point of view. 

Would you prefer I leave the 'is comprised of' or find another wording, such as 'A combination of in the case of the enum flags?

**Comment by Eilon** [comment]
#grammarnerds

I think the one that sounds most off to me is https://github.com/aspnet/AspNetCore/pull/7519/files#diff-bf4ec3339b253002eb8be7272b5eaea7 .

**Comment by jnm2** [comment]
How about, "Gets or sets the minimum number of unique characters which a password must contain"?

**Comment by Eilon** [comment]
Yeah that sounds great. Simpler English is good!

**Comment by jnm2** [comment]
Okay, what do you think of the new changes?

**Review by Eilon — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
