### PR TITLE
[release/3.0] Rebrand aspnetcore to rc1

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@Pilchie This action appears to have been missed after tactics Tuesday.

**Comment by mmitche** [comment]
Merging to unblock core-sdk build

**Comment by dougbu** [comment]
@mmitche I believe we should do the same in all ASP.NET Core repos. Am I correct on the following status:
- [x] aspnet/AspNetCore (#13341 i.e. this PR)
- [x] aspnet/AspNetCore-Tooling (aspnet/AspNetCore-Tooling#1006)
- [ ] aspnet/Blazor
- [ ] aspnet/EntityFramework6
- [x] aspnet/EntityFrameworkCore (aspnet/EntityFrameworkCore#17381)
- [x] aspnet/Extensions (aspnet/Extensions#2218)

**Comment by mmitche** [comment]
i missed blazor and Ef6...can you take care of those for me?

**Comment by dougbu** [comment]
:ok:

**Pull request merged**
