### PR TITLE
Remove myself from CODEOWNERS for SignalR

### PR DESCRIPTION
**Pull request by analogrelay**
I love me some SignalR but with BRT and such I need to focus my notifications :'(

### CODE REVIEW

**Comment by anurse** [comment]
Feel free to continue tagging me directly in PRs that you think are interesting though :)

**Review by BrennanConroy — APPROVED** [review]
I guess
:/

**Review by mikaelm12 — APPROVED** [review]
😢

**Comment by anurse** [comment]
license/cla check is still pending? I mean, I'm pretty sure I'm still current on all that :). Any way to re-run it? Shall I merge without it? @Eilon

**Comment by Eilon** [comment]
Hmm I've never seen it take that long... yeah just force for now.

**Pull request merged**
