### PR TITLE
Put IISExpress tests into a separate test group

### PR DESCRIPTION
**Pull request by jkotalik**
Latest test run on CI hit an execution timeout, my gut says it has something to do with the ServerTests conflicting with IIS tests.

### CODE REVIEW

**Comment by pakrym** [comment]
Do we have test groups for other functional test projects that use IIS?

**Comment by jkotalik** [comment]
The only one that isn't right now is ServerTests, which has a mix of IIS and non IIS tests.

**Comment by pakrym** [comment]
Do we still need this ?

**Comment by jkotalik** [comment]
Nope.

**Pull request closed without merging**
