### PR TITLE
Re-enable FlushPointTest

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes https://github.com/aspnet/AspNetCore-Internal/issues/2300

### CODE REVIEW

**Review by mkArtakMSFT — APPROVED** [review]

**Comment by pranavkm** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=191407&view=logs&jobId=a89a2a8c-213d-51e6-fe71-933481fa439c

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2408
https://github.com/aspnet/AspNetCore-Internal/issues/2348

**Comment by pranavkm** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=192055&view=logs

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2489
https://github.com/aspnet/AspNetCore-Internal/issues/2408

**Pull request merged**
