### PR TITLE
#42806 removing +1 from previous reconnection attempts

### PR DESCRIPTION
**Pull request by ghost**
#42806 removing +1 from previous reconnection attempts

I have removed the + in front of the previousReconnectAttempts variables variable when logging retry. 

#42806

### CODE REVIEW

**Comment by BrennanConroy** [comment]
I don't think we want a log saying "Reconnect attempt number 0 will start in ..."

Take a look at what we did for the javascript client: https://github.com/dotnet/aspnetcore/pull/34773/files

**Comment by WingZer0123** [comment]
Misread the file name has the logic was quite similar. Closing.

**Comment by WingZer0123** [comment]
Since this was related to a connection from a TypeScript file I have the client test application as opposed to connecting from a strict C# client at SignalR.Client.FunctionalTestApp and begun looking into the errors that are associated with loading that project.

These can be good additions to the pull request.

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=44611) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=44611) before we can accept your contribution.<br/><br/>:x: WingZer0123 [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=44611)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=44611) it.</sub>

**Comment by WingZer0123** [comment]
@BrennanConroy Strange that change is not showing up on my local repository related to this branch, I will try to roll that back. I have however located the  SignalR.Client.FunctionalTestApp project to perform some testing since the problem has arisen from a JavaScript client instead of a C# client. However, it contains quite a few linting errors that may be worth fixing for the future. Do not see a tslint or been around here long to know what we would use for TypeScript linting standards.

**Comment by BrennanConroy** [comment]
@WingZer0123  What is going on with this PR?

**Comment by WingZer0123** [comment]
@BrennanConroy I accidently clicked Close a few times that was my mistake. I got nervous, I usually don't contribute to such popular repos.

**Comment by BrennanConroy** [comment]
> I accidently clicked Close a few times that was my mistake.

No worries, happens to all of us. If you're still working that's fine, feel free to keep the PR open, maybe mark as draft? Or close until you're ready.

**Pull request closed without merging**
