### PR TITLE
CopyCabs

### PR DESCRIPTION
**Pull request by joeloff**
Copy CAB files to artifacts

### CODE REVIEW

**Comment by joeloff** [comment]
This should copy CAB files if there are any

@natemcmaster, I'm assuming that signing is done by the time we hit this target.

**Review by dougbu — APPROVED** [review]
Straightforward 😺

**Comment by dougbu** [comment]
@JunTaoLuo and @natemcmaster I believe this is just FYI for you two.

@joeloff, yes, the cabs are signed before the copy you're changing.

**Review by JunTaoLuo — APPROVED** [review]

**Comment by dougbu** [comment]
@joeloff the required checks are done. Let's get this. Unless, that is, you're waiting for something specific in the Helix tests?

**Pull request merged**
