### PR TITLE
Updated issue template

### PR DESCRIPTION
**Pull request by kichalla**

### CODE REVIEW

**Review by muratg — COMMENTED** [review]
I'd like @Eilon to decide what do to with the Home repo issue template.

**Comment by natemcmaster** [comment]
IMO we should consider github's new multi-template feature. We could have separate templates for feature requests, bug reports, and questions about how to use the product.

image

**Comment by kichalla** [comment]
👍 seems like a better way to do it. @Eilon / @muratg / @mkArtakMSFT probably have permissions to enable it.

**Comment by natemcmaster** [comment]
As long as we have agreement on what to do from @Eilon , we don't need special GitHub permissions to add these. The templates are stored as files in the repo. Example: https://github.com/natemcmaster/CommandLineUtils/tree/master/.github/ISSUE_TEMPLATE

**Comment by kichalla** [comment]
Great!

**Comment by zoidhddhdd** [comment]
Cool

**Comment by Eilon** [comment]
I updated our regular issue template, as seen here: https://github.com/aspnet/Home/blob/master/.github/ISSUE_TEMPLATE.md

The multi-issue-template thing is certainly cool, and something to consider in the future.

**Pull request closed without merging**
