### PR TITLE
Add `CreateHandler` method that allows additonal configuration

### LINKED ISSUE #42567: Additional Extensibility of `CreateHandler()` on `TestServer`
## Background and Motivation
When trying to make integration tests for a multi project application I sometimes have to have the projects talk to each other through [`HttpClient`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs). The existing [`WebApplicationFactory<TEntryPoint>`](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs) has a helpful method [`CreateDefaultClient()`](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs#L473-L500) among others for giving you an `HttpClient` that mocks the behavior of your request and sends it through your application as an [`HttpContext`](https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http.Abstractions/src/HttpContext.cs). This makes it so that a user can create the client use it as a mock response to [`IHttpClientFactory.CreateClient()`](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Http/src/IHttpClientFactory.cs#L36). Then your application is able to communicate with another instance of [`TestServer`](https://github.com/dotnet/aspnetcore/blob/main/src/Hosting/TestHost/src/TestServer.cs) so long as all communication is done through [`IHttpClientFactory`](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Http/src/IHttpClientFactory.cs). 

The problem: The `HttpClient` created by `TestServer` lacks some extensibility points that make it unusable in it's current form for my usage. I need to be able to set the [`HttpContext.Connection.RemoteIpAddress`](https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http/src/Features/HttpConnectionFeature.cs#L23). While it is great that there is a [`TestServer.SendAsync(Action<HttpContext>)`](https://github.com/dotnet/aspnetcore/blob/main/src/Hosting/TestHost/src/TestServer.cs#L193-L220) method given so that you are able to set more of these underlying features it means I can't use `WebApplicationFactory<TEntryPoint>.CreateDefaultClient()` and its underlying handler [`ClientHandler`](https://github.com/dotnet/aspnetcore/blob/main/src/Hosting/TestHost/src/ClientHandler.cs) and would have to create my own implementations much like the ones you have with only minor changes so I can use it to mock returns from `IHttpClientFactory.CreateClient()`.

## Proposed API

```diff
namespace Microsoft.AspNetCore.TestHost;

public class TestServer : IServer
{
+   public HttpMessageHandler CreateHandler(Action<HttpContext> configureContext);
}

public class ClientHandler : HttpMessageHandler
{
+   private readonly Action<HttpContext> _additionalContextConfiguration;

+   internal ClientHandler(PathString pathPase, ApplicationWrapper application, Action<HttpContext> additionalContextConfiguration);

    public override async Task<HttpResponseMessage> SendAsync(
        HttpRequestMessage request,
        CancellationToken cancellationToken)
    {
        ...
        contextBuilder.Configure((context, reader) =>
        {
            ...
        }

        // Much like: https://github.com/dotnet/aspnetcore/blob/main/src/Hosting/TestHost/src/TestServer.cs#L217
+       contextBuilder.Configure((context, reader) => _additionalContextConfiguration(context));

        var response = new HttpResponseMessage();
        ...
    }
}
```

## Usage Examples

```csharp
var handler = testServer.CreateHandler(context =>
{
    context.Connection.RemoteIpAddress = IPAddress.Parse("1.1.1.1");
});
var httpClient = new HttpClient(handler);
```
## Alternative Designs

I had also thought about an option to help set the initial feature collection of `DefaultHttpContext` but wasn't as big of a fan since the builder would then override some of those features and the user could find that quite annoying. 

```diff
namespace Microsoft.AspNetCore.TestHost;

public class TestServer : IServer
{
+   public HttpMessageHandler CreateHandler(IFeatureCollection initialHttpContextFeatures);
}

public class ClientHandler : HttpMessageHandler
{
+   private readonly IFeatureCollection _initialHttpContextFeatures;

+   internal ClientHandler(PathString pathPase, ApplicationWrapper application, IFeatureCollection initialHttpContextFeatures);
}

internal sealed class HttpContextBuilder : IHttpBodyControlFeature, IHttpResetFeature
{
+   internal HttpContextBuilder(ApplicationWrapper application, bool allowSynchronousIO, bool preserveExecutionContext, IFeatureCollection initialHttpContextFeatures)
    {
        ...
-       _httpContext = new DefaultHttpContext();
+       _httpContext = new DefaultHttpContext(initialHttpContextFeatures)
        ...
    }
}
```

## Risks

The main issue I see is that users could use it to set and remove things that are already set by the default behavior and this could mean that it would then fail to return a good response. But that is already the case of `TestServer.SendAsync(Action<HttpContext>)`. A user could mess it up so that the Content they supplied to the `HttpRequestMessage` is no longer used and the call doesn't have a body anymore but they would have done that to themselves. And this is why I propose only putting this extensibility point on the `CreateHandler` method. Anyone looking to create the handler themselves is probably looking to do something a little fancier than just `CreateClient()` and they may be less likely to trip over themselves. 

I don't believe there would have to be any breaking changes, the change to the constructor is done on an internal constructor so no one should be consuming it anyways. But also we could just add another construct that defaults the `additionalContextConfiguration` to a no op `_ => { }`. The other possibility is that someone already has an extension method like this but I could not find any with the same signature on grep.app. 

I also don't believe that there would be any noticeable performance regression. If people do not use the extra configuration the code would execute a method that does nothing and has no closures but if you utilize it then the performance regression would come only from the user.

### PR DESCRIPTION
**Pull request by justindbaur**
# Add `CreateHandler` method that allows additonal configuration

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Adds an additional `CreateHandler` method for configuring the `HttpContext` before the request is sent through the application pipeline.

## Description

As mentioned in the linked issue, the current experiencing of being able to use an `HttpClient` to make fake requests against a `TestServer` is really great and even required if you want to use that `HttpClient` to mock a real world connection amongst multiple applications. But it doesn't quite have all the customization as you might need to configure the `HttpContext` before it gets sent through your application. This change makes it so that a developer can create a handler that allows you one last chance to customize a call to your application so for example you can set `Connection` information. 

Fixes #42567

## Implementation Notes
I made the additional argument to the `ClientHandler` constructor an optional one that will connect to a method that does nothing if it isn't provided. This is a bit different from the api I proposed in the linked issue but it made for fewer changes in the tests. I could also just have it be supplied through a property. I am more than willing to change it to however others prefer.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=42677) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=42677) before we can accept your contribution.<br/><br/>:x: justindbaur [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=42677)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=42677) it.</sub>

**Review by halter73 — APPROVED** [review]
Looks great!

**Comment by Tratcher** [comment]
There are a few places we haven't been able to use the HttpClient TestServer APIs like:
https://github.com/dotnet/aspnetcore/blob/048a3fb79c4e53746ddc65da3e0d7b182c0635e5/src/Middleware/HostFiltering/test/HostFilteringMiddlewareTests.cs#L207-L209

Want to try refactoring a few of those to see how well this new API works?

**Comment by halter73** [comment]
Thanks again @justindbaur!

I'm going to merge this to make sure it gets into preview7 without needing to go through our ask mode process. I think I have 12 minutes until the bar raises. If you want to make the changes @Tratcher suggests in https://github.com/dotnet/aspnetcore/pull/42677#issuecomment-1182529274, we'd happily take it as a follow up PR.

**Pull request merged**
