### PR TITLE
Add readme for package Microsoft.AspNetCore.Authentication.JwtBearer

### PR DESCRIPTION
**Pull request by lyndaidaii**
# {PR title}

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

Include readme for NuGet package: Microsoft.AspNetCore.Authentication.JwtBearer

Fixes #{bug number} (in this specific format)

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
Thank you, @lyndaidaii.
@halter73 can you please review the text for the package? Thanks!

**Comment by lyndaidaii** [comment]
I only add readme context, it needs include it when build a package. Not sure about how AspnetCore packages build process possible MSbuild. Please help include it when build a package, thanks.

**Comment by halter73** [comment]
We don't have any `PACKAGE.md` files in this repo. The NuGet package metadata comes from the [cproj's "Description" property](https://github.com/dotnet/aspnetcore/blob/e888ea8ce36902090c57b0cc924bfda7b07e64e6/src/Security/Authentication/JwtBearer/src/Microsoft.AspNetCore.Authentication.JwtBearer.csproj#L4) and then augmented with a link to the commit that produced it [here](https://github.com/dotnet/aspnetcore/blob/e888ea8ce36902090c57b0cc924bfda7b07e64e6/eng/targets/Packaging.targets#L36).

I'm not sure how difficult it would be to source the package description from `PACKAGE.md`. It seems like it wouldn't be too difficult using the `ReadLinesFromFile` MSBuild Task, but I don't think it's something we have the time to do ourselves right now. And if we're going to start with more involved NuGet package descriptions, it's not clear we'd start with Microsoft.AspNetCore.Authentication.JwtBearer.

Thank you for your contribution, but I think we should probably close this. @wtgodbe What do you think?

**Comment by lyndaidaii** [comment]
I am from NuGet team, we are adding readme for top installed aspnetcore packages on NuGet.org.

**Comment by wtgodbe** [comment]
@lyndaidaii can you provide more info on the difference between the package description in the .csproj, and this readme file? Do either show up on nuget.org?

If Nuget has a goal to get READMEs into the top 5 packages from each repo, it should be pretty easy to get this included in the package - we can probably do it w/ msbuild in the same way dotnet/runtime does.

**Comment by lyndaidaii** [comment]
> @lyndaidaii can you provide more info on the difference between the package description in the .csproj, and this readme file? Do either show up on nuget.org?

A package without readme, it will show package description as default on readme tab on NuGet.org.  
For example, the JwtBearer doesn't have a readme instead it shows package description. 
image

A package with readme, it will show readme on NuGet.org. [An example for .NET package](https://www.nuget.org/packages/Microsoft.Extensions.Primitives/8.0.0): 
image

Difference between package description vs readme: 

1. README on NuGet.org support most GitHub flavor markdown, package description only support text render.
2. README provides important information to users and helps them understand what the package is and what it does quickly, package description is summary of packages, not useful to help users to get started with packages
3. We are working on rendering readme on PMUI in Visual Studio
4. README is metadata of packages, similar to package description, you could reference a README in your .csproj, here is more details: https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#packagereadmefile


> 
> If Nuget has a goal to get READMEs into the top 5 packages from each repo, it should be pretty easy to get this included in the package - we can probably do it w/ msbuild in the same way dotnet/runtime does.

@ViktorHofer is driving README work for dotnet runtime team. here is issue: https://github.com/dotnet/runtime/pull/91210/files
Free feel to reach out to Viktor about how they build readme file with package using MSbuild. 

Please let me know if you have any other question. I will create an issue on this repo that track the packages to include the readme.  Thanks.

**Review by halter73 — APPROVED** [review]
> If Nuget has a goal to get READMEs into the top 5 packages from each repo, it should be pretty easy to get this included in the package - we can probably do it w/ msbuild in the same way dotnet/runtime does.

@wtgodbe I'm not sure if there's anything more to do or if arcade will pick it up automatically. I guess we can keep an eye on nuget.org.

I see no reason to hold off merging this considering we've already merged #54504 which adds another PACKAGE.md file.

**Comment by halter73** [comment]
Thanks @lyndaidaii!

**Pull request merged**
