### PR TITLE
Use ArgumentException.ThrowIfNullOrEmpty

### LINKED ISSUE #50665: Use ArgumentException.ThrowIfNullOrEmpty
## Background and Motivation

Creating this new issue for changes related to ArgumentException.ThrowIfNullOrEmpty helper specifically, in order to keep it separate from #48185 and make the changes more easily reviewable

Similar to https://github.com/dotnet/runtime/pull/64357.

### PR DESCRIPTION
**Pull request by divyeshio**
# Use `ArgumentException.ThrowIfNullOrEmpty` where applicable

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Description

As suggested here https://github.com/dotnet/aspnetcore/pull/48414#issuecomment-1615204944 , I have splitted up the changes specific to ArgumentException.ThrowIfNullOrEmpty and have already addressed the feedback in this PR. 

Also, I have made changes to `Resources.ArgumentCannotBeNullOrEmpty` in the separate commit (just easier to filter on commit and review)

Fixes #50665

### CODE REVIEW

**Comment by captainsafia** [comment]
@divyeshio Thanks! It looks like you might've inadvertently re-introduced changes to the spa-templates submodule that are causing the build break. Removing these changes from the commit should do the trick. Let me know if you need help with this!

**Comment by danmoseley** [comment]
thanks for the PR @divyeshio . Looks like there's a build error -- typo. Could you please build locally before pushing changes? That will save unnecessary runs of our (considerable) validation matrix..

**Comment by divyeshio** [comment]
While restoring, I'm getting following error. I have tried deleting artifacts folder, cleared everything in nuget cache but still failing, all while being on main branch. Can you help me with this?

image

**Comment by wtgodbe** [comment]
That's weird - that wildcard expression should be picking up our native projects. It's from https://github.com/dotnet/aspnetcore/blob/36d30fdca5535180370fdf95db7af56853e4337b/eng/Build.props#L117-L121. It must be something in your local setup - have you deleted any files? What command-line shell are you using? Worst case scenario, you could work around it by deleting the block I linked (but don't include that change in your PR)

**Comment by divyeshio** [comment]
@wtgodbe It's resolved now, I had to update vs workload, delete the repo, start over again and then it worked. Btw, I'm using powershell.

A question, as these changes are spread across several projects, how do I verify my changes? Do I need to build and test whole repo? I tried `-projects` parameter in eng/build script, build fails when I use that vs when I build the individual project by navigating to the folder, it builds fine.

image

image

**Comment by wtgodbe** [comment]
Building the whole repo with `eng/build.cmd -test` will verify that everything is working. You can also run tests for the changed projects with `dotnet test` in the project directory

**Comment by divyeshio** [comment]
For following, should we change from `ArgumentException` to `ArgumentNullException` ? 

Since we are checking for null here and ArgumentNullException make more sense for it. Secondly, there is no ThrowIfNull helper for ArgumentException.
And change it to `ArgumentNullException.ThrowIfNull(tagBuilder)` 
https://github.com/dotnet/aspnetcore/blob/6e49859a0762576dcb174dd7583cde78ddf73979/src/Mvc/Mvc.ViewFeatures/src/Rendering/TagBuilder.cs#L45-L48

**Comment by danmoseley** [comment]
> For following, should we change from ArgumentException to ArgumentNullException ?

Seems reasonable, plus the current "or empty" message does not seem right.

**Comment by divyeshio** [comment]
Using `ArgumentException.ThrowIfNullOrEmpty` throws `ArgumentException` and `ArgumentNullException`.  Methods that were simply throwing ArgumentException have their Tests failing after changes, as tests were expecting ArgumentException but got ArgumentNullException instead. One such example is following:

https://github.com/dotnet/aspnetcore/blob/ee6d623741948c6ca907f60bad06736229b7d5e3/src/Middleware/Rewrite/src/ApacheModRewrite/FlagParser.cs#L57-L60  
After changes: `ArgumentException.ThrowIfNullOrEmpty(flagString);`

Failing test
https://github.com/dotnet/aspnetcore/blob/ee6d623741948c6ca907f60bad06736229b7d5e3/src/Middleware/Rewrite/test/ApacheModRewrite/FlagParserTest.cs#L61-L61

Should I update the tests or is it big enough breaking change?

**Comment by danmoseley** [comment]
I think it's fine to update tests that were expecting AE for a null parameter to now expect ANE. We've done that before.

**Comment by divyeshio** [comment]
Hi @danmoseley, I am still willing to make this contribution happen. I have few commits unpushed and last time I remember there were still few test cases failing and required changes. I was almost 80-90% there with all the changes. Now, starting again, Do I need to do something rebase or anything?

**Pull request closed without merging**
