### PR TITLE
Try out BuildProjectReferences=false in Components

### PR DESCRIPTION
**Pull request by BrennanConroy**
Same change as https://github.com/dotnet/aspnetcore/pull/34137 which was made to try and reduce build flakiness.
https://github.com/dotnet/aspnetcore-internal/issues/3915#issuecomment-928011626 for more info

### CODE REVIEW

**Comment by dougbu** [comment]
GitHub and AzDO are very confused: GitHub tried to cancel previous build for this PR but a few jobs are still running☹️ 

🤞 AzDO and GitHub eventually catch up (and that this change works 😃)

**Comment by BrennanConroy** [comment]
> GitHub and AzDO are very confused

That's what I get for doing manual builds before opening a PR :D

**Review by wtgodbe — APPROVED** [review]

**Review by dougbu — APPROVED** [review]
WFM though I'm surprised this doesn't cause new and different ordering issues e.g. Wasm.Prerendered.Server.csproj dependencies not being ready when Microsoft.AspNetCore.Components.E2ETests.csproj asks Wasm.Prerendered.Server.csproj  to build.

**Comment by dougbu** [comment]
> That's what I get for doing manual builds before opening a PR :D

Recommend draft PRs unless you need to test things w/ internal builds.

**Comment by SteveSandersonMS** [comment]
> WFM though I'm surprised this doesn't cause new and different ordering issues e.g. Wasm.Prerendered.Server.csproj dependencies not being ready when Microsoft.AspNetCore.Components.E2ETests.csproj asks Wasm.Prerendered.Server.csproj to build.

Yes, I wondered too. Does this change mean we're just hoping the build ordering/parallelism happens to work out OK, or is there anything that ensures it?

Also when building the `E2ETests` project locally, does it mean it no longer rebuilds any dependencies that have been changed? Because if so that would harm productivity for us an contributors.

**Review by pranavkm — COMMENTED** [review]
Isn't this problematic? If there's a reference that is unique to one of these projects, it'll never get built?

**Comment by dougbu** [comment]
@pranavkm that part I get 😄 The item group @BrennanConroy is changing is only used on the CI or when building the `Release` configuration. See

- https://github.com/dotnet/aspnetcore/blob/87a22b568732f03e01c4960ce63d4879b7546b1c/src/Components/test/E2ETest/Microsoft.AspNetCore.Components.E2ETests.csproj#L28-L29
- https://github.com/dotnet/aspnetcore/blob/87a22b568732f03e01c4960ce63d4879b7546b1c/src/Components/test/E2ETest/Microsoft.AspNetCore.Components.E2ETests.csproj#L58

**Comment by BrennanConroy** [comment]
Running again for sanity, planning on merging if it passes again.

**Comment by SteveSandersonMS** [comment]
> Running again for sanity, planning on merging if it passes again.

Asking again, with this change, is there anything that causes the build ordering/parallelism to be valid, or does it just happen to work by chance?

**Comment by BrennanConroy** [comment]
> is there anything that causes the build ordering/parallelism to be valid, or does it just happen to work by chance?

Components being near the end of the stack is probably why this _just_ works. I understand your ordering concerns but I'd rather try this out to see if the 'file in use' issues stop happening and revert/file an issue if we see ordering issues. Right now we have little to no information about the build problems we've been seeing and this PR will hopefully give us some info.

Plus, you already have this change for another of your project references so build ordering isn't a new problem here, it just might be more likely now.

**Comment by dougbu** [comment]
> is there anything that causes the build ordering/parallelism to be valid, or does it just happen to work by chance?

The changed project also has a _lot_ of dependencies, likely covering (almost❔) everything the few dependencies passed `$(BuildProjectReferences)` need. Those dependencies also appear at the end of the item group and will be processed last.

**Comment by SteveSandersonMS** [comment]
OK, sounds reasonable! We'll have to see how this turns out in practice.

**Pull request merged**
