### PR TITLE
Ensure InstallVisualStudio.ps1 doesn't mix RTM and preview versions if both are installed

### PR DESCRIPTION
**Pull request by natemcmaster**
Attempting to resolve https://github.com/aspnet/AspNetCore-Internal/issues/2210

### CODE REVIEW

**Review by JunTaoLuo — APPROVED** [review]

**Review by dougbu — APPROVED** [review]
Hmm, guessing the agents are being upgraded again. Once again we weren't notified.

Should we address #8941 and (hopefully) find a way to get more information into the logs about any VS installation failure at the same time?

**Comment by natemcmaster** [comment]
This issue is blocking P4 builds, so I don't want to address #8941 just yet. Seems this fix is sufficient to unblock P4 for now.

It appears the VS Build Tools preview version was actually 16 P4, not 16.1 previews. The agents must be stale.

**Comment by jkotalik** [comment]
Hey I think this is causing my build to fail: https://dev.azure.com/dnceng/public/_build/results?buildId=150728

**Comment by poke** [comment]
@jkotalik Once #9263 is merged, you should be able to rebase onto master and the builds should go through.

**Pull request merged**
