### PR TITLE
Do not assume that `this._settings.loginMode` is not `undefined`.

### LINKED ISSUE #35162: Blazor WebAssembly MSAL authentication error
### Describe the bug

I have a [Blazor WebAssembly application](https://github.com/IEvangelist/learning-blazor) that relies on:

`<PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" Version="6.0.0-preview.6.21355.2" />`

For authentication, with an AAD B2C instance. It works perfectly, when running locally. But now that the app is deployed to Azure as a static web app, I get the following error:

> "There was an error trying to log you in: 'Cannot read property 'toLowerCase' of undefined'"

The website is [deployed here](https://purple-stone-0b2589410.azurestaticapps.net).

### To Reproduce

Deploy a Blazor WebAssembly app (with PWA bits) to Azure static web apps, with AAD B2C auth. Try logging in.

### Exceptions (if any)

None

### Further technical details

Using .NET Core SDK Version: 6.0.100-preview.6.21355.2

### PR DESCRIPTION
**Pull request by IEvangelist**
**PR Title**

Do not assume that the `LoginMode` was provided, instead safely access the member with optional chaining. In the event that it's not provided, fall-through to popup instead of redirect -- which I believe is the default anyway.

Fixes #35162

### CODE REVIEW

**Review by pranavkm — APPROVED** [review]
Looks good to me. @javiercn could you take a quick look?

**Comment by SteveSandersonMS** [comment]
@IEvangelist Given you comment at https://github.com/dotnet/aspnetcore/issues/35162#issuecomment-896338506:

> I'm thinking that somehow the .ProviderOptions are not passing the .LoginMode. The correct scopes are coming through, but not the login mode.

... could you clarify why the preferred fix would be tolerating the absence of `LoginMode` rather than ensuring it's being passed? If there's a known legit reason for it not to be passed, or perhaps not defined in the first place, that would be good to know.

**Comment by IEvangelist** [comment]
> @IEvangelist Given your comment at [#35162 (comment)](https://github.com/dotnet/aspnetcore/issues/35162#issuecomment-896338506):
> 
> > I'm thinking that somehow the .ProviderOptions are not passing the .LoginMode. The correct scopes are coming through, but not the login mode.
> 
> ... could you clarify why the preferred fix would be tolerating the absence of `LoginMode` rather than ensuring it's being passed? If there's a known legit reason for it not to be passed, or perhaps not defined in the first place, that would be good to know.

It seemed to be related to the trimming of the auth package, this https://github.com/dotnet/aspnetcore/issues/35162#issuecomment-907282690 worked for me.

**Comment by pranavkm** [comment]
The WebAssembly.Auth assembly isn't currently annotated for trimming - https://github.com/dotnet/aspnetcore/issues/30751. It's likely that resolving that issue would resolve this issue. We could take this change regardless as it seems innocuous enough. Thoughts?

**Comment by SteveSandersonMS** [comment]
> We could take this change regardless as it seems innocuous enough. Thoughts?

The change given here would be good for a patch. However if we're making a fix for 7.0 it seems more worthwhile to do #30751 as it would fix a broader class of issues and not leave behind a weird special case that would confuse us in the future.

Do you think that #30751 would take more than an hour or two for one of us to address? Should we be doing that one anyway for 7.0?

**Comment by IEvangelist** [comment]
> > We could take this change regardless as it seems innocuous enough. Thoughts?
> 
> The change given here would be good for a patch. However if we're making a fix for 7.0 it seems more worthwhile to do #30751 as it would fix a broader class of issues and not leave behind a weird special case that would confuse us in the future.
> 
> Do you think that #30751 would take more than an hour or two for one of us to address? Should we be doing that one anyway for 7.0?

I'm all good on me end, and happy to close this one. My work around is fine for the time being, as I'm not sure what other issues are resulting from bits being inadvertently trimmed out. I believe that #30751 is the correct path forward and should be part of 7.0. That's my vote if I have one.

But I do agree with @pranavkm that this change is harmless and will potentially avoid an issue like this in the future. If there is no value for the `loginMode` isn't it better to have a default action that doesn't break the app entirely?

**Comment by SteveSandersonMS** [comment]
> If there is no value for the loginMode isn't it better to have a default action that doesn't break the app entirely?

If there's a legal reason for this situation to happen then yes. But if not, then no, that would be worse because then strange things are happening and nobody would get notified.

**Comment by pranavkm** [comment]
Alrightie, let's close this and figure out why trimming affects this / resolve it as part of https://github.com/dotnet/aspnetcore/issues/30751

**Pull request closed without merging**
