### PR TITLE
Docs: Fix branch link

### PR DESCRIPTION
**Pull request by staff0rd**
`dev` no longer exists.

### CODE REVIEW

**Review by analogrelay — APPROVED** [review]
Good catch!

**Review by mikaelm12 — APPROVED** [review]

**Comment by anurse** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=181220

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2481
https://github.com/aspnet/AspNetCore-Internal/issues/2423

**Review by halter73 — APPROVED** [review]

**Comment by halter73** [comment]
Thanks!

**Pull request merged**
