### PR TITLE
Add AnyHeader and AnyMethod

### LINKED ISSUE #54772: Add AnyHeader and AnyMethod to src/Middleware/CORS/src/Infrastructure/CorsConstants.cs
## Background and Motivation

According to pull request #54247, CorsConstants only contain AnyOrigin value

This is while it also needs AnyHeaders and AnyMethods because, unlike AnyOrigin, the value "*" is used directly in other places.

## Proposed API

My changes are like this:
```diff
namespace Microsoft.AspNetCore.Cors.Infrastructure;

public static class CorsConstants
{
+    public static readonly string AnyHeader = "*";
+    public static readonly string AnyMethod = "*";
}
```

## Usage Examples

```csharp
public bool AllowAnyHeader
{
    get
    {
        if (Headers == null || Headers.Count != 1 || Headers[0] != CorsConstants.AnyHeader)
        {
            return false;
        }
        return true;
    }
}
public bool AllowAnyMethod
{
    get
    {
        if (Methods == null || Methods.Count != 1 || Methods[0] != CorsConstants.AnyMethod)
        {
            return false;
        }
        return true;
    }
}
```

Instead of using this form:
```csharp
public bool AllowAnyHeader
{
    get
    {
        if (Headers == null || Headers.Count != 1 || Headers[0] != "*")
        {
            return false;
        }
        return true;
    }
}
public bool AllowAnyMethod
{
    get
    {
        if (Methods == null || Methods.Count != 1 || Methods[0] != "*")
        {
            return false;
        }
        return true;
    }
}
```

### PR DESCRIPTION
**Pull request by I-SER-I**
# Add AnyHeader and AnyMethod CorsConstants

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Description

Fixes #54772

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Thanks for the contribution, but this PR already exists: https://github.com/dotnet/aspnetcore/pull/54247

**Comment by hamidrezahy** [comment]
Hi @BrennanConroy,
my pull request [#54247](https://github.com/dotnet/aspnetcore/pull/) is still not approved, do I need to do something else?

**Comment by hamidrezahy** [comment]
Hi @BrennanConroy,
my pull request  https://github.com/dotnet/aspnetcore/pull/54247 is still not approved, do I need to do something else?

**Comment by BrennanConroy** [comment]
Closing as dupe of https://github.com/dotnet/aspnetcore/pull/54247

**Pull request closed without merging**
