### PR TITLE
[Helix] Don't fail fast on ef tool install issues (may be already installed)

### PR DESCRIPTION
**Pull request by HaoK**

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]

**Comment by HaoK** [comment]
Unrelated to this PR, so interesting @dougbu looks like the skip-ci only affects the aspnetcore-pr-validation-temp pipeline https://dev.azure.com/dnceng/public/_build?definitionId=279

**Review by JunTaoLuo — APPROVED** [review]

**Comment by Pilchie** [comment]
Do we understand if this does the right thing if the wrong version of the `ef` tool is installed?

**Comment by davidfowl** [comment]
Seem like we should install or update.

**Comment by HaoK** [comment]
So my impression is that you can install multiple versions of the tool, and the failure we were running into was that the version we were trying to install was already installed (maybe the SDK caught up to our runtime version?)

**Comment by HaoK** [comment]
`dotnet tool install dotnet-ef --global --version {Options.EfVersion}` so we are specifying the exact version we want (the AspNetRuntime version)

**Comment by Pilchie** [comment]
We should verify that installing multiple versions actually works the way we expect.  @wli3 - do you know about this?

**Comment by davidfowl** [comment]
Does it need to be installed globally? Seems like we should be installing it into a subfolder and using that instead no?

**Comment by BrennanConroy** [comment]
It should be installed in a local folder, I believe the DOTNET_CLI_HOME variable controls that. But it looks like we are no longer setting that after switching to the C# runner.

**Comment by HaoK** [comment]
Okay I can open a new PR on monday that switches to installing the tool non globally

**Comment by dougbu** [comment]
The bug here is not setting `$env:DOTNET_CLI_HOME` anymore. We should avoid global changes on the agents where possible because they are _not_ recreated from an image after each use. Put another way, we set `$env:DOTNET_CLI_HOME` for reasons.

**Comment by davidfowl** [comment]
This should be part of the helix package https://github.com/dotnet/aspnetcore/pull/20876

**Pull request merged**
