### PR TITLE
Update Microsoft.Identity.Web packages to pick up bugfixes

### PR DESCRIPTION
**Pull request by captainsafia**
#### Description

This PR updates our Microsoft.Identity.Web dependency to the latest release to bring in fixes to some user reported issues.

#### Customer Impact

This PR integrates bug fixes for user-reported issues with the initial GA version of the Microsoft.Identity.Web packages. There were no straight-forward workarounds for these user reported issues.

#### Regression?

No, because this is a new package we're consuming in .NET 5.

#### Risk

Low risk

### CODE REVIEW

**Review by jmprieur — APPROVED** [review]
LGTM.
Thanks @captainsafia

**Comment by Pilchie** [comment]
This was approved over email.

**Review by javiercn — APPROVED** [review]
Looks good to me.

@jmprieur can we confirm these have been validated E2E?

**Comment by jmprieur** [comment]
@javiercn : it has been with the Microsoft.Identity.Web templates.

**Comment by javiercn** [comment]
> @javiercn : it has been with the Microsoft.Identity.Web templates.
> Can you ping me to the artefacts generated by the AzureDevOps pipeline?

I think this is the one https://dev.azure.com/dnceng/_apis/resources/Containers/5267006/Windows_Packages?itemPath=Windows_Packages%2FRelease%2FShipping%2FMicrosoft.DotNet.Web.ProjectTemplates.5.0.5.0.0-ci.nupkg

**Comment by Pilchie** [comment]
Any updates here?  I'd like to get this merged before the bar goes up again and we lose our chance.

**Comment by jmprieur** [comment]
Where can I find the runtime @Pilchie @javiercn ?

**Comment by JunTaoLuo** [comment]
@jmprieur from the build logs I can see the following links:
SDK:  https://dotnetcli.azureedge.net/dotnet/Runtime/2.1.18/dotnet-runtime-2.1.18-win-x64.zip
Runtime: https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.0-rtm.20502.8/dotnet-runtime-5.0.0-rtm.20502.8-win-x64.zip

**Comment by jmprieur** [comment]
@JunTaoLuo : I don't understand the link to the SDK? above. this seems to be a runtime? not an SDK?

**Comment by JunTaoLuo** [comment]
Ah oops, looks like I copied the wrong link, this should be it: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-rc.1.20452.10/dotnet-sdk-5.0.100-rc.1.20452.10-win-x64.zip.

**Comment by jmprieur** [comment]
Thanks @JunTaoLuo. this is timely (was working no it)

**Comment by jmprieur** [comment]
@JunTaoLuo : this is anRC1 SDK? is it what we want to use to test RTM?

**Comment by JunTaoLuo** [comment]
The SDK we use to test shouldn't really matter actually, since a newer runtime should be used anyway. Feel free to use the RC1 SDK, I only linked what SDK our build used. Either should work.

**Comment by jmprieur** [comment]
I was able to successfully test all the templates in all configuration
I only have one issue with the blazorwasm one, but this seems to be that I don't have the right framework on my machine?

@javiercn could you please test it (for instance `dotnet new blazorwasm --auth SingleOrg`)

**Comment by Pilchie** [comment]
@javiercn have you had a chance to look at this yet?  It was approved by tactics over 7 days ago now.  Normally we want to have things merged within 24 hours of them being presented at Tactics. We need to either get better at testing before bringing to tactics, or getting things merged faster after.

**Comment by javiercn** [comment]
@Pilchie this is good to merge

**Review by JunTaoLuo — APPROVED** [review]

**Pull request merged**
