### PR TITLE
Update Channels.ps1

### PR DESCRIPTION
**Pull request by sayedihashimi**

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@sayedihashimi__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, MSOTBOT;

**Comment by DamianEdwards** [comment]
Does this change the semantics of the file? I currently just execute this file directly in my profile, then typ `Use-Dev` or `Use-Volatile` at the command line. How does the usage change?

**Comment by sayedihashimi** [comment]
@DamianEdwards I assume you're doing that by executing it with something similar to ```. .\Channels.ps1``` then the functions are available in the session. I just made some changes so that you can continue to do this.

Now you can pass a feed like ```. .\Channels.ps1 release``` or you can do the following.

```
>. .\Channels.ps1
...
> Use-Feed release
```

**Comment by Eilon** [comment]
@DamianEdwards 's original code matched the branch names, which people see more often, as opposed to the feed names, which are rather obscure...

**Pull request closed without merging**
