### PR TITLE
[ApiAuth] Switches back to use code+PKCE

### PR DESCRIPTION
**Pull request by javiercn**
* Brings back a commit that was reverted.
* Updates oidc-client.
* Includes the required template changes to use the new client APIs we needed.

### CODE REVIEW

**Comment by javiercn** [comment]
Feel free to skip the first commit

**Comment by brockallen** [comment]
I didn't see the use of the new API for `signinCallback` -- was it not useful?

**Comment by javiercn** [comment]
> I didn't see the use of the new API for `signinCallback` -- was it not useful?

It was, but it didn't pass the state back (which I need on the redirect case).

Have I missed something?

I worked around using the new apis in oidcclient directly, and doing that bit myself.

I have a bunch of notes that I've taken, I'm just trying to get this in today and we can address the cleanups later.

**Review by ryanbrandenburg — APPROVED** [review]
This looks fine. Many of the Templating tests are currently marked Flaky, meaning that they won't fail the build even if they're broken. Given that, please take the additional step of looking at the Tests tab of the AspNetCore-Ci run for this build to verify that nothing broke. Assuming everything is good on that front, :shipit:.

**Pull request merged**
