### PR TITLE
Migrate logging testing

### PR DESCRIPTION
**Pull request by JunTaoLuo**
This is part of https://github.com/dotnet/aspnetcore/issues/19254.

We want to move our LoggedTest infrastructure to aspnetcore. However, this is going to be difficult to make progress on due to namespace collisions and cyclic dependencies (AspNetCore.Testing (in aspnetcore) => Logging.Testing => AspNetCore.Testing (in extensions)). I'm looking into possible ways to solve this.

Note that we might also want to move the [CollectDump] attribute.

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
FYI this isn't going to work just yet and may need some work in dotnet/extensions and dotnet/runtime before the issues are resolved.

**Comment by JunTaoLuo** [comment]
This PR is ready for review. The changes here will require https://github.com/dotnet/extensions/pull/3040 to be merged and the new packages from extensions to be ingested here. Note that the ingestion will fail without these changes.

@anurse I think the risk here is that even though I'm able to build and test locally, it's possible that we'll encounter some difficulties on the CI. I think we can work out all the issues in about 1 day. Should I wait for a low traffic time (evening or weekend?) to make this pair of changes?

**Comment by JunTaoLuo** [comment]
FYI, the only commit that needs review is https://github.com/dotnet/aspnetcore/pull/19545/commits/c181547864a1dbf6ef7cb0917ede5d17bc17e4e6

**Comment by dougbu** [comment]
> FYI, the only commit that needs review is c181547

Why? And why are the validation builds on the floor?

**Comment by JunTaoLuo** [comment]
All other changes are merges from dotnet/extensions which we are bringing over to dotnet/aspnetcore. You can think of it as additional APIs we wanted to migrate from extensions to aspnetcore.

>The changes here will require dotnet/extensions#3040 to be merged and the new packages from extensions to be ingested here. Note that the ingestion will fail without these changes.

These changes will not pass until we ingest new extensions packages due to a cyclic dependency.

**Comment by JunTaoLuo** [comment]
@dougbu 🆙 📅

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
Hmm, I approved before I noticed this wasn't building ☹️

**Comment by JunTaoLuo** [comment]
It won't build until I merge https://github.com/dotnet/extensions/pull/3040 and get a dependency update from extensions

**Comment by JunTaoLuo** [comment]
I need to rework 3 AssemblyTestLogTests (https://github.com/dotnet/aspnetcore/issues/19683) but I'm merging this to unblock dependency updates.

**Pull request merged**
