### PR TITLE
[release/3.1] Resolve Component Governance bugs

### PR DESCRIPTION
**Pull request by wtgodbe**
Part of https://github.com/dotnet/aspnetcore/issues/37889. Resolves the remaining High/Critical 3.1 CompGov bug(s)

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
Looks fine to me but I recommend checking w/ the Blazor and SignalR teams. Also, weren't we leaving versions in our templates alone❔

**Comment by wtgodbe** [comment]
> Looks fine to me but I recommend checking w/ the Blazor and SignalR teams. Also, weren't we leaving versions in our templates alone❔

@dotnet/aspnet-blazor-eng @BrennanConroy could you take a look? And I left the templates alone, though I did update the template tests

**Review by BrennanConroy — APPROVED** [review]

**Comment by wtgodbe** [comment]
Some S.T.E.W CompGov bugs won't be fixed until we ingest https://github.com/dotnet/extensions/pull/3925

**Comment by Pilchie** [comment]
:eyes:

**Review by dougbu — APPROVED** [review]

**Pull request merged**
