### PR TITLE
Backport UseProgramMain template option

### LINKED ISSUE #40944: Backport UseProgramMain template option to SDK 6.0.300
Backport #40877 to SDK 6.0.300

### PR DESCRIPTION
**Pull request by DamianEdwards**
Backports the UseProgramMain template option to allow creation of web projects without using top-level statements.

Intended to land in SDK 6.0.300

Fixes #40944

Looks like this in Visual Studio:

image

### CODE REVIEW

**Comment by dougbu** [comment]
Is this something we also want to show up in 6.0.1xx and 6.0.2xx❔ I don't think we can make a change in this repo that affects only 6.0.3xx. Am I missing something @dsplaisted @marcpopMSFT❔

**Comment by DamianEdwards** [comment]
Yeah that's fine if it shows up in those too I think, but paging @baronfel to be sure.

**Comment by baronfel** [comment]
Yep, that sounds like what I'd expect.

**Comment by DamianEdwards** [comment]
Going to hold off on merging this (and the [related SPA templates change](dotnet/spa-templates#45)) until we square away the change flow process for the 6.0.xxx SDKs with tactics.

**Comment by DamianEdwards** [comment]
Also note this PR needs to be updated to update the spa templates submodule after [the PR for that](dotnet/spa-templates#45) is merged.

**Comment by dougbu** [comment]
@DamianEdwards please get this back-port approved (not just `servicing-approved`). Also, is the following done❔

> Also note this PR needs to be updated to update the spa templates submodule after [the PR for that](dotnet/spa-templates#45) is merged.

**Comment by DamianEdwards** [comment]
@dougbu what is "back-port" approved"

**Comment by dougbu** [comment]
> @dougbu what is "back-port" approved"

I meant even backports need a teammate to approve, not just `servicing-approved`. I don't know enough about what's changing here to do that for you but am happy to merge once someone signs off.

**Comment by DamianEdwards** [comment]
@dougbu understood. I've asked @phenning to review this change. I'll update this PR for the spa templates submodule update in the morning.

**Review by phenning — APPROVED** [review]
LGTM :shipit:

**Comment by DamianEdwards** [comment]
@dougbu spa templates submodule is updated, this PR should be ready to go assuming checks pass.

**Pull request merged**
