### PR TITLE
[DO NOT MERGE] Get non-crossgen'd builds

### PR DESCRIPTION
**Pull request by wtgodbe**
Grabbing a Debug build so we can get non-crossgen'd assets for ApiScan

### CODE REVIEW

**Comment by wtgodbe** [comment]
CC @kalaskarsanket

**Comment by dougbu** [comment]
1. This won't work because a few projects fail miserably when built for `Debug` on CI
2. _If_ we want a build like this, it unfortunately has to be done from a branch in the repo. That's annoying because our contributors should be switching to forks (hint, hint @wtgodbe)
3. Better to either
    1. Grab the shared runtime bits from a Helix correlation payload
    2. Change our YAML to add another top-level parameter then use that parameter to control `/p:CrossgenOutput=false` in  our regular Windows x64/x86 build job; only need to change one job

In general, we need something repeatable and simple. An internal manual build (the last option) with a single checkbox enabled seems pretty ideal if we're going to need this every month

**Comment by wtgodbe** [comment]
> If we want a build like this, it unfortunately has to be done from a branch in the repo. That's annoying because our contributors should be switching to forks (hint, hint @wtgodbe)

Did we decide to do that? Might have happened while I was on vacation, I don't remember seeing an email

**Review by dougbu — COMMENTED** [review]
Yeah, this should work. We still need something realz and repeatable for the future

**Comment by dougbu** [comment]
> Did we decide to do that?

We did and you probably were on vacation. But, discussion may not have gone beyond DoI and isn't absolutely required. You are encouraged to try things out w/ forks. Long conversation in DoI Teams channel that covered my process for eliminating local branch "noise" in my environment 😀 Start midway through discussions on 7 October.

**Pull request closed without merging**
