### PR TITLE
Support binding to Int16 (#15437)

### PR DESCRIPTION
**Pull request by mrpmorris**
Adds binding and formatting to `Int16` for the `InputNumber` component.

Addresses #15437

### CODE REVIEW

**Review by javiercn — COMMENTED** [review]
LGTM but I'll let @SteveSandersonMS have a say.

**Comment by SteveSandersonMS** [comment]
At the moment this PR doesn't do what I think it's trying to do.

 * It doesn't actually change how `Int16` is handled for `@bind` because it doesn't add the necessary overloads to `Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder` that provide a new code path for `Int16` values. The reason that `@bind="someInt16Value"` works is that int16 has a typeconverter and hence already worked prior to this PR.
 * It doesn't make `<InputNumber>` work with `Int16` because it doesn't change the `InputNumber` static constructor to allow `Int16`

For us to proceed with this PR, would you please be able to correct these two issues? Also it would be important to add an E2E test that covers the use of `<InputNumber>` with an `Int16` value to be sure it really works.

Thanks!

**Comment by mrpmorris** [comment]
@SteveSandersonMS Isn't this a suitable E2E test?
https://github.com/aspnet/AspNetCore/pull/16952/files#diff-0eeffe4e56168e67116e41b9a1d1ea99

**Comment by SteveSandersonMS** [comment]
No, that's not testing `<InputNumber>`

**Comment by mrpmorris** [comment]
Ah I see. I'll have a proper look when I'm no longer on my phone. Cheers :)

**Comment by mrpmorris** [comment]
Seems I've deleted the repository that had the pull request files in. I don't suppose you know how I can clone the original and grab these PR changes do you?

**Pull request closed without merging**
