### PR TITLE
Improve project reference consistency

### PR DESCRIPTION
**Pull request by dougbu**
Improve project reference consistency
- use `Private` and `SkipGetTargetFrameworkProperties` w/ `ReferenceOutputAssemblies="false"`
  - correct meaningless `$(ReferenceOutputAssemblies)` settings; no such metadata
  - `Private="false"` avoids unnecessary file copies
  - `SkipGetTargetFrameworkProperties="true"` should reduce useless TFM negotiation
    - that said, it can't be used everywhere due to multi-targeting restrictions
- do not use `PrivateAssets="All"` in `@(ProjectReference)` items or `@(Reference) items that become them
  - has no meaning in `@(ProjectReference)` items
- add warnings about mixed-up application of `%(Private)` and `%(PrivateAssets)`

Remove most `UndefineProperties` use
- should not be necessary

### CODE REVIEW

**Review by dougbu — COMMENTED** [review]
We normally use `SkipGetTargetFrameworkProperties="true"` only when referring to .npmproj from .csproj projects, to .csproj from .debproj or .rpmproj projects, or between .csproj projects with identical (and single) TFMs. Highlighting the few exceptions&hellip;

Do any of these raise red flags for you @rainersigwald❔

**Comment by dougbu** [comment]
> `UndefineProperties` is one of the metadata that is [handled natively in the `MSBuild` task][native_task]. 

Alright I'll revert some or all of my second commit. To confirm my understanding, "handled natively" also means `<MSBuild />` picks up and uses `%(UndefineProperties)` metadata from `@(ProjectReference)` items, `@(_MSBuildProjectReferenceExistent)` items, and similar❔

**Comment by dougbu** [comment]
And, sorry, @rainersigwald but I had a couple more questions for you:

1.  is `%(ProjectReference.Private)` metadata ignored when `%(ReferenceOutputAssembly)` is `false`❔
  - I'm wondering if I should _remove_ `Private="false"` everywhere we use `ReferenceOutputAssembly="false"`
  - Also curious whether `Private="true" ReferenceOutputAssembly="false"` on an item would mean "copy output assembly to my bin/ folder but don't reference it when compiling
 2. [on `SkipGetTargetFrameworkProperties="true"` exceptions from the single TFM norm] Do any of these raise red flags for you @rainersigwald❔

**Review by Pilchie — COMMENTED** [review]
Our build is complicated enough that I don't understand everything this is doing but the general idea seems sound.

However, one concern is that I thought MSBuild *didn't* block for `ProjectReference`s to build if they had `ReferenceOutputAssembly="false"`.  Since this sets that in more places, is it likely to actually introduce *more* build races?  @rainersigwald do you know about the scheduling aspect?

**Review by Pilchie — APPROVED** [review]

**Pull request merged**
