### PR TITLE
Extend timeout and report failure to WarmUp for template tests

### PR DESCRIPTION
**Pull request by ryanbrandenburg**
## Description

- Retry Click events and get a screenshot on failure.
- Extend warmup timeout and warn when it doesn't complete in time.

## Risk
Very low. The only changes are to tests and test infrastructure. The only risk is that the tests become more flaky, though they're already among the top failures, and this gives us more information when they DO fail.

## User impact
None. Changes are to tests only.

Part of https://github.com/aspnet/AspNetCore-Internal/issues/2996.

### CODE REVIEW

**Comment by ryanbrandenburg** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=412426.

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2715
https://github.com/aspnet/AspNetCore-Internal/issues/3241

**Comment by ryanbrandenburg** [comment]
Ran into a problem where the click event failed because the element was supposedly stale. Some googling suggests that this is something that "just happens" sometimes, that other people have "fixed" by retrying. I made the majority of our Click events go through "WaitAssertCore", that way it will retry, and if it does still fail we'll get a screenshot of the failure.

**Review by ajaybhargavb — APPROVED** [review]

**Comment by ryanbrandenburg** [comment]
@mkArtakMSFT it's still the case that we just have to do FYI on test only changes to 3.1 right?

**Comment by wtgodbe** [comment]
@ryanbrandenburg test-only changes are tell-mode. Do we need this for 3.1 GA, or 3.1.1? If it's for 3.1 GA I'll merge this Sunday/Monday

**Comment by ryanbrandenburg** [comment]
@wtgodbe that's a bit of a judgement call. The intent here is to improve reliability and make failures easier to investigate, so my first thought is to target 3.1 GA. On the other hand if we're cutting the GA branch over the weekend or something it might not be worth the trouble to bring in extra commits for improvements to tests that will only run like 3-5 times before 3.1.1.

So, I guess I'd tend to say we should wait for 3.1.1?

**Comment by wtgodbe** [comment]
@ryanbrandenburg sounds good, let's target 3.1.1.

**Review by mkArtakMSFT — APPROVED** [review]

**Review by javiercn — APPROVED** [review]

**Comment by wtgodbe** [comment]
Template test failures are not unique to this PR

**Pull request merged**
