### PR TITLE
Enable all Globalization analyzers

### PR DESCRIPTION
**Pull request by Youssef1313**
The three enabled rules are all Globalization rules, which shows interest in this category.

This PR enables all Globalization rules. I'm going to wait for CI to see how many violations are there, and depending on that I'll see how this can move forward.

### CODE REVIEW

**Review by pranavkm — COMMENTED** [review]
FYI @Pilchie

**Comment by Youssef1313** [comment]
There are some violations of globalization analyzers. All of them in test code, with the only exception:

https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Shared/Razor/CaseSensitiveBoundAttributeComparer.cs#L32

(it doesn't specify a StringComparison)

Do you want to fix all violations? or disable in tests and fix the one left violation?

**Comment by Pilchie** [comment]
Personally, I think fixing everywhere is the eventual end goal, but I'm definitely willing to start with product code.

**Comment by pranavkm** [comment]
The default implementation for `string.Equals` has the correct behavior in .NET Core. CA1309 is a bit iffy in .NET Core projects : https://github.com/dotnet/roslyn-analyzers/issues/2169.

**Comment by Youssef1313** [comment]
I'm going to close in favor of https://github.com/dotnet/aspnetcore/pull/30138

**Pull request closed without merging**
