### PR TITLE
Update RemoveCommand.cs

### PR DESCRIPTION
**Pull request by doggy8088**
Retarget the PR #17825  to `master` branch.

Summary of the changes (Less than 80 chars)
 - There is a tiny typo in this file. That will produce wrong English on the console.

image

### CODE REVIEW

**Review by pranavkm — APPROVED** [review]
Looks good to me. @ryanbrandenburg are you aware of any external dependencies (IDEs or SDKs) that are affected by this?

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg assigning this to you to follow up with the VS tooling team and make sure the right things will happen.

**Comment by ryanbrandenburg** [comment]
@pranavkm I'm aware of nothing that depends on this tool.

**Comment by pranavkm** [comment]
Thanks @doggy8088

**Pull request merged**
