### PR TITLE
Update branding for 5.0.11

### PR DESCRIPTION
**Pull request by vseanreesermsft**

### CODE REVIEW

**Comment by dougbu** [comment]
In addition to @BrennanConroy's `mcr` fix, something is messing up in the `nginx` installation. Assigning to @wtgodbe for fixes

**Comment by wtgodbe** [comment]
We might need https://github.com/dotnet/aspnetcore/pull/30253

**Comment by wtgodbe** [comment]
`ContinueOnError` for installing nginx looks like the way to go, tests still pass, and that leg doesn't produce anything we publish.

**Comment by wtgodbe** [comment]
Think we need to update selenium

**Comment by wtgodbe** [comment]
That's not doing it:

> https://dev.azure.com/dnceng/public/_build/results?buildId=1350161&view=results

@sebastienros @javiercn @SteveSandersonMS Components E2E tests are failing here, what did we do to fix them in main other than the Selenium update?

**Comment by sebastienros** [comment]
This PR is missing the selenium.config file change. @HaoK did you submit a backport of my PR to 5.0?

**Comment by wtgodbe** [comment]
Combining this with https://github.com/dotnet/aspnetcore/pull/36231

**Comment by sebastienros** [comment]
I see the PR is still open https://github.com/dotnet/aspnetcore/pull/36231

**Comment by sebastienros** [comment]
Thanks @wtgodbe

**Comment by wtgodbe** [comment]
Is there more we need? I don't see anything obvious in `main`:

> D:\workspace\_work\1\s\src\Shared\E2ETesting\BrowserFixture.cs(324,36): error CS0246: The type or namespace name 'RemoteLogs' could not be found (are you missing a using directive or an assembly reference?) [D:\workspace\_work\1\s\src\Components\test\E2ETest\Microsoft.AspNetCore.Components.E2ETests.csproj]

**Comment by sebastienros** [comment]
Didn't see these during my investigations

**Comment by wtgodbe** [comment]
Something from https://github.com/dotnet/aspnetcore/pull/36207/files? @SteveSandersonMS?

**Comment by wtgodbe** [comment]
Should we go back to https://github.com/dotnet/aspnetcore/pull/36236/commits/5a6101cd65ce0d3fde2d6c47198c8e0f863dcdde and just skip Components E2E for now? What's the best way to do that?

**Comment by wtgodbe** [comment]
Might need https://github.com/dotnet/aspnetcore/pull/34045/files

**Comment by dougbu** [comment]
Is this more complicated than #36235 simply because we introduced Selenium tests in release/5.0❔ Do you need any help here from anyone❔

**Comment by wtgodbe** [comment]
Yes, selenium is the blocker here. I think whatever started causing 6.0 selenium tests to fail is also happening here, and I'm trying to piece together the right fixes from what we've done in `main`. Current commit might work, but if not I'm waiting to hear from @SteveSandersonMS or @javiercn on what the right thing to do is here (disable? some other fix I'm missing?)

**Comment by SteveSandersonMS** [comment]
Looks like the current commit did work. I checked the [tests output](https://dev.azure.com/dnceng/public/_build/results?buildId=1350616&view=ms.vss-test-web.build-test-results-tab) and confirmed that the Components E2E tests did run here and they all passed. So, you might be fine as-is now!

It wouldn't be easy to backport all the changes I did for E2E test reliability to 5.0. For example, in 6.0 their CI run now happens on Linux in a separate pipeline to ensure there isn't anything else happening on the same machine at the same time. I expect making such sweeping changes to the 5.0 servicing branch would be out of scope.

**Review by wtgodbe — APPROVED** [review]

**Pull request merged**
