### PR TITLE
Ignore hash when supplying querystring parameters

### LINKED ISSUE #40806: SupplyParameterFromQuery includes anchor
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The `[SupplyParameterFromQuery]` attribute includes anchor data:

```razor
@page "/params"
<input class="input" @bind-value="Input" />
@code {
    [Parameter]
    [SupplyParameterFromQuery(Name="q")]
    public string? Input { get; set; }
}
```

Change the URL to `https://localhost:<port>/params?q=test#123`.

### Expected Behavior

The text box contains `test`.

The actual behavior is that it contains the value `test#123`.

### Steps To Reproduce

1. Create a Blazor Server app `dotnet new blazorserver -o blazor-server-anchors`
2. Add a page `params`
3. Use the code above

### .NET Version

6.0.200

### PR DESCRIPTION
**Pull request by campersau**
Fixes #40806

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
Thanks for your PR, @campersau.
@javiercn can you please review this? Thanks!

**Review by javiercn — APPROVED** [review]
Looks good to me

/cc @SteveSandersonMS

**Comment by javiercn** [comment]
Thanks for the contribution @campersau

**Comment by snerte** [comment]
Is this bug only fixed in 7 and not in 6?

Since 6 is LTS, we need to use that version for now.

**Pull request merged**
