### PR TITLE
AddressBinder: fix, really check the default cert is available

### PR DESCRIPTION
**Pull request by tmds**
@Tratcher ptal

### CODE REVIEW

**Comment by tmds** [comment]
It's been a while since I made a contribution here.
I'm not able to build the repo.

When I execute `build.sh` in `src/Servers` I get:
```
/home/tmds/repos/aspnetcore/src/Servers/IIS/AspNetCoreModuleV2/gtest/gtest.vcxproj(39,3): error MSB4019: The imported project "/Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "/Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
/home/tmds/repos/aspnetcore/src/Servers/IIS/AspNetCoreModuleV2/CommonLib/CommonLib.vcxproj(36,3): error MSB4019: The imported project "/Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "/Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
/home/tmds/repos/aspnetcore/src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/AspNetCore.vcxproj(39,3): error MSB4019: The imported project "/Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "/Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
/home/tmds/repos/aspnetcore/src/Servers/IIS/AspNetCoreModuleV2/CommonLibTests/CommonLibTests.vcxproj(41,3): error MSB4019: The imported project "/Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "/Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
/home/tmds/repos/aspnetcore/src/Servers/IIS/AspNetCoreModuleV2/IISLib/IISLib.vcxproj(36,3): error MSB4019: The imported project "/Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "/Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
/home/tmds/repos/aspnetcore/src/Servers/IIS/AspNetCoreModuleV2/InProcessRequestHandler/InProcessRequestHandler.vcxproj(38,3): error MSB4019: The imported project "/Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "/Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
/home/tmds/repos/aspnetcore/src/Servers/IIS/AspNetCoreModuleV2/OutOfProcessRequestHandler/OutOfProcessRequestHandler.vcxproj(38,3): error MSB4019: The imported project "/Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "/Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
/home/tmds/repos/aspnetcore/src/Servers/IIS/AspNetCoreModuleV2/RequestHandlerLib/RequestHandlerLib.vcxproj(36,3): error MSB4019: The imported project "/Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "/Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
```

**Comment by tmds** [comment]
The change I'm making will not bind the default https endpoint when there is no developer certificate. I think that was the original intent based on this comment:

https://github.com/dotnet/aspnetcore/blob/014a198bccaa1d8e2f8db454e704ad19fff5e47e/src/Servers/Kestrel/Core/src/Internal/AddressBinder.cs#L159

**Comment by Tratcher** [comment]
@dotnet/aspnet-build why would build.sh include AspNetCoreModuleV2? It will only build on windows.
https://github.com/dotnet/aspnetcore/pull/32345#issuecomment-831152606

**Comment by Tratcher** [comment]
Hmm, I'm going to have to dig into this more. The code has been that way for a very long time and there was even a test to verify it.

**Comment by Tratcher** [comment]
Oh, I see. This test covers an obscure scenario where someone called UseHttps in ConfigureEndpointDefaults to provide a non-dev server cert. That's why it's an `||`, it's checking if UseHttps has already been called.

DefaultAddressStrategy is only invoked when no other addresses are provided, so I don't think this logic will have any other side-effects.

This seems by design. Were you encountering an issue with it?

**Comment by tmds** [comment]
> DefaultAddressStrategy is only invoked when no other addresses are provided, so I don't think this logic will have any other side-effects.

ok.

> This seems by design. Were you encountering an issue with it?

I'm looking for a way to opt-out of the default usage of HTTPS on localhost.
I had misunderstood the comment as: removing the developer certificate will not expose an HTTPS endpoint.

Let me create a ticket to discuss that further and close this PR in the meanwhile.

**Pull request closed without merging**
