### PR TITLE
Upgrade Selenium Version

### PR DESCRIPTION
**Pull request by TanayParikh**
Upgrading to latest stable selenium. The other two Selenium packages are already up to date.

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
If this works fine, please do the same in at least release/6.0.

Might be needed in our servicing branches too. But, let's wait until we hit problems there.

**Comment by TanayParikh** [comment]
Verified the Selenium E2E tests are working with the updated driver locally (as they're no longer run via the CI)

**Comment by sebastienros** [comment]
> Verified the Selenium E2E tests are working with the updated driver locally (as they're no longer run via the CI)

Do you meant that a PR that would update these versions doesn't use the updated versions?
I can see the step in my PR:

https://github.com/dotnet/aspnetcore/pull/36107

image

**Comment by TanayParikh** [comment]
I was referring to the src/Components/test/E2ETests specifically which use this selenium driver but are no longer run on the CI. This is different from the quarantined tests which as you noted are still on the CI.

**Comment by sebastienros** [comment]
Should these quarantined tests use the new selenium version? It shows 91 instead of 93 still:

https://dev.azure.com/dnceng/_apis/resources/Containers/8072696/Windows_Quarantined_Test_Results?itemPath=Windows_Quarantined_Test_Results%2FRelease%2FQuarantined%2FMicrosoft.AspNetCore.Components.E2ETests_net6.0_x64.html

**Comment by TanayParikh** [comment]
I believe those should be on 93 as well, don't see any reason why they would be intentionally a version behind.

**Pull request merged**
