### PR TITLE
[release/3.1] Remove Helix remnants

### PR DESCRIPTION
**Pull request by dougbu**
Have no Helix jobs in any existing pipeline
- Helix mentions are just confusing here
- `tell-mode` because this cleanup affects only test and test asset projects.

Changes:
- remove Helix-related files
- clean out Helix mentions in miscellaneous files
- clean out Helix mentions in *.csproj files
- clean out Helix mentions in *.cs files

### CODE REVIEW

**Comment by dougbu** [comment]
/fyi this will probably be easier to review going through the commits individually

**Review by wtgodbe — APPROVED** [review]

**Comment by wtgodbe** [comment]
Whoops, didn't mean to approve yet, still looking

**Review by wtgodbe — APPROVED** [review]
Looks good assuming all tests pass

**Comment by dougbu** [comment]
> assuming all tests pass

Was all green before I marked this as ready for review 😺

**Pull request merged**
