### PR TITLE
show dnvm's current location

### PR DESCRIPTION
**Pull request by mishfit**
Okay so dnvm is't where it expected it would be.
Perhaps it's just me but I haven't got a clue where
I put it in the first place

### CODE REVIEW

**Comment by mishfit** [comment]
@Eilon could you take a look at this? It's silly but dnvm went from brew install to a simple curl call and might throw off those that installed using brew previously (or perhaps it will only ever throw me off and no one else)

**Comment by pranavkm** [comment]
@mishfit, could you send this PR to https://github.com/aspnet/dnvm? The file here gets pulled in from the other repo.

**Comment by pranavkm** [comment]
Closing this

**Comment by mishfit** [comment]
Absolutely, wasn't aware of the flow

**Pull request closed without merging**
