### PR TITLE
Update ExpectedObjFilesAfterRestore

### PR DESCRIPTION
**Pull request by JunTaoLuo**
NuGet Client now produces .dgspec.json files Addresses https://github.com/aspnet/AspNetCore-Internal/issues/2916

### CODE REVIEW

**Comment by dougbu** [comment]
@mmitche please help @JunTaoLuo understand how to correctly kick off a run of our [AspNetCore-e2e-tests pipeline](https://dnceng.visualstudio.com/internal/_build?definitionId=134). Likely need more ~~cowbell~~ credentials and / or restore sources.

Much appreciated

**Comment by JunTaoLuo** [comment]
Currently, it's complaining about missing `RestoreSources`:

```
D:\a\1\s\test\Cli.FunctionalTests\run-tests.ps1 : Missing an argument for parameter 'RestoreSources'. Specify a 
parameter of type 'System.Object' and try again.
```

There may be more missing parameters. See internal run: https://dnceng.visualstudio.com/internal/_build/results?buildId=460686&view=logs&j=61c2812f-92d1-5864-b571-194394639218&t=229a40e8-15f4-53c9-ae15-3eabaccf4cd0&l=20

**Comment by JunTaoLuo** [comment]
I'm going to mark this as ready. The changes is pretty simple and well understood. However, it'll be difficult to test until knowledgeable folks are back from vacation.

**Review by dougbu — APPROVED** [review]
Please find a way to do a test run of the pipeline before merging

**Comment by mmitche** [comment]
Following up in Teams. I'm not sure exactly how to do this without doing a full build though.

**Comment by JunTaoLuo** [comment]
I'm not sure if this is needed. 

From the verification runs, it looks like the 2.1 SDK is being used which doesn't produce the additional dgspec.json files. My guess is that at one point, the pipeline was misconfigured to install newer SDKs which cause the original issue. I'll close this PR for now but it'll be a simple fix if we ever do need to make it.

**Pull request closed without merging**
