### PR TITLE
Add support for IAsyncEnumerable<T> where T is value type (#17154)

### PR DESCRIPTION
**Pull request by pranavkm**
* Add support for IAsyncEnumerable<T> where T is value type

https://github.com/aspnet/AspNetCore/issues/17155

--------------------------------------

#### Description

In 3.0, we added support for IAsyncEnumerable<T> in MVC. Essentially you are allowed to return an IAsyncEnumerable<T> and MVC will serialize the contents for you without a blocking wait. Here’s some of the docs for it in action: https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-3.0#return-ienumerablet-or-iasyncenumerablet. In the current implementation, MVC will asynchronously read IAsyncEnumerable types, buffer it until the stream is exhausted (or we hit some user configured limit), and then serialize the contents. 

However, currently this feature only works when the type T is a reference type. When T is a value type, we pass the IAsyncEnumerable instance directly to the serializer. IAsyncEnumerable doesn’t implement IEnumerable<T> or any other collection contracts, so serializers end up returning an empty object. We got our first report of the issue today - https://github.com/aspnet/AspNetCore/issues/17139 where the user was surprised returning an IAsyncEnumerable<int> produced an empty object. 

#### Customer Impact

Returning an `IAsyncEnumerable<T>` where T is a value type results in no JSON output
		
#### Regression?

No, the feature hasn't worked correctly since it was introduced.
		
#### Risk

Low. The feature does not currently work correctly, so we do not expect users to be broken by this when it starts working. The code change is fairly minimal and well tested.

### CODE REVIEW

**Review by darielopper — APPROVED** [review]

**Comment by vivmishra** [comment]
Moved to Mar as per Tactics. Will need to be explicitly approved for Feb, if required.

**Comment by Pilchie** [comment]
I believe this should be back to 3.1.2 now.  @pranavkm / @mkArtakMSFT can we get this merged by EOD today?

**Review by SteveSandersonMS — DISMISSED** [review]
Looks like the change to `blazor.server.js` is accidental and should be reverted.

**Review by SteveSandersonMS — COMMENTED** [review]
Thanks for removing the unwanted change!

**Review by mkArtakMSFT — APPROVED** [review]

**Pull request merged**
