### PR TITLE
Pubternal IHttpHeadersHandler

### PR DESCRIPTION
**Pull request by Tratcher**
A possible solution to the pubternal shared code issues.

### CODE REVIEW

**Review by halter73 — APPROVED** [review]
LGTM

**Comment by Tratcher** [comment]
@aspnet/http2 IHttpHeadersHandler is something we moved into shared code for HPACK. It was previously a 'pubternal' API in our code base that our benchmarks infrastructure depended on. This PR restores it as a pubternal API in its original namespace until we can come up with a cleaner solution. I used ifdefs so no changes should be required in the runtime repo.

**Review by jkotalik — APPROVED** [review]

**Comment by jkotalik** [comment]
Is there anyway to confirm by merging this PR that benchmarks will build again? I'd prefer to have that inner loop fast as we have gone back and forth fixing pieces.

**Comment by halter73** [comment]
@Tratcher Are you planning to open a PR in https://github.com/dotnet/runtime to synchronize these changes?

**Pull request merged**
