### PR TITLE
Renamed `kpm restore` to `dnu restore`

### PR DESCRIPTION
**Pull request by henkmollema**
Looks like it was missed by the update.

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@henkmollema__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft Open Technologies, Inc. and real humans are currently evaluating your PR.</p>

TTYL, MSOTBOT;

**Comment by Eilon** [comment]
Wrong branch. 'master' is for beta3, which was still 'kpm'. The 'dev' branch has the latest changes.

**Comment by msotclas** [comment]
Hi __@henkmollema__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft Open Technologies, Inc. and real humans are currently evaluating your PR.</p>

TTYL, MSOTBOT;

**Comment by Eilon** [comment]
Actually, sorry, reopening this and will let @glennc handle it :smile:

**Comment by henkmollema** [comment]
@Eilon  I noticed that `k` was renamed to `dnx` and figured this one was forgotten. Need this on the dev branch too, or..?

**Comment by Eilon** [comment]
@glennc is in the process of fixing up the Home repo so I'll let him figure out the right thing to do.

**Pull request closed without merging**
