### PR TITLE
Fix bad automated merge in 2dc908d

### PR DESCRIPTION
**Pull request by 0xced**
Commit 2dc908d502888ffd9f6cfb306d58f0337caf004b (an automated merge) introduced weird behaviours in the dotnet-dev-certs tool.

### CODE REVIEW

**Comment by 0xced** [comment]
@javiercn Could you please have a look?

**Review by javiercn — APPROVED** [review]
LGTM.

**Comment by 0xced** [comment]
Can someone please press the merge button? 😉

**Comment by pranavkm** [comment]
@0xced looks like there are merge conflicts in your PR. Can you rebase if this change is still relevant?

**Comment by 0xced** [comment]
The code has completely changed since my original pull request so it's not relevant anymore.

**Pull request closed without merging**
