### PR TITLE
Make UseStatusCodePagesWithReExecute clear Endpoints

### PR DESCRIPTION
**Pull request by Tratcher**
#13715 There was a regression when switching to Endpoint based routing. When the status code component tries to re-execute the pipeline there is some state that needs to be cleared first such as the endpoint, otherwise the request will be routed to the old endpoint again.

Normally a middleware would do it's own cleanup (e.g. routing), but that significantly impacted the perf in the case of routing.

In 3.0 @NTaylorMullen Fixed this in UseExceptionHandlerWithReExecute but we missed UseStatusCodePagesWithReExecute.
https://github.com/aspnet/AspNetCore/commit/1f0641f5c0c8552f9605ff782ba1a27c06f4cedf#diff-abb2b51ad2d2d988debc78909b2674d9

FYI: I split the test files for exception handler and status code handler.

### CODE REVIEW

**Comment by anurse** [comment]
Will need @Pilchie approval to take a bug fix in 3.1

**Review by NTaylorMullen — APPROVED** [review]

**Comment by Tratcher** [comment]
@Pilchie @anurse this is ready to merge.

**Comment by anurse** [comment]
Seems good to me given that we did it for `UseExceptionHandlerWithReExecute`. I endorse this for 3.1

**Comment by Pilchie** [comment]
Agreed.  Approved for 3.1

**Pull request merged**
