### PR TITLE
Enable Docker Support checkbox for Blazor Server apps and gRPC apps.

### PR DESCRIPTION
**Pull request by pratiksanglikar**
Summary of the changes 
 - Enable "Enable Docker Support" checkbox for Blazor Server apps.
 - Enable "Enable Docker Support" checkbox for gRPC apps.

Addresses [#938514](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/938514) And [#938373](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/938373).

### CODE REVIEW

**Comment by ryanbrandenburg** [comment]
I've updated your original comment with links to the AZDO issues you seem to have been trying to mention.

Could you give us some more context here? What does it mean to "Support Docker" in this case? I would have guessed that that means there's a docker file which the template can use, and we don't have such a file. If what it means is that VS can create a docker-file for you, what would even by the case under which a template DOESN'T support docker?

@danroth27 for the experience and background here.

**Comment by pratiksanglikar** [comment]
Hi @ryanbrandenburg ,
The changes are related to the following dialogue box - 
Enable Docker Support

The Blazor apps and gRPC apps support Docker. 
Blazor Server apps and gRPC apps have been tested with Docker and they work as expected.

**Review by danroth27 — APPROVED** [review]
LGTM

**Comment by ryanbrandenburg** [comment]
@pratiksanglikar what I'm asking is what the difference between a template which supports docker and a template without is. If @danroth27 says it's fine I'm sure it is, but I'd like to understand how and why.

**Comment by pratiksanglikar** [comment]
@ryanbrandenburg Sorry my mistake, the image link in my earlier comment doesn't work, but here it is - [here](https://imgur.com/a/MXWSUP8) so when a template supports docker, the checkbox in the image is enabled or if the template doesn't support docker, then the checkbox is disabled.

That checkbox gives ability to enable docker support while creating the project instead of adding the docker support through context menu after the project is created.
Does that answer your question?

**Comment by ryanbrandenburg** [comment]
I think I'm being a bit unclear, what I'm trying to ask is how I, as a template author, know if my template "supports docker". That is, if I'm creating a new template and I get to that property in the .json and I ask myself "Should this property be true or false?" how do I answer that question? Surely if the property exists then there must be templates for which the answer is false, and I'm trying to learn how to tell the difference.

**Comment by pratiksanglikar** [comment]
Okay, I got your question now. 
So, any .NET Core web project (which supports http/https) should work with docker as long as there are no new dependencies.

There is no fixed  formula as such which tells certainly if a project works with Docker.

Any project can be tested if it works with Docker by -
1. Create the project
2. From the right click context menu of the project, select `Add Docker Support`.
3. Test F5 in Debug and Release mode.

If it works, it is safe to add that flag in in the template.

**Comment by pratiksanglikar** [comment]
I'm closing this PR to open a new one due to this merge commit -
[https://github.com/aspnet/AspNetCore/commit/f6942804faab30faf7ae2b8165ee7138f1a685ae](https://github.com/aspnet/AspNetCore/commit/f6942804faab30faf7ae2b8165ee7138f1a685ae).

**Comment by pratiksanglikar** [comment]
[#13016](https://github.com/aspnet/AspNetCore/pull/13016) is the new PR.

**Comment by ryanbrandenburg** [comment]
Thanks, that's good to know for the future.

**Pull request closed without merging**
