### PR TITLE
Change namespace to prove that RootNamespaceAttribute still works

### PR DESCRIPTION
**Pull request by hishamco**
This is related to the PR https://github.com/aspnet/Extensions/pull/2081

Addresses #10639

### CODE REVIEW

**Comment by hishamco** [comment]
FYI this will fail, because it should react to the above PR

**Comment by ryanbrandenburg** [comment]
Good reaction to take once the mentioned PR is in.

**Comment by hishamco** [comment]
@pranavkm this need to be merged to in reaction of the other merged PR

**Comment by pranavkm** [comment]
@hishamco we'd have to wait until we've picked up a new build of Extensions and rebase these changes. Might take a couple of days for the build dependency to flow through.

**Comment by hishamco** [comment]
You are right to avoid breaking the current build

Thanks..

**Comment by hishamco** [comment]
Sure

**Comment by hishamco** [comment]
Yep, I notice that, unfortunately i'm still blocked by https://github.com/aspnet/Extensions/issues/1931, but I will try to look into the AzurePipeline logs

**Comment by mkArtakMSFT** [comment]
Thanks for your effort. This has been done already as part of a different PR.

**Pull request closed without merging**
