### PR TITLE
Add compatibility suppression files to repo

### PR DESCRIPTION
**Pull request by JamesNK**
Every time I build aspnetcore framework directory, these files are written to disk. I have to avoid adding them to commits.

Either they should be added to the repo, added to .gitignore, or not written at all.

### CODE REVIEW

**Comment by JamesNK** [comment]
cc @dotnet/aspnet-admins

**Comment by wtgodbe** [comment]
Could you try flipping this to `false` instead: https://github.com/dotnet/aspnetcore/blob/f543e3552514c5c420eeddd55c505bbc131f10a6/Directory.Build.targets#L178

**Comment by mitchdenny** [comment]
Setting this value to **false** seems to result in a build failure:

```
C:\Code\dotnet\aspnetcore\.dotnet\sdk\8.0.100-alpha.1.22531.1\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ApiCompat.ValidatePackage.targets(37,5):
 error PKV0001: Target framework net7.0 does not have a compatible compile time asset in the package. [C:\Code\dotnet\aspnetcore\src\Framework\App.
Runtime\src\Microsoft.AspNetCore.App.Runtime.csproj]
```

**Review by wtgodbe — APPROVED** [review]

**Comment by TanayParikh** [comment]
There are more: https://github.com/dotnet/aspnetcore/pull/45681

**Pull request merged**
