### PR TITLE
Compatibility Suppressions

### PR DESCRIPTION
**Pull request by TanayParikh**
Part 2 of: https://github.com/dotnet/aspnetcore/pull/45507

These are all auto-generated when I build.

### CODE REVIEW

**Comment by JamesNK** [comment]
The order of content in these files is changing. What is producing them? Is there a bug in it that they're not explicitly ordered?

**Comment by TanayParikh** [comment]
> The order of content in these files is changing. What is producing them? Is there a bug in it that they're not explicitly ordered?

No idea, @wtgodbe @dougbu?

**Comment by wtgodbe** [comment]
This is from the package validation SDK, which used to be owned by Anirudh. @ViktorHofer @ericstj who owns that tool now? Did something change there?

**Comment by ViktorHofer** [comment]
> 
The order of content in these files is changing. What is producing them? Is there a bug in it that they're not explicitly ordered?

These suppressions weren't ordered before and we changed that with the .NET 7 release of ApiCompat / PackageValidation.

> This is from the package validation SDK, which used to be owned by Anirudh. @ViktorHofer @ericstj who owns that tool now? Did something change there?

Feel free to ping me or @smasher164 for ApiCompat / PackageValidation questions going forward. We received ownership of it during .NET 7.

**Review by wtgodbe — APPROVED** [review]

**Pull request merged**
