### PR TITLE
Missing $ in WebAssemblyComponentParameterDeserializer when throwing InvalidOperationException

### PR DESCRIPTION
**Pull request by xaberue**
# Missing $ in WebAssemblyComponentParameterDeserializer when throwing InvalidOperationException

- [X] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [X] You've included unit or integration tests for your change, where applicable.
- [X] You've included inline docs for your change, where applicable.
- [X] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Description

The dollar $ sign is missing in the interpolated string used for throwing an InvalidOperationException in WebAssemblyComponentParameterDeserializer, throwing non useful messages in these particular scenarios.

Fixes #52537

### CODE REVIEW

**Review by surayya-MS — APPROVED** [review]
Thank you for your contribution, @xaberue !

**Comment by surayya-MS** [comment]
> I've noticed also that the name of the class is not matching the file name:
> 
> Class: WebAssemblyComponentParameterDeserializer File: ClientComponentParameterDeserializer
> 
> Do you think worth it and/or needed to change the file name mathing the class name?

Thanks for catching that! Yes, I think we should change the file name to match the class `WebAssemblyComponentParameterDeserializer`. Let's do it in this PR.

cc @dotnet/aspnet-blazor-eng

**Comment by surayya-MS** [comment]
@xaberue, could you please do it in this PR?

**Comment by xaberue** [comment]
Done @surayya-MS , file name aligned with its class!

**Review by danmoseley — APPROVED** [review]
Thanks!

I wonder how feasible it would be to Grep for other similar mistakes.

**Pull request merged**
