### PR TITLE
Update jQuery 2.2 and 3.3.1 in samples to 3.4.1 (#20356)

### PR DESCRIPTION
**Pull request by HaoK**
Cherrypick of f1dcc5925555e01ab2559deba93d6f0f4d58bb73 to release/3.1

### CODE REVIEW

**Review by ryanbrandenburg — APPROVED** [review]
:shipit:

**Comment by HaoK** [comment]
@aspnet-build is the pr check hung?  I went to the pipeline page and everything is green but the linux-arm check on the PR is still waiting...

**Comment by HaoK** [comment]
Closing since there's a 3.5.1 version now, we should merge that instead https://github.com/dotnet/aspnetcore/pull/21577

**Pull request closed without merging**
