### PR TITLE
Re-add key

### PR DESCRIPTION
**Pull request by ryanbrandenburg**
Got excluded in the move.

### CODE REVIEW

**Comment by natemcmaster** [comment]
Instead of adding duplicates of this file, can we update the build properties to use this file instead? https://github.com/aspnet/AspNetCore/blob/master/eng/AspNetCore.snk. They should be identical.

**Comment by ryanbrandenburg** [comment]
Can do.

**Comment by ryanbrandenburg** [comment]
:up::date:

**Review by natemcmaster — APPROVED** [review]

**Comment by ryanbrandenburg** [comment]
Failure was kestrel tests. Merging.

**Pull request merged**
