### PR TITLE
Supporting pseudo-element attribute in css link fallback (#38146)

### LINKED ISSUE #38146: Add fallback tests based on css pseudo-elements
**Motivation:**

CSS for a popular CDN package [Bootstrap Icons](https://icons.getbootstrap.com/) consists entirely of pseudo-element definitions, such as below:

```
.bi::before {
  display: inline-block;
  font-family: bootstrap-icons !important;
   ...
}
```

The current implementation of the ASP.NET fallback tester offers no support for pseudo-elements, because the JavaScript for the tester calls a single-parameter overload of [`getComputedStyle`](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle). To test pseudo-elements, we need to pass the name of the the pseudo-element to be tested as a second parameter of `getComputedStyle`.

**Solution:**

We add support for testing pseudo-elements by setting an `asp-fallback-test-pseudo-element` attribute:

    ...
    asp-fallback-test-class="bi"
    asp-fallback-test-pseudo-element="before"
    ...

We then pass the value of the `asp-fallback-test-pseudo-element` as the second parameter to the fallback tester function, which then forwards it to `getComputedStyle`; if no value is specified, we pass `null`.

### PR DESCRIPTION
**Pull request by dasblinkenlight**
# <link> fallback testing based on css pseudo-elements

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Enhances fallback testing of the <link> element by checking css pseudo-elements

## Description

Current implementation uses a small Javascript function to test if a CDN load of a resource has been successful by checking if a specified css element is present after the load. This does not work when the resource is a css that consists entirely of pseudo-elements (i.e. items with ::before or ::after suffixes).

This change adds a second script that is identical to the current one, but takes the name of the pseudo-element as an additional parameter, and passes it to the getComputedStyle function.

The changes to the actual code are minimal. I made them for 100% backward compatibility: when the newly added `asp-fallback-test-pseudo-element` attribute is not present, the JavaScript function generated by the tag helper remain the same as in the current code.

The majority of the changes in this pull request are in the unit test code and the test data. Since the new attribute is optional, I made copies of all unit tests in which the new attribute is relevant, and adjusted the generated code to match the new functionality.

Fixes #38146

### CODE REVIEW

**Comment by dasblinkenlight** [comment]
@dotnet-policy-service agree

**Comment by dasblinkenlight** [comment]
The failure looks unrelated to the change that I am submitting. [There is an open issue for it](https://github.com/dotnet/aspnetcore/issues/50802). Please advise on how to work around.

**Comment by dasblinkenlight** [comment]
@NTaylorMullen If you are still associated with this project, could you please review the change? The code change is pretty small, most of the diffs come from the changes to unit tests and their output.

**Comment by mkArtakMSFT** [comment]
Thanks for your PR, @dasblinkenlight.
@javiercn could you please review this change? Thanks!

**Comment by dasblinkenlight** [comment]
@javiercn, could you please take a look at this? It isn't as large as it seems - 95% of the change is the additional unit tests and their output; the change itself is a few dozen lines.

**Pull request closed without merging**
