### PR TITLE
Try updating SDK

### PR DESCRIPTION
**Pull request by pakrym**
cc @sebastienros

### CODE REVIEW

**Comment by pakrym** [comment]
Blocked on https://github.com/dotnet/sdk/pull/3002

**Comment by sebastienros** [comment]
Do you mean you will take a newer sdk instead? But in that case you would just close this PR, so I don't get why it's blocked.

**Comment by pakrym** [comment]
Ok, I'll close it after it fails.

**Comment by pakrym** [comment]
Hm, it looks like it will pass. I guess we are not affected by the mentioned issue.

**Comment by sebastienros** [comment]
Somehow expected, this SDK is much older (2 weeks), the latest is around `3.0.100-preview4-010553` and the issue only appeared yesterday. This is the one I was using on benchmarks.

I think we should still take it, and then the new one when it's ready, because there might be other issues with it.

**Review by sebastienros — APPROVED** [review]

**Pull request merged**
