### PR TITLE
Rename class "error-ui" to "blazor-error-ui"

### PR DESCRIPTION
**Pull request by adrianwright109**
Follow up PR to #14636 

cc @SteveSandersonMS

### CODE REVIEW

**Review by ryanbrandenburg — APPROVED** [review]
Good call, less likely to conflict with existing classes.

**Comment by ryanbrandenburg** [comment]
Looks like an unrelated test failed due to flakiness. I'm retrying now.

**Comment by ryanbrandenburg** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=383862

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2483

**Review by SteveSandersonMS — APPROVED** [review]
Superb - thanks!

**Pull request merged**
