### PR TITLE
Prevent background process from crashing test when writing to the test output helper

### PR DESCRIPTION
**Pull request by JunTaoLuo**
I think I know what's causing the crashes.

The interop tests are set up like the following:

A single server is launched in a test fixture for all test cases.
The server is passed an ITestOutputHelper that's used during the entire duration of the tests.
If the test server tries to write anything to the ITestOutputHelper in between the test cases, the ITestOutputHelper is in an invalid state since no test is active. This causes a crash.

~I think the proper fix is to have the server not write to the ITestOutputHelper in between test cases. As a tactical fix though I think we can just ignore these exceptions when they are thrown.~

~Or better yet, use file logging instead so there's no contention. In this case, the server maintains its own logs and write to file. During each test case run, the server also writes to the test case's file logs so that it's easy to correlate between server/client logs.~

We ended up deciding to just launch a server instance for each test case.

### CODE REVIEW

**Comment by Pilchie** [comment]
Oops.  Accidental click.

**Comment by JunTaoLuo** [comment]
Not working on my dev machine so I can't build while I'm setting up my backup box. Let's see how many attempts it takes me to get it right when coding blind.

**Review by JamesNK — APPROVED** [review]
Would be nice to shutdown the server gracefully, but killing the server process should be fine. Can revisit if there is a need in the future.

**Comment by Tratcher** [comment]
Failed again on master: https://dev.azure.com/dnceng/internal/_build/results?buildId=580057&view=ms.vss-test-web.build-test-results-tab&runId=18238376&resultId=120468&paneView=attachments

**Pull request merged**
