### PR TITLE
Try to fix helix output path warning

### LINKED ISSUE #22246: Fix warning "The OutputPath property is not set for project 'helix.proj'."
Part of https://github.com/dotnet/aspnetcore/issues/22240

Happens during the Test Helix x64 step. Full warning text below:

> C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(778,5): warning : The OutputPath property is not set for project 'helix.proj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Release'  Platform=''.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [F:\workspace\_work\1\s\eng\helix\helix.proj]

@HaoK may know more about this one

### PR DESCRIPTION
**Pull request by HaoK**

### CODE REVIEW

**Comment by HaoK** [comment]
Looks like that did the trick for the output path warning

**Comment by HaoK** [comment]
Fixes https://github.com/dotnet/aspnetcore/issues/22246

**Comment by HaoK** [comment]
See https://dev.azure.com/dnceng/public/_build/results?buildId=660748&view=logs&jobId=db0106bb-d5d0-5bc4-063c-f858231502dc&j=3f6d4e0f-1b71-56b5-361e-d95b6e6da15a&t=d5bf30bc-9e5a-596c-d1c8-39e2dfa42d49 

build.cmd output compared to 

https://dev.azure.com/dnceng/public/_build/results?buildId=660542&view=logs&j=8c9dd6ae-5017-5a70-997c-c2386fed4e85&t=67839355-6a03-55d6-fbd7-5d56c2fd9ea1

**Review by dougbu — COMMENTED** [review]
Using pseudo-private properties this way feels like a brittle hack. Does the SDK team have anything coming that would be more first-class?

And, stepping back a bit, is there another way to achieve the same goal as why we make `$(OutputPath)` empty in the first place? (I guessed at the reasons in #22246 but am not positive.)

**Comment by HaoK** [comment]
I don't have any opinions here, this is what was suggested in the main arcade issue I filed here: https://github.com/dotnet/arcade/issues/1605

**Comment by dougbu** [comment]
I asked about the hackiness in that issue. But, back to my second question, why are we emptying `$(OutputPath)` in the first place?

**Comment by HaoK** [comment]
I don't have much context on why we occasionally empty out OutputPath in some of our projects other it looks like the clearing of output path was done by nate's PR that moved to obj/bin directories to root https://github.com/dotnet/aspnetcore/pull/10063.

**Comment by dougbu** [comment]
Nate linked that change to migrating tests to Helix but also mentioned some test projects didn't work when Arcade set `$(OutputPath)` to point under artifacts/ That implies to me that we're covering up problems a year later.

In any case, a number of the projects that do this contain comments linking to issues. Are those issues still current?

**Comment by HaoK** [comment]
I would guess those test projects still don't work without the output path hack then?  Those happen to also be the same tests that aren't the canonical xunit dll and run tests, which is why they overlapped with many of the projects that weren't trivial to enable on helix.

The PR comments is the only context I have, as far as I can tell:

"Add overrides for tests which still assert test binaries exist in a given location relative to the source code"

"Test failures on this PR correspond exactly with tests that are disabled in Helix. The root of the problem appears to be the same -- the test code makes assumptions about the location of source code relative to the test binary. These assumptions are not true in Helix and not true in this PR where obj/ and bin/ directories have been moved.

"Fixing this requires updating a lot of test code. @HaoK opened issues to track most of these test projects months ago, but we haven't seen traction on this. I see some of this issues have been punted or backlogged."

So the fixes we've generally made to enable some of these tests on helix have explicit helix environment checks, so they no-op in non helix environments.  

I think we should just take the property set :)

**Comment by dougbu** [comment]
Suggest we close this because setting `$(OutputPath)` gets rid of the warnings. I've done that in #22395.

**Pull request closed without merging**
