### PR TITLE
Added instruction to install unzip in order to unpack runtime packages

### PR DESCRIPTION
**Pull request by onatm**
Added instruction to install **unzip** in order to prevent getting an error message when `dnvm use` is executed.
- When I followed the instructions in [Getting Started](https://github.com/aspnet/Home/blob/dev/GettingStartedDeb.md) I ran into `Cannot find dnx-mono.1.0.0-beta4, do you need to run 'dnvm install 1.0.0-beta4'?`. This is solved by installing **unzip** package.

### CODE REVIEW

**Comment by Eilon** [comment]
@glennc ?

**Comment by jasonwilliams200OK** [comment]
Does this conflicts with https://github.com/aspnet/Home/pull/627? If latter is merged then the instruction to run the command would be rendered redundant.

**Comment by onatm** [comment]
@jasonwilliams200OK it conflicts with #627. However, you don't need 'unzip' to install 'libuv'.

**Comment by onatm** [comment]
any update?

**Comment by glennc** [comment]
I'm ok with this one, but perhaps it makes sense to just add a general pre-reqs section to the top of the instructions, what do you think?

**Comment by onatm** [comment]
You are right, general pre-reqs section would be more useful. So, should i create another pr for it?

**Comment by jasonwilliams200OK** [comment]
@onatm, you can amend the commits of this PR:

```bash
# cd into-aspnet-home-directory
notepad .\README
# make changes in the file
# save and close the file
git push -f
```

**Comment by glennc** [comment]
I am ok with whatever works best for you, closing this and starting another or amending this one.

**Comment by onatm** [comment]
Does it look OK now?

**Comment by glennc** [comment]
Yeah, looking good. Can you move curl to the prerequisites section as well? Get it out of the kestrel install step.

On a side note we should make DNVM more flexible so that it can work with wget as well at some point: https://github.com/aspnet/dnvm/blob/dev/src/dnvm.sh#L74

But that is a different issue, for a another time...

**Comment by onatm** [comment]
I added 'Get Curl' to prerequisites section.

I am looking forward to `wget` download option :eyes:

**Comment by onatm** [comment]
ping :bell:

**Comment by glennc** [comment]
Seems good. @danroth27 are you ok with this?

**Comment by danroth27** [comment]
Sure :shipit:
At some point we should probably transition all of the Home repo content to just point to http://docs.asp.net.

**Pull request merged**
