### PR TITLE
Update global.json to 10.0 sdk

### PR DESCRIPTION
**Pull request by BrennanConroy**

### CODE REVIEW

**Comment by wtgodbe** [comment]
Looks like we need to add the new prebuilt until https://github.com/dotnet/sdk/blob/c2257cb5b1617ddf9b2654547fa221f91b00c4e0/src/Installer/redist-installer/targets/GenerateBundledVersions.targets#L88-L90 gets updated

**Comment by BrennanConroy** [comment]
How do we do that

**Comment by wtgodbe** [comment]
Just need to add Microsoft.NETCore.App.Ref.9.0.0-preview.7.24405.7 to https://github.com/dotnet/aspnetcore/blob/main/eng/SourceBuildPrebuiltBaseline.xml, there's a link to the docs n
ext to the failure in the build logs. SourceBuild uploads a generated new manifest to the build artifacts as a convenience

Screenshot 2024-10-14 at 1 27 08 PM

**Review by wtgodbe — APPROVED** [review]

**Comment by MackinnonBuck** [comment]
Components E2E failures were due to the `M.A.C.CustomElements` project including the JS initializer module too late in the build process. This should now be fixed.

**Comment by halter73** [comment]
Does this indicate there was a breaking change in the SDK? Could this break other targets currently configured to run before `ResolveJSModuleStaticWebAssets` like [GenerateUnoWasmAssets](https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/2aa82e3b2b7e5f9e107313d08c053ed918d8873a/src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets#L276), because they're now run too late? That's all I found using grep.app, but that only indexes a small fraction of Blazor code.

**Comment by MackinnonBuck** [comment]
> Does this indicate there was a breaking change in the SDK?

Yeah, it's possible. I looked through the most recent changes to the StaticWebAssets SDK and didn't see anything that should impact the build order. Maybe we got lucky in the past that this target ran in time, and something else was recently introduced that indirectly changed the target execution order.

**Comment by MackinnonBuck** [comment]
cc @javiercn in case you have any thoughts or ideas about this

**Comment by javiercn** [comment]
@MackinnonBuck I don't remember why the integration for this package was done this way.

Normally we tell people to depend on `AssignTargetPaths` which runs before our pipeline.

**Comment by BrennanConroy** [comment]
Can we merge this then?

**Pull request merged**
