### PR TITLE
[blazor][wasm] Remove Wasm AOT Manifest and tool

### PR DESCRIPTION
**Pull request by lewing**
I think we can remove all of this, please let me know if I missed something or removed too much.

### CODE REVIEW

**Comment by lewing** [comment]
cc @BrennanConroy

**Review by pranavkm — APPROVED** [review]

**Comment by pranavkm** [comment]
Do we need a follow up in the installer / setup authoring for this? I'm guessing all of that was already resolved in p4.

**Comment by lewing** [comment]
I think https://github.com/dotnet/installer/pull/10594 was everything needed for installer.

**Review by dougbu — APPROVED** [review]
@lewing did you also clean up the `darc` subscriptions❔ Doesn't seem like they matter even before this change due to the updated emsdk names.

**Pull request merged**
