### PR TITLE
AddNativeClient AllowOfflineAccess

### PR DESCRIPTION
**Pull request by tibitoth**
Summary of the changes
 - `AddNativeClient` sets `AllowOfflineAccess` to `true`

Addresses #13434 

I don't know which branch to target to ship it in 3.0.

### CODE REVIEW

**Comment by HaoK** [comment]
@blowdart @javiercn does this seem like something reasonable to expose?

**Comment by blowdart** [comment]
I defer to @javiercn

**Comment by HaoK** [comment]
Underlying issue was closed, so closing PR

**Comment by abdu292** [comment]
@HaoK @blowdart Came across this when I was trying to implement a refresh token on a Xamarin.Forms app client. 
I'm using the version 5.0.9. Just was wondering if this is available yet out of the box as I remember this was planning for v5.

Can we have @tibitoth PR merged please  (that adds offline access to the NativeApp profile)

Thanks a bunch!

**Pull request closed without merging**
