### PR TITLE
Merging internal commits for release/5.0

### PR DESCRIPTION
**Pull request by vseanreesermsft**

### CODE REVIEW

**Comment by dougbu** [comment]
@jakubstilec @mmitche was 5.0.12 incoherent❔ Seeing very consistent failures in this PR:

``` text
dotnet-install: The resource at https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.12-servicing.21522.7/dotnet-runtime-5.0.12-servicing.21522.7-win-x64.zip is not available.
```

I'll check the manifest but thought I'd check-in w/ you two&hellip;

**Comment by dougbu** [comment]
❕ ❕ The problem isn't incoherence because `5.0.12-servicing.21522.7` is the _correct_ version. Are the redirects from https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.12-servicing.21522.7/ to the stable-versioned archives missing ❔ ❔

**Comment by mmitche** [comment]
> ❕ ❕ The problem isn't incoherence because `5.0.12-servicing.21522.7` is the _correct_ version. Are the redirects from https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.12-servicing.21522.7/ to the stable-versioned archives missing ❔ ❔

There's never a redirect for dotnetcli (it doesn't have that capability). It may have been incoherent. Checking.

**Comment by mmitche** [comment]
@dougbu @adiaaida @rbhanda 

It looks like the blob copy just didn't happen. Build is coherent. This is an aberration of how the release was done.

**Comment by dougbu** [comment]
@mmitche thanks for the information. Please ping or do the `azp run` thing when the blobs are in place

**Comment by adiaaida** [comment]
Looking

**Comment by adiaaida** [comment]
So the container/directory exists, but all of the files have the stable version number, not the non-stable, so it should be looking for https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.12-servicing.21522.7/dotnet-runtime-5.0.12-win-x64.zip

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
> So the container/directory exists, but all of the files have the stable version number, not the non-stable, so it should be looking for https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.12-servicing.21522.7/dotnet-runtime-5.0.12-win-x64.zip

Build isn't failing 💯% this time around. Does that mean `*productVersion.txt` files were temporarily missing ❔

**Comment by mmitche** [comment]
> > So the container/directory exists, but all of the files have the stable version number, not the non-stable, so it should be looking for https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.12-servicing.21522.7/dotnet-runtime-5.0.12-win-x64.zip
> 
> Build isn't failing 💯% this time around. Does that mean `*productVersion.txt` files were temporarily missing ❔

Possibly? But seems unlikely.

**Comment by adiaaida** [comment]
> > So the container/directory exists, but all of the files have the stable version number, not the non-stable, so it should be looking for https://dotnetcli.azureedge.net/dotnet/Runtime/5.0.12-servicing.21522.7/dotnet-runtime-5.0.12-win-x64.zip
> 
> Build isn't failing 💯% this time around. Does that mean `*productVersion.txt` files were temporarily missing ❔

Not sure about that. The productVersion.txt file is there now.

**Pull request merged**
