### PR TITLE
Update spa-templates submodule

### PR DESCRIPTION
**Pull request by HaoK**
Result of `git submodule update --remote spa-templates` attempting to pickup my spa changes

### CODE REVIEW

**Comment by HaoK** [comment]
This looks like it picks up more than just my changes as an fyi

**Review by halter73 — APPROVED** [review]

**Comment by halter73** [comment]
Thanks @HaoK I was just about to submit this PR myself because CTI validation was failing despite https://github.com/dotnet/aspnetcore/pull/34310 going in last week.

@dougbu How do we keep the submodules up to date?

**Comment by halter73** [comment]
Should we close this in favor of #34499?

**Comment by dougbu** [comment]
> Should we close this in favor of #34499?

I'd rather we stop using my fork ASAP. Let's not cause a conflict w/ #34499 by merging this.

Are you in a rush @HaoK❔ If yes, I could re-update the submodule in #34499.

**Comment by dougbu** [comment]
Suggest fixing this up after #34499 is in

**Comment by HaoK** [comment]
No rush, just let me know what i need to update after #34499 is in, do I just need to rerun the command?

**Comment by dougbu** [comment]
> do I just need to rerun the command?

You'll probably need to run `git submodule sync -- src/submodules/spa-templates` first since the submodule URI is changing in #34499

**Comment by dougbu** [comment]
#34499 is in now 😺

**Comment by HaoK** [comment]
@dougbu how come https://github.com/dotnet/spa-templates/pull/4/files doesn't show up in this, I see the commit sha is correct I think

**Comment by HaoK** [comment]
Never mind, I didn't push to github so that was why the PR didn't show it :)

**Comment by HaoK** [comment]
@dougbu if this looks good to you, I'll merge

**Comment by dougbu** [comment]
> @dougbu if this looks good to you, I'll merge

&hellip; on green you mean 😺

I can't comment on the specific changes you're bringing in from dotnet/spa-templates but the "bringing in" part looks good.

**Comment by HaoK** [comment]
Well I just meant I'd click on the auto-merge button so yes :)

**Pull request merged**
