### PR TITLE
Update SDK to 7.0.100-rc.1.22368.21

### PR DESCRIPTION
**Pull request by halter73**

### CODE REVIEW

**Review by dougbu — COMMENTED** [review]
Ick, more new errors. Should we be supressing `CA1305` everywhere @davidfowl❔ Adding an `IFormatProvider` will likely uglify our beautiful code ☹️

**Comment by halter73** [comment]
@SteveSandersonMS @javiercn @JamesNK 

This SDK update is also leading to complaints that:

> src/Components/WebAssembly/WebAssembly/src/HotReload/HotReloadAgent.cs#L127
src/Components/WebAssembly/WebAssembly/src/HotReload/HotReloadAgent.cs(127,17): error IL2070: (NETCORE_ENGINEERING_TELEMETRY=Build) 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods', 'DynamicallyAccessedMemberTypes.NonPublicMethods' in call to 'System.Type.GetMethod(String, BindingFlags, Type[])'. The parameter 'handlerType' of method 'GetUpdateMethod(Type, String)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.

https://github.com/dotnet/aspnetcore/blob/02d559b42b1eacef606f151e9d8cab782fdc5e0d/src/Components/WebAssembly/WebAssembly/src/HotReload/HotReloadAgent.cs#L125-L136

It looks like `WebAssemblyHost.RunAsync()` is the public API that eventually calls into this. I don't know how we'd flow the `handlerType` to the linker from that call. But given this is hot reload, do we care about trimming? Can we supress this?

**Comment by JamesNK** [comment]
I backtracked through the code, and I think handlerType comes from this attribute: https://github.com/dotnet/runtime/blob/901bbbc57b2faaa5970e9257875d6821b63f7792/src/libraries/System.Private.CoreLib/src/System/Reflection/Metadata/MetadataUpdateHandlerAttribute.cs#L31

It has an attribute to include everything. The exact type is lost in reflection here:

https://github.com/dotnet/aspnetcore/blob/02d559b42b1eacef606f151e9d8cab782fdc5e0d/src/Components/WebAssembly/WebAssembly/src/HotReload/HotReloadAgent.cs#L63-L81

IMO add the DynamicallyAccessedMembers attribute to `GetHandlerActions` and below, then suppress the warning in `GetMetadataUpdateHandlerActions`.

**Comment by halter73** [comment]
I made the trimming changes you suggested with https://github.com/dotnet/aspnetcore/pull/42803/commits/031eab10d88b7e4e5ce5af8bfc9d0f3106ba0745.

**Review by JamesNK — APPROVED** [review]

**Pull request merged**
