### PR TITLE
Add MapInboundClaims top level sugar for JwtBearerOptions

### PR DESCRIPTION
**Pull request by HaoK**
Part of https://github.com/dotnet/aspnetcore/issues/22764

### CODE REVIEW

**Comment by HaoK** [comment]
Sigh no triggers for draft

**Comment by Tratcher** [comment]
What about OIDC?

**Comment by HaoK** [comment]
OIDC updated

**Comment by Tratcher** [comment]
And the samples:
https://github.com/dotnet/aspnetcore/blob/7e094d7b7d623d8aa4ae5133aef80844ba07208a/src/Security/Authentication/OpenIdConnect/samples/OpenIdConnectSample/Startup.cs#L92

**Review by Tratcher — APPROVED** [review]

**Pull request merged**
