### PR TITLE
Fix MSBuild property name for Microsoft.Build.Tasks.Core

### PR DESCRIPTION
**Pull request by eerhardt**
There was a missing 's', which caused source-build to use a pre-built when building.

Related to https://github.com/dotnet/source-build/issues/2412

### CODE REVIEW

**Review by MichaelSimons — COMMENTED** [review]
LGTM.  Should this target release/6.0 instead?

**Review by dseefeld — APPROVED** [review]

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
/fyi I enabled auto-squish for this PR

**Comment by MichaelSimons** [comment]
> How necessary and urgent in 'release/6.0' is this fix

This is required for .NET 6.0.  

>are we peeling an onion here?

Yes, we know there are a number of prebuilts in aspnetcore right now (3 direct and 9 indirect).  We are still investigating and it is unknown how many will require aspnetcore source changes.

**Comment by dougbu** [comment]
Alright. Nothing here will break non-source-build builds and we might as well move through the onion incrementally. @dotnet/aspnet-build if any of you have had success using the backport action, please do the needful here.

**Pull request merged**
