### PR TITLE
Fixing CI

### PR DESCRIPTION
**Pull request by jkotalik**

### CODE REVIEW

**Comment by jkotalik** [comment]
I chatted with @pranavkm and he said these files were accidentally added from 5.0 to master. Deleting them should fix the master build.

**Comment by dougbu** [comment]
Sorry, what happened here❔ Why don't we want these files in master❔ Looks like a merge forward left something out rather than included too much.

**Comment by jkotalik** [comment]
I defer to @pranavkm but these were deleted in master but had modifications in the 5.0-rc2 branch and I believe these were added accidentally (nothing else is in that folder).

**Comment by dougbu** [comment]
Ah, it all makes sense now 😺

**Review by pranavkm — APPROVED** [review]

**Pull request merged**
