### PR TITLE
Fix missing cors middleware exception message

### PR DESCRIPTION
**Pull request by Kahbazi**

### CODE REVIEW

**Review by mkArtakMSFT — APPROVED** [review]
Thanks for noticing this!

**Comment by mkArtakMSFT** [comment]
@Kahbazi looks like there are also some tests which validate the error message which now got changed.  Please correct those too so the PR checks pass.

**Comment by Kahbazi** [comment]
@mkArtakMSFT I fix the tests.

**Comment by mkArtakMSFT** [comment]
Closing and will reopen to update the checks state as there seems to be some issue where the checks got out of sync.

**Comment by mkArtakMSFT** [comment]
Force-merging this as these are only fixes in comments. GitHub somehow went out-of-sync with AzDO.

**Pull request merged**
