### PR TITLE
Normalize all the line endings

### LINKED ISSUE #27182: Fix the line endings in the appsettings. Development.json file
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Fix-the-line-endings-in-the-appsettings/1217713)._

---
[severity:It bothers me. A fix would be nice]
When I create a new Visual Studio ASP.NET Core web project, choose the empty template, when I open appsettings.json , all is fine but  when I open appsettings. Development.json, I alwasy get the nagging "Inconsistent line endings" dialog box... can you please fix that in the template?
(latest visual studio 2019 16.7.5)

Also do check the other projects.

---
#### Feedback Bot on 10/13/2020, 07:41 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/14/2020, 02:09 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### visualstudio on 10/14/2020, 02:32 AM: 

<p>I think all developers who opens that file (appsettings.Development.json) is impacted by the issue. What I want is that the file in the template gets its line-ending fixed so that you are not presented with that dialog below:</p><p> </p><p><br></p><p></p>

#### visualstudio on 10/14/2020, 02:34 AM: 

(private comment, text removed)
#### visualstudio on 10/14/2020, 02:34 AM: 

<p>using the ASP.NET Core 3.1 web project MVC template </p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by eugeneogongo**
Summary of the changes (Less than 80 chars)
 -  Use git to Normalize all the line endings in the repo. 
 -  Git command `git add --renormalize .`

Addresses #27182
closes #27182

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=27201) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=27201) before we can accept your contribution.<br/><br/>:x: eugeneogongo [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=27201)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=27201) it.</sub>

**Comment by javiercn** [comment]
@eugeneogongo thanks for your contribution.

We would be willing to take the changes to the appsettings files in the project templates, but we won't be taking these changes on other non related files.

These types of changes normally cause conflicts on other developers doing work on the repo, so we prefer to avoid them where possible if they don't have a lasting impact.

If you remove the changes for all the non related files, we will be happy to accept this PR.

**Comment by eugeneogongo** [comment]
Hey there,
Thanks for the review.
I will update the PR to contain files from the project Templates only.

Thank you again

**Comment by eugeneogongo** [comment]
@javiercn I made a commit that includes normalization of line endings in appsettings.*

**Review by javiercn — APPROVED** [review]

**Pull request merged**
