### PR TITLE
Remove DOTNET_CLI_DO_NOT_USE_MSBUILD_SERVER workaround

### PR DESCRIPTION
**Pull request by Tratcher**
https://github.com/dotnet/aspnetcore/pull/44797#issuecomment-1297539027

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
Suggest building a couple of times to confirm we don't see `dotnet msbuild` crashing again. I believe at least one of the possible error messages started w/ `Unhandled exception: System.IO.IOException: Connection timed out : 'Global\\msbuild-server-launch-`

**Review by wtgodbe — APPROVED** [review]

**Comment by dougbu** [comment]
🎈 🎉 🎈 🎉

**Pull request merged**
