### PR TITLE
Disable flaky music store test

### PR DESCRIPTION
**Pull request by jkotalik**
I see this test frequently failing on CI. Disabling for now.

### CODE REVIEW

**Comment by jkotalik** [comment]
@Eilon this is high priority. 3 PRs I had in the last few hours failed on it.

**Review by Eilon — APPROVED** [review]

**Comment by Eilon** [comment]
Sounds good. Is there a bug tracking re-enabling?

**Comment by jkotalik** [comment]
https://github.com/aspnet/AspNetCore/issues/8462

**Comment by Eilon** [comment]
Thanx! Looks like we've had several PDB-copy issues for a while so hopefully there's a common root cause we can address. cc @aspnet/brt.

**Comment by jkotalik** [comment]
I've only seen this failure with PDBs, but yes it is a common problem. 

Also https://github.com/aspnet/AspNetCore-Internal/issues/1951 for another flaky test.

**Pull request merged**
