### PR TITLE
Remove obsolete AzureAd

### PR DESCRIPTION
**Pull request by HaoK**
Part of https://github.com/dotnet/aspnetcore/issues/27529

### CODE REVIEW

**Comment by Tratcher** [comment]
There's a lot of discussion on #27529 about if removing these APIs is actually necessary. Yes they've been replaced, but the old ones still work so do we need to forcibly break people that are still using them?

Is there a clear functional problem here driving the removal?

**Comment by HaoK** [comment]
These have been a constant source of issues and errors, doesn't an LTS seem like a good time to encourage them to move to the intended final destination?  Basically bullet 2
>What's the maintenance cost of keeping the API around? This includes things like the number of issues reported by users, whether there's a lot of flaky tests associated with the API, etc.

**Comment by HaoK** [comment]
This seems analogous to our Azure Key Vault configuration provider which we also dropped rather than keeping around with obsolete

**Comment by Tratcher** [comment]
We already moved the templates so that should cut down on the incoming issues. The main concern is if we're forcing change on people who weren't broken. That's @blowdart's call.

**Comment by HaoK** [comment]
Right, I checked with  @blowdart before opening the PR :)

**Comment by blowdart** [comment]
I lean on kill it off, obviously. People do need to change, because the v1 endpoint will retire, probably before the LTS expiry. Same with the app creation API.

**Comment by blowdart** [comment]
This apparently needs a wider discussion :)

**Review by Tratcher — APPROVED** [review]

**Comment by HaoK** [comment]
@blowdart did we get everything straightened out on the process side on your end for approval?

**Comment by blowdart** [comment]
We did not. The thread is ongoing. I'll ressurect it. We may have to keep it for a while longer.

**Comment by blowdart** [comment]
Closing until v7

**Pull request closed without merging**
