### PR TITLE
[release/3.0] Switch to embedded package icon

### PR DESCRIPTION
**Pull request by wtgodbe**
Contributes to aspnet/AspNetCore-Internal#3103

### CODE REVIEW

**Comment by wtgodbe** [comment]
> .dotnet\sdk\3.0.100-preview8-013656\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(198,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) The element 'metadata' in namespace 'http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd' has invalid child element 'icon' in namespace 'http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd'. List of possible elements expected: 'releaseNotes, contentFiles, frameworkReferences, title, frameworkAssemblies, summary, dependencies, licenseUrl, owners, references, packageTypes, iconUrl, language' in namespace 'http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd'. This validation error occurred in a 'icon' element.

Same as https://github.com/aspnet/AspNetCore-Tooling/pull/1166#issuecomment-534743171. Maybe this is only happening in jobs that build packages by default? @dougbu should we just update to the GA SDK? All the repos are currently on `preview8`

**Comment by dougbu** [comment]
Yes, let's update the SDK to 3.0.0 GA. Wasn't Arcade forcing this a topic at tactics this morning @mmitche? If yes, what was the decision for Arcade and does it imply we should _not_ change the SDK?

/cc @Pilchie

**Comment by mmitche** [comment]
@dougbu Arcade will force the update, but feel free to get ahead of it.

FYI please update branding to 3.0.1 and turn off stable builds prior to checking anything else into 3.0

**Comment by wtgodbe** [comment]
Just updated to the GA SDK

**Review by dougbu — APPROVED** [review]

**Comment by wtgodbe** [comment]
Code Check:

> F:\workspace\_work\1\s\src\Azure\AzureAD\Authentication.AzureADB2C.UI\src\Microsoft.AspNetCore.Authentication.AzureADB2C.UI.csproj : error Undefined: Failed to download package 'Microsoft.NET.Sdk.Razor.3.0.0' from 'https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/be6219d6-ca7b-4704-9703-2d3dd3237766/nuget/v3/flat2/microsoft.net.sdk.razor/3.0.0/microsoft.net.sdk.razor.3.0.0.nupkg'.
F:\workspace\_work\1\s\src\Azure\AzureAD\Authentication.AzureADB2C.UI\src\Microsoft.AspNetCore.Authentication.AzureADB2C.UI.csproj : error Undefined: Response status code does not indicate success: 500 (Operation could not be completed within the specified time.).

**Comment by wtgodbe** [comment]
Lots of builds failing with:

>   The element 'metadata' in namespace 'http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd' has invalid child element 'icon' in namespace 'http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd'. List of possible elements expected: 'tags, language, iconUrl, description, requireLicenseAcceptance, dependencies, references, serviceable, releaseNotes, copyright, developmentDependency, contentFiles, summary, packageTypes, frameworkAssemblies' in namespace 'http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd'. This validation error occurred in a 'icon' element.

Seeing this in `src\Installers\Windows\TargetingPack\TargetingPack.wixproj` and `AfterSolutionBuild.proj`. The builds claim to be using the stable 3.0.0 SDK, so I'm not sure why we're still seeing this old error

**Comment by wtgodbe** [comment]
Ah, I think the issue is that these 2 projects are using old versions of nuget:

https://github.com/aspnet/AspNetCore/blob/master/src/Installers/Windows/GenerateNugetPackageWithMsi.ps1#L24-L28

https://github.com/aspnet/AspNetCore/blob/master/eng/tools/RepoTasks/RepoTasks.csproj#L15

The one in RepoTasks is probably safe to upgrade, but it looks like the issue referenced in GenerateNugetPackageWithMsi.ps1 is still active: https://github.com/NuGet/Home/issues/5016. @dougbu bumping the nuget version there seems likely to increase the build time (possibly significantly), can you suggest a different workaround? Will push a commit now to update these versions, as a test.

**Comment by wtgodbe** [comment]
The "Build Installers" step in x64/x86 build is the one to keep an eye on, it might become significantly slower

**Comment by wtgodbe** [comment]
Errors so far are about the build machines not having MSBuild 16.3 😞

**Comment by dougbu** [comment]
`msbuild` issue as a known problem w/ the agents. @Chrisboh should have more info.

W.r.t NuGet/Home#5016 isn't that problem specific to cases involving `..` relative paths?

**Comment by wtgodbe** [comment]
Going to try using a preview9 SDK as a temporary workaround - hopefully there is a window between when `PackageIconUrl` was deprecated, and when the SDK started requiring msbuild 16.3 (cc @JunTaoLuo)

**Comment by wtgodbe** [comment]
Hitting the `tar` thing now

**Comment by wtgodbe** [comment]
Can't use the preview9 SDK - will revert back to the GA one

**Pull request merged**
