### PR TITLE
Reeanble dataprotection test

### LINKED ISSUE #6720: [Helix] DataProtection System_UsesProvidedDirectoryAndCertificate fails on OSX
DataProtection/Extensions/test/DataProtectionProviderTests.cs System_UsesProvidedDirectoryAndCertificate fails only on OSX queue

```
[xUnit.net 00:00:01.28]     Microsoft.AspNetCore.DataProtection.DataProtectionProviderTests.System_UsesProvidedDirectoryAndCertificate [FAIL]
Failed   Microsoft.AspNetCore.DataProtection.DataProtectionProviderTests.System_UsesProvidedDirectoryAndCertificate
Error Message:
 Interop+AppleCrypto+AppleCommonCryptoCryptographicException : write permissions error
Stack Trace:
   at Interop.AppleCrypto.X509StoreAddCertificate(SafeKeychainItemHandle certOrIdentity, SafeKeychainHandle keychain)
   at Internal.Cryptography.Pal.StorePal.AppleKeychainStore.Add(ICertificatePal cert)
   at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate)
   at Microsoft.AspNetCore.DataProtection.DataProtectionProviderTests.System_UsesProvidedDirectoryAndCertificate() in /_/src/DataProtection/Extensions/test/DataProtectionProviderTests.cs:line 124
[xUnit.net 00:00:01.58]     Microsoft.AspNetCore.DataProtection.DataProtectionProviderTests.System_UsesProvidedDirectory_WithConfigurationCallback [SKIP]
Skipped  Microsoft.AspNetCore.DataProtection.DataProtectionProviderTests.System_UsesProvidedDirectory_WithConfigurationCallback
Results File: /Users/dotnet-bot/dotnetbuild/work/e46143d4-88da-42ae-96d7-42513595330a/Work/45b5d399-ffd0-4a6b-ab73-3fce0571cf50/Exec/TestResults/_dci-mac-build-083_2019-01-15_01_40_03.trx
```

### PR DESCRIPTION
**Pull request by HaoK**
Fixes https://github.com/dotnet/aspnetcore/issues/6720

### CODE REVIEW

**Comment by HaoK** [comment]
Looks like this issue with X509store has been fixed so this test can be reenabled

**Comment by HaoK** [comment]
Actually there was 2, so making sure both pass

**Comment by HaoK** [comment]
There's still a weird OSX specific failure on this one test, @blowdart do you know if there's special about certs and OSX, I know we saw similar quirky issues with the Cert auth as well.

```
The System_UsesProvidedDirectoryAndCertificate is failing with

Interop+AppleCrypto+AppleCommonCryptoCryptographicException : User interaction is not allowed.
```

I'll reenable the tests on all the other queues, and leave the issue open to follow up with this failure

**Comment by blowdart** [comment]
Oh yea, apple really screwed over certs in the new OS.  Maybe @bartonjs has some ideas here

**Review by dougbu — APPROVED** [review]
Looks fine as long as you revert the ci.yml changes before merging

**Comment by bartonjs** [comment]
@HaoK The "user interaction" error means (as far as I understand) that the user account has not yet unlocked their keychain (which happens on a GUI login, but apparently not an SSH login, when it's marked as auto-unlock).  The keychain is locked, but since the current application is not running in a UI session it can't pop up the keychain unlock dialog.

You might be able to adjust it in automation via `security unlock-keychain <other arguments go here, that I don't remember>`.

Alternatively, try to avoid modifying X509Store in tests. (Use the new API for contextual root trust instead of adding to the root stores; pass certificates explicitly instead of using store-enumeration inference... yeah, you probably need tests for those other modes, too... but maybe they're OK being on a more opportunistic/manual loop)

**Pull request merged**
