### PR TITLE
Update precedence and Identity of templates for 5.0

### PR DESCRIPTION
**Pull request by ryanbrandenburg**
Fixes https://github.com/dotnet/aspnetcore/issues/17553.

@mkArtakMSFT I believe it was you who created the mapping for `https://aka.ms/aspnetcore/5.0-third-party-notices last` time? We need to do that again. This is basically a copy of https://github.com/dotnet/aspnetcore/pull/14637/files, plus the fact that we have a new template.

### CODE REVIEW

**Review by mkArtakMSFT — APPROVED** [review]
Thanks!

**Review by phenning — APPROVED** [review]

**Review by vijayrkn — APPROVED** [review]

**Comment by dougbu** [comment]
@ryanbrandenburg doesn't downstream packaging use the template names i.e. doesn't something else need to change to pick up the new "5.0" templates?

**Comment by wtgodbe** [comment]
Are we taking this today, or will we have to wait for Monday?

CC @mmitche as this will effect the timeline for preview1

**Comment by vijayrkn** [comment]
Without this change, if 5.0 preview1 is installed, users wont be able to create 3.1 projects in VS. 
So yes, we need to take it for preview1.

**Comment by phenning** [comment]
@dougbu packaging is dependent on the package authoring not the individual template identities. I believe the package is currently being created properly.

**Comment by wtgodbe** [comment]
Tactics approved this, merging

**Pull request merged**
