### PR TITLE
Investigate flaky blazor templates

### LINKED ISSUE #23992: Flaky tests in BlazorWasmTemplateTest
####  Templates.Test.BlazorWasmTemplateTest.BlazorWasmHostedPwaTemplate_Works 

```
      OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:50945/wd/hub/session/c6a977b01d306caa0c61117a51f361e9/url timed out after 60 seconds.
      ---- System.Net.WebException : The operation has timed out.
      Stack Trace:
           at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
           at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
           at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
           at OpenQA.Selenium.Remote.RemoteWebDriver.set_Url(String value)
           at OpenQA.Selenium.Remote.RemoteNavigator.GoToUrl(Uri url)
        /_/src/ProjectTemplates/Shared/AspNetProcess.cs(87,0): at Templates.Test.Helpers.AspNetProcess.VisitInBrowser(IWebDriver driver)
        /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs(463,0): at Templates.Test.BlazorWasmTemplateTest.BuildAndRunTest(String appName, Project project, Boolean usesAuth)
        /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs(189,0): at Templates.Test.BlazorWasmTemplateTest.BlazorWasmHostedPwaTemplate_Works()
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
           at System.Net.HttpWebRequest.GetResponse()
           at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)

```

#### Templates.Test.BlazorWasmTemplateTest.BlazorWasmHostedTemplate_IndividualAuth_Works_WithLocalDB 

```
      OpenQA.Selenium.NoSuchElementException : no such element: Unable to locate element: {"method":"partial link text","selector":"Fetch data"}
  (Session info: headless chrome=84.0.4147.89)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17763 x86_64)
      Stack Trace:
           at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
           at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
           at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
           at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByPartialLinkText(String partialLinkText)
           at OpenQA.Selenium.By.<>c__DisplayClass21_0.<PartialLinkText>b__0(ISearchContext context)
        /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs(541,0): at Templates.Test.BlazorWasmTemplateTest.TestBasicNavigation(String appName, Boolean usesAuth, Boolean skipFetchData)
        /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs(464,0): at Templates.Test.BlazorWasmTemplateTest.BuildAndRunTest(String appName, Project project, Boolean usesAuth)
        /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs(309,0): at Templates.Test.BlazorWasmTemplateTest.BlazorWasmHostedTemplate_IndividualAuth_Works(Boolean useLocalDb)
        --- End of stack trace from previous location ---
```

#### Templates.Test.BlazorWasmTemplateTest.BlazorWasmHostedTemplate_IndividualAuth_Works_WithOutLocalDB

```
      OpenQA.Selenium.NoSuchElementException : no such element: Unable to locate element: {"method":"partial link text","selector":"Fetch data"}
  (Session info: headless chrome=84.0.4147.89)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17763 x86_64)
      Stack Trace:
           at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
           at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
           at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
           at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByPartialLinkText(String partialLinkText)
           at OpenQA.Selenium.By.<>c__DisplayClass21_0.<PartialLinkText>b__0(ISearchContext context)
        /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs(541,0): at Templates.Test.BlazorWasmTemplateTest.TestBasicNavigation(String appName, Boolean usesAuth, Boolean skipFetchData)
        /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs(464,0): at Templates.Test.BlazorWasmTemplateTest.BuildAndRunTest(String appName, Project project, Boolean usesAuth)
        /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs(309,0): at Templates.Test.BlazorWasmTemplateTest.BlazorWasmHostedTemplate_IndividualAuth_Works(Boolean useLocalDb)
        --- End of stack trace from previous location ---
```

All of these failures have massive logs associated with them. You can find them in the artifacts of https://dev.azure.com/dnceng/public/_build/results?buildId=731663&view=results

These failures were all in a single run that also demonstrated a bug in the shared ProcessEx class (see #23990), so we might want to take these failures with a grain of salt.

### PR DESCRIPTION
**Pull request by HaoK**
For: https://github.com/dotnet/aspnetcore/issues/23992

### CODE REVIEW

**Comment by BrennanConroy** [comment]
We should probably re-enable the tests for 5.0

**Comment by HaoK** [comment]
Okay I'll file a PR with just the revert of the skip tests for 5.0

**Comment by HaoK** [comment]
Looks like its only disabled in master, since the fix came from 3.1 https://github.com/dotnet/aspnetcore/blob/release/5.0/src/Shared/E2ETesting/E2ETesting.props looks fine so we are good in 5.0

**Comment by HaoK** [comment]
Yeah this is why i was confused since the tests were running in 5.0 PRs when I was investigating

**Comment by HaoK** [comment]
@javiercn is it normal to sometimes get empty screenshots from the selenium captures?  The Templates.Test.BlazorWasmTemplateTest.BlazorWasmStandaloneTemplate_IndividualAuth_Works png appears to be blank to me :(

**Comment by HaoK** [comment]
Note these tests seem to all fail together, i.e. from https://dev.azure.com/dnceng/public/_build/results?buildId=849186&view=ms.vss-test-web.build-test-results-tab&runId=27060606&resultId=100004&paneView=debug they all pass for two builds, then all of them fail, which seems like something might be getting borked at the infrastructure level

**Comment by BrennanConroy** [comment]
Possible issue
```
dbug: Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware[1]
              Failed to authenticate HTTPS connection.
              System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
               ---> System.ComponentModel.Win32Exception (0x80090327): An unknown error occurred while processing the certificate.
                 --- End of inner exception stack trace ---
                 at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
                 at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
```

**Comment by HaoK** [comment]
Ah that could explain it, @Tratcher any ideas what might cause this cert exception? Or how to dig deeper into this?  Its happen fairly reliability, in that I hit it within 3 builds today

**Comment by Tratcher** [comment]
https://docs.microsoft.com/en-us/windows/win32/secauthn/schannel-error-codes-for-tls-and-ssl-alerts
SEC_E_CERT_UNKNOWN
0x80090327

Which could be any of these:
TLS1_ALERT_BAD_CERTIFICATE
TLS1_ALERT_UNSUPPORTED_CERT
TLS1_ALERT_CERTIFICATE_UNKNOWN

Are these tests relying on the dev cert or are they using a specific test cert?

**Comment by HaoK** [comment]
These are just the template tests so the dev cert, they just do new template build and run without any extra operations I don't think.

**Comment by HaoK** [comment]
Could this mean the dev cert wasn't installed properly some % of the time?

**Comment by Tratcher** [comment]
Seems likely, or it's being messed up by another test. Tests using the dev cert should:
- Check it before starting the test
- Not run in parallel in case they try to fix the cert in parallel

Or, we should make these tests not use the dev cert.

**Comment by HaoK** [comment]
Do we have any tests that currently check if the dev cert is valid?  Aka is there any code I can steal for that?

**Comment by Tratcher** [comment]
@javiercn ?

**Comment by HaoK** [comment]
Rebased version continuing in https://github.com/dotnet/aspnetcore/pull/27948

**Pull request closed without merging**
