### PR TITLE
Included githubactions in dependabot config

### PR DESCRIPTION
**Pull request by naveensrinivasan**
# Included githubactions in dependabot config

- [ ] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description
- Included githubactions in the dependabot config
- GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

Fixes #{bug number} (in this specific format)

### CODE REVIEW

**Comment by dougbu** [comment]
@naveensrinivasan we use very few GitHub actions in this repo. What is the value of having Dependabot keep those few up-to-date❔ I'm not aware of security issues for example.

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan we use very few GitHub actions in this repo. What is the value of having Dependabot keep those few up-to-date❔ I'm not aware of security issues for example.

- https://nathandavison.com/blog/github-actions-and-the-threat-of-malicious-pull-requests

- https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

Here are some write-ups on security issues.

Even if the actions don't have threats now. It would prevent any future threats also the project gets updates on notifications on new version changes.

By including this it is only positive addition IMO other than the fact there are going to be notifications when there are new changes published for those actions.

For example https://github.com/dotnet/aspnetcore/blob/55a5316e3f1797a0f4f294b3cb768173deeaf81c/.github/workflows/runtime-sync.yml#L24 has an update for v3 https://github.com/actions/checkout/releases/tag/v3.0.0 which the dependabot would have notified.

Thoughts?

**Comment by dougbu** [comment]
Discussed this a bit with others and was swayed by your argument that we _could_ have missed security fixes and _did_ miss general improvements.

**Review by dougbu — APPROVED** [review]

**Comment by naveensrinivasan** [comment]
> Discussed this a bit with others and was swayed by your argument that we _could_ have missed security fixes and _did_ miss general improvements.

👍

**Pull request merged**
