### PR TITLE
Move SegmentWriteStream to shared resource

### LINKED ISSUE #45957: Duplicate SegmentWriteStream
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Copies exist in:

* OutputCaching - https://github.com/dotnet/aspnetcore/blob/cefc6ccf4b23ac9f07418cd10e374cf533276eee/src/Middleware/OutputCaching/src/Streams/SegmentWriteStream.cs
* ResponseCaching - https://github.com/dotnet/aspnetcore/blob/cefc6ccf4b23ac9f07418cd10e374cf533276eee/src/Middleware/ResponseCaching/src/Streams/SegmentWriteStream.cs

### Expected Behavior

One copy, in shared source.

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Skaanning**
# Move SegmentWriteStream to shared resource

## Description

Moved SegmentWriteStream.cs from the projects `ResponseCaching`  and `OutputCaching` to the shared folder.

Moved SegmentWriteStream namespace from  `Microsoft.AspNetCore.ResponseCaching` and `Microsoft.AspNetCore.OutputCaching`  to `Microsoft.AspNetCore.WriteStream`

Fixes #45957

### CODE REVIEW

**Review by adityamandaleeka — APPROVED** [review]

**Comment by adityamandaleeka** [comment]
Thanks @Skaanning!

**Comment by adityamandaleeka** [comment]
This looks good to me. Will do a sanity check to make sure the moved tests are still running.

cc: @sebastienros

**Review by sebastienros — APPROVED** [review]

**Comment by sebastienros** [comment]
@Skaanning I didn't realize the PR was done by an external contributor, and hence you couldn't merge it once I approved it.

**Comment by adityamandaleeka** [comment]
Thanks @Skaanning!

**Pull request merged**
