### PR TITLE
Change ASP.NET 5 to ASP.NET Core in readme

### PR DESCRIPTION
**Pull request by fekberg**
Rename all instances of ASP.NET 5 to ASP.NET Core in the readme,

### CODE REVIEW

**Comment by Rovastar** [comment]
Isn't it .NET Core 1.0 and not ASP.NET Core 1.0

**Comment by Eilon** [comment]
We will be doing the readme updates in bulk in the near future, but thank you for the PR.

**Comment by fekberg** [comment]
@Rovastar No, it's now ASP.NET Core 1.0, see here: http://www.hanselman.com/blog/ASPNET5IsDeadIntroducingASPNETCore10AndNETCore10.aspx

**Comment by Eilon** [comment]
And on this site it's neither, it'll just say ASP.NET Core :smile:

**Pull request closed without merging**
