### PR TITLE
Fix alpine queue used for Helix

### PR DESCRIPTION
**Pull request by wtgodbe**
Use a queue w/ python installed

Test helix-matrix build: https://dev.azure.com/dnceng/public/_build/results?buildId=1384007&view=results

### CODE REVIEW

**Review by dougbu — APPROVED** [review]

**Comment by wtgodbe** [comment]
Got a flaky-looking template test failure on the new queue, but looks like it works at least mostly as-expected

**Comment by BrennanConroy** [comment]
> /root/helix/work/workitem/e/.nuget/playwrightsharp/0.192.0/build/netstandard2.0/PlaywrightSharp.targets(18,5): error MSB3073: The command "./playwright.sh install" exited with code 127. 

That might be consistent not flaky, failed on 2 (both?) components test dlls that use playwright

**Comment by wtgodbe** [comment]
Let's see, re-running: https://dev.azure.com/dnceng/public/_build/results?buildId=1384007&view=results

**Comment by BrennanConroy** [comment]
Looks consistent

**Comment by wtgodbe** [comment]
Yep, I'll put up a new PR to go back to 312 & mention this in the helix-matrix issue

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/pull/36951

**Pull request merged**
