### PR TITLE
Rebrand and update for 5.0.1

### PR DESCRIPTION
**Pull request by dougbu**
- [master] Update dependencies from dotnet/runtime dotnet/efcore (#26788)
    - 219ecd688012
- when project template tests run test assets, need latest shared Fx bits
- hit `BadImageFormatException`s otherwise
    - test projects build against uploaded packages
    - those packages reference the 5.0.1 shared framework
    - the ASP.NET parts of the 5.0.1 shared Fx are `crossgen`ed to target Windows

- Use runtime and ref/ assemblies matching repo in Helix testing
    - add Directory.Build.*.in files based on project template test infrastructure
    - use files as import boundary where the project doesn't create its own Directory.Build.* files
    - ensure `dotnet-watch` tests also use the latest runtime and ref/ assemblies

- Extend Helix Directory.Build.* workarounds
    - generate Directory.Build.* files when restoring any projects
    - include generated files in Helix runs needing the latest runtime
    - copy generated files when testing `dotnet-watch` locally
    - include generated content in Microsoft.NET.Sdk.BlazorWebAssembly.IntegrationTests test assets
        - remove duplicate settings from existing Directory.Build.* files
    - ensure shared framework and targeting packs are laid out under .dotnet/ before test assets restore

- Disable `crossgen` when building for Helix runs
    - make `$(CrossgenOutput)` property override-able
    - use override in CI jobs that submit to other platforms
        - for now, leave the ARM64 Helix jobs alone (build on Ubuntu, run in Debian)

### CODE REVIEW

**Comment by dougbu** [comment]
We'll need this general improvement in the veracity of template tests when rebranding for 5.0.1. If others prefer, could take more of this from master e.g. turn off `$(CrossgenOutput)` in other pipelines or use the Directory.Build.*.in files in the Blazor SDK and `dotnet-watch` tests.

**Review by wtgodbe — APPROVED** [review]

**Comment by dougbu** [comment]
This is blocked for now. Right @wtgodbe❔

**Comment by wtgodbe** [comment]
That's correct, 5.0.1 servicing will open up later this month

**Comment by dougbu** [comment]
This branch now includes everything that should be needed to get 5.0.1 builds going. I suspect it won't validate until the 5.0.100 SDK is usable in `dotnet-install.*` scripts. @dotnet/aspnet-build please review again since @wtgodbe only looked at one of the 6 commits here.

**Review by wtgodbe — APPROVED** [review]

**Pull request merged**
