### PR TITLE
Keep building packages that are marked packable

### PR DESCRIPTION
**Pull request by BrennanConroy**
The packages below stopped being in the shipping/non-shipping folder after https://github.com/dotnet/aspnetcore/pull/22362 which was an unintended side-effect:
* Microsoft.AspNetCore.SignalR.Specification.Tests
* signalr-x.y.z.jar
* Microsoft.AspNetCore.Server.IntegrationTesting
* Microsoft.AspNetCore.Server.IntegrationTesting.IIS

### CODE REVIEW

**Review by dougbu — COMMENTED** [review]
I get most of this but why does signalr.client.java.Tests.javaproj need to be built when not building tests?

**Comment by BrennanConroy** [comment]
> signalr.client.java.Tests.javaproj need to be built when not building tests

An unfortunate side-effect of how testing works. In order to make java tests run on Helix we just do the whole java build. So this file is used for testing and building. We could make two project files, but they would be 90% duplicated logic.

**Comment by dougbu** [comment]
> In order to make java tests run on Helix we just do the whole java build.

I'm still missing something. $(SkipTestBuild)` isn't set except in non-test and non-Helix builds.

**Comment by BrennanConroy** [comment]
signalr.client.java.Tests.javaproj is also the project that builds the jar that we ship

**Review by dougbu — APPROVED** [review]
Thanks for your patience and complete explanation❕

**Review by wtgodbe — APPROVED** [review]

**Pull request merged**
