### PR TITLE
Add additional constructor to HealthReport

### PR DESCRIPTION
**Pull request by Serg046**
I need to override HealthStatus calculation logic. I planed to replace HealthCheckService and put desired logic there. However, the appropriate method returns HealthReport with built-in logic which cannot be replaced. This PR adds possibility to put custom logic.

### CODE REVIEW

**Review by rezabazargan — APPROVED** [review]

**Comment by Serg046** [comment]
Just wanted to ask if you had a chance to take a look on this. Can I do anything elsel on my side to increase chances of the PR? Now we are forced to recalculate the status each time when we use HealthCheckService. But of course, I can imagine that ASP.NET team treats the existing calculation logic as the only possible and doesn't want to expose a code seam.

**Comment by pranavkm** [comment]
@Serg046 we discussed in our API review today and it wasn't clear what your application's use case is to have a different implementation for how the aggregate is calculated. Could you elaborate?

**Comment by Serg046** [comment]
We have an application which works with different servers using some protocol X. End users are interested in working with the only server at the same time. Usually the user doesn’t even have an access to several servers. So some users work with server1, other users work with server2, etc.

On the app side we have a health check to monitor the state of each server. The server server1 might be Healthy, server2 - Unhealthy and server3 - Degraded. It is absolutely okay because we don’t control the servers because they are external third party resources. Some of them are actually just demo servers so that they are often down. We also have an application-wide check to monitor the app itself. There we check the things which are not related to the servers directly, e.g. databases on our side. But we also include the servers to that app-wide check so that if all the servers are Unhealthy, then the app is Unhealthy too because we don’t expect such situation and most probably something is wrong on the app side. Anyway, even if everything is fine with the service itself we still want a notification that nobody is able to use the service. But the thing is that the default logic results Unhealthy when at least one check (e.g. server2) is Unhealthy.

Eventually, we use a workaround which work normal enough. I don’t think that our specific case is enough reason to change the framework behavior. I just found that kind of flexibility useful for the community. I can imagine some other calculation logic in other apps. That’s why I created the PR.

**Comment by pranavkm** [comment]
Thanks @Serg046 for your PR. I updated your PR to resolve some merge conflicts and pushed it to https://github.com/dotnet/aspnetcore/pull/24597. We'll use the linked PR to get your changes in.

**Pull request closed without merging**
