### PR TITLE
Pin remaining extensions dependencies

### PR DESCRIPTION
**Pull request by JunTaoLuo**
Work item: #19254 

There are three remaining dependencies on extensions:
Microsoft.AspNetCore.Analyzer.Testing
Internal.AspNetCore.Analyzers
Microsoft.Extensions.DiagnosticAdapter

Since we plan to deprecate these or switch to other implementations in the future.

I've migrated the analyzers but I'll pin DiagnosticAdapter until @rynowak investigates and get back to me.

### CODE REVIEW

**Comment by dougbu** [comment]
I worry this is a short-term plan for something that could easily take a while. If for example Internal.AspNetCore.Analyzers needs to be changed before we get around to removing it from our build system, pinning means we have extra manual steps to take to pick up the fix. Why not move these sources and do everything (including deprecation and eventual removal) in one place?

**Comment by JunTaoLuo** [comment]
Ready for another look @dotnet/aspnet-build

**Review by dougbu — APPROVED** [review]

**Comment by JunTaoLuo** [comment]
@rynowak @pranavkm I can't seem to figure out why the Mvc.Api.Analyzers.Test are failing. The change I made is that the package reference to Microsoft.AspNetCore.Analyzer.Testing was changed from a package reference to a project reference but I don't see how that would cause types to be missing. Care to help me take a look?

**Comment by davidfowl** [comment]
```
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.1 (64-bit .NET Core 5.0.0-preview.4.20201.1)
[xUnit.net 00:00:01.08]   Discovering: Mvc.Api.Analyzers.Test (method display = ClassAndMethod, method display options = None)
[xUnit.net 00:00:01.31]   Discovered:  Mvc.Api.Analyzers.Test (found 187 test cases)
[xUnit.net 00:00:01.32]   Starting:    Mvc.Api.Analyzers.Test (parallel test collections = on, max threads = 2)
[xUnit.net 00:00:02.53]       System.IndexOutOfRangeException : Index was outside the bounds of the array.
[xUnit.net 00:00:02.53]     Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiConventionMatcherTest.IsMatch_WithEmpty_MatchesMethodWithNoParameters [FAIL]
[xUnit.net 00:00:02.54]       Stack Trace:
[xUnit.net 00:00:02.55]            at System.Collections.Immutable.ImmutableArray`1.get_Item(Int32 index)
[xUnit.net 00:00:02.55]         /_/src/Mvc/Mvc.Api.Analyzers/src/ApiControllerSymbolCache.cs(99,0): at Microsoft.AspNetCore.Mvc.Api.Analyzers.ApiControllerSymbolCache.TryCreate(Compilation compilation, ApiControllerSymbolCache& symbolCache)
[xUnit.net 00:00:02.55]         /_/src/Mvc/Mvc.Api.Analyzers/test/SymbolApiConventionMatcherTest.cs(434,0): at Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiConventionMatcherTest.RunMatchTest(String methodName, String conventionMethodName, Boolean expected)
[xUnit.net 00:00:02.55]         --- End of stack trace from previous location ---
[xUnit.net 00:00:02.76]       System.IndexOutOfRangeException : Index was outside the bounds of the array.
[xUnit.net 00:00:02.76]       Stack Trace:
[xUnit.net 00:00:02.76]            at System.Collections.Immutable.ImmutableArray`1.get_Item(Int32 index)
[xUnit.net 00:00:02.76]         /_/src/Mvc/Mvc.Api.Analyzers/src/ApiControllerSymbolCache.cs(99,0): at Microsoft.AspNetCore.Mvc.Api.Analyzers.ApiControllerSymbolCache.TryCreate(Compilation compilation, ApiControllerSymbolCache& symbolCache)
[xUnit.net 00:00:02.76]         /_/src/Mvc/Mvc.Api.Analyzers/test/SymbolApiConventionMatcherTest.cs(434,0): at Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiConventionMatcherTest.RunMatchTest(String methodName, String conventionMethodName, Boolean expected)
[xUnit.net 00:00:02.76]     Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiConventionMatcherTest.IsMatch_ReturnsFalse_IfMethodNamesDoNotMatch [FAIL]
[xUnit.net 00:00:02.76]         --- End of stack trace from previous location ---
  √ Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiConventionMatcherTest.IsNameMatch_WithSuffix_ReturnFalse_IfNameIsNotProperSuffix(name: "candid", conventionName: "id") [2ms]
  √ Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiConventionMatcherTest.IsNameMatch_WithSuffix_ReturnFalse_IfNameIsNotProperSuffix(name: "canDid", conventionName: "id") [< 1ms]
  √ Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiConventionMatcherTest.IsNameMatch_WithExact_ReturnsFalse_IfNamesDifferInCase [< 1ms]
  X Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiConventionMatcherTest.IsMatch_WithEmpty_MatchesMethodWithNoParameters [1s 1ms]
  Error Message:
   System.IndexOutOfRangeException : Index was outside the bounds of the array.
  Stack Trace:
     at System.Collections.Immutable.ImmutableArray`1.get_Item(Int32 index)
   at Microsoft.AspNetCore.Mvc.Api.Analyzers.ApiControllerSymbolCache.TryCreate(Compilation compilation, ApiControllerSymbolCache& symbolCache) in /_/src/Mvc/Mvc.Api.Analyzers/src/ApiControllerSymbolCache.cs:line 99
   at Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiConventionMatcherTest.RunMatchTest(String methodName, String conventionMethodName, Boolean expected) in /_/src/Mvc/Mvc.Api.Analyzers/test/SymbolApiConventionMatcherTest.cs:line 434
--- End of stack trace from previous location ---
  √ Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiConventionMatcherTest.IsNameMatch_WithPrefix_ReturnsFalse_IfNameIsNotProperPrefix [< 1ms]
  X Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiConventionMatcherTest.IsMatch_ReturnsFalse_IfMethodNamesDoNotMatch [223ms]
  Error Message:
   System.IndexOutOfRangeException : Index was outside the bounds of the array.
  Stack Trace:
     at System.Collections.Immutable.ImmutableArray`1.get_Item(Int32 index)
   at Microsoft.AspNetCore.Mvc.Api.Analyzers.ApiControllerSymbolCache.TryCreate(Compilation compilation, ApiControllerSymbolCache& symbolCache) in /_/src/Mvc/Mvc.Api.Analyzers/src/ApiControllerSymbolCache.cs:line 99
   at Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiConventionMatcherTest.RunMatchTest(String methodName, String conventionMethodName, Boolean expected) in /_/src/Mvc/Mvc.Api.Analyzers/test/SymbolApiConventionMatcherTest.cs:line 434
--- End of stack trace from previous location ---
  √ Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiConventionMatcherTest.IsNameMatch_WithPrefix_ReturnsTrue_IfNamesAreExact [< 1ms]
  √ Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiConventionMatcherTest.IsNameMatch_WithExact_ReturnsTrue_IfExactMatch [< 1ms]
  √ Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiConventionMatcherTest.IsNameMatch_WithSuffix_ReturnsFalse_IfNamesAreDifferent [9ms]
[xUnit.net 00:00:03.10]     Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiResponseMetadataProviderTest.GetStatusCode_ReturnsValueFromConstructor [FAIL]
[xUnit.net 00:00:03.10]       Assert.Equal() Failure
[xUnit.net 00:00:03.10]       Expected: 201
[xUnit.net 00:00:03.10]       Actual:   200
[xUnit.net 00:00:03.10]       Stack Trace:
[xUnit.net 00:00:03.10]         /_/src/Mvc/Mvc.Api.Analyzers/test/SymbolApiResponseMetadataProviderTest.cs(401,0): at Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiResponseMetadataProviderTest.GetStatusCodeTest(String actionName, Int32 expected)
[xUnit.net 00:00:03.10]         --- End of stack trace from previous location ---
[xUnit.net 00:00:03.24]     Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiResponseMetadataProviderTest.GetDeclaredResponseMetadata_ApiConventionTypeAttributeOnBaseType_Works [FAIL]
[xUnit.net 00:00:03.24]       System.IndexOutOfRangeException : Index was outside the bounds of the array.
[xUnit.net 00:00:03.24]       Stack Trace:
[xUnit.net 00:00:03.24]            at System.Collections.Immutable.ImmutableArray`1.get_Item(Int32 index)
[xUnit.net 00:00:03.24]         /_/src/Mvc/Mvc.Api.Analyzers/src/ApiControllerSymbolCache.cs(99,0): at Microsoft.AspNetCore.Mvc.Api.Analyzers.ApiControllerSymbolCache.TryCreate(Compilation compilation, ApiControllerSymbolCache& symbolCache)
[xUnit.net 00:00:03.24]         /_/src/Mvc/Mvc.Api.Analyzers/test/SymbolApiResponseMetadataProviderTest.cs(323,0): at Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiResponseMetadataProviderTest.GetDeclaredResponseMetadata_ApiConventionTypeAttributeOnBaseType_Works()
[xUnit.net 00:00:03.24]         --- End of stack trace from previous location ---
  √ Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiConventionMatcherTest.IsNameMatch_WithSuffix_ReturnTrue_IfNameIsExact [< 1ms]
  √ Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiConventionMatcherTest.IsTypeMatch_WithAssignableFrom_ReturnsFalseForUnrelated [136ms]
  √ Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiConventionMatcherTest.IsTypeMatch_WithAny_ReturnsTrue(type: typeof(int), conventionType: typeof(System.Void)) [83ms]
  X Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiResponseMetadataProviderTest.GetStatusCode_ReturnsValueFromConstructor [1s 632ms]
  Error Message:
   Assert.Equal() Failure
Expected: 201
Actual:   200
  Stack Trace:
     at Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiResponseMetadataProviderTest.GetStatusCodeTest(String actionName, Int32 expected) in /_/src/Mvc/Mvc.Api.Analyzers/test/SymbolApiResponseMetadataProviderTest.cs:line 401
--- End of stack trace from previous location ---
  √ Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiConventionMatcherTest.IsTypeMatch_WithAny_ReturnsTrue(type: typeof(string), conventionType: typeof(System.DateTime)) [143ms]
  √ Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiConventionMatcherTest.IsTypeMatch_WithAny_ReturnsTrue(type: typeof(object), conventionType: typeof(object)) [68ms]
  X Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiResponseMetadataProviderTest.GetDeclaredResponseMetadata_ApiConventionTypeAttributeOnBaseType_Works [114ms]
  Error Message:
   System.IndexOutOfRangeException : Index was outside the bounds of the array.
  Stack Trace:
     at System.Collections.Immutable.ImmutableArray`1.get_Item(Int32 index)
   at Microsoft.AspNetCore.Mvc.Api.Analyzers.ApiControllerSymbolCache.TryCreate(Compilation compilation, ApiControllerSymbolCache& symbolCache) in /_/src/Mvc/Mvc.Api.Analyzers/src/ApiControllerSymbolCache.cs:line 99
   at Microsoft.AspNetCore.Mvc.Api.Analyzers.SymbolApiResponseMetadataProviderTest.GetDeclaredResponseMetadata_ApiConventionTypeAttributeOnBaseType_Works() in /_/src/Mvc/Mvc.Api.Analyzers/test/SymbolApiResponseMetadataProviderTest.cs:line 323
--- End of stack trace from previous location ---
```

**Comment by JunTaoLuo** [comment]
Turns out the analyzer was setting PreserveCompilationContext in a build/props file which is no longer imported after changing it to a project dependency.

**Pull request merged**
