### PR TITLE
[release/8.0] Update Swashbuckle.AspNetCore to 6.6.2

### PR DESCRIPTION
**Pull request by martincostello**
## Description

Update Swashbuckle.AspNetCore in .NET 8 templates to a version that has built-in support for .NET 8 so users creating applications from the template get a better experience when creating new applications targeting .NET 8.

## Customer Impact

Development on the Swashbuckle.AspNetCore repo has restarted after a haitus and Swashbuckle.AspNetCore 6.6.2 is the first release following this hiatus. The most impactful change here is that this release updates Swashbuckle to target the net8.0 TFM and fixes some long-standing bugs in the library.

## Regression?

- [ ] Yes
- [X] No

## Risk

- [ ] High
- [ ] Medium
- [X] Low

6.6.2 has already been independently consumed by developers in their own APIs. This change updates the templates to in .NET 8 to use this version.

## Verification

- [X] Manual (required)
- [X] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [X] N/A

### CODE REVIEW

**Comment by captainsafia** [comment]
@martincostello Thanks for opening this PR!

It looks like there is one "breaking" change here that affects the Grpc + Swagger integration (cc: @JamesNK). It seems that the descriptions that Swashbuckle produces for status codes might've changed? If that was intentional, I think we can update the tests and be fine.

**Comment by martincostello** [comment]
If it's the change I'm thinking of, we made some changes in https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2872 to align better with the RFC and add some missing entries.

If that fits with what's failing I can update the PR tomorrow to account for that.

**Comment by captainsafia** [comment]
> If it's the change I'm thinking of, we made some changes in [domaindrivendev/Swashbuckle.AspNetCore#2872](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2872) to align better with the RFC and add some missing entries.
> 
> If that fits with what's failing I can update the PR tomorrow to account for that.

Yep, that appears to be what's happening in `Microsoft.AspNetCore.Grpc.Swagger.Tests`. You should be able to repro this failure locally as well.

**Comment by martincostello** [comment]
@captainsafia Fixed the test - the e2e component test failures seem unrelated and are affecting other PRs.

**Comment by captainsafia** [comment]
@martincostello Thanks! And yes -- we're not blocking merging PRs to release/8.0 on the buggy components-e2e tests. I'll hold this PR until the 8.0 branch is open for merging.

**Comment by wtgodbe** [comment]
@captainsafia is this good to go?

**Comment by captainsafia** [comment]
@wtgodbe Is release/8.0 open for servicing? I'll need to email tactics for approval on this one.

**Comment by wtgodbe** [comment]
> Is release/8.0 open for servicing? I'll need to email tactics for approval on this one.

Yep!

**Comment by cremor** [comment]
> I'll need to email tactics for approval on this one.

Any news on that @captainsafia?

**Comment by captainsafia** [comment]
@cremor Argh -- dropped the ball on this. I'll try to get this in for the next servicing release.

**Review by wtgodbe — APPROVED** [review]

**Pull request merged**
