### PR TITLE
update arcade version To fix the publishing

### PR DESCRIPTION
**Pull request by Anipik**
Updates the arcade version

### CODE REVIEW

**Review by wtgodbe — CHANGES_REQUESTED** [review]
There are other versions that should get updated as well: https://github.com/dotnet/aspnetcore/blob/master/eng/Version.Details.xml#L308-L314

I recommend just doing this with Darc

**Comment by safern** [comment]
Helix SDK is not necessary needed to be updated for the purpose of unblocking publishing.

**Comment by Anipik** [comment]
> We still want to keep the version files in line w/ whatever's in global.json. What exactly is blocking publishing?

Some of the packages are not getting uploaded, mattg made to change to add retries to publishing.

**Comment by wtgodbe** [comment]
Just need to fix the Arcade SDK version in version.details.xml to unblock code check, and this should be good to go

**Review by wtgodbe — APPROVED** [review]

**Comment by dougbu** [comment]
@Anipik in the future please use `darc` for all updates to automatically-maintained versions in this repo. It _probably_ won't hurt that you updated the Arcade SDK but not the Helix SDK. But, I worry about out-of-date eng/common/ content. See at least one eng/common/ file changed in this update (https://github.com/dotnet/arcade/compare/ff5d4b6c8dbdaeacb6e6159d3f8185118dffd915...f6192d1e284a08ac05041d05fa6e60dec74b24f5#diff-ee3a7f0d86bfe417f1acbec7d1c0082a).

@wtgodbe I suggest triggering the Arcade sub at least for our 'master' branch (before merging this forward if possible).

**Comment by Anipik** [comment]
I didn't use darc here as it will update all the dependencies which can introduce failures late in the build cycle.
eg The latest CompilerToolSet package broke the runtime repo and we have to pin to a previous version
Happy to use it in future if we want to go that route :)

**Comment by dougbu** [comment]
@Anipik `darc` will _not_ "update all the dependencies" unless you run `darc update-dependencies` without additional parameters. I tend toward commands like `darc trigger-subscriptions --source-repo arcade --target-repo aspnetcore --regex --target-branch preview8` because that often avoids me needing to own the PR.

**Comment by Anipik** [comment]
I might be wrong here but i think darc will update all the dependencies from the source repo to the target repo.
```darc trigger-subscriptions --source-repo arcade --target-repo aspnetcore$ --regex --target-branch preview8```
The command will update all the packages and sdks(provided by the arcade) to the latest version in the aspnetcore repo

**Comment by dougbu** [comment]
Yes, that's what we want in every case. It's not a big deal that this PR didn't update the Helix SDK too but the eng/common/ exclusion would have been a problem if we used `cmake`.

**Pull request merged**
