### PR TITLE
Update branding to 2.2.3

### PR DESCRIPTION
**Pull request by dougbu**
- new version
- update baselines
- grab latest released Microsoft.NetCore.App and Microsoft.NETCore.DotNetAppHost

nit:
- updated ZipManifestGenerator's README.md to use 2.2 examples

### CODE REVIEW

**Comment by dougbu** [comment]
@natemcmaster the following errors look really weird to me. What is causing the build to think Microsoft.AspNetCore.AzureAppServices.HostingStartup is being released? Or, if this is just about the references within the repo, why hasn't Microsoft.AspNetCore.AzureAppServices.HostingStartup built before the checks below?
```
F:\vsagent\36\s\.w\se\rs.csproj : error NU1603: rs depends on Microsoft.AspNetCore.AzureAppServices.HostingStartup (>= 2.2.3-servicing-20190212.2) but Microsoft.AspNetCore.AzureAppServices.HostingStartup 2.2.3-servicing-20190212.2 was not found. An approximate best match of Microsoft.AspNetCore.AzureAppServices.HostingStartup 3.0.0-alpha1-10008 was resolved.
F:\vsagent\36\s\.w\se\rs.csproj : error NU1107: Version conflict detected for Microsoft.AspNetCore.Hosting. Install/reference Microsoft.AspNetCore.Hosting 3.0.0-alpha1-10008 directly to project rs to resolve this issue. 
F:\vsagent\36\s\.w\se\rs.csproj : error NU1107:  rs -> Microsoft.AspNetCore.AzureAppServices.HostingStartup 3.0.0-alpha1-10008 -> Microsoft.AspNetCore.AzureAppServicesIntegration 3.0.0-alpha1-10008 -> Microsoft.AspNetCore.Hosting (>= 3.0.0-alpha1-10008) 
F:\vsagent\36\s\.w\se\rs.csproj : error NU1107:  rs -> Microsoft.AspNetCore.App 2.2.3-servicing-20190212.2 -> Microsoft.AspNetCore.Hosting (>= 2.2.0 && < 2.3.0).
```

**Comment by natemcmaster** [comment]
This error looks like a problem with the site extension. I haven't seen this before. @pakrym any ideas?

https://github.com/aspnet/AspNetCore/blob/release/2.2/src/SiteExtensions/LoggingBranch/LoggingBranch.csproj

**Comment by pakrym** [comment]
Looking into it.

**Comment by dougbu** [comment]
Looks as if the required tests are now passing. Thanks @pakrym!

Now, if someone could review this 😈

**Review by natemcmaster — APPROVED** [review]

**Pull request merged**
