### PR TITLE
Backport Use CDN for .NET Assets to release 6.0

### PR DESCRIPTION
**Pull request by TanayParikh**
https://github.com/dotnet/aspnetcore/pull/39007

### CODE REVIEW

**Review by dougbu — APPROVED** [review]

**Comment by TanayParikh** [comment]
@MattGal based on your [comment](https://github.com/dotnet/aspnetcore/pull/39046#issuecomment-994967820), I believe 6.0 should be working here?

**Comment by dougbu** [comment]
To confirm: There's no CDN for the 6.0 bits❔

**Comment by MattGal** [comment]
> To confirm: There's no CDN for the 6.0 bits❔

There are two storage accounts, dotnetcli and dotnetbuilds.  Both have CDNs, but the container structure is different and this may be the source of confusion.  I may have been incorrect about the inflection point because I saw 6.0* blobs on the dotnetbuilds account, but in general if you are going to use them at scale the CDN is the right choice.

**Comment by TanayParikh** [comment]
@dotnet/aspnet-build requesting merge please.

**Pull request merged**
