### PR TITLE
[SignalR] Only minify .min.js files

### LINKED ISSUE #39829: Review NPM distribution files
After installing of SignalR files from NPM (https://www.npmjs.com/package/@microsoft/signalr) or any other package manager (e.g. LibMan from Visual Studio) there are 2 files in `dist/browser` directory:

- signalr.js [41.1 KB]
- signalr.min.js [41.2 KB]

Both files are minified while `signalr.js` is expected to be readable. `signalr.min.js` is minified as expected, but it is even larger than unminifed file.

Not sure what type of issue it should be.

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes #39829

Our webpack configuration handles calling terser so there is no need for an extra build step that manually calls terser. Additionally, added multiple outputs to the webpack config so we can run minify on only the `.min.js` files.

We might want to consider backporting this to 6.0 since the non-minified file regressed in 6.0 to ship as minified.

### CODE REVIEW

**Review by halter73 — APPROVED** [review]
Is there good way to regression test this?

**Comment by halter73** [comment]
> We might want to consider backporting this to 6.0 since the non-minified file regressed in 6.0 to ship as minified.

I agree we should do this.

**Comment by BrennanConroy** [comment]
> Is there good way to regression test this?

I wrote a test for this, check it out.

**Pull request merged**
