### PR TITLE
Added ObjectPool to the solution so I could run in VS

### PR DESCRIPTION
**Pull request by davidfowl**
The solution didn't build now it does 😄

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]

**Comment by davidfowl** [comment]
What is the deal with this test: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerTest.ClearsResponseBuffer_BeforeRequestIsReexecuted

**Comment by Tratcher** [comment]
> What is the deal with this test: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerTest.ClearsResponseBuffer_BeforeRequestIsReexecuted

Quarantine:
https://github.com/dotnet/aspnetcore/pull/24147

I'm wondering if a dependency update broke it.

**Comment by Pilchie** [comment]
See https://github.com/dotnet/aspnetcore/issues/24146.

**Review by Pilchie — APPROVED** [review]

**Comment by davidfowl** [comment]
OK so it's a known issue, what do I do, wait for that PR to merge?

**Pull request merged**
