### PR TITLE
[release/7.0-preview6] Backport custom HTML elements rendering Blazor components

### LINKED ISSUE #38447: Productize the custom elements support package
Related feedback:

- [ ] https://github.com/dotnet/aspnetcore/issues/38369

### PR DESCRIPTION
**Pull request by MackinnonBuck**
# Custom HTML elements rendering Blazor components

This PR productizes the [custom elements support package](https://github.com/aspnet/AspLabs/tree/main/src/BlazorCustomElements). Backport of #42314

## Description

This package provides a simple mechanism for using Blazor components as custom elements. This means you can easily render Blazor components dynamically from other SPA frameworks, such as Angular or React.

Fixes #38447

## Customer Impact

This package brings value to the scenario where Blazor components are gradually introduced into existing projects written in other SPA frameworks. Rather than having to manually manage the state and lifecycle of Blazor root components using JavaScript APIs, it can now be done in a more intuitive fashion using custom HTML elements. By making this package official and built with the rest of the repository, customers can trust that it will be stable and up to date with the latest version of Blazor. 

## Regression?

- [ ] Yes
- [X] No

## Risk

- [ ] High
- [ ] Medium
- [X] Low

These changes do not touch the core framework. The new code remains almost unchanged from the existing support package, so it's unlikely we're introducing new bugs.

## Verification

- [X] Manual (required)
- [X] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [X] N/A

### CODE REVIEW

**Comment by dougbu** [comment]
@MackinnonBuck I can approve and merge this but need your confirmation that (other than whitespace) this change is identical to what was merged earlier today into 'main' (89426080e771). Please let me know. If there are a few differences, please point them out&helllip;

**Comment by MackinnonBuck** [comment]
@dougbu This change is identical to the one merged into main earlier today.

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
I didn't see anything suspicious in the CI failure and am rerunning failed jobs there. Enabled auto-merge here.

**Comment by dougbu** [comment]
@MackinnonBuck please merge #42459 into this. I didn't realize the two PRs were tightly bound.

/cc @mmitche

**Pull request merged**
