### PR TITLE
Revert runtime update due to build breakage

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
Since https://github.com/dotnet/aspnetcore/pull/44726 was merged, all official `main` builds have consistently failed with:

```
/mnt/vss/_work/1/s/.dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: The "RestoreTask" task failed unexpectedly. [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.22520.1/tools/Tools.proj]
##[error].dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) The "RestoreTask" task failed unexpectedly. [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj]
/mnt/vss/_work/1/s/.dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex. [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.22520.1/tools/Tools.proj]
##[error].dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex. [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj]
/mnt/vss/_work/1/s/.dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout) [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.22520.1/tools/Tools.proj]
##[error].dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout) [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj]
/mnt/vss/_work/1/s/.dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: at NuGet.Common.Migrations.MigrationRunner.Run() [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.22520.1/tools/Tools.proj]
##[error].dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) at NuGet.Common.Migrations.MigrationRunner.Run() [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj]
/mnt/vss/_work/1/s/.dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: at NuGet.Build.Tasks.RestoreTask.Execute() [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.22520.1/tools/Tools.proj]
##[error].dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) at NuGet.Build.Tasks.RestoreTask.Execute() [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj]
/mnt/vss/_work/1/s/.dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.22520.1/tools/Tools.proj]
##[error].dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj]
/mnt/vss/_work/1/s/.dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.22520.1/tools/Tools.proj]
##[error].dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj]
```

This might be related to https://github.com/dotnet/arcade/issues/10885, but whether or not it is, we need the builds to go back to passing without waiting for that to be fixed.

### CODE REVIEW

**Comment by MattGal** [comment]
@SteveSandersonMS , @brunolins16 was looking at this in [this teams thread](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1666715129747?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1666715129747&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1666715129747&allowXTenantAccess=false); the workaround seems to have helped? 
("The workaround is running dotnet nuget --info as the first NuGet command on the machine.")

**Comment by brunolins16** [comment]
> @SteveSandersonMS , @brunolins16 was looking at this in [this teams thread](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1666715129747?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1666715129747&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1666715129747&allowXTenantAccess=false); the workaround seems to have helped? ("The workaround is running dotnet nuget --info as the first NuGet command on the machine.")

I added the workaround for failing steps in the Linux build https://github.com/dotnet/aspnetcore/pull/44734 and it was showing no issues.

**Comment by brunolins16** [comment]
> Since #44726 was merged, all official `main` builds have consistently failed with:
> 
> ```
> /mnt/vss/_work/1/s/.dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: The "RestoreTask" task failed unexpectedly. [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.22520.1/tools/Tools.proj]
> ##[error].dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) The "RestoreTask" task failed unexpectedly. [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj]
> /mnt/vss/_work/1/s/.dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex. [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.22520.1/tools/Tools.proj]
> ##[error].dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex. [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj]
> /mnt/vss/_work/1/s/.dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout) [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.22520.1/tools/Tools.proj]
> ##[error].dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout) [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj]
> /mnt/vss/_work/1/s/.dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: at NuGet.Common.Migrations.MigrationRunner.Run() [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.22520.1/tools/Tools.proj]
> ##[error].dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) at NuGet.Common.Migrations.MigrationRunner.Run() [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj]
> /mnt/vss/_work/1/s/.dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: at NuGet.Build.Tasks.RestoreTask.Execute() [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.22520.1/tools/Tools.proj]
> ##[error].dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) at NuGet.Build.Tasks.RestoreTask.Execute() [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj]
> /mnt/vss/_work/1/s/.dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.22520.1/tools/Tools.proj]
> ##[error].dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj]
> /mnt/vss/_work/1/s/.dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.22520.1/tools/Tools.proj]
> ##[error].dotnet/sdk/8.0.100-alpha.1.22524.1/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/tmp/6566fc12-85fc-4228-abe0-bcf60ad2065d/restore.csproj]
> ```
> 
> This might be related to [dotnet/arcade#10885](https://github.com/dotnet/arcade/issues/10885), but whether or not it is, we need the builds to go back to passing without waiting for that to be fixed.

@SteveSandersonMS can you share the build link that causes this error because looking at the latest pipelines runs everything looks green.

**Comment by SteveSandersonMS** [comment]
@brunolins16 Public builds have been passing, but the internal official builds have been failing since that change: https://dev.azure.com/dnceng/internal/_build?definitionId=21

**Comment by brunolins16** [comment]
> @brunolins16 Public builds have been passing, but the internal official builds have been failing since that change: https://dev.azure.com/dnceng/internal/_build?definitionId=21

@SteveSandersonMS maybe it is related to the SDK update, since this build https://dev.azure.com/dnceng/internal/_build/results?buildId=2029740&view=results (that is the first failure) also includes my PR and the one before did not.

**Comment by brunolins16** [comment]
> > @brunolins16 Public builds have been passing, but the internal official builds have been failing since that change: https://dev.azure.com/dnceng/internal/_build?definitionId=21
> 
> @SteveSandersonMS maybe it is related to the SDK update, since this build https://dev.azure.com/dnceng/internal/_build/results?buildId=2029740&view=results (that is the first failure) also includes my PR and the one before did not.

Oh wait! My fix is working but what is failing is **Build: Linux ARM64** that did not have the **Build RPM installer** step in the public build and my workaround was not applied

**Comment by brunolins16** [comment]
@SteveSandersonMS I think this PR would help with this issue https://github.com/dotnet/aspnetcore/pull/44745

**Comment by brunolins16** [comment]
@SteveSandersonMS the latest internal build succeeded, after my changes https://dev.azure.com/dnceng/internal/_build/results?buildId=2030322&view=results

**Comment by SteveSandersonMS** [comment]
Excellent - thanks for persisting with this right to a successful conclusion, @brunolins16!

**Pull request closed without merging**
