### PR TITLE
[release/8.0] Use MacOS-13 in CI

### PR DESCRIPTION
**Pull request by wtgodbe**

### CODE REVIEW

**Review by BrennanConroy — APPROVED** [review]

**Comment by wtgodbe** [comment]
>   A JSON parsing exception occurred in [/__w/1/s/artifacts/source-build/self/src/global.json], offset 743 (line 31, column 1): Missing a comma or '}' after an object member.

@dotnet/source-build any idea why the global.json changes in this PR would cause a JSON parsing error, only in the source-build job? The JSON in global.json does appear to be valid, so not sure what's going on

**Comment by mthalman** [comment]
> > A JSON parsing exception occurred in [/__w/1/s/artifacts/source-build/self/src/global.json], offset 743 (line 31, column 1): Missing a comma or '}' after an object member.
> 
> @dotnet/source-build any idea why the global.json changes in this PR would cause a JSON parsing error, only in the source-build job? The JSON in global.json does appear to be valid, so not sure what's going on

I suspect it's because the trailing newline was removed from the end of the file. I added it back.

**Comment by wtgodbe** [comment]
> I suspect it's because the trailing newline was removed from the end of the file. I added it back.

Interesting, is that a known thing w/ how SourceBuild parses global.json? I'm curious why it only happened there

**Comment by mthalman** [comment]
> > I suspect it's because the trailing newline was removed from the end of the file. I added it back.
> 
> Interesting, is that a known thing w/ how SourceBuild parses global.json? I'm curious why it only happened there

Not specific to source build. It's a general Linux thing. Certain Linux tools do not play nicely with files formatted that way. That's why GitHub has UI that alerts you to a missing newline. So likely source build is executing something in the context of Linux that doesn't like this.

**Comment by wtgodbe** [comment]
Failures unrelated

**Pull request merged**
