### PR TITLE
Fixed the bug in the windows service host where if application stop is requested, the service wouldn't know about it.

### PR DESCRIPTION
**Pull request by zlatanov**
Fixes https://github.com/aspnet/AspNetCore/issues/5929.

The main issue was that the windows service host registered wait for **ApplicationStopped** event instead of **ApplicationStopping**. Also the registration for the event should be done after the host start procedure, because the application might request stop while starting.

I've added 2 tests that illustrate the problem. I needed to create **Start** method in the host which the tests could use, because the default start sequence of **ServiceBase** is tightly coupled to how Windows Service controller interacts with its services.

Both of the tests fail if built against master (with the addition of the Start method). With the suggested changes, they pass successfully.

### CODE REVIEW

**Comment by muratg** [comment]
@Tratcher could you please take a look?

**Review by Tratcher — CHANGES_REQUESTED** [review]

**Review by Tratcher — APPROVED** [review]

**Review by Tratcher — CHANGES_REQUESTED** [review]

**Comment by zlatanov** [comment]
@Tratcher Even though I've added the requested assembly level attributes for the tests, the AspNetCore-ci is still running them. Did I miss something?

**Comment by Tratcher** [comment]
Sorry, I missed part of the change. You also need to mark the tests as conditional.
https://github.com/aspnet/AspNetCore/blob/ea344bf726f73d9928c03b613386ee78cfe40650/src/Servers/HttpSys/test/FunctionalTests/RequestBodyTests.cs#L20

**Review by Tratcher — APPROVED** [review]

**Comment by Tum4ik** [comment]
Hi, will be it also fixed in ASP.Net Core 2.1?

**Comment by Tratcher** [comment]
No, this is not considered a high priority for patching.

**Comment by Tum4ik** [comment]
what is the minimum version which has this fix? 3.0?

**Comment by Tratcher** [comment]
3.0.0-preview2

**Pull request merged**
