### PR TITLE
Draft: Support null values in Results/TypedResults

### LINKED ISSUE #49107: Results / TypedResults ignore null values
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using Minimal APIs with nullable annotations enabled, it is possible to make a delegate that returns a null value for a nullable-annotated type, e.g.
```csharp
// Responds 200: "null"
app.MapGet("/nullable", T? () => null);
```

If the same value is instead wrapped in a `Results` or `TypedResults` container, the response body will be empty, e.g.
```csharp
// Responds 200: ""
app.MapGet("/iresult", IResults () => Results.Ok<T?>(null));
app.MapGet("/typed_result", Ok<T?> () => TypedResults.Ok<T?>(null));
```

This means changing an endpoint delegate to use these result wrappers causes a breakage in the API.

`T` can be both a value or reference type, the problem still occurs.

Current behavior is acceptable if the value type is not null annotated in a nullable context: A null value for a non-nullable type is a program bug, and the framework can return whatever, e.g.
```csharp
// Programmer error, unexpected nasal demons are acceptable
app.MapGet("/", T () => null!);
```

### Expected Behavior

Wrapping a return value in Results / TypedResults of the same status should return the exact same body as the value by itself.

### Steps To Reproduce

```csharp
using Microsoft.AspNetCore.Http.HttpResults;

var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();
app.MapGet("/nullable", Data? () => Data.NullInstance);
app.MapGet("/iresult", IResult () => Results.Ok<Data?>(Data.NullInstance));
app.MapGet("/typed_result", Ok<Data?> () => TypedResults.Ok<Data?>(Data.NullInstance));
await app.StartAsync();

var client = new HttpClient { BaseAddress = new Uri(app.Urls.First()), };
var endpoints = new[] { "/nullable", "/iresult", "/typed_result", };
foreach (var e in endpoints)
{
    // This will fail for (Typed)Results:
    // var q = await client.GetFromJsonAsync<Data?>(e);
    var r = await client.GetAsync(e);
    var s = r.StatusCode;
    var c = await r.Content.ReadAsStringAsync();
    Console.WriteLine($"{e} -> {s}: {c}");
}

await app.StopAsync();

public record Data
{
    public static Data? NullInstance => null;
}
```

### Exceptions (if any)

_No response_

### .NET Version

7.0.203

### Anything else?

```
.NET SDK:
 Version:   7.0.203
 Commit:    5b005c19f5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.203\

Host:
  Version:      8.0.0-preview.5.23280.8
  Architecture: x64
  Commit:       bc78804f5d

.NET SDKs installed:
  6.0.410 [C:\Program Files\dotnet\sdk]
  7.0.107 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.5.23303.2 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.5.23302.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.5.23280.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.5.23302.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  C:\Users\ThomasGravgaardHanse\RiderProjects\ProofOfConcept\global.json
```

### PR DESCRIPTION
**Pull request by Dryvnt**
# Support null values in Results/TypedResults

This pull request implements a vertical slice of support (i.e. only for `Ok`) for null values in `Results`/`TypedResults`. 

See #49107 for the motivation behind these changes.

I plan to implement support for all status classes before this PR can go out of draft, but I want to be sure I'm working in the right direction, hence opening this draft.

## Description

Using `null` as a sentinel for "no value" is softly baked into `Ok<TValue>` et al., but for every value-containing `Ok<TValue>` there is a value-less `Ok`. By making the value containers not ignore their null values, we semantically separate "there is no value" from "there is a value, and it is null": Use `Results.Ok()`/`TypedResults.Ok()` for the former, and `Results.Ok(null)`/`TypedResults.Ok(null)` for the latter.

`Ok<TValue>` et al. use the same helper to handle their values, so simply changing this helper to not ignore null values solves that part of the issue.

`TypedResults` has a nice hard delineation between value and no-value, but `Results` does not. As a user, I cannot create a null-valued `Results.Ok`, because the current implementation short-circuits both `Results.Ok()`, `Results.Ok(null)`, and `Results.Ok<T?>(null)` into returning the cached valueless `Ok`. This can easily be changed (as has been done in this PR), but this is a change to something that has been shipped in the public API. I would that kind of change like signed off before I continue.

I have tried to follow the test style I could see to the best of my ability. In summary:
- Two basic tests to ensure the `HttpResultsHelper` change works as expected
- A new test ensures that a response body for an `Ok`-wrapped value is the same as the value by itself
  - Naming, class placements, test organization, etc. is open for change.
  - I expect the test class to be filled with more equivalence tests for the different statuses as they get implemented.
- A handful of tests needed to have their expected values changed. The blast radius was surprisingly small.

Fixes #49107

### Side Note

`Ok<TValue>` et al. stores a `TValue?` property, and `Results.Ok<TValue>`/`TypedResults.Ok<TValue>` have a parameter of `TValue?`. If null is no longer used as an implicit sentinel value, could these instead be a plain `TValue`?

It would simplify the implementation of the `HttpResultsHelper` a bit, because `typeof(TValue?)` feels weird.

More importantly, it would allow the compiler to catch some user errors: Consider the handler `Ok<T> () => { T? t = null; return TypedResults.Ok(t); }` causing a type error rather than a bug hunt. This would improve my personal DevEx (I like being able to trust my types), and I imagine I'm not the only one creating a greenfield project using Minimal APIs with nullable types enabled.

I can see this being a separate change, and that's fine. I just wanted to mention it, since I'm bumping against it here.

### CODE REVIEW

**Comment by Dryvnt** [comment]
@dotnet-policy-service agree

**Comment by jded76** [comment]
Any news on this? 
We have the same problem trying to convert an owin web api to minimal api, and we are facing this behavior difference.

**Comment by Dryvnt** [comment]
Oh wow, how the time flies.

For the sake of communication, from my POV I am still waiting for some "yeah, we can accept changing the API this way, go ahead" approval (of course I realize that doesn't mean my changes are guaranteed to be accepted, just that there's at least a chance), and I guess I forgot about it entirely.

At this point in time I still want the issue fixed, and I am still happy to personally do that actual work, but I would prefer not getting the PR rejected out of hand after I spent a weekend or two on repetitive busywork. But at this point I might as well do it just to make something happen.

**Comment by Dryvnt** [comment]
Hit problem, can't proceed without higher decisions being made. See https://github.com/dotnet/aspnetcore/issues/49107#issuecomment-1910531939

**Pull request closed without merging**
