### PR TITLE
Produce log output for flakey test

### PR DESCRIPTION
**Pull request by NTaylorMullen**
- For the flakey test replaced the default logger with Xunit's `ITestOutputHelper` in order to see what's going wrong when the flakey test will eventually fail.

aspnet/AspNetCore-Internal#1337

### CODE REVIEW

**Comment by pakrym** [comment]
Why not use `LoggedTest` infrastructure? Inherit from LoggedTest and use `this.LoggerFactory`

https://github.com/aspnet/AspNetCore/blob/010c1f0c9f22fba3f6a0e82461fa7553e9114b44/src/Servers/Kestrel/test/InMemory.FunctionalTests/DefaultHeaderTests.cs#L12-L17

**Comment by davidfowl** [comment]
+1 I second that, use LoggedTest is much better to use here. I plan on adding functionality like being able to take a dump based on a condition as well so you'll want that eventually.

**Comment by NTaylorMullen** [comment]
Had no clue that existed. 👏 Will change.

**Comment by NTaylorMullen** [comment]
🆙 📅

**Review by pranavkm — APPROVED** [review]

**Pull request merged**
