### PR TITLE
Hide test infrastructure from the solution explorer

### PR DESCRIPTION
**Pull request by pranavkm**
## Before:

image

## After:

image

### CODE REVIEW

**Review by BrennanConroy — APPROVED** [review]
Oh nice! I was wondering why those items were appearing

**Comment by pranavkm** [comment]
I tried putting it in a subdir and it caused build failures. This is a lot easier.

**Comment by pranavkm** [comment]
FYI @HaoK

**Comment by dougbu** [comment]
Congratulations on grabbing #38000❕ 

🎂 🎂

**Pull request merged**
