### PR TITLE
[release/8.0] Add ForgotPasswordRequest to STJ source generation context

### PR DESCRIPTION
**Pull request by Kahbazi**
Manual backport of https://github.com/dotnet/aspnetcore/pull/52714

# Add ForgotPasswordRequest to STJ source generation context

Add `ForgotPasswordRequest` to `IdentityEndpointsJsonSerializerContext` for `ApiEndpoints`.

## Description

Fixes https://github.com/dotnet/aspnetcore/issues/52646

## Regression?

- [ ] Yes
- [x] No

## Risk

- [ ] High
- [ ] Medium
- [x] Low

## Verification

- [x] Manual (required)
- [ ] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

----
/cc @halter73 @amcasey

### CODE REVIEW

**Review by amcasey — APPROVED** [review]

**Comment by mkArtakMSFT** [comment]
Thanks for your PR, @Kahbazi.
@halter73 what do you think about considering this for servicing?

**Comment by amcasey** [comment]
Oops, evidently I jumped the gun.  This has already been approved over email, but I'll certainly defer to @halter73's guidance.

**Comment by halter73** [comment]
@mkArtakMSFT We should take it. It's a trivial bugfix which has already been approved by tactics. Thanks @amcasey

**Comment by halter73** [comment]
/azp run

@dotnet/aspnet-build Can someone merge this? @amcasey should be able to confirm this was approved December 14th. The email subject was "[release/8.0] Fix aspnetcore AOT bug".

**Comment by amcasey** [comment]
> @dotnet/aspnet-build Can someone merge this? @amcasey should be able to confirm this was approved December 14th. The email subject was "[release/8.0] Fix aspnetcore AOT bug".

Confirmed - tactics approved over email 12/14.

**Pull request merged**
