### PR TITLE
Skip some more flaky tests

### PR DESCRIPTION
**Pull request by analogrelay**
https://github.com/aspnet/AspNetCore-Internal/issues/1854

https://github.com/aspnet/AspNetCore/issues/8187

### CODE REVIEW

**Comment by anurse** [comment]
@ryanbrandenburg added you because it has templates in it. Feel free to let me know if it's not your jam ;)

**Review by Tratcher — APPROVED** [review]

**Comment by anurse** [comment]
Test discovery issues #8201

**Comment by anurse** [comment]
AspNetCore-ci has passed but GitHub isn't showing it... May need an override merge

**Comment by anurse** [comment]
The associated build has **passed**: https://dev.azure.com/dnceng/public/_build/results?buildId=113789 but GitHub failed to update.

I'm going to use my newfound admin powers for Awesome here and merge it.

**Pull request merged**
