### PR TITLE
SpaProxy: Fix proxying of WebSocket protocol

### PR DESCRIPTION
**Pull request by stephtr**
- Use `client.Options.AddSubProtocol` for setting the WebSocket protocol instead of `client.Options.SetRequestHeader`

Addresses #23207

### CODE REVIEW

**Comment by stephtr** [comment]
The build failures seem to be unrelated to this PR (connection issue & file access issue).

**Comment by Tratcher** [comment]
Were you able to test this locally?

**Comment by stephtr** [comment]
Yes, for my Snowpack project I'm already using the modified `SpaProxy`. I've also successfully tested it with `dotnet new react`.

**Review by Tratcher — APPROVED** [review]

**Comment by Tratcher** [comment]
Thanks

**Pull request merged**
