### PR TITLE
Use Request.Scheme instead of Protocol

### PR DESCRIPTION
**Pull request by shnja**
Correction to #6775 and #6819

### CODE REVIEW

**Comment by shnja** [comment]
cc @pranavkm

**Review by pranavkm — APPROVED** [review]

**Comment by pranavkm** [comment]
Thanks @shnja

**Comment by shnja** [comment]
You're welcome :smiley:

**Comment by khellang** [comment]
Hmm. Has this been released yet? I'm seeing `Location: HTTP/1.1://localhost:5001/` running on preview 3 🤔

**Comment by pranavkm** [comment]
@khellang the change is in preview4.

**Pull request merged**
