### PR TITLE
Revert "[blazor][wasm] unify startup bit more"

### PR DESCRIPTION
**Pull request by TanayParikh**
Reverts dotnet/aspnetcore#45628 as it's causing build issues in the repo:

image

cc/ @pavelsavara

### CODE REVIEW

**Comment by pavelsavara** [comment]
How did the CI passed on my PR ?

**Comment by TanayParikh** [comment]
> How did the CI passed on my PR ?

Looks like the CI passed a ~week back. There may've been changes in main since which could've led to this behavior.

**Comment by pavelsavara** [comment]
We will see it soon on main https://dev.azure.com/dnceng-public/public/_build/results?buildId=132213&view=results

**Comment by pavelsavara** [comment]
I think that deleting `src\Components\Web.JS\node_modules` locally may help as there could be stale `dotnet.d.ts` in there.

**Comment by TanayParikh** [comment]
Superseded by https://github.com/dotnet/aspnetcore/pull/45997

**Pull request closed without merging**
