### PR TITLE
[Ignore]Force failures for Java test reporting

### PR DESCRIPTION
**Pull request by mikaelm12**
For PR https://github.com/aspnet/AspNetCore/pull/9214

### CODE REVIEW

**Comment by mikaelm12** [comment]
This is what happens. Nothing gets queued on AzDo. 

DraftPR
cc @ryanbrandenburg

**Comment by mikaelm12** [comment]
Ignore this

**Comment by mikaelm12** [comment]
Forced 3 tests to fail and this is what the error report looks like
SignalRTestReport

**Comment by BrennanConroy** [comment]
Excellent! Thank you

**Pull request closed without merging**
