### PR TITLE
[release/5.0] Improve File access issues

### PR DESCRIPTION
**Pull request by wtgodbe**
Attempt to improve https://github.com/dotnet/aspnetcore/issues/32219 in 5.0 by backporting parts of https://github.com/dotnet/aspnetcore/pull/34137 and https://github.com/dotnet/aspnetcore/pull/39336. If this doesn't help enough we can backport https://github.com/dotnet/aspnetcore/pull/37338 as well, but that's more involved.

### CODE REVIEW

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
Should this be in `area-infrastructure`❔

**Comment by wtgodbe** [comment]
> Should this be in area-infrastructure❔

Yes

**Comment by wtgodbe** [comment]
@BrennanConroy do you know what project I excluded here to cause all the typescript tests to fail?

**Comment by BrennanConroy** [comment]
https://github.com/dotnet/aspnetcore/pull/39680 and https://github.com/dotnet/aspnetcore/pull/39690 are needed for 5.0

**Pull request merged**
