### PR TITLE
Log exception from HealthCheckResult

### PR DESCRIPTION
**Pull request by mjolka**
Log the exception from the HealthCheckResult with the HealthCheckEnd
event.

Addresses #21588

### CODE REVIEW

**Comment by wattcode** [comment]
Hi, what's the status on this?

**Comment by B3nCr** [comment]
Hi, sorry to intrude on this PR and feel free to tell me this isn't the right place to ask this question but I'm curious. The build has failed due to an out of memory exception. Is this because the build is deliberately constrained to catch bugs which consume too much memory or is it just a bad coincidence/dodgy build agent?

**Review by pranavkm — APPROVED** [review]
Thanks for the PR.

**Comment by pranavkm** [comment]
@mjolka looks like there are some build errors in your change:

> DefaultHealthCheckServiceTest.cs(550,41): error CS8600: (NETCORE_ENGINEERING_TELEMETRY=Build) Converting null literal or possible null value to non-nullable type.

Can you update your PR?

**Comment by pranavkm** [comment]
@mjolka feel free to reopen this PR once you're able to address the build errors.

**Pull request closed without merging**
