### PR TITLE
Mark -internal blobs as nonshipping

### PR DESCRIPTION
**Pull request by wtgodbe**
Test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1628516&view=results

Part of https://github.com/dotnet/aspnetcore/issues/40050

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
Hate it when `[System.String]::Copy(...)` is necessary but I suspect other options like adding `Exclude="$(ArtifactsDir)installers\**\*internal*.zip"` to all of the `<_InstallersToPublish />` or using `Remove="..."` later would be more complicated.

**Comment by wtgodbe** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=1630537&view=results

**Comment by wtgodbe** [comment]
This didn't work, the manifest still shows all `aspnetcore-runtime-internal` (and all `aspnetcore-runtime`) blobs as `NonShipping="false"`. I tested the msbuild code locally and it does what I expect - @dotnet/dnceng do I need to mark these as nonshipping in a different way?

**Comment by wtgodbe** [comment]
Looks like we might be relying on some old behavior of `ItemsToPushToBlobFeed` - we should probably be setting `ManifestArtifactData` like arcade does:

https://github.com/dotnet/arcade/blob/0713a4634fb6fc2d9422379a6138ae2998b6ca14/src/Microsoft.DotNet.Arcade.Sdk/tools/Publish.proj#L85-L87

Can/should we get rid of the other metadata we use like `PublishFlatContainer` and `RelativeBlobPath`?

**Comment by wtgodbe** [comment]
I think the answer to my above question is "no" based on how the blob tasks work in arcade. New build:

https://dev.azure.com/dnceng/internal/_build/results?buildId=1631124&view=results

**Comment by dougbu** [comment]
Overlapping @wtgodbe's question, @dotnet/dnceng has the `@(ItemsToPushToBlobFeed)` metadata gone through a breaking change lately❔

**Comment by mmitche** [comment]
> Overlapping @wtgodbe's question, @dotnet/dnceng has the `@(ItemsToPushToBlobFeed)` metadata gone through a breaking change lately❔

Nope, this hasn't changed in at least a couple years. You can see how SDK does this here: https://github.com/dotnet/sdk/blob/main/eng/Publishing.props#L67

**Comment by wtgodbe** [comment]
Forgot about checksums & version files - gonna mark all of those `Nonshipping` as well: https://dev.azure.com/dnceng/internal/_build/results?buildId=1632708&view=results

**Comment by wtgodbe** [comment]
Alright, all `-internal` archive/installers, all checksums, and all `.version`-type files are non `nonshipping`. @mmitche @dougbu sound good?

**Comment by dougbu** [comment]
Sounds good @wtgodbe

**Pull request merged**
