### PR TITLE
Update SignalR Java Client metadata

### PR DESCRIPTION
**Pull request by analogrelay**
The repo URLs were pointing at the old one :)

### CODE REVIEW

**Review by BrennanConroy — APPROVED** [review]

**Comment by anurse** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=205370

**Comment by BrennanConroy** [comment]
@dougbu Any reason the bot didn't comment here?

**Comment by anurse** [comment]
Verified output POM in CI build:

```xml
  <url>https://github.com/aspnet/AspNetCore</url>
  <inceptionYear>2018</inceptionYear>
  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <developers>
    <developer>
      <id>microsoft</id>
      <name>Microsoft</name>
    </developer>
  </developers>
  <scm>
    <connection>scm:git:git://github.com/aspnet/AspNetCore.git</connection>
    <developerConnection>scm:git:git://github.com/aspnet/AspNetCore.git</developerConnection>
    <url>http://github.com/aspnet/AspNetCore/tree/master</url>
  </scm>
```

**Comment by dougbu** [comment]
> Any reason the bot didn't comment here?

No idea. @aspnet/build ?

**Pull request merged**
