### PR TITLE
Add a rule to mention the `aspnet-build` team on infrastructure issues

### PR DESCRIPTION
**Pull request by mkArtakMSFT**
Also drop a comment on community contributions suggesting that someone will get assigned to the PR soon and get it reviewed.

**Note ⚠️**: Because we don't rely on FabricBot UI any more, I am using the `Internal: Debug` label to validate my new rule. After validation, I'll update this file one more time to remove the condition.

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
If it works after removing the `Internal: Debug` bit, looks good

**Comment by mkArtakMSFT** [comment]
> If it works after removing the `Internal: Debug` bit, looks good

I'll find that out after merging this. And then, when everything is ok, will remove the debug label.

**Comment by mkArtakMSFT** [comment]
I've validated the rule with the debug label in place and have already removed the condition. Here is the verification PR that I've used: https://github.com/dotnet/aspnetcore/pull/41954

This concludes the changes we've talked about for me to implement.

**Comment by wtgodbe** [comment]
Also are we going to update codeowners? I'm now getting about 10 emails on each PR I'm tagged on 😆

**Pull request merged**
