### PR TITLE
[3.0] Also target netstandard2.1 for Identity.EFCore

### PR DESCRIPTION
**Pull request by HaoK**
Description
Fix for https://github.com/aspnet/AspNetCore/issues/13340

The  user/role features of identity (UserManager/RoleManager) are intended to continue working outside of ASP.NET for 3.0. Unfortunately we missed updating the Identity.EntityFrameworkCore store implementation package to target netstandard 2.1 (required for EF), so its currently only targeting netcoreapp3.0 (the default for ASP.NET Core).  This change just enables this package to be target netstandard2.1.

Customer Impact
Customers are unable to use the default identity EF store implementation outside of netcoreapp3.0 which is also regression from 2.2

Regression?
Yes, in 2.2, this package targeted netstandard2.0

Risk
Low

### CODE REVIEW

**Comment by Pilchie** [comment]
@HaoK This is approved, but it looks like it's failing CI.  Can you take a look?  Or you @JunTaoLuo ?

**Comment by HaoK** [comment]
Looks like a flaky test again, I'll rerun that test, but doesn't look related at all as its a hosting shutdown test.

**Comment by HaoK** [comment]
Required checks in aspnetcore-ci look green now

**Comment by mmitche** [comment]
This was approved, merging.

**Pull request merged**
