### PR TITLE
[release/2.1] Remove MusicStore

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Comment by dougbu** [comment]
This isn't incredibly urgent. But, might be nice to get it into 2.1.28 if ProdCon hasn't reached this repo by the time the changes are approved and validated.

**Comment by dougbu** [comment]
/btw this is `tell-mode` because it only affects samples and tests.

**Comment by dougbu** [comment]
@wtgodbe Any chance we can get this, #31813 and / or #31818 into the current releases❔ PRs clean up some cruft and may speed builds and tests slightly.

**Comment by dougbu** [comment]
If yes, please help doing the merges as I'll be offline for a while&hellip;

**Comment by wtgodbe** [comment]
I think https://github.com/dotnet/aspnetcore/pull/31813 is the only one we have time for, if it's green before I log off I'll merge it

**Review by JunTaoLuo — APPROVED** [review]

**Pull request merged**
