### PR TITLE
Add a benchmark app for Blazor

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Review by javiercn — APPROVED** [review]

**Comment by SteveSandersonMS** [comment]
@pranavkm Sorry I missed this before, but this PR doesn't include the third-party notices for content in this app: https://github.com/dotnet-presentations/blazor-workshop/blob/master/THIRD-PARTY-NOTICES.md

Would you also be able to add the relevant notices from that file into a new `THIRD-PARTY-NOTICES.md` inside `src/Components/benchmarkapps/`?

**Comment by SteveSandersonMS** [comment]
Oh wait, you didn't include the image files (e.g., `meaty.jpg`). What's the idea with this - that they're not needed for benchmarking so we exclude them? It might be confusing that they still get referenced though.

**Comment by javiercn** [comment]
> Oh wait, you didn't include the image files (e.g., `meaty.jpg`). What's the idea with this - that they're not needed for benchmarking so we exclude them? It might be confusing that they still get referenced though.

We could add it though, wouldn't the app look bad if it doesn't have it when you F5?

**Comment by pranavkm** [comment]
> Oh wait, you didn't include the image files (e.g., meaty.jpg). What's the idea with this - that they're not needed for benchmarking so we exclude them? It might be confusing that they still get referenced though.

Ignitor cares about the content, not the assets. I wanted to avoid checking in a bunch of files which wouldn't necessarily be used. I also edited the app to not reference these files, so you don't see 404s when you run it locally.

@javiercn it doesn't look entirely terrible 🍕:

image

**Pull request merged**
