### PR TITLE
Update branding to 2.1.32 & merge internal commits

### PR DESCRIPTION
**Pull request by wtgodbe**

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
Much of this looks familiar 😺

**Comment by dougbu** [comment]
`Unable to find a stable package Microsoft.AspNetCore.Identity with version (>= 2.1.31 && < 2.2.0)` and this PR is still using `macOS-10.14` images ☹️

**Comment by dougbu** [comment]
@wtgodbe is this held up by #38536❔

**Comment by wtgodbe** [comment]
Yes

**Pull request merged**
