### PR TITLE
Send email confirmation after register via external login

### PR DESCRIPTION
**Pull request by HaoK**
Fixes https://github.com/aspnet/AspNetCore/issues/5767

Note this doesn't cause any change in the default experience as the confirmation email is sent silently (and by default its a no-op anyways)  But dropping in a real email sender will just light it up

@ajcvickers @blowdart

### CODE REVIEW

**Comment by HaoK** [comment]
Maybe its worth consolidating the SendConfirmationEmail code block into a helper, since we have 4 copies of this identical block now (boostrap3/4 + External/Register).

**Review by mkArtak — APPROVED** [review]

**Comment by HaoK** [comment]
Weird is @mkArtak not considered an approving reviewer?

**Comment by anurse** [comment]
Current failure is https://github.com/aspnet/AspNetCore/issues/8109. Working on getting it skipped.

**Comment by HaoK** [comment]
@ajcvickers can you review?

**Review by ajcvickers — APPROVED** [review]

**Comment by Ponant** [comment]
The purpose of an external login is in large part for circumventing email confirmation. So I do not understand the logic behind this besides an logic in the `UserManager`. Cheers

**Pull request merged**
