### PR TITLE
Update localization for templates.

### PR DESCRIPTION
**Pull request by phenning**
Update localization for templates

Inserting localization from WebTools repo

### CODE REVIEW

**Comment by phenning** [comment]
@pranavkm Here are the updated strings. I couldn't locate your repo issue #, but this corresponds with the bug in DevOps.

**Comment by pranavkm** [comment]
Thanks Phil. Could you rebase on the 5.0 branch? Might fix the merge conflicts.

**Comment by phenning** [comment]
> Thanks Phil. Could you rebase on the 5.0 branch? Might fix the merge conflicts.

Weird, it was initially branched from release/5.0, but I created the PR targeting main then retargetted on the website when i noticed..

**Comment by wtgodbe** [comment]
Still lots of conflicts, I can get this merged once that's cleaned up

**Comment by mkArtakMSFT** [comment]
Thanks @wtgodbe.
@phenning can you please resolve conflicts so that Will can get this merged? Thanks!

**Comment by phenning** [comment]
> Still lots of conflicts, I can get this merged once that's cleaned up

Should be good to go now.

**Review by mkArtakMSFT — APPROVED** [review]
Thanks @phenning!

**Comment by wtgodbe** [comment]
Do we need this change in 3.1 as well? @phenning @mkArtakMSFT

**Comment by phenning** [comment]
> Do we need this change in 3.1 as well? @phenning @mkArtakMSFT

From my perspective in VS 16.9+ its not really necessary since we have 5.0 enabled by default and will pull in these strings in the new UI experience. Also, without updates to the en strings.json in 3.1 (which are not in this PR) enu and non-enu names would be out of sync since we added "ASP.NET Core" to some of the template names in the 5.0 branch for the new New Project Dialog experience.

**Pull request merged**
