### PR TITLE
[release/2.1] Update Node dependencies for Angular template

### PR DESCRIPTION
**Pull request by captainsafia**
## Description
- Update dependencies to their latest patch release via `npm updated`
- Update dependencies with known security issues via `npm audit fix`

## Customer Impact

This PR includes some routine updates to the Node packages that we reference in the Angular template. Customers can apply these updates on their own but including them as part of the template reduces the friction for using these templates.

## Regression?
- [ ] Yes
- [X] No

## Risk
- [ ] High
- [ ] Medium
- [X] Low

Most package updates are for minor/path versions.

## Verification
- [X] Manual (required)
- [ ] Automated

Manual validation completed via:

```
$ dotnet new angular
$ dotnet run
```

## Packaging changes reviewed?
- [ ] Yes
- [ ] No
- [X] N/A

### CODE REVIEW

**Review by ryanbrandenburg — APPROVED** [review]
LGTM

**Review by mkArtakMSFT — APPROVED** [review]
Thanks @captainsafia !

**Comment by BrennanConroy** [comment]
I don't know how templates are shipped, do they need to be included in the patch.config? @dotnet/aspnet-build

**Comment by wtgodbe** [comment]
> I don't know how templates are shipped, do they need to be included in the patch.config? @dotnet/aspnet-build

Looks like this build produced the package without it needing to be in patchConfig. Looking at old 2.1 drops, it seems that we produce the template packages every time.

**Comment by wtgodbe** [comment]
See https://www.nuget.org/packages/Microsoft.DotNet.Web.Spa.ProjectTemplates.2.1/

**Comment by captainsafia** [comment]
@wtgodbe I think this is ready to go now? I'm not sure if your comments above indicate there is more work to do here.

**Pull request merged**
