### PR TITLE
Merging internal commits for release/5.0

### PR DESCRIPTION
**Pull request by vseanreesermsft**

### CODE REVIEW

**Comment by dougbu** [comment]
@vseanreesermsft @mmitche are 5.0 merges to GitHub necessary or even correct now❔

**Comment by mmitche** [comment]
For this last release, we should merge back into 5.0 for completeness.

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
@Pilchie would you prefer we leave this and #41179 in the 5.0.x milestone❔ One alternative would be to create a 5.0.18 milestone that contains only these two PRs.

Also, how quickly should we remove the release/5.0 branches here and in AzDO after the v5.0.17 is visible in them (because we've merged this PR)❔

**Comment by Pilchie** [comment]
I'm fine with leaving them in the 5.0.x milestone.  However, before deleting the branch, we should create a tag of some kind that includes the commits from this PR, so that people can find the end of the 5.0 line, right?

**Comment by dougbu** [comment]
> we should create a tag of some kind that includes the commits from this PR

That makes sense and I'm tempted to name the tag `release/5.0`. But is there a naming policy or at least something more than prior art from other .NET repos or other branches that ended w/ an MSRC fix or two❔ I see a `release/2.2` tag in dotnet/extensions and both `release/2.2` and `release/3.0` in dotnet/efcore but neither in dotnet/aspnetcore.

**Pull request merged**
