### PR TITLE
Move EmptyHttpResult to Http.Abstractions

### PR DESCRIPTION
**Pull request by JamesNK**
This PR moves `EmptyHttpResult` to abstractions and adds a type forward. This allows us to no longer require reflection hacks to get a reference to `EmptyHttpResult.Empty`.

IMO this isn't just a change to make our code better. It is normal to have a "null" or "empty" value/implementation be part of the abstraction.

### CODE REVIEW

**Comment by JamesNK** [comment]
> Does this need an API review or does the type forward mitigate that?

From the user's perspective, nothing changes. Doesn't seem necessary. What do you think @halter73?

**Review by halter73 — APPROVED** [review]

**Comment by halter73** [comment]
This is a nonbreaking change that doesn't really add API. I don't think we have to API review this.

**Comment by JamesNK** [comment]
Numbers!

* Before https://github.com/dotnet/aspnetcore/pull/46020: **17316 KB**
* After this change: **15538 KB**

And no more warnings from `Http.Results`.

**Review by captainsafia — APPROVED** [review]
🚀

**Review by davidfowl — APPROVED** [review]

**Pull request merged**
