### PR TITLE
Revert "Run all tests on quarantine runs to mimic ci runs"

### PR DESCRIPTION
**Pull request by HaoK**
Reverts dotnet/aspnetcore#29667

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
Thanks

**Comment by TanayParikh** [comment]
Hmm, tests failing:
image

Looks like the two E2E tests need to be quarantined per https://github.com/dotnet/aspnetcore/pull/29652/.

**Comment by TanayParikh** [comment]
Quarantining: https://github.com/dotnet/aspnetcore/pull/29740

**Pull request merged**
