### PR TITLE
Make problemdetails settable in problemdetailscontext

### LINKED ISSUE #47633: Allow ProblemDetails property to be settable in ProblemDetailsContext
## Background and Motivation

Currently the ProblemDetail property in ProblemDetailsContext is init only, which makes it impossible to change the ProblemDetails instance to another type if wanted when customizing the problem details. 

For example, when sending invalid JSON to an API controller a validation problem is returned. If I would like to change this to another problem details type, the property needs to be settable.

## Proposed API

```diff
namespace Microsoft.AspNetCore.Http;

public class ProblemDetailsContext
{
-   public ProblemDetails ProblemDetails { get; init; }
+   public ProblemDetails ProblemDetails { get; set; }
}
```

## Usage Examples

```
builder.Services.AddProblemDetails(options =>
{
    options.CustomizeProblemDetails = (context) => 
    {
        if (context.ProblemDetails is HttpValidationProblemDetails)
        {
            // change to another problem details type because the HttpValidationProblemDetails contains
            // an Errors property that might not be wanted in some cases.
            context.ProblemDetails = new ProblemDetails() { .... }
        }
    };
});
```

## Alternative Designs
N/A

## Risks
Investigate so it has no side effect of substituting the problem details instance here,

### PR DESCRIPTION
**Pull request by bjornen77**
- [X] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [X] You've included unit or integration tests for your change, where applicable.
- [X] You've included inline docs for your change, where applicable.
- [X] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

# Make ProblemDetails settable in ProblemDetailsContext

## Description

The ProblemDetails property in ProblemDetailsContext is now settable which makes it possible to
replace the current ProblemDetails instance when using the customize problem details feature.

Fixes #47633

### CODE REVIEW

**Comment by bjornen77** [comment]
How can I solve the build errors?

**Comment by mitchdenny** [comment]
Hrm interesting. I'm not sure what the correct thing to do here is to express our intention. It seems wrong to update Shipped with ```init``` changed to ```set```, but you've already done what you would normally do when adding API.

@halter73 do you know the what the correct way to handle this is? I'm going to see if I can find the implementation logic for this check to see if I can figure it out but thought you might know the right thing to do off the top of your head.

**Comment by mitchdenny** [comment]
OK, I think I've got it. We have to REMOVE the old API in unshipped and add the new one. I've made a change to your PR with what I think should work. We should know soon enough if thats the correct way to do it ;)

For future reference, here is the analyzer that does this:

https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.cs

**Comment by bjornen77** [comment]
Nice work! Thank you for your help @mitchdenny.

**Comment by mitchdenny** [comment]
I wonder what behavioural tests we need to cover this. Perhaps a test that results in a problem using MVC that we then override using the setter and then checking it in an early stage middleware (not make sure the replaced version made it through).

**Comment by captainsafia** [comment]
> Hrm interesting. I'm not sure what the correct thing to do here is to express our intention. It seems wrong to update Shipped with `init` changed to `set`, but you've already done what you would normally do when adding API.
> 
> @halter73 do you know the what the correct way to handle this is? I'm going to see if I can find the implementation logic for this check to see if I can figure it out but thought you might know the right thing to do off the top of your head.

If you're in Visual Studio, there should be a codefix that lights up to automatically update the PublicAPI.txt files with the delta. If that isn't working, there might be something suspicious afoot.

> I wonder what behavioural tests we need to cover this. Perhaps a test that results in a problem using MVC that we then override using the setter and then checking it in an early stage middleware (not make sure the replaced version made it through).

Adding a test [in this class](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/test/Infrastructure/DefaultApiProblemDetailsWriterTest.cs) and [in this one](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/test/Infrastructure/DefaultApiProblemDetailsWriterTest.cs) that uses a setter and validates the behavior of the `WriteAsync` call is probably sufficient here.

**Comment by bjornen77** [comment]
> If you're in Visual Studio, there should be a codefix that lights up to automatically update the PublicAPI.txt files with the delta. If that isn't working, there might be something suspicious afoot.

@captainsafia  I used the codefix you mentioned in Visual Studio and it added the new API in PublicApi.Unshiped.txt and the warning/code fix in Visual Studio went away. But then when I created the PR I got the build errors.

**Comment by bjornen77** [comment]
> Adding a test [in this class](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/test/Infrastructure/DefaultApiProblemDetailsWriterTest.cs) and [in this one](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/test/Infrastructure/DefaultApiProblemDetailsWriterTest.cs) that uses a setter and validates the behavior of the `WriteAsync` call is probably sufficient here.

@captainsafia I think that both your links points to the same class?

**Comment by captainsafia** [comment]
> > Adding a test [in this class](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/test/Infrastructure/DefaultApiProblemDetailsWriterTest.cs) and [in this one](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/test/Infrastructure/DefaultApiProblemDetailsWriterTest.cs) that uses a setter and validates the behavior of the `WriteAsync` call is probably sufficient here.
> 
> @captainsafia I think that both your links points to the same class?

My bad, it should have been a link to https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http.Extensions/test/ProblemDetailsDefaultWriterTest.cs.

> > If you're in Visual Studio, there should be a codefix that lights up to automatically update the PublicAPI.txt files with the delta. If that isn't working, there might be something suspicious afoot.
> 
> @captainsafia I used the codefix you mentioned in Visual Studio and it added the new API in PublicApi.Unshiped.txt and the warning/code fix in Visual Studio went away. But then when I created the PR I got the build errors.

Ah, I believe you've run into a bug wherein APIs that are removed are not correctly documented by the PublicAPI analyzer. I believe there is an issue for this somewhere...

**Comment by bjornen77** [comment]
> My bad, it should have been a link to https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http.Extensions/test/ProblemDetailsDefaultWriterTest.cs.

Thanks @captainsafia!

**Comment by bjornen77** [comment]
Tests are now added.

**Review by mitchdenny — APPROVED** [review]

**Comment by mitchdenny** [comment]
Thanks for your contribution @bjornen77!

**Pull request merged**
