### PR TITLE
Stop shipping Blazor WASM templates in 3.1 patches

### PR DESCRIPTION
**Pull request by HaoK**
Part of https://github.com/dotnet/aspnetcore/issues/25923

## Description
The Blazor WASM template package is a going to be out of servicing support as of March. This change removes the code so it no longer will be built / shipped. We also plan to deprecate the package on nuget with a custom error message pointing at the current version of the template.

## Customer impact
This was the first version of the WASM templates, and there are many fixes and scenarios that are only in 5.0+, the expectation was that most customers will need to upgrade to 5.0 and not remain on 3.2 indefinitely, especially since once out of support, not even security fixes will be ported to 3.2

## Regression
No

## Risk
Low. We are just removing the entire source directory along with the tests.

### CODE REVIEW

**Comment by HaoK** [comment]
@dotnet/aspnet-build are there any known issues with the mac checks on release/3.1?  Its failed for me since yesterday

**Comment by wtgodbe** [comment]
Yeah, that's https://github.com/dotnet/core-eng/issues/11636

**Comment by HaoK** [comment]
@pranavkm should I just go ahead and delete the files now too?

**Review by javiercn — APPROVED** [review]
Should we remove the contents+tests alltogether?

**Review by ryanbrandenburg — APPROVED** [review]

**Comment by HaoK** [comment]
Ok I will update the PR to remove all the content as well now

**Comment by HaoK** [comment]
Is anyone aware of any files/content that live outside of the project templates directory for these wasm templates?  The build is green but...?

**Comment by captainsafia** [comment]
@HaoK AFAIK, template files don't exist outside of the templates for Blazor.

**Pull request merged**
