### PR TITLE
Big-endian fixes: Guid handling in KeyRingBasedDataProtector.cs

### PR DESCRIPTION
**Pull request by uweigand**
* Add big-endian version of optimized Guid accessors

* Fixes part 4 of https://github.com/dotnet/aspnetcore/issues/35709

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

**PR Title**
Big-endian fixes: Guid handling in KeyRingBasedDataProtector.cs

**PR Description**
* Add big-endian version of optimized Guid accessors
* Fixes part 4 of https://github.com/dotnet/aspnetcore/issues/35709

### CODE REVIEW

**Review by adityamandaleeka — APPROVED** [review]

**Comment by adityamandaleeka** [comment]
@blowdart @HaoK, this looks fine to me, but can one of you also take a look at this change?

**Comment by blowdart** [comment]
@GrabYourPitchforks should weigh in

**Comment by blowdart** [comment]
If we treat this like every other of the big endian stuff, let's go for it and test it doesn't break our mainline scenarios of little endian, and hold out for getting a free mainframe to test on ;)

**Review by blowdart — APPROVED** [review]

**Comment by GrabYourPitchforks** [comment]
On Core, this really should just call the `Guid(ROS<byte>)` ctor. On netstandard and downlevel frameworks (which assume little-endian), you can use `MemoryMarshal.Read<Guid>(...)`. Then the whole method becomes 5 lines of code.

**Pull request merged**
