### PR TITLE
Switch to Windows Server queues

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Comment by dougbu** [comment]
/fyi @MattGal

This changed worked in validation builds. Just kicked off https://dev.azure.com/dnceng/internal/_build/results?buildId=501567 because internal builds are more complete.

**Review by wtgodbe — APPROVED** [review]

**Comment by MattGal** [comment]
> /fyi @MattGal
> 
> This changed worked in validation builds. Just kicked off https://dev.azure.com/dnceng/internal/_build/results?buildId=501567 because internal builds are more complete.

Sweet.  If you don't do in-build, UI-based testing, I'd fully expect this outcome but I'm glad to hear!

**Review by MattGal — APPROVED** [review]

**Comment by dougbu** [comment]
Well, I was surprised to find `tar` on a Windows Server machine 😈 

How broadly should we apply changes like this i.e. should we do the same in all repos and branches where we use VS2019 queues?

**Comment by MattGal** [comment]
> Well, I was surprised to find `tar` on a Windows Server machine 😈
> 
> How broadly should we apply changes like this i.e. should we do the same in all repos and branches where we use VS2019 queues?

Absolutely;  if your builds work there, you should be moving to server-based queues.  This directly impacts in may cases the delay one encounters between queuing a pipeline and seeing the build start.

I actually wanted to make this change without even renaming the queues but we were concerned about unintentionally breaking at least one person's build, so there's both.  Ideally we'll eventually get everyone on the fastest-provisioning machines possible.

**Pull request merged**
