### PR TITLE
Update branding for preview 5

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Review by ryanbrandenburg — APPROVED** [review]

**Comment by jkotalik** [comment]
@ryanbrandenburg test failure looks like something relevant to you.

**Comment by jkotalik** [comment]
@aspnet-hello triage this

**Comment by ryanbrandenburg** [comment]
@jkotalik that's not how the bot works, you have to provide the URL of the build that failed.

**Comment by jkotalik** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=147275

**Review by Eilon — APPROVED** [review]

**Pull request merged**
