### PR TITLE
Synchronize KestrelTrace next-id comments

### PR DESCRIPTION
**Pull request by amcasey**
`KestrelTrace` IDs have to be unique across the many files in which they appear, so we have comments indicating the start of the unused range in multiple places.  Make those comments consistent.

### CODE REVIEW

**Review by adityamandaleeka — APPROVED** [review]
LGTM. Should we also update the comments to mention that all the comments should be updated when the number changes?

**Comment by amcasey** [comment]
> LGTM. Should we also update the comments to mention that all the comments should be updated when the number changes?

Pushed an update.

**Review by adityamandaleeka — APPROVED** [review]

**Comment by JamesNK** [comment]
Wait, is this true? I remember that numbers used to be shared because they shared the same logger name, but then we gave the loggers unique names. After that, it doesn't matter if there are conflicts.

**Comment by JamesNK** [comment]
They're separate loggers: https://github.com/dotnet/aspnetcore/blob/main/src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelTrace.cs

They were one logger but split out when the highest logger ID was 63. The comment's intent is to communicate that you can use sequential logger IDs in these files from 64 onwards.

**Comment by amcasey** [comment]
So the comment that was updated to 66 is wrong and a better comment would be 
```csharp
// IDs prior to 64 are reserved for back compat (the various KestrelTrace loggers used to share a single sequence)
```
?

**Comment by JamesNK** [comment]
Sure

**Pull request merged**
