### PR TITLE
Clone is required prior to pre requistes

### PR DESCRIPTION
**Pull request by kp2017-zz**
pre-requisites require the scripts directory

Summary of the changes (Less than 80 chars)
copied and pasted clone instructions above Pre Requiste instructions

### CODE REVIEW

**Comment by Pilchie** [comment]
@aspnet/aspdoi thoughts?

**Comment by dougbu** [comment]
Why is cloning required prior to getting the prerequisites? While scripts are available in the repo to install some of the prereqs, the particular install locations et cetera aren't required. This change seems to mandate an ordering unnecessarily.

**Comment by kp2017** [comment]
Maybe it’s not required but it is more efficient. Following the current directions the reader downloads multiple times. 

Another view point is the change gives context to the file location. If the audience doesn’t understand how to clone they probably don’t understand the path reference. I simply copied and pasted the clone directions to be first; however additional changes could be made to clarify the reference path.

**Comment by dougbu** [comment]
> current directions the reader downloads multiple times.

Downloads _what_ multiple times?

**Comment by kp2017** [comment]
The prerequisites require running scripts from powershell. Those scripts are in the repo however they are not on the reader's computer. Without running clone first the reader will have to find each script and all the scripts that script runs and individual download them or I guess down load the whole repo to make it easier. If later we want them to clone the Repo, why not just have the to do that to begin with.

**Comment by dougbu** [comment]
>  Those scripts are in the repo however they are not on the reader's computer.

@kp2017 that's not the case in general. Users can install the prerequisites using installers from the relevant product sites and the repo should find them. (If it doesn't, that's a build bug and not a doc problem.) For example Windows builds will find `java.exe` even if it's not installed using `InstallJdk.ps1`.

So, there's no reason to change the document.

**Comment by kp2017** [comment]
I understand that but the document does reference script that do it; therefore requiring the script to be ran (if chosen). It seems one way or the other should be changed but but the current version, telling someone to do something out of context, is a documentation issue.

**Comment by dougbu** [comment]
The following comments in the doc are intended to be suggestions. If you want to change them to make that even more clear, sure. But the existing change isn't something I can get behind.
> To install the **exact** required components, run eng/scripts/InstallVisualStudio.ps1

> To install a version of the JDK **that will only be used by this repo**, run eng/scripts/InstallJdk.ps1

**Comment by kp2017** [comment]
I understand the instructions are optional process flows but from the state the user's environment when the options are presented to them, their systems is not in a state that allows the options. If we are to assume they understand how to get their environment in that state, we do not need the cloning instructions following. 

I understand you might not like my approach to fixing this issue, but you are not providing alternatives. You are suggesting we just ignore the contradiction. I think you need to provide a better alternative.

**Comment by dougbu** [comment]
The alternative I'm suggesting is to make it clear the later sub-bullets using scripts in the repo are not the only way to install the prerequisites. Guess you could also mention the repo needs to be cloned first if users choose to use those scripts but I think that's pretty obvious.

**Comment by kp2017** [comment]
Can you check in the change that you are suggesting so I can get a better understanding of your perspective?

**Comment by dougbu** [comment]
@kp2017 I created #18277 because I can't push to your fork. My changes start from scratch due to the conflicts in this PR. Feel free to comment there.

I suggest closing this PR.

**Comment by kp2017** [comment]
Closing PR to use #18277 instead

**Pull request closed without merging**
