### PR TITLE
[Mvc] Use ArgumentNullException.ThrowIfNull in ChecksumValidator

### PR DESCRIPTION
**Pull request by javiercn**
# {PR title}

- [ ] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

{Detail}

Fixes #{bug number} (in this specific format)

### CODE REVIEW

**Review by MackinnonBuck — APPROVED** [review]

**Review by mgravell — APPROVED** [review]

**Review by captainsafia — APPROVED** [review]

**Comment by adityamandaleeka** [comment]
@dotnet/aspnet-build Any idea what this submodule fetch error is about?

**Comment by wtgodbe** [comment]
Interesting, haven't seen that one before - is it consistent?

@dotnet/source-build-internal have you seen this before when cloning submodules?

**Comment by wtgodbe** [comment]
Some more context on the failure:

>   Cloning repository at: /__w/1/s/ -> /__w/1/s/artifacts/source-build/self/src/ ...
  Creating empty clone at: /__w/1/s/artifacts/source-build/self/src/
  Cloning into '/__w/1/s/artifacts/source-build/self/src'...
  done.
  Checking out sources...
  Clone complete: /__w/1/s/ -> /__w/1/s/artifacts/source-build/self/src/
  Entering 'src/submodules/MessagePack-CSharp'
  Cloning repository at: . -> /__w/1/s/artifacts/source-build/self/src/src/submodules/MessagePack-CSharp ...
  Destination already exists!
  Clean is enabled: removing /__w/1/s/artifacts/source-build/self/src/src/submodules/MessagePack-CSharp and continuing...
  Creating empty clone at: /__w/1/s/artifacts/source-build/self/src/src/submodules/MessagePack-CSharp
  Cloning into '/__w/1/s/artifacts/source-build/self/src/src/submodules/MessagePack-CSharp'...
  fatal: transport 'file' not allowed
  fatal: run_command returned non-zero status for src/submodules/MessagePack-CSharp
  .
/__w/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.23063.7/tools/SourceBuild/SourceBuildArcadeBuild.targets(170,5): error MSB3073: The command "git submodule foreach --recursive '/__w/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.23063.7/tools/SourceBuild/git-clone-to-dir.sh  --source . --dest "/__w/1/s/artifacts/source-build/self/src/$sm_path" --clean'" exited with code 128. [/__w/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.23063.7/tools/Build.proj]
##[error].packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.23063.7/tools/SourceBuild/SourceBuildArcadeBuild.targets(170,5): error MSB3073: The command "git submodule foreach --recursive '/__w/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.23063.7/tools/SourceBuild/git-clone-to-dir.sh  --source . --dest "/__w/1/s/artifacts/source-build/self/src/$sm_path" --clean'" exited with code 128.

CC @crummel, @MichaelSimons - apparently this has been happening transiently on some of our PRs today and goes away on retry. The submodule in question hasn't been touched in 5 months - maybe fallout from an Arcade update?

**Comment by crummel** [comment]
It's actually from a git update that disabled the `file://` protocol by default for security reasons, so it probably depends on whether you're getting an up-to-date machine.  We thought we wouldn't need to fix it because the 3.1 builds were going away but I reopened https://github.com/dotnet/source-build/issues/3111 for it.

**Pull request merged**
