### PR TITLE
Remove use of Expression.Constant in RequestDelegateFactory

### PR DESCRIPTION
**Pull request by captainsafia**
Adresses https://github.com/dotnet/aspnetcore/issues/41435

I couldn't find a particularly elegant replacement for the use of `Expression.Constant` in the enums for the DateTimeStyles and NumberStyles but open to ideas here.

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Any chance you can see better perf numbers?

**Comment by davidfowl** [comment]
@captainsafia we should put this in .NET 8

**Comment by captainsafia** [comment]
Closing this so we can re-target for 8.0.

**Comment by davidfowl** [comment]
👍🏾

**Pull request closed without merging**
