### PR TITLE
Update branding to 6.0.1

### PR DESCRIPTION
**Pull request by dougbu**
- dotnet/aspnetcore-internal#3946

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]
Does all of the other special stuff have to wait until we ship?

**Comment by dougbu** [comment]
> Does all of the other special stuff have to wait until we ship?

Yes though it appears I'll need to do _something_ to get this building. Will look in a bit&hellip;

**Comment by dougbu** [comment]
I like consistency but failing _every_ build job is a bit much. The problem is our infrastructure ignores `@(SuppressBaselineReference)` items in servicing builds, expecting eng/Baseline.Designer.props to be updated before or at the same time as we move into servicing mode. Options:

1. Suppress the eng/targets/ResolveReferences.targets `<Error />`s about package references when `$(ValidateBaseline)` is `false`
2. Special-case the `IdentityServer4.*` references in eng/targets/ResolveReferences.targets
3. Add `%(InNuspecFile)` metadata to `IdentityServer4.*` references in Microsoft.AspNetCore.ApiAuthorization.IdentityServer.csproj. Yes, this would be a lie but the errors would go away

I lean toward (3) but would appreciate your thoughts @wtgodbe

**Comment by wtgodbe** [comment]
I prefer option 1 since it more accurately represents what we're doing (ignoring baseline errors)

**Comment by dougbu** [comment]
> I prefer option 1 since it more accurately represents what we're doing (ignoring baseline errors)

done

**Comment by dougbu** [comment]
@JamesNK @wtgodbe /fyi https://github.com/dotnet/aspnetcore/pull/38027/commits/68bf233d9f368536aa5108f620a8e5d0aea2eaa7 does the same thing for this PR as https://github.com/dotnet/aspnetcore/pull/38031/commits/c853dd85164fc2d4a6be0e2973efe8f10ee53604

**Pull request merged**
