### PR TITLE
Dispose CancellationTokenSource

### PR DESCRIPTION
**Pull request by alex-inftx**
we can dispose CancellationTokenSource after use

### CODE REVIEW

**Comment by gfoidl** [comment]
@alex-inftx please change the target branch of this PR to be _main_ (and not _release/6.0_).

**Comment by sharwell** [comment]
I changed the base branch to main not realizing that release/6.0 hasn't merged into main yet. Sorry for the noise.

**Comment by mgravell** [comment]
> I changed the base branch to main not realizing that release/6.0 hasn't merged into main yet. Sorry for the noise.

Still looks like 6.0 unless I'm misreading; if you click edit, the target branch should become editable:

image

However, if it starts freaking out, it may be easier to redo the branch against main.


as an aside: there is no "yet" here - 6.0 is a maintenance branch; it'll stay independent until some future hypothetical point when it simply gets nuked

**Comment by sebastienros** [comment]
I changed the base branch but now there are lots of conflicts. Might be easier to create a new PR.

**Comment by mgravell** [comment]
image

yeah, that would be the "freaking out" I was hoping to avoid :) in theory it should be possible to rebase and force push, but for a 2 line change, starting a clean branch from main is probably much much simpler

**Comment by alex-inftx** [comment]
> @alex-inftx please change the target branch of this PR to be _main_ (and not _release/6.0_).

**Comment by alex-inftx** [comment]
> @alex-inftx please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@dotnet-policy-service agree company="infotecs"

**Comment by alex-inftx** [comment]
> image
> 
> yeah, that would be the "freaking out" I was hoping to avoid :) in theory it should be possible to rebase and force push, but for a 2 line change, starting a clean branch from main is probably much much simpler

It's done [rebase and+force push] )

**Review by mgravell — APPROVED** [review]
This looks good to me, and should clean up a timer callback 👍

**Comment by alex-inftx** [comment]
> This looks good to me, and should clean up a timer callback 👍
thank you!
@mgravell , should I create a new PRs to place changes to release/6.0 and release/7.0 ?

**Comment by mgravell** [comment]
@alex-inftx IMO no this doesn't warrant backport. Yes, it may be more efficient, but: the feature isn't fundamentally broken or dangerous "as is". Others may disagree, but I vote "no"

**Comment by adityamandaleeka** [comment]
Thanks @alex-inftx. I agree with @mgravell that this doesn't need to be backported.

**Pull request merged**
