### PR TITLE
Make IdentityServer.Configuration.KeyDefinition linker friendly

### PR DESCRIPTION
**Pull request by benaadams**
Bind directly rather than using configuration.Bind(key)

Same issue as https://github.com/dotnet/aspnetcore/issues/25482

### CODE REVIEW

**Review by javiercn — APPROVED** [review]

**Comment by javiercn** [comment]
@Pilchie The changes have low impact and the tests pass. I'm happy if you decide to merge it for RC1 or wait for RC2 or 6.0.

**Comment by Pilchie** [comment]
Approved for RC1.

**Comment by benaadams** [comment]
@javiercn if this was merged to master, should I add another PR to add it to RC2 branch? (or other branch)

**Comment by javiercn** [comment]
@benaadams Yes, this needs to go in RC2, thanks for sending the PR.

**Pull request merged**
