### PR TITLE
Input components two way binding

### LINKED ISSUE #40097: InputText and other input components do not use SetUpdatesAttributeName() for two-way binding
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi @SteveSandersonMS,
is there any reason why the `InputText` implementation (and implementation of other input components) do not use the `SetUpdatesAttributeName("value")` method when it replicates the `<input @bind-value="..." />` in `BuildRenderTree()`?

The changes in DOM get not synchronized to the .NET model then.

As a result when someone wants to derive his own component from `InputText` e.g. to apply some text formatting and you enter the same text input twice, the first callback causes the UI to replace the value with the formatted value but the second callback leaves the input intact as it does not detect any change in the .NET model to be synchronized to DOM (no matter you call the `StateHasChanged()` or not).

### Expected Behavior

.NET model of `InputText` and other input components reflect DOM changes (two-way binding) from their underlying `input` elements.

### Steps To Reproduce

```csharp
public class MyInputText : InputText
{
	protected override bool TryParseValueFromString(string? value, out string? result, [NotNullWhen(false)] out string? validationErrorMessage)
	{
		if (value == "24h")
		{
			result = "24:00:00";
		}
		else
		{
			result = value;
		}
		validationErrorMessage = null;
		return true;
	}
}
```

```razor
<EditForm Model="model">
    <MyInputText @bind-Value="@model.Value" />
</EditForm>
@model.Value

@code
{
    private Model model = new Model();
    private class Model
    {
        public string Value { get; set; }
    }
}
```

This fixes the issue:
```csharp
public class MyInputText : InputText
{
	protected override bool TryParseValueFromString(string? value, out string? result, [NotNullWhen(false)] out string? validationErrorMessage)
	{
		if (value == "24h")
		{
			result = "24:00:00";
		}
		else
		{
			result = value;
		}
		validationErrorMessage = null;
		return true;
	}

	protected override void BuildRenderTree(RenderTreeBuilder builder)
	{
		builder.OpenElement(0, "input");
		builder.AddMultipleAttributes(1, base.AdditionalAttributes);
		builder.AddAttribute(2, "class", base.CssClass);
		builder.AddAttribute(3, "value", BindConverter.FormatValue(base.CurrentValue));
		builder.AddAttribute(4, "onchange", EventCallback.Factory.CreateBinder<string>((object)this, (Action<string>)delegate (string? __value)
		{
			base.CurrentValueAsString = __value;
		}, base.CurrentValueAsString, (CultureInfo?)null));
		builder.SetUpdatesAttributeName("value");              // <-------- THIS FIXES THE ISSUE
		builder.CloseElement();
	}
}
```

### Exceptions (if any)

_No response_

### .NET Version

6.0.101

### Anything else?

If it helps, I can prepare a PR for this.

Related issue [#17281](https://github.com/dotnet/aspnetcore/issues/17281)

### PR DESCRIPTION
**Pull request by hakenr**
# Input components two way binding

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

InputText and other input components do not use `SetUpdatesAttributeName()` for two-way binding. This PR adds missing `SetUpdatesAttributeName()` calls and aligns the code to `@bind` used by .razor.

## Description

Discussed with @SteveSandersonMS in #40097. Added the missing two-way binding in input components and created E2E test for the changed behavior (every single added test was failing before the fix).

Fixes #40097

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
Thanks so much for this, @hakenr! It looks like extremely high-quality work. The new E2E test cases look great.

Do you have a sense of what's going on with some of the existing E2E tests now failing? Do you know whether there's something defective about those existing test cases, or is there some unwanted side-effect from the new `SetUpdatesAttributeName` calls?

**Comment by hakenr** [comment]
My fix breaks some older tests which relay on the fact the input values are not synchronized to DOM (as the diff did not recognize they are changed). Will add adjustments to the tests but will need careful review...

## Example - failing `InputNumberInteractsWithEditContext_NonNullableInt` test
```csharp
    [Fact]
    public void InputNumberInteractsWithEditContext_NonNullableInt()
    {
        var appElement = MountTypicalValidationComponent();
        var ageInput = appElement.FindElement(By.ClassName("age")).FindElement(By.TagName("input"));
        var messagesAccessor = CreateValidationMessagesAccessor(appElement);

        // InputNumber emits unmatched attributes
        Browser.Equal("Enter your age", () => ageInput.GetAttribute("placeholder"));

        // Validates on edit
        Browser.Equal("valid", () => ageInput.GetAttribute("class"));
        ageInput.SendKeys("123\t");
        Browser.Equal("modified valid", () => ageInput.GetAttribute("class"));

        // Can become invalid
        ageInput.SendKeys("e100\t");
        Browser.Equal("modified invalid", () => ageInput.GetAttribute("class"));
        Browser.Equal(new[] { "The AgeInYears field must be a number." }, messagesAccessor);

        // Empty is invalid, because it's not a nullable int
        ageInput.Clear();
        ageInput.SendKeys("\t");
        Browser.Equal("modified invalid", () => ageInput.GetAttribute("class"));
        Browser.Equal(new[] { "The AgeInYears field must be a number." }, messagesAccessor);

        // Zero is within the allowed range
        ageInput.SendKeys("0\t");
        Browser.Equal("modified valid", () => ageInput.GetAttribute("class"));
        Browser.Empty(messagesAccessor);
    }
```
| Step                           | DOM input.value before                                       | DOM input.value With two-way binding                         |
| ------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ |
| 1. initial value               | `0`                                                          | `0`                                                          |
| 2. `SendKey("123\t")`          | `0123` => `123`                                              | `0123` => `123`                                              |
| 3. `SendKey("e100\t")`         | `123e100` (The `InputNumber.Value` remains `123`, but as there is no two-way binding, there is no change in DOM and the input remains `123e100`) | `123e100` => `123` (As the diff recognizes there is `123e100` in the DOM, the `InputNumber.Value` of `123` gets synchronized to the DOM.) |
| 4. `Clear()` + `SendKey("\t")` | (empty)                                                      | empty => `123` (The `InputNumber.Value` did not change. The diff recognizes there is empty value in DOM and synchronizes `123` gets synchronized to the DOM.) **Here the user sees `123` but indicated as `invalid`!** |
| 5. `SendKey("0\t")`            | `0` (valid)                                                  | `1230` (Zero gets added to the current input contents and the resulting value of `1230` is `invalid`). **This is where the current test fails.** |

@SteveSandersonMS Not sure whether the two-way binding implicates need for some further changes in Input-components as there might occur situations as no. 4 where the input reverts to original valid value but still indicates `invalid` state.

**Comment by SteveSandersonMS** [comment]
Thanks again @hakenr. That's a very clear description. I appreciate the investigation you've done.

This clarifies that it's going to be more complicated than just adding `SetUpdatesAttributeName`, since we couldn't break compatibility for the existing input components in this way. Many apps may rely on the user being able to enter invalid data temporarily and not instantly revert the edit and lose the user's change. I'm reassured that the E2E tests picked this up.

I suppose what we're looking for is some way to preserve the existing behavior of being able to hold invalid contents while also allowing the developer to manipulate edits programmatically if they want. A basic solution would be just adding a further bool parameter called something like `StrictValueConsistency` that turns on this new feature. However it's not ideal because:

1. People won't really understand the conditions under which they should or should not turn on this flag. Perhaps a better name for it would help.
2. Even if people do understand it, we're splitting the behavior in two and forcing people to choose between different modes. It's not as elegant as if there is one mode that covers all reasonable circumstances.

Perhaps some better design would avoid this, e.g., by maintaining some info on the .NET side about the current user-entered string whether or not it is legal, and then only writing the developer's possibly-mutated property value into it if the incoming value was legal. Whether or not we'd want to introduce this extra behavior depends on how sophisticated it ends up being - these input components are pretty foundational so we don't want to complicate them much or open a risk that their behavior becomes harder to reason about. The main alternative would be advising people who want this strict consistency to subclass the relevant Input components and override the rendering to do whatever they want in their specific case.

What do you think?

**Comment by hakenr** [comment]
I believe in long term we should not rely on the deficit of synchronization between .NET model and DOM when implementing the components.
I would rather separate the `Value` parameter used for .NET binding (possibly with some indication of validity and/or default value) from the `value` of underlying `input` (`protected` state of the Input-component), where the second will allow preserving invalid inputs without overwriting them with `Value` when not appropriate.

**Comment by hakenr** [comment]
Proposed one of possible solutions for `InputBase` in separate PR #40326.
I'm leaving this PR as a basis for other possibilities.

**Comment by hakenr** [comment]
Hi @msftbot :-), the PR continues in #40326 to separate two dependent issues and to allow different solutions of the second part while reusing the first one.

**Pull request closed without merging**
