### PR TITLE
Change WebSocket project to target netcoreapp3.0

### PR DESCRIPTION
**Pull request by Tratcher**
#3754 
This only changes the WebSocket package. The tests and samples were already updated. 

These aren't getting updated, correct?
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore
Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore
Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore.Tests

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
This looks fine but why just update the one project?

**Comment by natemcmaster** [comment]
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore should be updated to netcoreapp3.0 since it will need to compile with FrameworkReference before we ship RTM (#4257)
Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore can stay netstandard.
Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore.Tests should update to test on netcoreapp3.0 + .net framework.

**Review by natemcmaster — APPROVED** [review]

**Review by dougbu — APPROVED** [review]
Mostly curious: Does the src/Middleware/WebSockets/samples/TestServer/TestServer.csproj project need to be a legacy .csproj forever?

**Comment by Tratcher** [comment]
Need? No, but it's a good reminder that it's using a completely different stack for interop testing.

**Pull request merged**
