### PR TITLE
Adds ForbiddenObjectResult

### PR DESCRIPTION
**Pull request by ghost**
The ForbidResult does not satisfy the need for passing a message to the consumer. 
So, I added ForbiddenObjectResult which helps in this regard.

### CODE REVIEW

**Comment by brockallen** [comment]
You should enhance it to also issue a www-authenticate response header with an optional error and error_description as per rfc6750.

**Comment by ClaudiuSocaci** [comment]
@pranavkm I have seen this discussion:
https://github.com/aspnet/Mvc/issues/8219
 and I also need ForbidObjectResult.
I added it and created this PR. I would really appreciate if you have a look.

**Comment by pranavkm** [comment]
See https://github.com/aspnet/Mvc/pull/8264 & https://github.com/aspnet/Mvc/pull/8372 for some prior discussions about this.

**Comment by blowdart** [comment]
@pranavkm What does this add to the previous attempts?

**Comment by ClaudiuSocaci** [comment]
@blowdart this is a good feature to have. I managed to read the attempts details after I created the pull request. I mainly read the initial problem stated here aspnet/Mvc#8219 . 
So, in short, it is just another attempt. I will read the other ones and try to change it accordingly

**Comment by ClaudiuSocaci** [comment]
@pranavkm I try to see if I understood it properly:
1) I have to add overloads for Forbid() in ControllerBase
2) I have to add overloads for ForbiddenObjectResult constructor
3) I have to add an executor for this new ForbiddenObjectResult which extends : ObjectResultExecutor and in there override ExecuteAsync -> Does this executor has to be registered somewhere or the executor is found by reflection?
4) I have to add in ForbiddenObjectResult 
public override Task ExecuteResultAsync(ActionContext context) 
where I have to do smth similar to:
`
var executor = context.HttpContext.RequestServices.GetRequiredService<IActionResultExecutor<ForbiddenResultObject>>();
            return executor.ExecuteAsync(context, this);
`

Is this right?

**Comment by ClaudiuSocaci** [comment]
On the other hand, I see @mkArtakMSFT comment and I am not sure if it is still valid for the steps I want to follow.
`Thanks for your effort, @Matthiee. We've discussed this issue further and decided to close this instead, as it doesn't compose well with our existing security story.`

**Comment by ClaudiuSocaci** [comment]
I would really appreciate to know if i should continue this.

**Comment by pranavkm** [comment]
@ClaudiuSocaci 

> * I have to add overloads for Forbid() in ControllerBase
> * I have to add overloads for ForbiddenObjectResult constructor
👍 

> * I have to add an executor for this new ForbiddenObjectResult which extends : ObjectResultExecutor and in there override ExecuteAsync -> Does this executor have to be registered somewhere or the executor is found by reflection?

I think it'll be OK to override `OnFormatting` and have it do call `ForbidAsync`: https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/ForbidResult.cs#L103-L115 

The primary reason we hesitate to add this API, is as discussed, this API works in a very narrow set of cases i.e if you're using bearer auth. Most other auth providers redirect the user (as part of the call to `ForbidAsync`), the body is never sent down to the client. We think developers would be surprised \ confused by this. If this API is added, we need some content in the summary docs that says it's behavior is entirely auth provider dependent. 

Does this help?

**Comment by ClaudiuSocaci** [comment]
I understand, but currently, how can we pass information to consumers telling them what is the cause of 403? Is it recommended to pass nothing, just the status code? Usually with301 it is more understandable but with 403 there can be a lot of reasons why it failed that would help the consumer. That is the only reason I am thinking it would be useful.

**Comment by blowdart** [comment]
As Pranav says there's an assumption here that such messages get displayed somewhere, but that's up to the authentication middleware. For example, cookies just redirects to a page, so that page might pull out the details, but, for example, certificate authentication wouldn't use it at all, because it just eats details. It doesn't help there's no useful standard for the response payload itself, so parsing can't be automated.

**Comment by ClaudiuSocaci** [comment]
Or, would it be enough just to add that class ? ForbiddenObjectResult.
Without any call to it, and every dev can use it where they need.

**Comment by ClaudiuSocaci** [comment]
Ok, thanks @blowdart. Would it be ok just to add the class as I said above?
If not, I think a better idea would be to close the pull request 👍

**Comment by blowdart** [comment]
I leave that to @pranavkm

**Comment by pranavkm** [comment]
> Would it be ok just to add the class as I said above?

Sorry I missed responding to this. Adding the class sounds fine. We'd still want to go with the remainder of the outline described here: https://github.com/aspnet/AspNetCore/pull/12155#issuecomment-513867136

**Comment by pranavkm** [comment]
@ClaudiuSocaci do you still plan on completing this PR based on the most recent feedback?

**Comment by ClaudiuSocaci** [comment]
@pranavkm I do not plan to add all the things you recommended. Only the short option I recommended.
You can close the PR if the second option is not fine.

Thanks

**Comment by ClaudiuSocaci** [comment]
Cool. I will do the changes

**Comment by ClaudiuSocaci** [comment]
@pranavkm Updated as discussed.

**Comment by ClaudiuSocaci** [comment]
@mkArtakMSFT I will try yes

**Comment by ClaudiuSocaci** [comment]
@mkArtakMSFT @pranavkm Locally the build succeeds. I am using macOs Mojave (10.14.5).
Steps I followed:
1) cd src/MVC
2) ./build.sh
3) ./build.sh --test
Everything looks good. I tried to push one more time as last time I did the change directly from github. I hope it succeeds this time.

Screen Shot 2019-08-31 at 3 33 57 PM

**Comment by ClaudiuSocaci** [comment]
@mkArtakMSFT @pranavkm Locally the build succeeds. I am using macOs Mojave (10.14.5).
Steps I followed:

cd src/MVC
./build.sh
./build.sh --test
Everything looks good. I tried to push one more time as last time I did the change directly from github. I hope it succeeds this time.

**Comment by pranavkm** [comment]
@ClaudiuSocaci I'm sorry I misunderstood what you meant by 

> Or, would it be enough just to add that class ? ForbiddenObjectResult.

The behavior isn't correct and I don't think we'd be able to take it as is. I'm sorry I spent a bunch of your time trying to get you to update this PR. We have to call `ForbidAsync` from the result, setting the status code isn't sufficient. Would you be interested in making the change? If not, we should close this PR, we cannot accept it in it's current state.

**Comment by ClaudiuSocaci** [comment]
Sorry I also miss understood. 
What about this last change?

**Comment by mkArtakMSFT** [comment]
Thanks for your effort, @ClaudiuSocaci.
After a detailed review of this issue we've decided not to move forward with it as this PR.
There are some other aspects this change should have incorporated which it doesn't.

**Pull request closed without merging**
