### PR TITLE
[release/2.1] Allow Hosting Bundle to be upgraded by MU

### PR DESCRIPTION
**Pull request by wtgodbe**
## Customer Impact

Adds an .msi, `dotnet-hosting-options`, which writes to the registry the value of the switches used when last installing the hosting bundle for a given Major.Minor version. Subsequent installs of that band of the hosting bundle will choose what the install in the following way:

- If the user passes any switches on the command line, use exactly those (and write them to the registry, along with `0` for any switches not passed).
- Else use what's in the registry, if there are values in the registry.
- Else set all switches to `0` and write `0` to the registry for each switch

## Testing

Tested various scenarios with versions of the new hosting bundle across multiple Major.Minor.Patch versions, as well as how it interacts with previous Hosting Bundles without the Registry-writing behavior.

## Risk

In December all customers who get this update thru MU will get a 1-time hit where, regardless of what they already had installed, the hosting bundle will install all components. We suspect most customers install everything anyways, and those who don't will be able to work around this by manually re-running the installer with whatever switches they passed the last time they installed the bundle manually. Additionally, there could be a scenario that we didn't think of (and therefore wasn't covered by our manual testing) that will break.

### CODE REVIEW

**Comment by wtgodbe** [comment]
Test internal builds:
https://dev.azure.com/dnceng/internal/_build/results?buildId=1451524&view=results
https://dev.azure.com/dnceng/internal/_build/results?buildId=1451525&view=results (newer branding)

**Comment by dougbu** [comment]
optimistically updating the milestone

**Comment by wtgodbe** [comment]
New test builds:

https://dev.azure.com/dnceng/internal/_build/results?buildId=1452353&view=results
https://dev.azure.com/dnceng/internal/_build/results?buildId=1452352&view=results (newer branding)

**Comment by wtgodbe** [comment]
> candle.exe : error CNDL0351: Multiple source files ('.\Product.wxs', '.\Product.wxs') have resulted in the same output file 'D:\workspace\_work\1\s\artifacts\obj\HostOptions\Release\Product.wixobj'.  This is likely because the source files only differ in extension or path.  Rename the source files to avoid this problem. [D:\workspace\_work\1\s\src\Installers\Windows\HostOptions\HostOptions.wixproj]

The only other `Product.wxs` in 2.1 is https://github.com/dotnet/aspnetcore/blob/release/2.1/src/Installers/Windows/SharedFramework/Product.wxs - @joeloff  do I need to change the format of https://github.com/dotnet/aspnetcore/blob/38a1fcae783c42375785ef656ab451ecc408399b/src/Installers/Windows/HostOptions/HostOptions.wixproj#L21 in this branch?

**Comment by wtgodbe** [comment]
Never mind, I see `*.wxs` files are included automatically in all `.wixproj`'s. Removed the unneeded `Compile Include`

**Comment by wtgodbe** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=1452918&view=results
https://dev.azure.com/dnceng/internal/_build/results?buildId=1452917&view=results

**Comment by wtgodbe** [comment]
Had a typo in one of the conditions. New test builds:

https://dev.azure.com/dnceng/internal/_build/results?buildId=1453478&view=results
https://dev.azure.com/dnceng/internal/_build/results?buildId=1453484&view=results

**Review by joeloff — APPROVED** [review]

**Pull request merged**
