### PR TITLE
Use non-pinnable buffer for zero byte read

### PR DESCRIPTION
**Pull request by benaadams**
From https://github.com/aspnet/KestrelHttpServer/pull/3094

### CODE REVIEW

**Comment by Eilon** [comment]
@halter73 - you can merge this into the 2.2 patch branch, then it can get ported to master. This change was officially approved for 2.2.1 in shiproom today.

**Comment by Eilon** [comment]
@benaadams - thank you, of course! Sorry for the confusion earlier in the previous repo.

**Comment by benaadams** [comment]
@Eilon is there a 2.2.1 branch? Or should I submit this to 2.2 branch? (or let @halter73 sort it?)

**Comment by natemcmaster** [comment]
If this should go into 2.2.1, you should retarget the PR to the release/2.2 branch.

**Comment by benaadams** [comment]
Retargeted https://github.com/aspnet/AspNetCore/pull/4066

**Pull request closed without merging**
