### PR TITLE
Unescape query parameter name

### LINKED ISSUE #33394: QueryString key is not unescaped when value omitted
An incoming request with a query string that contains an escaped key without a value is not properly unescaped.

Example:

```http
GET http://localhost/api/demo?fields%5BtodoItems%5D HTTP/1.1
```

```c#
string keys = string.Join(' ', new HttpContextAccessor().HttpContext.Request.Query.Keys);
// keys: %5BtodoItems%5D
```

In contrast, when the query string does contain a value, it gets unescaped properly.

```http
GET http://localhost/api/demo?fields%5BtodoItems%5D=1 HTTP/1.1
```

```c#
string keys = string.Join(' ', new HttpContextAccessor().HttpContext.Request.Query.Keys);
// keys: [todoItems]
```

This bug applies to ASP.NET Core version: 3.1, 5.0 and the master branch.

The problem is caused by the next line:
https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Http/WebUtilities/src/QueryHelpers.cs#L221
which does not unescape. To fix, replace this line with:
```c#
string name = queryString.Substring(scanIndex, delimiterIndex - scanIndex);
accumulator.Append(Uri.UnescapeDataString(name.Replace('+', ' ')), string.Empty);
```

When this gets fixed, it would be great to also backport it to .NET Core 3.1 and 5.0.

### PR DESCRIPTION
**Pull request by campersau**
**PR Title**
Unescape query parameter name in QueryHelpers

**PR Description**
Unescapes the query parameter name when there is no value. This is already done when there was a value.

There are currently no test in QueryHelpersTests for testing encoded keys / values, should I add some more?

Fixes #33394

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]

**Comment by Tratcher** [comment]
> There are currently no test in QueryHelpersTests for testing encoded keys / values, should I add some more?

A little more test coverage would be appreciated.

**Comment by Tratcher** [comment]
Sorry, I just realized this conflicts with https://github.com/dotnet/aspnetcore/pull/32829/ that re-wrote a lot of this code to be more efficient. This bug still exists in that new code, so we'll prioritize getting that PR merged and then rebase this on top. Hold tight.

**Comment by Tratcher** [comment]
#32829 has been merged so this can now be rebased.

**Comment by campersau** [comment]
@Tratcher updated the new code path and added tests for it.

**Review by Tratcher — APPROVED** [review]

**Comment by Tratcher** [comment]
Thanks for getting back to this.

**Pull request merged**
