### PR TITLE
Update Selenium versions

### PR DESCRIPTION
**Pull request by dougbu**
- December edition

### CODE REVIEW

**Review by TanayParikh — APPROVED** [review]

**Review by wtgodbe — APPROVED** [review]
This updates more files than described in https://github.com/dotnet/aspnetcore-internal/blob/main/docs/operations/selenium_update.md - do we need to update the doc?

**Comment by dougbu** [comment]
> do we need to update the doc?

Probably. @dotnet/aspnet-blazor-eng do you agree❔

**Comment by TanayParikh** [comment]
> > do we need to update the doc?
> 
> Probably. @dotnet/aspnet-blazor-eng do you agree❔

Yep makes sense. May be simpler (and easier to keep current), if we just link this PR to demonstrate all the areas the version changes need to be made.

PS. CI timed out waiting for machine, re-running it.

**Comment by dougbu** [comment]
@TanayParikh how many jobs failed last time❔ It's generally a **Bad Idea:tm:** to rerun the entire pipeline unless either a new fix in the target branch is mandatory for the run to pass or almost all of the jobs failed

**Comment by TanayParikh** [comment]
> fix in the target branch is mandatory for the run to pass

`components-e2e` failed. This CI run was around the same time as I merged the `components-e2e` fix yesterday (so it may've been missing that fix). I did `azp run` to ensure a new merge commit was created and tested against.

**Comment by TanayParikh** [comment]
Hmm looks like a legitimate test failure based on the upgraded packages (failed to launch server).

**Comment by dougbu** [comment]
Problem here is the same as the last time I tried to update the main Selenium package versions. Issue appears to be code in the tests themselves.

``` text
[xUnit.net 00:00:02.44] Microsoft.AspNetCore.Components.E2ETests: Unrecognized option: -
[xUnit.net 00:00:02.44] Microsoft.AspNetCore.Components.E2ETests: Error: Could not create the Java Virtual Machine.
[xUnit.net 00:00:02.44] Microsoft.AspNetCore.Components.E2ETests: Error: A fatal exception has occurred. Program will exit.
[xUnit.net 00:00:02.45] Microsoft.AspNetCore.Components.E2ETests: 
[xUnit.net 00:00:02.45] Microsoft.AspNetCore.Components.E2ETests: > microsoft.aspnetcore.components.e2etest@0.0.1 selenium-standalone
[xUnit.net 00:00:02.45] Microsoft.AspNetCore.Components.E2ETests: > selenium-standalone "start" "--config" "/home/vsts/work/1/s/src/Shared/E2ETesting/selenium-config.json" "--javaArgs=-Dwebdriver.chrome.driver=/usr/local/share/chrome_driver/chromedriver" "--" "-port" "41665"
[xUnit.net 00:00:02.45] Microsoft.AspNetCore.Components.E2ETests: 
[xUnit.net 00:00:02.81] Microsoft.AspNetCore.Components.E2ETests: /home/vsts/work/1/s/src/Components/test/E2ETest/node_modules/selenium-standalone/lib/check-started.js:30
[xUnit.net 00:00:02.81] Microsoft.AspNetCore.Components.E2ETests:       throw new Error(
[xUnit.net 00:00:02.81] Microsoft.AspNetCore.Components.E2ETests:             ^
[xUnit.net 00:00:02.81] Microsoft.AspNetCore.Components.E2ETests: 
[xUnit.net 00:00:02.81] Microsoft.AspNetCore.Components.E2ETests: Error: Selenium exited before it could start with code 1
```

**Comment by dougbu** [comment]
@TanayParikh has there been a breaking change in the code we're using, especially a change in the `start` command syntax❔

Suspect the problem is at https://github.com/dotnet/aspnetcore/blob/main/src/Shared/E2ETesting/SeleniumStandaloneServer.cs#L107

**Comment by dougbu** [comment]
Not sure if I'm reading this correctly but it appears `javaArgs` are now supposed to be set via `opts.javaArgs`. If that can be done from the command line, perfect. Otherwise, may need to update the selenium-config.json file using environment variables in `SeleniumStandaloneServer` or perhaps do something in a project file. Could you please have a deeper look and try something @dotnet/aspnet-blazor-eng❔

**Comment by TanayParikh** [comment]
> has there been a breaking change in the code we're using, especially a change in the `start` command syntax❔

None that I'm aware of.



> Could you please have a deeper look and try something @dotnet/aspnet-blazor-eng❔

Is this a blocker? Can we upgrade everything else aside from `selenium-standalone` for now?

**Comment by HaoK** [comment]
@TanayParikh can I assign this PR to you to take point for getting this PR merged?

**Comment by TanayParikh** [comment]
I don't believe this needs to be a blocker. We should revert all the changes except the ones in `Versions.prop` and `src/Shared/E2ETesting/selenium-config.json` (ie. skip the `selenium-standalone` changes for now).

**Comment by HaoK** [comment]
Sigh, forks...  So i'll extract the handful of changes to a new branch without the standalone changes

**Comment by HaoK** [comment]
Replaced with https://github.com/dotnet/aspnetcore/pull/38788

**Pull request closed without merging**
