### PR TITLE
Tweak RunHelix.ps1 to work on DevBox

### PR DESCRIPTION
**Pull request by amcasey**
Microsoft DevBox sets the `NUGET_PACKAGES` environment variable to indicate that it has moved the packages out of the user's home directory.

### CODE REVIEW

**Comment by amcasey** [comment]
I'm a powershell novice, so let me know if this is unidiomatic.

**Review by halter73 — APPROVED** [review]
What version of powershell do we need to target for this script? In Powershell 7, `$env:NUGET_PACKAGES ??= "$env:HOMEPATH/.nuget/packages"` works, but it's probably safest to go with what we know will work everywhere.

**Comment by amcasey** [comment]
@halter73 I tried that first and it didn't work on my box, so I went with the older style.

**Review by BrennanConroy — APPROVED** [review]

**Review by wtgodbe — APPROVED** [review]

**Comment by wtgodbe** [comment]
Nice!

**Pull request merged**
