### PR TITLE
Use ModelOnly for Validation Summary

### PR DESCRIPTION
**Pull request by nj**
Previously when [Validation Summary](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-2.2#the-validation-tag-helpers) used `All`, it appended the property-related content to both the summary as well as the property specific span elements (= `asp-validation-for="..."`).

By switching to [`ModelOnly`](https://www.reddit.com/r/dotnet/comments/6st6j3/what_does_aspvalidationsummarymodelonly_mean/) it only show model-related messages in the summary (such as ["Invalid login attempt."](https://github.com/aspnet/AspNetCore/blob/c5bc96d/src/Identity/src/UI/Areas/Identity/Pages/V4/Account/Login.cshtml.cs#L147)) which was most likely the original intention.

### CODE REVIEW

**Comment by Eilon** [comment]
@mkArtakMSFT - for your consideration whether to take this.

cc @javiercn

**Comment by nj** [comment]
@mkArtakMSFT Giving this any thoughts? Anything that needs to be changed?

**Comment by nj** [comment]
@mkArtakMSFT Have merged latest master in, so it shows green (though it technically also was before)

**Comment by nj** [comment]
`/ping`

**Comment by mkArtakMSFT** [comment]
Hi @nj.
Just noticed this one. We usually try to work from issues and then after discussing whether a change makes sense or not, move to accepting/making a PR. This particular one seems to be a change in the IdentityUI, where we report the errors. @blowdart, @danroth27 would you like this change in the Identity UI?

**Comment by blowdart** [comment]
I defer to @HaoK and @javiercn on this and what the original intent was

**Comment by mkArtakMSFT** [comment]
Closing as there has been no activity on this PR for quite a while.

**Comment by nj** [comment]
🤦‍♂️

**Comment by mkArtakMSFT** [comment]
Actually, this one was a mistake. @HaoK this is awaiting your input.

**Review by HaoK — APPROVED** [review]
Looks reasonable

**Comment by mkArtakMSFT** [comment]
@HaoK let's get this merged post Preview 8 branching - sometime next week should be fine.

**Comment by pranavkm** [comment]
Thanks for the PR!

**Comment by nj** [comment]
@pranavkm Anytime :+1: 😃

**Pull request merged**
