### PR TITLE
Add/Modify Url Encoding/Decoding for IIS UrlRewrite

### LINKED ISSUE #5985: Add/Modify Url Encoding/Decoding for IIS UrlRewrite
I didn't implement UrlDecode, a server variable in IISUrlRewrite, because there wasn't a great library (or static method) to do it. Right now I'm using Uri.Encode for encoding, which doesn't have the best perf.

I think we can use Uri.EscapeDataString, but fundamentally I think this should be changed to a different library.

### PR DESCRIPTION
**Pull request by senbar**
Add Url encoding and modify url Encoding for IIS UrlRewrite

Add Segment Decode class using Uri.UnescapeDataString and plug it into Input Parser.
Modify Url Encode so that it uses Uri.DecodeDataString.

## Description

As was suggested I have changed Decode Data String to Unescape Data String which is recommended by docs. 
For Url Decoding I have used analogical function  UnescapeDataString. I have written unit tests for decoding covering opposite cases to encoding. I have also written tests for InputParser checking whether decode parameter goes into correct case and correct rule is added.

I wasn't sure if I was supposed to write performance tests since the motivation of changing from UrlEncode was that it's slow. If these test are desired I can add them.

Fixes #5985

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
Triage: Unfortunately `UnescapeDataString` isn't sufficient here because it's not context-aware and will unescape things that it shouldn't (such as %3F in the middle of a path).

We'll investigate and get back to you with a better approach.

**Comment by adityamandaleeka** [comment]
Note: we should also add a test with {QUERY_STRING} or some variable (see https://docs.microsoft.com/en-us/iis/extensions/url-rewrite-module/url-rewrite-module-configuration-reference#string-functions)

**Comment by senbar** [comment]
Ok, should I add such test for encode too?

**Comment by senbar** [comment]
> Note: we should also add a test with {QUERY_STRING} or some variable (see https://docs.microsoft.com/en-us/iis/extensions/url-rewrite-module/url-rewrite-module-configuration-reference#string-functions)

Thanks for suggestion, will do.

**Comment by senbar** [comment]
> Note: we should also add a test with {QUERY_STRING} or some variable (see https://docs.microsoft.com/en-us/iis/extensions/url-rewrite-module/url-rewrite-module-configuration-reference#string-functions)

Done

**Comment by adityamandaleeka** [comment]
@senbar Sorry to make you wait, we'll get to this in a couple of weeks.

**Comment by sebastienros** [comment]
I added the tests to ensure encoded query values are correctly encoded (the opposite of what we had to do in Orchard since they were for headers). The tests passed for me locally.

**Review by sebastienros — APPROVED** [review]

**Pull request merged**
