### PR TITLE
Workaround transitive Components.Analyzer dependency issue

### PR DESCRIPTION
**Pull request by mkArtakMSFT**
The root cause for this is https://github.com/dotnet/aspnetcore/issues/18563.
This workaround will be removed when the that issue is fixed in release/3.1.

Addresses https://github.com/dotnet/aspnetcore-internal/issues/3494

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
@pranavkm do you know whether there are other projects this should be added to?

**Review by pranavkm — APPROVED** [review]

**Comment by pranavkm** [comment]
I guess not (at least looking at the build failures)

**Comment by pranavkm** [comment]
I had a look at why the build was failing in those runs. It looks like we use the dotnet that's in the path rather than the version our build installs: https://github.com/dotnet/aspnetcore/blob/blazor-wasm/.azure/pipelines/blazor-daily-tests.yml#L24. This seems problematic.

**Comment by mkArtakMSFT** [comment]
> I had a look at why the build was failing in those runs. It looks like we use the dotnet that's in the path rather than the version our build installs: https://github.com/dotnet/aspnetcore/blob/blazor-wasm/.azure/pipelines/blazor-daily-tests.yml#L24. This seems problematic.

What is the recommended alternative?

**Comment by pranavkm** [comment]
We could run `restore.cmd` and then use the dotnet that it installs in the `repoRoot/.dotnet` directory?

**Comment by ajaybhargavb** [comment]
> We could run restore.cmd and then use the dotnet that it installs in the repoRoot/.dotnet directory?

We already run build.cmd which would create the .dotnet folder

We can just update the script to include a call to activate.sh. That will put the dotnet in repoRoot/.dotnet in path.
```yml
- script: |
  . ../../../../activate.sh
  dotnet test --filter "StandaloneAppTest"
  deactivate
```

**Comment by mkArtakMSFT** [comment]
> 
> 
> We could run `restore.cmd` and then use the dotnet that it installs in the `repoRoot/.dotnet` directory?

This looks a bit off of from what I planned to do here. If, however, @ajaybhargavb 's suggestion is the right think, I'll be happy to include in this PR. @pranavkm ?

**Comment by ajaybhargavb** [comment]
The tests fail even after this workaround, https://dev.azure.com/dnceng/internal/_build/results?buildId=526120&view=results. May be something else needs fixing, @pranavkm?

**Comment by ajaybhargavb** [comment]
The daily tests pipeline passed today even without this change https://dnceng.visualstudio.com/internal/_build?definitionId=738&_a=summary

**Comment by mkArtakMSFT** [comment]
I assume the patch fixes are now in. @pranavkm I'm not really sure whether we should continue with this change or not. Should I abandon this?

**Comment by pranavkm** [comment]
We haven't picked up the 3.1.3 in the blazor-wasm branch as yet

**Pull request closed without merging**
