### PR TITLE
Make RequestServices work for cloned longpolling HttpContext

### LINKED ISSUE #20846: Make RequestServices work for cloned longpolling HttpContext
Today we return an empty IServiceProvider, instead, we should create a new scope and stash it on the connection https://github.com/dotnet/aspnetcore/blob/162817d3f05f62b54589af553396525e03986679/src/SignalR/common/Http.Connections/src/Internal/HttpConnectionDispatcher.cs#L666.

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/dotnet/aspnetcore/issues/20846

### CODE REVIEW

**Comment by davidfowl** [comment]
@BrennanConroy I forgot to say, I made this change and had second thoughts 😄

**Comment by BrennanConroy** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by halter73** [comment]
> I forgot to say, I made this change and had second thoughts 😄

Care to elaborate? Was the change fragile for some reason?

**Comment by davidfowl** [comment]
> Care to elaborate? Was the change fragile for some reason?

I had a thought about "leaking" disposable transients resolved in the connection scope vs the hub scope.

**Comment by halter73** [comment]
We still use a per-invocation scope when activating Hubs, right?

Is the fear the people doing resolving a transient disposable via `Context.GetHttpContext().RequestServices` who would have previously experienced ODEs with long polling transport will now experience a "leak"? Wouldn't the "leaking" already be an issue for WebSockets or SSE.

**Comment by BrennanConroy** [comment]
Could you elaborate on the leaking problem?

**Comment by davidfowl** [comment]
> Is the fear the people doing resolving a transient disposable via Context.GetHttpContext().RequestServices who would have previously experienced ODEs with long polling transport will now experience a "leak"? Wouldn't the "leaking" already be an issue for WebSockets or SSE?

Yes exactly. But you're right, this just makes that leaking consistent 😄

**Review by halter73 — APPROVED** [review]

**Review by davidfowl — APPROVED** [review]

**Pull request merged**
