### PR TITLE
Utf8Json -> System.Text.Json

### PR DESCRIPTION
**Pull request by pranavkm**
|      Description |     RPS | CPU (%) | Memory (MB) | Avg. Latency (ms) | Startup (ms) | First Request (ms) | Latency (ms) | Ratio |
| ---------------- | ------- | ------- | ----------- | ----------------- | ------------ | ------------------ | ------------ | ----- |
|         Utf8Json | 407,353 |      69 |          39 |              0.76 |          304 |              50.27 |         0.62 |  1.00 |
| System.Text.Json | 403,295 |      70 |          40 |              0.72 |          305 |              56.17 |         0.43 |  0.99 |

### CODE REVIEW

**Comment by pranavkm** [comment]
@davidfowl \ @halter73

**Review by davidfowl — APPROVED** [review]

**Comment by pranavkm** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=177556

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2465

**Comment by davidfowl** [comment]
cc @sebastienros

**Pull request merged**
