### PR TITLE
In diffing, optimize unkeyed frames after keyed frames

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
This is a continuation of https://github.com/dotnet/aspnetcore/pull/40142, retaining the commit from @jirikanda.

Previously, the diffing system handled unkeyed-after-keyed frames in a legal way, but the diff output was suboptimal as it didn't retain the unkeyed components as often as it could. The PR #40142 improves the diffing output in this case.

After seeing the change in #40142, I found it hard to reason about why it was correct, as the new condition looked fairly arbitrary to me and I couldn't immediately intuit why we only wanted to check for this situation when it comes to deletions and not for insertions. I added another unit test for the insertion case and observed that the #40142 logic produced an optimal result, but it still wasn't obvious why we'd have this asymmetry in the logic.

To make this more maintainable in the future, I've broken up the key-based diffing logic in a different way. This is a lot more explicit now, has comments explaining each of the decisions, and turns out to be more symmetrical across both insertion and deletion. It also involves one fewer check at runtime, since several of the cases coalesce into an identical criterion.

I'm not saying it's easy to understand now, because there's still a lot going on, but I've spent hours thinking about how best to express this in code for human readability and it's the clearest I've got to.

### CODE REVIEW

**Comment by javiercn** [comment]
Looks great to me in general.

The only question that I have is if there is an impact when both things happen simultaneously.
```
<SomeUnkeyedComponent />
<Component @key="will delete"></Component>
<Component @key="will retain"></Component>
<SomeUnkeyedComponent />
```
->
```
<SomeUnkeyedComponent />
<Component @key="will retain"></Component>
<Component @key="will insert"></Component>
<SomeUnkeyedComponent />
```

Will this result in an edit operation + Permute? Or will it result in delete + insert

**Comment by SteveSandersonMS** [comment]
That case would result go like this:

1. SomeUnkeyedComponent vs SomeUnkeyedComponent => match, leave them alone
2. `will delete` vs `will retain` => reaches the `newKeyIsInOldTree ? DiffAction.Delete : DiffAction.Insert` criterion and picks `Delete`
3. `will retain` vs `will retain` => match, leave them alone
4. SomeUnkeyedComponent  vs `will insert` => reaches the `newKeyIsInOldTree ? DiffAction.Delete : DiffAction.Insert` criterion and picks `Insert`
5. SomeUnkeyedComponent  vs SomeUnkeyedComponent  => match, leave them alone

So it would be delete then insert.

**Comment by javiercn** [comment]
@SteveSandersonMS thanks for the clarification.

Does Edit + Permute make sense here? Is it a worthy optimization? (I'm assuming reusing components is generally worth it) Is it possible for us to do it, or is it a complete different beast.

**Comment by SteveSandersonMS** [comment]
No, edit+permute would be an illegal outcome here. The `@key` directive attribute specifically requires component instances to be retained if and only if the key matches.

**Comment by javiercn** [comment]
Thanks again for clarifying, it's been a while and these things are tricky

**Review by javiercn — APPROVED** [review]
Great addition!

**Pull request merged**
