### PR TITLE
Accessibility for ReactRedux

### PR DESCRIPTION
**Pull request by ryanbrandenburg**
Somehow these contrast changes didn't make it into ReactRedux (might have had a bad rebase? Or just general oversight.)

This is basically exactly what we do in React.

### CODE REVIEW

**Comment by ryanbrandenburg** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=238933

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2314

**Comment by ryanbrandenburg** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=238934

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2489

**Review by danroth27 — APPROVED** [review]

**Pull request merged**
