### PR TITLE
Upgrade yarn dependencies

### PR DESCRIPTION
**Pull request by MackinnonBuck**
Upgraded:
* `src/Components/Web.JS/yarn.lock`
* `src/SignalR/clients/ts/signalr/yarn.lock`

By running `yarn upgrade`

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Review by mkArtakMSFT — APPROVED** [review]

**Comment by MackinnonBuck** [comment]
```text
An unexpected error occurred: "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public-npm/npm/registry/@babel/core/-/core-7.25.2.tgz: Request failed \"401 Unauthorized\""
```

@wtgodbe Do you know why this might happen? Is there another step required for CI when updating Yarn lockfiles? This doesn't happen when I install packages locally.

**Comment by wtgodbe** [comment]
Not sure, I would've thought that if anything, doing a local restore pre-build would pull in the package to our feed. Maybe update the relevant package.json's as well, just in case? If not, maybe someone from @dotnet/dnceng would know more about authenticating to the npm feed

**Comment by dougbu** [comment]
you need to run `vsts-npm-auth.cmd -config $PWD\.npmrc` or similar (if not in Powershell) to authorize yourself before using `yarn upgrade`. probably best to clean out `npm` caches and related folders first. IIRC auth basically switches from letting you pull from the upstream source to pulling from the upstream _and_ updating the `dotnet-public-npm` feed

**Comment by javiercn** [comment]
@wtgodbe should we consider backporting a bunch of the changes we did in this area in the 9.0 timeframe to 8.0?

It would definitely be easier if we could rely on the same infrastructure and just backport updates.

**Comment by wtgodbe** [comment]
> should we consider backporting a bunch of the changes we did in this area in the 9.0 timeframe to 8.0?

> It would definitely be easier if we could rely on the same infrastructure and just backport updates.

I'm on board with it if it makes npm updates easier. Which changes did you have in mind?

**Comment by javiercn** [comment]
> > should we consider backporting a bunch of the changes we did in this area in the 9.0 timeframe to 8.0?
> 
> > It would definitely be easier if we could rely on the same infrastructure and just backport updates.
> 
> I'm on board with it if it makes npm updates easier. Which changes did you have in mind?

Getting rid of all the yarn related stuff + centralized NPM

**Comment by MackinnonBuck** [comment]
Hm, still no luck (getting the same "401 Unauthorized" error). I did:
```text
git clean -fdx
npm cache clean --force
vsts-npm-auth.ps1 -config .\.npmrc -F
```

Then from each folder with a `yarn.lock`:
```
yarn upgrade
```

**Comment by MackinnonBuck** [comment]
Looks like #56677 already covered this.

**Pull request closed without merging**
