### PR TITLE
Remove flaky test

### PR DESCRIPTION
**Pull request by BrennanConroy**
Port https://github.com/aspnet/AspNetCore/pull/15269 to release/3.1

### CODE REVIEW

**Comment by BrennanConroy** [comment]
cc @Pilchie as FYI

**Review by halter73 — APPROVED** [review]

**Comment by halter73** [comment]
On a semi-related note, I just saw the test directly following these two fail in master: https://github.com/aspnet/AspNetCore/pull/13947#issuecomment-548589798 😢

**Comment by BrennanConroy** [comment]
Aww :( looks like it is relying on similar racy behavior

**Comment by BrennanConroy** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=410488&view=logs

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/3318

**Pull request merged**
