### PR TITLE
Updating minimum required VS version to 16.2

### PR DESCRIPTION
**Pull request by mkArtakMSFT**
Addresses #10421

### CODE REVIEW

**Review by mkArtakMSFT — COMMENTED** [review]
@rynowak, @NTaylorMullen if I want to target VS 16.2, should I also update the Prerequisite for `Microsoft.VisualStudio.Component.Web` to the same version too? (see line 23)

**Comment by NTaylorMullen** [comment]
> @rynowak, @NTaylorMullen if I want to target VS 16.2, should I also update the Prerequisite for `Microsoft.VisualStudio.Component.Web` to the same version too? (see line 23)

As of today we don't technically require a newer version of them (they haven't made any changes to require that). However, in practice they will always be 16.2+ so it doesn't hurt.

**Review by NTaylorMullen — APPROVED** [review]

**Comment by rynowak** [comment]
Make sure you test this, by doing a build and then double-clicking the VSIX and going through the whole install process.

**Comment by mkArtakMSFT** [comment]
Sure, I've done that already, @rynowak.

**Comment by mkArtakMSFT** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=198009&view=ms.vss-test-web.build-test-results-tab

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2559

**Pull request merged**
