### PR TITLE
Update branding to 3.1.2

### PR DESCRIPTION
**Pull request by JunTaoLuo**
Waiting until branches open.

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
With the "wait" caveat, looks good

@Pilchie should we also prep for 2.1.16 and perhaps 3.0.3?

**Comment by dougbu** [comment]
This doesn't seem to be building and the baseline changes look incomplete. Are we waiting for dotnet/extensions publication as in 3.0?

**Comment by JunTaoLuo** [comment]
Ready to go @dougbu @wtgodbe

**Review by wtgodbe — APPROVED** [review]

**Comment by dougbu** [comment]
Does this PR need a CodeCheck fix too?

**Pull request merged**
