### PR TITLE
Update Microsoft.Data.SqlClient

### PR DESCRIPTION
**Pull request by BrennanConroy**
Update SqlClient dependency to resolve a data corruption issue.

@Pilchie

### CODE REVIEW

**Review by JunTaoLuo — APPROVED** [review]

**Comment by Pilchie** [comment]
This was approved by tactics.

**Comment by Pilchie** [comment]
@BrennanConroy can you verify the helix failures are not related?

**Comment by BrennanConroy** [comment]
Failures look unrelated, I'll let RAAS triage them

**Comment by BrennanConroy** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=345861&view=ms.vss-test-web.build-test-results-tab&runId=10355866&resultId=109054&paneView=debug

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/3094

**Comment by BrennanConroy** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=345861&view=logs

**Pull request merged**
