### PR TITLE
[SignalR TS] Set keep alive timer in receive loop

### PR DESCRIPTION
**Pull request by BrennanConroy**
A potential fix we can make for https://github.com/dotnet/aspnetcore/issues/31079

By setting the timeout in the receive loop we are avoiding chained timers and making a timer on a network call. This should in theory avoid the chrome timer throttling.

The downside is that if you set the client-side keep alive interval to a value smaller than the server-side keep alive interval you will only send at the same rate as the server-side interval.

### CODE REVIEW

**Comment by halter73** [comment]
Here's the similar PR in the SignalR/SignalR repo for reference: https://github.com/SignalR/SignalR/pull/4544

I'll also try to see if I can repro the issue.

**Comment by jahmai-ca** [comment]
@BrennanConroy I can reproduce this issue easily in our product. Are there any plans to release this as a preview that I can test?

**Comment by mgazell** [comment]
Hi @BrennanConroy ,

Thanks for making the fix. Assuming that it gets merged and tested, when do you anticipate it going live?

**Comment by jahmai-ca** [comment]
FYIW we've created a package from source and tested this with positive results. There are some tests failing which I believe are due to the tests now being out-dated.

**Comment by BrennanConroy** [comment]
> FYIW we've created a package from source and tested this with positive results

Thanks for the confirmation 👍 

I've also tested the change and kept a connection open for multiple days (instead of a couple minutes), so looks like this works.

> Assuming that it gets merged and tested, when do you anticipate it going live?

We have previews roughly every month. And nightlies available at https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json
For npm `registry=https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/npm/registry/`, although that doesn't have the npm artifacts right now, so I'll look at getting that changed.

**Review by halter73 — APPROVED** [review]

**Pull request merged**
