### PR TITLE
feat: Add StringSyntaxAttribute for guid and timespan args

### PR DESCRIPTION
**Pull request by abc516**
#44535 (GuidFormat and TimeSpanFormat)

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Description

Adds the StringSyntaxAttribute for guid and timespan string function parameters, to specify syntax adherence.
Specifically, for the guid params, it adds it to all references of the [SignalR Hub ConnectionId param](https://learn.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server#how-to-get-information-about-the-client-from-the-context-property) and Kestrel Web Server ConnectionID .

### CODE REVIEW

**Comment by abc516** [comment]
@BrennanConroy I can remove them from the Http/Kestrel Server references. Do you have any recommendations to where I can put them GuidFormat usages?

**Comment by BrennanConroy** [comment]
> Do you have any recommendations to where I can put them GuidFormat usages?

There might not be any.

**Comment by davidfowl** [comment]
I understand why this could be useful for the developers in this code base, but it doesn't seem like there's a big value in having these throughout internal and private methods in the code base.

**Comment by danmoseley** [comment]
Based on the notes above, and this has sat for a while, I'm going to close. Thanks @abc516 for the contribution.

**Pull request closed without merging**
