### PR TITLE
Allow HubConnectionBuilder to build multiple HubConnection

### LINKED ISSUE #11567: Allow multiple calls to HubConnectionBuilder.Build
Right now we, somewhat arbitrarily, stop you from calling `HubConnectionBuilder.Build` more than once. We should consider allowing multiple calls. It makes it easier to "recreate" connections from scratch.

We should do a little historical investigation as to why we didn't do this in the first place.

### PR DESCRIPTION
**Pull request by Kahbazi**
Fixes #11567

### CODE REVIEW

**Comment by anurse** [comment]
We should consider the comment you posted in the issue thread (https://github.com/aspnet/SignalR/pull/1830#discussion_r179028857). The `HubConnection` itself is a singleton in the DI container so calling `Build` multiple times won't change anything. Plus, if you want to "reconfigure" the builder it could mess with existing instances.

I think there's a viable way forward, but we should discuss a bit to see what makes sense.

**Comment by Kahbazi** [comment]
I think since the `Build` method is creating a new `IServiceProvider`, the changes on the `ServiceCollection` won't affect the previous `HubConnection`s. 

https://github.com/aspnet/AspNetCore/blob/0d9a030b4857582607b537fb423cb22103384250/src/SignalR/clients/csharp/Client.Core/src/HubConnectionBuilder.cs#L37

**Comment by anurse** [comment]
Ah yes, I think you're right. We keep the service collection around but not the provider. The only concern is in places where we `TryAdd` or `TryAddEnumerable` to the `IServiceCollection` (which is, I think, kept around between `Build()`s). Those may not work properly. `TryAdd` is idempotent and doesn't add a service if there is already one registered for a given interface. `TryAddEnumerable` is similar in that it doesn't add if there's a service with the same implementation type registered for an interface.

**Comment by Kahbazi** [comment]
Well the main question here is when `HubConnectionBuilder` should be used to create multiple `HubConnection`. and I think the answer is when it is for the same config. 
 Because the code right now is not ready for multiple configs. For example one might use `WithUrl` and `WithEndPoint` on one instance of a `HubConnectionBuilder` and expect to get both connection type but will always get the first one.

```
HubConnectionBuilder hubConnectionBuilder = new HubConnectionBuilder();
hubConnectionBuilder.WithUrl(...);
var connection1 = hubConnectionBuilder. Build(); // using url

hubConnectionBuilder.WithEndPoint();
var connection2 = hubConnectionBuilder. Build();// also using url

```

But if we want to use `HubConnectionBuilder` with different config perhaps one solution could be to remove all `ServiceDescriptor` for `IConnectionFactory` and `EndPoint` in `WithEndPoint` and `WithUrl` methods before registering new one.

**Comment by anurse** [comment]
I guess one thing we need to do is go back to understand the scenario that motivated this. I filed the issue, so I expect it was part of something we were discussing as a team in one of our triage meetings. I'm not sure that we've heard much from customers who want this feature. Understanding if a customer wants this feature and if so, _why_ they want this feature might help.

It might be best for us to hold on making a change like this until we have a customer asking for it.

**Comment by jkotalik** [comment]
@Kahbazi I'm going to close this PR for now as you "liked" @anurse comment.

**Pull request closed without merging**
