### PR TITLE
Exclude some .wxl files from localization

### PR DESCRIPTION
**Pull request by dougbu**
- preparing for dotnet/arcade#10383 merge and migration to this repo
- without this, `OneLocBuild` will generate multiple unused translation files

### CODE REVIEW

**Comment by dougbu** [comment]
Oh, found an example LocExclusions.json file and the syntax is incorrect here. One moment...

**Review by jonfortescue — APPROVED** [review]
Looks good!

**Comment by dougbu** [comment]
@cristianosuzuki77 is there something I can do in source files like https://github.com/dotnet/aspnetcore/blob/main/src/Installers/Windows/SharedFrameworkBundle/thm.wxl to inform the loc team that most of the strings have existing translations❔ Might we worth including in this PR so we're ready.

I suggest validating what's already here of course.

**Comment by dougbu** [comment]
> @cristianosuzuki77 is there something I can do in source files like https://github.com/dotnet/aspnetcore/blob/main/src/Installers/Windows/SharedFrameworkBundle/thm.wxl to inform the loc team that most of the strings have existing translations❔ Might we worth including in this PR so we're ready.

Will do this separately if it's possible

**Pull request merged**
