### PR TITLE
Remove localization segment

### PR DESCRIPTION
**Pull request by guardrex**
https://github.com/aspnet/Docs/pull/10789#discussion_r253707591

### CODE REVIEW

**Comment by davidfowl** [comment]
What about the other templates?

**Comment by guardrex** [comment]
It's in a few README files but not in template code that renders output.

**Comment by pranavkm** [comment]
@guardrex could you resolve the merge conflict if this PR is still valid?

**Comment by guardrex** [comment]
I must have deleted by fork for some reason. I'll reconstitute this tomorrow (Saturday) morning.

**Pull request closed without merging**
