### PR TITLE
Update SDK to 9.0.100-alpha.1.23421.9

### PR DESCRIPTION
**Pull request by halter73**

### CODE REVIEW

**Comment by halter73** [comment]
> .dotnet/sdk/8.0.100-rc.1.23407.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1210: (NETCORE_ENGINEERING_TELEMETRY=Restore) IsAotCompatible is not supported for the target framework. Consider multi-targeting to a supported framework to enable ahead-of-time compilation analysis, and set IsAotCompatible only for the supported frameworks. For example:
<IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">true</IsAotCompatible>

Both this and the [efcore SDK update PR](https://github.com/dotnet/efcore/pull/31423) are failing to build with this NETSDK1210 error. All of our `IsAotCompatible`/`IsTrimmable` projects that have non-`net8.0` targets (so `netstandard2.0` and `net462`) fail to build with this error with this SDK update. I'm not sure what change triggered it.

Assuming that these NETSDK1210 is legitament. I could update all our `<IsTrimmable>` usage to be `<IsTrimmable Condition="'$(TargetFramework)' == '$(DefaultNetCoreTargetFramework)'">` or perhaps use `$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)`, $(DefaultNetCoreTargetFramework)))` like the error message suggests, but that would be noisy and might mess up the LinkabilityChecker.

**Comment by wtgodbe** [comment]
@sbomer are you aware of any relevant recent changes?

**Comment by JamesNK** [comment]
> .dotnet/sdk/8.0.100-rc.1.23407.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1210: (NETCORE_ENGINEERING_TELEMETRY=Restore) IsAotCompatible is not supported for the target framework. Consider multi-targeting to a supported framework to enable ahead-of-time compilation analysis, and set IsAotCompatible only for the supported frameworks. For example:
true

We don't have `IsAotCompatible` property anywhere in our source code. Is it implicitly set to true when `PublishAot` is true?

It's confusing to have an error message about a property that isn't present in source code. SDK should complain about `PublishAot` if it is what is set.

@eerhardt

**Comment by halter73** [comment]
The Windows build servers are also failing with a seemingly unrelated error when trying to build some ANCM vcxproj's:

> Directory.Build.props(95,31): error MSB4242: (NETCORE_ENGINEERING_TELEMETRY=Restore) SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildSdkResolver" failed while attempting to resolve the SDK "Microsoft.DotNet.Arcade.Sdk". Exception: "System.IO.FileNotFoundException: Could not find file 'D:\a\_work\1\s\.dotnet\sdk-manifests\8.0.100-rc.1\microsoft.net.workload.emscripten.current\WorkloadManifest.json'.
File name: 'D:\a\_work\1\s\.dotnet\sdk-manifests\8.0.100-rc.1\microsoft.net.workload.emscripten.current\WorkloadManifest.json'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.<>c__DisplayClass7_0.<GetManifests>b__0()
   at Microsoft.NET.Sdk.WorkloadManifestReader.ReadableWorkloadManifest.OpenManifestStream()
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.LoadManifestsFromProvider(IWorkloadManifestProvider manifestProvider)
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.Create(IWorkloadManifestProvider manifestProvider, String dotnetRootPath, String sdkVersion, String userProfileDir)
   at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.CachingWorkloadResolver.Resolve(String sdkReferenceName, String dotnetRootPath, String sdkVersion, String userProfileDir)
   at Microsoft.DotNet.MSBuildSdkResolver.DotNetMSBuildSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext context, SdkResultFactory factory)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.TryResolveSdkUsingSpecifiedResolvers(IList`1 resolvers, Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio, SdkResult& sdkResult, IEnumerable`1& errors, IEnumerable`1& warnings)""

I'm not sure why ANCM would need an emscripten workload or why it's missing.

**Comment by eerhardt** [comment]
> > .dotnet/sdk/8.0.100-rc.1.23407.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1210: (NETCORE_ENGINEERING_TELEMETRY=Restore) IsAotCompatible is not supported for the target framework. Consider multi-targeting to a supported framework to enable ahead-of-time compilation analysis, and set IsAotCompatible only for the supported frameworks. For example:
> > true
> 
> We don't have `IsAotCompatible` property anywhere in our source code. Is it implicitly set to true when `PublishAot` is true?
> 
> It's confusing to have an error message about a property that isn't present in source code. SDK should complain about `PublishAot` if it is what is set.
> 
> @eerhardt

@sbomer - I believe this is caused by https://github.com/dotnet/sdk/pull/34077. Can you take a look?

**Comment by halter73** [comment]
We're still getting the following error I mentioned yesterday:

> Directory.Build.props(95,31): error MSB4242: (NETCORE_ENGINEERING_TELEMETRY=Restore) SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildSdkResolver" failed while attempting to resolve the SDK "Microsoft.DotNet.Arcade.Sdk". Exception: "System.IO.FileNotFoundException: Could not find file 'D:\a\_work\1\s\.dotnet\sdk-manifests\8.0.100-rc.1\microsoft.net.workload.emscripten.current\WorkloadManifest.json'

I noticed there was a workload-related failure in the last SDK update (https://github.com/dotnet/aspnetcore/pull/49761) for a different wasm linking workload, but that seems to have had a different cause. Does anyone know what's going on here? @radical @lewing @joeloff @marcpopMSFT

**Comment by joeloff** [comment]
> We're still getting the following error I mentioned yesterday:
> 
> > Directory.Build.props(95,31): error MSB4242: (NETCORE_ENGINEERING_TELEMETRY=Restore) SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildSdkResolver" failed while attempting to resolve the SDK "Microsoft.DotNet.Arcade.Sdk". Exception: "System.IO.FileNotFoundException: Could not find file 'D:\a_work\1\s.dotnet\sdk-manifests\8.0.100-rc.1\microsoft.net.workload.emscripten.current\WorkloadManifest.json'
> 
> I noticed there was a workload-related failure in the last SDK update (#49761) for a different wasm linking workload, but that seems to have had a different cause. Does anyone know what's going on here? @radical @lewing @joeloff @marcpopMSFT

Do you know which workloads are present? Wasm has a dependency on EMSDK and that should get installed as part of installing wasm-tools.

**Comment by halter73** [comment]
> Do you know which workloads are present? Wasm has a dependency on EMSDK and that should get installed as part of installing wasm-tools.

I just ran restore.cmd before and after this SDK update and I noticed a difference to the location where emscripten's WorkloadManifest.json is installed. Before it was `.dotnet\sdk-manifests\8.0.100-rc.1\microsoft.net.workload.emscripten.current\WorkloadManifest.json`, but after the SDK update it's `.dotnet\sdk-manifests\8.0.100-rc.1\microsoft.net.workload.emscripten.current\8.0.0-rc.1.23377.1\WorkloadManifest.json`.

Noticed the new `8.0.0-rc.1.23377.1` directory between `microsoft.net.workload.emscripten.current` and `WorkloadManifest.json`. And this change isn't limited to just the emscripten workload. It's now like that for every 8.0.100-rc.1 sdk-manifest albiet with different version numbers.

Is this intentional?

**Comment by joeloff** [comment]
It is intentional. The new path is related to workload sets (version and grouping) that's being introduced. @dsplaisted as an FYI

**Comment by marcpopMSFT** [comment]
Are you building using VS/fullframework and what version of VS is used in the builds? We had to make a fix in 17.7-preview5 and it just released 17.7.0 today which may affect this. Can you update to a preview image of VS?

**Comment by halter73** [comment]
This definitely has something to do with this SDK update and not just the environment considering the main branch and other PRs are still building fine. The latest failing Build.native.binlog for Windows_Test_Logs shows `MSBuild version = "17.6.3+07e294721"`.

This is the first SDK update that the aspnetcore repo has consumed where the `WorkloadManifest.json` files have been moved to a versioned subfolder, and this appears to be causing arcade's `_IsProjectRestoreSupported` target to fail for all of our ANCM vcxproj's.

Is MSBuild version 17.6.3 is too old to get the latest changes to SdkDirectoryWorkloadManifestProvider that cause it to look in versioned subfolders for the workload manifests? How do we update it?

@dsplaisted

**Comment by joeloff** [comment]
I believe you need 17.7 and the only way to get that is to move to a different OS image.

**Comment by halter73** [comment]
Since this is failing in the azure pipeline before we get the chance to see how this affects our helix tests, should I update default-build.yml here?

https://github.com/dotnet/aspnetcore/blob/0b35f03ec3909b6c71651e037e52a7c4b4b6f7b0/.azure/pipelines/jobs/default-build.yml#L124-L131

It looks like we're currently using `1es-windows-2022` and `1es-windows-2022-open`. What should we be using?

Will Helix.Common.props need a similar update?

**Comment by marcpopMSFT** [comment]
We use Windows.Amd64.VS2022.Pre.Open for our test runs which pulls in preview versions of VS. For our builds, we don't use full framework so use the same images that you use. Not sure if there is a version with VS as an alternative.

**Comment by halter73** [comment]
We queue jobs to more than just Windows.Amd64.VS2022.Pre.Open:

https://github.com/dotnet/aspnetcore/blob/12b48e62f6ea7ca37ebc579f871601bb0e5938db/eng/targets/Helix.Common.props#L33-L34

I'm not sure if the additional Windows Helix queues will be an issue, but first we need to figure out how to get arcade working on the dnceng 1ES agent pools. Right now, it looks like every job using a Windows AzDO agent is failing with this workload resolution error.

**Comment by wtgodbe** [comment]
We only need to update https://github.com/dotnet/aspnetcore/blob/0b35f03ec3909b6c71651e037e52a7c4b4b6f7b0/.azure/pipelines/jobs/default-build.yml#L124-L131 for now, since the error is just in the build. The tests may be OK. Let's start with that, and additionally run https://dev.azure.com/dnceng-public/public/_build?definitionId=85 against this PR to make sure _all_ our windows test queues are fine. If not we can update those too.

**Comment by wtgodbe** [comment]
One sec, let me figure out what to update to

**Comment by wtgodbe** [comment]
Helix-matrix: https://dev.azure.com/dnceng-public/public/_build/results?buildId=368490&view=results

**Comment by wtgodbe** [comment]
Looks like `windows.vs2022preview.amd64.open` doesn't have 17.7 yet. @dotnet/dnceng is there an image we can use that will have 17.7, outside of the scouting one? I'd prefer waiting to update the SDK over using the scout queue for our official builds

**Comment by dougbu** [comment]
> Looks like `windows.vs2022preview.amd64.open` doesn't have 17.7 yet.

Those machines have 17.7 preview 3. `windows.vs2022preview.scout.amd64[open]` machines have preview 4. We normally don't scout a new version until it's been out for about a month. Since 17.7 GA shipped 8 August, that would mean our machines should first see it in an early September rollout.

@wtgodbe are you asking for an exception to our usual rollout schedule❔

/cc @ilyas1974

**Comment by wtgodbe** [comment]
> @wtgodbe are you asking for an exception to our usual rollout schedule❔

Hmm, no, I don't think that's necessary here. If it'll be until September, I guess it's better to use the scouting queue until then, rather than blocking SDK updates during the RC1 build. I'll update the PR and, if it works, file an issue against myself to revert usage of the scouting queue in September.

**Comment by wtgodbe** [comment]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=368641&view=results

**Comment by wtgodbe** [comment]
> D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\InstallDotNetCore.targets(15,5): error MSB4018: The "InstallDotNetCore" task failed unexpectedly. [D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\Tools.proj]
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\InstallDotNetCore.targets(15,5): error MSB4018: System.MissingMethodException: Method not found: 'System.Text.Json.JsonDocument System.Text.Json.JsonDocument.Parse(System.ReadOnlyMemory`1<Byte>, System.Text.Json.JsonDocumentOptions)'. [D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\Tools.proj]
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\InstallDotNetCore.targets(15,5): error MSB4018:  [D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\Tools.proj]
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\InstallDotNetCore.targets(15,5): error MSB4018: Server stack trace:  [D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\Tools.proj]
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\InstallDotNetCore.targets(15,5): error MSB4018:    at Microsoft.DotNet.Arcade.Sdk.InstallDotNetCore.Execute() [D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\Tools.proj]
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\InstallDotNetCore.targets(15,5): error MSB4018:    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs) [D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\Tools.proj]
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\InstallDotNetCore.targets(15,5): error MSB4018:    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg) [D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\Tools.proj]
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\InstallDotNetCore.targets(15,5): error MSB4018:  [D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\Tools.proj]
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\InstallDotNetCore.targets(15,5): error MSB4018: Exception rethrown at [0]:  [D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\Tools.proj]
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\InstallDotNetCore.targets(15,5): error MSB4018:    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg) [D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\Tools.proj]
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\InstallDotNetCore.targets(15,5): error MSB4018:    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type) [D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\Tools.proj]
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\InstallDotNetCore.targets(15,5): error MSB4018:    at Microsoft.Build.Framework.ITask.Execute() [D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\Tools.proj]
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\InstallDotNetCore.targets(15,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\Tools.proj]
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\InstallDotNetCore.targets(15,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\Tools.proj]
##[error].packages\microsoft.dotnet.arcade.sdk\8.0.0-beta.23404.2\tools\InstallDotNetCore.targets(15,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) The "InstallDotNetCore" task failed unexpectedly.

We see this locally when devs haven't installed the correct VS components (native toolsets, Windows SDKs, etc), looks like the scouting queue doesn't have everything we need. We may be blocked on this update without any build pools that work for us

**Comment by dsplaisted** [comment]
> System.MissingMethodException: Method not found: 'System.Text.Json.JsonDocument System.Text.Json.JsonDocument.Parse(System.ReadOnlyMemory`1, System.Text.Json.JsonDocumentOptions)'.

It seems weird that it would fail in that way because the correct VS components aren't installed.  What components do you think need to be installed?  Is there a way to update the VS components that are installed in one of the build queues?

**Comment by wtgodbe** [comment]
I don't know exactly what missing/mismatched component causes this to happen, but devs see this exact symptom pretty frequently locally when they need to update VS (based on our .vsconfig: https://github.com/dotnet/aspnetcore/blob/main/.vsconfig)

**Comment by marcpopMSFT** [comment]
I have a new suggestion I just tested out. While the SDK includes the SxS manifests that requires a new VS to read, our install doesn't support that yet. If you run `dotnet workload update` with a feed that includes workload manifests in it (which the dotnet8 public feed does) it should update the manifests back to the old format (even though it won't install any workloads).  Only risk is if you target the dotnet8 feed, you could pick up mismatches between runtime/emsdk when there are updates.

Would that be a temporary option here until the VS images have been updated?

**Comment by wtgodbe** [comment]
> Would that be a temporary option here until the VS images have been updated?

It doesn't look like it - if I try running that command before the build, it'll fail because the version of `dotnet` from global.json isn't installed yet. And the failure happens during the [InstallDotNetCore](https://github.com/dotnet/arcade/blob/0a5c7d6f73fbd46568986bf6ff3ea37130d208ca/src/Microsoft.DotNet.Arcade.Sdk/tools/InstallDotNetCore.targets#L5-L22) target from Arcade, so there's nowhere to hook a target in between dotnet getting installed & the failure occurring - I'm not sure what else we can do to get the SDK updated without a machine pool available that has what we need on it

**Comment by captainsafia** [comment]
> > Would that be a temporary option here until the VS images have been updated?
> 
> It doesn't look like it - if I try running that command before the build, it'll fail because the version of `dotnet` from global.json isn't installed yet. And the failure happens during the [InstallDotNetCore](https://github.com/dotnet/arcade/blob/0a5c7d6f73fbd46568986bf6ff3ea37130d208ca/src/Microsoft.DotNet.Arcade.Sdk/tools/InstallDotNetCore.targets#L5-L22) target from Arcade, so there's nowhere to hook a target in between dotnet getting installed & the failure occurring - I'm not sure what else we can do to get the SDK updated without a machine pool available that has what we need on it.

I ended up reverting the `dotnet workload update` command since that didn't work so we're back to resolving the issue with `DotNetInstallCore` failing due to a missing method exception.

I wonder if we should trigger the update on CI the same way devs do locally by calling the `InstallVisualStudio` script with the `passive` and `quiet` flags set? It might tide us over until the official images are updated.

Also, it strikes me as odd that a VS update is what resolves this issue (even locally) because I can't quite pinpoint _why_. There might be a side effect the installation is applying here that is resolving the actual issue.

Also, the underlying `InstallDotNetCore` code hasn't changed in 4 years, but the issue has only happened within the last 2 months so there might be another confounding factor here...

**Comment by dougbu** [comment]
our rollout completed already this morning. VS2022 17.8 preview 1 is now available on `windows.vs2022preview.scout.amd64[.open]` images in our build pools. you might want to give those images a try. if the switch doesn't work, please make an explicit request for us to speed up moving to 17.7 GA on `windows.vs2022.scout.amd64[.open]` images.

**Comment by halter73** [comment]
> if the switch doesn't work, please make an explicit request for us to speed up moving to 17.7 GA on windows.vs2022.scout.amd64[.open] images.

I doesn't look like the update to the preview scouting images worked. How do we make an explicit request to speed up moving to 17.7 GA on the non-preview scout images?

**Comment by dougbu** [comment]
> How do we make an explicit request to speed up moving to 17.7 GA on the non-preview scout images?

@ilyas1974 do you need an email or is this sufficient❔

/btw https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md describes what's on the `1es-windows-2022` machines. we essentially put a thin wrapper on the Azure hosted image. it currently has VS 17.6.

> What's the difference?

no idea. we have limited understanding of the problems discussed in this PR. further, it's also weird to imagine 17.7 GA solving a problem that continues into 17.8p1.

**Comment by captainsafia** [comment]
To make things a little bit more interesting, it appears that the PR merging release/8.0 -> main, which contains the SDK update, does not have any of the failures that we are seeing here: https://github.com/dotnet/aspnetcore/pull/50281.

Perhaps using the preview image pool here wasn't the right idea.

In any case, I'm inclined to let the forward port PR linked above flow and then try another SDK update after that....

**Comment by wtgodbe** [comment]
> To make things a little bit more interesting, it appears that the PR merging release/8.0 -> main, which contains the SDK update, does not have any of the failures that we are seeing here: https://github.com/dotnet/aspnetcore/pull/50281.

> Perhaps using the preview image pool here wasn't the right idea.

> In any case, I'm inclined to let the forward port PR linked above flow and then try another SDK update after that....

I think this is because the breaking change is in `main` but not `8.0` in the SDK - we'll still be blocked on going to a 9.0 SDK until we can get images with 17.7. @ilyas1974 is there any update on that?

**Comment by garath** [comment]
> @ilyas1974 is there any update on that?

No updates yet.

Highlighting a point @dougbu made:

> it's [unexpected] to imagine 17.7 GA solving a problem that continues into 17.8p1.

Has that been considered? Is there something in 17.7 that is expected to allow this to work that's not present in 17.8?

**Comment by wtgodbe** [comment]
Checking to see if the error was the same in the 1es images vs the Scout images

**Comment by wtgodbe** [comment]
1es updated from 17.6 to 17.7 yesterday, so this might just work now - I think we need the combination of VS 17.7 (or newer), plus the windows toolsets/native components on the 1es images

**Review by wtgodbe — APPROVED** [review]

**Comment by dougbu** [comment]
@wtgodbe to confirm: you're not expecting a need for VS 17.7 in the build pools DNCEng provides i.e., the 1es images should now work here❔

**Comment by wtgodbe** [comment]
> You're not expecting a need for VS 17.7 in the build pools DNCEng provides i.e., the 1es images should now work here❔

That's right, sorry for the confusion - I mixed up the initial workload error w/ the missing components error. Now that 1es has updated to 17.7 we are good to go

**Comment by wtgodbe** [comment]
Down to a couple test failures:

`Microsoft.AspNetCore.WebSockets.Test.WebSocketMiddlewareTests.WebSocket_Abort_Interrupts_Pending_ReceiveAsync`

> Assert.IsType() Failure
Expected: Microsoft.AspNetCore.Connections.ConnectionAbortedException
Actual:   System.ArgumentNullException

```text
   at Microsoft.AspNetCore.WebSockets.Test.WebSocketMiddlewareTests.<>c__DisplayClass16_0.<<WebSocket_Abort_Interrupts_Pending_ReceiveAsync>b__0>d.MoveNext() in /_/src/Middleware/WebSockets/test/UnitTests/WebSocketMiddlewareTests.cs:line 550
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.WebSockets.Test.KestrelWebSocketHelpers.<>c__DisplayClass0_0.<<CreateServer>b__5>d.MoveNext() in /_/src/Middleware/WebSockets/test/UnitTests/KestrelWebSocketHelpers.cs:line 30
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.WebSockets.Test.KestrelWebSocketHelpers.<>c__DisplayClass0_0.<<CreateServer>b__5>d.MoveNext() in /_/src/Middleware/WebSockets/test/UnitTests/KestrelWebSocketHelpers.cs:line 38
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:line 676
   at Microsoft.AspNetCore.WebSockets.Test.KestrelWebSocketHelpers.<>c__DisplayClass0_0.<<CreateServer>b__4>d.MoveNext() in /_/src/Middleware/WebSockets/test/UnitTests/KestrelWebSocketHelpers.cs:line 83
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.WebSockets.Test.WebSocketMiddlewareTests.WebSocket_Abort_Interrupts_Pending_ReceiveAsync() in /_/src/Middleware/WebSockets/test/UnitTests/WebSocketMiddlewareTests.cs:line 576
--- End of stack trace from previous location ---
```

`Microsoft.AspNetCore.WebSockets.Test.WebSocketMiddlewareTests.WebSocket_AllowsCancelling_Pending_ReceiveAsync_When_CancellationTokenProvided`

> Assert.True() Failure
Expected: True
Actual:   False

```text
   at Microsoft.AspNetCore.WebSockets.Test.WebSocketMiddlewareTests.<>c__DisplayClass17_0.<<WebSocket_AllowsCancelling_Pending_ReceiveAsync_When_CancellationTokenProvided>b__0>d.MoveNext() in /_/src/Middleware/WebSockets/test/UnitTests/WebSocketMiddlewareTests.cs:line 614
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.WebSockets.Test.KestrelWebSocketHelpers.<>c__DisplayClass0_0.<<CreateServer>b__5>d.MoveNext() in /_/src/Middleware/WebSockets/test/UnitTests/KestrelWebSocketHelpers.cs:line 30
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.WebSockets.Test.KestrelWebSocketHelpers.<>c__DisplayClass0_0.<<CreateServer>b__5>d.MoveNext() in /_/src/Middleware/WebSockets/test/UnitTests/KestrelWebSocketHelpers.cs:line 38
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:line 676
   at Microsoft.AspNetCore.WebSockets.Test.KestrelWebSocketHelpers.<>c__DisplayClass0_0.<<CreateServer>b__4>d.MoveNext() in /_/src/Middleware/WebSockets/test/UnitTests/KestrelWebSocketHelpers.cs:line 83
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.WebSockets.Test.WebSocketMiddlewareTests.WebSocket_AllowsCancelling_Pending_ReceiveAsync_When_CancellationTokenProvided() in /_/src/Middleware/WebSockets/test/UnitTests/WebSocketMiddlewareTests.cs:line 637
--- End of stack trace from previous location ---
```

**Comment by wtgodbe** [comment]
@adityamandaleeka could you assign someone to take a look at the WebSocketMiddleware test failures above? Hopefully a trivial fix

**Comment by JamesNK** [comment]
I took a look, and the tests passed locally. I added some logging to get information about where the ArgumentNullExceptions originated.

**Comment by JamesNK** [comment]
This is the error message:

```
[0.007s] [Microsoft.AspNetCore.WebSockets.Test.WebSocketMiddlewareTests] [Error] Unexpected error.
System.ArgumentNullException: Value cannot be null. (Parameter 'buffer.Array')
   at System.Net.WebSockets.WebSocketValidate.ValidateArraySegment(ArraySegment`1 arraySegment, String parameterName)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebSockets.ServerWebSocket.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken) in /_/src/Middleware/WebSockets/src/ServerWebSocket.cs:line 58
   at Microsoft.AspNetCore.WebSockets.Test.WebSocketMiddlewareTests.<>c__DisplayClass16_0.<<WebSocket_Abort_Interrupts_Pending_ReceiveAsync>b__0>d.MoveNext() in /_/src/Middleware/WebSockets/test/UnitTests/WebSocketMiddlewareTests.cs:line 528
```

It looks like what is happening is the test is calling [WebSocket.ReceiveAsync](https://learn.microsoft.com/en-us/dotnet/api/system.net.websockets.websocket.receiveasync?view=net-7.0#system-net-websockets-websocket-receiveasync(system-arraysegment((system-byte))-system-threading-cancellationtoken)) with a `byte[]`. The `byte[]` is implicitly converted to `ArraySegment<byte>`. However, for some reason, the inner `buffer.Array` value is still null, causing this error.

All the other tests in this file explicitly create the segment, e.g. `new ArraySegment<byte>(new byte[1024])`, instead of relying on an implicit conversion. I've [made that change to the two failing tests](https://github.com/dotnet/aspnetcore/pull/49911/commits/2555a0cf77cf59f0344a644647fb9c8045d804d1), but the bug with the implicit conversion should be looked at.

**Pull request merged**
