### PR TITLE
Disable quarantine pipeline on windows

### PR DESCRIPTION
**Pull request by sebastienros**

### CODE REVIEW

**Comment by dougbu** [comment]
@sebastienros why❔ And, do you now (or will you soon) have an actual fix❔

**Comment by sebastienros** [comment]
I think I have it ... testing right now

**Comment by sebastienros** [comment]
> why?

Running them makes builds longer, blocks agents and doesn't add any value since it fails. Not doing it is just worse.

**Comment by sebastienros** [comment]
https://github.com/dotnet/aspnetcore/pull/36173

**Pull request closed without merging**
