### PR TITLE
Add TryAddScheme

### PR DESCRIPTION
**Pull request by HaoK**
Replaces https://github.com/aspnet/AspNetCore/pull/11079

### CODE REVIEW

**Comment by HaoK** [comment]
Still blocked by cross gen failures in the current SDK in release/3.1

**Comment by HaoK** [comment]
Note: expected fix for the cross gen issue is here: https://github.com/dotnet/coreclr/pull/25839

**Comment by HaoK** [comment]
Retargetting master

**Review by Tratcher — APPROVED** [review]

**Comment by damianh** [comment]
Am a bit late and the linked issue is closed, so just going to say here... thank you @Tratcher for re-opening and reconsidering and thanks @HaoK for implementing.

**Pull request merged**
