### PR TITLE
Update Dockerfiles and allows kestrel to listen for * domains

### PR DESCRIPTION
**Pull request by emyann**
- Fix "web" command mismatch with kestrel entrypoint by updating Dockerfiles
- Allow multiple domains with server.urls *

### CODE REVIEW

**Comment by Eilon** [comment]
@glennc @ahmetalpbalkan ?

**Comment by emyann** [comment]
@Eilon FYI, the mismatch only exists into the folder called latest. The other ones are correct. Thank you for treating this PR :)

**Comment by glennc** [comment]
I don't want to depend on microsoft/aspnet in this sample. These samples are supposed to always work on the latest bits, and the aspnet image is static to released versions. So there is a reason it is that way.

The * change is fine.

Outside of that we will need to change this whole thing significantly when RC2 comes around.

**Comment by Eilon** [comment]
@glennc any thoughts on this?

**Comment by glennc** [comment]
No longer relevant now that there are no samples here.

**Pull request closed without merging**
