### PR TITLE
Add missing `BeforeTargets` for IIS local testing

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Comment by dougbu** [comment]
Thanks to @HaoK for reporting this problem in #39810❕

Not sure how I missed this when doing #39998. Suspect I had published before testing locally.

**Review by HaoK — APPROVED** [review]
Awesome thanks!

**Comment by dougbu** [comment]
[aspnetcore-quarantined-pr build #20220223.10](https://dev.azure.com/dnceng/public/_build/results?buildId=1628439&view=results) failed due to a transient-seeming `503` from https://registry.yarnpkg.com/ua-parser-js/-/ua-parser-js-0.7.30.tgz. Since other jobs got what they wanted from the registry and this PR shouldn't impact Helix testing at all (that already worked), I'll ignore the failure.

**Comment by HaoK** [comment]
This might fix some things, but unfortunately this doesn't do the trick for the main issue:

```
System.AggregateException : One or more errors occurred. (Could not find a part of the path 'C:\Github\aspnetcore\src\Servers\IIS\IIS\test\testassets\InProcessWebSite\bin\Release\net7.0\publish\InProcessWebSite-Portable'.) (Operation did not succeed after 15 retries (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element))
---- System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\Github\aspnetcore\src\Servers\IIS\IIS\test\testassets\InProcessWebSite\bin\Release\net7.0\publish\InProcessWebSite-Portable'.
---- System.AggregateException : Operation did not succeed after 15 retries (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element)
-------- System.InvalidOperationException : Sequence contains more than one element

```

The tests still fail because no publish\InProcessWebSite-Portable type directories are created, I tried these changes out locally, both VS builds and full build.cmd still don't produce those directories which the tests expect.  That is the main issue with the current test failures locally

**Comment by dougbu** [comment]
Thanks for the added information @HaoK. The IIS Express tests I tried didn't require the portable profile but failed w/o this. So, this change was necessary but not sufficient. Touching this PR up&hellip;

**Comment by HaoK** [comment]
If the tests don't work for you locally, you can turn off Helix via the BuildHelixPayload setting to trigger them running the old way to flush out any kinks in this PR

**Comment by dougbu** [comment]
What I tested before was

1. `git clean ...`
2. `.\eng\build.cmd` (this doesn't publish the test assets)
3. `dotnet test /bl .\src\Servers\IIS\IIS\test\IISExpress.FunctionalTests\IISExpress.FunctionalTests.csproj` (this does)

That worked fine and src\Servers\IIS\IIS\test\testassets\InProcessWebSite\bin\Debug\net7.0\publish\ contained both InProcessWebSite-Portable and InProcessWebSite-Standalone-x64 when tests completed. My second commit here _should_ be redundant but are you doing similar things❔

**Comment by dougbu** [comment]
> you can turn off Helix via the BuildHelixPayload setting to trigger them running the old way to flush out any kinks in this PR

Opened #40381 as a draft to test this way in parallel. Would still like to know why test assets are being published for me but not you @HaoK

**Comment by HaoK** [comment]
I usually just do `src/servers/IIS/build.cmd -c release`

And then I've just been doing VS - test explorer run.  I haven't tried running the full root eng/build today.

There's also some issues with the fastuptodate checks that were removed in the IIS projects, I'll be adding those back, because the current behavior is that just editing the shared test cs files does not result in a rebuild, which is super confusing, as VS will happily run the old tests since it doesn't notice the shared cs files getting edited.

**Comment by dougbu** [comment]
> There's also some issues with the fastuptodate checks that were removed in the IIS projects, I'll be adding those back, &hellip;

/cc @Pilchie

> And then I've just been doing VS - test explorer run

Thought you said somewhere that you tried testing both from the command line and in VS. How do you test from the command line❔ I'll also see if I can repro your continued issues in VS w/ and w/o my second commit here.

**Comment by dougbu** [comment]
/fyi my current suspicion is that VS test explorer doesn't use the targets I added to `BeforeTargets` in the first commit and my second commit didn't help but I'll see&hellip; (VS was out-of-date-ish and I'm waiting.)

**Comment by Pilchie** [comment]
@HaoK can you file an issue with detailed steps of what wasn't working when you add them back?  I'd like to investigate and try fixing for real again.

**Comment by HaoK** [comment]
Sure filed https://github.com/dotnet/aspnetcore/issues/40387 with the steps to reproduce in main today, the repro is actually just on the managed test code, I believe there's similar issues with the native code, but its much easier to hit with just the top level SkipNonHelix on one of the common startup tests.

**Comment by dougbu** [comment]
Shoot, didn't mean to update this branch. Will reset&hellip;

**Review by wtgodbe — APPROVED** [review]
LGTM if it works

**Comment by dougbu** [comment]
@HaoK I was eventually able to reproduce the problems you're having with testing in VS. My thanks to @MarcoRossignoli for his help understanding the root cause.

Basically, VS uses `msbuild` for builds but doesn't when testing. It (vstest.console.exe) instead uses the test assembly directly to discover and execute tests. My previous second commit partially handled that case but only when using `Standalone-x64` profiles. This version covers `Portable` too.

**Comment by HaoK** [comment]
Yay, I'll make these changes in my branch to see if that fixes everything too

**Comment by HaoK** [comment]
This PR fixes things for me locally too!

**Comment by dougbu** [comment]
🎉 Success here (testing IIS mostly on Helix), success locally (including in VS), and success in #40381 (testing IIS mostly on build agents). 🎉

**Pull request merged**
