### PR TITLE
Include third-party-notices.txt in all packages

### PR DESCRIPTION
**Pull request by wtgodbe**
Resolves https://github.com/dotnet/aspnetcore/issues/20086

Explicitly includes `Third-Party-Notices.txt` in all packages, and allows packages to use a custom `third-party-notices.txt` file if they so choose (Identity.UI and the Components packages currently do so). Also includes the `version.txt` file that was missing from the shared framework

### CODE REVIEW

**Review by JunTaoLuo — APPROVED** [review]
Looks good but let's verify the build artifacts when available.

**Comment by wtgodbe** [comment]
Will do. I took a look at the artifacts on my box & they looked good, but will re-verify w/ the stuff from CI

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
How will we keep the Identity/UI and Components files up-to-date @mkArtakMSFT (especially after this change gets into 'master')❔ And, is there a way to automatically verify the files are complete close to release time?

**Comment by wtgodbe** [comment]
The packages here look correct to me. @safern @ericstj @ViktorHofer does dotnet/runtime do any package testing to validate that files like `third-party-notices.txt` are actually being included?

**Comment by ericstj** [comment]
We do some package testing but we don't have tests around those additional files, however we do include them in the dotnet/runtime packages.

**Comment by ericstj** [comment]
Actually, I see we have in our nuget packages, but not in the shared framework.  @dagood @NikolaMilosavljevic we might want to fix that.

**Comment by dagood** [comment]
Installing the .NET Core Runtime places "C:\Program Files\dotnet\ThirdPartyNotices.txt" down alongside the host. Installing it with the sharedfx too might be good for side-by-side installs to get a per-version TPN file, but not sure if it's necessary. @leecow @nakarnam

**Comment by dagood** [comment]
The goal in the past has seemed to be that "C:\Program Files\dotnet\ThirdPartyNotices.txt" contains data for everything in the directory: https://github.com/dotnet/runtime/issues/3619.

**Pull request merged**
