### PR TITLE
Backport 41868 to release/6.0

### LINKED ISSUE #41731: Issue when binding DateTime to input type="time"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Consider this code:

`<input type="time" @bind-value="Input.AnyPropertyWhichIsOfTypeDateTime" class="form-control" placeholder="Time" />`

Now consider the bound property to have a value like:
`new DateTime(2022, 5, 18, 12, 22, 30);`

As you can see, this value has the seconds set to 30.

.NET 5 displays the Input like this:
grafik

if you do the same thing with .NET 6 then the seconds will be displayed as well but the control is invalid because Step is set to 60 by default. So this control does not expect any seconds at all which results in a validation error from HTML5.
grafik

grafik

This is really annoying because most databases saves the seconds by default. 

### Expected Behavior

It should work exactly like in .NET 5

### Steps To Reproduce

1. Create a new project
2. Create a model which holds a datetime property
3. bind this property to `<input type="time">`
4. Set the value to DateTime.Now
5. Test with .NET 5 and then .NET 6

### Exceptions (if any)

grafik

### .NET Version

6.0.300

### Anything else?

.NET SDK (gemäß "global.json"):
 Version:   6.0.300
 Commit:    8473146e7d

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  3.1.419 [C:\Program Files\dotnet\sdk]
  5.0.404 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
# Fix time/datetime-local binding with seconds when there's no step attribute

Restores the ability to do `<input type=time @bind="someDateTimeVariable">` without getting a weird browser warning if `someDateTimeVariable` has a non-zero "seconds" component. This used to work in 5.0 but regressed in 6.0.

## Description

In 5.0, there was explicit JS-side logic to handle the case where an `<input type=time>` had no `step` attribute (which browsers interpret as "use whole number of minutes - no seconds"). We automatically stripped off any "seconds" part of the formatted string to make it valid as far as the `<input type=time>` is concerned. This behavior was unintentionally lost in 6.0.

Fixes #41731

## Customer Impact

Without this change:

 * People upgrading 5.0 applications to 6.0
 * Or, people writing new 6.0 applications without realising they would need to ensure bound `DateTime` or `TimeOnly` values have a zero "seconds" component when used with `<input type=time>` or `<input type=datetime-local>`

... would find that:

1. The UI displays a weird tooltip saying that the time value is invalid
2. The values retrieved from an `<input type=time>` or `<input type=datetime-local>` would have a nonzero "seconds" component *only if they have not been edited by the user*, which is pretty odd

## Regression?

- [x] Yes
- [ ] No

Worked in 5.0

## Risk

- [ ] High
- [x] Medium
- [x] Low

It is plausible that a 6.0 developer has taken a dependency on this weird behavior. For example, they might be using the `<input type=time>` as a readonly value, and be relying on the ability to round-trip a value that includes a nonzero "seconds" part. However:

 1. This is a bad UX, as the browser will be showing a tooltip saying the value is invalid
 2. This would be a very flaky pattern to follow, because "input" elements are primarily intended for editing, and the moment the user edits the value, the "seconds" part would be reset to zero

The 5.0 behavior is objectively better, so I have no doubt we should fix this in 7.0. Whether or not we should also patch 6.0 and accept the risk that some developer actually wants the bug is a more ambiguous question.

## Verification

- [x] Manual (required)
- [x] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
cc @mkArtakMSFT

**Review by javiercn — APPROVED** [review]

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT This can be merged

**Comment by mkArtakMSFT** [comment]
@wtgodbe when will the branches be ready to merge this? Can I merge this now?

**Comment by wtgodbe** [comment]
Branches will open after we do branding next Tuesday (6/7)

**Pull request merged**
