### PR TITLE
Add ProblemDetials.Extensions to ControllerBase.Problem and ControllerBase.ValidationProblem

### PR DESCRIPTION
**Pull request by mariusz96**
This PR:
- adds parameter for `ProblemDetails.Extensions` to `ControllerBase.Problem` and `ControllerBase.ValidationProblem`

API proposal:
- https://github.com/dotnet/aspnetcore/issues/50220

Addresses:
- #43159

### CODE REVIEW

**Comment by mariusz96** [comment]
@dotnet-policy-service agree

**Comment by captainsafia** [comment]
I've marked the issue associated with this PR as ready for API review. We'll commence code review once that API has been approved.

**Comment by captainsafia** [comment]
@mariusz96 The API was approved in API review with some notes. In particular, making sure we use a new overload here instead of modifying the existing one to avoid introducing a binary breaking change. Let me know if you need help reacting to any of the API review feedback.

**Comment by KirkMunroSagent** [comment]
@mariusz96 Thank you for opening this PR. I was just looking for this functionality, so it's nice to see that it's on the way. Do you have an ETA when you'll be able to update it with overloads as requested in the API review feedback? Seems like an easy update to make. Just wondering because I would use this overload today if it was available, so I'd like to know when it might be completed/published.

**Comment by mariusz96** [comment]
> @mariusz96 Thank you for opening this PR. I was just looking for this functionality, so it's nice to see that it's on the way. Do you have an ETA when you'll be able to update it with overloads as requested in the API review feedback? Seems like an easy update to make. Just wondering because I would use this overload today if it was available, so I'd like to know when it might be completed/published.

There is no approved API. The accepted one from the API proposal does not compile.

The changes will be added when new API gets approved.

**Comment by captainsafia** [comment]
> > @mariusz96 Thank you for opening this PR. I was just looking for this functionality, so it's nice to see that it's on the way. Do you have an ETA when you'll be able to update it with overloads as requested in the API review feedback? Seems like an easy update to make. Just wondering because I would use this overload today if it was available, so I'd like to know when it might be completed/published.
> 
> There is no approved API. The accepted one from the API proposal does not compile.
> 
> The changes will be added when new API gets approved.
> 
> cc @captainsafia @halter73

I moved the related issue back to `api-ready-for-review` so it will come up during our next API review session.

**Comment by captainsafia** [comment]
@mariusz96 Apologies for the delay! Took a while for this to come up during our API review meetings. The issue has been updated with a modified proposal and this PR is ready for update.

**Review by captainsafia — APPROVED** [review]

**Pull request merged**
