### PR TITLE
Change framework names

### PR DESCRIPTION
**Pull request by hishamco**
Based on https://github.com/aspnet/Announcements/issues/3

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@hishamco__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft Open Technologies, Inc. and real humans are currently evaluating your PR.</p>

TTYL, MSOTBOT;

**Comment by Eilon** [comment]
@glennc

**Comment by muratg** [comment]
Thanks @hishamco.

@glennc :shipit:

**Comment by hishamco** [comment]
You are welcome @muratg

**Comment by glennc** [comment]
Thanks @hishamco, but we made this change as part of a larger change recently. I am sorry I didn't see this before I merged the larger change or I would've merged your PR fist. Thanks for going to the effort to contribute it. I appreciate the help :)

**Comment by hishamco** [comment]
@glennc no problem .. all the best ..

**Pull request closed without merging**
