### PR TITLE
Update branding to 2.1.16

### PR DESCRIPTION
**Pull request by JunTaoLuo**
https://github.com/aspnet/AspNetCore-Internal/issues/3464

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
Ready to go @dougbu @wtgodbe yay nuget index finally updated.

**Comment by JunTaoLuo** [comment]
Actually I need to update the package archive too, one moment.

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
@JunTaoLuo why isn't this one merged? The required checks look good and so do the changes.

**Comment by JunTaoLuo** [comment]
I'm wondering if the test failure in macos is flaky or not.

**Comment by dougbu** [comment]
Depending on how long that leg of the aspnetcore-ci build takes, you might not want to wait. That's not a required check of this branch.

**Comment by JunTaoLuo** [comment]
Turns out it was just flaky.

**Pull request merged**
