### PR TITLE
Merge aspnet/KestrelHttpServer into this repo

### PR DESCRIPTION
**Pull request by natemcmaster**
As a part of #3598, this merges the source code and history of aspnet/KestrelHttpServer release/2.1 into this repo.

For easier review of code layout, see https://github.com/aspnet/AspNetCore/tree/namc/merge-kestrel-2.1/src/Servers

TODO:
* get tests to pass. Most of them currently fail with NullReferenceException in LoggedTestBase

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]
Once some of the tests pass.

**Comment by natemcmaster** [comment]
Unclean state on my machine. It appears tests pass on CI now.

**Review by JunTaoLuo — APPROVED** [review]
if tests pass

**Comment by natemcmaster** [comment]
I'll merge after lunch.

**Pull request merged**
