### PR TITLE
Dispose MemoryStream in DataProtectorTokenProvider

### LINKED ISSUE #23271: Undisposed MemoryStream
I just dove a bit into Identity's source code and saw that in [DataProtectorTokenProvider.cs](https://github.com/dotnet/aspnetcore/blob/cb35b902262535d831209996a2a0053f717dadb3/src/Identity/Core/src/DataProtectorTokenProvider.cs#L88) there's a `MemoryStream` that's not being disposed.

Proposal: Put the `MemoryStream` into a `using` statement to dispose it after use.

### PR DESCRIPTION
**Pull request by Kahbazi**
Fixes https://github.com/dotnet/aspnetcore/issues/23271

### CODE REVIEW

**Comment by gfoidl** [comment]
Cf. https://github.com/dotnet/aspnetcore/pull/9339
I still wouldn't dispose it, as it's private use and the "sub-class problem" (custom dispose-logic) doesn't apply here.

**Comment by mkArtakMSFT** [comment]
Thanks for your PR.
@HaoK can you please look into this? Thanks!

**Comment by HaoK** [comment]
Yep not worth it, thanks for the PR anyways!

**Comment by Kahbazi** [comment]
@Haok Should this issue be closed too? https://github.com/dotnet/aspnetcore/issues/23271

**Pull request closed without merging**
