### PR TITLE
Mark changes in `.github` folder with `area-infrastructure` label

### PR DESCRIPTION
**Pull request by mkArtakMSFT**

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Review by dougbu — APPROVED** [review]
😺

**Comment by dougbu** [comment]
General question: CODEOWNERS handles subdirectories quite nicely, allowing more reviewers on (say) PublicAPI.*Shipped.txt files than on other changes in the same folder. Should we do similar things w/ the bot and its labels❔ I think the bot alread addes labels requesting API reviews whenever a PublicAPI.*Shipped.txt file is touched and have a fancy split w/in src/Mvc. But, for .github/ in particular, can we label action changes to let @Tratcher know about them or issue template changes to let you, @mkArtakMSFT, know❔

**Comment by mkArtakMSFT** [comment]
We can sure do that, @dougbu. Although I don't like pinging a specific individual in a rule. Team would be a better choice. If you have a clear mapping in mind, could you please put that out in an issue and let me know about it, and I'll handle it.

**Comment by dougbu** [comment]
> I don't like pinging a specific individual in a rule

I agree though we haven't stuck to that in CODEOWNERS, probably because that's dealing w/ reviewers and those get dropped once on person on a team responds. The same shouldn't be true for `@` mentions and allows the bot's rules to stick w/ teams.

In this case, I don't have specific teams in mind, but we could certainly create `github-template-reviewers`, `github-workflow-reviewers`, or a combined `github-subdirectory-reviewers`. (It's probably only @dotnet/aspnet-build that cares about all of .github/&hellip;

Something to keep in mind in the future or where we already have "interesting" teams (or labels).

**Comment by mkArtakMSFT** [comment]
In that case I think this PR is enough, as it will now label these with area-infrastructure, and that will ping the build team.

**Pull request merged**
