### PR TITLE
Templates enable EF SQL command logging in development

### LINKED ISSUE #32977: ASP.NET template disables EF Core SQL logging by default
### Include your code

Create an ASP.NET Core app with individual user accounts so EF Core is used

```
dotnet new webapp -au Individual -uld -o RPauth
cd RPauth
dotnet ef database update
dotnet run

```

Browse to https://localhost:5001/ and create a new account. Click on the link to confirm the account. Note that no SQL is logged.

Add the following to *appsettings.json*:
```,"Microsoft.EntityFrameworkCore.Database.Command": "Information"```

No need to stop/restart as *appsettings.json* is reloaded. Navigate to https://localhost:5001/Identity/Account/Manage can select some of the tabs on the left. SQL output is displayed.

Comment out the following and  SQL output stops:

```// ,"Microsoft.EntityFrameworkCore.Database.Command": "Information"```

### Include provider and version information

Using all defaults with .NET 5 or .NET 6

Related: dotnet/efcore#3240

### PR DESCRIPTION
**Pull request by DamianEdwards**
Fixes #32977

### CODE REVIEW

**Review by Rick-Anderson — APPROVED** [review]

**Comment by davidfowl** [comment]
This feels so bad to do preemptively

**Review by davidfowl — CHANGES_REQUESTED** [review]
I don't think this should be in the template

**Comment by DamianEdwards** [comment]
@davidfowl are you saying you don't think this should be in the templates at all, or that we should remove it from the templates that don't use Entity Framework?

**Comment by davidfowl** [comment]
I think adding it to templates that use EF is fine.

**Comment by ajcvickers** [comment]
Would it be useful to add a template/option to use EF Core without needing to also use Identity? //cc @Rick-Anderson @JeremyLikness 

@davidfowl Maybe the real problem here is the setting to Warning for _all_ Microsoft logs, which sets the logging for any Microsoft package without any knowledge of what the packages are or what is appropriate to log from them. Can the template more selectively set logging levels for only the things it actually knows about?

**Comment by Rick-Anderson** [comment]
I want to make sure customers that create a new web or API project have EF logging in debug mode enabled.  See [this SO thread](https://stackoverflow.com/questions/45893732/how-do-you-show-underlying-sql-query-in-ef-core), 55K + views, all the ridiculous answers to get SQL logging. Luckily I was able to contact the owner and have him change my answer to the correct answer.

**Comment by JeremyLikness** [comment]
Which templates use EF Core? Is it just when users choose authentication and pick identity server? Or are there templates that will scaffold general data access (not Identity) using EF Core? I thought it was the former. Either way I agree there shouldn't be EF Core settings in templates that don't use EF Core.

**Comment by DamianEdwards** [comment]
@JeremyLikness yes it's only when the identity options are enabled that EF Core is added to the templates today. The scaffolding system will add EF Core to a project but doesn't currently add the logging configuration. I've created dotnet/Scaffolding#1615 to track that.

I'll update the PR to remove EF Core logging settings if EF Core is not actually referenced.

**Comment by ajcvickers** [comment]
@DamianEdwards Do we have numbers that show scaffolding commonly used to add EF Core? (In other words, will this really address @Rick-Anderson's concerns?)

**Comment by DamianEdwards** [comment]
New idea from @davidfowl:

> Instead of making everything `Microsoft.*` `Warning`, how about we configure just `Microsoft.AspNetCore.*` and `Microsoft.Extensions.*` as `Warning`?

**Comment by DamianEdwards** [comment]
Just tried this out locally and if we want this change to only apply for development then this is what the logging section of _appsettings.Development.json_ has to contain to get the desired configuration:

``` json
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Information",
      "Microsoft.AspNetCore": "Warning",
      "Microsoft.Extensions": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  }
```

This is because these settings are **merged** with those in _appsettings.json_ which explicitly configures `"Microsoft": "Warning"` so we have to override it.

Alternatively we update both configuration files with the same settings like so:
``` json
"Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning",
      "Microsoft.Extensions": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  }
```

**Comment by DamianEdwards** [comment]
FYI here's some example output from an app using auth with the suggested configuration after starting it then navigating to the profile page (already logged in):

``` console
❯ dotnet run
Building...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:7151
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5057
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\src\GitHub\dotnet\aspnetcore\src\ProjectTemplates\scripts\webapp
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 6.0.0-rc.1.21406.1 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.Sqlite' with options: None
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (11ms) [Parameters=[@__p_0='?' (Size = 36)], CommandType='Text', CommandTimeout='30']
      SELECT "a"."Id", "a"."AccessFailedCount", "a"."ConcurrencyStamp", "a"."Email", "a"."EmailConfirmed", "a"."LockoutEnabled", "a"."LockoutEnd", "a"."NormalizedEmail", "a"."NormalizedUserName", "a"."PasswordHash", "a"."PhoneNumber", "a"."PhoneNumberConfirmed", "a"."SecurityStamp", "a"."TwoFactorEnabled", "a"."UserName"
      FROM "AspNetUsers" AS "a"
      WHERE "a"."Id" = @__p_0
      LIMIT 1
```

**Comment by davidfowl** [comment]
Remove `"Microsoft.Extensions": "Warning",` and see what happens?

**Comment by DamianEdwards** [comment]
@davidfowl sorry I already had, so what you're seeing above is the output from both settings file having:

``` json
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  }
```

**Comment by DamianEdwards** [comment]
I guess we can remove the specific config for `Microsoft.Hosting.Lifetime` too then...

**Comment by DamianEdwards** [comment]
Confirmed that we can update both settings files with following and get the same output:
``` json
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  }
```

**Comment by davidfowl** [comment]
cc @Tratcher

**Review by davidfowl — APPROVED** [review]

**Pull request merged**
