### PR TITLE
Reduce Functional Test Stream Item Delay

### PR DESCRIPTION
**Pull request by mikaelm12**
This makes the functional tests run twice as fast.
A number of our tests use this method and when running all the variations it adds up.

### CODE REVIEW

**Comment by halter73** [comment]
Is there any particular reason we need to delay any amount of time? What if we Thread.Yielded instead? Or just wrote to the ChannelWriter as fast as it would allow?

**Comment by halter73** [comment]
I think we should also look at reducing the number of variations of our functional tests. In our C# functional HubConnectionTests.cs, we only have 40 test methods, but 768 test cases. I doubt that all these variations are really adding coverage.

**Comment by mikaelm12** [comment]
> I think we should also look at reducing the number of variations of our functional tests. In our C# functional HubConnectionTests.cs, we only have 40 test methods, but 768 test cases. I doubt that all these variations are really adding coverage.

I think in the beginning when things were a lot smaller and we were just adding the new hub types and protocols it made more sense but I tend to have more of your mindset now.

**Comment by mikaelm12** [comment]
> Is there any particular reason we need to delay any amount of time? What if we Thread.Yielded instead? Or just wrote to the ChannelWriter as fast as it would allow?

There are some streaming tests for cancellation that depended on having some delay. A better solution might be to find the tests that depend on that and add new hub methods for those and reduce the number of test variants. A lot of our tests current use the hub method that has a 100ms delay that don't particularly need it.

**Review by halter73 — APPROVED** [review]

**Comment by halter73** [comment]
Either way, this seems to be an improvement.

**Pull request merged**
