### PR TITLE
Added the Blazor survey link to the Blazor-Server project template

### PR DESCRIPTION
**Pull request by mkArtakMSFT**
## Description
We currently have the Blazor survey link in the Blazor WASM project, but don't have this link in the Blazor Server project template. This results in getting skewed data, which doesn't allow us to make reasonable decisions. We are now enabling this for Blazor Server projects too to cover all the Blazor users.

## User Impact
The Index page in the Blazor Serer app will now have a link in the bottom (similar to what is there in the Blazor WASM project template) which will take users to the survey about Blazor.

## Regression
No: this is something new which is going to be visible only in the new projects.

## Risk
Minimal

Addresses https://github.com/aspnet/AspNetCore/issues/17433

### CODE REVIEW

**Review by danroth27 — APPROVED** [review]

**Review by ryanbrandenburg — APPROVED** [review]

**Comment by vivmishra** [comment]
Moved to Mar as per Tactics. Will need to be explicitly approved for Feb, if required.

**Comment by mkArtakMSFT** [comment]
Moving back to 3.1.2 per a later Tactics decision (@jamshedd , @vivmishra )

**Comment by mkArtakMSFT** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=486656&view=ms.vss-test-web.build-test-results-tab&runId=15485336&resultId=116172&paneView=debug

**Comment by mkArtakMSFT** [comment]
The only failure here is unrelated and is tracked by https://github.com/aspnet/AspNetCore-Internal/issues/3467

**Comment by mkArtakMSFT** [comment]
@dotnet/aspnet-build folks, the only failure here is unrelated and I've filed a separate issue to track that down. This PR is ready to be merged.

**Pull request merged**
