### PR TITLE
Blazor Template improvements Take 2

### PR DESCRIPTION
**Pull request by HaoK**
Don't split up the create/publish/build for now, but keep the logging changes

### CODE REVIEW

**Comment by HaoK** [comment]
@javiercn @dotnet/aspnet-build this is an example log of dotnet restore failing both as part of dotnet new and the follow up explicit dotnet restore, the new tracing logs might have something helpful too.  Maybe extra eyes can help see if anything jumps out here because its not obvious to me why restore is failing

Example log
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-pull-31242-merge-0145cf8253a9442eb7/BlazorTemplates.Tests--net6.0/Templates.Test.BlazorWasmTemplateTest_BlazorWasmHostedTemplate_IndividualAuth_Works_WithOutLocalDB-Chromium.log?sv=2019-07-07&se=2021-04-14T18%3A23%3A09Z&sr=c&sp=rl&sig=3Kb6C%2BNGplePjJGvLZsTzcf9J%2B%2BskxvAXwq92yyLa6E%3D

```
[2.354s] [Templates.Test.BlazorWasmTemplateTest] [Information] [ERROR] CoreCLR path = '/private/tmp/helix/working/A11808B3/w/A229090A/e/.dotnet23310/shared/Microsoft.NETCore.App/6.0.0-preview.3.21167.1/libcoreclr.dylib', CoreCLR dir = '/private/tmp/helix/working/A11808B3/w/A229090A/e/.dotnet23310/shared/Microsoft.NETCore.App/6.0.0-preview.3.21167.1/'
[2.368s] [Templates.Test.BlazorWasmTemplateTest] [Information] [ERROR] Launch host: /private/tmp/helix/working/A11808B3/w/A229090A/e/.dotnet23310/dotnet, app: /private/tmp/helix/working/A11808B3/w/A229090A/e/.dotnet23310/sdk/6.0.100-preview.3.21168.19/MSBuild.dll, argc: 6, args: -maxcpucount,-verbosity:m,-nologo,-target:Restore,/tmp/helix/working/A11808B3/w/A229090A/e/Templates/BaseFolder/AspNet.rhdzyvzuhk4/AspNet.rhdzyvzuhk4.sln,-distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/private/tmp/helix/working/A11808B3/w/A229090A/e/.dotnet23310/sdk/6.0.100-preview.3.21168.19/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/private/tmp/helix/working/A11808B3/w/A229090A/e/.dotnet23310/sdk/6.0.100-preview.3.21168.19/dotnet.dll,
[2.368s] [Templates.Test.BlazorWasmTemplateTest] [Information] [ERROR] --- Begin breadcrumb write
[2.368s] [Templates.Test.BlazorWasmTemplateTest] [Information] [ERROR] Directory core breadcrumbs [] was not specified or found
[2.368s] [Templates.Test.BlazorWasmTemplateTest] [Information] [ERROR] Fallback directory core breadcrumbs at [opt/corebreadcrumbs] was not found
[2.368s] [Templates.Test.BlazorWasmTemplateTest] [Information] [ERROR] Breadcrumb store was not obtained... skipping write.
[602.971s] [Templates.Test.BlazorWasmTemplateTest] [Information] [ERROR] Execute managed assembly exit code: 0x1
[602.979s] [Templates.Test.BlazorWasmTemplateTest] [Information] Restore failed.
[602.979s] [Templates.Test.BlazorWasmTemplateTest] [Information] Post action failed.
[602.980s] [Templates.Test.BlazorWasmTemplateTest] [Information] Description: Restore NuGet packages required by this project.
[602.980s] [Templates.Test.BlazorWasmTemplateTest] [Information] Manual instructions: Run 'dotnet restore'
[602.980s] [Templates.Test.BlazorWasmTemplateTest] [Information] 
[603.158s] [Templates.Test.BlazorWasmTemplateTest] [Information] [ERROR] Execute managed assembly exit code: 0x0
[603.167s] [Templates.Test.BlazorWasmTemplateTest] [Information] Process exited.
```

**Comment by javiercn** [comment]
@HaoK I don't see anything other than the restore failed :(

**Comment by HaoK** [comment]
I think things are more stable now, I'm still seeing this test consistently time out, but regardless I'll requarantine the tests so we can see more numbers in the quarantine-pr, I think this PR is safe to merge now as it only should be affecting the logs

The wasm tests that seem to consistently fail are failing with this error:
```
Process proc dotnet new blazorwasm --debug:custom-hive "Hives/.templateEngine" --hosted -au Individual  -o /tmp/helix/working/B13E0978/w/A5BC0967/e/Templates/BaseFolder/AspNet.0ec2mjonrmj timed out after 00:15:00.
```

**Comment by HaoK** [comment]
Bringing back the template logging improvements without any of the breakup of tests, this shouldn't affect ci greenness since all the tests basically are remaining in quarantine (the last PR introduced the new build/create/publish tests that were flaky, and are not part of this PR)

**Review by javiercn — APPROVED** [review]

**Pull request merged**
