### PR TITLE
Jmprieur/fix web api templates

### PR DESCRIPTION
**Pull request by jmprieur**
- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

**PR Title**
Fixing ASP.NET Core project templates (Web API and Blazorwasm hosted webAPI)

**PR Description**
- Fixing the "Scopes" line in the configuration file. It wasn't located at the right location, and not available for B2C
- In the blazorwasm, fixing the template.json and adding different razor pages to call the API
- Using the b2clogin authorities for B2C (tfp is being obsoleted)

Fixes #bugnumber (in this specific format)

### CODE REVIEW

**Comment by HaoK** [comment]
Per our meeting today, getting this into main and 6.0

**Comment by HaoK** [comment]
Oops wrong one

**Comment by pranavkm** [comment]
@jmprieur could you confirm if these these changes still relevant for .NET 7?

**Comment by jmprieur** [comment]
@pranavkm it is relevant in NET 7.
Isn't it there?

**Comment by pranavkm** [comment]
@HaoK mentioned some of these changes were already in .NET 7, but perhaps I misinterpreted it. @HaoK could you confirm?

**Comment by HaoK** [comment]
I think so, this should match this backport https://github.com/dotnet/aspnetcore/commit/1e5fc75adafa46987e1d435fe80fff12eebf21b9#diff-2d7a7842c77c7c9e65a078402324f24c9d5b086c05513ce97bde0a018284990e

**Comment by pranavkm** [comment]
Alright, I guess we should be good to close this PR in that case.

**Pull request closed without merging**
