### PR TITLE
Add RegexOptions.Compiled option to RegexRouteConstraint 

### LINKED ISSUE #46154: RegexRouteConstraint should use Compiled Regex
Today, when using a `regex` route constraint, we create a new Regex:

https://github.com/dotnet/aspnetcore/blob/e5238763bddd7100823751c4a4ae0220d78160aa/src/Http/Routing/src/Constraints/RegexRouteConstraint.cs#L40-L43

This should use the `RegexOptions.Compiled` as well. That way we aren't interpreting these regular expressions every time the route is inspected.

[Our docs](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-7.0#regular-expressions-in-constraints) even say this should be using Compiled:

> The ASP.NET Core framework adds RegexOptions.IgnoreCase | RegexOptions.Compiled | RegexOptions.CultureInvariant to the regular expression constructor. See [RegexOptions](https://learn.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regexoptions) for a description of these members.

### PR DESCRIPTION
**Pull request by eugeneogongo**
# Add RegexOptions.Compiled option to RegexRouteConstraint 

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description
Add RegexOptions.Compiled option to RegexRouteConstraint 

Fixes #46154

### CODE REVIEW

**Comment by eugeneogongo** [comment]
@surayya-MS  would you go through this PR?
Thank you.

**Review by danmoseley — APPROVED** [review]
thanks

**Comment by mkArtakMSFT** [comment]
@surayya-MS can you please review this? Thanks!

**Review by surayya-MS — APPROVED** [review]

**Comment by surayya-MS** [comment]
Thanks for the contribution

**Comment by JamesNK** [comment]
I looked back in time, and we've never used `RegexOptions.Compiled`: https://github.com/dotnet/aspnetcore/blob/a917cbd5770beaf4759bff9254bfcaa483e20d70/src/Microsoft.AspNet.Routing/RegexConstraint.cs#L18

Maybe `Compiled` was left out accidentally, but it could have been purposefully removed. I worry about web app startup time. For example, an app could have thousands of routes with regex constraints. Are they all compiled when the app starts up? That could really hurt time to first request.

**Comment by eugeneogongo** [comment]
@JamesNK  The cost of constructing the [Regex](https://learn.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex) object may be higher, but the cost of performing matches with it is likely to be much smaller.

**Comment by JamesNK** [comment]
@eugeneogongo The performance improvement in matching the constraint is great, but I think we should take some time to verify that nothing else (startup time, total app memory usage) has regressed when there are a lot of routes with regex constraints.

If measuring highlights `RegexOptions.Compiled` is a problem, there might be ways to have the best of both worlds. For example, waiting to create the `Regex` instance until the first time the route constraint is evaluated.

**Pull request merged**
