### PR TITLE
chore (Badge) : Add .NET foundation badge

### PR DESCRIPTION
**Pull request by ShreyasJejurkar**
1. Found the .NET foundation badge at https://img.shields.io/badge/.NET%20Foundation-blueviolet.svg
2. Add to badge collection.

### CODE REVIEW

**Comment by Pilchie** [comment]
@terrajobst - is this a thing other repos are doing?

**Comment by ShreyasJejurkar** [comment]
I have not seen this badge to other repo. But recently I cam across the new dotnet foundation project (https://github.com/reaqtive/reaqtor). And I saw that badge there!

**Comment by Pilchie** [comment]
@dotnet/aspdoi @dotnet/aspnet-build Any objections here?  The (site)[https://shields.io] claims no tracking which was my only concern.

**Comment by dougbu** [comment]
> Any objections here?

I can't see anything objectionable and we use https://shields.io/ badges already in the Readme file. We have the horizontal room for another badge, it looks pretty good, and the link is helpful (despite the license text at the top of most files).

Minor but how helpful is it is to add the badge w/o a dynamic label providing additional information❔ I can't think of a constraint we need to weigh against this but thought I'd ask.

**Review by Pilchie — APPROVED** [review]

**Pull request merged**
