### PR TITLE
Fix variable names in dnvminstall.ps1

### PR DESCRIPTION
**Pull request by glen-84**

### CODE REVIEW

**Comment by davidfowl** [comment]
@glen-84 Send this pr to aspnet/dnvm. These files are automatically updated and are considered readonly on this repository.

**Comment by davidfowl** [comment]
Bah my bad

**Comment by jasonwilliams200OK** [comment]
:+1:

**Comment by glennc** [comment]
We did this in the dev branch when we done the reorg of stuff recently. Missed this PR for it I would've merged it first. Thanks for taking the time for the PR, I'm sorry we made the change instead of merging it.

**Comment by glennc** [comment]
Re-opening, I don't know what I was thinking. Thanks for the PR, I am merging it now :).

**Comment by glen-84** [comment]
You're welcome. :smile:

**Pull request merged**
