### PR TITLE
Put favicon.ico back for Blazor Server-Side template. Fixes #9096

### LINKED ISSUE #9096: Razor Components project template doesn't have a favicon.ico
All our other web app templates have a `favicon.ico` in the `wwwroot` folder. We should probably have the same one in the Razor Components project template too. Without it, Chrome makes a request anyway then shows an error in the dev console which is less than pleasant.

image

@danroth27

### PR DESCRIPTION
**Pull request by SteveSandersonMS**

### CODE REVIEW

**Comment by javiercn** [comment]
hmm, did i not do this correctly?

**Comment by javiercn** [comment]
I think that's the wrong icon. @danroth27 wants to use the same as the one for blazor.

**Review by javiercn — APPROVED** [review]

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT Thanks for offering to get this merged.

**Comment by SteveSandersonMS** [comment]
BTW Javier and I agreed this is the right icon already.

**Review by ryanbrandenburg — CHANGES_REQUESTED** [review]
When you add new files to templates you must [update the baseline](https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/test/template-baselines.json#L891)

**Comment by SteveSandersonMS** [comment]
Thanks @ryanbrandenburg - I wasn't aware of that. Done.

**Review by ryanbrandenburg — APPROVED** [review]

**Review by dougbu — APPROVED** [review]

**Pull request merged**
