### PR TITLE
onBoard package validation

### LINKED ISSUE #33981: Use Package Validation SDK
https://devblogs.microsoft.com/dotnet/package-validation/

Suppressions: https://github.com/dotnet/sdk/blob/18b394cf392030683ec0e7abd2ce588803d8d514/src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/SuppressionTests/SuppressionEngineTests.cs#L139

Baseline Suppressions: https://github.com/dotnet/sdk/blob/18b394cf392030683ec0e7abd2ce588803d8d514/src/Tests/Microsoft.DotNet.ApiCompatibility.Tests/SuppressionTests/SuppressionEngineTests.cs#L190

`DisablePackageBaselineValidation` to disable baseline validation in a given project (we want this to be conditioned on `IsServicingBuild`)

https://github.com/dotnet/msbuild/issues/4249 for conditionally using SDK tags in a project

### PR DESCRIPTION
**Pull request by Anipik**
Fixes #33981

> How/When can we get this version updated automatically? I believe it comes from dotnet/sdk right now - we could add a back-edge subscription that only fires once a week or so?

yes adding a toolset dependency to dotnet/sdk would be the best way to get the most recent changes. This tool is now part of the sdk as well so you can get that by using the daily sdk bits as well

> What else should we do to validate that this is doing what we expect? I see the below in a binlog of one of our shipping projects

sadly there is no other way that to check the logs to verify. We talked about adding something but it the eventual decision there was no

The file contention issues faced earlier in https://github.com/dotnet/aspnetcore/pull/34122 got resolved by https://github.com/dotnet/sdk/pull/20136

we should also port this change to release/6.0 branch

We will need an updated sdk for this one

### CODE REVIEW

**Comment by wtgodbe** [comment]
I'm not sure what's up with the source build errors:

>   /__w/1/s/.dotnet/sdk/6.0.100-rc.1.21426.23/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(246,5): error NETSDK1004: Assets file '/__w/1/s/artifacts/source-build/self/src/artifacts/obj/Microsoft.Extensions.Caching.SqlServer/project.assets.json' not found. Run a NuGet package restore to generate this file. [/__w/1/s/artifacts/source-build/self/src/src/Caching/SqlServer/src/Microsoft.Extensions.Caching.SqlServer.csproj]

@dseefeld any ideas?

**Comment by dseefeld** [comment]
> I'm not sure what's up with the source build errors:
> 
> > /__w/1/s/.dotnet/sdk/6.0.100-rc.1.21426.23/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(246,5): error NETSDK1004: Assets file '/__w/1/s/artifacts/source-build/self/src/artifacts/obj/Microsoft.Extensions.Caching.SqlServer/project.assets.json' not found. Run a NuGet package restore to generate this file. [/__w/1/s/artifacts/source-build/self/src/src/Caching/SqlServer/src/Microsoft.Extensions.Caching.SqlServer.csproj]
> 
> @dseefeld any ideas?

It looks to me like this is hitting the same issue described in https://github.com/dotnet/arcade/issues/7795.  Looking at the binlog, `Microsoft.Extensions.Caching.SqlServer.csproj` is marked `ExcludeFromSourceBuild`, but some targets are still being executed for that project.

**Comment by ericstj** [comment]
Likely has to do with how the validation targets are sequenced + how arcade disables the project entrypoints.

Arcade disables entrypoints by overriding them:
https://github.com/dotnet/arcade/blob/e7ede87875f41a9b3df898ae08da5ebc96e24f56/src/Microsoft.DotNet.Arcade.Sdk/sdk/Sdk.targets#L14-L15
https://github.com/dotnet/arcade/blob/e7ede87875f41a9b3df898ae08da5ebc96e24f56/src/Microsoft.DotNet.Arcade.Sdk/tools/Empty.targets#L16-L21

However the targets still exist, so things sequenced before/after will still run.  I think we can workaround this by conditioning validation not to run when things are excluded from source-build.  Perhaps there is some secondary property we can use to do this?  Looks like today these targets look at `IsPackable` and that happens to be set to true, even in the case that source-build is disabling stuff.

**Comment by dseefeld** [comment]
I opened a PR in Arcade to skip these targets when `ExcludeFromSourceBuild` is true.  https://github.com/dotnet/arcade/pull/7825  @ericstj Is the workaround that you're proposing a general fix for this or just for this PR?  If general, maybe my change in Arcade is not needed?

**Comment by ericstj** [comment]
I'm not sure we need a change in Arcade yet.  I'd like someone  to observe the state of the project when ExcludeFromSourceBuild to see if there is something that we should use as a condition to determine when to run validation.

It seems to me that there ought to be a crisp contract around project state (EG: a single property) that should indicate "I am building and producing a package".  We should establish what that is, and if necessary make the changes to honor it, either in package validation or arcade.  Once we have such a property we can use that in any Target that might hang it self off of Build or Pack to turn itself off during source build.

**Review by wtgodbe — APPROVED** [review]
Looks good to me!

**Pull request merged**
