### PR TITLE
Update SDK to 7.0.100-preview.2.22078.1

### PR DESCRIPTION
**Pull request by captainsafia**
Weekly build-ops rotation update.

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Comment by dougbu** [comment]
@captainsafia the new SDK updates the edit configuration or how it's interpreted; doesn't seem to like spacing in e.g.

``` c#
<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)]T>
```

**Comment by captainsafia** [comment]
@dougbu Yep, I'm trying to grok why it no longer respects the fact that we have `IDE0055` silenced/reduced to warning in our editor config.

**Review by TanayParikh — APPROVED** [review]
LGTM though looks like the CI found some more `IDE0055`.

**Comment by pranavkm** [comment]
The rule is enabled in CLI builds and the CLI update is discovering new places that weren't previously being flagged. Seems fine.

**Review by pranavkm — APPROVED** [review]

**Pull request merged**
