### PR TITLE
[release/6.0] Always build App.Ref and the targeting packs

### LINKED ISSUE #39471: Microsoft.AspNetCore.App.Ref needs to be produced and versioned correctly in servicing for source-build
Currently building release/6.0 for 6.0.1 doesn't produce a Microsoft.AspNetCore.App.Ref package.  This is because the package wasn't serviced in 6.0.1.  6.0.0 is the active version yet the build doesn't produce it.  This breaks source-build which needs to produce the entire product.  

In previous versions, source-build handled this by treating the package as a reference package via https://github.com/dotnet/source-build-reference-packages.  This is no longer an option in 6.0 with the introduction of roslyn analyzers (e.g source) in the package.

dotnet/runtime made changes in 6.0 to support this [here](https://github.com/dotnet/arcade/blob/e7ede87875f41a9b3df898ae08da5ebc96e24f56/src/Microsoft.DotNet.SharedFramework.Sdk/targets/Microsoft.DotNet.SharedFramework.Sdk.targets#L19).

### PR DESCRIPTION
**Pull request by dougbu**
# [release/6.0] Always build App.Ref and the targeting packs

- remove `$(IsTargetingPackBuilding)` entirely
- 6.0.x version of #39568

## Description

Remove `$(IsTargetingPackBuilding)` settings and remove all use of the property. For example, it's not necessary to reference Microsoft.AspNetCore.App.Runtime.csproj when Microsoft.AspNetCore.App.Ref.csproj won't build; references to Microsoft.AspNetCore.App.Ref.csproj are all we need.

In detail:
- where `Condition`s were positive (`$(IsTargetingPackBuilding)` or `$(IsTargetingPackBuilding)' == 'true'`), remove the `Condition` or its relevant portion
- otherwise, (`! $(IsTargetingPackBuilding)` or `$(IsTargetingPackBuilding)' != 'true'`), remove the affected block or the relevant portion of the `Condition`

nit: simplify any leftover `Condition`s if possible

Fixes #39471

## Customer Impact

Without this change, we're unable to create source-build tarballs except with significant hacks.

We also realized skipping builds of the &hellip;Ref packages and targeting pack installers would be uncommon given their new analyzer and code generator content in 6.0.x. Decided always building these assets simplified everything in the relevant repos.

In this repo, not releasing the targeting packs was a major exception. We build and pack everything else for every release and have since 3.1.0.

## Regression?

- [ ] Yes
- [x] No

The main difference from 5.0.x in this release is the analyzer and code generator assemblies in our targeting packs. This content makes it easier to justify building the targeting packs for every release.

## Risk

- [ ] High
- [ ] Medium
- [x] Low

This PR removes some complexity from our build and should simplify our release process.

## Verification

- [x] Manual (required)
- [ ] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

This PR does not change individual packages. It just ensures Microsoft.AspNetCore.App.Ref.nupkg and our targeting pack installers are always created.

----

## When servicing release/2.1

- [ ] Make necessary changes in eng/PatchConfig.props

### CODE REVIEW

**Comment by dougbu** [comment]
@Pilchie should we treat this one as ask-mode due to the release implications i.e. shipping more❔

**Comment by Pilchie** [comment]
I can bring it up in Tactics tomorrow.

**Review by wtgodbe — APPROVED** [review]

**Comment by leecow** [comment]
Need to confirm we're doing the right thing on update and uninstall.

**Comment by dougbu** [comment]
Rebased on `brecon/60cookie` to confirm continued success

**Comment by TanayParikh** [comment]
@dougbu can this be merged now given the CI is passing and it is servicing approved?

**Comment by wtgodbe** [comment]
Closing in favor of https://github.com/dotnet/aspnetcore/pull/39924

**Comment by dougbu** [comment]
> can this be merged now given the CI is passing and it is servicing approved?

@TanayParikh /fyi what @wtgodbe did is a bit cleaner because the change will go in together w/ the new branding. We considered force-merging the branding PRs then doing these but either works. And both are better than doing a lot of stuff before branding is done.

**Pull request closed without merging**
