### PR TITLE
Stop producing unused package archives

### PR DESCRIPTION
**Pull request by natemcmaster**
Resolves https://github.com/aspnet/AspNetCore/issues/4265

The following package archives which are no longer used by partner teams. It is expected that these will be replaced by targeting packs.

* LZMA (was used by dotnet-cli)
* zips (ended up not getting used by anyone)
* Compat zips (was used by Antares)

### CODE REVIEW

**Comment by natemcmaster** [comment]
FYI @livarcocc @nguerrera @dsplaisted - goodbye, LZMA!

**Comment by livarcocc** [comment]
So happy for us all.

**Comment by nguerrera** [comment]
🎄🎁

**Review by JunTaoLuo — APPROVED** [review]
Brings a tear of joy to my eye.

**Pull request merged**
