### PR TITLE
Generate Composite Images Redistributable

### PR DESCRIPTION
**Pull request by ivdiazsa**
# Generate Composites Redistributable

This is still a WIP. The purpose of these changes is to be able to generate a distributable with the full composite images enabled.

## Description

This change modifies _Microsoft.AspNetCore.App.Runtime.csproj_ located in _aspnetcore/src/Framework/App.Runtime/src_ to also generate the distributable with the composite images. This is currently achieved by taking the composite output (more details can be found in its original PR's #41855 and #42296) and bundling it with the rest of the installers.

The end goal of this change is to make the composites easily accessible, in order to be used to build the .NET 7 Docker images, which are afterwards shipped to customers.

### CODE REVIEW

**Comment by ivdiazsa** [comment]
### WIP Next Steps

So far, we bundle the full _obj/Composite_ folder and that's it. However, the end result expects to build it using the same layout the default zip/tar.gz has. I've found that this is found in _obj\RedistSharedFx.Layout_. However, the problem at hand is that we need to somehow differentiate between the ASP.NET and the Runtime binaries, so we can send them to their appropriate subfolders (e.g. Microsoft.NetCore.App).

After some experimenting, I found out that due to how the runtime works, this change doesn't require any major overhauling. Just send the composite r2r image to Microsoft.NetCore.App, alongside the binaries previously used to generate it and it will work. So, the only missing thing is, as mentioned in the above paragraph, distinguish between ASP.NET and Runtime binaries in the Composite folder. Do you have any recommendations as to how we can proceed with this @dougbu?

**Comment by dougbu** [comment]
I suggest changing the `$(CompositesTargetDir)` layout to match the existing redist layout or copy the files into a new layout folder.

Separately, `$(CompositesTargetDir)` _should_ be defined in the target you're adding but for some reason is empty. Might be a typo in the `tar` command. But you'll need to handle the cases where `$(CrossgenOutput)` is `false`, likely by creating the composite image unconditionally instead. (We only override `$(CrossgenOutput)` to avoid problems testing on other platforms.)

**Comment by dougbu** [comment]
Validating this PR isn't possible because it deals only w/ artifacts and the new ones won't be published for builds of a fork. Suggest either switching to a branch in this repo or pushing your branch to the AzDO dotnet-aspnetcore repo. I also suggest removing all `*_CompositeImages` entries in ci.yml, including the existing one. Need only the new archives and those will be included in BlobArtifacts.

**Comment by ivdiazsa** [comment]
Okok I see. Removing the `ci.yml` entries now I understand, but could you please elaborate more on branch switching Doug? Like which branch should I be working on? Or would I be allowed to push my branch into this repo, as some of the existing ones I see belong to other people?

**Comment by dougbu** [comment]
@ivdiazsa I meant you should avoid using a fork. If you lack permissions to push to this repo, let me know and I'll check your branch out and push it here tomorrow.

**Comment by ivdiazsa** [comment]
Migrated to #42506.

**Pull request closed without merging**
