### PR TITLE
Enumerate paramnames on startup

### LINKED ISSUE #46010: Array will allocate less and little faster when creating RequestDelegateFactoryOptions in  CreateRDFOptions
It uses List<string>, which gets assigned to `RouteParameterNames` as `IEnumerable.` 
https://github.com/dotnet/aspnetcore/blob/432e6a061f28dda696ba16bc5442328d23b25d93/src/Http/Routing/src/RouteEndpointDataSource.cs#L260

Ran a benchmark with 10 strings of length 6. The results are below.
image

Another run:
image

The benchmark code used:

```
public class Benchmarks
    {
        private const int Length = 10;
        private readonly IReadOnlyCollection<string> _readOnlyCollection = new List<string>() { "param1","param2", "param1","param2", "param1","param2", "param1","param2", "param1","param2"}.AsReadOnly();
        [Benchmark]
        public void Add10StringsToList()
        {
            List<string> parameters = new(Length);
            foreach (var s in _readOnlyCollection)
            {
                parameters.Add(s);
            }

            
        }

        [Benchmark]
        public void Add10StringsToArray()
        {
            var parameters = new string[Length];
            var i = 0;
            foreach (var s in _readOnlyCollection)
            {
                parameters[i] = s;
                i++;
            }
            
        }
    }
```

### PR DESCRIPTION
**Pull request by marafiq**
# Enumerate endpoint parameter names on startup instead of allocating a list.

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes 

## Use Enumerable instead of List to save allocation

Use of `IEnumerable<string>` when getting the endpoint parameters names from the collection, which then gets used to create the `RequestDelegateFactoryContext`

Fixes https://github.com/dotnet/aspnetcore/issues/46010

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=46086) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=46086) before we can accept your contribution.<br/><br/>:x: marafiq [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=46086)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=46086) it.</sub>

**Comment by adityamandaleeka** [comment]
@mitchdenny Assigning this to you to look at since the corresponding issue is assigned to you.

**Comment by mitchdenny** [comment]
Also looping in @captainsafia  since she would be interested in seeing the PR and is doing some stuff in AOT in this area.

On the surface this doesn't look like a breaking API change (good) - but in terms of performance impact in an actual application I don't think I can see the impact. One thing to point out with the benchmark is that you've got 10 route parameters - that is actually a lot when you consider even quite nested APIs such as: 

```/customers/{customer}/contacts/{contact}/addresses/{address}```

I re-ran the benchmark with 3 route parameters and the results aren't quite as dramatic in that case:

```
|                          Method |      Mean |     Error |    StdDev |   Gen0 | Allocated |
|-------------------------------- |----------:|----------:|----------:|-------:|----------:|
|              Add10StringsToList | 58.127 ns | 1.1880 ns | 1.7414 ns | 0.0278 |     120 B |
|             Add10StringsToArray | 49.984 ns | 0.8905 ns | 0.8330 ns | 0.0204 |      88 B |
|     UseEnumerableWithLinqSelect | 21.989 ns | 0.3592 ns | 0.2999 ns | 0.0167 |      72 B |
| UseEnumerableWithLocalFuncYield |  9.093 ns | 0.2014 ns | 0.1978 ns | 0.0111 |      48 B |
```

Let's imagine an application with a modest number of 3 parameter routes (say a 10):



|Scenario|Startup time contribution (10 * mean ns)|Memory contribution (10 * mean allocations)
|-|-|-|
|Without optimization|580 **nano**seconds|1200 bytes|
|With optimization|90 **nano**seconds|480 bytes|

**Comment by marafiq** [comment]
Thanks for taking a look at us @mitchdenny 
Three route parameters for an endpoint are a good default. One thing to note is that the code will run for every endpoint with parameters.
>but in terms of performance impact in an actual application I don't think I can see the impact

As you have seen in your benchmark run, there are slight improvements in allocation and some ns. There is not nothing else in terms of impact.

**Review by mitchdenny — APPROVED** [review]
Thanks for the contribution!

**Review by halter73 — APPROVED** [review]
We will probably not merge this kind of micro-optimization unless it is on a really hot path in the future. If the optimization is large enough that it would show a statistically significant impact on the overall `RequestDelegateFactory.Create(Delegate)` call, that would be a different story.

That said, I appreciate the initiative! Given that the microbenchmark shows an improvement, and that the code is as easy to follow as it was before imo, I think we should merge the PR this time.

Thanks for contributing!

**Pull request merged**
