### PR TITLE
Rename forgot password button

### PR DESCRIPTION
**Pull request by Kahbazi**
#5413

### CODE REVIEW

**Comment by javiercn** [comment]
@blowdart LGTM, any objection to merge?

**Comment by blowdart** [comment]
Sure, fine by me

**Review by javiercn — APPROVED** [review]

**Comment by javiercn** [comment]
I've retriggered the build. will merge merge once the build is green or there are no related failing tests

**Comment by javiercn** [comment]
@Eilon @mkArtakMSFT All the test failures here are unrelated to this change. This is good to merge.

**Comment by Eilon** [comment]
@javiercn - go for it. Please update the bug's milestone and then close as appropriate.

**Comment by Eilon** [comment]
Oh sorry you want an admin to override?

**Comment by Eilon** [comment]
Though this failure is certainly unrelated, I'd rather wait for it to be fixed:

```
019-01-29T17:31:56.0411320Z   Application startup exception: System.NotSupportedException: Duplicate definitions of 'OverloadedMethod'. Overloading is not supported.
2019-01-29T17:31:56.0463420Z      at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.DiscoverHubMethods() in /_/src/SignalR/server/Core/src/Internal/DefaultHubDispatcher.cs:line 544
2019-01-29T17:31:56.0464090Z      at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1..ctor(IServiceScopeFactory serviceScopeFactory, IHubContext`1 hubContext, IOptions`1 hubOptions, IOptions`1 globalHubOptions, ILogger`1 logger) in /_/src/SignalR/server/Core/src/Internal/DefaultHubDispatcher.cs:line 38
```

**Comment by BrennanConroy** [comment]
Search for "[Fail]" to find the actual failing tests. The text you copied is normal expected output.

**Comment by javiercn** [comment]
I normally just check the failed tests on the tests section of the azure pipelines build

**Comment by Eilon** [comment]
Oh sorry my bad. A Chrome plugin made the rendering all weird so I didn't see the actual failures...

**Comment by javiercn** [comment]
@Eilon Yeah, I wanted admin override, given that this breaks literally nothing

**Comment by Eilon** [comment]
Done, thanx! We have an email thread where we're discussing this policy now...

**Comment by Eilon** [comment]
But do remember to update the bug milestone/etc.

**Comment by javiercn** [comment]
Done

**Pull request merged**
