### PR TITLE
Add WebApi-CSharp Template Toggle Description (#37367)

### LINKED ISSUE #37864: Incorrect info tooltip for 'Enable OpenAPI support' checkbox
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Incorrect-info-tooltip-for-Enable-OpenA/1563452)._

---
[severity:It bothers me. A fix would be nice]
When creating a new "ASP.NET core Web API" project in Visual Studio 2022 (v17.0 Preview 6.0), the **Additional Information** dialog that appears during the creation process has a checkbox labelled 'Enable OpenAPI support'. It has a little info icon next to it, and if you mouse over that, it displays a tooltip.

This tooltip's text describes the _opposite_ of what the checkbox does

! [image.png] (https://aka.ms/dc/image?name=B40786b4b22e64fdd938b6d5377529e30637708221348249618_20211026-061532-image.png&tid=40786b4b22e64fdd938b6d5377529e30637708221348249618)

Checking the button enables OpenAPI support. But the tooltip says it disables OpenAPI support.

Presumably whoever wrote that was thinking "I'll describe what happens when they uncheck this" because it is checked by default. But there are two problems here;

1. it displays the same text whether checked or not, so describing what it would do if you uncheck it is misleading when it's already unchecked
2. the checkbox immediately above it doesn't use this inverted logic - its tooltip says what happens when it is checked

(The checkbox above also explicitly states what happens when unchecked in the main text of the checkbox. Perhaps the OpenAPI one could follow suit, although I think that explicit description of the unchecked behaviour is probable more important on the top checkbox because this is really switching between two quite different modes, whereas the lower checkbox just turns a feature on or off. Arguably that top checkbox should be a pair of radio buttons.)

---
#### Feedback Bot on 10/26/2021, 00:24 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by captainsafia**
## Description

This PR adds a clearer description to the "Enable OpenAPI" open in Web API templates. 

## Customer Impact

This change does not introduce any functional changes but makes it easier for customers to understand what happens when they check/uncheck the "Enable OpenAPI" item in the VS new project experience.

## Regression?

- [ ] Yes
- [X] No

## Risk

- [ ] High
- [ ] Medium
- [X] Low

This change adds more documentation and does not introduce functional changes to the UI.

## Verification

- [X] Manual (required)
- [ ] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [X] N/A

----

Closes #37864

### CODE REVIEW

**Review by pranavkm — APPROVED** [review]

**Comment by pranavkm** [comment]
Do we need to localize this text?

**Review by TanayParikh — APPROVED** [review]

**Comment by captainsafia** [comment]
> Do we need to localize this text?

Any guidance around how to localize here? I noticed from https://github.com/dotnet/aspnetcore/pull/30101 that it seems the localizations get inserted from the WebTools repo?

**Comment by phenning** [comment]
@captainsafia responded offline with a link to the generated files. Also, in a more general sense, the templates should be updated to use the new localization mechanism provided by the core template engine going forward. This would allow them to have their metadata localized within "dotnet new" and better streamline localization within Visual Studio. @vlada-shubina   and @DavidKarlas should be able to give some guidance on this.

**Comment by bekir-ozturk** [comment]
Hi @captainsafia,
I will describe the process of switching to new localization format. But this will require getting all your templates localized again. With release so close, I'm not sure if there is time.

Starting .NET 7, we have an [MSBuild task](https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet7&package=Microsoft.TemplateEngine.Tasks&protocolType=NuGet&version=7.0.100-alpha.1.21554.1) to ease this process. This should be the way going forward. But since this PR is about .NET 6, I won't give details here. Let me know if you need to apply this to main branch and I can help you further.

Starting .NET 6, we have Template Localizer tool to help with this. You should:
- Clone the repo to your local machine and create a branch for your changes
- Install the TemplateLocalizer tool
- Run the tool on your template folder (this will generate all the loc files on disk).
- Commit and push the changes to the repo, then merge.
- Loc team will automatically receive the loc files and provide the translations in a later PR.

You can install Template Localizer tool using:
```dotnetcli
dotnet tool install -g Microsoft.TemplateEngine.TemplateLocalizer
```

Run it on the root template directory using:
```dotnetcli
dotnet-template-localizer export <path_to_root_template_directory> --recursive
```

**Comment by captainsafia** [comment]
> I responded offline with a link to the generated files. Also, in a more general sense, the templates should be updated to use the new localization mechanism provided by the core template engine going forward. This would allow them to have their metadata localized within "dotnet new" and better streamline localization within Visual Studio. @vlada-shubina and @DavidKarlas should be able to give some guidance on this.

Thanks! I've updated the localizations in the templates and created https://github.com/dotnet/aspnetcore/issues/38102 to track updating our infra.

**Pull request merged**
