### PR TITLE
[master] Update hosted (AzDO) and BYOC (dnceng) agents used in our builds

### PR DESCRIPTION
**Pull request by dougbu**
- dotnet/aspnetcore-internal#3540
- nit: Consistently use `in` / `notin` with `Build.Reason`
  - YAML was inconsistent and this aligns w/ the Arcade code

### CODE REVIEW

**Review by HaoK — COMMENTED** [review]
So just for my information sake, what's the functional difference here?  Build Reason can sometimes contain more than one reason which would fail our checks?

**Comment by dougbu** [comment]
@HaoK as I said, changing this addressed a nit. There should be no functional difference but we were inconsistent in our YAML and when compared with the Arcade YAML files.

Of course, the Arcade YAML may be using `in` and `notin` for reasons 😈

**Review by HaoK — APPROVED** [review]

**Review by JunTaoLuo — APPROVED** [review]

**Review by Pilchie — APPROVED** [review]

**Comment by BrennanConroy** [comment]
Can we merge this please? I think this is now causing failures on builds because mac10.13 is being blocked on AzDo for some reason.

**Comment by anurse** [comment]
Are we getting this in to preview 2? We're getting hit by the macOS 10.13 brownout there as well.

**Comment by dougbu** [comment]
I have #19674 open already but wasn't clear on whether it was approved for merging 'til this morning. I'll go through the PRs for preview2 in a sec.

**Pull request merged**
