### PR TITLE
added beta7 coreclr sample

### PR DESCRIPTION
**Pull request by jchannon**
added beta7 coreclr sample :smile: 

ties it into the aspnet docker CI build https://github.com/aspnet/aspnet-docker/pull/84

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
is the only diff the dockerfile?

**Comment by jchannon** [comment]
yup

**Comment by ahmetalpbalkan** [comment]
Then you can probably symlink all the other files. I'm no big fan of duplicating things just because we need this folder structure in docker image CI. 

Actually we may even rewrite the CI scripts over there to replace the image name in the dockerfile here.

**Comment by jchannon** [comment]
Yup makes sense. Want me to symlink to beta 7 for now?

**Comment by ahmetalpbalkan** [comment]
I'll let repo owners decide. Maintaining symlinks on Windows might be a pain :-)

**Comment by Eilon** [comment]
Closing because this is no longer needed. Thanks!

**Pull request closed without merging**
