### PR TITLE
Add Dockerfiles and improve instructions on how to use the ASP.NET Docker image

### PR DESCRIPTION
**Pull request by tlk**
Addresses #536

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@tlk__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by msotclas** [comment]
__@tlk__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by jasonwilliams200OK** [comment]
Thanks @tlk! :+1:

**Comment by garora** [comment]
Sorry, I m  interrupting you guys. Does this mean everyone need to sign
this who want to contribute across the glob?

**Comment by Eilon** [comment]
@garora only certain contributions require CLAs. This is the new .NET Foundation CLA that's being used on all new projects (the Roslyn compiler, the CLR, and now ASP.NET and Entity Framework). The new CLA is simpler than the old one and is used more broadly among different projects. If you've already signed the new .NET Foundation CLA for another project, then there is no need to sign again.

**Comment by garora** [comment]
Awesome!  I will sign it tomorrow.  Can you please share the link?

**Comment by Eilon** [comment]
@garora https://cla2.dotnetfoundation.org/

**Comment by glennc** [comment]
This is still up-to-date right? I don't think anything is changed but since it has taken me so long to get to this I wanted to make sure.

**Comment by moander** [comment]
There is one update to the dockerfile I suggest you implement, but i'm not sure where to post changes for pull requests?


Morten




On Fri, Jun 12, 2015 at 7:10 PM -0700, "Glenn Condron" <notifications@github.com<mailto:notifications@github.com>> wrote:


This is still up-to-date right? I don't think anything is changed but since it has taken me so long to get to this I wanted to make sure.

-

**Comment by jasonwilliams200OK** [comment]
> but i'm not sure where to post changes for pull requests?

If it is your Pull Request, then you just need to add commit (or edit an existing one) in your branch, from where the PR is originated. Any change in your branch will appear in the opened PR, until it is merged. Note that a PR is 1:1 association between branches, regardless of forks.

If it is not your Pull Request, then you can either:
* Comment on each line of code in diff view (for example https://github.com/aspnet/Home/pull/537/files), to ask the OP of PR to make the changes (=> "amending the commit": `git --amend`).
* Send a PR to the OP's fork from your form on the same branch. So, while this PR is opened, and OP of PR merges your PR in his branch, it will automatically appear here.

**Comment by moander** [comment]
@jasonwilliams200OK I created a pull request on the OP's fork.

https://github.com/tlk/aspnet-home/pull/1

**Comment by tlk** [comment]
@glennc it's still up-to-date AFAICT :+1:

**Comment by glennc** [comment]
Ok, I'm ok with this then :). Thanks for the pr, and sorry for being so slow at processing it.

**Pull request merged**
