### PR TITLE
Merging internal commits for release/7.0

### PR DESCRIPTION
**Pull request by vseanreesermsft**

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Comment by wtgodbe** [comment]
@MackinnonBuck could you take a look at these blazor template test failures?

> BlazorWasmHostedTemplate_IndividualAuth_NoHttps_Works_WithOutLocalDB_ProgramMain

> System.ComponentModel.Win32Exception : An error occurred trying to start process 'dotnet-ef' with working directory '/tmp/helix/working/A6D30982/w/B4780A0D/e/Templates/BaseFolder/AspNet.Uutzfhzkapmb/Server'. No such file or directory

Lots of failures of this type across various OSes

**Comment by MackinnonBuck** [comment]
I haven't been able to narrow down the cause just yet, but it seems EF-related. My guess is that the "DotNetEfFullPath" environment variable isn't being set up correctly and that's causing [this code](https://github.com/dotnet/aspnetcore/blob/8d157a1aebc3351430a439c1a92ccd5506503412/src/ProjectTemplates/Shared/Project.cs#L216) to use the fallback "dotnet-ef" command. Trying to reproduce locally.

**Comment by MackinnonBuck** [comment]
It seems that `dotnet-ef` 8.0.0 is getting installed:

```text
/datadisks/disk1/work/BC800A71/t/630ced86-05ff-4c05-8274-385fc9b24e15/restore.csproj : error NU1202: Package dotnet-ef 8.0.0 is not compatible with net7.0 (.NETCoreApp,Version=v7.0) / any. Package dotnet-ef 8.0.0 supports: net8.0 (.NETCoreApp,Version=v8.0) / any
```

**Comment by wtgodbe** [comment]
@dsplaisted is this the bug where the `dotnet tool install` silently installs the latest version of a package, rather than what was requested?

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/pull/52094 is this PR without the SDK update. If the tests pass, that would point to the `dotnet tool install` bug

**Comment by dsplaisted** [comment]
@wtgodbe The bug you're referring to was with local tools, and I would be very surprised if it were to show up in 7.0, as it was related to some major tools refactoring that is only in 8.0.

In this case, it looks like this is the command line used to install the tool:

> Running '/datadisks/disk1/work/BC800A71/p/dotnet-cli/dotnet tool install dotnet-ef --tool-path /datadisks/disk1/work/BC800A71/w/97FC0871/e --add-source /datadisks/disk1/work/BC800A71/p'

That command will install (as a global tool) the latest version available on the feeds.  So now that .NET 8 has been released, it's trying to install the 8.0 version of dotnet-ef, which fails because it's not compatible with .NET 7.

**Comment by wtgodbe** [comment]
If https://github.com/dotnet/aspnetcore/pull/52045/commits/4f873f6cbcdaab267aacd0d0db4a73db3fb964c8 works I'll port it to 8 & main

**Comment by wtgodbe** [comment]
Ports: https://github.com/dotnet/aspnetcore/pull/52103, https://github.com/dotnet/aspnetcore/pull/52104

**Pull request merged**
