### PR TITLE
Add comment to gRPC template tests SkipOnAlpine attribute

### PR DESCRIPTION
**Pull request by JamesNK**
re: https://github.com/dotnet/aspnetcore/pull/46462#discussion_r1098795980

### CODE REVIEW

**Review by adityamandaleeka — APPROVED** [review]

**Comment by JamesNK** [comment]
@dotnet/aspnet-build Do PRs run tests on alpine? I don’t want to merge this and then break main build.

**Comment by adityamandaleeka** [comment]
@JamesNK That's why I mentioned musl above. It runs on an alpine container:

mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-WithNode

**Comment by JamesNK** [comment]
Hmm, I think it's built there, but I don't think the template tests run there.

Helix Alpine queue only runs on the main build:
https://github.com/dotnet/aspnetcore/blob/5bd03bbf50d4e209ec9119a0e98f2da9a247c766/eng/targets/Helix.Common.props#L43

How can I run here from a PR? Temporarily update Helix.Common.props to add the queue to PR?

**Comment by dougbu** [comment]
> Hmm, I think it's built there, but I don't think the template tests run there.
> 
> Helix Alpine queue only runs on the main build:
> https://github.com/dotnet/aspnetcore/blob/5bd03bbf50d4e209ec9119a0e98f2da9a247c766/eng/targets/Helix.Common.props#L43
> 
> How can I run here from a PR? Temporarily update Helix.Common.props to add the queue to PR?

If by "main build" you mean [`aspnetcore-helix-matrix`](https://dev.azure.com/dnceng-public/public/_build?definitionId=85), then updating Helix.Common.props could work. The alternative is to head over to the pipeline and click `Run Pipeline`, selecting this branch.

You may want to rebase the branch first because `Run Pipeline` won't do-merge w/ 'main' the way CI builds do.

**Comment by JamesNK** [comment]
The templates still fail on Alpine:
image

The issue was closed because a workaround was provided, and we're not doing that on our machine. I'm going to change this PR to update the attribute description.

**Review by adityamandaleeka — APPROVED** [review]

**Comment by eerhardt** [comment]
> a workaround was provided

IMO that workaround is bogus. Installing the glibc compat package is a crutch and not a real solution. If we support Alpine (which we say we do https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md), we should be building a musl-compatible binary. This is analogous to saying we support ARM64, but requiring Rosetta 2 to run on a macOS M1 machine.

**Pull request merged**
