### PR TITLE
[release/6.0] Update Helix.Common.props

### PR DESCRIPTION
**Pull request by JamesNK**
Backport of https://github.com/dotnet/aspnetcore/pull/45737 to release/6.0

### CODE REVIEW

**Comment by JamesNK** [comment]
Failing with:
> Playwright does not support chromium on mac12

**Comment by JamesNK** [comment]
If the change to upgrade Playwright is difficult, then an alternative is to leave the `release/6.0` branch targeting `OSX.1100.Amd64.Open`.

**Comment by captainsafia** [comment]
> @dotnet/aspnet-build @captainsafia If the change to upgrade Playwright is difficult, then an alternative is to leave the `release/6.0` branch targeting `OSX.1100.Amd64.Open`. If we don't update the branch to 12.0, then Playwright doesn't need to be changed.

I think there should be a few more tweaks in the ProjectTemplateTests.

Another thing to note is that the Playwright.Sharp package referenced in this branch is deprecated anyways so the upgrade would be prudent regardless.

**Comment by HaoK** [comment]
@captainsafia I have some concerns with this PR resulting in pretty big deviations from current bits in the infrastructure, there was some refactoring done by @dougbu in https://github.com/dotnet/aspnetcore/commit/0be2c29d9c09da46e95047afb41514fb58137c26

I really think we want to avoid a major chism between test runner/playwright code.  I don't think we get much (any?) benefits from running playwright tests on 6.0, so maybe we can just pull the plug on it entirely in servicing if its only for smattering of tests.

**Comment by captainsafia** [comment]
> I really think we want to avoid a major chism between test runner/playwright code.  I don't think we get much (any?) benefits from running playwright tests on 6.0, so maybe we can just pull the plug on it entirely in servicing if its only for smattering of tests.

Assuming these Playwright tests aren't providing any value, we might benefit from skipping them altogether. However, if the Playwright tests _do_ need to run in .NET 6, it seems like there is some value in getting us onto the non-deprecated testing library on this branch, especially if it is LTS.

> @captainsafia I have some concerns with this PR resulting in pretty big deviations from current bits in the infrastructure, there was some refactoring done by @dougbu in https://github.com/dotnet/aspnetcore/commit/0be2c29d9c09da46e95047afb41514fb58137c26

I believe those deviations exist regardless given that the referenced commit is in 7.0 and 6.0. I didn't modify anything in the `TestRunner` in 6.0 although I am not sure if your point is that the `TestRunner` in 6.0 should be updated...

**Comment by HaoK** [comment]
I just mean this PR contains a lot of changes that look specific to 6.0, like going from selected.Length to Count...  and it looks like @TanayParikh removed this directory in main for 7.0 here: https://github.com/dotnet/aspnetcore/commit/5247048126a2bdfac17d44d63d497055a53d08a2

So I think instead we should just nuke the files in 6.0 as well.

**Comment by wtgodbe** [comment]
> So I think instead we should just nuke the files in 6.0 as well.

If the team has sufficient confidence that the coverage in 7.0/main provides enough validation for 6.0, I'm fine with that

**Comment by wtgodbe** [comment]
Branches are open for Feb until 1/16

**Comment by HaoK** [comment]
Cool, replacing this PR with https://github.com/dotnet/aspnetcore/pull/45852

**Pull request closed without merging**
