### PR TITLE
Add Microsoft.AspNetCore.Server.Kestrel.Transport.Quic to SharedFx

### LINKED ISSUE #34439: Include Microsoft.AspNetCore.Server.Kestrel.Transport.Quic in the shared runtime
As of dotnet-sdk-6.0.100-preview.1.21366.55-win-x64 and  Microsoft.AspNetCore.App 6.0.0-preview.7.21363.16, Microsoft.AspNetCore.Server.Kestrel.Transport.Quic is not shipping in the shared runtime. 

msquic.dll is included in Microsoft.NETCore.App 6.0.0-preview.7.21365.21.

Moving it into the shared runtime will allow us to clean up the user experience (e.g. kestrel can include the quic transport by default).

### PR DESCRIPTION
**Pull request by wtgodbe**
Fixes https://github.com/dotnet/aspnetcore/issues/34439. Adds the library to the SharedFx & Targeting pack, and removes the package. Still need to release note this.

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]

**Comment by Tratcher** [comment]
Is this something we should consider for p7, removing the package before anybody really uses it?

**Comment by Pilchie** [comment]
This doesn't expose any exchange types from `System.Net.Quic`?

**Comment by Tratcher** [comment]
Right, the System.Net.Quic types aren't use publicly:
https://github.com/dotnet/aspnetcore/blob/e034ff60a86b9ad28a4e8c558592ca302cd63fea/src/Servers/Kestrel/Transport.Quic/src/PublicAPI.Unshipped.txt#L28-L43

**Comment by wtgodbe** [comment]
Doesn't hurt to ask. I'll send the mail after I fix the build issue.

**Review by JamesNK — APPROVED** [review]

**Pull request merged**
