### PR TITLE
Changed LogLevel to Information instead of warning for EphemeralDataProtectionProvider

### LINKED ISSUE #29107: Explicitly specifying UseEphemeralDataProtectionProvider should NOT log a warning
## Summary

The line (in Startup.cs) `services.AddDataProtection().UseEphemeralDataProtectionProvider();` results in a warning message getting logged when the `EphemeralDataProtectionProvider` is instantiated. I believe the provider should NOT log a warning if it was explicitly selected.

It appears that, when the constructor receives a logger, it will always call `UsingEphemeralDataProtectionProvider()`:
https://github.com/dotnet/aspnetcore/blob/69600972f69d669ebecd30d59abd0e1e2ff62ac0/src/DataProtection/DataProtection/src/EphemeralDataProtectionProvider.cs#L60

And `UsingEphemeralDataProtectionProvider()` results in a warning:
https://github.com/dotnet/aspnetcore/blob/69600972f69d669ebecd30d59abd0e1e2ff62ac0/src/DataProtection/DataProtection/src/LoggingExtensions.cs#L328-L331

## Motivation and goals

The intent is to encourage developers to always take warnings seriously. This warning causes logs to contain warnings that developers have no choice but to ignore.

One possible solution is to simply change this warning to an information level message. This should be ok because code that employs the ephemeral data provider as a fall back is already logging an equivalent warning.
https://github.com/dotnet/aspnetcore/blob/69600972f69d669ebecd30d59abd0e1e2ff62ac0/src/DataProtection/DataProtection/src/KeyManagement/XmlKeyManager.cs#L549-L553

A different solution would be to change `UseEphemeralDataProtectionProvider()` extension method to pass in a newly created option to specify that this specific warning is NOT necessary because the provider was explicitly requested.

## In scope

A stateless API backend that uses JWTs to manage authentication and has no need to persist keys between instances of the application (aside from the JWT related key which is obtained from configuration).

## Risks / unknowns

*How might developers misinterpret/misuse this?*
The current implementation, which always logs a warning, can lead developers to search for a way to avoid the ephemeral data protection provider even when it might be a good fit for their solution.

*How might implementing it restrict us from other enhancements in the future? Also list any perf/security/correctness concerns.*
New code that falls back on the ephemeral provider should always log a warning similar to https://github.com/dotnet/aspnetcore/blob/69600972f69d669ebecd30d59abd0e1e2ff62ac0/src/DataProtection/DataProtection/src/KeyManagement/XmlKeyManager.cs#L553 because the new ephemeral provider will no longer log a warning on its own.

### PR DESCRIPTION
**Pull request by ShreyasJejurkar**
Fixes https://github.com/dotnet/aspnetcore/issues/29107

### CODE REVIEW

**Comment by davidfowl** [comment]
This is a bit trickier than the proposed fix. We want to warn if the ephemeral provider is chosen implicitly.

**Comment by davidfowl** [comment]
This is a bit trickier than the proposed fix. We want to warn if the ephemeral provider is chosen implicitly.

**Comment by MCCshreyas** [comment]
yeah @davidfowl. But making it `information` level log by default I don't think it will break any stuff (but might break the decision of making it `warning`). 
On the other side If we wanted to detect if the ephemeral provider was chosen explicitly using `UseEphemeralDataProtectionProvider()` then how could we do that? bool property?

**Comment by davidfowl** [comment]
We can detect if we fell back to it I stress of trying to detect if it was selected explicitly.

Nothing should be logged at all if it was chosen explicitly

**Comment by MCCshreyas** [comment]
> We can detect if we fell back to it I stress of trying to detect if it was selected explicitly.

Sorry, I did not understand this statement!

**Comment by davidfowl** [comment]
> @davidfowl Did you mean "We can detect if we fell back to it instead of trying to detect if it was selected explicitly."?

Yes.

This log should be removed https://github.com/dotnet/aspnetcore/blob/29d0f9c0fbb17211410ef7cc5ba211c35bff29c7/src/DataProtection/DataProtection/src/EphemeralDataProtectionProvider.cs#L60

It's currently in the constructor but shouldn't be here. It'll end up being logged anytime it's used, which is wrong. That said, I don't think there's any easy way to log if we're falling back based on the current logic.

**Comment by MCCshreyas** [comment]
> That said, I don't think there's any easy way to log if we're falling back based on the current logic

Yeah, it's hard to detect! Implicit or explicit! 

Because of which I asked can we have a boolean variable in [IDataProtectionProvider.cs](https://github.com/dotnet/aspnetcore/blob/main/src/DataProtection/Abstractions/src/IDataProtectionProvider.cs) that will represent is given data protection was chosen explicitly (by using the extension method in `startup.cs`) or not! 
That way we can toggle logger severity!

**Comment by davidfowl** [comment]
> Because of which I asked can we have a boolean variable in IDataProtectionProvider.cs that will represent is given implementation of data protection was chosen explicitly (by using the extension method in startup.cs) or not!
That way we can toggle logger severity!

No I don't think we'd pollute a public API or break an interface for logging purposes.

**Comment by MCCshreyas** [comment]
>No I don't think we'd pollute a public API or break an interface for logging purposes
Yeah, make sense! One might be the possible solution of default public property in interface like below. 

```csharp

public interface IDataProtectionProvider
{
   bool IsChoosenExplicitely => false;  //default value, no breaking
   IDataProtector CreateProtector(string purpose);  //existing 
}

```

**Comment by HaoK** [comment]
So if I understand the issue, we just need to detect when UseEphemeralDataProtectionProvider has been called and log when in that situation, can we just inject a marker service in UseEphemeralDataProtectionProvider, and check for that to skip the check?  I guess the ctor could take the service collection and do a lookup for the marker service

**Comment by davidfowl** [comment]
We *can* but I couldn't even find the fallback code. Where is it? I wonder if we can log from elsewhere.

**Comment by HaoK** [comment]
Hrm, I can't seem to find any fallback logic either, @blowdart do you have any idea where the fallback logic to use ephemeral is?  Or is that not a thing?  Do you have to explicitly configure it to get the throwaway provider?

**Comment by blowdart** [comment]
There's definitely fall back, it's the default on Linux. Probably beside the code that detects if it's in an azure web app

**Comment by HaoK** [comment]
Ok, so we were looking at the wrong class for references, the in memory repository logic is here:

https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/DataProtection/DataProtection/src/KeyManagement/XmlKeyManager.cs#L556 and has its own slightly different log message, so looks like there already is two separate logging messages, so just changing this one to Info might be good...

**Comment by HaoK** [comment]
Note there are more details in the original issue (https://github.com/dotnet/aspnetcore/issues/29107), which did point to the XmlRespository line as well (oops)

**Comment by HaoK** [comment]
@blowdart I think this is in a reasonable state now, so we changed the log level for only the explicit one to information. The implicit code paths remain warning.  Good to go from your perspective?

**Comment by blowdart** [comment]
Sure :)

**Review by HaoK — APPROVED** [review]

**Comment by HaoK** [comment]
Thanks @MCCshreyas

**Comment by davidfowl** [comment]
Did we want this fix?

**Comment by HaoK** [comment]
@davidfowl did you have any outstanding concerns?  I looked into the code and it looks like there's two slightly different error messages and code paths so this log message is only called during explicit, while there's another one that is still warning which gets hit in the implicit code path: it uses this log entry which is still warning

https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/DataProtection/DataProtection/src/LoggingExtensions.cs#L391

**Comment by davidfowl** [comment]
Maybe instead of information this one should be debug.

**Pull request merged**
