### PR TITLE
Updated vsconfig

### PR DESCRIPTION
**Pull request by ShreyasJejurkar**
Added NativeDesktop workload as well, as C++ libraries are required to build projects which are under this folder https://github.com/dotnet/aspnetcore/tree/master/src/Servers. 
Without this workload, the projects will be failed to build.

### CODE REVIEW

**Comment by MCCshreyas** [comment]
@captainsafia review?

**Comment by Pilchie** [comment]
Hmm - back in the days when we had individual .sln files, we deliberately only put this in the directories that had C++ projects, because we didn't want to force everyone to have the C++ tools installed.

**Comment by captainsafia** [comment]
Yeah, we've set the goal of making sure that each project requires its own dependencies instead of having all the dependencies installed at the top-level at https://github.com/dotnet/aspnetcore/issues/27633.

With regard to this, I think we can document this requirement in the README for the Servers are as part of #27561 and do some work as part of #27633 to make sure this workload is installed when the user tries to build the Servers project.

@halter73 @jkotalik  Thoughts?

**Comment by halter73** [comment]
Makes sense. I've updated #27561 to list `Servers/Kestrel` and `Servers/(HttpSys|IIS|test/FunctionalTests)` as different projects since Kestrel doesn't need C++ tools to build. I wonder if we should restructure the directory layout.

**Comment by MCCshreyas** [comment]
@captainsafia yeah totally agreed. But the thing is that I did not build server project explicitly, it's the part of build.cmd which is at root level.
So if user did not have this workload installed on their machine then it will fail to build and build.cmd will be terminated in first few minutes, because this are the first projects which gets build! 
And I think showing up VS installer in middle of build.cmd to get this workload installed ( if user has not already) will be a bad experience! 

So from my point of view, either put this workload at top level vsconfig or provide a option for build.cmd to build the server workload just like we have for NodeJS and Java projects that would be a better option and experience!

**Comment by captainsafia** [comment]
> So if the user did not have this workload installed on their machine then it will fail to build and build.cmd will be terminated in the first few minutes because these are the first projects which get build!

@dougbu Thoughts? Seems like a bug in the VS config although not sure why it hasn't been picked up...

**Comment by dougbu** [comment]
I had thought the global.json file listed the workloads / components necessary for .\build.cmd to run. We specifically do _not_ include everything needed for a Visual Studio build because not everyone uses VS. We should fix the tools.vs.components array if it's incomplete.

What is the exact error on your machine @MCCshreyas❔

**Comment by dougbu** [comment]
Side note: The Arcade infrastructure enforces global.json requirements in the `tools` object i.e. when executing `build.*` scripts. Visual Studio is the only thing that pays attention to .vsconfig. And, avoiding requiring native workloads everywhere is part of the reason we've got .vsconfig files spread around the repo.

**Comment by dougbu** [comment]
Because a .vsconfig change won't fix ./build.cmd failures, I suggest we do not take this change. We also have a .vsconfig file that does contain the native workloads and components in src/Servers/IIS alongside the IISIntegration.slnf file

But, we should definitely correct global.json once we hear back from @MCCshreyas.

**Comment by captainsafia** [comment]
@dougbu Makes sense. Thanks for confirming here. I'll close this PR out now.

@MCCshreyas Can you open an issue with the details from https://github.com/dotnet/aspnetcore/pull/27626#issuecomment-726274766? We can figure out what the best course of action is from there.

**Comment by MCCshreyas** [comment]
Just answer the following questions, you guys will understand what I am trying to point out. 
1.  Do server projects build as part of the build.cmd? (**Yes**)
2. If yes, for that to get build, do we require native C++ components? (**Yes**)
3. Do we have included that native c++ components in root vs config? (**No**)

As we do not have C++ native components included, the following files won't be there in the user directory. 

image


And as result, the given following project will get failed. As the file does no exists there. 

image


What my assumption is like, only 10% of people are working on IIS and Kestral native projects, and 90% of people are working on other blazor and Mvc stuff. 
So can we include a switch in build.cmd (like --BuildServerNativeProject) so that if this has passed then only build.cmd will build projects from the Server directory and if not it simply excludes them. 

This way newcomers won't face any issue just like this (https://github.com/dotnet/aspnetcore/issues/27003)

I hope this helps to understand. 

> Note - Please wait for some time to get a reply, as I live in a different time zone.

**Comment by dougbu** [comment]
Definitely something wrong here but it has nothing to do with the .vsconfig file. That's not used when building from the command line. In the #27003 scenario, .\build.cmd should have failed to find a version of Visual Studio containing a suitable desktop `msbuild`. Either the logic finding `msbuild` is incorrect or our global.json is missing something.

**Comment by MCCshreyas** [comment]
@dougbu yes that might be the issue! Just to confirm which msbuild should build.cmd using? The one which comes from VS or then one which is in repository? By default its uses repository one but msbuild won't find c++ packages in there (and it fails) and then I need to set vctargetpath explicitly to VC folder which come from VS installation ( I mean from C drive) then it works!

**Pull request closed without merging**
