### PR TITLE
Shorten package version properties

### PR DESCRIPTION
**Pull request by dougbu**
- `$(...PackageVersion)` -> `$(...Version)`
- inspired by a similar dotnet/efcore change
- aligns names with Arcade SDK, meaning our values apply consistently

Remove unused PublishSymbols.proj and related property
- restore Arcade's control of `$(MicrosoftSymbolUploaderBuildTaskVersion>)`
- would otherwise result in a version downgrade

Update `$(MicrosoftNetCompilersToolsetVersion)` to match Arcade's value
- avoid using an older toolset
- now successfully overriding Arcade value

### CODE REVIEW

**Comment by dougbu** [comment]
FYI this big change is why I temporarily disabled our Maestro++ subscriptions for the master branch. Will enable them again once this is in i.e. after we can avoid massive conflicts.

**Review by wtgodbe — APPROVED** [review]
Looks good assuming there's nothing trickier than what you called out in the description

**Comment by dougbu** [comment]
Quick note on what still spells out "packageversion": The main thing is of course the `$(PackageVersion)` property. I also left properties from the .NET SDK or Arcade alone e.g. `$(BundledNETCoreAppPackageVersion)` and `$(StabilizePackageVersion)`. But the biggest area is our `$(BaselinePackageVersion)` properties.

**Comment by dougbu** [comment]
Help please @JamesNK and @pranavkm. I'm confused by the `error CS8603: Possible null reference return.` about src/SignalR/common/Shared/JsonUtils.cs, specifically the `return defaultValue` line in
``` c#
public static T GetOptionalProperty<T>(JObject json, string property, JTokenType expectedType = JTokenType.None, T defaultValue = default)
{
    var prop = json[property];

    if (prop == null)
    {
        return defaultValue;
    }

    return GetValue<T>(property, expectedType, prop);
}
```

As I read this, `defaultValue` should already be of the `T` type i.e. if `default` is `null` then `T` is `Nullable<Something>` or `Something?`. What am I missing❔

----

VS Code (though not the CI build) also reports the same error later in the file:
``` c#
public static string? ReadAsString(JsonTextReader reader, string propertyName)
{
    reader.Read();

    if (reader.TokenType != JsonToken.String)
    {
        throw new InvalidDataException($"Expected '{propertyName}' to be of type {JTokenType.String}.");
    }

    return reader.Value?.ToString();
}
```
This looks even stranger to me because the return is nullable.

**Comment by dougbu** [comment]
I recall seeing the above error when building this branch locally but it wasn't nearly as consistent. New warnings or errors are likely occurring because we're now using our configured version of Microsoft.CodeAnalysis.CSharp and not Arcade's older choice. But, as I said, I don't "get" that particular `CS8603`.

**Comment by BrennanConroy** [comment]
You can delete the `GetOptionalProperty` function. It isn't used anywhere and is internal.

I wonder if a value type for `T` would cause that?

**Comment by dougbu** [comment]
Thanks @BrennanConroy the pipeline is running much smoother now 😺

**Pull request merged**
