### PR TITLE
Remove nameof for event name

### PR DESCRIPTION
**Pull request by Kahbazi**
Based on https://github.com/aspnet/AspNetCore/pull/6420#discussion_r245768445

### CODE REVIEW

**Comment by rynowak** [comment]
I love it. This is the most Ryan thing ever.

**Comment by Kahbazi** [comment]
I don't think that the changes have anything to do with failed tests.

**Comment by anurse** [comment]
@Kahbazi very likely :). We have some flaky tests I'm afraid :(. I'll take a look.

**Comment by anurse** [comment]
Ah, in this case the macOS build agent just got in to a bad state. Restarted.

**Comment by anurse** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=200798

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2619

**Comment by anurse** [comment]
Helix failure seems unrelated. Merging. Thanks @Kahbazi !

**Pull request merged**
