### PR TITLE
Reduce allocations

### LINKED ISSUE #4229: Don't allocate a closure for IO callbacks in IIS in proc
https://github.com/aspnet/AspNetCore/blob/4d57528704d7ec54570f5960b3b9ddca503d5c89/src/IISIntegration/src/Microsoft.AspNetCore.Server.IIS/Core/IO/AsyncIOOperation.cs#L154

While we're at it we should not capture the ExecutionContext. Lets make the switch to UnsafeQueueUserWorkItem as well.

cc @pakrym @jkotalik

### PR DESCRIPTION
**Pull request by davidfowl**
- Remove per request allocations by implementing IThreadPoolWorkItem on the IISHttpContext.
- Removed per operation allocations by using UnsafeQueueUserWorkItem in AsyncIOOperation.
- This should also reduce overhead by removing non-essential ExecutionContext propagation logic

The per IO operation allocation should be removed completely by this optimization https://github.com/dotnet/coreclr/commit/e7ead79fedc52e17f2cf9befd5c0f5091d70f909#diff-b9b22fdb097c803c0ca6fa45655b24f7

Fixes #4229

### CODE REVIEW

**Comment by jkotalik** [comment]
Change makes sense to me. Can you check what the RPS is before and after this change on plaintext? Would we expect a difference?

**Review by pakrym — APPROVED** [review]

**Comment by davidfowl** [comment]
@sebastienros where is my PR bot? 😄

**Comment by sebastienros** [comment]
Between your keyboard and your chair

**Comment by davidfowl** [comment]
> Between your keyboard and your chair

@sebastienros sigh.............................................

**Comment by davidfowl** [comment]
Turns out the in process benchmark died recently...

**Comment by sebastienros** [comment]
@pakrym IISInProcess doesn't work anymore since Dec 19. Any idea what could have changed? I will investigate on my side too.

**Comment by sebastienros** [comment]
Actually the issue happens with all benchmarks using `--self-contained` ... since Dec 19th, and it seems we took a new runtime around that time. Still investigating, but I can repro locally.

**Comment by sebastienros** [comment]
@pakrym and his windbg magic found the root cause. We are blocked on benchmarking custom builds due to this: https://github.com/dotnet/coreclr/issues/21690

**Review by jkotalik — APPROVED** [review]

**Pull request merged**
