### PR TITLE
Fix comment typos in build props

### PR DESCRIPTION
**Pull request by gitslav**
# Fix comment typos in build props

## Description

Fixes typos in eng/Build.props and eng/Signing.props

### CODE REVIEW

**Comment by gitslav** [comment]
@dotnet-policy-service agree

**Review by mkArtakMSFT — APPROVED** [review]
Thanks for catching these.

**Comment by gitslav** [comment]
@mkArtakMSFT @wtgodbe there was a test failing but it is now quarantined in #56562.

**Comment by mkArtakMSFT** [comment]
@gitslav can you please rebase to main? Thanks!

**Pull request merged**
