### PR TITLE
Remove old artifacts from Home repo

### PR DESCRIPTION
**Pull request by danroth27**
It's time to do some spring cleaning on the Home repo and remove all the old files that are no longer relevant.

@pranavkm @glennc @muratg @Eilon Please review.

### CODE REVIEW

**Comment by pranavkm** [comment]
:shipit:

**Comment by Zazcallabah** [comment]
This commit just broke all our vsts builds.

https://blogs.msdn.microsoft.com/uk_faculty_connection/2015/09/07/continuous-integration-and-testing-using-visual-studio-online/ still references code in this repo. I seem to remember the official guide doing the same, but it seems to be updated now.

What is the currently preferred way of getting a rc1 project to build in vsts ci?

**Comment by danroth27** [comment]
@Zazcallabah You are welcome to sync to a particular commit or tag in the Home repo, but RC1 and RC2 are no longer supported now that 1.0.0 is out and available.

**Comment by Zazcallabah** [comment]
That wouldn't help in this case, would it? Since dnvminstall.ps1 itself does web requests to other files in this repo.

**Comment by danroth27** [comment]
@Zazcallabah Correct, you would have to create a modified version of dnvminstall.ps1. Can you update to RTM?

**Comment by eriksendc** [comment]
Hi @danroth27 

My business, @Zazcallabah , is suffering terribly with this having happened. I totally get that things aren't supported, but tearing down what had been allowing VSTS builds to work without an announcement has really hurt us. For a thousand business-related reasons we're having to stick with RC1 for a few more weeks. 

How do we move forward from here? I was never an expert on the powershell scripts that had previously been a part of this build solution. Can we have some guidance and access to what we'll need to rebuild our own version of this stuff? Since it's gone I don't know where to go looking for it. But isn't there a way to just put a few things back just for another few weeks and then we can plan, calmly and coolly to get our own build script working?

Many thanks in advance for your consideration.

Regards,
Brian Eriksen

**Comment by MaximRouiller** [comment]
If you can, fork https://github.com/aspnet/Home/tree/glennc/rc1 and change the Urls inside to match to your own fork. 

I haven't tested it but it should work. The important part is replacing those `aspnet/home/dev` by the right repository. 

@danroth27 would that work?

**Comment by danroth27** [comment]
OK, to give folks a bit more time to deal with this change I have temporarily added back the dnvm scripts: https://github.com/aspnet/Home/pull/1761

I've also posted an announcement to let folks know that we will remove the dnvm scripts on **Oct 31, 2016**: https://github.com/aspnet/Home/pull/1761.

Please ensure that your infrastructure has been updated by that date to no longer depend on dnvm from the https://github.com/aspnet/Home repo. We strongly recommend updating to the latest supported release to ensure your applications are running on stable and secure bits.

**Comment by danroth27** [comment]
@MaximRouiller Yes, forking and updating the scripts would technically *work*, but you would be better off doing a full update to the latest stable and supported release.

**Comment by eriksendc** [comment]
Hi @danroth27 , First thanks so much for giving us time to regroup. Now that this is out there as a deadline to hit, I'll be sure our team is ready for things to disappear on 31 October. That's really super helpful.

I had reported #1757 a few days ago and got pointed to this issue by @MaximRouiller . I've just retried a build and I'm still having the main issue I reported in #1757. The powershell script we took from a Microsoft post (now torn down) is in #1757 for reference. The issue is that https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1 is not present. Who would be the right person to resurrect https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1?

Thanks,
Brian Eriksen

**Comment by danroth27** [comment]
@eriksendc I just merged the PR so `dnvminstall.ps1` is now (temporarily) back in the Home repo where it was.

**Comment by eriksendc** [comment]
@danroth27 I just tried again and we're back in business! I cannot thank you enough for your consideration and willingness to put stuff back in place for us so that we can march towards a known deadline. We never really wanted to be where we are with still being on RC1. But we're trying to get out the door with our new business. Not that that's your issue! :) If you're interested, though, you're helping us help pets. Check out getyourpet.com.

Thanks again!
Brian Eriksen

**Comment by danroth27** [comment]
> If you're interested, though, you're helping us help pets. Check out getyourpet.com.

@shanselman @jongalloway ASP.NET Core is saving kittens!! :smile:

**Comment by eriksendc** [comment]
Hi @danroth27 ,

As of 6pm EDT last night we're officially saving puppies and kittens at https://getyourpet.com/ and your giving us a reprieve on the ability to continue to build our RC1-based app on Visual Studio Team Services was really important in keeping us on track. Thank you again!

When we last interacted on this you set a [very reasonable] deadline of 31 Oct for pulling down the assets that are supporting RC1 builds. Our plan had been to release on 15 Oct and then spend 15-31 Oct porting to .NET Core 1.0 RTM. We slipped and now we're just getting to the port. We are 100% committed to getting to .NET Core 1.0 RTM immediately. In fact we've already started. But it may take us a week to do the work and a week to test and deploy. Is there any way you would consider changing the date to 15 Nov so, while we're porting, if we need to do an emergency patch to production then we can still do builds through Visual Studio Team Services? 

I understand completely if you need to stick to 31 Oct. If there's some specific thing that this request will hold up, I totally understand. But if you do have flexibility, please consider this 2-week extension.

By the way, many thanks to you and everyone Microsoft for this whole new world we're now coding in. .NET Core is just such an amazing thing. It's just so lightening fast and rock-solid stable!

And thanks @shanselman and @jongalloway  for answering my questions at the community stand up along the way. I haven't been able to watch for the past month or two as I've been working 16-hour days on getting Get Your Pet to market. I'm looking forward to binge watching to catch up, though!

Hope y'all are having a nice Sunday!

Regards,
Brian Eriksen

**Comment by danroth27** [comment]
For puppies and kittens I think we can do that :smile:. I've updated the corresponding announcement issue: https://github.com/aspnet/Announcements/issues/205.

**Comment by eriksendc** [comment]
@danroth27 Thanks again, Dan! And we're already making great progress in migrating to .NET Core 1.0 RTM. I promise to not bother you with any more requests like this.

**Comment by danroth27** [comment]
@eriksendc Are you guys ok for us to remove the dnvm stuff at this point?

**Comment by eriksendc** [comment]
Hi @danroth27 Yes we got onto RTM so we're all set. And we saw quite a performance improvement after we put out the RTM release. Thanks again for giving us the extension on this. 

Regards and Happy Holidays,
Brian Eriksen

**Comment by danroth27** [comment]
> Yes we got onto RTM so we're all set. And we saw quite a performance improvement after we put out the RTM release

Nice! Happy to hear that! :smile:

**Pull request merged**
