### PR TITLE
Disable source index build step

### PR DESCRIPTION
**Pull request by sebastienros**
Current step fails on main builds because of an outdated package version. Tracked by https://github.com/dotnet/aspnetcore/issues/51709

### CODE REVIEW

**Comment by wtgodbe** [comment]
@sebastienros can you provide more info here? dnceng & customers rely on us having this enabled, is there a related issue in arcade?

**Comment by sebastienros** [comment]
Binlog reader package is being updated. Will link to the issue after lunch. All the bills are failing right now.

**Comment by sebastienros** [comment]
Issue:
https://dev.azure.com/dnceng/internal/_build/results?buildId=2302910&view=logs&j=316d5c15-0c50-544e-8051-e6b14a1ab674&t=68de0bee-b0ee-5e79-8d1a-c77a89225a17

image

Resolution in source-indexer: https://github.com/dotnet/source-indexer/pull/120
I believe something else will need to update a version and flow, so right now disabling the step would at least fix the builds.

**Comment by wtgodbe** [comment]
I'm going to try to get a new build of source-indexer instead, I'd prefer that to disabling this step on a Friday

**Comment by wtgodbe** [comment]
Leaving this open in case that hits a wall, though

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/pull/51715

**Comment by wtgodbe** [comment]
https://github.com/dotnet/arcade/pull/14172 failed, so let's take this for now

**Review by wtgodbe — APPROVED** [review]

**Pull request merged**
