### PR TITLE
fix NavLink with query string can't be selected correctly

### LINKED ISSUE #31312: When using a querystring with Blazor apps the the default NavItem is not selected.
### Describe the bug
This happens in a client side application.
When you use a NavItem in your MailLayout like in the default generated application and you call the application with a querystring f.i. https://localhost:123456/?CourseId=123456 then the first NavItem that normally becomes the selected one is displayed as not selected.

### To Reproduce
- Generate a new Blazor Client side application
- Run the application
- In the addressbar of the browser put a querystring behind the url f.i. https://localhost:44381/?CourseId=13333 and press enter
- Notice how the 'Home' menu no longer is selected.

### PR DESCRIPTION
**Pull request by ElderJames**
- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

**PR Title**
Summary of the changes (Less than 80 chars)

Remove query string when handling path matching.

**PR Description**
Detail 1
Detail 2

Addresses #bugnumber (in this specific format)

fixed #31312

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
Thanks for proposing this, @ElderJames! There are still some details that would need to be worked out before we could make a change like this.

 * Back-compatibility. Some developers might be taking a dependency on the link *not* matching if the querystring is present, so we wouldn't want to just break them by applying this new rule by default. Options:
   * We could add a further flag, e.g., `bool IgnoreQueryString`, so the existing behavior is retained by default
   * Or, we could focus more on making `NavLink` more generally customizable. For example we could change its `private bool ShouldMatch` to be `protected virtual bool ShouldMatch`. Then developers who want the kind of change you have here could trivially subclass `<NavLink>` to make (for example) `<NavLinkIgnoreQueryString>` with their custom matching rule.
* E2E tests are needed for new functionality like this.

If you're interested in proceeding with this, could you make a proposal for how to handle the back-compatibility concern? We can then come to an agreement about that. Once that's resolved and an E2E test is added, it's likely we can take this change.

Thanks very much!

**Comment by ElderJames** [comment]
Thank you for your reply @SteveSandersonMS  . 

I think adding a `IgnoreQueryString` flag is better. And this behavior is also quite general.

**Comment by SteveSandersonMS** [comment]
@ElderJames If you're interested in implementing the proposed design, including tests, please let us know. Otherwise the bot will soon close this PR.

**Comment by ElderJames** [comment]
Sorry, I was on vacation the other day. I will continue to finish this feature.

**Comment by captainsafia** [comment]
@ElderJames Thanks for following up.

The build is failing at the moment since a new public API was added that is not tracked in the text files that we include in the repo.

If you're developing in VS, there is a built-in Roslyn analyzer that you can use to automatically update the text files by right clicking on the warning under the defined symbol.

You can also add the type definition at the end of https://github.com/dotnet/aspnetcore/blob/28acd06c02924b2b9ee20748bf7e38847c94f0c4/src/Components/Web/src/PublicAPI.Unshipped.txt.

**Comment by ElderJames** [comment]
Sorry, I don't really understand how to write this test.😂

**Review by captainsafia — COMMENTED** [review]
Left some comments inline.

With regard to how to write tests, you can leverage our end-to-end testing infrastructure. We have a `BasicTestApp` that contains a few components with scenarios used for testing.

For your PR, the component you'll want to use is https://github.com/dotnet/aspnetcore/blob/fdabaf00a6720d852ec3120b7bbe4b14de2f3ccf/src/Components/test/testassets/BasicTestApp/RouterTest/Links.razor.

You'll want to add a new `NavLink` component to that that sets the new parameter.

We exercise that component from Selenium-based tests. For your scenario, the relevant tests are in https://github.com/dotnet/aspnetcore/blob/fdabaf00a6720d852ec3120b7bbe4b14de2f3ccf/src/Components/test/E2ETest/Tests/RoutingTest.cs.

Let me know if you have any other questions!

**Comment by PaulSinnema** [comment]
Don't close this bug. It's an ugly one. Please solve it.

**Pull request closed without merging**
