### PR TITLE
Use the DisplayName and Display attributes to obtain the display name of a property

### PR DESCRIPTION
**Pull request by Eleve2023**
# Set column title by using DisplayAttribute and DisplayNameAttribute

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

{Detail}
This code uses the DisplayName and Display attributes to obtain the display name of a property. It starts by getting the member information from the provided member expression using the Member property of the memberExpression object. Then, it uses the GetCustomAttribute method to get the DisplayName and Display attributes associated with this member. If the DisplayName attribute is present, its value is used as the title. Otherwise, if the Display attribute is present, its Name property is used as the title. If neither of these attributes is present, the name of the member itself is used as the title. Finally, the value of the title is assigned to the Title property.
add a feature (https://github.com/dotnet/aspnetcore/issues/47155)

### CODE REVIEW

**Comment by Eleve2023** [comment]
Hello everyone,

I was looking at the check results for this pull request and noticed that there are 3 failing checks: Build Analysis, aspnetcore-ci  — Build #20230430.7 failed, and aspnetcore-ci (Build Test: Windows Server x64).

Could you provide more information on the cause of these errors and how to resolve them?

Thank you in advance for your help.

**Comment by SteveSandersonMS** [comment]
Thanks for the contribution, @Eleve2023!

We wouldn't want to couple `PropertyColumn` directory to `System.ComponentModel.DataAnnotations`, since DataAnnotations isn't a universal standard, and people may prefer other ways to represent this information. Additionally, we wouldn't perform reflection on every render like this.

However, I *think* you can already achieve what you want by subclassing `PropertyColumn`, and then overriding `OnParametersSet` to add the DataAnnotations-specific logic you want. Does that work for you?

Thanks!

**Comment by Eleve2023** [comment]
Thank you for your response, @SteveSandersonMS. I understand your concern about directly coupling `PropertyColumn` to `System.ComponentModel.DataAnnotations`. However, I would like to point out that reflection only executes once, even if another parameter triggers `OnParametersSet`, since `Title` will not be null. We could remove the `Display` attribute and only keep `DisplayName`, but in my opinion, it would be better to keep it for the ecosystem, as we already use `System.ComponentModel.DataAnnotations` for `ModelState` and form validations. What do you think?

**Comment by SteveSandersonMS** [comment]
If you want to use DataAnnotations, you should subclass `PropertyColumn` to add your DataAnnotations-specific logic. I'm afraid we don't want to couple it directly by default. Hope that's OK.

**Comment by Eleve2023** [comment]
Thank you for your response, @SteveSandersonMS. I understand your concern about directly coupling 'PropertyColumn' to 'System.ComponentModel.DataAnnotations'. To address your concerns, I could remove the 'Display' attribute from 'System.ComponentModel.DataAnnotations' and only keep the 'DisplayName' attribute from 'System.ComponentModel'. This would reduce the dependency on 'DataAnnotations' while still retaining the desired functionality. Additionally, this would still allow for the use of a friendly name if that is better. What do you think?

**Comment by SteveSandersonMS** [comment]
Unless I'm missing something, it looks like it could be done in a subclass as simply as:

```cs
public class MyPropertyColumn<TGridItem, TProp> : PropertyColumn<TGridItem, TProp>
{
    protected override void OnParametersSet()
    {
        if (Title is null && Property.Body is MemberExpression memberExpression)
        {
            // ... your logic here ...
        }

        base.OnParametersSet();
    }
}
```

There don't seem to be any difficulties with knowing when things are initialized, etc. Am I misunderstanding?

**Comment by Diaz15h** [comment]
Hello @SteveSandersonMS, I would like to apologize for any confusion on my part. I now understand that using a subclass for ‘PropertyColumn’ could be a good aid for users who want to customize the column name using data annotations. However, I still think it would be interesting to add this feature directly. In fact, there is already a request for this feature on GitHub: https://github.com/dotnet/aspnetcore/issues/47155.

**Comment by SteveSandersonMS** [comment]
Thanks. It's an option we could reconsider in the future but given how easy it already is to do, and how we are trying not to couple people to specific other technologies, we are not going to do it in the short term. Would it be OK to close this PR?

**Pull request closed without merging**
