### PR TITLE
Accessible navigation

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
Fix for part of https://github.com/dotnet/aspnetcore/issues/32390

### Background

When a server-rendered web page is loaded (e.g., because of following a link to another page on the same site), screen readers observe the "loading completed" event and read out the primary heading (e.g., `h1`). For SPAs, it's not so easy, because screen readers don't know when a navigation has occurred. If the developer doesn't account for this, then by default, SPA navigation isn't announced by the screen reader at all. The user clicks on a navigation link, and nothing audibly happens. See more general details at https://hiddedevries.nl/en/blog/2018-07-19-accessible-page-titles-in-a-single-page-app.

Other technologies including popular routers in Angular, React, and Vue have started providing functionality to help improve this. The most common technique is shown in [this video from Google Chrome Labs](https://www.youtube.com/watch?v=srLRSQg6Jgg): after each navigation completes, the application sets focus to an element at the top of the new content, typically something containing the title for the new page.

Benefits:

 * Programmatically setting focus to a title element (e.g., `h1`) causes the screen reader to announce the new title, just like it would do if you did a regular full-page load on a server-rendered site
 * Moving the focus into the content region (as opposed to leaving it on the nav menu) means the user is now ready to consume its content, e.g., by repeatedly pressing the "down" key which makes a screen reader read the next paragraph. If the focus was left in the nav menu, the user then has to press other keys (maybe many times) to get the focus into the main content so they can start reading it.

### Design

Considerations:

 * Since this is a rather specific UX pattern, we shouldn't assume that everyone wants it to work exactly like this. It's not even the only technique for making accessible SPA navigation.
 * However, this technique probably is the most commonly used one, and it's very simple and causes few drawbacks to people who don't understand the accessibility goals.
 * We need *some* technique baked into the project template, because it's not good enough for navigation - by default - to be unhelpful if you're using a screen reader.

All these things together, I think:

 * We should not bake the technique or any infrastructure for it into core parts of the system like `<Router>`.
 * Instead, it should go into some standalone component that you're free to just not use if you don't like it. You can implement your own alternative if you want some other behavior. Since this is decoupled from most of the system, it's OK for us to make quite specific assumptions about how it should work (because again, if you don't like it, don't use it). As long as it's simple and decoupled, it's not going to cause us any long-term maintenance costs even if one day tech moves on to a better solution and we deprecate this one component.

I did consider doing this purely inside the project template, but I think it's over the complexity boundary of what we'd consider acceptable to put in there. If we're serious that every site needs to account for accessibility, we shouldn't be shy about putting components for this into framework packages.

### Possible drawbacks

If your page components try to set focus to something else programmatically when they first load, it will get overwritten by this. But:

 * Arguably people should *not* set focus to random other things on page load (e.g., text boxes) because although that might be nice to sighted keyboard users, it's disadvantageous to people using screen readers who rely on the reader starting with the title of the new page.
 * If someone knows what they are doing and wants to control this more precisely, they can change the `Selector` to something like `h1:not(.skip-announce)` and then put the class `skip-announce` on certain `h1` elements. However maybe they still shouldn't.

**Update**: Actually that problem doesn't occur. Because the lifecycle callbacks are queued in a breadth-first manner across the component hierarchy, the `OnAfterRenderAsync` in the page component will run after the one in `FocusOnNavigate`, and hence takes precedence. This means that any page-specific behavior will override `FocusOnNavigate`, which is helpful.

### Implementation

All the developer has to do (and is done by default in the template) is add this new `FocusOnNavigate` component to their router:

```razor
<Router AppAssembly="...">
    <Found Context="routeData">
        <RouteView RouteData="@routeData" />
        <FocusOnNavigate RouteData="@routeData" Selector="h1" />
    </Found>
    ...
</Router>
```

No need to change any other pages. Now, after each navigation, if the new page contains a `h1` then we'll focus it and the screen reader will announce the navigation.

If you don't like it, just remove the component. If you only want this to happen on a subset of pages, change the selector to something like `.announce-title` and then put that class on the subset of titles you want to get announced.

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging @merriemcgaw as an FYI.

**Review by javiercn — APPROVED** [review]
Sounds reasonable to me.

**Comment by SteveSandersonMS** [comment]
Posting some info here for future reference.

 * The technique shown here by default (focus the `h1` after navigation) is pretty orthodox and is what's done in (this Vue accessibility guide](https://accessible-app.com/pattern/vue/routing), in [Svelte Navigator](https://github.com/mefechoel/svelte-navigator/issues/1), and in [this set of recommendations](https://medium.com/@robdel12/single-page-apps-routers-are-broken-255daa310cf).
 * However, other opinions are available. This [blog post](https://marcus.io/blog/improved-accessible-routing-vuejs) is more up-to-date and based on more research, and talks about improving the technique further via a more complex system of setting focus to a "skip to content" link and using JavaScript to trigger an independent "Loaded {PAGE_NAME}" announcement. This seems rather difficult to get right, since even [the demo page for this technique](https://ns7t5.csb.app/) behaves quite badly - it doesn't actually read out the updated content title after navigation, and is really hard to get focus to go into the new content.

Because the allegedly improved technique is more complex and doesn't seem to work correctly, I propose at least for preview 6 we keep the conventional solution that we already have in this PR, and ask for feedback from anyone who might be an expert in this area.

**Comment by SteveSandersonMS** [comment]
@bradygaster I hear you have expertise in this area. Do you have any views on the approach used here?

**Comment by bradygaster** [comment]
I think I grok what's happening and, off the cusp, would be agreeable to the plan and think it sounds reasonable. That said, I think it would be interesting if I could see the difference in the two sets of behavior. Is there a way I could see a demo of the options? 

What was said here sums it up well, though:

> Since this is a rather specific UX pattern, we shouldn't assume that everyone wants it to work exactly like this. It's not even the only technique for making accessible SPA navigation.

I concur with this, basically due to it being the convention and given its consistency with the aforementioned options (vue, for instance). 

> Because the allegedly improved technique is more complex and doesn't seem to work correctly, I propose at least for preview 6 we keep the conventional solution that we already have in this PR, and ask for feedback from anyone who might be an expert in this area.

All this said, I think this would be a very interesting customer study to participate in or drive.

**Comment by SteveSandersonMS** [comment]
> Is there a way I could see a demo of the options?

Sure.

 * For an example that uses the same technique as in this PR, check [this demo site](https://github.com/GoogleChromeLabs/a11ycasts/tree/master/examples/managing-focus-spa) (which you'll have to clone and run locally). Alternatively wait until a nightly preview 6 build shows up containing the change from this PR, probably today or tomorrow, then do `dotnet new blazorwasm` or `dotnet new blazorserver`.
 * For an example that uses the more complex technique, see [this demo site](https://ns7t5.csb.app/).

In both cases you'll need to run a screen reader such as the Windows 10 Narrator or NVDA. For evaluating them, it's not purely a comparison of the UX, as we also have to make tradeoffs about how general it is across site types, and how well we think developers will understand it and get good results from it even if they don't have a good grasp of accessibility. We need the code to be simple enough that you pretty much can't get it wrong even if you're new or confused.

One other good point about the `FocusOnNavigate` component added in this PR is that, if you do want the "auto-focus skip-to-content link after navigation" UX, then you can use `FocusOnNavigate` to achieve that. The main thing the developer would have to implement is the skip link itself.

**Pull request merged**
