### PR TITLE
force invariant mode on

### PR DESCRIPTION
**Pull request by lewing**
This will unblock the runtime sync

### CODE REVIEW

**Comment by lewing** [comment]
@pranavkm this is the quick way to unblock the runtime sync

**Review by pranavkm — COMMENTED** [review]
Do we need this in preview8?

**Review by pranavkm — APPROVED** [review]

**Comment by pranavkm** [comment]
Let me update this as part of the merge PR. We'll need to regen the js files

**Comment by lewing** [comment]
If we add the full loading we can improve this but that can happen in a follow up

**Comment by pranavkm** [comment]
I updated the merge PR: https://github.com/dotnet/aspnetcore/pull/23978/commits/66034f95bd49fab7f5c960d2229a92e4116bcc4d. We can close this PR. Thanks @lewing

**Pull request closed without merging**
