### PR TITLE
Unpin Microsoft.Extensions.Configuration.Binder package

### PR DESCRIPTION
**Pull request by dougbu**
- shipping in this release

### CODE REVIEW

**Review by ryanbrandenburg — APPROVED** [review]
Seems fine.

**Review by HaoK — APPROVED** [review]

**Comment by mmitche** [comment]
@dougbu Can you merge to unblock the builds?  The failures are unrelated.

**Comment by dougbu** [comment]
> The failures are unrelated.

@mmitche I agree the failures are unrelated. But, the builds are repeatedly unable to download the JDK or to build our local repo tasks. Something is very wrong at the moment. We're not getting to the point where unpinning this dependency matters.

Besides that, the branch protection rules here prevent merges when the validation checks are failing -- even for admins.

**Comment by dougbu** [comment]
Very strange. `RepoTasks.csproj` is building successfully in #8528 but not here. Rebased on release/2.2.

**Comment by mmitche** [comment]
@dougbu We are putting the Sunday validation at risk here. Do the JDK problems affect the official build?

**Comment by dougbu** [comment]
> We are putting the Sunday validation at risk here.
Understood. There's at least 2 other changes necessary to get the official builds working:
- #8528
- correct the baselines to that official baseline test succeeds: http://aspnetci/viewLog.html?buildId=629133&buildTypeId=Releases_22xMSRC_UniverseCoherence&tab=buildLog&_focus=5292

> Do the JDK problems affect the official build?

No though we do need to be able to get past the validation checks to get this in.

https://github.com/dotnet/core-eng/issues/5488 is also slowing us down.

**Comment by dougbu** [comment]
Done here. Signing still blocked on #8528 and @JunTaoLuo is working that through.

http://aspnetci/viewLog.html?buildId=629133&buildTypeId=Releases_22xMSRC_UniverseCoherence&tab=buildLog&_focus=5292 failures look transient. Will confirm in next internal build&hellip;

**Pull request merged**
