### PR TITLE
Update branding to 3.1.3

### PR DESCRIPTION
**Pull request by wtgodbe**
CC @dotnet/aspnet-build @mmitche

### CODE REVIEW

**Review by mmitche — APPROVED** [review]

**Comment by wtgodbe** [comment]
Template tests are failing:

> [F:\workspace\_work\1\s\src\ProjectTemplates\test\bin\Release\netcoreapp3.1\TestTemplates\AspNet.angularindividual.e4cxpoptre5\AspNet.angularindividual.e4cxpoptre5.csproj]\r\nF:\workspace\_work\1\s\.dotnet\sdk\3.1.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(283,5): error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path 'F:\workspace\_work\1\s\.dotnet\packs\Microsoft.AspNetCore.App.Ref\3.1.2\data\FrameworkList.xml'.

**Comment by wtgodbe** [comment]
The frameworkList.xml file is in the 3.1.2 ref pack, I'm guessing we're not pulling it in though. Which makes sense, because it isn't released yet

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/blob/c3acdcac86dad91c3d3fbc3b93ecc6b7ba494bdc/src/ProjectTemplates/test/Infrastructure/GenerateTestProps.targets#L18 is resolving to `3.1.2`, due to https://github.com/dotnet/aspnetcore/blob/c3acdcac86dad91c3d3fbc3b93ecc6b7ba494bdc/eng/Versions.props#L36. This seems wrong - now the deb/rpm installers will pin their PackageVersions to 3.1.2: https://github.com/dotnet/aspnetcore/blob/c3acdcac86dad91c3d3fbc3b93ecc6b7ba494bdc/src/Installers/Debian/TargetingPack/Debian.TargetingPack.debproj#L41

@dougbu my interpretation here is that we shouldn't be pinning `TargetingPackVersionPrefix` to 3.1.2 - it should just be the repo's version prefix. I'm not quite sure what the template tests should be referencing, though

**Comment by wtgodbe** [comment]
`restore.cmd` on this branch gives me the 3.1.0 `Microsoft.AspNetCore.App.Ref` in my `.dotnet` folder

**Comment by dougbu** [comment]
Suspect we've got an ordering issue here and need to use the previous targeting pack until 3.1.2 is published. Please include comments in dotnet/aspnetcore#19019 to fix this between 3.1.2 shipping and locking down 3.1.3 (so we don't forget).

**Comment by wtgodbe** [comment]
> Suspect we've got an ordering issue here and need to use the previous targeting pack until 3.1.2 is published

I think we'd also need to update to an SDK that includes the 3.1.2 ref pack

**Comment by dougbu** [comment]
> I think we'd also need to update to an SDK that includes the 3.1.2 ref pack

That had better be true of the released 3.1.2 SDK 😈 But, yes, need another comment in #19019  about updating the SDK.

**Comment by wtgodbe** [comment]
@dougbu look good?

**Review by dougbu — APPROVED** [review]
Yes, looks good :shipit:

**Pull request merged**
