### PR TITLE
Update .NET Core 3.0 dependencies

### PR DESCRIPTION
**Pull request by natemcmaster**
* Update Extensions to 3.0.0-preview.18569.14
* Update EFCore to 3.0.0-preview.18569.2
* Update corefx to preview.18566.8
* Update core-setup to preview-27117-01

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
Once builds pass, this looks good.

**Review by Eilon — APPROVED** [review]
What @dougbu said.

**Comment by Eilon** [comment]
😄

**Comment by Eilon** [comment]
@natemcmaster - do we need to ping anyone to help ferry an E2E build through?

**Pull request merged**
