### PR TITLE
Consume ValueTask in DefaultHubLifetimeManager

### PR DESCRIPTION
**Pull request by Kahbazi**
Addresses #29639

### CODE REVIEW

**Comment by BrennanConroy** [comment]
We should probably do something similar in HubConnectionContext.cs
https://github.com/dotnet/aspnetcore/blob/0e195da775478fd49b5c476dc333c99a115ad9ce/src/SignalR/server/Core/src/HubConnectionContext.cs#L180

**Review by BrennanConroy — APPROVED** [review]

**Review by halter73 — APPROVED** [review]

**Comment by halter73** [comment]
I already reran this once. It looks like we're seeing repeated occurrences of https://github.com/dotnet/aspnetcore/issues/25768 on Windows.10.Amd64.Server20H2.Open. See https://dev.azure.com/dnceng/public/_build/results?buildId=968241&view=results for the previous build.

**Comment by BrennanConroy** [comment]
Oh... we fixed that an hour or so ago https://github.com/dotnet/aspnetcore/pull/29701
This rerun should work.

**Comment by BrennanConroy** [comment]
Thanks @Kahbazi

**Pull request merged**
