### PR TITLE
Merging internal commits for release/6.0

### PR DESCRIPTION
**Pull request by vseanreesermsft**

### CODE REVIEW

**Comment by wtgodbe** [comment]
Got some Components-e2e failures, @MackinnonBuck could you take a look?

`Microsoft.AspNetCore.Components.E2ETest.Tests.ComponentRenderingTest.CanHandleClearedChild`

> In value: ReadOnlyCollection<LogEntry> [[2023-04-11T18:43:04Z] [Info] http://127.0.0.1:42599/subdir/_framework/blazor.webassembly.js 0:35640 "Handle blur...", [2023-04-11T18:43:09Z] [Debug] http://127.0.0.1:42599/subdir/_framework/dotnet.6.0.16.abslel8s2o.js 0:131187 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28", [2023-04-11T18:43:09Z] [Severe] http://127.0.0.1:42599/subdir/_framework/dotnet.6.0.16.abslel8s2o.js 0:17630 "/__w/1/s/src/mono/mono/eglib/gpath.c:115 \u003Cdisabled>", [2023-04-11T18:43:09Z] [Severe] http://127.0.0.1:42599/subdir/_framework/dotnet.6.0.16.abslel8s2o.js 0:17630 "/__w/1/s/src/mono/mono/eglib/gpath.c:115 \u003Cdisabled>"]

**Comment by MackinnonBuck** [comment]
Looks like some tests are failing because there are errors in the console.

@pavelsavara Do you know what might be happening here?

```
dotnet.6.0.16.9vxckk6r1z.js:1  /__w/1/s/src/mono/mono/eglib/gpath.c:115 <disabled>
580850 @ dotnet.6.0.16.9vxckk6r1z.js:1
_emscripten_asm_const_int @ dotnet.6.0.16.9vxckk6r1z.js:1
$func111 @ dotnet.wasm:0x94bd
$func2230 @ dotnet.wasm:0x8ebb3
$func3483 @ dotnet.wasm:0xcc2e7
$func3484 @ dotnet.wasm:0xcc318
$func3485 @ dotnet.wasm:0xcc34b
$func3552 @ dotnet.wasm:0xcd83e
$func2078 @ dotnet.wasm:0x862e3
$func2076 @ dotnet.wasm:0x85de1
$func1338 @ dotnet.wasm:0x653d0
$func328 @ dotnet.wasm:0x255f4
$func310 @ dotnet.wasm:0x1eb55
$func361 @ dotnet.wasm:0x27e5b
$func214 @ dotnet.wasm:0x1a03b
$func167 @ dotnet.wasm:0x18991
$func166 @ dotnet.wasm:0xbd73
$func2815 @ dotnet.wasm:0xabef4
$func1619 @ dotnet.wasm:0x6fcb4
$func1623 @ dotnet.wasm:0x70321
$func3217 @ dotnet.wasm:0xc4e86
$mono_background_exec @ dotnet.wasm:0x9433f
Module._mono_background_exec @ dotnet.6.0.16.9vxckk6r1z.js:1
pump_message @ dotnet.6.0.16.9vxckk6r1z.js:1
setTimeout (async)
_schedule_background_exec @ dotnet.6.0.16.9vxckk6r1z.js:1
$func2392 @ dotnet.wasm:0x942f0
$func3216 @ dotnet.wasm:0xc4e16
$func219 @ dotnet.wasm:0x1a529
$func167 @ dotnet.wasm:0xce8f
$func166 @ dotnet.wasm:0xbd73
$func2815 @ dotnet.wasm:0xabef4
$func1619 @ dotnet.wasm:0x6fcb4
$func1623 @ dotnet.wasm:0x70321
$mono_wasm_invoke_method @ dotnet.wasm:0x969f
Module._mono_wasm_invoke_method @ dotnet.6.0.16.9vxckk6r1z.js:1
_call_method_with_converted_args @ dotnet.6.0.16.9vxckk6r1z.js:1
call_method @ dotnet.6.0.16.9vxckk6r1z.js:1
(anonymous) @ dotnet.6.0.16.9vxckk6r1z.js:1
call_assembly_entry_point @ dotnet.6.0.16.9vxckk6r1z.js:1
callEntryPoint @ MonoPlatform.ts:61
At @ Boot.WebAssembly.ts:135
await in At (async)
(anonymous) @ Boot.WebAssembly.ts:218
(anonymous) @ blazor.webassembly.js:1
```

**Comment by pavelsavara** [comment]
I don't know yet. 

@kg @radekdoulik any thoughts ?

**Comment by pavelsavara** [comment]
`/mono/mono/eglib/gpath.c:115` is `g_path_get_dirname` with `NULL` filename

**Comment by lewing** [comment]
@elinor-fung I think this is the dllimport change breaking blazor

**Comment by elinor-fung** [comment]
Looks like 6.0 didn't have the null check: https://github.com/dotnet/runtime/pull/60445

Just to double check - this is a log message, not a 'crashing the world', right?

**Comment by wtgodbe** [comment]
Test failure fixed by https://github.com/dotnet/runtime/pull/84740

**Comment by lewing** [comment]
> Looks like 6.0 didn't have the null check: [dotnet/runtime#60445](https://github.com/dotnet/runtime/pull/60445)
> 
> Just to double check - this is a log message, not a 'crashing the world', right?

no this is crashinng the world when that path gets hit

**Pull request merged**
