### PR TITLE
skip Libuv.FunctionalTests RemoteIPv6Address on Helix

### PR DESCRIPTION
**Pull request by analogrelay**
related #8109

### CODE REVIEW

**Review by Eilon — APPROVED** [review]

**Review by HaoK — APPROVED** [review]
Hopefully this is the main offender, I have a vague recollection of seeing similar tests in here fail before, but I might have skipped them already, cross our fingers I guess

**Comment by anurse** [comment]
If another one shows up, I'll disable the entire project :).

**Comment by anurse** [comment]
I messed something up. I thought it was building on my machine but I was wrong :).

**Comment by anurse** [comment]
Figured it out, the file is also used in Sockets tests. I'm adding some `#ifdef` fun.

**Review by HaoK — APPROVED** [review]
Yeah these tests are all shared, so slightly more annoying to disable

**Comment by HaoK** [comment]
Generally I've only seen the libuv bind/functional tests fail (and usually only on non windows, so the flakiness is limited somewhat)

**Pull request merged**
