### PR TITLE
Add additional ProblemDetails default types and titles

### PR DESCRIPTION
**Pull request by ghost**
- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Description

This PR adds additional problem details titles and types for HTTP statuses 407, 410, 411, 413, 414, 416, 417, 421, 501, and 505.

### CODE REVIEW

**Comment by joegoldman2** [comment]
Failure in CI seems unrelated. This PR is ready to be reviewed.

**Comment by adityamandaleeka** [comment]
Thanks @joegoldman2. This seems fine to me... @martincostello @captainsafia, do we have any policy for which statuses we include here?

**Comment by martincostello** [comment]
Not that I'm aware of - I guess as long as it's an official code in the RFC it should be fine?

**Comment by captainsafia** [comment]
Yep, the Problem Details spec is very permissive about what status codes can be referenced in the payload ([ref](https://datatracker.ietf.org/doc/html/rfc7807#section-3.1)). The only thing it cautions about is that you make sure the status code in the Problem Details payload matches what is actually returned in the HTTP response (accounting for any proxies and whatnot).

With that in mind, we might want to consider if we want to go ahead and support all the status codes or just the finite set added here. @joegoldman2 Was there a particular reason you chose this subset to add?

**Comment by joegoldman2** [comment]
> @joegoldman2 Was there a particular reason you chose this subset to add?

I needed to use a few (not all I added to this PR) and realized that the default values were missing. I decided to add all the missing standard (from the RFC) statuses.

**Review by captainsafia — APPROVED** [review]
LGTM! I double checked and this does cover all the status codes currently under Client Error and Server Error in the RFC.

**Pull request merged**
