### PR TITLE
Refresh BuildFromSource docs

### PR DESCRIPTION
**Pull request by captainsafia**
- Clean up build from source docs
- Add engine information to package.json files

### CODE REVIEW

**Comment by davidfowl** [comment]
We also need a true .vsconfig file that works. InstallVS.ps1 is jank

**Review by Pilchie — COMMENTED** [review]
Looks good except for a few nits.

**Review by Tratcher — COMMENTED** [review]
Overall this is a cleaner approach. It needs a little more detail on the "things I need to install" section.

**Review by dougbu — COMMENTED** [review]
I have a nagging feeling we've lost useful text while things moved around. Is that valid❔

**Pull request closed without merging**
