### PR TITLE
Change efcore identity design

### PR DESCRIPTION
**Pull request by yihango**
Summary of the changes (Less than 80 chars)
 - The identity database context provider and identity database configuration are added to make the Store less dependent on a certain type of DbContext for decoupling purposes.

Addresses #bugnumber (in this specific format)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=27602) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=27602) before we can accept your contribution.<br/><br/>:x: staneee [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=27602)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=27602) it.</sub>

**Comment by blowdart** [comment]
I'm sorry but a PR of this size, with no issue, or discussion around the issue, which changes how EF works, can't be accepted.

This needs a much wider discussion, given its breaking nature.

**Comment by staneee** [comment]
> I'm sorry but a PR of this size, with no issue, or discussion around the issue, which changes how EF works, can't be accepted.
> 
> This needs a much wider discussion, given its breaking nature.

My problems:
When I want to override the Identity EFcore implementation, forcing the injection of a certain type of database context prevents me from being more flexible with it.So I use a database context provider to get the database context instance, and when I want to override it, I just change the database context provider.

**Comment by blowdart** [comment]
You should start your problem as an issue for consideration, this is just too big and too breaking to start as a PR.

Closing it I'm afraid.

**Pull request closed without merging**
