### PR TITLE
Disable app init test in 2.2

### PR DESCRIPTION
**Pull request by jkotalik**
Disables https://github.com/aspnet/AspNetCore-Internal/issues/2602/https://github.com/aspnet/AspNetCore-Internal/issues/2631 and does a bunch of cleanup stuff for being able to build ANCM in VS.

This test is only failing on a specific agent ( I think it's an agent issue). I see it pass locally.

@aspnet/build if given permission, I can rdp onto http://aspnetci/agentDetails.html?name=aspnetci-a-102&agentTypeId=55 if you'd like me to figure out what is wrong on the agent.

### CODE REVIEW

**Comment by jkotalik** [comment]
@anurse / @aspnet/build this is also a change to 2.2 but is a test only.

**Comment by anurse** [comment]
> this is also a change to 2.2 but is a test only.

Requires shiproom notification but not approval. Once the build is green obviously ;).

**Comment by anurse** [comment]
@jkotalik when this is ready to merge, send email to `netcoreship` with a brief summary (couple of sentences) of the change and indicate it is test-only. An admin (myself or whoever else is available) can merge.

**Comment by BrennanConroy** [comment]
>This test is only failing on a specific agent ( I think it's an agent issue). I see it pass locally.

Shouldn't we fix the agent instead of entirely disabling the test?

**Comment by jkotalik** [comment]
I can't access the machine to diagnose why it is failing (@aspnet/build ?). Before, this test was skipped on all runs prior because a module wasn't installed: http://aspnetci/viewType.html?buildTypeId=Releases_22xPublic_Win2012&tab=buildTypeHistoryList. aspnetci-a-108 didn't have the right dependencies, but aspnetci-a-102 does. I ran this test locally on win10 and it passed, so either it's an issue on Win8 or it's an issue with the agent itself.

**Comment by jkotalik** [comment]
Closing, will reopen in a different PR.

**Pull request closed without merging**
