### PR TITLE
Quarantine CannotAddMultipleRootComponentsToTheSameElementAtTheSameTime

### PR DESCRIPTION
**Pull request by captainsafia**
See https://github.com/dotnet/aspnetcore/issues/34743 for more info.

### CODE REVIEW

**Review by TanayParikh — APPROVED** [review]

**Comment by wtgodbe** [comment]
You beat me to it! 😆

**Comment by davidfowl** [comment]
Did this get un quarantined?

**Comment by SteveSandersonMS** [comment]
Yes, I was able to repro locally the same specific error we saw on CI and fixed it here: https://github.com/dotnet/aspnetcore/pull/34803/files#diff-1963cbaf34ddc48b12c0dff8dcbbddb8978fbcb732d1d173df375eacedc40c11R231

Has there been another failure since then?

**Comment by davidfowl** [comment]
Yes on my PR it failed

**Pull request merged**
