### PR TITLE
[release/6.0-preview2] React to Microsoft.Extensions.Internal.Transport package name change

### PR DESCRIPTION
**Pull request by mmitche**
Package name changed to Microsoft.AspNetCore.Internal.Transport

### CODE REVIEW

**Comment by mmitche** [comment]
@dougbu @Anipik can you take a look at the failures? Looks like a breaking change.

**Comment by dougbu** [comment]
@mmitche not exactly a breaking change. Microsoft.Extensions.DependencyModel is no longer in the transport package. That's fine but a couple of projects used that namespace without depending on the package. Turns out the `using`s were useless.

Long story short, cherry-pick the rest of #30405 in here or wait for me to merge that and use the squashed commit instead of what you've got here.

**Comment by dougbu** [comment]
@mmitche 550bd15b011451963887af880928baab18b8d5a9 was the squashed commit in 'main' for #30405. I overwrote your fork w/ a cherry-pick of that.

**Review by dougbu — APPROVED** [review]
Of course I approve this 😀

**Review by Anipik — APPROVED** [review]

**Comment by dougbu** [comment]
Thanks for alerting us this was needed for 6.0 @mmitche❕

**Pull request merged**
