### PR TITLE
Added the submodules initialization step

### PR DESCRIPTION
**Pull request by mkArtakMSFT**

### CODE REVIEW

**Review by sebastienros — APPROVED** [review]

**Review by JunTaoLuo — APPROVED** [review]

**Comment by mkArtakMSFT** [comment]
@aspnet/brt this has failed with some unrelated error, as my change is to a MD file only.

**Comment by ryanbrandenburg** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=142524&view=results

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

I've triaged the above build.

**Comment by ryanbrandenburg** [comment]
@mkArtakMSFT when this kind of thing happens speak the above incantation and RaaS will arrive to triage. After it's been triaged you can retry the build.

**Pull request merged**
