### PR TITLE
update triageprocess.md for .NET 8

### PR DESCRIPTION
**Pull request by danmoseley**
@mkArtakMSFT

### CODE REVIEW

**Comment by danmoseley** [comment]
Hm, should `*.md` or `docs/*.md` or `docs/` be excluded to not trigger regular pipelines? something like this:

https://github.com/dotnet/runtime/blob/dd6696a29c77c3256d35ef25970fba7c09440aca/eng/pipelines/runtime.yml#L15

**Review by mkArtakMSFT — APPROVED** [review]
Thanks @danmoseley !

**Comment by mkArtakMSFT** [comment]
> Hm, should `*.md` or `docs/*.md` or `docs/` be excluded to not trigger regular pipelines? something like this:
> 
> https://github.com/dotnet/runtime/blob/dd6696a29c77c3256d35ef25970fba7c09440aca/eng/pipelines/runtime.yml#L15

Good idea. I think we should do that too.

**Comment by captainsafia** [comment]
> Good idea. I think we should do that too.

Agree. We have a skip-ci label that you can put on the PR title to avoid updates but it's very easy to forget to do.

@dougbu Do you have any reservations about this? If not, is the code below the right place to make the change?

https://github.com/dotnet/aspnetcore/blob/89ed4d898e84be89545b5647e98117a9f71d5093/.azure/pipelines/ci.yml#L6-L12

**Comment by danmoseley** [comment]
I mentioned the 3 options above because I don't know whether there's non markdown stuff in docs that participates in build, or markdown stuff outside of docs that participates in build. The ideal would be both `docs/` and `**md`.

You might consider whether there are other extensions too eg txt possibly.

**Comment by dougbu** [comment]
> Hm, should `*.md` or `docs/*.md` or `docs/` be excluded to not trigger regular pipelines?

We tried this in the past but decided not to make skipping aspnetcore-ci optional in our branch protection rules. We have never run like dotnet/runtime, where they seem to have very lenient branch protection rules.

Don't remember the PR but suspect we tried the `*.md` thing; very few (if any) MarkDown files have any impact on our packages or blobs. In any case, that PR was reverted because PRs required admin overrides -- the opposite of what we were going for.

@wtgodbe do you remember other details❔

**Comment by dougbu** [comment]
I clicked `rerun failed jobs` in AzDO. The failed job is pretty fast.

**Comment by wtgodbe** [comment]
> Don't remember the PR but suspect we tried the *.md thing; very few (if any) MarkDown files have any impact on our packages or blobs. In any case, that PR was reverted because PRs required admin overrides -- the opposite of what we were going for.

Yeah, we tried at least `*.md` files, but backed it out because aspnetcore-ci is a required check, so nobody but admins could click merge on those PRs.

**Comment by dougbu** [comment]
> You might consider whether there are other extensions too eg txt possibly.

I'd resist this (even if we decided to drop all required checks in the branch protection rules) because `*.txt` files end up in shipping packages e.g. THIRD-PARTY-NOTICES.txt and eng/PlatformManifest.txt. Those files make things complicated. `docs/` or `*.md` would be fine (though there's no `*.txt` files in docs/).

**Comment by danmoseley** [comment]
@Dotnet/dnceng @viktorhofer do any of you know a way that we could avoid triggering validation for certain file types in a branch that is protected as described above?

**Comment by missymessa** [comment]
> > @dotnet/dnceng @ViktorHofer do any of you know a way that we could avoid triggering validation for *.md without making it necessary for an admin to merge because it's therefore skipped a required check? that seems like a conundrum.
> 
> I don't think github supports that workflow :/

I don't think so either. I think we looked into doing that for dotnet/arcade because of all the docs we have in that repo and it wasn't going to work.

**Pull request merged**
