### PR TITLE
React to dotnet/runtime#47684, a new transport package

### PR DESCRIPTION
**Pull request by dougbu**
- handle Microsoft.Extensions.Internal.Transport -> 'Microsoft.AspNetCore.Internal.Transport name change
- remove `$(...V0Version)` / `%(RTMVersion)` workarounds
- remove mention of System.Security.AccessControl package; only need transitive references to that
- confirm content of Microsoft.AspNetCore.Internal.Transport package
    - missing Microsoft.Extensions.DependencyModel assembly

### CODE REVIEW

**Comment by dougbu** [comment]
/fyi @BrennanConroy (you asked about this yesterday)

**Comment by dougbu** [comment]
@ericstj @Anipik @Pilchie 
> missing Microsoft.Extensions.DependencyModel assembly

Should we add that assembly to Microsoft.AspNetCore.Internal.Transport❔ I'm not positive it matters and would appreciate your thoughts.

We depend on Microsoft.Extensions.DependencyModel in our [Microsoft.AspNetCore.Mvc.Testing](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Testing) and [https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation) packages though not in Microsoft.AspNetCore.App.Ref or &hellip;Runtime. The dependency version would change if we ever serviced Microsoft.Extensions.DependencyModel in 5.0.x or (eventually) 6.0.x. But, in 5.0.x, we'd build against the RTM ref/ assembly and that won't happen in 6.0.x.

**Comment by ericstj** [comment]
> missing Microsoft.Extensions.DependencyModel assembly

This was probably included before by happenstance since it matched the Micrsoft.Extensions prefix.  As you mentioned it's not part of the framework, so it probably shouldn't be consumed as a transport package.  It can be consumed as a normal package.

**Review by Anipik — APPROVED** [review]

**Comment by Anipik** [comment]
Microsoft.AspnetCore.Internal.Transport not having Micorosft.Extensions.DependencyModel in the package will imply that we can increment the assembly version in 6.0 servicing. (if we serviced the dependencyModel)

**Review by wtgodbe — APPROVED** [review]

**Comment by dougbu** [comment]
@wtgodbe could you please double-check this PR❔ It's different from what you approved, particularly in src/Framework/App.Ref/src/Microsoft.AspNetCore.App.Ref.csproj

**Review by wtgodbe — APPROVED** [review]
Makes sense

**Pull request merged**
