### PR TITLE
Allow runtime compilation to be configured via the hosting startup.

### PR DESCRIPTION
**Pull request by pranavkm**
## Description

As part of refactoring how Razor Pages are loaded, the ability to use runtime compilation via the hosting startup / env variable was broken. We had this feature enabled via a project template option. Because we removed the option in 6.0 in favor of hot reload, we lost coverage for it and had no end-to-end tests. This change restores support for this feature and adds better test coverage.

Fixes https://github.com/dotnet/aspnetcore/issues/38465

## Customer Impact

Users are unable to use the hosting startup from the runtime compilation package. 

## Regression?

- [x] Yes
- [ ] No

[If yes, specify the version the behavior has regressed from] 5.0

## Risk

- [ ] High
- [ ] Medium
- [x] Low

The changes are limited to when the runtime compilation is referenced and enabled via the hosting startup feature. 

## Verification

- [x] Manual (required)
- [x] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

### CODE REVIEW

**Comment by pranavkm** [comment]
Porting https://github.com/dotnet/aspnetcore/pull/39381 to release/6.0

**Review by TanayParikh — APPROVED** [review]
Approving Backport

**Comment by pranavkm** [comment]
@dotnet/aspnet-build could we get this merged?

**Comment by dougbu** [comment]
@pranavkm this is approved for 6.0.3 and branches aren't open for that version yet.

**Pull request merged**
