### PR TITLE
Safe utf8 string conversion

### PR DESCRIPTION
**Pull request by benaadams**
Saw this, thought @blowdart might like it

### CODE REVIEW

**Comment by GrabYourPitchforks** [comment]
Separately: We should also consider whether we want to block ill-formed UTF-8 from coming into the system at all. The default behavior of `Encoding.UTF8` is that it replaces invalid sequences with `\uFFFD`. (And this behavior is changing ever so slightly in .NET Core 3.0, so 2.x and 3.0 will potentially produce different numbers of `\uFFFD` chars given invalid input.)

**Comment by benaadams** [comment]
Could use a throwing fallback?

**Comment by GrabYourPitchforks** [comment]
I don't know if it would be appropriate to use a throwing fallback here as part of this PR. The web server framework probably isn't expecting these particular calls to throw right now. It's just something I wanted to throw out for future consideration.

**Comment by blowdart** [comment]
Someone has hacked @benaadams's github account. We need to rollback everything from at least the last week.

**Review by JamesNK — APPROVED** [review]

**Comment by davidfowl** [comment]
LGTM. This is hold over from .Net fx support

**Review by davidfowl — APPROVED** [review]

**Pull request merged**
