### PR TITLE
Quarantine identity test

### PR DESCRIPTION
**Pull request by HaoK**
Make spec tests no pack

### CODE REVIEW

**Comment by Pilchie** [comment]
:eyes:

**Review by JunTaoLuo — APPROVED** [review]
Changes look good, but curious why are we no shipping the spec tests?

**Comment by HaoK** [comment]
We can't quarantine them if we ship them, so since they aren't widely used, not shipping them anymore seems like an acceptable tradeoff, they aren't changing much so the 3.0 versions should be good enough going forward

**Pull request merged**
