### PR TITLE
Change gRPC template logging level to info in development

### PR DESCRIPTION
**Pull request by JamesNK**
Addresses #9408

### CODE REVIEW

**Review by davidfowl — APPROVED** [review]

**Comment by JamesNK** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=161479

**Review by shirhatti — APPROVED** [review]

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2300
https://github.com/aspnet/AspNetCore-Internal/issues/2267

**Comment by JamesNK** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=161548

**Review by ryanbrandenburg — APPROVED** [review]

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2332

**Comment by davidfowl** [comment]
This hasn’t passed yet!?

**Review by JunTaoLuo — APPROVED** [review]

**Comment by JamesNK** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=161600

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2332

**Comment by davidfowl** [comment]
@JamesNK just re-run the thing...

**Pull request merged**
