### PR TITLE
Blazor WebAssembly move to netstandard2.1

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
This moves the Blazor WebAssembly project template, and packages specific to it, to `netstandard2.1`. This is the TFM we expect to ship with for the Blazor WebAssembly release. Doing this unlocks a whole bunch of more modern .NET Core functionality.

This is possible now because Mono WebAssembly has had many recent updates to support ns2.1 features, plus @lewing helped us discover what changes to the linker config are needed to make that work.

There is a deliberate extra functional change in this PR, which is needed to make the linker still work:

 * Previously we used to link (i.e., strip code from) only the Mono BCL assemblies, i.e., those bundled in the special `Microsoft.AspNetCore.Blazor.Mono` package
 * After this change, we now link any assembly whose name starts with `System.`, regardless of where it comes from

The reason for this change is:

1. For `System.*` packages that *aren't* in the Mono BCL, we want the linker now to use its own logic to decide whether to resolve against Mono's facades or `.dll` files from NuGet. We weren't doing that before, and it wasn't compatible with ns2.1 because Mono's assembly layout is different from CoreFx's, and we were picking the wrong implementations of `System.*` assemblies that can come from NuGet packages.
2. A side-benefit of the new arrangement is that we have an easy way to specify whether or not assemblies are linkable based on filename or other metadata. ~~I've chosen to include `Microsoft.Extensions.*` simply because they are quite large, and linking them seems to work perfectly well with no obvious drawbacks. This takes 100kb or so off the final app size.~~ Update: I've reverted that bit, so it no longer links `Microsoft.Extensions.*`, as it was breaking things as per E2E tests. We would need to provide a more detailed treatment for this in linker config.

### Merging this

Let's discuss whether we intend to include this in the preview3 branch or whether to merge this later.

### CODE REVIEW

**Review by javiercn — APPROVED** [review]
This is a great set of changes.

I'm marginally worried that the move to ns2.1 could potentially break existing libraries referencing the ns2.0 version of some of these things (i'm speculating here).

Otherwise it looks great!

**Comment by javiercn** [comment]
WRT merging I think it's too late for preview3, but ask @Pilchie

I'm in favor of this change as it mostly affects client-side Blazor. (The TFM update for nuget packages being the only thing going into 3.1)

Should we also update Microsoft.JSInterop?

**Comment by SteveSandersonMS** [comment]
Yeah, I’m going to revert the target change in the libraries and make this a change only to the wasm template and build system. 

Dropping ns2.0 support for the core libs is not something I think we’d be ok with for 3.1.

**Comment by SteveSandersonMS** [comment]
@Pilchie @danroth27 OK we have to make a call on whether moving `Microsoft.AspNetCore.Components` (etc) to `netstandard2.1` is something we'd consider doing for the 3.1 release. Either doing it or not doing it is possible. It could be merged within hours either way.

Are we in general changing TFMs to `netstandard2.1` for the 3.1 release?

**Comment by Pilchie** [comment]
I would rather not unless there is a good reason to do so in the 3.1 timeframe.  We don't have very much preview coverage remaining for 3.1, and it seems like a lot of risk without a clear upside.

**Comment by SteveSandersonMS** [comment]
@Pilchie OK. What's your opinion about whether to merge this PR for 3.1 as-is? That means it would only affect the Blazor WebAssembly template and packages. That would be helpful to keep things moving on that side, without risking any change in the shared framework packages for 3.1.

**Comment by Pilchie** [comment]
We'd still need to get QB approval from tactics if we want this in the 3.1 release.

**Comment by wtgodbe** [comment]
What's the latest on this? Has it been QB approved for 3.1 GA?

**Comment by SteveSandersonMS** [comment]
No, I'll rebase it on the new blazor-wasm branch once that's available and merge it there.

**Comment by mkArtakMSFT** [comment]
The `blazor-wasm` branch is now available.

**Comment by rabbitism** [comment]
Hello experts, 

  What would be the best way of moving existing projects targeting 2.0 to 2.1?

Thanks!

**Comment by danroth27** [comment]
@rabbitism 3.1 Preview 3 should now be available.

**Pull request merged**
