### PR TITLE
Update Microsoft.Web.Xdt version

### PR DESCRIPTION
**Pull request by NikolaMilosavljevic**
# Update Microsoft.Web.Xdt version

## Description

Updates version of Microsoft.Web.Xdt package and add source-build dependency in Version.Details.xml.

Fixes https://github.com/dotnet/source-build/issues/2969

### CODE REVIEW

**Review by dougbu — APPROVED** [review]

**Review by MichaelSimons — APPROVED** [review]

**Comment by dougbu** [comment]
@NikolaMilosavljevic I enabled auto-merge because I doubt you have rights to merge into release/7.0

**Comment by NikolaMilosavljevic** [comment]
@dougbu one test is failing - do you if this is a known issue? Helix log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-pull-43521-merge-2943ef4d444443beb1/Interop.FunctionalTests--net7.0/1/console.eb323cc8.log?helixlogtype=result

```
2022-08-25T00:23:19.9102105Z [xUnit.net 00:00:29.04]       Assert.Throws() Failure
2022-08-25T00:23:19.9117637Z [xUnit.net 00:00:29.03]     Interop.FunctionalTests.Http3.Http3TlsTests.OnAuthenticate_Available_Throws(protocols: Http1AndHttp2AndHttp3) [FAIL]
2022-08-25T00:23:19.9138337Z [xUnit.net 00:00:29.04]       Expected: typeof(System.NotSupportedException)
2022-08-25T00:23:19.9185721Z [xUnit.net 00:00:29.04]       Actual:   typeof(System.IO.IOException): Failed to bind to address https://0.0.0.0:48668: address already in use.
2022-08-25T00:23:19.9217384Z [xUnit.net 00:00:29.05]       ---- System.IO.IOException : Failed to bind to address https://0.0.0.0:48668: address already in use.
2022-08-25T00:23:19.9686149Z [xUnit.net 00:00:29.05]       -------- Microsoft.AspNetCore.Connections.AddressInUseException : Address already in use
2022-08-25T00:23:19.9686431Z [xUnit.net 00:00:29.05]       ------------ System.Net.Sockets.SocketException : Address already in use
```

**Comment by wtgodbe** [comment]
Probably test flakiness - CC @halter73 who's on build ops

**Comment by dougbu** [comment]
This is a test problem @JamesNK's fixes in RC1 might not have fixed. In fact it's worse these days.

Could backport a7fa9695a77 from 'main' to cover all `Http3TlsTests`.

**Comment by dougbu** [comment]
Oh, that's not quite right. #43534 will include the fixes @JamesNK did in RC1. Not sure what's holding that PR up&hellip;

**Comment by dougbu** [comment]
☹️ Helix tests failing there too ☹️ (not just expected Code Check errors)

**Comment by halter73** [comment]
> Probably test flakiness - CC @halter73 who's on build ops

I'm OOF. My bad for not checking beforehand. @captainsafia has graciously swapped with me.

**Comment by dougbu** [comment]
@captainsafia we should probably just `Skip="borked"` that particular test. I see some evidence it fails even in main, where we retry all `Http3TlsTests` tests.

**Comment by dougbu** [comment]
This is our worst offender among all tests these days (across most branches)
image

**Comment by NikolaMilosavljevic** [comment]
> @captainsafia we should probably just `Skip="borked"` that particular test. I see some evidence it fails even in main, where we retry all `Http3TlsTests` tests.

Should we wait on merging this PR, until the test is fixed or skipping enabled? My changes are unrelated, and can be merged, I believe.

**Comment by NikolaMilosavljevic** [comment]
@dougbu is the fix for the test in release/7.0 branch? I could close and reopen this PR to pick up the fix.

Alternatively, this PR could be merged now, as the known failure is not introduced by my changes.

**Comment by captainsafia** [comment]
@NikolaMilosavljevic I think we can save the extra build here and merge this PR as is considering the failure is unrelated.

@dougbu If that's fine with you, I'll use my temporary admin privileges to merge.

**Comment by dougbu** [comment]
Had to disable auto-merge first 😁

**Pull request merged**
