### PR TITLE
Add support custom client hub method name

### PR DESCRIPTION
**Pull request by vahpetr**
Good day!

Added support for custom names for hub interface methods.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=23614) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=23614) before we can accept your contribution.<br/><br/>:x: vahpetr [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=23614)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=23614) it.</sub>

**Review by halter73 — APPROVED** [review]
Seems obvious we should do this in hindsight. Looks to me like a nice simple improvement with a good test. Does this look good to you @BrennanConroy?

**Comment by vahpetr** [comment]
@BrennanConroy look please

**Comment by BrennanConroy** [comment]
> Looks to me like a nice simple improvement with a good test.

Agreed, however I am a bit hesitant because the `HubMethodNameAttribute` is meant for the Hub methods and this is applying it to client methods instead.

**Comment by halter73** [comment]
I see where you're coming from, but I consider client methods "hub methods" as well especially if we ever do #15198.

I cannot think of a better name than HubMethodNameAttribute for a client-side attribute. We just need to move HubMethodNameAttribute to the SignalR.Common project with a type forward when we implement #15198 so it can be used on both server and client.

Thoughts @davidfowl?

**Comment by davidfowl** [comment]
I think it's fine to reuse the attribute but it needs to be in a shared place between server and client. This does feel a bit premature since we don't have client side hubs yet though.

**Comment by vahpetr** [comment]
Do I need to fix something? It seems that you are raising issues of a higher order. I think this change can be accepted without global changes.

**Comment by halter73** [comment]
I don't see this as premature. Hub interface methods are already a thing, so why not support the HubMethodNameAttribute on them now? I already called out the need to eventually move this to SignalR.Common and type forward, but AFAIK that can be done later when we implement client side hubs. It's already in the common Microsoft.AspNetCore.SignalR namespace, so I don't think it would be breaking.

@davidfowl Do you still think it's too premature to merge this PR? I still think we should take this.

**Comment by davidfowl** [comment]
It’s fine. I don’t have any pushback besides moving the attribute type somewhere neutral

**Comment by halter73** [comment]
Thanks @vahpetr!

@davidfowl You're fine with moving the attribute to somewhere neutral when we implement #15198, right?

**Comment by davidfowl** [comment]
If the namespace is right yep

**Pull request merged**
