### PR TITLE
!!! Correct condition controlling `public` API analysis !!!

### PR DESCRIPTION
**Pull request by dougbu**
-  #26785 demonstrated analyzers were inoperable

### CODE REVIEW

**Comment by dougbu** [comment]
@Pilchie is this too late for tell mode❔

**Comment by Pilchie** [comment]
I think we can still get it, but obviously the errors will need to be fixed. Do we know if this is new API surface since the previous change?

**Comment by dougbu** [comment]
I'm working on the errors. Appears changes are primarily due to nullable additions since #25662. I'm not sure that's the whole story however.

**Review by wtgodbe — APPROVED** [review]

**Comment by dougbu** [comment]
@Pilchie should I fix #26784 here or separately❔

**Comment by Pilchie** [comment]
Whichever is comfortable is fine with me.

**Pull request merged**
