### PR TITLE
Update AuthenticatorTokenProvider.cs

### LINKED ISSUE #32871: Missing Dispose in AuthenticatorTokenProvider
### Describe the bug
The [AuthenticatorTokenProvider](https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Extensions.Core/src/AuthenticatorTokenProvider.cs) should dispose the HMACSHA1 instance created on line 57.

### PR DESCRIPTION
**Pull request by dIeGoLi**
Added using to hmacsha1 instance in order to dispose it.

Addresses #32871

### CODE REVIEW

**Comment by dIeGoLi** [comment]
I assume that there is currently a problem with the Build Pipeline / Build Test? I can't imagine that my smallest change would not pass.

**Comment by Pilchie** [comment]
Tagging @HaoK  and @javiercn.
 
It doesn't look like the test failure is related to this change.

**Review by HaoK — APPROVED** [review]

**Comment by dIeGoLi** [comment]
Thank you. Keep doing your awesome work :)

**Comment by HaoK** [comment]
Thanks for the PR @dIeGoLi

**Pull request merged**
