### PR TITLE
Autobahn test fix

### PR DESCRIPTION
**Pull request by mikaelm12**
Moving this [pr](https://github.com/aspnet/AspNetCore/pull/4272) to the release/2.1
Issue: https://github.com/aspnet/AspNetCore-Internal/issues/1320

### CODE REVIEW

**Comment by anurse** [comment]
I can't really tell from the output if the AzDO build is passing, but as long as the WebSockets tests are running successfully with this change, it looks good to me.

**Review by analogrelay — DISMISSED** [review]
Approved? If it's working :)

**Comment by anurse** [comment]
```
 Skipped  Microsoft.AspNetCore.WebSockets.ConformanceTest.AutobahnTests.AutobahnTestSuite
```

in the build log.

Maybe the test was marked skipped to prevent further failures?

**Comment by ryanbrandenburg** [comment]
Likely the problem is [this](https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/WebSockets/test/ConformanceTests/AutobahnTests.cs#L25). If it's relatively fast to add wstest installation to the pr-validation build do so, if not I would say to just merge it and keep an eye out for any fallout since this fails 100% of TeamCity tests. Either way make sure there's an (open) issue to remove that constitutionality when there's no place that actively uses it.

**Comment by anurse** [comment]
> Likely the problem is [this](https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/WebSockets/test/ConformanceTests/AutobahnTests.cs#L25). If it's relatively fast to add wstest installation to the pr-validation build do so, if not I would say to just merge it and keep an eye out for any fallout since this fails 100% of TeamCity tests.

We need to know for sure if it's actually going to fix the tests. If @mikaelm12 has successfully run the tests locally, that's sufficient for me.

On a parallel note, we really should enable the tests in the PR validation ASAP. It's pretty simple to set up wstest, the logic is here: https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/WebSockets/setup-wstest.ps1 (and a similar `.sh`). Basically the steps are:

1. Install Python (could be done with an AzDO task probably?)
1. Use Python's package manager `pip` to install the `autobahntestsuite` package

The script I linked uses [virtualenv](https://virtualenv.pypa.io/en/latest/) because it was designed to be run on an agent and kept around permanently, so it tries to make it easy to remove and isolate from other python installs/builds. If we install it as part of the build steps, I feel much less inclined to bother with virtualenv.

**Comment by natemcmaster** [comment]
> On a parallel note, we really should enable the tests in the PR validation ASAP.

+1. Feel free to open issues on this repo and label as `area-infrastructure` to track this kind of work.

**Review by natemcmaster — APPROVED** [review]

**Comment by mikaelm12** [comment]
Took a little bit to get the Autobahn test suite set up locally but looks like the tests are passing now
autobahntestpass

**Pull request merged**
