### PR TITLE
Allow runtime compilation to be configured via the hosting startup.

### LINKED ISSUE #38465: Razor runtime view compilation via environment variable not working in .NET 6
Runtime view compilation appears to not be working in .NET 6 Razor Pages projects when using the environment variable to specify this behavior as described here:

https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-6.0&tabs=visual-studio#conditionally-enable-runtime-compilation-in-an-existing-project

If I manually add `AddRazorRuntimeCompilation()` in ConfigureServices it does work though.

I'm including v6.0.0 of the assembly package:
`<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="6.0.0" />`

And my launch profile has the following section:
```
"environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_HOSTINGSTARTUPASSEMBLIES": "Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation"
      }
```

Worked as expected in .NET 5 on the same project.

### PR DESCRIPTION
**Pull request by pranavkm**
As part of refactoring how Razor Pages are loaded, the ability to use runtime compilation via the hosting startup / env variable was broken.
The refactoring assumed AddRuntimeCompilation was always invoked after a call to AddRazorPages / AddControllersWithViews etc which is not the case
for registration via the HostingStartup. This PR address this defect.

Fixes https://github.com/dotnet/aspnetcore/issues/38465

### CODE REVIEW

**Comment by isaacdontjelindellblp** [comment]
Hi @pranavkm - as someone who is unfamiliar with the .NET dev process, but is affected by this issue - how will this fix be released? Is it going to be included in a patch to .NET 6, or will we have to wait until .NET 7 to see this fix? I've read through the linked issue, but the outcome isn't clear to me. Thanks!

**Comment by pranavkm** [comment]
@isaacdontjelindellblp my hope is to backport this to a 6.0 release once it's accepted in to main.

**Comment by isaacdontjelindellblp** [comment]
> @isaacdontjelindellblp my hope is to backport this to a 6.0 release once it's accepted in to main.

@pranavkm Fantastic - thanks much!

**Comment by pranavkm** [comment]
@dotnet/aspnet-blazor-eng could I get a quick review on this? I'd like to consider this for a 6.0 patch.

**Review by javiercn — APPROVED** [review]
LGTM

**Comment by AndrewTriesToCode** [comment]
Thanks for pushing this through @pranavkm

**Pull request merged**
