### PR TITLE
Remove unused HTML files

### PR DESCRIPTION
**Pull request by dougbu**
- just a bit confusing to leave these around
- the files haven't been used since @pakrym removed the resources in 56c064bd53ed

### CODE REVIEW

**Comment by dougbu** [comment]
/ping @JunTaoLuo checks are done and everything went well

**Review by davidfowl — APPROVED** [review]

**Comment by davidfowl** [comment]
@dougbu before merge @Tratcher  should do a look over. We have a built in error page in hosting as well as the middleware and these were used for that. If nothing is embedded I'm not sure where they are coming from.

**Comment by davidfowl** [comment]
Yah the actual code is here now https://github.com/dotnet/aspnetcore/tree/master/src/Shared/ErrorPage

**Comment by dougbu** [comment]
> Yah the actual code is here now https://github.com/dotnet/aspnetcore/tree/master/src/Shared/ErrorPage

No need to wait for @Tratcher then❔

**Comment by davidfowl** [comment]
Yea, merge it

**Comment by JunTaoLuo** [comment]
Post-hoc :shipit:

**Pull request merged**
