### PR TITLE
Merge branch 'release/5.0-preview7' => 'master'

### PR DESCRIPTION
**Pull request by pranavkm**
I think I messed up the merge here: https://github.com/dotnet/aspnetcore/pull/23427#issuecomment-652170764 and the bot is confused.

### CODE REVIEW

**Comment by dougbu** [comment]
@pranavkm I think you need @SteveSandersonMS here, sorry. In addition what's with the validation failures❔

**Comment by pranavkm** [comment]
Pinged @javiercn about the failures.

**Comment by pranavkm** [comment]
@dougbu should be good now.

**Comment by dougbu** [comment]
@pranavkm my point was mostly that I'd like @SteveSandersonMS to look at this before we merge. All of the incoming changes are his. With his signoff, you're free to merge.

**Comment by SteveSandersonMS** [comment]
> All of the incoming changes are his

I’m not totally following that - only one of the commits here are mine. 

Nonetheless I have no reason to question the others. Since they are already in the preview7 branch I’ll mark this as approved.

**Review by SteveSandersonMS — APPROVED** [review]

**Pull request merged**
