### PR TITLE
update contributing guidelines to state that Squash is preferred

### PR DESCRIPTION
**Pull request by danmoseley**
I understand from @captainsafia that this is de-facto policy.

BTW, we may want to require admin elevation for merge and rebase into main. dotnet/runtime does this and it has caused little or no trouble.

### CODE REVIEW

**Review by JamesNK — APPROVED** [review]

**Review by captainsafia — APPROVED** [review]

**Comment by danmoseley** [comment]
Or rather not merging, as I forgot that we require everything's green 😃

**Comment by riarenas** [comment]
Since these are the azure pipelines hosted mac machines I don't think there's much to dig in other than retrying. The leg seems to hover between 15 minutes and 1 hour in the worst cases so it's not a matter of increasing the timeout. 

@MattGal I don't know if you have access to some azure pipelines data that would give you any interesting insights here?

**Comment by MattGal** [comment]
> @MattGal I don't know if you have access to some azure pipelines data that would give you any interesting insights here?

Not really, there just isn't enough telemetry about hosted MacOS machines to solve this it would seem.  I spent a lot of time with the hosted MacOS folks hunting down "why do macs get slow sometimes?" with an engineer from the MacCloud team and there simply wasn't enough telemetry to say what specifically was happening. 

I've forwarded this particularly egregious example along to my contact over there (it looks like these jobs timed out at 3/4 hours and normally take < 20 minutes?!?) but the "good" news is that they are working on replacing hosted Macs with more modern hardware to run the VMs on (availability date unknown, but we've done some experiments on them that were promising)

As for now, all we can really do is retry and perhaps use shorter timeouts when something typically takes a short time to complete.

**Comment by danmoseley** [comment]
Thanks @MattGal @riarenas I'll rerun. It's particularly unfortunate as I'm only changing a markdown file. Do either of you have some insight into how to allow *.md to avoid triggering validation, without causing this conundrum? https://github.com/dotnet/aspnetcore/pull/44421#issuecomment-1275412111

**Pull request merged**
