### PR TITLE
[Blazor] Fix `Microsoft.AspNetCore.Components.WebView.props` not getting packed correctly

### LINKED ISSUE #52637: Microsoft.AspNetCore.Components.WebView.props does not get imported correctly
We're seeing build failures in https://github.com/dotnet/maui/pull/19236 caused by `src/Components/WebView/WebView/src/build/Microsoft.AspNetCore.Components.WebView.props` not being found in the produced NuGet package for `Microsoft.AspNetCore.Components.WebView`.

### PR DESCRIPTION
**Pull request by MackinnonBuck**
Fixes #52637

### CODE REVIEW

**Review by Eilon — APPROVED** [review]

**Comment by danmoseley** [comment]
@Eilon how can we test this in such a way that we cover the path we missed in testing the original change? Can MAUI test privates?

**Comment by mattleibow** [comment]
By the time this reaches maui, it is very late. We have to wait for aspnet, runtime, android and ios - then the sdk and possibly installer.

nd then still we may not pick it up because we typically build with public versions from nuget.org.

**Comment by jonathanpeppers** [comment]
From what I observed, you shouldn't need MAUI to test if this change fixes the problem. You could add this package to a console app and build it -- it was failing during MSBuild evaluation before.

**Review by javiercn — APPROVED** [review]

**Comment by rmarinho** [comment]
Can we get this merged to see if it helps with ou net9 builds? Thanks

**Comment by Eilon** [comment]
Are we OK to merge this? I haven't run locally yet but it _seems_ obviously the right fix. It's blocking MAUI net9 now.

**Pull request merged**
