### PR TITLE
Remove unused `using`-s from Program and Startup classes

### PR DESCRIPTION
**Pull request by mkArtakMSFT**
Addresses #8347

### CODE REVIEW

**Review by javiercn — APPROVED** [review]
It's nearly impossible to validate this PR by hand. I'm ok with it so long as the template tests pass. If something breaks we'll get pinged.

**Review by ryanbrandenburg — APPROVED** [review]
What @javiercn said. Each of these have tests that compile them, if those pass you're golden.

**Review by Eilon — APPROVED** [review]
Looks good! Hopefully it's correct 😄

**Review by davidfowl — CHANGES_REQUESTED** [review]
This isn't a good change. We actually want some of these because of extension methods that exist in various places.

**Comment by mkArtakMSFT** [comment]
@davidfowl, can you be more specific please. Which particular namespaces you'd like to keep?
Here I'm removing only those which aren't used.

**Comment by davidfowl** [comment]
```
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
```

I can't open up VS now because I'm updating but for example, in Program.cs the logging extensions methods are in Microsoft.Extensions.Logging (AddConsole, AddEventLog etc) and the configuration extension methods are in Microsoft.Extensions.Configuration. Having those unused using these make it easier to find logging providers and configuration providers without having to type it out by hand.

**Comment by mkArtakMSFT** [comment]
Sounds good, @davidfowl. I'll leave these two usings untouched.

**Review by davidfowl — APPROVED** [review]

**Pull request merged**
