### PR TITLE
Fix syntax error in runtests.sh

### PR DESCRIPTION
**Pull request by HaoK**

### CODE REVIEW

**Comment by HaoK** [comment]
Spaces around '=' when setting vars causes syntax errors

**Review by BrennanConroy — APPROVED** [review]
Haha, and this is why we moved most of this to C#

**Comment by HaoK** [comment]
Yeah it results in super confusing errors like:
```
Completed Helix job with exit code '1'
./runtests.sh: line 93: exit_code: command not found
Finished tests...exit_code=0

```

**Comment by dougbu** [comment]
Do we know the root cause of the templates test failure?
```
Checking for Microsoft.AspNetCore.App/
Found Microsoft.AspNetCore.App/, copying to /datadisks/disk1/work/9A08087C/w/B83509A4/e/.dotnet16165/shared/Microsoft.AspNetCore.App/5.0.0-preview.4.20205.13
Exception in InstallAspNetAppIfNeeded: System.IO.DirectoryNotFoundException: Could not find a part of the path '/datadisks/disk1/work/9A08087C/w/B83509A4/e/.dotnet16165/shared/Microsoft.AspNetCore.App/5.0.0-preview.4.20205.13/Microsoft.AspNetCore.App/Microsoft.Extensions.Configuration.Xml.dll'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at RunTests.TestRunner.InstallAspNetAppIfNeededAsync() in /datadisks/disk1/work/9A08087C/w/B83509A4/e/RunTests/TestRunner.cs:line 101
```

**Comment by HaoK** [comment]
Yeah those fixes are a part of https://github.com/dotnet/aspnetcore/pull/20659 which I guess can just be updated with this fix

**Comment by HaoK** [comment]
Added into https://github.com/dotnet/aspnetcore/pull/20659

**Pull request closed without merging**
