### PR TITLE
React to kestrel merge conflict

### PR DESCRIPTION
**Pull request by Tratcher**
Merge conflict with breaking changes...

### CODE REVIEW

**Review by JunTaoLuo — APPROVED** [review]

**Comment by JunTaoLuo** [comment]
Got offline approval from @anurse to merge immediate to fix build.

**Comment by JunTaoLuo** [comment]
Compilation on macOS completed as a sanity check.

**Comment by anurse** [comment]
> Got offline approval from @anurse to merge immediate to fix build.

Confirmed

**Comment by anurse** [comment]
🤞

**Pull request merged**
