### PR TITLE
Use Result instead of GetAwaiter().GetResult()

### PR DESCRIPTION
**Pull request by Kahbazi**
Addresses #13611

### CODE REVIEW

**Comment by pranavkm** [comment]
@Kahbazi as discussed in https://github.com/aspnet/AspNetCore/issues/13611, the `GetAwaiter().GetResult()` is intentionally used to produce a better async exception stack trace. We use this fairly commonly through our code base.

Closing this PR since the change isn't desirable.

**Comment by Kahbazi** [comment]
But in this case there will be never any exception since IsCompletedSuccessfully has been checked. So I think calling Result has better performance then GetAwaiter().GetResult.
Also Result has been used in similar cases in this repository.

**Comment by pranavkm** [comment]
Yup,  you're right.

**Comment by pranavkm** [comment]
Thanks for the PR!

**Pull request merged**
