### PR TITLE
Add back strings.json for WebApi-CSharp

### PR DESCRIPTION
**Pull request by TanayParikh**
Extension of https://github.com/dotnet/aspnetcore/pull/40128 per @phenning's comment.

Will need to revert (re-delete) these files upon completion of https://github.com/dotnet/aspnetcore/issues/37202 (when we remove the ide.host.json property `overrideDefault` name/description.

### CODE REVIEW

**Comment by TanayParikh** [comment]
Note didn't restore the F# WebApi strings.json as they don't have overrides: 
https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/WebApi-FSharp/.template.config/ide.host.json

**Comment by pranavkm** [comment]
I'll let @phenning sign off on this 👍🏽

**Comment by phenning** [comment]
> Note didn't restore the F# WebApi strings.json as they don't have overrides: https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/WebApi-FSharp/.template.config/ide.host.json

Looks good to me, sorry for the confusion with this.

**Review by phenning — APPROVED** [review]
:shipit:

**Comment by TanayParikh** [comment]
Thanks! Enabled auto-merge _after_ the approval this time around 😄

**Pull request merged**
