### PR TITLE
Fix fetch of package version in eng/Publishing.props

### PR DESCRIPTION
**Pull request by dougbu**
- target project is a test project; need to undo `$(SkipTestBuild)` impact in these jobs

nit: remove a comment from DeveloperCertificates project that's irrelevant now

### CODE REVIEW

**Comment by dougbu** [comment]
Should help close dotnet/core-eng#10415 though I still have some questions there. Should also unblock publication in our official builds.

**Comment by dougbu** [comment]
Test internal build (with some added debug `Message` tasks and binary logs) worked: https://dev.azure.com/dnceng/internal/_build/results?buildId=764739

**Review by MattGal — APPROVED** [review]

**Review by wtgodbe — APPROVED** [review]

**Pull request merged**
