### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by Tratcher**
@wtgodbe I'm seeing errors that `@dotnet-maestro-bot` doesn't exist or have write access to the repo?

### CODE REVIEW

**Review by JamesNK — APPROVED** [review]
😭

**Comment by JamesNK** [comment]
@adityamandaleeka @joperezr It looks like some areas have no owner now, e.g. `src/Security`, `src/Shared/runtime`. Should find a new owner.

@Tratcher On the topic of `src/Shared/runtime`, do your actions for keeping code in sync need to be updated?

**Comment by Tratcher** [comment]
@JamesNK it should all be fine for now, https://github.com/dotnet/aspnetcore/issues/18943 will be pinged when there's a new diff.

Note that there's talk of locking down permissions where github actions would no longer have write access to the repo. The whole setup will need re-thinking if it comes to that.

**Comment by JamesNK** [comment]
> Note that there's talk of locking down permissions where github actions would no longer have write access to the repo. The whole setup will need re-thinking if it comes to that.

😐

**Pull request merged**
