### PR TITLE
Fix SignalR typescript tests with Chrome SameSite reaction

### PR DESCRIPTION
**Pull request by BrennanConroy**
Chrome released its SameSite cookie support on 8/25 which broke some tests that used cookies cross-domain. This fixes the tests.

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]

**Review by wtgodbe — APPROVED** [review]

**Comment by Pilchie** [comment]
Thanks @BrennanConroy - FYI test-only fixes can be proactively merged unless you have concern about the risk to the build.

**Comment by BrennanConroy** [comment]
> proactively merged unless you have concern about the risk to the build

Mac passed on this PR which was the remaining failures on https://github.com/dotnet/aspnetcore/pull/25090 which had half of this change. I've verified before and after on my Windows machine as well, so confident this wont break.

If someone wants they can merge then 👍

**Comment by dougbu** [comment]
@ajaybhargavb the validation build for this PR failed due to build ordering issues. Something has destabilized the release/5.0 branch significantly because I've seen this a few times in the last week. Please use some of your ops-on-call time to figure out what's busted.

**Comment by ajaybhargavb** [comment]
@dougbu, I'm currently heads down on getting https://github.com/dotnet/aspnetcore/pull/25219 merged. Would you like me to file an issue to track this?

**Comment by dougbu** [comment]
@ajaybhargavb yes please. And, please also mention that issue as important when handing off your ops rotation.

**Comment by ajaybhargavb** [comment]
Filed https://github.com/dotnet/aspnetcore/issues/25293

**Comment by dougbu** [comment]
@BrennanConroy thanks for opening #25473 too❕

You'll probably need to `cherry-pick` @captainsafia's #25324 and skip some of the Kestrel Interop tests to get that PR working. When you succeed, I'll copy what you've done to test out my #25217😺

**Pull request merged**
