### PR TITLE
Clean up ManualResetEvent usage in tests

### PR DESCRIPTION
**Pull request by Tratcher**
#6172 Reduces the likelihood of test hangs caused by ManualResetEvent induced thread blocks.

### CODE REVIEW

**Comment by pranavkm** [comment]
Changes to `CacheTagHelperTest` look good. I think someone more familiar with the other tests do an overall signoff.

**Review by jkotalik — APPROVED** [review]

**Comment by muratg** [comment]
@natemcmaster Thoughts on check-ins until we get a candidate build at this point? This is a test-only change but if the risk is not reasonable in your opinion, we can delay.

**Review by JunTaoLuo — APPROVED** [review]
LGTM

**Review by natemcmaster — APPROVED** [review]

**Comment by natemcmaster** [comment]
Risk seems low. :shipit:

**Review by muratg — APPROVED** [review]

**Pull request merged**
