### PR TITLE
Negotiate protocol versioning and ConnectionID split

### PR DESCRIPTION
**Pull request by BrennanConroy**
Backport the Negotiate versioning and ConnectionID split

- [x] SignalR Negotiate protocol versioning https://github.com/aspnet/AspNetCore/pull/13389
- [x] SignalR ConnectionToken/ConnectionAddress feature https://github.com/aspnet/AspNetCore/pull/13773
- [x] Add support for negotiateVersion query string parameter https://github.com/aspnet/AspNetCore/pull/13880
- [x] [TS] Add support for negotiateVersion and connectionToken https://github.com/aspnet/AspNetCore/pull/14157
- [x] C# and Java client negotiateVersion cleanup https://github.com/aspnet/AspNetCore/pull/14196

Manual Testing:
- [x] 3.0 JS client + 3.1 server
- [x] 3.0 Java client + 3.1 server
- [x] 3.0 C# client + 3.1 server
- [x] 3.1 JS client + 3.0 server
- [x] 3.1 Java client + 3.0 server
- [x] 3.1 C# client + 3.0 server
- [x] 2.1 JS client + 3.1 server
- [x] 2.1 C# client + 3.1 server
- [x] 2.2 JS client + 3.1 server
- [x] 2.2 Java client + 3.1 server
- [x] 2.2 C# client + 3.1 server
- [x] 3.1 client + 3.1 server + SignalR Service
- [x] 3.0 client + 3.1 server + SignalR Service

### CODE REVIEW

**Comment by anurse** [comment]
This feature work is **approved** for 3.1 (internal tracking item: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/984226/) and can be merged (when all the usual reviews/builds/etc. are complete).

**Comment by BrennanConroy** [comment]
Ready for review. I've got the core scenarios tested and I'll work on completing the rest.

**Comment by BrennanConroy** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=372086&view=logs

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/3173

**Review by halter73 — APPROVED** [review]

**Comment by BrennanConroy** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=372087

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/3184

**Pull request merged**
