### PR TITLE
Update submodules.props for EF 2.2.6

### PR DESCRIPTION
**Pull request by ajcvickers**

### CODE REVIEW

**Comment by ajcvickers** [comment]
@dougbu @JunTaoLuo @natemcmaster Did I miss anything here on on the EF branch for 2.2.6?

**Comment by natemcmaster** [comment]
Update the git submodule, too.

**Comment by ajcvickers** [comment]
@natemcmaster Thought I did that, but didn't end up in the commit. Looks like it is there now.

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
@ajcvickers yup, everything's in place now

**Review by natemcmaster — APPROVED** [review]
Added a commit to your PR to fix a bug in dependencies.props that was causing PR build failures.

**Comment by ajcvickers** [comment]
@dougbu @natemcmaster @JunTaoLuo Can't get this patch build to pass. Doesn't look like the failures are due my changes. Any ideas?

**Comment by JunTaoLuo** [comment]
@pranavkm can you take a look and see if the test failure on Windows is unrelated?

**Comment by JunTaoLuo** [comment]
As for the hang. I'd need to backport the infrastructure to diagnose background processes from master but I would imagine the puppeteer processes are not cleaned up and that's what's causing the builds to hang.

**Comment by dougbu** [comment]
> backport the infrastructure to diagnose background processes from master

Suggest only making the `KillProcesses.ps1` addition to `build.ps1` to minimize churn in the downlevel branches. We should be pretty confident something external (PowerShell, MSBuild, &hellip;) is changing to cause these hangs because the release/2.x branches have stable infrastructure internally. (If you find an exception to that, it deserves a hard look.)

**Comment by pranavkm** [comment]
That usually indicates something around launching chromium failed. Logging an issue for it to see if we could make some stability improvement

**Comment by pranavkm** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=224304

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2641

**Comment by JunTaoLuo** [comment]
@ajcvickers I think if the test failure is the only issue, you can merge this PR.

**Pull request merged**
