### PR TITLE
Ensure non-final builds have unique package GUIDs

### PR DESCRIPTION
**Pull request by JunTaoLuo**
This addresses https://github.com/dotnet/core-sdk/issues/2655

The regression seems to be https://github.com/aspnet/AspNetCore/commit/41ce223c1cf4ffd482c4ea36e88ed44a94db37b3#diff-8a63ea279503159f0bb870af84feae00L10. I'm assuming it was an oversight when removing the `BuildNumberSuffix` variable. I'm updating the logic to mimic the previous behaviour, albeit using different variables.

I've verified with this change that the product code and upgrade code are now unique between builds. However, I don't think I'll be able to do end to end verification.

I plan on merging as soon as builds are green, so the change can be consumed downstream.

cc @johnbeisner

### CODE REVIEW

**Comment by johnbeisner** [comment]
@JunTaoLuo 
Why would the final builds need a stable GUID, release over release. I would think we would have the same problem.

**Review by ghost — APPROVED** [review]

**Comment by JunTaoLuo** [comment]
Yea, I wasn't sure why but this is the behaviour I see in our previous code. Since I couldn't track down why it was built that way, I figured it's safer to keep it until I can find out more.

**Comment by JunTaoLuo** [comment]
Do you know what's the logic used by other teams? @johnbeisner

**Comment by johnbeisner** [comment]
For dotnet/core-sdk MSIs:
```
<GenerateGuidFromName Name="$(SdkMSIInstallerFile)">
      <Output TaskParameter="OutputGuid"
```

Where the seed string 'SdkMSIInstallerFile' for the MSI GUID is full path + filename: "C:\buildrootcoresdk\artifacts\packages\Release\Shipping\dotnet-sdk-3.0.100-preview7-012608-win-x64.msi"

**Comment by JunTaoLuo** [comment]
Ah, then I think we should follow suite.

**Comment by joeloff** [comment]
The logic got removed as part of the arcade work it seems: https://github.com/aspnet/AspNetCore/commit/41ce223c1cf4ffd482c4ea36e88ed44a94db37b3#diff-8a63ea279503159f0bb870af84feae00

**Pull request merged**
