### PR TITLE
Set crossorigin to anonymous for integrity attribute

### LINKED ISSUE #20305: CORS problem with subresource integrity
I am trying to load the webassembly version of blazor into an existing javascript app.
But I have problems with the subresource integrity. It throws this error message:
```console
Subresource Integrity: 
The resource 'http://test.local/_framework/wasm/dotnet.3.2.0-preview2.20159.2.js' has an integrity attribute,
but the resource requires the request to be CORS enabled to check the integrity, and it is not.
The resource has been blocked because the integrity cannot be enforced.
```

I included the script within the head with this snippet:
```javascript
var script = document.createElement('script');
script.src = 'http://test.local/_framework/blazor.webassembly.js';
document.head.appendChild(script);
```

### PR DESCRIPTION
**Pull request by MarkusRodler**
dotnet/aspnetcore#20305

### CODE REVIEW

**Review by javiercn — APPROVED** [review]
Looks good to me!

Thanks for the contribution!

@SteveSandersonMS I'll leave you to do the final merge.

**Comment by SteveSandersonMS** [comment]
Thanks for the contribution, @MarkusRodler!

I think we would want to be consistent about the use of `crossOrigin: anonymous` whenever we're fetching framework resources. If we change it for this script tag, it should also be changed in the other places I mentioned on the original issue. Otherwise it because another point of confusion for other developers, and a strange extra rule we have to describe in docs.

**Comment by MarkusRodler** [comment]
I copy the comment from the issue: (Idk if is better to communicate in the issue or in the pr)
@SteveSandersonMS What should be set on the other three places? Your first link points to the generation of an html tag. This is the only one I found in that project with an integrity attribute.
The other three links points to fetch-API calls. I didnt't found a `crossOrigin` attribute there but an `mode` attribute to set. But these links are not problematic in my case. Everything works to download _framework stuff via CORS. I don't know if it will be inherited from the first generated html tag or if the default is cors.

**Comment by MarkusRodler** [comment]
This are the other places i mentioned:
https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/Web.JS/src/Platform/WebAssemblyResourceLoader.ts#L30
https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/Web.JS/src/Platform/WebAssemblyResourceLoader.ts#L99
https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/ProjectTemplates/ComponentsWebAssembly.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Client/wwwroot/service-worker.published.js#L21

**Comment by SteveSandersonMS** [comment]
@MarkusRodler We decided your PR is fine as-is and merged it. Thanks!

**Pull request merged**
