### PR TITLE
Update WiX to signed build

### PR DESCRIPTION
**Pull request by dougbu**
- #36854

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Comment by dougbu** [comment]
- Should I change https://github.com/dotnet/aspnetcore/blob/release/6.0-rc2/eng/SignCheckExclusionsFile.txt❔
- Does this change anything about the WiX toolset we recommend in https://github.com/dotnet/aspnetcore/blob/release/6.0-rc2/docs/BuildFromSource.md#wix-optional or https://github.com/dotnet/aspnetcore/blob/release/6.0-rc2/src/Installers/Windows/README.md❔

**Comment by dougbu** [comment]
Oops, wrong reference. Issue is #36854

**Comment by joeloff** [comment]
> * Should I change https://github.com/dotnet/aspnetcore/blob/release/6.0-rc2/eng/SignCheckExclusionsFile.txt❔
> * Does this change anything about the WiX toolset we recommend in https://github.com/dotnet/aspnetcore/blob/release/6.0-rc2/docs/BuildFromSource.md#wix-optional or https://github.com/dotnet/aspnetcore/blob/release/6.0-rc2/src/Installers/Windows/README.md❔

wixstdba was one of the main pain points. It's been signed for a while now since we moved to 3.14, except now it will have multiple authenticode signatures. You should be able to clear out some of the other exclusions for WiX as well.

The recommendation for the build from source is still fine as long as that points people to 3.14 since that's the minimum requirement if you're trying to build for arm64. The only difference is that our copy of the toolset we use internally is signed by Microsoft and WiX. Functionally speaking, it's the official 3.14.0.4118 build (hence two versions in the semver to track our build process and reflect the official WiX build at the same time).

**Comment by dougbu** [comment]
> You should be able to clear out some of the other exclusions for WiX as well.

@mmitche w/ post-build signing and much later validations, is there a quick way to check whether removing https://github.com/dotnet/aspnetcore/blob/release/6.0-rc2/eng/SignCheckExclusionsFile.txt entries breaks anything❔

**Comment by dougbu** [comment]
Merging now. We can experiment w/ SignCheckExclusionsFile.txt after I understand how to verify things e2e e.g. once we're looking at 'main'

**Comment by mmitche** [comment]
> > You should be able to clear out some of the other exclusions for WiX as well.
> 
> @mmitche w/ post-build signing and much later validations, is there a quick way to check whether removing https://github.com/dotnet/aspnetcore/blob/release/6.0-rc2/eng/SignCheckExclusionsFile.txt entries breaks anything❔

+ @adiaaida 
The nightly validation builds should catch that I think.

**Comment by ericstj** [comment]
When does this change hit main?  Can we manually port?

**Pull request merged**
