### PR TITLE
Better way to detect "Failed to start the HttpConnection before stop() was called."

### LINKED ISSUE #38893: Better way to detect "Failed to start the HttpConnection before stop() was called."
I'm using some client side SignalR-Services that get disposed, as soon as the component utilizing it gets destroyed.

Right now my code looks like this:

```
this.hubConnection.start().then(_ => {
    this.initializeConnection();
    this.isConnected$.next(true);
}, e => {
    if (e.message !== 'Failed to start the HttpConnection before stop() was called.') { throw e; }
});
```

This default catch-behavior is pretty unclean - but I quite common case I'm not interested in. It would be nice if this error could be detected _cleaner_ somehow.

### PR DESCRIPTION
**Pull request by z77ma**
# Use specifically typed error when connection failed to start 

The AbortError is used to mark a situation when a stop() method is being invoked before a call to start() succeeds.

## Description

As proposed in the issue the specific error is returned in case stop was called before start ended in the HttpConnection and HubConnection classes

Fixes #38893

### CODE REVIEW

**Comment by z77ma** [comment]
Hi, @halter73, could you check if I understood your suggestion in the issue correct? Thanks.

**Review by halter73 — APPROVED** [review]
Thanks @z77ma! The tests look good too.

**Comment by halter73** [comment]
@BrennanConroy does this look good to you too?

**Review by BrennanConroy — APPROVED** [review]

**Comment by BrennanConroy** [comment]
Thanks for the enhancement @z77ma !

**Comment by angelaki** [comment]
Thank you very much guys! Sorry I didn't contribute 👎

**Pull request merged**
