### PR TITLE
Use the defaults that existed in Kestrel before

### PR DESCRIPTION
**Pull request by davidfowl**
Preserving the existing settings but now at the transport level.

### CODE REVIEW

**Comment by davidfowl** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=208641

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/1950

**Review by jkotalik — APPROVED** [review]

**Comment by Tratcher** [comment]
@davidfowl you know this missed preview6, right?

**Comment by davidfowl** [comment]
Yep. @anurse told me it was too late to change these values :trollface: . If there's no performance regression, it's fine.

**Pull request merged**
