### PR TITLE
Explicitly reference Roslyn compiler toolset version that will ship in preview 7

### PR DESCRIPTION
**Pull request by dougbu**
- see also aspnet/EntityFrameworkCore#16370 and aspnet/EntityFrameworkCore#16385 discussions
- grab latest from the '.NET Core 3 Release' channel

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]
LGTM - once again please ACK when you've added the subscription

**Comment by dougbu** [comment]
@pranavkm and @rynowak should I skip the 6 tests that are failing in 'master' (see #11744)? If not, which likely will be fine?

**Comment by dougbu** [comment]
@wtgodbe new subscription for 'release/3.0-preview7' is '57fb441b-6285-4828-9e09-08d6fb351674'

Tests are failing and I'll skip them as soon as I'm sure we know the full set.

**Comment by rynowak** [comment]
@dougbu - go ahead and skip tests. I'll address the bug after the change is merged.

**Comment by wtgodbe** [comment]
@rynowak do you mean we can merge with the failing tests, or is there some commit we can cherry-pick to skip the failing tests?

**Comment by wtgodbe** [comment]
Issue to track disabled tests: https://github.com/aspnet/AspNetCore/issues/11828

**Comment by wtgodbe** [comment]
@dougbu I've switched to `MicrosoftNetCompilersToolsetPackageVersion` as this can't be merged without CodeCheck passing, and I've verified locally that darc updates still work with that property name.

**Comment by dougbu** [comment]
Thanks for the added commits @wtgodbe Looks good❕

**Pull request merged**
