### PR TITLE
Update WorkloadManifest.json.in

### PR DESCRIPTION
**Pull request by wli3**
to unblock https://github.com/dotnet/installer/pull/10226

@mhutch is this the right change for null?

### CODE REVIEW

**Comment by captainsafia** [comment]
Looping @lewing into this since I'm a bit of out of the loop on this.

Last I know, there was a conversation about how we can continue to maintain the behavior of having an optional SDK with this change in place. See https://github.com/dotnet/aspnetcore/pull/31761/files#r614224769.

**Comment by wli3** [comment]
Talked to @mhutch , this is the right thing to do. And the spec will be updated with detail for this situation.

**Review by captainsafia — APPROVED** [review]
Approving to unblock the installer insertion.

**Review by lewing — APPROVED** [review]
Yes this what we discussed see https://github.com/dotnet/designs/pull/206

**Pull request merged**
