### PR TITLE
Enable build acceleration 

### PR DESCRIPTION
**Pull request by ShreyasJejurkar**
1. Enable Accelerated builds for all projects. Read more here => https://github.com/dotnet/project-system/blob/main/docs/build-acceleration.md

### CODE REVIEW

**Comment by ShreyasJejurkar** [comment]
Failure looks unrelated to this change!

**Comment by adityamandaleeka** [comment]
Thanks @ShreyasJejurkar. It would be great to see a before/after comparison showing the impact of this on build time.

**Comment by wtgodbe** [comment]
Agree the failure looks unrelated - were you able to get data on whether this speeds things up in VS?

**Comment by ShreyasJejurkar** [comment]
@wtgodbe in local testing, it does speed up build perf. I will post some screenshot here about that, please give me some more time. Sorry having some office work, got engaged in that.

**Review by RussKie — APPROVED** [review]

**Pull request merged**
