### PR TITLE
Manually resolve ref and runtime packs instead of modifying the .NET SDK used in the build

### PR DESCRIPTION
**Pull request by jkoritzinsky**
# Manually resolve ref and runtime packs instead of modifying the .NET SDK used in the build

## Description

Instead of modifying the SDK used in the build to include the just-built ref and runtime packs, use the same SDK features we use in dotnet/runtime to manually resolve the packs in their layout folders. This removes the need to modify the sdk to build tests.

Fixes https://github.com/dotnet/aspnetcore/pull/54084#discussion_r1493057506

TODO: I might need to modify the testing setup to resolve things correctly, we'll see what CI says.

### CODE REVIEW

**Comment by lewing** [comment]
We need a common way to handle this kind of logic, the one-offs in all the repositories are a problem.

cc @dotnet/project-system

**Comment by drewnoakes** [comment]
@lewing is this a VS-specific scenario? If not then reach out to the SDK or MSBuild teams. If so, can you provide more context?

**Comment by lewing** [comment]
> @lewing is this a VS-specific scenario? If not then reach out to the SDK or MSBuild teams. If so, can you provide more context?

The alias names are also not great if project-system is VS specific only, but I will follow up with the SDK team too.

**Comment by drewnoakes** [comment]
"Project System" is a VS concept: https://learn.microsoft.com/visualstudio/extensibility/creating-a-basic-project-system-part-1

**Comment by lewing** [comment]
> "Project System" is a VS concept: https://learn.microsoft.com/visualstudio/extensibility/creating-a-basic-project-system-part
Understood, I was simply suggesting more like vs-project-system.  From my perspecting there is a great deal of overlap here

**Review by mmitche — APPROVED** [review]

**Comment by mmitche** [comment]
Nice, So then the remaining work in this area is to be able to find the netcore targeting pack so that we can get the nethost headers.

**Comment by drewnoakes** [comment]
> Understood, I was simply suggesting more like vs-project-system. From my perspecting there is a great deal of overlap here (the link is 404)

The name comes from `dotnet/project-system` on GitHub.

Fixed the link.

**Review by wtgodbe — APPROVED** [review]
Other than the helix proj msbuild error, LGTM. Could you push this branch to the internal repo, run a build of https://dev.azure.com/dnceng/internal/_build?definitionId=21, and make sure the produced installers have the same content they used to?

**Comment by jkoritzinsky** [comment]
Official build installers have the same contents as previously.

**Pull request merged**
