### PR TITLE
Default IdentityUI to Bootstrap4

### LINKED ISSUE #8353: Make Bootstrap4 the default UIFramework for the Identity UI
Change this to `Bootstrap4`:

https://github.com/aspnet/AspNetCore/blob/bfec2c14be1e65f7dd361a43950d4c848ad0cd35/src/Identity/UI/src/IdentityBuilderUIExtensions.cs#L33

This will help avoid all the places in the templates where the value must be set to Bootstrap4 explicitly, such as:

https://github.com/aspnet/AspNetCore/blob/bc009fc0f180532e003b7d3e466c5a1a2456a630/src/ProjectTemplates/Web.ProjectTemplates/content/RazorPagesWeb-CSharp/Startup.cs#L73

Note: This is super Announcement-worthy, so please make sure an announcement issue gets logged for this.

So, the work here is to:
* [ ] Make the default Bootstrap4
* [ ] Remove the setting from all the templates
* [ ] Post an announcement

### PR DESCRIPTION
**Pull request by ryanbrandenburg**
Fixes #8353.

### CODE REVIEW

**Comment by javiercn** [comment]
Doesn't this break any test? I think there are tests that need to change as part of this fix, as we test both bootstrap3 and bootstrap4 versions, I have the feeling that changing the default will make it so that bootrstrap3 tests don't test bootrstrap3 but 4 as I imagine they rely on the defaults.

**Comment by javiercn** [comment]
Other than that, looks good.

**Review by Eilon — APPROVED** [review]
The code change looks good. I defer to @javiercn on other matters.

**Comment by ryanbrandenburg** [comment]
Which tests are you referring to? If you [mean these](https://github.com/aspnet/AspNetCore/blob/master/src/Identity/test/Identity.FunctionalTests/Bootstrap3Tests/Bootstrap3AuthorizationTests.cs) then it would seem that it's already explicit.

**Review by javiercn — APPROVED** [review]

**Pull request merged**
