### PR TITLE
Switch to 1ES R&D Pools on main

### PR DESCRIPTION
**Pull request by jonfortescue**
- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

**Switch to 1ES R&D Pools on main**
We need to switch to the 1ES pools. This does that on main.

Tracking issue: https://github.com/dotnet/core-eng/issues/14276

### CODE REVIEW

**Review by ulisesh — APPROVED** [review]
LGTM

**Review by dougbu — APPROVED** [review]
Thanks @jonfortescue❕

**Comment by dougbu** [comment]
@jonfortescue please let us know if you need help merging

**Comment by jonfortescue** [comment]
@dougbu looks like I have permissions to merge! Doing that now.

**Pull request merged**
