### PR TITLE
update Nuget.Protocol version

### PR DESCRIPTION
**Pull request by danmoseley**
Resolve https://github.com/dotnet/aspnetcore/security/dependabot/116

### CODE REVIEW

**Comment by danmoseley** [comment]
@wtgodbe looks like we have dependabot configured to ask permission before making updates like this. is there any reason we don't have it simply create the PR's? I assume it would ignore anything handled by our own dependency flow.

**Comment by wtgodbe** [comment]
> looks like we have dependabot configured to ask permission before making updates like this. is there any reason we don't have it simply create the PR's? I assume it would ignore anything handled by our own dependency flow.

We initially disabled it because dependabot incorrectly modifies our `package.lock.json` files to include references to `npmjs.com` instead of our AzDO feed. I'm looking now to see if there's a way to have it only update our C# deps, it looks like there are configurable rules

**Review by wtgodbe — APPROVED** [review]
Tested this locally & it works (BaselineGenerator doesn't run in CI)

**Comment by wtgodbe** [comment]
> I'm looking now to see if there's a way to have it only update our C# deps, it looks like there are configurable rules

Screenshot 2024-02-20 at 10 01 48 AM

Yep, just enabled this. Will keep an eye out for incoming PRs to see if it worked.

**Pull request merged**
