### PR TITLE
chore : Remove unwanted `using` statement

### PR DESCRIPTION
**Pull request by ShreyasJejurkar**
Just misc changes removed unwanted usings statement. 
Area wise commits 

Antiforgery - https://github.com/dotnet/aspnetcore/commit/ff48cc47d2841f41c273a7eb9ee113785c6eeb22
Azure - https://github.com/dotnet/aspnetcore/pull/39176/commits/8e5527e143a40b501d76912d2f534047f714bba5
Caching - https://github.com/dotnet/aspnetcore/pull/39176/commits/ced03ef14ed3445fefa90cb7e72fe73760044f19
Components - https://github.com/dotnet/aspnetcore/pull/39176/commits/0f74df88f65a7a0fcae7c14c8e0cc8770c473344
Configuration.KeyPerFile - https://github.com/dotnet/aspnetcore/pull/39176/commits/591988a2cc04469d9278ba266cf91c1492710cd3
DataProtection - https://github.com/dotnet/aspnetcore/pull/39176/commits/663d1a3ba479074b840503330c3ccf30d20d6bfe
DefaultBuilder - https://github.com/dotnet/aspnetcore/pull/39176/commits/0e5326cdefa9a166d1dbd8372dd2fccddcd9f82e
Features - https://github.com/dotnet/aspnetcore/pull/39176/commits/a9216cd572e71ad0192be186d1bf020e892795a0
FileProviders - https://github.com/dotnet/aspnetcore/pull/39176/commits/26c838532b28f558be0b9dc0c8b5222a44ed92e8
Framework - https://github.com/dotnet/aspnetcore/pull/39176/commits/b8d524c6169d65206788ccd2eccf2512b1abcdc9
Hosting - https://github.com/dotnet/aspnetcore/pull/39176/commits/269a17abe8d64569bdfcd1316e41d5a3fb192dfc
Html.Abstractions - https://github.com/dotnet/aspnetcore/pull/39176/commits/eb5487f4691d55bf3c942257a4c3ef3541767b27
Http - https://github.com/dotnet/aspnetcore/pull/39176/commits/d2a948097688737ef2aa8311d4392cfc0b20e5ae
Identity - https://github.com/dotnet/aspnetcore/pull/39176/commits/69ee9748284e70409501cbeddc05b5ee53e580b5
JSInterop - https://github.com/dotnet/aspnetcore/pull/39176/commits/0d9683b608c7851d61f72f92d96f5b220474e348
Localization - https://github.com/dotnet/aspnetcore/pull/39176/commits/f0757c922d307974f0c878da762cd2c95e372e25
Logging.AzureAppServices - https://github.com/dotnet/aspnetcore/pull/39176/commits/2030a4c7bac959fe11a438af7a80ba77d1337a0b
Middleware - https://github.com/dotnet/aspnetcore/pull/39176/commits/fecdbd24cc1e6b4b3336b48f40390a37a99b7d75
Mvc - https://github.com/dotnet/aspnetcore/pull/39176/commits/9e05b182fe27408cf59b4774e8c32f2f511bb509
ObjectPool - https://github.com/dotnet/aspnetcore/pull/39176/commits/f14f95258c4393bde63b3de510e9c698091dc250
Razor - https://github.com/dotnet/aspnetcore/pull/39176/commits/eb1da37b38e81ef0260349905b57db5b782ca932
Security - https://github.com/dotnet/aspnetcore/pull/39176/commits/952c66f97da6a9fbe058f132544aa365a02af102
Servers - https://github.com/dotnet/aspnetcore/pull/39176/commits/415a7732baba5027e862ca3e280548f6e2970da3
Testing - https://github.com/dotnet/aspnetcore/pull/39176/commits/2df5857dd64d2a0a3a9cd23417d6f306b070ee51

### CODE REVIEW

**Comment by pranavkm** [comment]
Could you turn enable this rule in the root editorconfig as part of this change: https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0005?

**Comment by ShreyasJejurkar** [comment]
Yes, I am already going to do that, am just waiting for all green tests!

**Comment by ShreyasJejurkar** [comment]
Hi @pranavkm I had to comment out the rule as of now because of some error that I was not able to resolve, so can you please fix some unwanted using with follow up commit and also uncomment rule in `.editorconfig` file!

**Comment by mkArtakMSFT** [comment]
Thank you for your PR, @ShreyasJejurkar.
@pranavkm I've assigned this to you for now. Feel free to reassign to others as needed. Thanks!

**Review by pranavkm — APPROVED** [review]

**Pull request merged**
