### PR TITLE
Try running Diagnostics.FunctionalTests in Helix

### PR DESCRIPTION
**Pull request by wtgodbe**
Seeing if https://github.com/dotnet/aspnetcore/issues/38819 is resolved

### CODE REVIEW

**Comment by wtgodbe** [comment]
Failures on attempt 3 were unrelated

**Comment by wtgodbe** [comment]
Alright, the tests have passed 6 times in a row, I'm satisfied. Undrafting

**Review by Tratcher — APPROVED** [review]

**Comment by HaoK** [comment]
Yay, glad this is finally working again

**Pull request merged**
