### PR TITLE
Update branding to 2.1.25

### PR DESCRIPTION
**Pull request by JunTaoLuo**

### CODE REVIEW

**Review by dougbu — APPROVED** [review]

**Comment by wtgodbe** [comment]
@JunTaoLuo Since branding already got done internally, it's probably best to just close this at this point

**Comment by JunTaoLuo** [comment]
FYI this probably won't be merged. But keeping open to investigate CI failures.

**Comment by JunTaoLuo** [comment]
This didn't recur during 2.1.26 so closing.

**Comment by JunTaoLuo** [comment]
Actually I'm still seeing failures in 2.1.26. I'll debug it separately.

**Pull request closed without merging**
