### PR TITLE
Update versions

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Review by pakrym — APPROVED** [review]

**Comment by pranavkm** [comment]
A bunch of Libuv tests fail when I try to get a new version of the shared fx.

```
[xUnit.net 00:01:50.47]     ConnectionClosedWhenBothRequestAndResponseExperienceBackPressure [FAIL]
  Failed   ConnectionClosedWhenBothRequestAndResponseExperienceBackPressure
  Error Message:
   System.TimeoutException : The operation at /_/src/Servers/Kestrel/shared/test/TaskTimeoutExtensions.cs:12 timed out after reaching the limit of 30000ms.
  Stack Trace:
     at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
     at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.ConnectionClosedWhenBothRequestAndResponseExperienceBackPressure() in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 728
  --- End of stack trace from previous location where exception was thrown ---
  Standard Output Messages:
   | [0.002s] TestLifetime Information: Starting test ConnectionClosedWhenBothRequestAndResponseExperienceBackPressure at 2019-03-05T01:13:45
   | [0.007s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
   | [0.008s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
   | [0.008s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Libuv.FunctionalTests, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
   | [0.008s] Microsoft.AspNetCore.Server.Kestrel Debug: TestServer is listening on port 51149
   | [0.009s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLL10UGEN1HE" started.
   | [0.009s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http:///  6553600
   | [0.011s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLL10UGEN1HE", Request id "0HLL10UGEN1HE:00000001": started reading request body.
   | [0.643s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLL10UGEN1HE" paused.
   | [30.024s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
   | [30.095s] Microsoft.AspNetCore.Server.Kestrel Error: Connection id "0HLL10UGEN1HE", Request id "0HLL10UGEN1HE:00000001": An unhandled exception was thrown by the application.
   | System.TimeoutException: The operation at /_/src/Servers/Kestrel/shared/test/TaskTimeoutExtensions.cs:12 timed out after reaching the limit of 30000ms.
   |    at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
   |    at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.<>c__DisplayClass11_0.<<ConnectionClosedWhenBothRequestAndResponseExperienceBackPressure>g__App|4>d.MoveNext() in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 700
   | --- End of stack trace from previous location where exception was thrown ---
   |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:line 576
   | [30.096s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 30088.0164ms 200 
   | [30.097s] Microsoft.AspNetCore.Server.Kestrel Error: Connection id "0HLL10UGEN1HE", Request id "0HLL10UGEN1HE:00000001": An unhandled exception was thrown by the application.
   | Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted by the application. ---> System.InvalidOperationException: Reading is already in progress.
   |    at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_AlreadyReading()
   |    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   |    at System.IO.Pipelines.Pipe.TryRead(ReadResult& result)
   |    at System.IO.Pipelines.Pipe.DefaultPipeReader.TryRead(ReadResult& result)
   |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.TryRead(ReadResult& readResult) in /_/src/Servers/Kestrel/Core/src/Internal/Http/Http1ContentLengthMessageBody.cs:line 113
   |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.OnConsumeAsync() in /_/src/Servers/Kestrel/Core/src/Internal/Http/Http1MessageBody.cs:line 41
   |    --- End of inner exception stack trace ---
   | [30.097s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLL10UGEN1HE", Request id "0HLL10UGEN1HE:00000001": done reading request body.
   | [30.097s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLL10UGEN1HE" disconnecting.
   | [30.098s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLL10UGEN1HE" sending FIN because: "The libuv transport's send loop completed gracefully."
   | [30.098s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLL10UGEN1HE" stopped.
   | [30.100s] TestLifetime Information: Finished test ConnectionClosedWhenBothRequestAndResponseExperienceBackPressure in 30.098767s
```

Did something with the `PipeReader` change that could have caused this? @Tratcher

**Comment by pranavkm** [comment]
@jkotalik \ @davidfowl

**Comment by jkotalik** [comment]
Looking into it. This was an expected break, but it may have a few more side effects than we thought.

**Comment by pakrym** [comment]
@pranavkm PlatformAbstraction library removal is expected (https://github.com/dotnet/core-setup/pull/5218). Can you please fix `PlatformManifestListsAllFiles` and `SharedFrameworkContainsExpectedFiles`?

**Comment by davidfowl** [comment]
Confirmed it's a bug with my pipelines change, working on a fix.

**Comment by pranavkm** [comment]
:shipit:

**Pull request merged**
