### PR TITLE
Correct typo in ProtectedPersonalDataAttribute.cs & PersonalDataAttribute.cs 

### PR DESCRIPTION
**Pull request by bretthoes**
# {PR title}

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

{Detail}

Fixes #{bug number} (in this specific format)

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
Thanks for the catch. I see that you have sent two PRs both fixing typos. Let's close one and combine both changes into this PR. Can you please do that?

**Comment by bretthoes** [comment]
Consolidated

**Comment by bretthoes** [comment]
@dotnet-policy-service agree default

**Comment by bretthoes** [comment]
@dotnet-policy-service agree

**Review by halter73 — APPROVED** [review]

**Comment by halter73** [comment]
Thanks @bretthoes

**Pull request merged**
