### PR TITLE
HTTP/2: Ignore additional RST_STREAM frames sent to stream

### LINKED ISSUE #32442: HTTP/2: Correctly handle receiving multiple RST_STREAM frames
https://github.com/grpc/grpc-java/issues/8142

tldr; Java gRPC client is sending two RST_STREAM frames for the same stream ID. Kestrel is killing the connection. This might not be correct.

Stream states section in the HTTP/2 spec: https://tools.ietf.org/html/rfc7540#section-5.1

When Kestrel receives the second RST_STREAM frame, it goes into a `closed` state.

>       An endpoint MUST NOT send frames other than PRIORITY on a closed
>       stream.  An endpoint that receives any frame other than PRIORITY
>       after receiving a RST_STREAM MUST treat that as a stream error
>       (Section 5.4.2) of type STREAM_CLOSED.  Similarly, an endpoint
>       that receives any frames after receiving a frame with the
>       END_STREAM flag set MUST treat that as a connection error
>       (Section 5.4.1) of type STREAM_CLOSED, unless the frame is
>       permitted as described below.

Kestrel should have a stream error rather than a connection error on the second RST_STREAM.

I'm not sure what a stream error would mean in this case as you're not allowed to send a RST_STREAM in response to a RST_STREAM - https://tools.ietf.org/html/rfc7540#section-5.4.2

>    An endpoint that detects a stream error sends a RST_STREAM frame
>    (Section 6.4) that contains the stream identifier of the stream where
>    the error occurred.  The RST_STREAM frame includes an error code that
>    indicates the type of error.

And

>    To avoid looping, an endpoint MUST NOT send a RST_STREAM in response
>    to a RST_STREAM frame.

I think Kestrel should just ignore additional RST_STREAM frames.

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/aspnetcore/issues/32442

### CODE REVIEW

**Review by halter73 — APPROVED** [review]

**Review by Tratcher — APPROVED** [review]

**Comment by ahjohannessen** [comment]
@JamesNK Any chance this is backported into 5.0.x series as a bugfix?

**Comment by JamesNK** [comment]
Is there a workaround for this issue in your app?

We judge whether to backport fixes based on a bunch of factors such as whether there is a workaround and how many people are encountering the problem.

I'd also like to figure out whether this is a bug in the Java gRPC client. I think the Java gRPC client is violating the HTTP/2 spec by double sending the RST_STREAM frame.

**Comment by ahjohannessen** [comment]
>Is there a workaround for this issue in your app?

No, sadly not. I have tried various things, but when just as I thought I fixed it then it pops up under different setup.

>I'd also like to figure out whether this is a bug in the Java gRPC client. I think the Java gRPC client is violating the HTTP/2 spec by double sending the RST_STREAM frame.

I think that is something @ejona86 is a better person to answer.

**Comment by jageall** [comment]
there does not seem to be a reasonable workaround on the server for this either.  Everything is internal and I am not seeing a sensible way to try and deal with it closer to the transport. The only possible option I can see is to fork aspnetcore and patch the .net5 version with this fix. I'd rather not be forced to do that unless I really have to. Are there any other alternatives I am missing?

**Pull request merged**
