### PR TITLE
Dash and Bash issue on Mint 17.2

### PR DESCRIPTION
**Pull request by lgtelles**
On Linux mint the dnvm.sh doesn't work on the user log in due to a Dash/Bash issue.

While the script uses bash, on cinnamon mint .profile executes the file using dash, causing several erros due to non-posix programming such as "[[" and loops using arrays.
The UI, then, crashes leaving the user unable to log in using X

If the user proceeds to remove the line appended on .profile and adds it on .bashrc (which uses bash instead of dash) the script runs without any glitch.

I've added the workaround in the .md file so the users can correct this

### CODE REVIEW

**Comment by glennc** [comment]
Hey @lgtelles. Should we not modify the dnvminstall.sh file so that it doesn't use bash_profile at all? This avoids this problem completely right?

cc @BrennanConroy

**Comment by lgtelles** [comment]
@glennc Then should we force that it uses .bashrc instead of .profile? And should we also override that when the $Profile returns it?

One alternative that would also work is to refactor dnvm/dnvm.sh to comply with the posix syntax.
I've taken a look and it seems a lot of work but it could be done



The main thing about the documentation upgrade is to help the people that are currently with that problem with no idea about what happened

**Comment by glennc** [comment]
Can we move this to the dnvm repo and discuss it there? Changes to DNVM happen in aspnet/dnvm and then get pushed to here as part of a build step.

**Comment by glennc** [comment]
Didn't mean to close :). I am ok with this change if there is no good way to make it not break at all. If we can fix this then we should.

**Comment by lgtelles** [comment]
Removed the .profile reference in dnvminstall.sh

**Comment by Eilon** [comment]
Closing because this is no longer needed. Thanks!

**Pull request closed without merging**
