### PR TITLE
Use MIT license for Installer EULA

### LINKED ISSUE #40835: Windows runtime installer contains .NET Framework EULA
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Windows installer of .NET Framework 6.0.1 64-bit (Hosting bundle) (https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.1-windows-hosting-bundle-installer) installs Microsoft .NET EULA under "C:\Program Files\dotnet\shared\eula.rtf".
eula

It is this file that seems to be included: src/Installers/Windows/files/eula.rtf (https://github.com/dotnet/aspnetcore/blob/429c578753386ec0b762632d27de5f6ed68a5365/src/Installers/Windows/files/eula.rtf)

### Expected Behavior

The EULA should not be there as .NET Framework is released under MIT License (or it should be clearly stated what files are covered by the EULA).

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

_No response_

### Anything else?

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### PR DESCRIPTION
**Pull request by wtgodbe**
Fixes https://github.com/dotnet/aspnetcore/issues/40835

### CODE REVIEW

**Comment by Pilchie** [comment]
Seems fine to me.

**Comment by joeloff** [comment]
That looks like a plain text fail and not RTF. Does it load properly?

**Comment by dougbu** [comment]
> That looks like a plain text fail and not RTF. Does it load properly?

Whether or not the file is plaintext, I suggest renaming the file to `eula.txt` and updating its 6 mentions in 2 WXS files.

**Comment by dougbu** [comment]
/btw is there a non-GitHub conversation about this❔ I'd like to hear any thoughts @ChrisSfanos has.

**Comment by wtgodbe** [comment]
> /btw is there a non-GitHub conversation about this❔ I'd like to hear any thoughts @ChrisSfanos has.

Yep, just forwarded you the email thread

**Comment by wtgodbe** [comment]
Test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1729658&view=results

**Review by dougbu — APPROVED** [review]

**Comment by wtgodbe** [comment]
Test hosting bundle works as expected

**Pull request merged**
