### PR TITLE
Update SDK, Unquarantine tests

### PR DESCRIPTION
**Pull request by wtgodbe**
Should be able to unquar these now that https://github.com/dotnet/installer/pull/13376 is in.

https://github.com/dotnet/aspnetcore/issues/40642

### CODE REVIEW

**Review by TanayParikh — APPROVED** [review]

**Comment by dougbu** [comment]
I wonder about the process here. #40642 isn't marked as `test-fixed` and we normally wait for 30 days after fixing something before un-quarantining. Why the exception in this case❔

**Comment by TanayParikh** [comment]
> Why the exception in this case❔

The tests had to be quarantined due to breaking changes on runtime, it wasn't a flakiness issue (which is why we originally established the 30 day guidance). @wtgodbe mentioned https://github.com/dotnet/installer/pull/13376 should resolve the issue. So as long as the CI passes now, I think this should be safe to consume.

**Comment by wtgodbe** [comment]
> D:\a\_work\1\s\src\Caching\SqlServer\src\Microsoft.Extensions.Caching.SqlServer.csproj : error : Version 7.0.100-preview.4.22174.1 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

Maybe time to update the `VS2022` images - though @dougbu any ideas why this is only happening in code check?

**Comment by dougbu** [comment]
> Maybe time to update the `VS2022` images - though @dougbu any ideas why this is only happening in code check?

Nah

The problem here is the usual desktop `msbuild` versus `dotnet msbuild` incompatibility. eng\scripts\GenerateProjectList.ps1 is unique in that it invokes eng/common/msbuild.ps1. Change GenerateProjectList.ps1 to pass `-msbuildEngine dotnet` and all will be well.

**Review by dougbu — APPROVED** [review]

**Pull request merged**
