### PR TITLE
Move Kestrel.Core.Tests to their own test group

### PR DESCRIPTION
**Pull request by Tratcher**
https://github.com/aspnet/AspNetCore-Internal/issues/1699
Experimenting to see if this is the same issue we've been having in 2.1.

Compare to the baseline build https://dnceng.visualstudio.com/public/_build/results?buildId=77668

### CODE REVIEW

**Comment by Tratcher** [comment]
Success! There are unrelated failures but the Kestrel tests are fixed.

@pakrym that IIS chunked test you disabled in master is failing in 2.2.

**Review by halter73 — APPROVED** [review]

**Comment by halter73** [comment]
@natemcmaster Is there anyway to know for sure whether the other test projects are running against the updated Kestrel.Core assembly?

**Comment by natemcmaster** [comment]
> Is there a way to confirm the other test projects are running against the updated Kestrel.Core assembly?

Build locally and check the Kestrel.Core.dll file to see if it matches one from a package or the local build. If it's from a package, add a direct `<Reference>` item to Kestrel.Core into the test .csproj file.

**Comment by halter73** [comment]
Do we have to manually do that for every test project in the repo that might depend on Kestrel.Core?

**Comment by natemcmaster** [comment]
Yes.

**Pull request merged**
