### PR TITLE
Move connection id creation into the transport.

### PR DESCRIPTION
**Pull request by davidfowl**
This became the obvious thing to do once I started looking at the client side of things https://github.com/aspnet/AspNetCore/pull/11672

### CODE REVIEW

**Comment by davidfowl** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=243015

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2489

**Comment by anurse** [comment]
Gotta land this today for p7.

**Comment by davidfowl** [comment]
@Tratcher @halter73 @jkotalik gimme an approve

**Comment by jkotalik** [comment]
This PR was made 4 hours ago. Give us a minute.

**Review by jkotalik — APPROVED** [review]

**Comment by anurse** [comment]
Overhead shot of a number of people putting hands on top of each other in a "Go Team!" gesture

**Pull request merged**
