### PR TITLE
 Remove ANCMV1 from everywhere

### PR DESCRIPTION
**Pull request by pakrym**

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]

**Review by jkotalik — APPROVED** [review]

**Comment by jkotalik** [comment]
Can you also remove ANCM here? https://github.com/aspnet/AspNetCore/blob/a8f1b034d8b8c4c0fc341f2a4e39fa54af28294c/src/Servers/IIS/IIS/test/IIS.BackwardsCompatibility.FunctionalTests/IIS.BackwardsCompatibility.FunctionalTests.csproj#L27

**Comment by pakrym** [comment]
Good point.

**Comment by pakrym** [comment]
@Tratcher FYI, this is a much larger change now.

**Comment by Tratcher** [comment]
Was there any plan to keep back compat tests? Or do we rely on the patch branches for that?

**Comment by pakrym** [comment]
Back compat of what with what?

**Comment by pakrym** [comment]
Talked offline, back compat in @Tratcher question is unrelated to this.

**Pull request merged**
