### PR TITLE
[Blazor] Switch to rollup for bundling

### PR DESCRIPTION
**Pull request by javiercn**
Looking at modernizing our JS infrastructure I've compared a few bundlers. Namely:
* Webpack: What we've been using, has fallen out of favor and is lacking important features like producing ES6 bundlers (it's technically possible with plugins)
* Vite: The community champion, its stable and builds on top of Rollup and Esbuild, but it doesn't work well for our library setup (requires more work) and requires type checking typescript separately.
* Parcel: Builds on top of rollup and mostly offers a simpler configuration, our setup is complex enough that we don't benefit from this.
* Esbuild: This is becoming a standard used by other tools, but its too experimental for now, produces bigger bundles than rollup and doesn't support type checking (needs to be done separately)
* Rspack: Same as esbuild, aims to be backwards compatible with webpack config, but is even more experimental than esbuilds and also lacks type checking.

Rollup is the most mature bundler that supports our use cases (current and future) and there is a clear path in the future as vite is working on its own rust based version of rollup 'rolldown'.

This is the initial work to replace the old version of webpack with an up to date bundler implementation that will allow us to generate not only commonjs bundles but also esm bundles. The PR also removes many old and stale dependencies that we weren't using. The bundle sizes are reduces between 0-2% depending on the bundle, which is likely negligible, but it's less than nothing.

Contributes to https://github.com/dotnet/aspnetcore/issues/52819

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
This sounds great to me! Switching over to rollup totally makes sense as we modernize and consider more modular output. I also investigated current JS bundler options in December for a different project and also concluded that Rollup was the most practical choice for that, so can relate to all the reasoning you gave when comparing the options.

My only question is whether we know for sure that the updated minification mechanism will preserve the same APIs as we had before. We do have some E2E coverage to exercise some of the public APIs, but do you know if (in theory) the newer minification options might be mangling more of the pubternal JS API names than the older one did?

**Comment by javiercn** [comment]
> This sounds great to me! Switching over to rollup totally makes sense as we modernize and consider more modular output. I also investigated current JS bundler options in December for a different project and also concluded that Rollup was the most practical choice for that, so can relate to all the reasoning you gave when comparing the options.

> My only question is whether we know for sure that the updated minification mechanism will preserve the same APIs as we had before. We do have some E2E coverage to exercise some of the public APIs, but do you know if (in theory) the newer minification options might be mangling more of the pubternal JS API names than the older one did?

I don't think this will be mangling more stuff, but I'll take a look from the JS side of things

**Comment by javiercn** [comment]
@SteveSandersonMS API looks fine

image

**Comment by SteveSandersonMS** [comment]
OK great. If we discover anything did get moved (e.g., I see it's configured with `keep_classnames: false`) we can always tweak the config later. But maybe it's already exactly correct.

**Review by SteveSandersonMS — APPROVED** [review]

**Pull request merged**
