### PR TITLE
Update README for packages that moved to Azure SDK

### PR DESCRIPTION
**Pull request by BrennanConroy**

### CODE REVIEW

**Review by Pilchie — APPROVED** [review]
Is there an equivalent in extensions for Microsoft.Extensions.Configuration.AzureKeyVault?

**Comment by BrennanConroy** [comment]
I will make a PR there, just wanted to see if there was any feedback on the format first.

**Comment by BrennanConroy** [comment]
Tell mode I'm assuming?

@JunTaoLuo I need to update the patch config don't I?

**Comment by BrennanConroy** [comment]
We also need a new milestone and branding?

**Comment by Pilchie** [comment]
Yes, let's take tell-mode.

**Review by JunTaoLuo — APPROVED** [review]

**Pull request merged**
