### PR TITLE
Add pointerenter/leave to nonBubblingEvents

### LINKED ISSUE #43129: [Blazor] the `pointerenter` and `pointerleave` events not getting fired
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Out of all pointer events, the `pointerenter` and `pointerleave` events are not getting fired, in both Blazor Server and Blazor WASM.
I need the `leave` event since its non-bubbling nature is required for my use case. the `out` event does not help since its bubbling feature breaks my app. the only solution that I can think of, is fallback to javascript.

### Expected Behavior

like the other pointer events, the enter and leave events should get fired correctly.

### Steps To Reproduce

consider this sample:

```razor
<div @onpointerleave=@(Log("pointer leave"))
     @onpointerenter=@(Log("pointer enter"))
     @onpointermove=@(Log("pointer move"))
     @onpointerover=@(Log("pointer over"))
     @onpointerout=@(Log("pointer out"))
     @onpointercancel=@(Log("pointer cancel"))
     @onpointerdown=@(Log("pointer down"))
     @onpointerup=@(Log("pointer up"))>
    <h1>Hello, world!</h1>
</div>

@code {
    [Inject] private IJSRuntime _js { get; set; } = default!;

    private Func<Task> Log(string value) => async Task () => await _js.InvokeVoidAsync("console.log", value);
}
```

if you check the console, you can see that only the `pointer leave` and `pointer enter` phrases never get printed out.

### Exceptions (if any)

_No response_

### .NET Version

6.0.302

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by zHaytam**
(This is @SteveSandersonMS hijacking the PR description to add our servicing template so it can be considered for .NET 7 RC2)

# Add pointerenter/leave to nonBubblingEvents

Blazor supports all pointer events except for `pointerenter` and `pointerleave`. This adds support for those too.

## Description

The only reason why `pointerenter` and `pointerleave` don't already work is that they are nonbubbling events, and we haven't included them in the list of nonbubbling events. Blazor needs to know about which events are nonbubbling because the way they are captured and dispatched into .NET is slightly different than for bubbling events.

This PR just adds those events to the nonbubbling list so they start working.

Fixes #43129

## Customer Impact

Without this fix, developers can't use the `pointerenter` and `pointerleave` events. They have to use the older `mouseover` and `mouseout` events which don't support such a wide range of devices and in many cases don't have the desired modern semantics for overlapping elements.

## Regression?

- [ ] Yes
- [x] No

[If yes, specify the version the behavior has regressed from]

## Risk

- [ ] High
- [ ] Medium
- [x] Low

Low because it's just adding two new event names to the list of nonbubbling events. It should only affect the behavior for those two events, which was already broken in the past and now should stop being broken. No other behaviors/events should be affected.

## Verification

- [x] Manual (required)
- [x] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

----

**Original PR description by @zHaytam:**

The events `pointerenter` and `pointerleave` are the only two pointer events that don't work. This is because they don't bubble and as such, we need to set `useCapture` to `true`, which is done when `nonBubblingEvents` contains the event. Basically, they need to behave the same way as `mouseenter` and `mouseleave`.

Fixes #43129

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
Thanks for this, @zHaytam!

I think we'd be happy to accept this PR if it also contained the relevant end-to-end (E2E) test cases for the new functionality. You could add E2E tests for `pointerenter` and `pointerleave` following exactly the same pattern that is used for `mouseenter` and `mouseleave` tests in `MouseEventComponent.razor` and `EventTest.cs`.

Would you be interested in doing that?

**Comment by zHaytam** [comment]
Yes, I can do that. I'll have that ready as soon as I can.

**Comment by zHaytam** [comment]
I have added the test, but for some reason I can't run it on my machine:
```bash
../../../../../node_modules/@types/vfile/index.d.ts(11,31): error TS2792: Cannot find module 'vfile-message'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' opti
on? [D:\Projects\aspnetcore\src\JSInterop\Microsoft.JSInterop.JS\src\Microsoft.JSInterop.JS.npmproj]
../../../../../node_modules/@types/webpack-sources/index.d.ts(10,62): error TS2792: Cannot find module 'source-map'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'path
s' option? [D:\Projects\aspnetcore\src\JSInterop\Microsoft.JSInterop.JS\src\Microsoft.JSInterop.JS.npmproj]
D:\Projects\aspnetcore\eng\targets\Npm.Common.targets(82,5): error : Command failed with exit code 1. [D:\Projects\aspnetcore\src\JSInterop\Microsoft.JSInterop.JS\src\Microsoft.JSInterop.JS.npmproj]
```

**Comment by SteveSandersonMS** [comment]
@Pilchie Can we consider this one for RC2?

**Review by SteveSandersonMS — APPROVED** [review]

**Comment by Pilchie** [comment]
Approved for .NET 7 RC2.  Thanks for the contribution @zHaytam!

**Review by SteveSandersonMS — CHANGES_REQUESTED** [review]
Actually I need to make sure `blazor.server.js` and `blazor.webview.js` are updated before merging this.

@zHaytam No further action is needed from you - I'll sort this out. Thanks for the contribution!

**Comment by zHaytam** [comment]
I'm glad this got approved but did the unit tests run? I still can't manage to run them locally so I would hate to contribute something not working...

**Comment by SteveSandersonMS** [comment]
@zHaytam Yes, the CI system did run your new `PointerEnterAndPointerLeave_CanTrigger` test, and it passes on both WebAssembly and Server. You can search by test name at https://dev.azure.com/dnceng-public/public/_build/results?buildId=1245&view=ms.vss-test-web.build-test-results-tab after changing the filter to include "passed" tests.

**Review by SteveSandersonMS — APPROVED** [review]

**Comment by SteveSandersonMS** [comment]
@Pilchie @mkArtakMSFT Could either of you merge this, assuming the build passes and the most recent commit in this PR is still 5fc4102? That's the commit I've approved. The change was approved for RC2 by Kevin above.

I don't have permission to merge to `release/7.0` but if I'm getting my info from the latest email thread, that's where RC2 changes should go now.

**Comment by Pilchie** [comment]
Done - this is the right branch, it just has our default release branch protection rules.

**Pull request merged**
