### PR TITLE
Remove en-us locale from links in Blazor server-side project template

### PR DESCRIPTION
**Pull request by scottaddie**
Remove the "en-us" locale from the layout file used in the auth and no auth versions of the Blazor server-side project template.

### CODE REVIEW

**Review by ryanbrandenburg — APPROVED** [review]

**Comment by ryanbrandenburg** [comment]
Code looks fine but you seem to have run into some transient test failures. You can force a retry by rebasing your branch or otherwise introducing new commits.

**Comment by scottaddie** [comment]
@ryanbrandenburg Is `release/3.1` still the correct branch to target now that 3.1 has shipped?

**Comment by ryanbrandenburg** [comment]
That seems to be correct yeah.

**Comment by scottaddie** [comment]
@ryanbrandenburg Looks like we're good to go now.

**Comment by ryanbrandenburg** [comment]
Thanks @scottaddie!

**Pull request merged**
