### PR TITLE
Fixup site extensions 3.1 versions

### PR DESCRIPTION
**Pull request by JunTaoLuo**
This fixes up the version update made in https://github.com/dotnet/aspnetcore/pull/31773

### CODE REVIEW

**Review by pranavkm — APPROVED** [review]

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
Set `auto-merge` to get this in ASAP. But, @wtgodbe and @JunTaoLuo feel free to merge immediately if starting ASP.NET builds is urgent. The PR build won't validate the change. I'm just not sure how pressed for time we are.

**Comment by wtgodbe** [comment]
This is against `main`, so no rush

**Comment by dougbu** [comment]
Oh, I assumed this was against `release/5.0`. Does this mean we aren't creating up-to-date site extension bundles for `5.0` ❔

We normally do the same thing in that branch though our issue template only mentions "the main copy". IIRC @BrennanConroy suggested doing this in both branches was helpful.

**Comment by wtgodbe** [comment]
Looks like I missed updating the 5.0 version: https://github.com/dotnet/aspnetcore/blob/415693c9a3cf3ddc7bf1d5d4c7524408cec1de44/eng/Versions.props#L241

I can create that PR now

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/pull/31811

**Comment by JunTaoLuo** [comment]
Can you also update the doc so we remember to update in both branches?

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore-internal/pull/3809

**Pull request merged**
