### PR TITLE
Run template tests on helix arm

### LINKED ISSUE #25835: Fix shared framework on Helix
Found in https://github.com/dotnet/aspnetcore/pull/25587

Windows shared runtime is installed in Linux and OSX Helix queues.

Need to:
1. Install shared runtime for the correct platform in Helix
2. Fix tests that assume the Windows runtime is always installed.

### PR DESCRIPTION
**Pull request by JunTaoLuo**
Fixes https://github.com/dotnet/aspnetcore/issues/25835

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
Ah I need to actually test the full helix matrix to see if it works on arm.

**Comment by JunTaoLuo** [comment]
Actually does it make sense to enable these tests? The reason I ask is because the environment that would be enabled isn't quite the same as what the customers would use. 

This is because we are disabling cross-gen and end up using non-platform specific shared framework that was built on Windows-x64. This is different from what we actually release, but for tests like gRPC interop, this difference doesn't affect the validity of the test. But for the other helix  tests, this might not be what we want and issues in what we release for arm might not show up in the tests.

Thoughts @HaoK ?

**Comment by dougbu** [comment]
@JunTaoLuo could you clarify your comments❔ I'd like to see this go in. Disabling `crossgen` means the shared Fx bit essentially act like our packages --  they're applicable everywhere. There's nothing special about ARM in this. Would be good to close #25835 and worry about using shared Fx bits `crossgen`ed for the individual platforms when we move to testing against SDKs.

**Comment by JunTaoLuo** [comment]
What I thought was that we treat our template tests as verification of E2E scenarios. I'm concerned that potentially we would be masking issues on ARM if we use an environment that's different from what our customers use. But now I think about it, I suppose running these as is is better than not running them.

**Review by wtgodbe — APPROVED** [review]

**Pull request merged**
