### PR TITLE
Fix cert auth sample

### PR DESCRIPTION
**Pull request by HaoK**
Update Program.cs since app wasn't working

### CODE REVIEW

**Comment by Tratcher** [comment]
What was the problem? Your changes don't appear to have have any functional difference.

**Comment by HaoK** [comment]
The app wouldn't f5 run in the soln before, while with these change it does 🤷

**Review by Tratcher — APPROVED** [review]
Hmm, it might be the language version not allowing `Task Main`?

**Comment by HaoK** [comment]
That sounds familiar, I didn't look at it too carefully since I noticed the other sample was updated to use this startup style which worked

**Pull request merged**
