### PR TITLE
[SPA] Updates outdated npm dependencies

### LINKED ISSUE #29129: Update project dependencies
Time to update npm package dependencies that we have in our project templates.

### PR DESCRIPTION
**Pull request by javiercn**
## Description

Updates outdated dependencies for the Angular, React and React redux templates.

## Customer Impact

Customers creating new projects get obsolete versions of some javascript dependencies and need to update them manually.

## Regression?
- [ ] Yes
- [X] No

[If yes, specify the version the behavior has regressed from]

## Risk
- [ ] High
- [ ] Medium
- [X] Low

The changes only update dependencies and have been tested manually.

## Verification
- [X] Manual (required)
- [ ] Automated

## Packaging changes reviewed?
- [ ] Yes
- [ ] No
- [X] N/A

Addresses #29129

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
@javiercn, please use the template from: https://aka.ms/aspnet/servicing/template

**Comment by javiercn** [comment]
@mkArtakMSFT done

**Comment by javiercn** [comment]
@mkArtakMSFT this is good to go as soon as it's approved by tactics.

Please squash the commits into a single commit and just add the following message:

```
Updates npm dependencies for the angular, react and react-redux project templates
```

**Review by mkArtakMSFT — APPROVED** [review]
Thanks @javiercn!

**Comment by Pilchie** [comment]
Looks like this was merged before the branch opened. @dotnet/aspnet-build is that going to cause a problem?

**Pull request merged**
