### PR TITLE
[2.1] Enable control flow guard for IIS dlls

### PR DESCRIPTION
**Pull request by jkotalik**
Backporting https://github.com/dotnet/aspnetcore/pull/22480 to 2.1.

I'm not certain if this should be ask mode or tell mode for this change. @blowdart @Pilchie

### CODE REVIEW

**Review by dougbu — APPROVED** [review]

**Comment by Pilchie** [comment]
This is approved for July servicing, but the branch isn't open yet.

**Comment by jkotalik** [comment]
@dotnet/aspnet-build please merge 😄

**Comment by BrennanConroy** [comment]
Do we need to add this to the patch config?

**Comment by jkotalik** [comment]
No, these changes only affect the ANCM msis and aren't part of any packages.

**Pull request merged**
