### PR TITLE
Fix #10066 remove the namespace Microsoft.AspNetCore.Http.Endpoints

### LINKED ISSUE #10066: We should remove the namespace Microsoft.AspNetCore.Http.Endpoints
The only thing in this namespace is the extension methods `GetEndpoint()` and `SetEndpoint()`. `Endpoint` is defined in `Microsoft.AspNetCore.Http`. We should move these extension methods there too.

### PR DESCRIPTION
**Pull request by rynowak**
Fixes: #10066

### CODE REVIEW

**Review by analogrelay — APPROVED** [review]

**Comment by rynowak** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=184433&view=logs

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2481

**Review by davidfowl — APPROVED** [review]
monorepo FTFW

**Comment by rynowak** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=184542

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2498

**Pull request merged**
