### PR TITLE
Fix file headers in src/SignalR

### PR DESCRIPTION
**Pull request by Youssef1313**
Part of https://github.com/dotnet/aspnetcore/issues/18873

### CODE REVIEW

**Review by BrennanConroy — COMMENTED** [review]
Looks good!

Could you also take a look at the Crankier folder? Looks like it got missed.
https://github.com/dotnet/aspnetcore/tree/main/src/SignalR/perf/benchmarkapps/Crankier

**Comment by mkArtakMSFT** [comment]
Thanks for your PR.

Unfortunately, we can't take this PR as it's related to the licensing comments. These are things we're working on already so we'll have to close this.

Thanks for your effort.

**Comment by Youssef1313** [comment]
> Looks good!
> 
> Could you also take a look at the Crankier folder? Looks like it got missed.
> https://github.com/dotnet/aspnetcore/tree/main/src/SignalR/perf/benchmarkapps/Crankier

Going to take a look why/how it was missed. This was literally a FixAll application from the command line.

**Comment by Youssef1313** [comment]
> Thanks for your PR.
> 
> Unfortunately, we can't take this PR as it's related to the licensing comments. These are things we're working on already so we'll have to close this.
> 
> Thanks for your effort.

@mkArtakMSFT Please see the discussion in https://github.com/dotnet/aspnetcore/pull/30132

**Comment by Youssef1313** [comment]
> Looks good!
> 
> Could you also take a look at the Crankier folder? Looks like it got missed.
> https://github.com/dotnet/aspnetcore/tree/main/src/SignalR/perf/benchmarkapps/Crankier

@BrennanConroy It was missed because it doesn't exist in `SignalR.slnf` nor in `AspNetCore.sln`.

**Pull request closed without merging**
