### PR TITLE
Fix API baseline check when building site extensions

### PR DESCRIPTION
**Pull request by JunTaoLuo**
Try to fix 5.0 builds.

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
Tested in the PR build to ensure the fix is sufficient.

Not sure what the value is in including API files for the HostingStartup project. I think it would make more sense to disable the check instead. But given that the API baseline files are present, I've chosen to include the files for the build. Note that currently release/5.0 is blocked on this.

**Comment by JunTaoLuo** [comment]
I'm going to merge this now to fix the build, but I'll address feedback separately if needed.

**Comment by JunTaoLuo** [comment]
Turns out I can't force merge. I guess I'll wait for review.

**Comment by dougbu** [comment]
@JunTaoLuo this will work but you're right API baselines for tools aren't useful. Since this project doesn't follow the usual conventions, I recommend removing the PublicApi.*.txt files then adding the following to HostingStartup.csproj
``` msbuild
<!-- No need to track public APIs of this tool. -->
<AddPublicApiAnalyzers>false</AddPublicApiAnalyzers>
```
That matches what I did for other tools that don't have `Tools` in their paths.

**Review by dougbu — APPROVED** [review]
If you want to save time and go with this approach, :ok: Please follow up with a correction afterward in that case.

**Comment by JunTaoLuo** [comment]
I'll disable the check

**Review by dougbu — COMMENTED** [review]
Thanks @JunTaoLuo❕ Please revert your ci.yml change before merging.

Let's also remember to discuss the annoyance of PR validation not building the site extensions in Teams w/ our leads on Monday or at the meeting on Thursday.

**Comment by dougbu** [comment]
Oops I was looking at an old view of the PR. The src/SiteExtensions/Sdk/SiteExtension.targets change should be reverted in release/5.0 because it's just confusing.

**Pull request merged**
