### PR TITLE
Don't fail shutdown-does-not-crash test if merely ungraceful

### PR DESCRIPTION
**Pull request by halter73**
Fixes https://github.com/aspnet/AspNetCore-Internal/issues/2101

### CODE REVIEW

**Review by analogrelay — APPROVED** [review]

**Comment by halter73** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=136722

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

I've triaged the above build.

**Comment by halter73** [comment]
@anurse this is good to go.

**Comment by anurse** [comment]
2.2 branch isn't open yet, we should wait for the branding change.

**Comment by anurse** [comment]
Branch is now open, please merge ASAP.

**Comment by halter73** [comment]
Yes, please do 😉

**Pull request merged**
