### PR TITLE
Delete `StackTraceHelper`  code that won't fire

### PR DESCRIPTION
**Pull request by hueifeng**
These changes can be clearly seen that the corresponding processing has been done above the code block, so it will not be executed in every deleted code block.

### CODE REVIEW

**Comment by pranavkm** [comment]
Build errors on this one. If you're eliminating nulls, could you annotate this file with `#nullable enable`? This should give us more confidence that there aren't other nullability issues lurking here.

**Comment by hueifeng** [comment]
@pranavkm  I think it is ok, do I need to modify this file to add `#nullable enable`? 
Or do I need to modify our library to be empty `<Nullable>enable</Nullable>`?

**Comment by pranavkm** [comment]
Just the one file since it's shared.

**Comment by hueifeng** [comment]
@padmasrid  I submitted the changes.

**Review by mkArtakMSFT — APPROVED** [review]

**Pull request merged**
