### PR TITLE
Update SDK to 8.0.100-rc.1.23374.2

### PR DESCRIPTION
**Pull request by MackinnonBuck**

### CODE REVIEW

**Comment by MackinnonBuck** [comment]
With this SDK update, we're seeing:

```
The PrivateSdkAssemblies ItemGroup is required for _ComputeAssembliesToCompileToNative
```

Here's an [example](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342279&view=logs&j=6c33d704-163a-5170-38fa-caa7bc99f17c&t=4a2ac175-72f0-54eb-c8b6-eb1e5d86c7d5&l=4381).

@ivanpovazan do you know what might have caused this?

**Comment by MackinnonBuck** [comment]
Also, the macOS runs are failing on restore, and that's happening in the efcore SDK update too. We can see if that gets resolved in the next SDK build.

**Comment by ivanpovazan** [comment]
Hi @MackinnonBuck, I am not sure why you started experiencing this issue by bumping the SDK version.
The reason why the error message appears:
> ```
> The PrivateSdkAssemblies ItemGroup is required for _ComputeAssembliesToCompileToNative
> ```
is usually due to `ResolvedILCompilerPack` not being resolved properly during `ResolveFrameworkReferences` build target which should resolve the package directory and set `PackageDirectory` metadata on this item, which is later used in NativeAOT build integration targets to point to the sdk assemblies.

Why the package directory does not get resolved, I cannot tell for sure, but I would assume there is a problem with NuGet restore and/or version mismatch of ILCompiler packs. 

Hope this helps

**Comment by wtgodbe** [comment]
@sbomer do you know of anything that might have changed related to @ivanpovazan's comment above?

**Comment by RussKie** [comment]
@sbomer assigning to you for now.

**Comment by wtgodbe** [comment]
I think we're blocked on getting an SDK with https://github.com/dotnet/roslyn/pull/69010

**Review by wtgodbe — APPROVED** [review]

**Comment by wtgodbe** [comment]
That did the trick

**Comment by eerhardt** [comment]
Blazor WASM project templates tests are failing because of https://github.com/dotnet/sdk/issues/34135. Need to wait for an SDK with the fix.

**Comment by amcasey** [comment]
> Blazor WASM project templates tests are failing because of [dotnet/sdk#34135](https://github.com/dotnet/sdk/issues/34135). Need to wait for an SDK with the fix.

https://github.com/dotnet/sdk/issues/34135 seems to cite https://github.com/dotnet/runtime/issues/89273 as the problem and [this comment](https://github.com/dotnet/runtime/issues/89273#issuecomment-1644699334) seems to say that https://github.com/dotnet/sdk/pull/34142 was a workaround.  So I think we're waiting for https://github.com/dotnet/sdk/pull/34142?  Is that right, @eerhardt?

**Comment by javiercn** [comment]
@eerhardt this seems to be still stuck in the config source generator

**Comment by eerhardt** [comment]
> @eerhardt this seems to be still stuck in the config source generator

We are still waiting on https://github.com/dotnet/sdk/pull/34220 to be available in an official SDK build. I pushed the latest SDK from dotnet/installer, but it doesn't appear to have this fix.

**Comment by javiercn** [comment]
Still stuck `error SYSLIB1104: Binding logic was not generated for a binder call. Unsupported input patterns include generic calls and passing boxed objects. [/private/tmp/helix/working/C0AC0A29/w/B0A309A6/e/Templates/BaseFolder/AspNet.ifxssxpdts2s/AspNet.ifxssxpdts2s.csproj`

**Comment by eerhardt** [comment]
@javiercn - it looks like there are additional failures with the new SDK. Can you take a look?

**Comment by eerhardt** [comment]
> Still stuck `error SYSLIB1104: Binding logic was not generated for a binder call. Unsupported input patterns include generic calls and passing boxed objects. [/private/tmp/helix/working/C0AC0A29/w/B0A309A6/e/Templates/BaseFolder/AspNet.ifxssxpdts2s/AspNet.ifxssxpdts2s.csproj`

I've updated to the latest SDK which now has the fix. Let me know if you still see failures in this area.

**Pull request merged**
