### PR TITLE
[release/5.0] Rebrand to 5.0.3

### PR DESCRIPTION
**Pull request by dougbu**
- merge from internal/internal/release/5.0
- rebrand to 5.0.3
- update site extensions versions from 3.1.11 release
- update baselines to reflect 5.0.2 release

Part of dotnet/aspnetcore#29223

### CODE REVIEW

**Review by BrennanConroy — APPROVED** [review]
Approved for the parts I'm familiar with

**Review by wtgodbe — APPROVED** [review]

**Comment by dougbu** [comment]
@wtgodbe has the transport feed been updated yet❔ Getting errors like `Microsoft.NETCore.BrowserDebugHost.Transport 5.0.2-servicing.20611.20 was not found`.

**Comment by wtgodbe** [comment]
> @wtgodbe has the transport feed been updated yet?

Still in progress. My work machine got turned off so I have to do it from home, which is going very slowly over my internet connection

**Review by mmitche — APPROVED** [review]
LGTM make sure to a merge commit

**Pull request merged**
