### PR TITLE
Remove extra `git submodule` commands

### PR DESCRIPTION
**Pull request by dougbu**
- all work now done in "Checkout dotnet/aspnetcore" step
- reconfigured pipeline based on https://github.com/dotnet/aspnetcore/pull/22002#issuecomment-631318377

### CODE REVIEW

**Comment by dougbu** [comment]
Run of affected pipeline: https://dev.azure.com/dnceng/public/_build/results?buildId=658075

**Comment by dougbu** [comment]
Thanks @HaoK for finding the hidden pipeline configuration❕

**Review by HaoK — APPROVED** [review]
Yay much nicer!

**Pull request merged**
