### PR TITLE
Cleaning up AzDO Test Run Names

### PR DESCRIPTION
**Pull request by BrennanConroy**
Stealing from https://github.com/dotnet/aspnetcore/pull/19575

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Thoughts and comments?
image
and
image

Ignore the "-net" for the bottom ones, they'll be "-xunit" in the next build

**Comment by jkotalik** [comment]
What does trx stand for?

**Comment by Pilchie** [comment]
It's the vstest test result format.  "Test Result Xml" I think.

**Review by Pilchie — APPROVED** [review]

**Review by dougbu — APPROVED** [review]
I like it. Minor suggestion would be to burn the `$(BuildConfiguration)` part with fire. We only build `Release` in this repo.

**Comment by BrennanConroy** [comment]
We might one day run Debug! Like actually, https://github.com/dotnet/aspnetcore/issues/11632

**Pull request merged**
