### PR TITLE
[Design]LibMan

### PR DESCRIPTION
**Pull request by ryanbrandenburg**
Moved from https://github.com/aspnet/Templating/pull/814.

### CODE REVIEW

**Comment by natemcmaster** [comment]
It looks like this PR has gone stale. @ryanbrandenburg who should be assigned to review?

**Comment by ryanbrandenburg** [comment]
We shouldn't do this until the Puppeteer PR goes in because it will give us a much better way to confirm that we don't have any missing resources.

**Comment by natemcmaster** [comment]
Removing myself as a reviewer. GitHub added me automatically, but I don't know enough to validate if this change is correct or not.

cc @mkArtakMSFT

**Comment by ryanbrandenburg** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=124543&view=logs

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

I've triaged the above build.

**Comment by dougbu** [comment]
@ryanbrandenburg is this a draft PR? And, what is the issue it's addressing?

**Comment by ryanbrandenburg** [comment]
Yes it's a draft PR, the issue it addresses is https://github.com/aspnet/AspNetCore/issues/5415.

**Comment by ryanbrandenburg** [comment]
@aspnet-hello triage https://dnceng.visualstudio.com/public/_build/results?buildId=145222&view=results

The above is a test of RaaS functionality, please ignore it.

**Comment by BrennanConroy** [comment]
Please remove all those files you didn't mean to add.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg we should probably close this and reopen, when we'll get to it.

**Pull request closed without merging**
