### PR TITLE
Allow user specific PasswordValidator options

### PR DESCRIPTION
**Pull request by Skulblaka**
Summary of the changes (Less than 80 chars)
 - Add virtual method `PasswordValidator.GetOptions` to get `PasswordOptions`

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=28901) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=28901) before we can accept your contribution.<br/><br/>:x: Skulblaka [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=28901)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=28901) it.</sub>

**Comment by Skulblaka** [comment]
We have a group of users (lower-grade students) for which more lax password requirements are specified.

The passwords of lower-grade students can be validated using the `PasswordValidator` class as well, but I found no way to configure different `PasswordOptions` depending on a specific user.  
My change allows everyone to do this without having to copy the entire `ValidateAsync` method.

**Comment by pranavkm** [comment]
Thanks @Skulblaka for sending this PR. We typically would like an issue to discuss new features or behavior before starting work on it. In this particular case, it's likely that you should be able to configure `PasswordOptions` in your application startup: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration?view=aspnetcore-5.0#password.

Closing this PR. If you still feel the linked documentation doesn't cover your requirements, could you please start by filing an issue?

**Comment by mstfzhoseini-sketch** [comment]
Hi team, C#/ASP.NET Core pro (https://github.com/mstfzhoseini-sketch). CORS+SignalR fix: 1.5h

PR plan: AddCorsPolicy → MapHub sequence fix

Ready now!

Mostafa Hoseni

**Pull request closed without merging**
