### PR TITLE
Fix path for PoliCheckExclusions.xml

### PR DESCRIPTION
**Pull request by wtgodbe**
The current path points to the wrong place

### CODE REVIEW

**Review by jcagme — APPROVED** [review]
Thanks for fixing!

**Comment by dougbu** [comment]
Is the aspnetcore repository just one of those repos mapped when the eng/sdl-tsa-vars.config is actually used?

**Comment by jcagme** [comment]
> Is the aspnetcore repository just one of those repos mapped when the eng/sdl-tsa-vars.config is actually used?

Currently the following are doing nightly runs:

* https://github.com/dotnet/aspnetcore
* https://github.com/dotnet/aspnetcore-tooling
* https://github.com/dotnet/extensions
* https://github.com/dotnet/installer
* https://github.com/dotnet/efcore
* https://github.com/dotnet/ef6
* https://github.com/dotnet/runtime

But only aspnetcore defines `-PoliCheckAdditionalRunConfigParams` which I thought was correct but saw was missing the repo name

**Comment by dougbu** [comment]
Ah, I guess that the pipeline fetches two repos: The SDL one and the repo that's being checked?

**Comment by jcagme** [comment]
> Ah, I guess that the pipeline fetches two repos: The SDL one and the repo that's being checked?

That's very on point. The `dotnet-release` repo is cloned and it then executes a task to clone the aspnetcore (or any repo we'll analyze) and places it in `s/<repo-name>`

**Review by dougbu — APPROVED** [review]

**Pull request merged**
