### PR TITLE
Get `MSBuild` performance summary

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
😞 but :shipit:

**Comment by wtgodbe** [comment]
Won't the changes to eng/common/tools.ps1 be overwritten by the next update from Arcade?

**Comment by dougbu** [comment]
> Won't the changes to eng/common/tools.ps1 be overwritten by the next update from Arcade?

Yes. That's why we need to change Arcade if we're going to stop using binary logs.

BTW this PR is not something I intend to merge. The first commit isn't something we want or need in general. It's just useful as we try out ways to improve build performance e.g. @mmitche's investigations and mine.

**Pull request closed without merging**
