### PR TITLE
Upgrade Selenium Versions

### PR DESCRIPTION
**Pull request by TanayParikh**
Attempts to resolve issues seen in https://github.com/dotnet/aspnetcore/issues/34870.

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Comment by wtgodbe** [comment]
@TanayParikh go back to 4.0.0 - I'm mirroring the packages now

**Comment by dougbu** [comment]
We'll need this in release/6.0 too @TanayParikh I'll try but if it doesn't work, please `cherry-pick` manually.

(Tell-mode will be fine because this change only affects tests.)

**Comment by TanayParikh** [comment]
> We'll need this in release/6.0 too @TanayParikh I'll try but if it doesn't work, please `cherry-pick` manually.
> 
> (Tell-mode will be fine because this change only affects tests.)

https://github.com/dotnet/aspnetcore/pull/37735

**Pull request merged**
