### PR TITLE
Structured log in HttpLoggingMiddleware

### LINKED ISSUE #33038: Use structured log properties in HTTP logging middleware
The new [HTTP logging middleware](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-4/#http-logging-middleware) is a neat idea. IMO it's not really usable for anything else than simple console or file logging, though. This is because all of the information from the request and response is simply concatenated to a big string:

```
Request: Protocol: HTTP/2 Method: GET Scheme: https PathBase: Path: /serviceworker.js QueryString: Cache-Control: [Redacted] :authority: [Redacted] :method: [Redacted] :path: [Redacted] :scheme: [Redacted] Accept: */* Accept-Encoding: gzip, deflate, br Accept-Language: en-US,en;q=0.9,da;q=0.8,da-DK;q=0.7 Cookie: [Redacted] Host: localhost:5001 Referer: [Redacted] User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 service-worker: [Redacted] sec-fetch-site: [Redacted] sec-fetch-mode: [Redacted] sec-fetch-dest: [Redacted]
```

The string is fine, but including structured properties would make it possible to do lots of interesting things if working with a log storage implementation that supports structured properties. The above string could look like this structured:

```
Request: {Protocol} {Method} {Scheme} {PathBase} {Path} {QueryString} ...
```

### PR DESCRIPTION
**Pull request by Kahbazi**
Fixes https://github.com/dotnet/aspnetcore/issues/33038

### CODE REVIEW

**Comment by wtgodbe** [comment]
This addresses https://github.com/dotnet/aspnetcore/issues/33038 in practice, but I'm not sure it does in spirit - we're still concatenating the objects to strings in the middleware, so logger implementations still don't have access to the original objects - @davidfowl do we think that's a goal here?

**Comment by Tratcher** [comment]
HttpRequestLog has the list of individual objects, though I think AddToList needs to be changed from `string?` to `object` as well.

**Comment by wtgodbe** [comment]
At least `HttpRequest.QueryString` is not a string: https://github.com/dotnet/aspnetcore/blob/accd569d147859491dc639d2e2c4a586060b8713/src/Middleware/HttpLogging/src/HttpLoggingMiddleware.cs#L106-L109

**Comment by Tratcher** [comment]
It's mostly a string 😁. Passing the wrapper object preserves a little context. the same for Path. Anything else?

**Comment by wtgodbe** [comment]
There are some I'm adding in W3C, but I can handle those after this is in (Cookie, Query)

**Comment by davidfowl** [comment]
Yes this is fine.

**Review by davidfowl — APPROVED** [review]

**Pull request merged**
