### PR TITLE
[release/8.0] [Blazor] Fix misdetection of component comments

### LINKED ISSUE #52126: DOMException: Failed to execute 'setStartBefore' on 'Range': the given Node has no parent.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After upgrading an existing Blazor Server side on .NET 7 to a Blazor App in .NET 8 I get this javascript error when navigating:

```
Uncaught (in promise) DOMException: Failed to execute 'setStartBefore' on 'Range': the given Node has no parent.
    at q (https://localhost:7001/_framework/blazor.web.js:1:20110)
    at yi (https://localhost:7001/_framework/blazor.web.js:1:167970)
    at wi (https://localhost:7001/_framework/blazor.web.js:1:169913)
    at yi (https://localhost:7001/_framework/blazor.web.js:1:167646)
    at wi (https://localhost:7001/_framework/blazor.web.js:1:169913)
    at yi (https://localhost:7001/_framework/blazor.web.js:1:167646)
    at vi (https://localhost:7001/_framework/blazor.web.js:1:165963)
    at https://localhost:7001/_framework/blazor.web.js:1:176131
    at Object.write (https://localhost:7001/_framework/blazor.web.js:1:174447)
```

After that, the server streaming part of the page doesn't load. This is totally random. 

The same project works fine with the previous version of the framework,

### Expected Behavior

Navigate from one page to another without any problem

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version

8.0.100

### Anything else?

.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.8d38d0cc

Ambiente di runtime:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100\

Carichi di lavoro .NET installati:
 Workload version: 8.0.100-manifests.8d38d0cc
 [android]
   Origine dell'installazione: VS 17.8.34309.116
   Versioni del manifesto:    34.0.43/8.0.100
   Percorso del manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.43\WorkloadManifest.json
   Tipo di installazione:              Msi

 [maui-windows]
   Origine dell'installazione: VS 17.8.34309.116
   Versioni del manifesto:    8.0.3/8.0.100
   Percorso del manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.3\WorkloadManifest.json
   Tipo di installazione:              Msi

 [maccatalyst]
   Origine dell'installazione: VS 17.8.34309.116
   Versioni del manifesto:    17.0.8478/8.0.100
   Percorso del manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.0.8478\WorkloadManifest.json
   Tipo di installazione:              Msi

 [ios]
   Origine dell'installazione: VS 17.8.34309.116
   Versioni del manifesto:    17.0.8478/8.0.100
   Percorso del manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.0.8478\WorkloadManifest.json
   Tipo di installazione:              Msi

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]
  6.0.320 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]
  8.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

### PR DESCRIPTION
**Pull request by MackinnonBuck**
# Fix misdetection of component comments

Backport of https://github.com/dotnet/aspnetcore/pull/52647

Fixes an issue where in certain cases, SSR updates fail to apply to the page. This results browser errors which may cause parts of the app to lose functionality.

## Description

Under the hood, Blazor uses HTML comments to store component metadata in the DOM. When an SSR update occurs, those comments help indicate which HTML elements are associated with a component. However, one aspect of the enhanced navigation/streaming rendering logic was sometimes misinterpreting ordinary HTML comments as Blazor component comments, causing an error to be thrown. This edge case doesn't occur often, but the error can be reproduced fairly consistently if:

1. An app has an interactive component in the top level of its layout, then...
2. the user refreshes the browser while on a page with streaming enabled, then...
3. the user navigates to another page via enhanced navigation.

This PR fixes the issue by correcting the logic that sometimes misinterprets non-component comments as component comments.

Fixes #52126

## Customer Impact

Customers with interactive components in the top level of their app's layout are likely to encounter this bug. This seems to be a somewhat common pattern - we've seen multiple customers in the linked issue indicate that they're affected by this bug. When the bug occurs, it may cause parts of the app to stop working; components may not become interactive and link clicks may not do anything.

## Regression?

- [ ] Yes
- [X] No

This is a bug in streaming rendering and enhanced navigation, which are features that were introduced in .NET 8. The bug has existed for as long as SSR updates have been allowed to add, update, and remove interactive components.

## Risk

- [ ] High
- [ ] Medium
- [X] Low

The change to this particular piece of code is fairly straightforward to reason about, and we have a new E2E test for the exact scenario that produced the error.

## Verification

- [X] Manual (required)
- [X] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [X] N/A

### CODE REVIEW

**Review by javiercn — APPROVED** [review]

**Comment by wtgodbe** [comment]
@MackinnonBuck can you fix the merge conflict?

**Comment by wtgodbe** [comment]
@MackinnonBuck are the test failures related?

**Comment by wtgodbe** [comment]
Test failures are unrelated

**Pull request merged**
