### PR TITLE
Update Versions.props to latest Microsoft.Identity.Web

### PR DESCRIPTION
**Pull request by jmprieur**
# Update Versions.props to latest Microsoft.Identity.Web

- [x ] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Description
Update Versions.props to latest Microsoft.Identity.Web so that the project templates pick-them up (2.13.4)
Needed to support the CIAM scenarios in VS

@captainsafia FYI

### CODE REVIEW

**Comment by eerhardt** [comment]
Do you want this in .NET 8? If so, you should target the release/8.0 branch.

**Comment by jmprieur** [comment]
> Do you want this in .NET 8? If so, you should target the release/8.0 branch.

Fair enough. I'll do another PR for .NET 8 too?

**Comment by jmprieur** [comment]
@Tratcher : shall I close this new one?
https://github.com/dotnet/aspnetcore/pull/50594

**Comment by jmprieur** [comment]
> Ha, race conditions... I closed my duplicate.

Thanks @Tratcher

**Review by mthalman — APPROVED** [review]
No source-build concerns here since these properties look like they're only consumed by project templates.

**Review by eerhardt — APPROVED** [review]

**Pull request merged**
