### PR TITLE
Update ISSUE_TEMPLATE with clearer instructions

### PR DESCRIPTION
**Pull request by jchannon**
I went to Antiforgery repo, it said raise an issue here. I read this template and it told me to create it in a specific repository. Um, what?  This should hopefully make it clearer.

### CODE REVIEW

**Comment by Tratcher** [comment]
This is already stated on line 15 https://github.com/aspnet/Home/pull/3113/files#diff-1a1c3dd142f76a5fad803a0c52839881L15. At least remove the duplication?

**Comment by jchannon** [comment]
Removed the duplication, I think that was the line that was confusing 😄

**Comment by muratg** [comment]
cc @Eilon

**Comment by zoidhddhdd** [comment]
Cool

**Comment by Eilon** [comment]
Hi @jchannon thanks for the PR. I just updated the issue template with a bunch of info, including a clarification on repos: https://github.com/aspnet/Home/blob/master/.github/ISSUE_TEMPLATE.md

Thanks,
Eilon

(BTW sorry for the delay - I was on paternity leave + vacation for a while!)

**Pull request closed without merging**
