### PR TITLE
Make CertificateConfig linker friendly

### PR DESCRIPTION
**Pull request by benaadams**
#25485 targeting 5.0

Currently can't use Certificates from config files if you link ASP.NET as all the setters for the config section are removed.

This directly references the properties rather than nebulously reflecting them via `object` so the linker will preserve them as they are directly used.

Resolves https://github.com/dotnet/aspnetcore/issues/25482

### CODE REVIEW

**Comment by Tratcher** [comment]
Sorry, I timed that badly. release/5.0 locked down today for rc1. However, you can rebase onto release/5.0-rc2.

**Comment by benaadams** [comment]
I think you are secretly testing my retargeting skills 😅

**Review by Tratcher — APPROVED** [review]

**Comment by Tratcher** [comment]
> I think you are secretly testing my retargeting skills 😅

A challenge worth of any master dev.

**Comment by Tratcher** [comment]
@Pilchie rc2 merge please.

**Comment by Tratcher** [comment]
Wait... wrong branch.

**Comment by benaadams** [comment]
Bleh

**Comment by benaadams** [comment]
New PR, https://github.com/dotnet/aspnetcore/pull/25515

Using the GitHub UI to retarget wasn't a good idea 🤣

**Pull request closed without merging**
