### PR TITLE
Updated IdentityModel packages to 6.7

### LINKED ISSUE #23441: Consider bumping Wilson to 6.7.1
The preview7 branch was updated recently to target Wilson 6.6.0... 

https://github.com/dotnet/aspnetcore/blob/b446ab7c6f28bb10879bd355afe08bbf283c7de3/eng/Versions.props#L192-L194

... but Wilson 6.7.0 was released yesterday, so ASP.NET Core should probably target it instead of 6.6.0.

Changelog: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases/tag/6.7.0

### PR DESCRIPTION
**Pull request by HaoK**
Fixes https://github.com/dotnet/aspnetcore/issues/23441

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]

**Comment by HaoK** [comment]
@dougbu this is a preview7 change, basically same as the previous one just 6.7 came out right after we merged our last bump

**Comment by dougbu** [comment]
@HaoK preview 7 is pretty locked down this week and we've already had two builds to validate. Please work with @ajcvickers and / or @Pilchie to see if it's too late to merge this. May also need Tactics approval.

**Comment by HaoK** [comment]
Seems like this could wait til preview8, 6.6 should be good enough for preview 7 then.  @blowdart does that sound fine?

**Comment by blowdart** [comment]
Sure whatever works.

**Comment by HaoK** [comment]
Ok i will just remake this change against master, github rebase puked

**Pull request closed without merging**
