### PR TITLE
MapController in RazorPages

### LINKED ISSUE #8132: Routing doesn't find controllers when using StarterWeb template
The reason is that the template is missing `router.MapControllers()` call in the `Startup.Configure()` method. This results in the Default Identity UI's `AccountController` not routeable hence the error.

### PR DESCRIPTION
**Pull request by ryanbrandenburg**
Fixes #8132.

That `#if` is my attempt at "#if HasAuth". If there's a better way let me know.

### CODE REVIEW

**Comment by javiercn** [comment]
I'm not sure you need controllers in razor pages unless it's aad or b2c auth

**Comment by javiercn** [comment]
You should instantiate the different auth options and try that out

**Comment by ryanbrandenburg** [comment]
I already confirmed that it's needed for IndividualAuth in [the repro](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/797529?src=WorkItemMention&src-action=artifact_link). if you still think we need to check all the types do we have existing AD B2C/aad resources to use and/or instructions on how to set them up?

**Comment by javiercn** [comment]
Inside Azure there are samples, grab the settings from there and change the port in the generated app.

> I already confirmed that it's needed for IndividualAuth in [the repro](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/797529?src=WorkItemMention&src-action=artifact_link).

The template uses horrible terminology for the different options. Individual auth == Identity, the repro is for B2C (although AAD is on the same spot)

**Comment by javiercn** [comment]
I don't think it's needed for windows auth either.

**Review by rynowak — APPROVED** [review]

**Review by JamesNK — APPROVED** [review]

**Review by javiercn — APPROVED** [review]
looks good to me

**Comment by ryanbrandenburg** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=134406

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

I've triaged the above build.

**Pull request merged**
