### PR TITLE
Update branding to 2.1.29

### PR DESCRIPTION
**Pull request by JunTaoLuo**

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Review by wtgodbe — CHANGES_REQUESTED** [review]
You can update the zipfile manifest thing now also

**Comment by wtgodbe** [comment]
Need to retarget to rel/2.1

**Comment by JunTaoLuo** [comment]
Yea I was wondering about that, why do we do that as part of the branding update? Isn't it possible that it can contain unreleased bits?

**Comment by wtgodbe** [comment]
> Isn't it possible that it can contain references to unreleased bits?

Not in a way that would allow anybody to access them, or that would fail the build - I think they're effectively just numbers. But if it makes more sense we can move that to patch tuesday, I don't think it matters much either way as long as we're consistent.

**Review by dougbu — APPROVED** [review]

**Comment by JunTaoLuo** [comment]
I think I'd rather do it as part of the patch Tuesday changes.

**Review by wtgodbe — APPROVED** [review]

**Pull request merged**
