### PR TITLE
Update branding to 8.0.0-alpha1

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]
Do we need to update https://github.com/dotnet/aspnetcore/blob/2d953dbcb6f7313335bda764cea9a578920da7ce/src/Framework/AspNetCoreAnalyzers/test/Verifiers/CSharpRouteHandlerCodeFixVerifier.cs#L68?

**Comment by dougbu** [comment]
> Do we need to update &hellip;

Shouldn't need to do that yet. Not changing any TFMs.

**Comment by wtgodbe** [comment]
> Shouldn't need to do that yet. Not changing any TFMs.

Looks like the doc needs updating: https://github.com/dotnet/aspnetcore/pull/43308

**Comment by halter73** [comment]
Yeah. I think .NET 8 work should stay in feature branches for a while longer to avoid unnecessary merge conflicts.

**Comment by dougbu** [comment]
> Yeah. I think .NET 8 work should stay in feature branches for a while longer to avoid unnecessary merge conflicts.

What's the context for your comment @halter73❔ We're not changing TFMs at this point but are changing assembly and package versions, along w/ all other .NET repos.

**Comment by halter73** [comment]
I just don't want any big changes in `main` to cause merge conflicts with the .NET 7 release branches which I expect will be the more active source of changes over the next few weeks.

If we agreed to start .NET 8 branding this early, fine I guess. That shouldn't cause hard to resolve conflicts by itself, but I don't see the benefit to starting this early. When do we release 8.0.0-alpha1?

I expect life would be a whole lot easier for most devs if `main` only tracked .NET 7 changes for a little longer.

**Comment by dougbu** [comment]
Sorry, that's not the direction .NET has chosen at this time. We're rebranding now and in fact are late in doing so (due to test and infrastructure this hit yesterday).

**Pull request merged**
