### PR TITLE
Revert "Guarantee ordering for SignalR client HttpConnection.send (#1…

### PR DESCRIPTION
**Pull request by pranavkm**
…0780)"

This reverts commit b1a29281ba3b93d55a6b7b5b1a0c7f27de04bb78.

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @Pilchie \ @mkArtakMSFT \ @halter73

**Comment by pranavkm** [comment]
@aspnet/build we're taking this change for preview7. Reverting my most recent commit.

**Comment by Pilchie** [comment]
Thanks @pranavkm.  Do we need to be careful that the revert doesn't flow into `master`?

**Comment by pranavkm** [comment]
I'll take care of undoing it once it merges in to master. There isn't a good reason to complicate the automated build process

**Review by natemcmaster — APPROVED** [review]

**Comment by natemcmaster** [comment]
Thanks for the heads up.

FYI @wtgodbe @mmitche - this will mean rebuilding P6 from AspNetCore up.

**Comment by mmitche** [comment]
@natemcmaster no problem

**Comment by wtgodbe** [comment]
@natemcmaster do we need to wait for the helix leg to finish?

**Comment by mmitche** [comment]
I don't think we do.  It's going to fail becuase of lack of 10.14 machines.

**Comment by wtgodbe** [comment]
I'll go ahead and merge then, given that this is just a reversion.

**Pull request merged**
