### PR TITLE
Remove unnecessary null check

### PR DESCRIPTION
**Pull request by Kahbazi**

### CODE REVIEW

**Comment by Kahbazi** [comment]
This PR didn't automatically add anyone as reviewers. I have a feeling this PR is @blowdart's territory!

**Comment by blowdart** [comment]
Why do you think it's unnecessary? :) Or what actual harm does it do here?

**Comment by Kahbazi** [comment]
There's absolutely no harm here. I just thought since logger is being set in constructor, the null check could be dropped for a tiny perf improve.

**Comment by rynowak** [comment]
> 
> 
> There's absolutely no harm here. I just thought since logger is being set in constructor, the null check could be dropped for a tiny perf improve.

It improves the clarity of the code. Which I'm told is important when it's security related - the extra null check is misleading,

**Comment by blowdart** [comment]
Closing as we prefer clarity in this case.

**Pull request closed without merging**
