### PR TITLE
Set OpenApiServers object in document

### LINKED ISSUE #56188: Servers not emitted in OpenAPI document
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I ran the spectral CLI against the OpenAPI schema generated for an app of mine using .NET 9 preview.4, and there was a single warning against it:

```text
oas3-api-servers
OpenAPI "servers" must be present and non-empty array.
```

I see in #54598 that `servers` is mentioned, but I can't find anything explicit to track adding it in another issue or in any of the checkboxes in that issue.

> `servers`: Derived from the host info registered in the `IServer` implementation.

It also isn't currently assigned in the code:

https://github.com/dotnet/aspnetcore/blob/2b5d2b36a04f3a4a9bb20bbca38617d1cd6a3a1a/src/OpenApi/src/Services/OpenApiDocumentService.cs#L55-L60

### Expected Behavior

The `servers` property is present in the emitted OpenAPI schema document.

### Steps To Reproduce

Generate an OpenAPI document for a Minimal API using the new OpenAPI NuGet package.

### Exceptions (if any)

None.

### .NET Version

9.0.100-preview.4.24267.66

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by captainsafia**
Closes https://github.com/dotnet/aspnetcore/issues/56188 by setting `servers` property in local development based on metadata in `IServerAddressFeature`.

### CODE REVIEW

**Comment by captainsafia** [comment]
I've temporarily reverted `readOnly` support from this PR in reaction to some questions about how we might evolve `readOnly` in OpenAPI v3.1.

In OpenAPI v3.0, when `readOnly` is applied on a property that is in the required list, it's requiredness will only be validated for response types.

> If the property is marked as readOnly being true and is in the required list, the required will take effect on the response only.

In OpenAPI v3.1, we rely on JSON schema rules which don't enable similar validation on `readOnly`. We'll need to revisit how we want to bake in this behavior into the implementation at a later time.

**Review by BrennanConroy — COMMENTED** [review]
What's restricting this to development mode? Is it safe to include the server address(es) in a document that users can query?

Update the PR description so the readonly issue isn't closed 😄

**Comment by captainsafia** [comment]
> What's restricting this to development mode? Is it safe to include the server address(es) in a document that users can query?

Added an explicit check for the host environment here. This should achieve the desired goal of only settings the servers attribute for local scenarios where you might want to use something like Swagger UI or Postman to do E2E testing.

**Review by BrennanConroy — APPROVED** [review]
nit: I didn't notice a test with multiple addresses?

**Comment by captainsafia** [comment]
> nit: I didn't notice a test with multiple addresses?

Just added one.

**Comment by heedfull** [comment]
Is there a way to get your servers to show when the environment is Production? 
I need the servers so that the workaround below for running behind a reverse proxy works.

https://github.com/scalar/scalar/issues/4381#issuecomment-2575017829

**Comment by martincostello** [comment]
One way you can do it is [using my OpenAPI extensions library](https://github.com/martincostello/openapi-extensions?tab=readme-ov-file#usage), which includes a document transformer that adds the servers to the document for Production via an opt-in setting.

If you don't want to use that, then you'll need to implement your own [document transformer](https://learn.microsoft.com/aspnet/core/fundamentals/openapi/customize-openapi?view=aspnetcore-9.0#use-document-transformers) to do it.

**Pull request merged**
