### PR TITLE
[release/5.0] Resolve credscan bugs

### PR DESCRIPTION
**Pull request by wtgodbe**
Resolves remaining credscan bugs in this branch - anything in the suppressions file has already been approved via the same bugs in `main`

### CODE REVIEW

**Review by Pilchie — APPROVED** [review]
Do we have to deal with additional MusicStore issues in this branch?

**Comment by wtgodbe** [comment]
Doug removed MusicStore: https://github.com/dotnet/aspnetcore/pull/31818

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
The branches were open @wtgodbe❔

**Comment by wtgodbe** [comment]
> The branches were open @wtgodbe❔

Nope, we coordinated with tactics to merge them early since the deadline for credscan bugs is 5.28. I cancelled all of the internal builds.

**Pull request merged**
