### PR TITLE
See if project templates work on arm

### PR DESCRIPTION
**Pull request by HaoK**

### CODE REVIEW

**Comment by HaoK** [comment]
Some weird package restore issues, have you seen any thing like these errors recently @dougbu 

```
/root/helix/work/workitem/.dotnet385/sdk/6.0.100-alpha.1.20523.3/MSBuild.dll -consoleloggerparameters:Summary -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/root/helix/work/workitem/.dotnet385/sdk/6.0.100-alpha.1.20523.3/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/root/helix/work/workitem/.dotnet385/sdk/6.0.100-alpha.1.20523.3/dotnet.dll -maxcpucount -property:Configuration=Debug -verbosity:m /bl ./AspNet.gwoljqk1ywz.csproj
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.Authentication.JwtBearer with version (>= 6.0.0-ci)
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 972 version(s) in dotnet5 [ Nearest version: 5.0.0-rtm.20512.8 ]
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 189 version(s) in dotnet6 [ Nearest version: 6.0.0-alpha.1.20552.7 ]
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 64 version(s) in nuget.org [ Nearest version: 5.0.0-rc.2.20475.17 ]
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 1 version(s) in dotnet-tools [ Nearest version: 5.0.0-rc.2.20513.11 ]
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 0 version(s) in roslyn-tools
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 0 version(s) in roslyn
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 0 version(s) in dotnet-eng
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 0 version(s) in dotnet31-transport
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 0 version(s) in dotnet5-transport
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 0 version(s) in dotnet6-transport
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.Authentication.OpenIdConnect with version (>= 6.0.0-ci)
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 972 version(s) in dotnet5 [ Nearest version: 5.0.0-rtm.20512.8 ]
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 189 version(s) in dotnet6 [ Nearest version: 6.0.0-alpha.1.20552.7 ]
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 64 version(s) in nuget.org [ Nearest version: 5.0.0-rc.2.20475.17 ]
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 1 version(s) in dotnet-tools [ Nearest version: 5.0.0-rc.2.20513.11 ]
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 0 version(s) in roslyn-tools
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 0 version(s) in roslyn
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 0 version(s) in dotnet-eng
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 0 version(s) in dotnet31-transport
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 0 version(s) in dotnet5-transport
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 0 version(s) in dotnet6-transport

Build FAILED.

/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.Authentication.JwtBearer with version (>= 6.0.0-ci)
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 972 version(s) in dotnet5 [ Nearest version: 5.0.0-rtm.20512.8 ]
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 189 version(s) in dotnet6 [ Nearest version: 6.0.0-alpha.1.20552.7 ]
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 64 version(s) in nuget.org [ Nearest version: 5.0.0-rc.2.20475.17 ]
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 1 version(s) in dotnet-tools [ Nearest version: 5.0.0-rc.2.20513.11 ]
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 0 version(s) in roslyn-tools
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 0 version(s) in roslyn
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 0 version(s) in dotnet-eng
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 0 version(s) in dotnet31-transport
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 0 version(s) in dotnet5-transport
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 0 version(s) in dotnet6-transport
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.Authentication.OpenIdConnect with version (>= 6.0.0-ci)
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 972 version(s) in dotnet5 [ Nearest version: 5.0.0-rtm.20512.8 ]
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 189 version(s) in dotnet6 [ Nearest version: 6.0.0-alpha.1.20552.7 ]
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 64 version(s) in nuget.org [ Nearest version: 5.0.0-rc.2.20475.17 ]
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 1 version(s) in dotnet-tools [ Nearest version: 5.0.0-rc.2.20513.11 ]
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 0 version(s) in roslyn-tools
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 0 version(s) in roslyn
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 0 version(s) in dotnet-eng
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 0 version(s) in dotnet31-transport
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 0 version(s) in dotnet5-transport
/root/helix/work/workitem/Templates/BaseFolder/AspNet.gwoljqk1ywz/AspNet.gwoljqk1ywz.csproj : error NU1102:   - Found 0 version(s) in dotnet6-transport
    0 Warning(s)
    2 Error(s)
```

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-pull-27451-merge-9fb200bcd5dd482888/ProjectTemplates.Tests--net6.0/console.6a48bf59.log?sv=2019-07-07&se=2020-11-23T09%3A25%3A24Z&sr=c&sp=rl&sig=v7Mvt8n2ttmdwZUqyU3rCBruilrxupNsabuKNVGMd5Y%3D

**Comment by dougbu** [comment]
@HaoK the build uploaded Microsoft.AspNetCore.App.Runtime.linux-arm64.6.0.0-ci.nupkg but `TestRunner` looked for Microsoft.AspNetCore.App.Runtime.win-x64.6.0.0-ci.nupkg. Either need to switch the job to run on Windows ARM64 or generalize `TestRunner`.

**Comment by HaoK** [comment]
Ah right, so this was disabled due to the fact that we always use the runtime bits from win, I thought there was an issue tracking that somewhere but I can't seem to find it

**Comment by HaoK** [comment]
https://github.com/dotnet/aspnetcore/issues/25835

**Comment by HaoK** [comment]
I'll put that info in the bug

**Pull request closed without merging**
