### PR TITLE
Fix IDE0055 errors

### PR DESCRIPTION
**Pull request by dougbu**
- problems show up in local Ubuntu 20.04 builds but not on CI
- most errors involve now-disallowed line comments within expressions
- a few errors are about extra indentation for "pretty" alignment
- a few odd errors are about pragmas between comments and method declarations

### CODE REVIEW

**Comment by dougbu** [comment]
This PR fixes a variety of IDE0055 errors that show up in my WSL Ubuntu 20.04 environment but not when building locally on Windows 11 nor on the CI. Is that a bug somewhere❔

Can't say I'm a fan of the apparent rules about comment lines within expressions or how to place `#pragmas` around method descriptions. https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/formatting-rules mentions neither requirement and doesn't provide a way to turn either off. Thoughts❔

**Comment by dougbu** [comment]
I changed the wording of a few comments where they needed to be further from the relevant code. Any suggestions appreciated in that area❕

**Comment by pranavkm** [comment]
Could we turn off the rule if it's problematic and file an issue in https://github.com/dotnet/roslyn-analyzers? I don't think we should change perfectly valid code to make an analyzer happy.

> This PR fixes a variety of IDE0055 errors that show up in my WSL Ubuntu 20.04 environment 

I wonder if it's got to do with windows style line-endings in a Linux environment.

**Comment by dougbu** [comment]
Closing in favour of #40181

**Pull request closed without merging**
