### PR TITLE
Delete deprecated AzureAD identity UI packages

### PR DESCRIPTION
**Pull request by HaoK**
These packages were marked as obsolete in 5.0, as identity.web is the replacement, and the endpoints these work against are not going to be supported for much longer

### CODE REVIEW

**Review by javiercn — APPROVED** [review]
Looks good to me!

**Comment by HaoK** [comment]
@aspnet-build what am I supposed to do about the codecheck/baseline warnings from nuking the entire directory, do I have to leave empty directories around just with the baselines?

**Comment by dougbu** [comment]
> what am I supposed to do about the codecheck/baseline warnings

Fix the references to the removed projects in solution and solution filter files. Then one of us can merge on red, ignoring the other CodeCheck problem. The baseline complaint won't come back because the checks look at the current changes compared to the base branch.

**Comment by HaoK** [comment]
@dotnet/aspnet-build I believe the remaining code check failures are due to baselines, let me know if there's anything else I need to fix

**Pull request merged**
