### PR TITLE
[release/5.0] Update JavaScript dependencies for Web.JS project

### PR DESCRIPTION
**Pull request by captainsafia**
## Description

Update dependencies with known security issues via npm audit fix.

Technical note: `yarn` doesn't support `audit fix` so I used a [workaround](https://stackoverflow.com/questions/51732435/is-there-a-yarn-alternative-for-npm-audit/60878037#60878037) to automate the upgrades.

## Customer Impact

This PR includes some routine updates to the Node packages that we reference in the Angular template. Customers can apply these updates on their own but including them as part of the template reduces the friction for using these templates.

## Regression?
- [ ] Yes
- [X] No

## Risk
- [ ] High
- [ ] Medium
- [X] Low

The version changes mostly affect minor/path versions. `serialize-javascript` was incremented to a major version but we don't directly consume this package and the breaking changes cover internal behavior things (see [the release notes](https://github.com/yahoo/serialize-javascript/releases)). Manual/automated validation was complete.

## Verification
- [X] Manual (required)
- [X] Automated

Manual verification by running sample apps.

Automated validation via our E2E tests.

## Packaging changes reviewed?
- [ ] Yes
- [ ] No
- [X] N/A

### CODE REVIEW

**Comment by BrennanConroy** [comment]
nit: the workaround you linked technically isn't quite what you want. The yarn-audit-fix npm package is more accurate.

Basically, it will convert your yarn.lock file to package.lock.json **without** updating any packages (`npm i --package-lock-only` will update packages), then do the rest of the steps for you.

**Comment by captainsafia** [comment]
@BrennanConroy I believe the package is basically a util that does the steps in the workaround ([ref](https://github.com/antongolub/yarn-audit-fix/blob/master/src/main/ts/index.ts#L168-L179)).

I didn't follow the workaround to a tee since the fact that we have Yarn-specific local references in our repo totally borks `npm` so I had to remove the references, apply the the workaround, add the references, then install again. Seemed to do the trick.

**Comment by BrennanConroy** [comment]
> I believe the package is basically a util that does the steps in the workaround

Almost, the main difference is https://github.com/antongolub/yarn-audit-fix/blob/0171397bbf9e152b887b26e0ffafe19c293498e5/src/main/ts/index.ts#L99
Which converts the lock file instead of creating a lock file from scratch with npm. This would minimize unneeded package updates.

**Comment by captainsafia** [comment]
Ahhhhhh -- that's helpful to know.

Well, from a spot-check of the updates that were made here it seems that most of them are minor/patch version updates.

Hopefully, Dependabout will be setup soon so we don't have to do the manual changes.

**Comment by BrennanConroy** [comment]
Yeah I don't think it's a problem here. Just letting you know about it.

**Comment by wtgodbe** [comment]
@captainsafia let me know if/when this is ready to merge for March (branches close EOD)

**Review by javiercn — APPROVED** [review]
LGTM!

**Review by SteveSandersonMS — APPROVED** [review]

**Comment by captainsafia** [comment]
@wtgodbe Good to go! Thanks.

**Pull request merged**
