### PR TITLE
New Hosted build pools

### PR DESCRIPTION
**Pull request by ulisesh**
We are transitioning all servicing builds to a new set of build pools

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]
LGTM if it works

**Comment by wtgodbe** [comment]
Can you queue a test internal job against this branch as well?

**Comment by ulisesh** [comment]
Internal build worked, it was 20210902.23

**Comment by dougbu** [comment]
/fyi @TanayParikh still nope on the backport bot.

/fyi @dotnet/aspnet-build I'll move this change around manually&hellip;

**Pull request merged**
