### PR TITLE
Run components E2E tests in CI

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
This is to find out which of our various CI test runners are ready to run the Components' Selenium-based E2E tests.

If they all run them flawlessly we could merge this as-is. If not, I'll close this PR and investigate further.

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
I'm unclear on how to know whether this is passing or not.

 * The `AspNetCore-pr-validation-temp` job is passing, but that appears to be building only (not running any tests)
 * The `AspNetCore-ci` job always gets cancelled after 2h, which appears to be before it gets to the Component tests
 * The `aspnetci` setup runs the build separately from tests. I could manually trigger a build for the `stevesa/run-components-e2e-tests-in-ci` branch, but then is it possible to make it run tests based on the result of that build? The build of `master` is failing on `aspnetci` right now anyway, so it may well not be able to get to the stage of running tests.

It doesn't really matter right now though. Since this is a whole new category of tests, I was planning to wait until January before merging to `master` to avoid any risk of instability while I'm out. So I'll review the CI situation again at the start of the new year.

**Comment by SteveSandersonMS** [comment]
Looks like the PR validation and aspnetci builds aren't running unit tests currently anyway, so there isn't anything else to verify about this now. It does work locally and AFAIK should work the same in CI.

@rynowak @javiercn @natemcmaster If one of you could CR this so I can merge that would be great - thanks!

**Review by javiercn — APPROVED** [review]

**Comment by davidfowl** [comment]
This change is making tests hang on OSX.

**Comment by davidfowl** [comment]
```
 Selenium started
2019-01-08T21:27:28.5159090Z     [xUnit.net 00:00:04.7225098]     Microsoft.AspNetCore.Components.E2ETest.Tests.EventBubblingTest.BubblingStandardEvent_FiredOnElementWithHandler [FAIL]
2019-01-08T21:27:28.5442700Z     [xUnit.net 00:00:04.7329399]     Microsoft.AspNetCore.Components.E2ETest.Tests.EventTest.MouseOverAndMouseOut_CanTrigger [FAIL]
2019-01-08T21:27:28.5740220Z     [xUnit.net 00:00:04.7355707]     Microsoft.AspNetCore.Components.E2ETest.Tests.ComponentRenderingTest.CanUseJsInteropToReferenceElements [FAIL]
2019-01-08T21:27:28.5861460Z     [xUnit.net 00:00:04.7374082]     Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.ServerRoutingTest.CanFollowLinkToTargetBlankClick [FAIL]
2019-01-08T21:27:28.5970320Z     [xUnit.net 00:00:04.7412392]     Microsoft.AspNetCore.Components.E2ETest.Tests.EventTest.PreventDefault_AppliesToFormOnSubmitHandlers [FAIL]
2019-01-08T21:27:28.6114500Z     [xUnit.net 00:00:04.7437649]     Microsoft.AspNetCore.Components.E2ETest.Tests.ComponentRenderingTest.CanAddAndRemoveEventHandlersDynamically [FAIL]
2019-01-08T21:27:28.6299940Z     Failed   Microsoft.AspNetCore.Components.E2ETest.Tests.EventBubblingTest.BubblingStandardEvent_FiredOnElementWithHandler
2019-01-08T21:27:28.6401220Z     Error Message:
2019-01-08T21:27:28.6503210Z      System.AggregateException : One or more errors occurred. (Failed to connect to the web driver. Please see the readme and follow the instructions to install selenium.Remember to start the web driver with `selenium-standalone start` before running the end-to-end tests.) (The following constructor parameters did not have matching fixture data: BrowserFixture browserFixture)
2019-01-08T21:27:28.6604110Z     ---- System.InvalidOperationException : Failed to connect to the web driver. Please see the readme and follow the instructions to install selenium.Remember to start the web driver with `selenium-standalone start` before running the end-to-end tests.
2019-01-08T21:27:28.6706120Z     -------- OpenQA.Selenium.WebDriverException : unknown error: cannot find Chrome binary
2019-01-08T21:27:28.6806000Z       (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.13.6 x86_64) (WARNING: The server did not provide any stacktrace information)
2019-01-08T21:27:28.6907810Z     Command duration or timeout: 109 milliseconds
2019-01-08T21:27:28.7009420Z     Build info: version: '3.141.0', revision: '2ecb7d9a', time: '2018-10-31T20:22:52'
2019-01-08T21:27:28.7110360Z     System info: host: 'Mac-379.local', ip: '10.79.1.143', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_192'
2019-01-08T21:27:28.7211340Z     Driver info: driver.version: unknown
2019-01-08T21:27:28.7312910Z     ---- The following constructor parameters did not have matching fixture data: BrowserFixture browserFixture
2019-01-08T21:27:28.7412970Z     Stack Trace:
2019-01-08T21:27:28.7514600Z     
2019-01-08T21:27:28.7619370Z     ----- Inner Stack Trace #1 (System.InvalidOperationException) -----
2019-01-08T21:27:28.7719580Z        at Microsoft.AspNetCore.Components.E2ETest.Infrastructure.BrowserFixture..ctor() in /_/test/Microsoft.AspNetCore.Components.E2ETest/Infrastructure/BrowserFixture.cs:line 51
2019-01-08T21:27:28.7825260Z     ----- Inner Stack Trace -----
2019-01-08T21:27:28.7907420Z        at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
2019-01-08T21:27:28.7987980Z        at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2019-01-08T21:27:28.7989100Z        at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
2019-01-08T21:27:28.7989700Z        at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
2019-01-08T21:27:28.7990280Z        at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities, TimeSpan commandTimeout)
2019-01-08T21:27:28.7990860Z        at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
2019-01-08T21:27:28.7991430Z        at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, DriverOptions options)
2019-01-08T21:27:28.7992010Z        at Microsoft.AspNetCore.Components.E2ETest.Infrastructure.BrowserFixture..ctor() in /_/test/Microsoft.AspNetCore.Components.E2ETest/Infrastructure/BrowserFixture.cs:line 41
2019-01-08T21:27:28.7993410Z     ----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
2019-01-08T21:27:28.7994000Z     
2019-01-08T21:27:28.7994590Z     Failed   Microsoft.AspNetCore.Components.E2ETest.Tests.EventTest.MouseOverAndMouseOut_CanTrigger
2019-01-08T21:27:28.7995130Z     Error Message:
2019-01-08T21:27:28.7996510Z      System.AggregateException : One or more errors occurred. (Failed to connect to the web driver. Please see the readme and follow the instructions to install selenium.Remember to start the web driver with `selenium-standalone start` before running the end-to-end tests.) (The following constructor parameters did not have matching fixture data: BrowserFixture browserFixture)
2019-01-08T21:27:28.7997920Z     ---- System.InvalidOperationException : Failed to connect to the web driver. Please see the readme and follow the instructions to install selenium.Remember to start the web driver with `selenium-standalone start` before running the end-to-end tests.
2019-01-08T21:27:28.7999140Z     -------- OpenQA.Selenium.WebDriverException : unknown error: cannot find Chrome binary
2019-01-08T21:27:28.8099460Z       (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.13.6 x86_64) (WARNING: The server did not provide any stacktrace information)
2019-01-08T21:27:28.8100460Z     Command duration or timeout: 108 milliseconds
2019-01-08T21:27:28.8102140Z     Build info: version: '3.141.0', revision: '2ecb7d9a', time: '2018-10-31T20:22:52'
2019-01-08T21:27:28.8103520Z     System info: host: 'Mac-379.local', ip: '10.79.1.143', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_192'
2019-01-08T21:27:28.8104560Z     Driver info: driver.version: unknown
2019-01-08T21:27:28.8105600Z     ---- The following constructor parameters did not have matching fixture data: BrowserFixture browserFixture
2019-01-08T21:27:28.8106150Z     Stack Trace:
2019-01-08T21:27:28.8106650Z     
2019-01-08T21:27:28.8107590Z     ----- Inner Stack Trace #1 (System.InvalidOperationException) -----
2019-01-08T21:27:28.8208000Z        at Microsoft.AspNetCore.Components.E2ETest.Infrastructure.BrowserFixture..ctor() in /_/test/Microsoft.AspNetCore.Components.E2ETest/Infrastructure/BrowserFixture.cs:line 51
2019-01-08T21:27:28.8310090Z     ----- Inner Stack Trace -----
2019-01-08T21:27:28.8408190Z        at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
2019-01-08T21:27:28.8409440Z        at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2019-01-08T21:27:28.8410050Z        at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
2019-01-08T21:27:28.8410290Z        at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
2019-01-08T21:27:28.8410540Z        at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities, TimeSpan commandTimeout)
2019-01-08T21:27:28.8410700Z        at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
2019-01-08T21:27:28.8410860Z        at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, DriverOptions options)
2019-01-08T21:27:28.8411460Z        at Microsoft.AspNetCore.Components.E2ETest.Infrastructure.BrowserFixture..ctor() in /_/test/Microsoft.AspNetCore.Components.E2ETest/Infrastructure/BrowserFixture.cs:line 41
2019-01-08T21:27:28.8412870Z     ----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

With a 30 second re-try per test 😄

**Comment by natemcmaster** [comment]
I think we need to revert this if we can fix this soon. All PR checks on master are failing because they exceed the build timeout.

**Pull request merged**
