### PR TITLE
Revert Enforce WebSockets Transport for Blazor

### PR DESCRIPTION
**Pull request by TanayParikh**
## Description

Reverting changes introduced in https://github.com/dotnet/aspnetcore/pull/34644, which enforced WebSockets as the only available transport. Long polling was disabled as a fallback transport, due to concerns about user experience.

## Customer Impact

This was a breaking change ([announcement](https://github.com/aspnet/Announcements/issues/470) / [docs](https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/6.0/blazor-long-polling-fallback)). However, based on the feedback received in the recent RC1 release, more users are still utilizing long polling than expected. By adding back support of long polling, we're hoping to reduce migration complexity from .NET 5 -> .NET 6

## Regression?
- [ ] Yes
- [x] No

[If yes, specify the version the behavior has regressed from]

## Risk
- [ ] High
- [ ] Medium
- [x] Low

[Justify the selection above]

Reverting changes introduced in RC1 to add back long polling as a fallback transport.

## Verification
- [x] Manual (required)
- [ ] Automated

## Packaging changes reviewed?
- [ ] Yes
- [ ] No
- [x] N/A

Addresses https://github.com/dotnet/aspnetcore/issues/36655

### CODE REVIEW

**Review by SteveSandersonMS — APPROVED** [review]

**Review by pranavkm — APPROVED** [review]
Changes look good.

@BrennanConroy we're undoing the limitation we added to Blazor Server to only use WebSockets, but changes to SignalR client that added details to the error are left as is.

**Comment by TanayParikh** [comment]
@Pilchie requesting approval to get this in for RC2.

**Comment by Pilchie** [comment]
Approved by me, but needs approval from Tactics for RC2.

**Comment by TanayParikh** [comment]
Thanks Kevin. This has now been approved by tactics for RC2 (offline). @dotnet/aspnet-build could this please be merged.

**Comment by Daniel15** [comment]
Have you considered using Server-Sent Events (SSE) as a fallback with a higher priority than long polling? Like long polling, it's plain HTTP so it gets through most proxies. Unlike long polling, it's a properly defined protocol with a spec.

**Comment by TanayParikh** [comment]
> Have you considered using Server-Sent Events (SSE) as a fallback with a higher priority than long polling? Like long polling, it's plain HTTP so it gets through most proxies. Unlike long polling, it's a properly defined protocol with a spec.

Hi @Daniel15. SSE is limited to supporting `Text` data, and does not support arbitrary binary data (without `Base-64` encoding). Hence WebSockets and Long Polling are the only transport options for us. 

More details are available [here](https://github.com/aspnet/SignalR/blob/master/specs/TransportProtocols.md#transfer-formats).

**Pull request merged**
