### PR TITLE
Fixed two misspelling of 'tenant' in properties' inline XML documentation

### PR DESCRIPTION
**Pull request by biste5**
In two files, just a misspell in the documentation
- Azure/AzureAD/Authentication.AzureAD.UI/src/AzureADOptions.cs
- AzureAD/Authentication.AzureADB2C.UI/src/AzureAdB2COptions.cs

### CODE REVIEW

**Review by javiercn — APPROVED** [review]

**Comment by javiercn** [comment]
@biste5 Thanks for your contribution. 

Seems that this branch needs to be rebased before we can merge the changes.

**Comment by biste5** [comment]
@javiercn ok. Sorry for  the inconvenience. Just to clarify: shall I just rebase onto 'master' and still target 'master', or something different?

**Comment by javiercn** [comment]
Just rebase on to master.

image

**Comment by biste5** [comment]
I don't think I have anything to rebase from master..
image
upstream is set to https://github.com/aspnet/AspNetCore.git

**Comment by javiercn** [comment]
The issue went away, I'm not sure why. But it's merged now. Thanks!

**Pull request merged**
