### PR TITLE
Added typescript fix for problem with specs created by "dotnet new angular --auth"

### LINKED ISSUE #18121: Jasmine specs fail on new angular project using --auth Individual
### Describe the bug
After creating a new project using "dotnet new angular", there are jasmine spec failures.

### To Reproduce
Run attached script (create-problem.bat).  This script creates a new solution with a webapi/angular project, builds the solution, and then runs 'ng test'

[create-problem.bat.txt](https://github.com/aspnet/AspNetCore/files/4021951/create-problem.bat.txt)

You should see a handful of spec failures in LoginMenuComponent, AuthorizeGuard, LogoutComponent.  (see spec-failure-details.txt)

[spec-failure-details.txt](https://github.com/aspnet/AspNetCore/files/4021954/spec-failure-details.txt)

AuthorizeGuard > should ...
NullInjectorError: StaticInjectorError(DynamicTestModule)[AuthorizeGuard -> Router]: 
  StaticInjectorError(Platform: core)[AuthorizeGuard -> Router]: 
    NullInjectorError: No provider for Router!
error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'AuthorizeGuard', Function ] })
    at <Jasmine>
    at NullInjector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:855:1)
    at resolveToken (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:17514:1)
    at tryResolveToken (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:17440:1)
    at StaticInjector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:17266:1)
    at resolveToken (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:17514:1)
    at tryResolveToken (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:17440:1)
    at StaticInjector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:17266:1)
    at resolveNgModuleDep (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:30393:1)
    at _createClass (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:30463:1)
    at _createProviderInstance (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:30426:1)
LogoutComponent > should create
NullInjectorError: StaticInjectorError(DynamicTestModule)[LogoutComponent -> ActivatedRoute]: 
  StaticInjectorError(Platform: core)[LogoutComponent -> ActivatedRoute]: 
    NullInjectorError: No provider for ActivatedRoute!
error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'LogoutComponent', Function ], ngDebugContext: DebugContext_({ view: Object({ def: Object({ factory: Function, nodeFlags: 33669121, rootNodeFlags: 33554433, nodeMatchedQueries: 0, flags: 0, nodes: [ Object({ nodeIndex: 0, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: 0, flags: 33554433, childFlags: 114688, directChildFlags: 114688, childMatchedQueries: 0, matchedQueries: Object({  }), matchedQueryIds: 0, references: Object({  }), ngContentIndex: null, childCount: 1, bindings: [  ], bindingFlags: 0, outputs: [  ], element: Object({ ns: '', name: 'app-logout', attrs: [  ], template: null, componentProvider: Object({ nodeIndex: 1, parent: <circular reference: Object>, renderParent: <circular reference: Object>, bindingIndex: 0, outputIndex: 0, checkIndex: 1, flags: 114688, childFlags: 0, directChildFlags: 0, childMatchedQueries: 0, matchedQueries: Object, matchedQueryIds: 0, references: Object, ngContentIndex ...
    at <Jasmine>
    at NullInjector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:855:1)
    at resolveToken (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:17514:1)
    at tryResolveToken (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:17440:1)
    at StaticInjector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:17266:1)
    at resolveToken (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:17514:1)
    at tryResolveToken (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:17440:1)
    at StaticInjector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:17266:1)
    at resolveNgModuleDep (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:30393:1)
    at NgModuleRef_.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:31578:1)
    at resolveDep (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:32143:1)
Expected undefined to be truthy.
Error: Expected undefined to be truthy.
    at <Jasmine>
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/src/api-authorization/logout/logout.component.spec.ts:23:23)
    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:359:1)
    at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:308:1)
LoginComponent > should create
NullInjectorError: StaticInjectorError(DynamicTestModule)[LoginComponent -> ActivatedRoute]: 
  StaticInjectorError(Platform: core)[LoginComponent -> ActivatedRoute]: 
    NullInjectorError: No provider for ActivatedRoute!
error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'LoginComponent', Function ], ngDebugContext: DebugContext_({ view: Object({ def: Object({ factory: Function, nodeFlags: 33669121, rootNodeFlags: 33554433, nodeMatchedQueries: 0, flags: 0, nodes: [ Object({ nodeIndex: 0, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: 0, flags: 33554433, childFlags: 114688, directChildFlags: 114688, childMatchedQueries: 0, matchedQueries: Object({  }), matchedQueryIds: 0, references: Object({  }), ngContentIndex: null, childCount: 1, bindings: [  ], bindingFlags: 0, outputs: [  ], element: Object({ ns: '', name: 'app-login', attrs: [  ], template: null, componentProvider: Object({ nodeIndex: 1, parent: <circular reference: Object>, renderParent: <circular reference: Object>, bindingIndex: 0, outputIndex: 0, checkIndex: 1, flags: 114688, childFlags: 0, directChildFlags: 0, childMatchedQueries: 0, matchedQueries: Object, matchedQueryIds: 0, references: Object, ngContentIndex:  ...
    at <Jasmine>
    at NullInjector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:855:1)
    at resolveToken (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:17514:1)
    at tryResolveToken (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:17440:1)
    at StaticInjector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:17266:1)
    at resolveToken (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:17514:1)
    at tryResolveToken (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:17440:1)
    at StaticInjector.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:17266:1)
    at resolveNgModuleDep (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:30393:1)
    at NgModuleRef_.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:31578:1)
    at resolveDep (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:32143:1)
Expected undefined to be truthy.
Error: Expected undefined to be truthy.
    at <Jasmine>
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/src/api-authorization/login/login.component.spec.ts:23:23)
    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:359:1)
    at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:308:1)
LoginMenuComponent > should create
Failed: Template parse errors:
Can't bind to 'routerLink' since it isn't a known property of 'a'. ("*ngIf="isAuthenticated | async">
    <li class="nav-item">
        <a  class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/profile"]' title="Manage">Hello {{ userName | async }}</a>
    </li>"): ng:///DynamicTestModule/LoginMenuComponent.html@2:39
Can't bind to 'routerLink' since it isn't a known property of 'a'. ("
    </li>
    <li class="nav-item">
        <a  class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/logout"]' [state]='{ local: true }' title="Logout">Logout</a>
    </"): ng:///DynamicTestModule/LoginMenuComponent.html@5:39
Can't bind to 'state' since it isn't a known property of 'a'. ("class="nav-item">
        <a  class="nav-link text-dark" [routerLink]='["/authentication/logout"]' [ERROR ->][state]='{ local: true }' title="Logout">Logout</a>
    </li>
</ul>
"): ng:///DynamicTestModule/LoginMenuComponent.html@5:81
Can't bind to 'routerLink' since it isn't a known property of 'a'. ("*ngIf="!(isAuthenticated | async)">
  <li class="nav-item">
        <a class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/register"]'>Register</a>
    </li>
    <li class="nav-item">
"): ng:///DynamicTestModule/LoginMenuComponent.html@10:38
Can't bind to 'routerLink' since it isn't a known property of 'a'. ("
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/login"]'>Login</a>
    </li>
</ul>
"): ng:///DynamicTestModule/LoginMenuComponent.html@13:38
error properties: Object({ ngSyntaxError: true, ngParseErrors: [ Can't bind to 'routerLink' since it isn't a known property of 'a'. ("*ngIf="isAuthenticated | async">
    <li class="nav-item">
        <a  class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/profile"]' title="Manage">Hello {{ userName | async }}</a>
    </li>"): ng:///DynamicTestModule/LoginMenuComponent.html@2:39, Can't bind to 'routerLink' since it isn't a known property of 'a'. ("
    </li>
    <li class="nav-item">
        <a  class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/logout"]' [state]='{ local: true }' title="Logout">Logout</a>
    </"): ng:///DynamicTestModule/LoginMenuComponent.html@5:39, Can't bind to 'state' since it isn't a known property of 'a'. ("class="nav-item">
        <a  class="nav-link text-dark" [routerLink]='["/authentication/logout"]' [ERROR ->][state]='{ local: true }' title="Logout">Logout</a>
    </li>
</ul>
"): ng:///DynamicTestModule/LoginMenuComponent.htm ... ...
Error: Template parse errors:
Can't bind to 'routerLink' since it isn't a known property of 'a'. ("*ngIf="isAuthenticated | async">
    <li class="nav-item">
        <a  class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/profile"]' title="Manage">Hello {{ userName | async }}</a>
    </li>"): ng:///DynamicTestModule/LoginMenuComponent.html@2:39
Can't bind to 'routerLink' since it isn't a known property of 'a'. ("
    </li>
    <li class="nav-item">
        <a  class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/logout"]' [state]='{ local: true }' title="Logout">Logout</a>
    </"): ng:///DynamicTestModule/LoginMenuComponent.html@5:39
Can't bind to 'state' since it isn't a known property of 'a'. ("class="nav-item">
        <a  class="nav-link text-dark" [routerLink]='["/authentication/logout"]' [ERROR ->][state]='{ local: true }' title="Logout">Logout</a>
    </li>
</ul>
"): ng:///DynamicTestModule/LoginMenuComponent.html@5:81
Can't bind to 'routerLink' since it isn't a known property of 'a'. ("*ngIf="!(isAuthenticated | async)">
  <li class="nav-item">
        <a class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/register"]'>Register</a>
    </li>
    <li class="nav-item">
"): ng:///DynamicTestModule/LoginMenuComponent.html@10:38
Can't bind to 'routerLink' since it isn't a known property of 'a'. ("
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/login"]'>Login</a>
    </li>
</ul>
"): ng:///DynamicTestModule/LoginMenuComponent.html@13:38
    at syntaxError (http://localhost:9876/_karma_webpack_/node_modules/@angular/compiler/fesm2015/compiler.js:2175:1)
    at TemplateParser.parse (http://localhost:9876/_karma_webpack_/node_modules/@angular/compiler/fesm2015/compiler.js:11388:1)
    at JitCompiler._parseTemplate (http://localhost:9876/_karma_webpack_/node_modules/@angular/compiler/fesm2015/compiler.js:25961:1)
    at JitCompiler._compileTemplate (http://localhost:9876/_karma_webpack_/node_modules/@angular/compiler/fesm2015/compiler.js:25949:61)
    at http://localhost:9876/_karma_webpack_/node_modules/@angular/compiler/fesm2015/compiler.js:25893:1
    at <Jasmine>
    at JitCompiler._compileComponents (http://localhost:9876/_karma_webpack_/node_modules/@angular/compiler/fesm2015/compiler.js:25893:1)
    at http://localhost:9876/_karma_webpack_/node_modules/@angular/compiler/fesm2015/compiler.js:25813:1
    at Object.then (http://localhost:9876/_karma_webpack_/node_modules/@angular/compiler/fesm2015/compiler.js:2166:27)
    at JitCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/node_modules/@angular/compiler/fesm2015/compiler.js:25811:1)
Error: Template parse errors:
Can't bind to 'routerLink' since it isn't a known property of 'a'. ("*ngIf="isAuthenticated | async">
    <li class="nav-item">
        <a  class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/profile"]' title="Manage">Hello {{ userName | async }}</a>
    </li>"): ng:///DynamicTestModule/LoginMenuComponent.html@2:39
Can't bind to 'routerLink' since it isn't a known property of 'a'. ("
    </li>
    <li class="nav-item">
        <a  class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/logout"]' [state]='{ local: true }' title="Logout">Logout</a>
    </"): ng:///DynamicTestModule/LoginMenuComponent.html@5:39
Can't bind to 'state' since it isn't a known property of 'a'. ("class="nav-item">
        <a  class="nav-link text-dark" [routerLink]='["/authentication/logout"]' [ERROR ->][state]='{ local: true }' title="Logout">Logout</a>
    </li>
</ul>
"): ng:///DynamicTestModule/LoginMenuComponent.html@5:81
Can't bind to 'routerLink' since it isn't a known property of 'a'. ("*ngIf="!(isAuthenticated | async)">
  <li class="nav-item">
        <a class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/register"]'>Register</a>
    </li>
    <li class="nav-item">
"): ng:///DynamicTestModule/LoginMenuComponent.html@10:38
Can't bind to 'routerLink' since it isn't a known property of 'a'. ("
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/login"]'>Login</a>
    </li>
</ul>
"): ng:///DynamicTestModule/LoginMenuComponent.html@13:38
error properties: Object({ ngSyntaxError: true, ngParseErrors: [ Can't bind to 'routerLink' since it isn't a known property of 'a'. ("*ngIf="isAuthenticated | async">
    <li class="nav-item">
        <a  class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/profile"]' title="Manage">Hello {{ userName | async }}</a>
    </li>"): ng:///DynamicTestModule/LoginMenuComponent.html@2:39, Can't bind to 'routerLink' since it isn't a known property of 'a'. ("
    </li>
    <li class="nav-item">
        <a  class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/logout"]' [state]='{ local: true }' title="Logout">Logout</a>
    </"): ng:///DynamicTestModule/LoginMenuComponent.html@5:39, Can't bind to 'state' since it isn't a known property of 'a'. ("class="nav-item">
        <a  class="nav-link text-dark" [routerLink]='["/authentication/logout"]' [ERROR ->][state]='{ local: true }' title="Logout">Logout</a>
    </li>
</ul>
"): ng:///DynamicTestModule/LoginMenuComponent.htm ... ...
Error: Template parse errors:
Can't bind to 'routerLink' since it isn't a known property of 'a'. ("*ngIf="isAuthenticated | async">
    <li class="nav-item">
        <a  class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/profile"]' title="Manage">Hello {{ userName | async }}</a>
    </li>"): ng:///DynamicTestModule/LoginMenuComponent.html@2:39
Can't bind to 'routerLink' since it isn't a known property of 'a'. ("
    </li>
    <li class="nav-item">
        <a  class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/logout"]' [state]='{ local: true }' title="Logout">Logout</a>
    </"): ng:///DynamicTestModule/LoginMenuComponent.html@5:39
Can't bind to 'state' since it isn't a known property of 'a'. ("class="nav-item">
        <a  class="nav-link text-dark" [routerLink]='["/authentication/logout"]' [ERROR ->][state]='{ local: true }' title="Logout">Logout</a>
    </li>
</ul>
"): ng:///DynamicTestModule/LoginMenuComponent.html@5:81
Can't bind to 'routerLink' since it isn't a known property of 'a'. ("*ngIf="!(isAuthenticated | async)">
  <li class="nav-item">
        <a class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/register"]'>Register</a>
    </li>
    <li class="nav-item">
"): ng:///DynamicTestModule/LoginMenuComponent.html@10:38
Can't bind to 'routerLink' since it isn't a known property of 'a'. ("
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/login"]'>Login</a>
    </li>
</ul>
"): ng:///DynamicTestModule/LoginMenuComponent.html@13:38
    at syntaxError (http://localhost:9876/_karma_webpack_/node_modules/@angular/compiler/fesm2015/compiler.js:2175:1)
    at TemplateParser.parse (http://localhost:9876/_karma_webpack_/node_modules/@angular/compiler/fesm2015/compiler.js:11388:1)
    at JitCompiler._parseTemplate (http://localhost:9876/_karma_webpack_/node_modules/@angular/compiler/fesm2015/compiler.js:25961:1)
    at JitCompiler._compileTemplate (http://localhost:9876/_karma_webpack_/node_modules/@angular/compiler/fesm2015/compiler.js:25949:61)
    at http://localhost:9876/_karma_webpack_/node_modules/@angular/compiler/fesm2015/compiler.js:25893:1
    at <Jasmine>
    at JitCompiler._compileComponents (http://localhost:9876/_karma_webpack_/node_modules/@angular/compiler/fesm2015/compiler.js:25893:1)
    at http://localhost:9876/_karma_webpack_/node_modules/@angular/compiler/fesm2015/compiler.js:25813:1
    at Object.then (http://localhost:9876/_karma_webpack_/node_modules/@angular/compiler/fesm2015/compiler.js:2166:27)
    at JitCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/node_modules/@angular/compiler/fesm2015/compiler.js:25811:1)
Expected undefined to be truthy.
Error: Expected undefined to be truthy.
    at <Jasmine>
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/src/api-authorization/login-menu/login-menu.component.spec.ts:23:23)
    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:359:1)
    at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:308:1)

### PR DESCRIPTION
**Pull request by benday**
Summary of the changes (Less than 80 chars)
 - Modified angular template code for api-authorization to fix defects in specs
 - Imported RouterTestingModule to login, logout, and login-menu component specs
 - Modified login.componet.spec.ts to use spys to mock logic in AuthorizeService during testing

Addresses #18121

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
Thanks for your PR, @benday. Please target `master` branch as this resulted in too many commits and file changes showing up, making the PR unreadable.

**Comment by benday** [comment]
@mkArtakMSFT -- FYI, I changed the target branch from 3.0 to master.  Hopefully this should keep the changes more readable.

**Review by ryanbrandenburg — DISMISSED** [review]
Unfortunately this doesn't seem to fix all the tests when merged with the master branch.

**Review by benday — COMMENTED** [review]
Removed trailing spaces per PR comments

**Comment by ryanbrandenburg** [comment]
I'm still seeing failures such as:
```
Chrome 84.0.4147.105 (Windows 10) LoginMenuComponent should create FAILED
            <li class="nav-item">
                <a  class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/profile"]' title="Manage">Hello {{ userName | async }}</a>
            </li>
            <li class="nav-item">
                <a  class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/logout"]' [state]='{ local: true }' title="Logout">Logout</a>
                <a  class="nav-link text-dark" [routerLink]='["/authentication/logout"]' [ERROR ->][state]='{ local: true }' title="Logout">Logout</a>
            </li>
        </ul>
        Can't bind to 'routerLink' since it isn't a known property of 'a'. ("*ngIf="isAuthenticated | async">
            <li class="nav-item">
                <a  class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/profile"]' title="Manage">Hello {{ userName | async }}</a>
            </li>"): ng:///DynamicTestModule/LoginMenuComponent.html@2:39
        Can't bind to 'routerLink' since it isn't a known property of 'a'. ("
            </li>
            <li class="nav-item">
                <a  class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/logout"]' [state]='{ local: true }' title="Logout">Logout</a>
            </"): ng:///DynamicTestModule/LoginMenuComponent.html@5:39
        Can't bind to 'state' since it isn't a known property of 'a'. ("class="nav-item">
                <a  class="nav-link text-dark" [routerLink]='["/authentication/logout"]' [ERROR ->][state]='{ local: true }' title="Logout">Logout</a>
            </li>
        </ul>
        "): ng:///DynamicTestModule/LoginMenuComponent.html@5:81
        Can't bind to 'routerLink' since it isn't a known property of 'a'. ("*ngIf="!(isAuthenticated | async)">
          <li class="nav-item">
                <a class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/register"]'>Register</a>
            </li>
            <li class="nav-item">
        "): ng:///DynamicTestModule/LoginMenuComponent.html@10:38
        Can't bind to 'routerLink' since it isn't a known property of 'a'. ("
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" [ERROR ->][routerLink]='["/authentication/login"]'>Login</a>
            </li>
        </ul>
        "): ng:///DynamicTestModule/LoginMenuComponent.html@13:38
        error properties: Object({ ngSyntaxError: true, ngParseErrors: [ Can't bind to 'routerLink' since it isn't a known property of 'a'. ("*ngIf="isAuthenticated | async">
            </li>"): ng:///DynamicTestModule/LoginMenuComponent.html@2:39, Can't bind to 'routerLink' since it isn't a known property of 'a'. ("
            </"): ng:///DynamicTestModule/LoginMenuComponent.html@5:39, Can't bind to 'state' since it isn't a known property of 'a'. ("class="nav-item">
        "): ng:///DynamicTestModule/LoginMenuComponent.htm ... ...
```
when I attempt to run these tests. Are you not seeing those when you run it locally? If not let me know what steps your taking to test so I can follow them.

**Comment by benday** [comment]
Yah.  I'm seeing that, too.  It was working and now it isn't.  

BTW, the "dotnet new angular" template targets Angular 8.  I've got this working with Angular 9.  Would you like me to add my Angular 9 template updates to this PR along with the security unit test changes?

**Comment by ryanbrandenburg** [comment]
> BTW, the "dotnet new angular" template targets Angular 8. I've got this working with Angular 9. Would you like me to add my Angular 9 template updates to this PR along with the security unit test changes?

Moving to Angular 9 is a bigger thing (if not for the code, then from the book-keeping we do about dependencies on our end). I would prefer to keep the two separate.

**Comment by benday** [comment]
gotcha.  should I submit a PR for Angular 9 or would you like to push that to a later date entirely?

**Comment by ryanbrandenburg** [comment]
The issue for upgrading to Angular 9 [is here](https://github.com/dotnet/aspnetcore/issues/14076). Looks like we had previously delayed due to problems people were finding with upgrading. @danroth27 is driving some other work related to our SPA templates and could maybe opine if you asked on that issue.

**Comment by danroth27** [comment]
@LadyNaggaga

**Comment by mkArtakMSFT** [comment]
@HaoK can you please take this PR over from @ryanbrandenburg and work with @benday to get this merged? Thanks!
//cc @javiercn

**Comment by HaoK** [comment]
@benday looks like all the CI checks are passing now, are you still seeing any failures or is this good to go from your perspective?

**Review by HaoK — APPROVED** [review]

**Comment by benday** [comment]
@HaoK -- Looks good to me.  No changes from my end.  I'd say it's good to go.  Lemme know if you need anything.

**Comment by HaoK** [comment]
Thanks for the PR @benday

**Pull request merged**
