### PR TITLE
Drop IResponseCache async methods

### LINKED ISSUE #14993: Change IResponseCache output to ValueTask
In ResponseCaching middleware there's no way to replace `IResponseCache` and in the implementation of it (`MemoryResponseCache`), the async methods are just a wrapper on sync methods. So is it better that the output of the methods be ValueTask?

### PR DESCRIPTION
**Pull request by Kahbazi**
Fixes #14993

### CODE REVIEW

**Comment by anurse** [comment]
cc @davidfowl 

For context everyone, these async methods weren't actually doing anything async and were completely `internal` so @Kahbazi wondered if they should just be removed.

**Comment by jkotalik** [comment]
@JunTaoLuo to evaluate the risk of this change.

**Comment by davidfowl** [comment]
Seems fine, this interface is internal and nothing was async.

**Review by JunTaoLuo — APPROVED** [review]
Yes this looks good.

**Comment by JunTaoLuo** [comment]
Thanks for the contribution @Kahbazi !

**Pull request merged**
