### PR TITLE
Update IdentityModel version

### PR DESCRIPTION
**Pull request by wtgodbe**
@mmitche @mthalman is there a source-build-externals commit w/ the new IdentityModel version that we can ingest?

### CODE REVIEW

**Comment by mthalman** [comment]
I'll get that pushed.

**Comment by mthalman** [comment]
https://github.com/dotnet/source-build-externals/pull/252

**Comment by ViktorHofer** [comment]
I just hit this in the PR. Triggered the SBE dependency and copied this change into https://github.com/dotnet/aspnetcore/pull/53302

**Comment by ViktorHofer** [comment]
Closing in favor of https://github.com/dotnet/aspnetcore/pull/53252

**Pull request closed without merging**
