### PR TITLE
Big-endian fixes: Kestrel IP/socket address handling

### PR DESCRIPTION
**Pull request by uweigand**
* Add big-endian version of optimized SockAddr.cs processing

* Fixes part 2 of https://github.com/dotnet/aspnetcore/issues/35709

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

**PR Title**
Big-endian fixes: Kestrel IP/socket address handling

**PR Description**
* Add big-endian version of optimized SockAddr.cs processing
* Fixes part 2 of https://github.com/dotnet/aspnetcore/issues/35709

### CODE REVIEW

**Review by halter73 — APPROVED** [review]

**Comment by uweigand** [comment]
> @uweigand Are you actually using the libuv transport? I ask because it's [officially deprecated](https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/5.0/kestrel-libuv-transport-obsolete), but I'm fine taking this.

Ah, I wasn't aware of this, thanks.  In any case, I simply noticed that there were a bunch of failing test cases, which turned out to be caused by the problem fixed here.   So as long as this is still in the code base (and still being tested), I would prefer the endian fix to be included, if only to get the test suite clean.

(B.t.w. the web page you linked to states that "Libuv support [...] will be removed entirely in .NET 6.0."   Is that actually going to happen, given that it still appears to be present in the previews?)

**Comment by halter73** [comment]
It's unlikely that libuv will be removed in .NET6 at this point, but we reserve the right to do so.

**Review by adityamandaleeka — APPROVED** [review]

**Comment by adityamandaleeka** [comment]
Thanks @uweigand

**Pull request merged**
