### PR TITLE
Add HTTP/2 pseudo headers as known headers

### LINKED ISSUE #4761: Add HTTP/2 pseudo-headers as known headers
https://github.com/aspnet/KestrelHttpServer/blob/526dfdb332b30fd6042d8ef8d1a2ba99cc654010/src/Kestrel.Core/Internal/Http2/Http2Stream.cs#L55-L66

It looks like these are being treated as unknown headers. Consider adding them to KnownHeaders. Note we'll have to special case them in the generator as the colon does not translate into a valid C# member name.

https://github.com/aspnet/KestrelHttpServer/blob/526dfdb332b30fd6042d8ef8d1a2ba99cc654010/tools/CodeGenerator/KnownHeaders.cs

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/aspnetcore/issues/4761

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]
I'm curious if this registers on the benchmarks.

**Comment by titanix** [comment]
There is a typo in variable name in https://github.com/dotnet/aspnetcore/blob/master/src/Servers/Kestrel/shared/KnownHeaders.cs#L369

 `var identifer` instead of ` var identifier`

**Comment by Tratcher** [comment]
Woops. Want to fix it?

**Comment by titanix** [comment]
I made a [PR](https://github.com/dotnet/aspnetcore/pull/27431). Note I just lexically change the source code from GitHub since I don't have enough storage on my machine to download, build and test code.

**Pull request merged**
