### PR TITLE
change 'ValuesController' to 'ValueController'

### PR DESCRIPTION
**Pull request by deepchoudhery**
- changed references in Web.ItemTemplates\content\ApiController\ValueController.cs from `ValuesController` to `ValueController`
- consistent with the all other references
- fixed --name parameter

### CODE REVIEW

**Comment by mitchdenny** [comment]
Is this just a preference for singular over plural controller names?

**Comment by deepchoudhery** [comment]
> Is this just a preference for singular over plural controller names?

It actually fixes the issue with `--name` param working correctly since the template.json and the actual file ValueController.cs were out of sync with the reference `ValueController`. Need them matching for the parameter working.

**Comment by mkArtakMSFT** [comment]
Thanks @deepchoudhery. Can you share the customer impact please?
Specifically what was not working for the customer?

As a side note, I do agree that the class name should have matched the file name here, and it was most probably a mistake done when this was created.

**Comment by deepchoudhery** [comment]
> Thanks @deepchoudhery. Can you share the customer impact please? Specifically what was not working for the customer?
> 
> As a side note, I do agree that the class name should have matched the file name here, and it was most probably a mistake done when this was created.

Customer Impact : Customers who want to name their ApiController using the --name, controller will not be named correctly.

It was a mistake when we first [committed ](https://github.com/dotnet/aspnetcore/pull/46714)this template to aspnetcore

**Review by mkArtakMSFT — APPROVED** [review]
Thanks @deepchoudhery !

**Comment by mkArtakMSFT** [comment]
@deepchoudhery can you merge this, or do you want me to ?

**Pull request merged**
