### PR TITLE
Add exclusion for `.vsconfig` file to CI

### PR DESCRIPTION
**Pull request by ShreyasJejurkar**
Let's not trigger CI for `.vsconfig` changes, we dont validate anything in CI for this file!

### CODE REVIEW

**Review by captainsafia — COMMENTED** [review]
The last time we made a change to these builds was [in this commit](https://github.com/dotnet/aspnetcore/commit/f55bcd840f9405808d0daa210933a425b584b95c) which was reverted in [this PR](https://github.com/dotnet/aspnetcore/pull/29321) because:

> Decided these exclusions were a mistake. Though the product won't change when these files are updated, we should keep our builds up-to-date.

From [here](https://github.com/dotnet/aspnetcore/pull/29321).

I'd like to wait and here @wtgodbe thoughts on trying this again but he's OOF at the moment.

**Comment by ShreyasJejurkar** [comment]
Thanks for the reply @captainsafia. We should trigger CI for doc files as there is now markdown-lint configured in CI to validate those changes. 
But in this PR, I am adding an exclusion for the `.vsconfig` file which is used for Visual Studio workload configuration for developers/contributors, and "it is not a doc file". 

And also we don't get any benefit for running the CI for the changes in this file, as we don't validate it in CI! 

We can wait for @wtgodbe reply here, no hurries at all. 😅

**Review by wtgodbe — CHANGES_REQUESTED** [review]
Unfortunately we can't use the path exclude feature without making it more difficult to merge PRs that touch those paths - `aspnetcore-ci` is a required check for this repo, so if it doesn't run, PR merges are blocked. Unfortunately, as of now, there's no way to tell github to only consider required checks _if they've ran_.

**Comment by wtgodbe** [comment]
Going to close this as we unfortunately can't skip required jobs until github supports a way to make them required only if they've actually ran

**Pull request closed without merging**
