### PR TITLE
Wrong replication of resource names in embedded file provider

### LINKED ISSUE #45585: EmbeddedFileProvider: Not recognizing correct manifest resource names
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When using the EmbeddedFileProvider in my example for the UseStaticFiles builder method, it won't recognizing that the manifest resource names of the folders with an hypen (-) changes to underscore (_). So it cannot find the embedded files.

In my researches I found out, that the hyphen may not be an allowed EverettId character and gets replaced by an underscore in the [CreateManifestNameImpl](https://github.com/dotnet/msbuild/blob/main/src/Tasks/CreateCSharpManifestResourceName.cs#L89)-Method of the [CreateCSharpManifestResourceName.cs](https://github.com/dotnet/msbuild/blob/main/src/Tasks/CreateCSharpManifestResourceName) class.

**Example:**

File path: 
/lib/nice-css/nice-css.css

Manifest resource name: 
lib.nice_css.nice-css.css

Embedded File Provider looking for path:
lib.nice-css.nice-css.css

### Expected Behavior

The embedded file provider should looking for the correct resource name with the same logic how the resource names gets created.

### Steps To Reproduce

https://github.com/Yannici/IssueEmbeddedFileProvider

### Exceptions (if any)

_No response_

### .NET Version

7.0.100

### Anything else?

Visual Studio 2022 17.4.2
ASP.NET Core Version: 7.0.0

.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

### PR DESCRIPTION
**Pull request by Yannici**
Fixes wrong replication of resource names in embedded provider

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Added methods to make valid everett-id directory names and fixed wrong replicates of the embedded resource names.

## Description

Added functionality that already exists in dotnet/msbuild that creates resource names as a valid Everett ID. These resource names now getting correctly replicated to find the correct file in the embedded file provider.

Fixes #45585

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=46067) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=46067) before we can accept your contribution.<br/><br/>:x: Yannici [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=46067)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=46067) it.</sub>

**Comment by mkArtakMSFT** [comment]
Hi @Nick-Stanton.
Can you please look into this and try to review? Thanks!

**Review by Nick-Stanton — APPROVED** [review]
Nit: You don't really need triple-slash annotations for private methods, especially since you left descriptive comments throughout. I'll leave it open for a few days just in case you want to change it, but otherwise thank you for your contribution!

**Comment by Yannici** [comment]
Thanks for the review.
I took over some methods from dotnet/msbuild and left the comments like they were. That's why I don't think I will change it.

**Pull request merged**
