### PR TITLE
[release/2.2] update SignalR Java client signing cert

### PR DESCRIPTION
**Pull request by analogrelay**
Update the Java signing cert in 2.2. See https://github.com/aspnet/AspNetCore/pull/9048

Part of https://github.com/aspnet/AspNetCore-Internal/issues/2109

### CODE REVIEW

**Comment by Eilon** [comment]
Why 18,000 lines changed?

**Comment by anurse** [comment]
> Why 18,000 lines changed?

Wow. Let me... uh.. fix that :)

**Comment by anurse** [comment]
That's better :)

**Review by Eilon — APPROVED** [review]

**Comment by anurse** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=142465

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

I've triaged the above build.

**Review by dougbu — APPROVED** [review]

**Comment by anurse** [comment]
Waiting to confirm that the infrastructure is all in place before merging.

**Comment by anurse** [comment]
Ok, checked in with @natemcmaster. We're good to go if we merge this and https://github.com/aspnet/AspNetCore-Internal/pull/2151/files#diff-89c5000ec48d3e950226e7fb88462c23 together.

**Review by natemcmaster — APPROVED** [review]

**Comment by dougbu** [comment]
@anurse we need this in before official 2.2.x builds kick off correct? Are waiting for anything to merge it?

**Comment by anurse** [comment]
@dougbu I need to merge the internal PR first. I'll do that now and we should be able to merge this tomorrow morning.

**Comment by anurse** [comment]
Looks like the "Infrastructure" build is pretty snappy. Should be able to merge now.

**Pull request merged**
