### PR TITLE
Omit keyed services from OpenAPI definitions

### PR DESCRIPTION
**Pull request by captainsafia**
Fixes https://github.com/dotnet/aspnetcore/issues/50704

### CODE REVIEW

**Review by BrennanConroy — APPROVED** [review]

**Comment by captainsafia** [comment]
@danmoseley Can I get help merging this? It addresses a bug report from a customer using RC1. Keyed services need to be omitted from OpenAPI definition, like non-keyed services, since they are not derived from the HTTP request.

**Review by davidfowl — APPROVED** [review]

**Comment by danmoseley** [comment]
approved, impact meets bar, and I'm going to infer risk is low..

**Comment by stevendarby** [comment]
@captainsafia this doesn't seem to work for attributes derived from `FromKeyedServicesAttribute` - can it be changed to use `IsAssignableTo` instead of the direct type comparison? Should I raise a new issue for this?

**Comment by martincostello** [comment]
> Should I raise a new issue for this?

Yes.

**Pull request merged**
