### PR TITLE
Add missing archive files

### PR DESCRIPTION
**Pull request by wtgodbe**
We've missed creating these in the last 2 releases of 2.1.

### CODE REVIEW

**Review by dougbu — COMMENTED** [review]
What's failing w/o these empty files and why are they all empty (archives aren't consistently empty though they often are)❔

**Comment by wtgodbe** [comment]
> The ArchiveBaseline for previous release (v2.1.34) could not be found. This is required to build the incremental archives. See instructions in D:\a\_work\1\s\src\PackageArchive\ZipManifestGenerator/README.md

@vseanreesermsft reported the above error on Teams.

They're empty because https://github.com/dotnet/versions/tree/main/build-info/dotnet/product/cli/release doesn't update anymore, I don't actually know if we use these for anything at this point - if not we could find the source of the above error & disable it

**Comment by dougbu** [comment]
> if not we could find the source of the above error & disable it

src/PackageArchive/Archive.targets is imported by the four src/PackageArchive .zipproj and .lzmaproj projects as well as by repo.targets (which BuildTools uses for the outer build). @Pilchie do we need archives like nuGetPackagesArchive-ci-server-2.1.34.zip going forward❔ I _think_ these were used in Azure / Antares deployments, which might include .NET Framework support.

**Comment by Pilchie** [comment]
I don't think this is used anywhere anymore, but I'm not sure.  @joeloff or @marcpopMSFT do you know?

**Comment by dougbu** [comment]
If we also confirm the archives aren't needed anymore, let's do a follow-up to avoid these manual steps in the future i.e. remove the code that relies on these files and maybe everything that creates the archives

**Pull request merged**
