### PR TITLE
Add Third Party Notices

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
We have a file at the root of the repo but it's primarily for things that ship in the SharedFx. Putting it here seems nicer, but I don't know if it's the correct (legal) thing to do.

**Comment by Eilon** [comment]
Historically, a Third Party Notice (3PN) must be easily findable in every place where a 3rd party project is included. So, there needs to be a 3PN in these places:

1. This GitHub repo needs one for _all_ third-party content that's in it (e.g. there must be a hundred copies of jQuery and Bootstrap in here, plus random other stuff)
2. Every NuGet package that _contains_ third-party content (e.g. let's say a template NUPKG contains jQuery)
3. Every MSI or ZIP or other container that has third-party content needs one for whatever it has

Also, historically the 3PN includes copies of the licenses of those third-party contents for informational purposes (as opposed to just a list of projects). I'm not sure what the current policy is on that.

**Comment by Eilon** [comment]
Here's a mildly useful tool I've used in the past to generate the 3PN file: https://github.com/Eilon/ThirdPartyNoticesGenerator

**Review by SteveSandersonMS — APPROVED** [review]
This looks totally reasonable to me.

I also don't know for sure if there's any rule that all TPN information must be at the root of the repo, or if it's OK to put them in the relevant subfolders. @Pilchie might know.

**Comment by pranavkm** [comment]
Thanks @Eilon . I started off from the 3PN file that was in the original fork of this project and stripped things out. We generally don't expect users to reference this, it's a majorly stripped down version of the app primarily meant for benchmarking.

**Comment by Eilon** [comment]
@SteveSandersonMS the 3PN just have to be easily gettable. Root of the repo certainly counts. But some reasonably-named sub-folder or similar thing with a reasonably-named file usually suffices.

**Pull request merged**
