### PR TITLE
Updating sdk/tooling version

### PR DESCRIPTION
**Pull request by sebastienros**
@BrennanConroy I am almost sure you know a magic command to do it, but I guess this works too.

### CODE REVIEW

**Comment by sebastienros** [comment]
The goal is to update the api changes that have been done to kestrel.

**Comment by BrennanConroy** [comment]
I don't think this will work. This probably pulls in the net5.0 TFM which needs a lot of work, see https://github.com/dotnet/aspnetcore/pull/19860

**Comment by sebastienros** [comment]
It's not the most recent one, would the tests fail?

**Comment by dougbu** [comment]
@sebastienros suggest closing this in favour of #21017

**Pull request closed without merging**
