### PR TITLE
Remove photo from showprofile

### LINKED ISSUE #25254: [Templates] Update ShowProfile to avoid Base64 encoding images
https://github.com/dotnet/aspnetcore/blob/release/5.0-preview8/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorServerWeb-CSharp/Pages/ShowProfile.razor#L71-L72

### PR DESCRIPTION
**Pull request by HaoK**
Fixes https://github.com/dotnet/aspnetcore/issues/25254

### CODE REVIEW

**Review by pranavkm — APPROVED** [review]

**Comment by pranavkm** [comment]
Shoot missed that this wasn't targeting the 5.0 branch. @mkArtakMSFT are we cool porting this change to 5.0?

**Comment by HaoK** [comment]
Ah my bad, didn't realize there was a release/5.0 branch now too, want me to cherry pick it and open a new pR?

**Comment by HaoK** [comment]
https://github.com/dotnet/aspnetcore/pull/26253 is the release/5.0 PR

**Comment by pranavkm** [comment]
Sorry, release/5.0-rc2 would be the ideal place to put it in, but I'm not sure if we're too late for a rc2 change at this point. release/5.0 is likely the RTM targeting branch but @mkArtakMSFT might be able to confirm that.

**Comment by HaoK** [comment]
Okay I'll retarget my cherry pick PR to rc2

**Pull request merged**
