### PR TITLE
Merge 5.0-preview2

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
@jkotalik do these changes look right? The automated PR shows 100s of files changing + has merge conflicts that are suspect.

**Review by dougbu — APPROVED** [review]
Looks fine but why not update the merge bot's branch in #19724❔

**Comment by pranavkm** [comment]
Will do

**Comment by pranavkm** [comment]
Hmm, so I can't seem to update the bot branch:

>  ! [remote rejected]       merge/release/5.0-preview2-to-master -> merge/release/5.0-preview2-to-master (shallow update not allowed)

Let's just use this to get the change in.

**Comment by dougbu** [comment]
Odd error message from `git` that seems to indicate the bot is using shallow branches i.e. doesn't have much history around. Given that, using your own branch is fine. Sounds like the other alternative is to execute `git fetch --unshallow origin` in the bot's branch before pushing the right changes back at it.

**Pull request merged**
