### PR TITLE
Add an analyzer that complains when using using model binding attributes with a minimal action delegate (#35359)

### PR DESCRIPTION
**Pull request by BrennanConroy**
* [x] Complain when using MVC binding attributes with minimal action

Backport of https://github.com/dotnet/aspnetcore/pull/35359

## Customer Impact

Easier to diagnose issues when using minimal APIs incorrectly, via an analyzer.

## Testing

Automated tests for both positive and negative cases.

## Risk

Low

### CODE REVIEW

**Review by pranavkm — APPROVED** [review]

**Comment by davidfowl** [comment]
Is the risk really low since we're doing this ship with the SDK thing? How well is this tested?

**Comment by pranavkm** [comment]
I would say this is medium risk. There is a new servicing burden since we haven't really understood what it takes to service analyzers in the targeting pack. That said, we already have one in there (the logging source generator), so there's some sunk cost fallacy here.

**Comment by davidfowl** [comment]
How well is this change tested though?

**Comment by pranavkm** [comment]
We have automated tests, and that gives us code coverage for the implementation. Unfortunately the end-to-end scenarios require a build of the installer with the changes. I verified things by manually patching things in, but that does leave much to be desired. An actual build with all things in place isn't available as yet.

If we're feeling iffy about it, we could punt it until rc2 and give it a little more time to bake.

**Comment by davidfowl** [comment]
I rather do it in RC1 than RC2 but I I want to make sure we aren't flowing things all the way to the installer to find basic problems. We should spend time verifying (as hacky as we need to) to make sure we're not missing basic things.

**Comment by pranavkm** [comment]
In that sense - we have reasonable coverage outside of a legit installer build. 

Like I mentioned earlier, I was able to manually verify by extracting the targeting pack over an existing SDK. Our helix tests also do something to this effect (by updating the contents of the locally installed .dotnet) and we discovered a packaging issue because of this.

**Review by davidfowl — APPROVED** [review]

**Comment by davidfowl** [comment]
Approved. I await the outcome of the dependency flow.

**Comment by pranavkm** [comment]
@wtgodbe could you merge this please? Thanks!

**Comment by pranavkm** [comment]
Circling back - the analyzer is available as part of the 6.0-rc1 installer and appears to be working great.

**Pull request merged**
