### PR TITLE
Minimal APIs naming cleanup

### LINKED ISSUE #35478: Minimal APIs naming cleanup
We should not use "Minimal" in any API names. We should also avoid the word "action" when defining minimal route handlers.

1. `MinimalActionEndpointRouteBuilderExtensions` -> `DelegateEndpointRouteBuilderExtensions`
2. `MinimalActionEndpointConventionBuilder` -> `DelegateEndpointConventionBuilder`
3. `Map(this IEndpointRouteBuilder endpoints, RoutePattern pattern, Delegate action)` -> `Map(this IEndpointRouteBuilder endpoints, RoutePattern pattern, Delegate handler)`
4. `RequestDelegateFactory.Create(Delegate action, RequestDelegateFactoryOptions? options)` -> `RequestDelegateFactory.Create(Delegate handler, RequestDelegateFactoryOptions? options)`

### PR DESCRIPTION
**Pull request by halter73**
This avoids using "Minimal" in any API names and avoids using "action" when defining minimal route handlers.

1. `MinimalActionEndpointRouteBuilderExtensions` -> `DelegateEndpointRouteBuilderExtensions`
2. `MinimalActionEndpointConventionBuilder` -> `DelegateEndpointConventionBuilder`
3. `Map(this IEndpointRouteBuilder endpoints, RoutePattern pattern, Delegate action)` -> `Map(this IEndpointRouteBuilder endpoints, RoutePattern pattern, Delegate handler)`

Once this is merged, I'll backport for rc1 since this is a breaking change.

Fixes #35478

### CODE REVIEW

**Review by pranavkm — APPROVED** [review]

**Review by davidfowl — APPROVED** [review]
LGTM

**Comment by davidfowl** [comment]
You gonna backport this?

**Comment by halter73** [comment]
> You gonna backport this?

Yep. I'm just trying to follow the proper process.

**Comment by Kahbazi** [comment]
`action` -> `handler` ?
https://github.com/dotnet/aspnetcore/blob/1c929ce5293cfdba516ae883475baef087bf84d8/src/Http/Http.Extensions/src/RequestDelegateFactory.cs#L73

**Comment by halter73** [comment]
Good catch @Kahbazi 👍

**Comment by Kahbazi** [comment]
There's also some hard-coded string in analyzer. 

https://github.com/dotnet/aspnetcore/blob/6475919c680bee247def46551d0636575ce2a9e4/src/Framework/Analyzer/src/MinimalActions/WellKnownTypes.cs#L14

**Comment by JamesNK** [comment]
I don't know if it counts, but an analyzer also has minimal actions in public API:

https://github.com/dotnet/aspnetcore/blob/main/src/Framework/Analyzer/src/MinimalActions/MinimalActionAnalyzer.cs

**Comment by halter73** [comment]
I'm not sure if it counts either, but I renamed `MinimalActionAnalyzer` to `DelegateEndpointAnalyzer` and the containing namespace from `Microsoft.AspNetCore.Analyzers.MinimalActions` to `Microsoft.AspNetCore.Analyzers.DelegateEndpoints` in the last commit.

**Pull request merged**
