### PR TITLE
Use .IndexOf(char/byte) where possible

### PR DESCRIPTION
**Pull request by benaadams**
As its faster. Also string.IndexOf(string) is by default CurrentCulture so its much faster than that.

Follow up to https://github.com/aspnet/AspNetCore/pull/9537

FormPipeReader goes a bit ugly using the ternaries

/cc @GrabYourPitchforks for more spice

### CODE REVIEW

**Comment by rynowak** [comment]
:shipit: from  me on the routing change. Someone else should take a look at the form reader part :)

**Comment by benaadams** [comment]
>  Someone else should take a look at the form reader part :)

I think I'm going to back that out as its too ugly; and the current version shouldn't be too bad, even if its doing extra work.

**Comment by benaadams** [comment]
K, dropped the Formreader change

**Review by Tratcher — APPROVED** [review]

**Comment by anurse** [comment]
Looks nice and safe to me. I'll merge now for preview 5.

**Pull request merged**
