### PR TITLE
Update Blazor survey link

### PR DESCRIPTION
**Pull request by adrianwright109**
Updates Blazor survey link to: [https://go.microsoft.com/fwlink/?linkid=2086020](https://go.microsoft.com/fwlink/?linkid=2086020)

Addresses #8860

### CODE REVIEW

**Review by danroth27 — APPROVED** [review]
Looks good to me. Thanks!

**Comment by mkArtakMSFT** [comment]
@aspnet/brt Another potential flaky test causing this PR to fail. I've retried the failed jobs.

**Comment by mkArtakMSFT** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=135570

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

I've triaged the above build.

**Comment by mkArtakMSFT** [comment]
Waiting for https://github.com/aspnet/AspNetCore/pull/9094#pullrequestreview-223051835 to be merged

**Comment by danroth27** [comment]
I've rebased these change in another PR (https://github.com/aspnet/AspNetCore/pull/9095) so we can get past the CI failures.

**Pull request closed without merging**
