### PR TITLE
[Static web assets] Updates hosting to use the new static web assets manifest format (#34510)

### PR DESCRIPTION
**Pull request by JunTaoLuo**
Cherry picked https://github.com/dotnet/aspnetcore/pull/34510 to main.

Updates static web assets to use the new JSON based manifest format.

The build now produces a <<AppName>>.staticwebasets.runtime.json that
contains a list of content roots as well as a tree structure that
includes the paths for the list of mapped static web assets as well as
the list of patterns to use for discovering new asses.

### CODE REVIEW

**Comment by javiercn** [comment]
@JunTaoLuo thanks John, I was preparing a change but was running into issues with picking up a newer SDK

**Comment by JunTaoLuo** [comment]
What was the issue with updating the SDK? Does this change need to be combined with https://github.com/dotnet/aspnetcore/pull/34550/files?

**Comment by javiercn** [comment]
@JunTaoLuo I think so.

I was bumping the SDK manually on global.json (same thing I did in preview) and was getting build errors on random stuff, so I gave up

**Comment by dougbu** [comment]
See also the very similar #34819

**Comment by JunTaoLuo** [comment]
I opened the PR originally to start the cherry-picking process. Looks like there's been more progress with https://github.com/dotnet/aspnetcore/pull/34819 so I'll close this one. Thanks @javiercn

**Pull request closed without merging**
