### PR TITLE
[release/3.0-preview6] Unpin EF dependencies then grab the latest

### PR DESCRIPTION
**Pull request by dougbu**
- #10050
- includes new preview 6 packages from Blazor, Extensions, EntityFrameWorkCore, and AspNetCore-Tooling
- update coherent parent chain to use EF Core instead of AspNetCore-Tooling again
- partially reverts 58c67727dfb3

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging to see status here.

**Review by ajcvickers — APPROVED** [review]

**Comment by dougbu** [comment]
Retried the PR validation build. First attempt failed 6 tests on Ubuntu which is strange&hellip;

**Review by mmitche — APPROVED** [review]

**Review by natemcmaster — APPROVED** [review]

**Comment by natemcmaster** [comment]
@aspnet-hello triage  https://dev.azure.com/dnceng/public/_build/results?buildId=210185&view=logs

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2303

**Comment by dougbu** [comment]
@Pilchie @natemcmaster and I looked at the test failures in the 1st attempt and couldn't find anything of concern. 2nd attempt already succeeded and is working on notifying GitHub. Anything I should wait on before merging this PR e.g. https://devdiv.visualstudio.com/DevDiv/_workitems/edit/904672 ?

**Comment by natemcmaster** [comment]
Let's merge and get a build queued up. I would be shocked if this change wasn't approved by QB since this is just a dependency update.

**Comment by Pilchie** [comment]
Thanks everyone.  Merging was the right call.

**Pull request merged**
