### PR TITLE
Update Selenium dependencies

### PR DESCRIPTION
**Pull request by Tratcher**
Regular update to Selenium dependencies.

### CODE REVIEW

**Comment by Tratcher** [comment]
@dotnet/aspnet-build these versions can't be updated because the new packages aren't available on our feeds, only nuget.org. Did the process for copying a package from nuget ever get worked out?

**Comment by dougbu** [comment]
> Did the process for copying a package from nuget ever get worked out?

The most common way to request additions to `nuget-public` is to ask in the First Responders channel. They are very responsive.

**Comment by Tratcher** [comment]
```
System.InvalidOperationException : Failed to launch the server.
ExitCode: 0
Captured output lines:

> microsoft.aspnetcore.components.e2etest@0.0.1 selenium-standalone D:\a\_work\2\s\src\Components\test\E2ETest
> selenium-standalone "start" "--config" "D:\a\_work\2\s\src\Shared\E2ETesting\selenium-config.json" "--" "-port" "15100"

(node:3568) UnhandledPromiseRejectionWarning: Error: Missing D:\a\_work\2\s\src\Components\test\E2ETest\node_modules\selenium-standalone\.selenium\chromedriver\94.0.4606.6100-x64-chromedriver
    at D:\a\_work\2\s\src\Components\test\E2ETest\node_modules\selenium-standalone\lib\check-paths-existence.js:16:29
    at suppressedCallback (fs.js:235:5)
    at FSReqCallback.oncomplete (fs.js:179:23)
(Use node --trace-warnings ... to show where the warning was created)
(node:3568) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3568) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This might require the updates to selenium-standalone? https://github.com/dotnet/aspnetcore/pull/37184

Alternatively, selenium-config.json doesn't like trailing zeros?

**Comment by TanayParikh** [comment]
@Tratcher what's the status on this one. Can it be merged considering CI is green?

**Comment by Tratcher** [comment]
I was waiting for the CI. Yes, it's ready for review now.

**Review by dougbu — APPROVED** [review]

**Pull request merged**
