### PR TITLE
Add section to UpdatingMajorVersionAndTFM.md about marking APIs shipped

### PR DESCRIPTION
**Pull request by wtgodbe**

### CODE REVIEW

**Review by dougbu — COMMENTED** [review]
This looks fine so far but
1. Sentences mentioning `RepoTasks` as an exception are no longer correct
2. Suggest moving the template rebranding (`precedence` and `identity` updates) up into this section

**Review by captainsafia — APPROVED** [review]
LGTM!

Side note: the list is getting long. I wonder if it would help with readability to have headings separating the major sections instead of using sub-bullets for each section.

**Comment by wtgodbe** [comment]
> Sentences mentioning RepoTasks as an exception are no longer correct

This isn't true yet, it's still an exception until https://github.com/dotnet/aspnetcore/issues/45973 is done.

> Suggest moving the template rebranding (precedence and identity updates) up into this section

Will do

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/issues/46173

**Review by dougbu — APPROVED** [review]

**Comment by wtgodbe** [comment]
CI isn't reporting - @dotnet/dnceng is there a known outage right now?

Force-merging since this is just a change to a .md file.

**Comment by MattGal** [comment]
> CI isn't reporting - @dotnet/dnceng is there a known outage right now?
> 
> Force-merging since this is just a change to a .md file.

There was some kind of GitHub degradation going on.  Closing / reopening PRs seems to unblock it.

**Pull request merged**
