### PR TITLE
Remove unused nuget feeds

### PR DESCRIPTION
**Pull request by wtgodbe**
CC @aspnet/build 

Don't merge until we open for 3.0.2

### CODE REVIEW

**Comment by wtgodbe** [comment]
> ##[error]eng/tools/RepoTasks/RepoTasks.csproj(0,0): error NU1101: Unable to find package Internal.AspNetCore.BuildTasks

@dougbu Should we push this to one of the AzDO feeds?

**Comment by wtgodbe** [comment]
> ##[error]src\SiteExtensions\LoggingAggregate\src\Microsoft.AspNetCore.AzureAppServices.SiteExtension\Microsoft.AspNetCore.AzureAppServices.SiteExtension.csproj(0,0): error NU1101: Unable to find package Microsoft.AspNetCore.AzureAppServices.SiteExtension.2.1. No packages exist with this id in source(s): darc-pub-aspnet-AspNetCore-Tooling-7471a3d, darc-pub-aspnet-EntityFrameworkCore-be2fd3d, darc-pub-aspnet-Extensions-7dbc3eb, darc-pub-dotnet-core-setup-32085cb, darc-pub-dotnet-core-setup-7d57652, darc-pub-dotnet-core-setup-903ca49, darc-pub-dotnet-corefx-4ac4c03, dotnet-core, dotnet-tools, dotnet3, dotnet3-transport, F:\workspace\_work\1\s\artifacts\packages\Release\NonShipping\, grpc-nuget-dev, nuget.org

**Comment by wtgodbe** [comment]
@dougbu I guess `Microsoft.AspNetCore.AzureAppServices.SiteExtension.2.1` was on the AspNet myget feed. Is it suited for `dotnet-tools`/`dotnet-eng` ?

**Comment by dougbu** [comment]
> Is it suited for dotnet-tools/dotnet-eng ?

Maybe but I'm surprised it's not available on NuGet.org. May also hit issues with Microsoft.AspNetCore.AzureAppServices.SiteExtension.2.2.

Opinions / suggestions @anurse @jkotalik❔

**Review by dougbu — APPROVED** [review]
If we can get rid of `aspnetcore-dev`, wonderful. If not, do we really need 3 `darc-pub-dotnet-core-setup-{blah}` feeds?

**Comment by anurse** [comment]
And here we hit the really annoying thing about the Azure Site Extension. Since we can only ship one site extension and it has to contain the 2.1, 2.2 **and** 3.0 (and soon 3.1 and 5.0) components, the way we do it is that the 2.1/2.2 branches build and publish a partial site extension package to an internal feed (the tools feed, it turns out) and then the 3.0 build takes those along with the 3.0 content and builds a single unified package.

This is already causing problems and going to need some rethinking: https://github.com/aspnet/AspNetCore/issues/15381

**Comment by dougbu** [comment]
Apart from the #15381 issues, the site extension packages sound like candidates for the new dotnet-eng feed. That's intended to transport things that aren't specific to a TFM (whereas `dotnet3`, dotnet3.1` or `dotnet5` _are_ TFM-specific). And, it's not as overcrowded or unreliable as the old aspnetcore-dev feed.

**Comment by anurse** [comment]
Seems OK to me.

**Comment by wtgodbe** [comment]
I pushed `Microsoft.AspNetCore.AzureAppServices.SiteExtension.2.1` version `2.1.1` to dotnet-eng.

**Pull request merged**
