### PR TITLE
Changing `@functions` block to `@code` block

### PR DESCRIPTION
**Pull request by mkArtakMSFT**
Addresses https://github.com/aspnet/AspNetCore/issues/10527

### CODE REVIEW

**Comment by ryanbrandenburg** [comment]
Can we get a bit more background here? Is it the case that both will work (for a time) but we recommend `@code` over `@functions` for functional or stylistic reasons?

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg yes, both are supported, and we want to use simpler `@code` block for Blazor templates and leave `@functions` block for razor scenarios

**Review by ryanbrandenburg — COMMENTED** [review]
Looks fine to me, definitely have someone with Blazor knowledge review also though.

**Comment by rynowak** [comment]
>Can we get a bit more background here? Is it the case that both will work (for a time) but we recommend @code over @functions for functional or stylistic reasons?

`@functions` will also be supported forever. This is old Razor feature that's been around for years and we have no reason to break it.

**Comment by rynowak** [comment]
I think you may have missed the client side templates in src/Components/Blazor/Templates/src/content

**Comment by mkArtakMSFT** [comment]
Double checked and apparently I had missed just two files, but the Blazor templates have been already updated 🆙📅

**Comment by BrennanConroy** [comment]
Bad rebase?

**Comment by mkArtakMSFT** [comment]
BAD REBASE. PL:EASE HOLD OFF FROM REVIEWING - FIXING

**Pull request closed without merging**
