### PR TITLE
[WIP] Faster startline parsing

### PR DESCRIPTION
**Pull request by benaadams**
Reduce stack space used and stack used by ABI in parameter passing

Contributes to https://github.com/dotnet/aspnetcore/issues/20518

### CODE REVIEW

**Comment by benaadams** [comment]
@aspnet-hello benchmark

**Comment by benaadams** [comment]
@aspnet-hello benchmark

**Comment by benaadams** [comment]
@aspnet-hello benchmark

**Comment by benaadams** [comment]
@aspnet-hello benchmark

**Comment by benaadams** [comment]
@aspnet-hello benchmark

**Comment by benaadams** [comment]
@aspnet-hello benchmark

**Comment by benaadams** [comment]
hmm...

**Comment by benaadams** [comment]
@aspnet-hello benchmark

**Comment by benaadams** [comment]
@aspnet-hello benchmark

**Comment by benaadams** [comment]
@aspnet-hello benchmark

**Comment by benaadams** [comment]
@aspnet-hello benchmark

**Comment by benaadams** [comment]
@aspnet-hello benchmark

**Comment by davidfowl** [comment]
@benaadams Safe start line parsing next?

**Comment by benaadams** [comment]
😉

**Comment by benaadams** [comment]
> @benaadams Safe start line parsing next?

https://github.com/dotnet/aspnetcore/pull/20885

**Pull request closed without merging**
