### PR TITLE
Update Blazor icon to be .NET purple

### LINKED ISSUE #34138: Update Blazor icon
The existing Blazor icon uses wrong color purple from the old .NET branding. We should update the Blazor icon to use new .NET purple.

BrandBlazor_nohalo_128x

180px- NET_Logo svg

### PR DESCRIPTION
**Pull request by danroth27**
Fixes #34138

### CODE REVIEW

**Review by pranavkm — APPROVED** [review]
How do I know this is truly the right shade of purple?

**Review by TanayParikh — APPROVED** [review]

**Comment by mkArtakMSFT** [comment]
@dotnet/aspnet-build folks, this PR has been failing for multiple attempts already. Can someone please help with this? Thanks!

**Comment by Tratcher** [comment]
There's an ongoing network outage, I don't know that there's much we can do about it on our end.

**Comment by mkArtakMSFT** [comment]
> There's an ongoing network outage, I don't know that there's much we can do about it on our end.

Thanks @Tratcher. Understood!

**Pull request merged**
