### PR TITLE
Removed duplicated and nested dispatcher invoking.

### PR DESCRIPTION
**Pull request by nextfool**
# Removed duplicated and nested dispatcher invoking from WebViewManager
## Description
Since ```_ipcSender.NotifyUnhandledException``` already called ```dispatcher.InvokeAsync```.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=40366) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=40366) before we can accept your contribution.<br/><br/>:x: nextfool [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=40366)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=40366) it.</sub>

**Comment by pranavkm** [comment]
@nextfool can you elaborate on why this change is desirable? Nested dispatches shouldn't be a problem and this makes the code harder to follow.

**Comment by javiercn** [comment]
@nextfool thanks for the contribution.

Could you please file an issue first so that we can have some context and discuss the implications of the proposed change before moving forward?

**Comment by pranavkm** [comment]
Feel free to reopen this PR once you've had a chance to discuss the changes in an issue. Thanks!

**Pull request closed without merging**
