### PR TITLE
Add schema in launchSettings.json files

### LINKED ISSUE #38120: Document launchSettings.json
### Is your feature request related to a problem? Please describe.
The various settings in launchSettings.json are mostly undocumented. Many are self explanatory but some are not. It's not clear what some of them do. E.g. `dotnetRunMessages` is only documented here:

- https://github.com/dotnet/aspnetcore/issues/32273

In particular, I'm personally interested in a new setting called `useSSL` used when Docker is added:

```
"Docker": {
    "commandName": "Docker",
    "launchBrowser": true,
    "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}/swagger",
    "publishAllPorts": true,
    "useSSL": true
}
```

### Describe the solution you'd like
Please add a documentation page documenting each and every setting in launchSettings.json

### PR DESCRIPTION
**Pull request by sebastienros**
Fixes #38120

Complementary to https://github.com/SchemaStore/schemastore/pull/2507

### CODE REVIEW

**Comment by JamesNK** [comment]
I'm not sure if this is the right approach. `appsettings.json`, for example, has the schema automatically inferred by VS and VS code.

Change to the VS code extension for that: https://github.com/OmniSharp/omnisharp-vscode/pull/4280. There was a similar change in VS.

Do we want the schema added to these files, or should it be consistent with what `appsettings.json` does?

**Comment by sebastienros** [comment]
@JamesNK it's nice that the tooling can infer the schema, but I don't think it's contradicting this PR. If someone uses another tool, let's say Rider, or VS for MAC (not sure it does it too). And assuming adding the schema in the templates don't conflict with the tooling.

One template already had the reference, so if we decide to not add the schema then I will remove it from there (https://github.com/dotnet/aspnetcore/blob/91271151f6c4363606ad3520526192a8f7c7292b/src/ProjectTemplates/Web.ProjectTemplates/content/WebApi-CSharp/Properties/launchSettings.json#L2)

In any case we can also ponder if launchSettings support should be added to tooling too.

**Comment by JamesNK** [comment]
Another thing to consider is the schema file that VS generates if one isn't present. I tested deleting the file and restarting VS, and the newly generated launchSettings.json doesn't have a $schema property.

**Comment by sebastienros** [comment]
Should we just discard this PR then and assume that the issue is fixed as we updated the schema to add more properties?

I see that the changes I pushed on the schema are actually already working in VS, and it's inferred:

image

**Comment by JamesNK** [comment]
> Should we just discard this PR then and assume that the issue is fixed as we updated the schema to add more properties?

Yeah, I think so. Although it sounds like one launchSettings.json is specifying the schema. Remove it from that one for consistency?

**Comment by sebastienros** [comment]
Found 4 files with it, 2 sample and 2 templates

**Comment by sebastienros** [comment]
@JamesNK GTG?

**Review by JamesNK — APPROVED** [review]

**Comment by sebastienros** [comment]
https://github.com/orgs/dotnet/teams/aspnet-build please merge

**Pull request merged**
