### PR TITLE
Fix RCL template to have correct filename for scoped CSS

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
I noticed this while doing some other test updates. In case you're wondering why we don't have test coverage that caught this, [we actually do, here](https://github.com/dotnet/aspnetcore/blob/release/5.0-rc2/src/ProjectTemplates/test/template-baselines.json#L882), but looks like those template baseline tests aren't running.

## Description

Not sure how it happened, perhaps a bad rebase, but at some point before https://github.com/dotnet/aspnetcore/pull/25613 was merged, one of the changes in it got lost. The `wwwroot/styles.css` file was meant to have been moved to `Component1.razor.css` (and a comment in it was meant to have been removed due to it not really serving a purpose).

This definitely was the case at some point as I remember verifying it. However it's clearly not there in the final PR that was merged. **Update:** root-cause explanation in later comment.

## Customer Impact

Unless fixed, the RCL template won't use scoped CSS as clearly intended, and it will make no sense why.

Developers consuming RCLs will have to take extra steps to use them (i.e., add `<link>` tags pointing to their styles).

The styling in the RCL won't be scoped as intended.

## Regression?

No

## Risk

No. As long as the broader CSS isolation feature works correctly (which we are already counting on), then using that feature here presents no extra risk.

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
Update: I've tracked down how this happened. Via `git reflog`, I see that I did do a manual rebase using `cherry-pick` and misunderstood the `git cherry-pick <hash1>...<hash2>` syntax. It only includes the changes *after* `hash1`, and hence I lost the first commit in the range I intended to pick.

**Review by mkArtakMSFT — APPROVED** [review]
Thanks for tracking this down, Steve!

**Comment by SteveSandersonMS** [comment]
What's the approval process for RC2 now, @mkArtakMSFT? Does @Pilchie still approve or does this need to go through tactics now?

**Comment by Pilchie** [comment]
I'll let this one squeak by, but from now on we'll go through Tactics.

**Comment by Pilchie** [comment]
Approved for .NET 5 RC2.

**Comment by Pilchie** [comment]
Sorry for the close/re-open :(  This did pass CI before, so we could skip it this time if we wanted to.

**Pull request merged**
