### PR TITLE
Turn HTTP/3 on by default in Kestrel

### LINKED ISSUE #36486: HTTP/3: Enable in Kestrel by default
Turn on HTTP/3 by default in .NET 7, i.e. default protocol is `Http1AndHttp2AndHttp3`. 🌶️ 🔥 💥

Should do this sooner rather than later to get feedback in .NET 7 previews.

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/aspnetcore/issues/36486

### CODE REVIEW

**Comment by Tratcher** [comment]
Should we try to fix https://github.com/dotnet/aspnetcore/issues/41762 first?

**Comment by JamesNK** [comment]
It falls back silently.

**Review by Tratcher — APPROVED** [review]

**Comment by Eagle3386** [comment]
@JamesNK I'm a bit confused: while it does state `Merged into main` since almost a year ago, even the current `main`-branch as of now still hasn't enabled HTTP/3 in Kestrel by default:
https://github.com/dotnet/aspnetcore/blob/c1b76241bf4043e3e54edbb236963c503eec18e0/src/Servers/Kestrel/Core/src/ListenOptions.cs#L19

Furthermore, if I explicitly go to the commit's "branch", it reads as follows:
> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

Therefore, I'd like to know what happened & what's the plan for going forward with Kestrel & "HTTP/3 on by default"?

**Comment by JamesNK** [comment]
It was later turned off by default because anti-virus would always prompt for HTTP/3 endpoints.

You can still configure Kestrel to turn HTTP/3 on if you want to use it.

**Comment by Eagle3386** [comment]
Thanks, but are there plans to re-enable this by default at some future point (.NET 9/10) or will it remain like it's now?

**Pull request merged**
