### PR TITLE
Revert "Revert "Improve components infrastructure (#12145)" (#12679)"

### PR DESCRIPTION
**Pull request by JunTaoLuo**
This reverts commit e2d57e2806eeeedd91400665985996706ac3ac71.

As per meeting discussion, this is the approach we would like to take for source build as well. However, there will likely be pieces of the infrastructure that needs to be modified (e.g. not redistributing yarn binaries) but we'll address those separately. 

I'm adding the original changes to preview 9 for improving workflow.

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
Has anything changed in this since the original PR? If yes, where should we dive deeper?

**Comment by rynowak** [comment]
`revert revert` is the best kind of revert. Prove me wrong.

**Comment by JunTaoLuo** [comment]
I'm going to update with a few more details on how I intend for this to work when all tests come back clean but I believe this is close to ready.

**Review by dougbu — APPROVED** [review]
Still looks good.

**Comment by JunTaoLuo** [comment]
Here's a few of the common scenarios and how it will work when you run build by default (i.e. without specifying BuildNodeJs or NoBuildNodeJS):

Scenario | node installed | no node
-- | -- | --
build.cmd in root | builds dependent npm projects | uses checked in assets if available, displays warning
build.cmd in src/Components | builds dependent npm projects | uses checked in assets if available, displays warning
dotnet build on   Microsoft.AspNetCore.Components.Server | builds dependent npm projects | uses checked in assets if available, displays warning
yarn run build on   Web.JS npmproj | does not build dependent projects | fails

With explicit specification of BuildNodeJs:
The dependent npm projects will be built if node is available on the path and the build will fail if it's not.

With explicit specification of NoBuildNodeJs:
The dependent npm projects will not be built and the JS artifacts from previous builds will be used. If the JS artifacts are not present (only the release versions are checked into source control) the build will fail

**Comment by halter73** [comment]
@rynowak, @pranavkm calls your `revert revert` and raises to [revert revert revert](https://github.com/aspnet/Extensions/commit/c5f4ba2c0c8ebbd49bf707890c20e6d2cd7fe67d).

**Comment by rynowak** [comment]
Dank.

**Comment by JunTaoLuo** [comment]
Revertception
image

**Pull request merged**
