### PR TITLE
Try newer helix sdk

### PR DESCRIPTION
**Pull request by HaoK**

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
The Helix job likely failed because some dependencies moved on. I retried the job.

If the retry passes, you're good to go :shipit:
If not, I suggest not making any changes until we have something that passes reliably

**Comment by HaoK** [comment]
@dougbu What do you mean about dependencies moving on exactly?

**Comment by dougbu** [comment]
@HaoK I saw warnings in the previous Azure Pipelines run that mentioned differing versions. Those types of warnings sometimes clear in a rerun and avoid any errors.

In this case, the same failures occurred in the rerun. The error is probably in the configuration you changed:
```
D:\a\1\s\.dotnet\x64\sdk\3.0.100-preview-009750\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FSharp.targets(29,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\FSharp\Microsoft.FSharp.NetSdk.targets" cannot be imported again. It was already imported at "D:\a\1\s\.dotnet\x64\sdk\3.0.100-preview-009750\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FSharpTargetsShim.targets (63,3)". This is most likely a build authoring error. This subsequent import will be ignored. [D:\a\1\s\src\Mvc\test\WebSites\FSharpWebSite\FSharpWebSite.fsproj]
D:\a\1\s\.dotnet\x64\sdk\3.0.100-preview-009750\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FSharp.targets(29,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\FSharp\Microsoft.FSharp.NetSdk.targets" cannot be imported again. It was already imported at "D:\a\1\s\.dotnet\x64\sdk\3.0.100-preview-009750\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FSharpTargetsShim.targets (63,3)". This is most likely a build authoring error. This subsequent import will be ignored. [D:\a\1\s\src\Mvc\test\WebSites\FSharpWebSite\FSharpWebSite.fsproj]
D:\a\1\s\eng\targets\ResolveReferences.targets(186,5): warning : Package references changed since the last release. This could be a breaking change. References removed: [D:\a\1\s\src\SignalR\clients\csharp\Client.Core\src\Microsoft.AspNetCore.SignalR.Client.Core.csproj]
D:\a\1\s\eng\targets\ResolveReferences.targets(186,5): warning :  - Microsoft.AspNetCore.SignalR.Protocols.Json [D:\a\1\s\src\SignalR\clients\csharp\Client.Core\src\Microsoft.AspNetCore.SignalR.Client.Core.csproj]
D:\a\1\s\eng\targets\ResolveReferences.targets(186,5): warning : Package references changed since the last release. This could be a breaking change. References removed: [D:\a\1\s\src\SignalR\common\SignalR.Common\src\Microsoft.AspNetCore.SignalR.Common.csproj]
D:\a\1\s\eng\targets\ResolveReferences.targets(186,5): warning :  - Newtonsoft.Json [D:\a\1\s\src\SignalR\common\SignalR.Common\src\Microsoft.AspNetCore.SignalR.Common.csproj]
D:\a\1\s\eng\targets\ResolveReferences.targets(186,5): warning : Package references changed since the last release. This could be a breaking change. References removed: [D:\a\1\s\src\SignalR\common\Http.Connections.Common\src\Microsoft.AspNetCore.Http.Connections.Common.csproj]
D:\a\1\s\eng\targets\ResolveReferences.targets(186,5): warning :  - Newtonsoft.Json [D:\a\1\s\src\SignalR\common\Http.Connections.Common\src\Microsoft.AspNetCore.Http.Connections.Common.csproj]
D:\a\1\s\eng\targets\ResolveReferences.targets(186,5): warning : Package references changed since the last release. This could be a breaking change. References removed: [D:\a\1\s\src\SignalR\clients\csharp\Client.Core\src\Microsoft.AspNetCore.SignalR.Client.Core.csproj]
D:\a\1\s\eng\targets\ResolveReferences.targets(186,5): warning :  - Microsoft.AspNetCore.SignalR.Protocols.Json [D:\a\1\s\src\SignalR\clients\csharp\Client.Core\src\Microsoft.AspNetCore.SignalR.Client.Core.csproj]
D:\a\1\s\eng\targets\ResolveReferences.targets(186,5): warning : Package references changed since the last release. This could be a breaking change. References removed: [D:\a\1\s\src\SignalR\common\SignalR.Common\src\Microsoft.AspNetCore.SignalR.Common.csproj]
D:\a\1\s\eng\targets\ResolveReferences.targets(186,5): warning :  - Newtonsoft.Json [D:\a\1\s\src\SignalR\common\SignalR.Common\src\Microsoft.AspNetCore.SignalR.Common.csproj]
D:\a\1\s\eng\targets\ResolveReferences.targets(186,5): warning : Package references changed since the last release. This could be a breaking change. References removed: [D:\a\1\s\src\SignalR\common\Http.Connections.Common\src\Microsoft.AspNetCore.Http.Connections.Common.csproj]
D:\a\1\s\eng\targets\ResolveReferences.targets(186,5): warning :  - Newtonsoft.Json [D:\a\1\s\src\SignalR\common\Http.Connections.Common\src\Microsoft.AspNetCore.Http.Connections.Common.csproj]
D:\a\1\s\.nuget\packages\microsoft.dotnet.helix.sdk\2.0.0-beta.19105.2\tools\Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(51,5): error : SendHelixJob given no WorkItems to send. [D:\a\1\s\eng\helix\helix.proj]
```

**Comment by HaoK** [comment]
Ah yeah so I think the issue is more that something changed in the helix SDK that we need to respond to, since its not picking up any of our work items anymore:

```
D:\a\1\s\.nuget\packages\microsoft.dotnet.helix.sdk\2.0.0-beta.19105.2\tools\Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(51,5): error : SendHelixJob given no WorkItems to send. [D:\a\1\s\eng\helix\helix.proj]
```

That's the real error, it doesn't show up if we keep using the older version of the helix sdk.  This PR is trying to verify that the new parallel upload feature works for us

**Comment by alexperovich** [comment]
@HaoK yes the helix sdk stuff changed a bit. I think it will work if you change the BeforeTargets of the "Gather" target to "Build". The specific change that is causing the problem is that the jobs are send in the CoreTest target now, rather than in the Test target. This causes the send to happen before your "Gather" target. From what I can see of your project, "Gather" should run before Build.

**Comment by HaoK** [comment]
Cool @alexperovich that looks like it was the issue

**Comment by HaoK** [comment]
@alexperovich @MattGal Do you guys know why the arm queues might be timing out/hanging?  everything else was green but the arm queues timed out after 4 hours and it doesn't look like any of them reported results...

https://mc.dot.net/#/user/aspnetcore/pr~2Faspnet~2Faspnetcore/ci/20190219.36

**Comment by MattGal** [comment]
@HaoK Looks like all those machines died around the same 30 minute period.  I've reached out to the DDFUN folks to see if they know what's up and filed https://github.com/dotnet/core-eng/issues/5261

**Pull request closed without merging**
