### PR TITLE
Remove try/catch around IsSupported property

### LINKED ISSUE #41042: HTTP/3: Remove try/catch around IsSupported property
Steve added try/catch here https://github.com/dotnet/aspnetcore/pull/40376

IsSupported no longer throws: https://github.com/dotnet/runtime/pull/67036

Try/catch can be removed.

### PR DESCRIPTION
**Pull request by samiizadeh**
## Description

Remove try/catch around IsSupported property

Fixes #41042

### CODE REVIEW

**Comment by JamesNK** [comment]
@SteveSandersonMS IsSupported for QUIC has been updated to no longer throw on unsupported platforms: https://github.com/dotnet/runtime/pull/67036

Is there a simple way for you to test/verify? I'd hate to remove the try/catch just to break your scenario again.

**Review by SteveSandersonMS — APPROVED** [review]
@JamesNK Thanks for checking. Yes, it appears to work fine without the try/catch now.

This is based on me manually building stuff and overwriting assemblies in my local SDK, so it's possible I got something wrong, but it did just work so I'm reasonably confident.

**Comment by mkArtakMSFT** [comment]
Thanks for your contribution, @samiizadeh!

**Comment by delneg** [comment]
@mkArtakMSFT , @SteveSandersonMS 
Trying to run Wasi SDK code, experiencing this again with both net7.0-preview4 and .net7.0-preview5 daily (`7.0.100-preview.5.22267.11` to be exact) on macOS x64


```
System.PlatformNotSupportedException: System.Net.Quic is not supported on this platform.
   at System.Net.Quic.QuicImplementationProviders.get_Default()
   at Microsoft.AspNetCore.Hosting.WebHostBuilderQuicExtensions.UseQuic(IWebHostBuilder hostBuilder)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderKestrelExtensions.UseKestrel(IWebHostBuilder hostBuilder)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderKestrelExtensions.UseKestrel(IWebHostBuilder hostBuilder, Action`1 options)
   at Program.main(String[] args)
```

**Comment by JamesNK** [comment]
@SteveSandersonMS Could you double check whether this is working or not?

**Comment by delneg** [comment]
Upd: I've tried preview 3 (as mentioned here https://www.strathweb.com/2022/03/running-net-7-apps-on-wasi-on-arm64-mac/) and it works fine with `7.0.100-preview.3.22179.4 for me`, but not with `7.0.100-preview.4.22252.9` or `7.0.100-preview.5.22267.11` - all of that tested on macOS x64

**Comment by rzikm** [comment]
@delneg Can build the app as self-contained and check the System.Net.Quic.dll deployed to the publish directory with ILSpy? Even for unsupported platforms, the `System.Net.Quic.QuicImplementationProviders.Default` property should not throw.

**Comment by SteveSandersonMS** [comment]
> [James] Could you double check whether this is working or not?

Yes, it's working for me on 7.0.100-preview.4.22252.9. Verified on Windows and Linux (Ubuntu in WSL2).

@rzikm To diagnose, I'd recommend:

 * Clean your project (remove `bin` and `obj` dirs completely)
 * Build using `dotnet build /bl`
 * Assuming it's still not working, upload the generated `msbuild.binlog` file somewhere that we can have a look

**Comment by delneg** [comment]
FYI Just tested on macOS arm64 (M1) with preview4, also doesn't work

```
➜  Project git:(master) dotnet --version
7.0.100-preview.4.22252.9
➜  Project git:(master) uname -a
Darwin hostname.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 arm64
```

**Comment by delneg** [comment]
> @delneg Can build the app as self-contained and check the System.Net.Quic.dll deployed to the publish directory with ILSpy? Even for unsupported platforms, the `System.Net.Quic.QuicImplementationProviders.Default` property should not throw.

I've tried building with `dotnet publish --self-contained true`
and got 
`-rwxr--r--    1 user  staff   361K Apr 30 00:42 System.Net.Quic.dll`
in `bin/Debug/net7.0/osx-arm64/publish/` directory.

I'm not sure what ILSpy should be used for (and how, never used it) though

**Comment by delneg** [comment]
@SteveSandersonMS Thanks, I can confirm that the issue was indeed related to Wasi.Sdk

Now it works for me on macOS x64 with 7.0.100-preview.5.22267.11

**Pull request merged**
