### PR TITLE
Added `WebAssembly` capability to Blazor WebAssembly projects

### LINKED ISSUE #28716: Add a unique capability to Blazor WebAssembly SDK
This is needed for VS to light-up certain experiences for WebAssembly projects correctly.
As of right now, when trying to add gRPC service reference in a Blazor WebAssembly project, VS will end up adding wrong package references. That's because it think these are usual ASP.NET Web projects.

### PR DESCRIPTION
**Pull request by mkArtakMSFT**
## Description

VS has a feature of adding gRPC service reference to a project using UI. Currently that experience has no easy way to differentiate between Blazor Server and Blazor WebAssembly projects. As a result, adding gRPC reference using VS feature adds the wrong gRPC package (Grpc.AspNetCore), instead of adding `Grpc.Net.Client` and `Grpc.Net.Client.Web`, per our documentation. The package which is wrong adds framework reference transitively, which is not supported on WebAssembly.

This change adds a unique WebAssembly capability to all Blazor WebAssembly projects (through the SDK) so VS can build unique experiences those projects and also address that bug.

## Customer Impact
This particular change has no customer impact, but it will enable VS to fix their experience tracked by [this AzDO issue](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1242008)

## Regression?
- [ ] Yes
- [x] No

## Risk
- [ ] High
- [ ] Medium
- [x] Low

[Justify the selection above]

## Verification
- [ ] Manual (required)
- [ ] Automated

Not applicable as this change has no functional impact. The follow-up change is on the VS side to utilize this change and differentiate projects.

## Packaging changes reviewed?
- [ ] Yes
- [ ] No
- [x] N/A

Addresses https://github.com/dotnet/aspnetcore/issues/28716

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
@BillHiebert can you please confirm this is what you are looking for to fix the gRPC reference issue in VS?

**Comment by mkArtakMSFT** [comment]
@vijayrkn looks like @BillHiebert is out. Please assign someone to review this. Thanks!

**Review by vijayrkn — APPROVED** [review]

**Comment by mkArtakMSFT** [comment]
@wtgodbe I should merge this?

**Comment by wtgodbe** [comment]
> @wtgodbe I should merge this?

Not yet, branches don't open until Tuesday

**Pull request merged**
