### PR TITLE
Dynamically install NGinx

### PR DESCRIPTION
**Pull request by Tratcher**
https://github.com/aspnet/AspNetCore-Internal/issues/1525

Poached these from our old travis yml. Let's see if they work...

### CODE REVIEW

**Comment by pakrym** [comment]
```

2018-12-20T22:04:32.0950396Z cc1: all warnings being treated as errors
2018-12-20T22:04:32.0985471Z objs/Makefile:754: recipe for target 'objs/src/event/ngx_event_openssl.o' failed
2018-12-20T22:04:32.1027473Z make[1]: Leaving directory '/tmp/nginx-1.8.0'
2018-12-20T22:04:32.1028019Z make[1]: *** [objs/src/event/ngx_event_openssl.o] Error 1
2018-12-20T22:04:32.1028594Z Makefile:12: recipe for target 'install' failed
2018-12-20T22:04:32.1028874Z make: *** [install] Error 2
```

**Comment by Tratcher** [comment]
I ran out of time and opted to disable the nginx tests. I left my changes as they were working on mac. Linux needs work. The install succeeded but the test still couldn't find nginx for some reason.

**Review by pakrym — APPROVED** [review]
Either merge scripts or skip condition no need to have both

**Comment by Tratcher** [comment]
Take your pick. I'm off for the rest of the year so someone please merge this.

**Comment by pakrym** [comment]
I'll take this.

**Pull request merged**
