### PR TITLE
[SignalR] Add Http options to Negotiate endpoint metadata

### LINKED ISSUE #35544: [SignalR] Provide a way for Azure SignalR to read HttpConnectionDispatcherOptions
### Current issue
SignalR provided a auth expiration feature in [Close connection on auth expiration by BrennanConroy · Pull Request #32431](https://github.com/dotnet/aspnetcore/pull/32431), however, the option `CloseOnAuthenticationExpiration` is in `HttpConnectionDispatcherOptions`, this is one Option that Azure SignalR SDK is **not** able to fetch out value from.

A similar issue we encountered before is the `TransportType` option, since we are not able to fetch the `TransportType` value out from the option, we add a [similar option in Service SDK](https://github.com/Azure/azure-signalr/pull/1365#issuecomment-888017659)

### Proposed solution
It would be great if there is a way for the Azure SignalR SDK to read `HttpConnectionDispatcherOptions`, so that we don't need to create a similar option in the service SDK and users don't need to set a similar Option when using service SDK.

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/dotnet/aspnetcore/issues/35544

### CODE REVIEW

**Comment by davidfowl** [comment]
Can't you do this without adding new APIs?

**Comment by BrennanConroy** [comment]
Yes, I called that out in the PR comment.

**Review by davidfowl — APPROVED** [review]

**Comment by davidfowl** [comment]
@vicancy before we merge this, make sure it's workable.

**Review by vicancy — APPROVED** [review]
Looks cool to me. Adding @Y-Sindo to confirm

**Review by Y-Sindo — APPROVED** [review]

**Pull request merged**
