### PR TITLE
Only run selenium tests when build java is specified

### PR DESCRIPTION
**Pull request by JunTaoLuo**
Addresses https://github.com/aspnet/AspNetCore/issues/10504

### CODE REVIEW

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
More Ubuntu `inotify` failures in Helix runs ☹️

**Comment by JunTaoLuo** [comment]
Yea there are a few tracking issues on the inotify issue already. cc @javiercn are you looking into those?

**Comment by javiercn** [comment]
Yes, I have a PR out, although looking at my changes I don’t know how they caused it.

**Comment by pranavkm** [comment]
I'm doing the egregious sin of commenting on a closed PR. But with this change, I can't do `dotnet test` on the Component's E2E tests anymore since `BuildJava` isn't defined by default. Should the test here be:

``$(BuildJava)` != "false"` so it's only skipped when we explicitly say we do not require Java? Right now, there's a risk that the tests never run if the flag isn't set. What do you folks think?

**Comment by dougbu** [comment]
`dotnet test /p:BuildJava=true`

**Pull request merged**
