### PR TITLE
Unquarantine controller test

### LINKED ISSUE #24414: Test DefaultControllerFactory_DelegatesDisposalToControllerActivator fails
Failed here: https://dev.azure.com/dnceng/public/_build/results?buildId=749131&view=results

> System.BadImageFormatException : Bad IL format.

> at Castle.Proxies.IControllerActivatorProxy.Release(ControllerContext context, Object controller)
   at Microsoft.AspNetCore.Mvc.Controllers.DefaultControllerFactory.ReleaseController(ControllerContext context, Object controller) in /_/src/Mvc/Mvc.Core/src/Controllers/DefaultControllerFactory.cs:line 84
   at Microsoft.AspNetCore.Mvc.Controllers.DefaultControllerFactoryTest.DefaultControllerFactory_DelegatesDisposalToControllerActivator() in /_/src/Mvc/Mvc.Core/test/Controllers/DefaultControllerFactoryTest.cs:line 199

### PR DESCRIPTION
**Pull request by HaoK**
Fixes https://github.com/dotnet/aspnetcore/issues/24414

30 day 100% 690/690

### CODE REVIEW

**Comment by HaoK** [comment]
Underling lying exception was: 

```
System.BadImageFormatException : Bad IL format.

at Castle.Proxies.IControllerActivatorProxy.Release(ControllerContext context, Object controller)
```

which doesn't seem likely to be something specific to this test

**Review by pranavkm — APPROVED** [review]

**Comment by pranavkm** [comment]
Yup, there's a race condition in CastleCore which shows up once in a blue moon.

**Comment by BrennanConroy** [comment]
> shows up once in a blue moon

Well there is a blue moon in 2 weeks. On a more serious note, can we avoid using Mock if we know it causes flakiness?

**Comment by HaoK** [comment]
Filed https://github.com/dotnet/aspnetcore/issues/27042 for the larger issue, merging this for now

**Pull request merged**
