### PR TITLE
Use new string.Split() overloads

### PR DESCRIPTION
**Pull request by martincostello**
* Use new `string.Split()` overloads to remove need to allocate arrays.
  * Use static array for new line characters in `HtmlEncodeAndReplaceLineBreaks()` instead of allocating a new one each time.

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]

**Comment by Tratcher** [comment]
Thanks

**Comment by GrabYourPitchforks** [comment]
Related: You should also take a look at https://github.com/dotnet/runtime/pull/35740 and https://github.com/GrabYourPitchforks/aspnetcore/commit/bbf393fae8d940122eda8831952338a2539ab707 if you're trying to clean up these code paths a bit.

**Comment by martincostello** [comment]
Ah nice, I wasn't aware of that incoming. Looks like one of these changes could be refactored to use the new enum member.

**Comment by martincostello** [comment]
Ah wait, I noticed you already did it in the referenced commit 😃

**Comment by GrabYourPitchforks** [comment]
Yup. Feel free to send a new PR and improve upon it however you see fit.

**Comment by martincostello** [comment]
> Yup. Feel free to send a new PR and improve upon it however you see fit.

Done - #23712

**Pull request merged**
