### PR TITLE
Make incorrect password error message consistent (#9556)

### PR DESCRIPTION
**Pull request by wenz**
Changing the error message

Addresses #9556

### CODE REVIEW

**Comment by Eilon** [comment]
Wow, so quick to send a PR! Thank you!

**Review by blowdart — APPROVED** [review]
LGTM

**Comment by HaoK** [comment]
Closing/reopening to retrigger checks

**Comment by HaoK** [comment]
Replaced by https://github.com/aspnet/AspNetCore/pull/9561 which rebases against master

**Comment by HaoK** [comment]
This has been merged, thanks @wenz !

**Pull request closed without merging**
