### PR TITLE
Port of Bootstrap v4 SxS support to 7.0

### PR DESCRIPTION
**Pull request by HaoK**
Cherry-pick of https://github.com/dotnet/aspnetcore/commit/77d5fbb6d8d5dc9c14858705765e9b30d3bcbb8f

### CODE REVIEW

**Comment by wtgodbe** [comment]
Was this already reviewed in 6.0?

**Comment by HaoK** [comment]
Yep, this is just a port forward, so there's nothing new to review

**Review by wtgodbe — APPROVED** [review]

**Comment by dougbu** [comment]
I told AzDO to rerun the failed jobs because we have some evidence the agent acquisition problem has cleared up.

Separately, why was this work done first in release/6.0❔ I see things started in 'main' but further work was done for 6.0 instead of there.

**Comment by HaoK** [comment]
There was SDK changes that were only in release/6.0 which this work depended on

**Pull request merged**
