### PR TITLE
Turn SETLOCAL on so that we don't accumulate in the PATH

### PR DESCRIPTION
**Pull request by cshung**
Summary of the changes (Less than 80 chars)
 - Constraint the environment change to stay inside the script by adding [SETLOCAL](https://ss64.com/nt/setlocal.html) in the `startvs.cmd` 
 - I tested, the normal workflow using `startvs.cmd` still works, and the shell environment no longer contains duplicated paths.

Addresses #10501  (in this specific format)

### CODE REVIEW

**Comment by dougbu** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=199170

**Comment by dougbu** [comment]
Retried the Code check job. It failed with a very strange error that _should_ be unrelated to the one-line change in this PR.

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build.

**Review by natemcmaster — APPROVED** [review]
Thanks @cshung!

**Comment by dougbu** [comment]
More Helix timeouts that can't be related to this one-line change

**Pull request merged**
