### PR TITLE
Change middleware projects to target netcoreapp3.0

### PR DESCRIPTION
**Pull request by Tratcher**
#3754 Blocked on IIS https://github.com/aspnet/AspNetCore/pull/4371.

### CODE REVIEW

**Review by JunTaoLuo — APPROVED** [review]
When tests pass

**Comment by natemcmaster** [comment]
We're adding required PR checks to ensure the repo compiles before you merge. Can you update this PR by rebasing on master?

```
git fetch origin master:master
git rebase master
```

Alternative: if you plan to 'squash merge' this PR, you can also use a merge to update this PR. This can be easier to manage if you have lots of changes in this PR.
```
git fetch origin master:master
git merge master
```

**Comment by Tratcher** [comment]
Rebased. I've opted to skip ForwardedHeaders for now as that's blocked on IIS. Getting ResponseCompression up to 3.0 unblocks some feature work I'd like to start.

**Comment by Tratcher** [comment]
Nope, IIS tests also depend on ResponseCompression ....

**Pull request merged**
