### PR TITLE
[release/6.0] Try skipping tests with Japanese chars

### PR DESCRIPTION
**Pull request by wtgodbe**
Seeing if this fixes the issue seen in https://github.com/dotnet/aspnetcore/pull/47545#issuecomment-1496219366

### CODE REVIEW

**Comment by wtgodbe** [comment]
Passed on macOS-11.7.1, trying again

**Comment by BrennanConroy** [comment]
11.6.8 passed: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-pull-47560-merge-13ae8898bf4848d8b4/Microsoft.AspNetCore.SignalR.Common.Tests--net6.0/1/console.e00fc879.log?helixlogtype=result

**Comment by wtgodbe** [comment]
@BrennanConroy could you review?

**Review by sebastienros — APPROVED** [review]

**Pull request merged**
