### PR TITLE
[release/5.0-preview1] Merge the mega merge

### PR DESCRIPTION
**Pull request by dougbu**
- merge the mega merge (and more) into 5.0-preview1
- 188 commits 😺

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]
Merge Simpson

**Comment by jkotalik** [comment]
> Merge Simpson

I laughed at this way too much.

**Comment by dougbu** [comment]
> I laughed at this way too much.

I cried

**Comment by dougbu** [comment]
@JunTaoLuo this means your extensions work is unblocked❕

**Comment by JunTaoLuo** [comment]
Merge-it Thatcher approves 👍

**Pull request merged**
