### PR TITLE
Slow things down

### PR DESCRIPTION
**Pull request by halter73**
Summary of the changes (Less than 80 chars)
 - Detail 1
 - Detail 2

Addresses #bugnumber (in this specific format)

### CODE REVIEW

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by davidfowl** [comment]
@aspnet-hello benchmark

**Comment by davidfowl** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Pull request closed without merging**
