### PR TITLE
update IdentityModel to latest

### PR DESCRIPTION
**Pull request by jennyf19**
# Update Microsoft.IdentityModel to latest 7.4.1

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Description

7.4.1 includes this fix: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2412 as well as several other bugs and perf improvements since 7.1.2. [Release notes for details](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases)

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
@jennyf19 are there any breaking changes in this release? If not, I wonder if this is something we should try to port to 8?
@halter73 what do you think?

**Comment by wtgodbe** [comment]
We need a corresponding source-build-externals update before taking this

**Comment by jennyf19** [comment]
> @jennyf19 are there any breaking changes in this release? If not, I wonder if this is something we should try to port to 8? @halter73 what do you think?

No breaking changes, but a lot of bug fixes.

**Comment by jennyf19** [comment]
> We need a corresponding source-build-externals update before taking this

Yes, thanks @wtgodbe ...is that something you can help with?

**Comment by wtgodbe** [comment]
https://github.com/dotnet/source-build-externals/pull/293 will need to be merged, then we'll need to take an update from source-build-externals

**Comment by jennyf19** [comment]
@wtgodbe will this still make it in?

**Comment by martincostello** [comment]
As latest is now 7.5.0, should there be a further update?

**Comment by wtgodbe** [comment]
Working on getting https://github.com/dotnet/source-build-externals/pull/293 green now

**Comment by wtgodbe** [comment]
https://github.com/dotnet/source-build-externals/pull/293 is merged, next dependency flow from that repo should unblock this

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/pull/54890 will update the IdentityModel version when merged into `main`

**Comment by wtgodbe** [comment]
Done!

**Pull request merged**
