### PR TITLE
To get host address in Configure method of Startup class

### PR DESCRIPTION
**Pull request by lenixsss**
When you need to know the host address while configuring

### CODE REVIEW

**Comment by mitchdenny** [comment]
Can you please open up an API proposal issue for this using the following template:

https://github.com/dotnet/aspnetcore/issues/new?assignees=&labels=api-suggestion&template=30_api_proposal.md&title=

**Comment by Tratcher** [comment]
This approach is IIS specific and should be avoided. 

Why do you need to know the host address during configuration? Most operations should be host relative.

**Comment by lenixsss** [comment]
It is needed when I want to create scheduled job that send requests to the controller

**Comment by davidfowl** [comment]
I think this is fine, but I'm not sure why we would expose this from options, can't you resolve the `IServer` and get it from there or is that too late?

**Comment by lenixsss** [comment]
> I think this is fine (because your code is making the assumption so it's fragile but in your code base), but I'm not sure why we would expose this from options, can't you resolve the `IServer` and get it from there or is that too late?

How can I get Host-address using IServer before calling Microsoft.AspNetCore.Builder.WebApplication.Run method?

**Comment by davidfowl** [comment]
Can you show where you are using it?

**Comment by adityamandaleeka** [comment]
It's been a few days since the last activity on this PR, and we're unlikely to take this change in its current form anyway (see comments above).

@lenixsss If you're still interested in this, feel free to open an issue where we can discuss it further with you. As @mitchdenny pointed out above, there is also an API proposal/review process we use to ensure that API changes go through some considered scrutiny before merging.

**Pull request closed without merging**
