### PR TITLE
Add SignIn method without authentication scheme

### LINKED ISSUE #23325: Inconsistent requirement to specify auth scheme
MVC provides several ActionResults for interacting with the authentication infrastructure.
- ChallengResult
- ForbidResult
- SignInResult
- SignOutResult

These mirror and call similar methods on the HttpContext:
https://github.com/dotnet/aspnetcore/blob/5155e11120cf7ee2e07383225057f66512f00fde/src/Http/Authentication.Abstractions/src/AuthenticationHttpContextExtensions.cs

Problem: These results and their associated methods are inconsistent about their requirement to specify the AuthenticationScheme. E.g. ChallengeResult, ForbidResult, and SignOutResult do not require an auth scheme to be specified, but SignInResult does. The authentication scheme is optional on all of the underlying HttpContext APIs, falling back to the application defaults for each.

Proposal: AuthenticationScheme should be optional for SignInResult as well, and ControllerBase should add the appropriate overload to match.
```
        // Existing
        public virtual SignInResult SignIn(ClaimsPrincipal principal, AuthenticationProperties properties, string authenticationScheme);
        public virtual SignInResult SignIn(ClaimsPrincipal principal, string authenticationScheme);
        // New
        public virtual SignInResult SignIn(ClaimsPrincipal principal, AuthenticationProperties properties);
        public virtual SignInResult SignIn(ClaimsPrincipal principal);
```

This makes the APIs consistent and reduces the verbosity in the Actions.

Example in the wild:
https://github.com/AzureAD/microsoft-identity-web/blob/17f48c62410e08ea0d4c1fdb4f15a0713ed7f00c/src/Microsoft.Identity.Web.UI/Areas/MicrosoftIdentity/Controllers/AccountController.cs#L41-L48

### PR DESCRIPTION
**Pull request by Kahbazi**
Fixes https://github.com/dotnet/aspnetcore/issues/23325

### CODE REVIEW

**Comment by Kahbazi** [comment]
@Tratcher Do I need to have the latest preview version of Visual Studio in order to generate the reference assemblies?

**Comment by Tratcher** [comment]
> @Tratcher Do I need to have the latest preview version of Visual Studio in order to generate the reference assemblies?

Did the docs/ReferenceAssemblies.md instructions not work for you?

The good news is that this manual reference assembly generation process is going away soon. https://github.com/dotnet/aspnetcore/pull/23403

**Comment by Kahbazi** [comment]
> Did the docs/ReferenceAssemblies.md instructions not work for you?

No, it worked a few times in the past, but I usually end up doing them manually.

**Comment by javiercn** [comment]
@Kahbazi where are you stuck with the ref assembly generation?

**Comment by Kahbazi** [comment]
I get `error MSB4057: The target "GenerateReferenceSource" does not exist in the project.` after running `dotnet msbuild /t:GenerateReferenceSource`.

If the changes in this PR is ok, I'll update the reference assemblies manually.

**Comment by javiercn** [comment]
@Kahbazi let me try fetching your branch and see if I can get it to work or if I see the same issue. If I can get it to work maybe I can figure out the process for pushing a commit on top and we should be good. I'm not sure if I'll have to end-up creating a separate PR with your commit on it to be able to do it, but we can at least figure out the changes and you can apply them manually on top if necessary

**Comment by javiercn** [comment]
Here is the patch with the changes, this should at least make it easier to make the changes. [0001-Update-ref-assemblies.txt](https://github.com/dotnet/aspnetcore/files/4919931/0001-Update-ref-assemblies.txt)

Alternatively, what I did was to run `.\eng\scripts\GenerateReferenceAssemblies.ps1`

**Comment by Kahbazi** [comment]
@javiercn thanks for the patch. I tried `.\eng\scripts\GenerateReferenceAssemblies.ps1` before. It didn't work for me either.

**Review by HaoK — APPROVED** [review]

**Review by javiercn — APPROVED** [review]

**Comment by javiercn** [comment]
Merged.

@Kahbazi thanks for the contribution!

**Pull request merged**
