### PR TITLE
[release/6.0] Backport deletion of playwright tests

### PR DESCRIPTION
**Pull request by HaoK**
These tests were removed in https://github.com/dotnet/aspnetcore/commit/5247048126a2bdfac17d44d63d497055a53d08a2 for 7.0, and due to pw having some infrastructure costs, better to remove these in 6.0 rather than update pw infrastructure

### CODE REVIEW

**Comment by HaoK** [comment]
Per discussion with @captainsafia and @TanayParikh these playwright tests were removed in 7.0 so this just backports their removal to 6.0 so we avoid any extra playwright issues

**Review by TanayParikh — APPROVED** [review]
Thanks!

**Comment by HaoK** [comment]
@wtgodbe this PR is green, is there any other process we need to follow to get this in, or is this sufficient for the build team to merge during the window?

**Review by dougbu — APPROVED** [review]

**Review by captainsafia — APPROVED** [review]

**Comment by dougbu** [comment]
This PR is test-only. Any reason not to merge it @HaoK❔

**Comment by HaoK** [comment]
Nope, should be good to merge!

**Pull request merged**
