### PR TITLE
Retry failing helix test

### PR DESCRIPTION
**Pull request by amcasey**
`Http2WebSocketTests.HEADERS_Received_SecondRequest_ConnectProtocolReset` failed in https://github.com/dotnet/aspnetcore/pull/48664

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Comment by BrennanConroy** [comment]
Issue? Link to failure?

**Comment by amcasey** [comment]
Sorry, a bit rushed today.  Failure: https://github.com/dotnet/aspnetcore/runs/14144482654

Was I supposed to file a corresponding issue?  I didn't notice that in the handbook instructions.

**Comment by amcasey** [comment]
My reading of [these steps](https://github.com/dotnet/aspnetcore-internal/blob/main/docs/operations/quarantine_tests.md#instructions) was, don't follow the quarantine procedure (including filing an issue and adding an attribute) if you can add it to the retry list.  I agree that it's a little weird that there will be no (apparent?) follow-up if the test passes on retry.

**Comment by BrennanConroy** [comment]
> Was I supposed to file a corresponding issue? I didn't notice that in the handbook instructions.

It's possible the instructions changed. The whole retry thing is kind of new (and I'm not a fan of it anyways 😆)

Also, that failure looks very similar to the PR Will pinged us on yesterday...

**Comment by amcasey** [comment]
> Also, that failure looks very similar to the PR Will pinged us on yesterday...

That was in `release/6.0` and I was unable to repro it in `main`.  Fair point though.

**Pull request merged**
