### PR TITLE
Tests for GetHttpProtocolVersion

### PR DESCRIPTION
**Pull request by gfoidl**
Addresses https://github.com/aspnet/AspNetCore/issues/14139

/cc: @JamesNK

### CODE REVIEW

**Review by jkotalik — APPROVED** [review]

**Comment by JamesNK** [comment]
Opps, I missed seeing this.

There is nothing wrong with unit testing this. However, the tests I'd be most interested in for verifying `Request.Protocol` in Kestrel vs IIS is end-to-end functional/integration tests.

**Review by JamesNK — APPROVED** [review]

**Comment by gfoidl** [comment]
> for verifying `Request.Protocol` in Kestrel vs IIS is end-to-end functional/integration tests.

This it out of my scope (i.e. I don't know how and where to put these tests), that's why this PR didn't add such tests (as I'd also like to see these).
If you can give me some pointers I can add tests for this.

**Comment by JamesNK** [comment]
No problem. They're more complex. Probably better than an ASP.NET engineer handles it.

**Comment by jkotalik** [comment]
@JamesNK I can take a look into this. I thought it would be easy to add a test, but there needs to be some casing on whether Http2 is supported/enabled or not, which is tricky.

**Comment by jkotalik** [comment]
I still think we can merge this PR as is though!

**Comment by gfoidl** [comment]
@jkotalik thx. When you have your PR ready, can you please tag me, as I'm interested to see how it's done?

**Comment by gfoidl** [comment]
https://github.com/aspnet/AspNetCore/pull/14644 is the PR for e2e-tests (just to put the reference here).

**Comment by jkotalik** [comment]
@HaoK do you know what's up with teh ARM64 queues failing here?

**Comment by HaoK** [comment]
The queues ran out of disk space, but it should be fixed now if you retry

**Comment by jkotalik** [comment]
@gfoidl Thanks!

**Pull request merged**
