### PR TITLE
Enable logging branch SiteExtension

### PR DESCRIPTION
**Pull request by pakrym**
We are servicing Azure Logger provider and need to rebuild branch site extension.

### CODE REVIEW

**Review by natemcmaster — APPROVED** [review]

**Comment by dougbu** [comment]
To confirm: This PR doesn't need any new packages to be listed in PatchConfig.props?

**Comment by pakrym** [comment]
Honestly, I'm not sure, site extension build produces a package but it's not our usual product `.nupkg` and is more similar to shared runtime packages in nature and is done in a separate build step.

What does `PatchConfig` effect?

**Comment by dougbu** [comment]
> What does `PatchConfig` affect?

As I understand it, this file affects what's included in the "slim" version of the patch Zip for incremental patch updates as well as the packages we actually ship. @natemcmaster is that correct?

**Comment by natemcmaster** [comment]
PatchConfig affects all projects which import Directory.Build.props/targets. It is used to determine whether or not to produce a new .nupkg.

Site extension is still special in this branch of the build system. Run the build locally and double check that you get the build artifacts you expect.

**Pull request merged**
