### PR TITLE
Update ws-proxy sources to match Mono commit c5149e31b4d7c

### PR DESCRIPTION
**Pull request by SteveSandersonMS**

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
With this version, breakpoints are hitting and stepping seems to work great, however I can no longer see the values of any variables (locals or properties). Previously it was possible to expand `this` here and see the counter value:

image

I get the same effect if debugging in Chrome as in VS.

It's possible this is because the ws-proxy code is now newer than the version of the `dotnet.wasm` runtime. @pranavkm Do you know if the latest runtime has flowed into the `blazor-wasm` branch yet?

**Comment by pranavkm** [comment]
Looks like the runtime build's been stuck for a few days. Let me check

**Comment by pranavkm** [comment]
Looks better with the runtime updated, although I'm not sure what the extra `this` is:

image

**Review by pranavkm — APPROVED** [review]

**Comment by SteveSandersonMS** [comment]
The extra « this » was there before too. Thanks for checking!

**Comment by mkArtakMSFT** [comment]
And we have a tracking bug for the extra `this` issue: https://github.com/mono/mono/issues/19306

**Pull request merged**
