### PR TITLE
[Helix] Reenable azure auth tests

### PR DESCRIPTION
**Pull request by HaoK**

### CODE REVIEW

**Comment by HaoK** [comment]
Likely blocked until https://github.com/aspnet/AspNetCore/issues/7986 is addresessed (but Mvc Functionals blocked by a build issue), so this PR can isolate the WebApplicationFactory helix issues

**Comment by HaoK** [comment]
Pointing the content root at the publish directory does the trick for these too

**Review by javiercn — APPROVED** [review]

**Comment by javiercn** [comment]
@HaoK I'm not sure about the contentroot.sln (what is it used for?) If these tests are using Web Application factory there is a feature you can use by just adding an additional assembly metadata-like attribute

**Comment by HaoK** [comment]
That's just a quick and dirty way for the existing code that scans for a sln file to just work.  I'm happy to switch to the attribute if it works just as well.  Do you have an example of the attribute usage somewhere else?

**Comment by javiercn** [comment]
https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/test/Mvc.FunctionalTests/Microsoft.AspNetCore.Mvc.FunctionalTests.csproj#L24

The attribute is more flexible because it allows you to specify relative paths from the output, the order in which it applies and it has fallback logic, so you can adapt it to multiple situations.

**Comment by javiercn** [comment]
You still need to do the specific publish bit.

**Comment by HaoK** [comment]
Cool works for me, updated this and the other similar tests to use the attribute instead of dropping dummy files

**Comment by HaoK** [comment]
@javiercn doesn't look like the attribute works on the helix machines, it worked fine locally when I published and copied to a different directory, but doesn't appear to work in the ci builds.

```
 System.InvalidOperationException : Solution root could not be located using application root C:\dotnetbuild\work\d1935b84-7351-4913-9a1d-23b20fb7b2ed\Work\14cc37ca-e686-4398-9418-2c06f7de80f7\Exec\.
Stack Trace:
   at Microsoft.AspNetCore.TestHost.WebHostBuilderExtensions.UseSolutionRelativeContentRoot(IWebHostBuilder builder, String solutionRelativePath, String applicationBasePath, String solutionName) in /_/src/Hosting/TestHost/src/WebHostBuilderExtensions.cs:line 108
   at Microsoft.AspNetCore.TestHost.WebHostBuilderExtensions.UseSolutionRelativeContentRoot(IWebHostBuilder builder, String solutionRelativePath, String solutionName) in /_/src/Hosting/TestHost/src/WebHostBuilderExtensions.cs:line 75
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.SetContentRoot(IWebHostBuilder builder) in /_/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs:line 193
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer() in /_/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs:line 151
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers) in /_/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs:line 403
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(Uri baseAddress, DelegatingHandler[] handlers) in /_/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs:line 451
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient(WebApplicationFactoryClientOptions options) in /_/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs:line 388
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient() in /_/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs:line 380
   at Microsoft.AspNetCore.Identity.FunctionalTests.LoginTests`2.CanLogInWithTwoFactorAuthentication_WithGlobalAuthorizeFilter() in /_/src/Identity/test/Identity.FunctionalTests/LoginTests.cs:line 96

```

**Comment by HaoK** [comment]
Going back to the old working workaround for now, we can switch to the attribute in a separate pr in the future if it makes sense

**Comment by javiercn** [comment]
@haok it seems like it didn’t find the probing file

**Comment by javiercn** [comment]
This approach is fine too.

**Review by javiercn — APPROVED** [review]

**Pull request merged**
