### PR TITLE
Update appSettings.json to have a comment for org auth cases

### PR DESCRIPTION
**Pull request by sayedihashimi**
I have modified the `appSettings.json` to have a comment that will help users configure Azure settings that are needed for org auth scenarios.

Note: the FWLink that the comment points to will be updated before these are released.

Before merging we will need to test the nuget packages that come out of the build. @phenning and @vijayrkn will assist in testing.

Replaces PR at https://github.com/dotnet/aspnetcore/pull/29604

## Description
This includes a new comments in appSettings.json for asp.net core projects that have been created with Microsoft identity platform as the auth method.
In 16.9, the user will need to create some objects in Azure, and then specify the values in the appSettings.json.
This change includes an FWLink that will point to some docs that the user can follow to complete the process. I'm still working on that doc, so the
link is currently pointing to a general doc about Microsoft identity platform and asp.net core.
Later in 16.10, Visual Studio will do the work to provision the Azure objects and populate appSettings.json, but this comment will still be helpful
for users that create projects with `dotnet new`

## Customer Impact
Helps users complete configuration of asp.net core projects created with Microsoft identity platform as the auth method.

## Regression?
- [ ] Yes
- [X] No

[If yes, specify the version the behavior has regressed from]

## Risk
- [ ] High
- [ ] Medium
- [X] Low

Pretty low risk, the change just includes a comment in the `appSettings.json` files for asp.net core projects that support Microsoft identity platform auth.

[Justify the selection above]

## Verification
- [X] Manual (required)
- [ ] Automated

## Packaging changes reviewed?
- [ ] Yes
- [ ] No
- [x] N/A
Not sure what this question is asking here.

Addresses [issue number]
No issue tracking this currently

### CODE REVIEW

**Review by pranavkm — APPROVED** [review]
Changes look ok to me. @phenning could you have a look?

Our 5.0 branches are currently closed. @mkArtakMSFT could you be responsible for making sure this goes in once the branches are ready? Thanks!

**Review by phenning — APPROVED** [review]

**Comment by phenning** [comment]
> Changes look ok to me. @phenning could you have a look?
> 
> Our 5.0 branches are currently closed. @mkArtakMSFT could you be responsible for making sure this goes in once the branches are ready? Thanks!

:shipit:

**Comment by sayedihashimi** [comment]
@phenning I noticed after going through VS the URL is messed up because some `/` characters were removed.
For example here is what I'm seeing

```html
/*
The following identity settings need to be configured
before the project can be successfully executed.
For more info see https:aka.ms/dotnet-template-ms-identity-platform 
*/
```

@phenning can you take a look to see what could be happening here?

**Comment by phenning** [comment]
Try escaping it. Use https://// instead of https://

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sayedihashimi** [comment]
@phenning looks like escaping fixes the issue that I brought up. I've updated my PR with a new commit to fix that.

**Pull request merged**
