### PR TITLE
Implemented minimal WebTransport Middleware

### PR DESCRIPTION
**Pull request by Daniel-Genkin-MS-2**
Quick PR to add a new project for the WebTransport Middleware. This will eventually host the WebTransport API.

## TODO
- [x] Add sample project
- [x] Add test project

### CODE REVIEW

**Comment by davidfowl** [comment]
What does the WebTransport API look like? Is there a new API we're adding here? What does this middleware do?

**Comment by Daniel-Genkin-MS-2** [comment]
Just squashed the commits to get a nicer permalink for my other PR (https://github.com/dotnet/aspnetcore/pull/41949). No code changes were made.

**Comment by Daniel-Genkin-MS-2** [comment]
> What does the WebTransport API look like? Is there a new API we're adding here? What does this middleware do?

Those are great questions! I don't know yet as I am doing everything very incrementally. My next follow up PR will hopefully answer these questions. This PR just sets up the project.

**Comment by halter73** [comment]
> The theory is that it will work similar to WebSockets,

Is it similar enough to consider putting the WebTransport middleware in the `Microsoft.AspNetCore.WebSockets` assembly?

**Comment by Tratcher** [comment]
> > The theory is that it will work similar to WebSockets,
> 
> Is it similar enough to consider putting the WebTransport middleware in the `Microsoft.AspNetCore.WebSockets` assembly?

I would only do that if we expected them to share any code. I don't think that will be the case.

**Comment by Tratcher** [comment]
> So in theory when we ship this would it go into the BCL networking APIs?

Only the symmetrical parts (if any), similar to the WebSocket type.

**Comment by davidfowl** [comment]
> Only the symmetrical parts (if any), similar to the WebSocket type.

Yes, the entire WebSocket implementation 😄

**Review by Tratcher — CHANGES_REQUESTED** [review]
After yesterday's design discussion it looks like most of the WebTransport functionality will need to be built directly into Kestrel. Let's pause this PR until we're sure if we need the middleware package or not.

**Comment by Daniel-Genkin-MS-2** [comment]
> After yesterday's design discussion it looks like most of the WebTransport functionality will need to be built directly into Kestrel. Let's pause this PR until we're sure if we need the middleware package or not.

I agree. By "pause", do you mean close or just stop committing to it?

**Pull request closed without merging**
