### PR TITLE
Update SDK to preview 7

### PR DESCRIPTION
**Pull request by JunTaoLuo**
Addresses https://github.com/aspnet/AspNetCore-Internal/issues/2774

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
If it builds :shipit:

**Comment by JunTaoLuo** [comment]
It builds! But tests fail and it's related to the SDK update, I'll address it tomorrow.

**Comment by dougbu** [comment]
@JunTaoLuo the following blocks of workarounds should be removed either in this PR or as a follow-up:
- https://github.com/aspnet/AspNetCore/blob/331ff2404dcf54b5d7a4dc5caed237fdb5c67788/eng/Workarounds.targets#L18-L22
- https://github.com/aspnet/AspNetCore/blob/331ff2404dcf54b5d7a4dc5caed237fdb5c67788/eng/Workarounds.targets#L50-L70

**Comment by dougbu** [comment]
This isn't building. Any chance we could get it in before noon tomorrow?

**Comment by JunTaoLuo** [comment]
I fixed a behaviour change w.r.t how we filter assemblies we put into the reference package.

As for the failing templating tests, they are caused by a behaviour change in https://github.com/dotnet/templating/pull/1929. In this PR, I've taken the approach of disabling the tests. The rationale is that we should ask the templating team for details on how we should be using it.

As an alternative, I did find a way to get tests uninstallation to work: https://github.com/aspnet/AspNetCore/pull/12557. Assuming both passes, pick whichever approach you prefer.

**Comment by dougbu** [comment]
Went with #12682

**Pull request closed without merging**
