### PR TITLE
Update Polly and support IConcurrentPolicyRegistry<string>

### PR DESCRIPTION
**Pull request by martincostello**
**PR Title**

Update to the latest release of Polly.

**PR Description**

  * Update Polly dependency to the latest version of the package, [7.2.2](https://www.nuget.org/packages/Polly/7.2.2).
  * Also register Polly policy registries as `IConcurrentPolicyRegistry<string>` https://github.com/dotnet/aspnetcore/pull/28283#discussion_r598061746.

Addresses #31705

### CODE REVIEW

**Comment by martincostello** [comment]
The latest release of Polly isn't in the Azure Artifacts feed, so I tested this locally with this added to `NuGet.config`:

```xml
<add key="nuget-public" value="https://api.nuget.org/v3/index.json" />
```

**Review by javiercn — APPROVED** [review]
Looks great!

Thanks for the contribution!

**Comment by dougbu** [comment]
> The latest release of Polly isn't in the Azure Artifacts feed

@mmitche @wtgodbe could you please help here❔

**Pull request merged**
