### PR TITLE
Replace favicon.ico with smaller size

### PR DESCRIPTION
**Pull request by ghost**
In the ProjectTemplate folder - replace favicon.icon with a smaller (5.3 KB) version.

Addresses #13491

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=22533) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=22533) before we can accept your contribution.<br/><br/>:x: heyitstanyado [sign now](https://cla.dotnetfoundation.org/dotnet/aspnetcore?pullRequest=22533)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/aspnetcore?pullRequest=22533) it.</sub>

**Comment by pranavkm** [comment]
@heyitstanyado thanks for the PR. Did you happen to use the icon files that @DamianEdwards listed in the issue comment?

**Comment by heyitstanyado** [comment]
Yup, I pulled it from the zip file in the original/first comment.

**Review by pranavkm — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
