### PR TITLE
[SPA] Update NPM dependencies

### PR DESCRIPTION
**Pull request by javiercn**

### CODE REVIEW

**Comment by dougbu** [comment]
@javiercn please work to get this approved for 5.0.13 this week.

@Pilchie suggest we make the same `tell-mode` decision as in #37776

**Comment by dougbu** [comment]
Optimistically updating the milestone i.e. expecting review will be done soon

**Review by mkArtakMSFT — APPROVED** [review]
Thanks @javiercn. Signing off as you've verified the changes already.

**Pull request merged**
