### PR TITLE
Renormalize line endings for some files.

### PR DESCRIPTION
**Pull request by mmitche**
Done with git add --renormalize. Issues (`crlf will be replaced by lf`) seen in source-build stash/unstash.

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Comment by Pilchie** [comment]
@vijayrkn @phenning - any idea if this would impact the template engine on Linux?

**Comment by mmitche** [comment]
> @vijayrkn @phenning - any idea if this would impact the template engine on Linux?

That was my main concern. I think the alternative would be to normalize at LF, then change the .gitattributes for those files to expect LF.

**Comment by phenning** [comment]
I’m not sure what, if any impact this would have on Linux. Someone from the Prague team might better be able to answer that.

**Comment by phenning** [comment]
@bekir-ozturk

**Comment by vijayrkn** [comment]
Looks like these 2 bugs have a lot of details on the current template engine behavior: 
https://github.com/dotnet/templating/issues/350
https://github.com/dotnet/templating/issues/1248 (still open)

Adding  @DavidKarlas to comment on which is preferred.

**Comment by mmitche** [comment]
This appears to have resolved the issues with the official build.

**Comment by sebastienros** [comment]
Does it have to be done in release/3.1 too?

https://dev.azure.com/dnceng/internal/_build/results?buildId=1289533&view=results

**Comment by wtgodbe** [comment]
The pipeline you linked is against `main` - the most recent 3.1 job looks to have passed: https://dev.azure.com/dnceng/internal/_build/results?buildId=1286624&view=results

**Comment by sebastienros** [comment]
Sorry, I meant to share https://dev.azure.com/dnceng/internal/_build/results?buildId=1286623&view=results but your result is newer so that's ok. I picked it from the dashboard, which doesn't show the success:

image

**Comment by sebastienros** [comment]
Failing on main branch, an hour ago:

https://dev.azure.com/dnceng/internal/_build/results?buildId=1290736&view=results

**Comment by mmitche** [comment]
Odd....no changes in those files and https://dev.azure.com/dnceng/internal/_build/results?buildId=1290485&view=results passed just a few hours ago. Those two files do have bad line endings though. I ran it over all files in aspnetcore and this PR is now open: https://github.com/dotnet/aspnetcore/pull/35301

**Pull request merged**
