### PR TITLE
Duplicate delegation rules should not fail

### LINKED ISSUE #25831: HttpSysRequestDelegationFeature - HttpSysException when creating two delegation rules for the same queue but different url prefixes
### Describe the bug
Using the new [delegate request feature](https://github.com/dotnet/aspnetcore/issues/21163) create two delegation rules for the same queue name but different url prefixes. This results in an HttpSysException. 

### To Reproduce

```c#
namespace Sample
{
    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostApplicationLifetime lifetime, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            
            var delegator = app.ServerFeatures.Get<IServerDelegationFeature>();
            delegator.CreateDelegationRule("DefaultAppPool", "http://*:80/");
            delegator.CreateDelegationRule("DefaultAppPool", "http://*:443/");
        }
    }
}
```

### Exceptions (if any)

```
Microsoft.AspNetCore.Server.HttpSys.HttpSysException (183): Cannot create a file when that file already exists.
         at Microsoft.AspNetCore.Server.HttpSys.UrlGroup.SetProperty(HTTP_SERVER_PROPERTY property, IntPtr info, UInt32 infosize, Boolean throwOnError)
         at Microsoft.AspNetCore.Server.HttpSys.UrlGroup.SetDelegationProperty(RequestQueue destination)
         at Microsoft.AspNetCore.Server.HttpSys.ServerDelegationPropertyFeature.CreateDelegationRule(String queueName, String uri)
```

### Further technical details

Targeting ASP.NET Core 5.0.0-rc.1.20425.11

```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20426.10
 Commit:    e6cd5e783a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.1.20426.10\

Host (useful for support):
  Version: 5.0.0-rc.1.20425.18
  Commit:  55ab8ce696

.NET SDKs installed:
  3.1.401 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20426.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20425.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20425.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20425.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### PR DESCRIPTION
**Pull request by shirhatti**
Creating two delegation rules for the same queue name but different url prefixes no longer results in an HttpSysException.

### CODE REVIEW

**Comment by davidfowl** [comment]
Is there an issue that should be linked?

**Comment by shirhatti** [comment]
#25831

**Comment by shirhatti** [comment]
I just realized swallowing the error is a terrible idea just as I started working on https://github.com/dotnet/aspnetcore/issues/27126.

Unsetting the property on disposing the delegation rule should be the desired behavior. That allow you to add and remove delegation rules (as new delegatee processes come and go) without restarting the delegator process.

I'm now convinced the right behavior is to not swallow the exception

**Comment by shirhatti** [comment]
@Tratcher and I decided not to do anything here. The `ERROR_ALREADY_EXISTS` error is sufficient

**Pull request closed without merging**
