### PR TITLE
http.sys - remove all GC pins in primary write path

### PR DESCRIPTION
**Pull request by mgravell**
# http.sys - remove all GC pins in primary write path

## Description

Motivation: performance

The buffers going to http.sys need to be pinned (vs GC move) for the duration of the P/Invoke; historically we have used `GCHandle` for the incoming data buffers, and byte-arrays for small scratch buffers (used for things like chunked-encoding sentinels); this works, but requires a lot of overhead for the manual book-keeping.

Currently, all our P/Invoke for http.sys is synchronous; in synchronous paths, simpler mechanisms exist, specifically:

- we can use `fixed` for the main external data buffers, which is very cheap (just a special local to the ref, on the stack)
- we can use `stackalloc` for the scratch buffers (which aren't exposed to GC and thus never require pinning, and don't impact the GC) - only required when chunked, and very small (10 bytes, so entirely stack-suitable)

We still use the same `UnmanagedBufferAllocator` to handle some other pre-existing memory fun, but we don't need the `byte[]` allocs or any `GCHandle.Alloc` in `GCHandleType.Pinned` mode (plus the need to unpin the same via `FreeDataBuffers`)

---

other minor tweaks:

- avoid `new StreamPipeWriterOptions` each request/writer
- avoid instance delegate allocation from `OnResponseStart` via static cached delegate plus `_onStartContext` state
- "DRY" - move multiple `_requestContext.Response.BoundaryType == BoundaryType.Chunked` checks to `IsChunked`
- avoid async machinery in `WriteAsync`; optimize for sync-write in `Write`

### CODE REVIEW

**Comment by Tratcher** [comment]
> Currently, all our P/Invoke for http.sys is synchronous

I don't follow, the Write/FlushAsync code paths are fully async, even the P/Invokes. The sync code paths are all disabled by default (AllowSynchronousIO = false), so there's limited value to optimizing them. The current changes seem fine, but I wouldn't persue any more down that code path.

**Comment by mgravell** [comment]
The .NET side is async, but the actual places where we P/Invoke: we're using the synchronous http.sys APIs, which is why the existing code can just try/finally around them and release the pins in the finally - rather than waiting for some callback/poll to unpin. I'm talking purely about the P/Invoke layer.

**Comment by mgravell** [comment]
@Tratcher if you're saying "the code path you're looking at : is rarely if ever used any more" - great; in that case I would absolutely agree with you and leave well alone. I'll double check that, however: I *believe* I was hitting this code path from the async APIs. Happy to check briefly tomorrow - it won't take me long.

**Comment by Tratcher** [comment]
Right, you shouldn't be hitting sync pinvokes in the async code paths.

**Comment by mgravell** [comment]
@Tratcher will look tomorrow and double-check my understanding

**Comment by mgravell** [comment]
@Tratcher looking again today; I have to mostly agree - but I know I hit that code path; maybe that was from the `Dispose()`? but agreed: probably not worth touching the sync code path at this point; however! now I'm curious as to the timing of things re the async completion; because we don't actually wait for that before the `allocator.Dispose()`; I'm reading up on http.sys docs re the exact timing here, i.e. does it copy in the first P/Invoke, or does it just stash the pointers for use later; if the latter, we *could* have unpinned memory in the async part of the unmanaged code, which is... fun

**Pull request closed without merging**
