### PR TITLE
Send confirmation mails for external accounts

### PR DESCRIPTION
**Pull request by HaoK**
Fixes https://github.com/dotnet/aspnetcore/issues/18140

Without this fix, users who create their accounts via social login are unable to login with the templates

### CODE REVIEW

**Comment by ajcvickers** [comment]
### Description

When creating an account using a social login the confirmation email does not get sent which can then result in the account being locked out.

### Customer Impact

Reported by several customers. There is a relatively easy workaround, but given the out-of-box experience is not good for a somewhat common case we feel it should be patched anyway.

###How found

Reported by several customers.

### Test coverage

Added a regression test for this case.

### Regression?

Yes, from 2.2 to 3.0.

### Risk

Low. Code change is minimal and self contained.

**Comment by jamshedd** [comment]
Approved for March

**Comment by ajcvickers** [comment]
@HaoK Don't merge until the branches are open for March. I'll let you know.

**Comment by Pilchie** [comment]
Pulling back into 3.1.2

**Comment by Pilchie** [comment]
@HaoK can you work to get this merged by EOD today?

**Comment by HaoK** [comment]
This PR is ready to go, I might be able to click the merge button if someone approves it, @ajcvickers can you approve?

**Review by ajcvickers — APPROVED** [review]

**Comment by ajcvickers** [comment]
@HaoK Approved.

**Comment by HaoK** [comment]
Okay I still can't click the merge button, only authorized users can merge this pr...

**Comment by HaoK** [comment]
@dougbu is there any other process I need to do for 3.1.2 now that this has been merged?

**Comment by Pilchie** [comment]
No, this should be good.

**Pull request merged**
