### PR TITLE
Updated order of projects in the new project dialog

### PR DESCRIPTION
**Pull request by mkArtakMSFT**
Addresses #9460

### CODE REVIEW

**Review by danroth27 — APPROVED** [review]
LGTM

**Review by ryanbrandenburg — APPROVED** [review]
:shipit: assuming the behavior here is that sharing the same number means it's ordered alphabetically.

**Review by shirhatti — APPROVED** [review]

**Comment by mkArtak** [comment]
@aspnet-hello triage

**Comment by mkArtakMSFT** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=159571&view=logs&jobId=f31c9f97-4411-58e7-49ac-fc73f645e6b6

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2306

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2306

**Pull request merged**
