### PR TITLE
[3.1] Enable control flow guard for IIS dlls

### PR DESCRIPTION
**Pull request by jkotalik**
Backporting https://github.com/dotnet/aspnetcore/pull/22480 to 3.1.

### CODE REVIEW

**Comment by Pilchie** [comment]
:eyes:

**Comment by jkotalik** [comment]
@Pilchie question from my other PR:

> I'm not certain if this should be ask mode or tell mode for this change.

**Comment by Pilchie** [comment]
I think tell mode is fine once the branch opens again.

**Comment by jkotalik** [comment]
My guess would be around 2 days of work. We should be able to piggy back off the work done in Kestrel. Reaching out to partners for verification isn't included in this cost.

**Review by dougbu — APPROVED** [review]

**Comment by Pilchie** [comment]
@jkotalik @BrennanConroy - any idea about the failure?  Seems unlikely this would break a SignalR test...

**Comment by BrennanConroy** [comment]
Flaky test that was fixed in 5.0. It would be a little awkward to backport to 3.1 since we added a new feature (internal only) to fix it.

**Comment by Pilchie** [comment]
Okay - I'll force merge this one.

**Pull request merged**
