### PR TITLE
Disconnect circuit on `beforeunload` event

### LINKED ISSUE #19050: Circuit not disconnected properly on all browsers when navigating away from page
### Describe the bug
I have a Blazor Server project running on ASP.NET Core 3.1 with a problem that is exhibited both when:

1. I debug with VS 2019 (16.4 and 16.5) using IIS, and 
2. Deployed to an Azure Web App running Linux and within a Docker container.

The issue is that certain actions that I take that call `NavigationManager.NavigateTo("/my-page");` causes the signalr connection between the Blazor app and my browser to drop for a couple of seconds and then re-establish itself to the state as it was before I pressed the relevant button. The next time I try everything works as intended.

This has different behaviour depending upon my browser:

1. Chromium Edge is the worst. When the lost connection happens, it resumes as if the relevant event had never happened.
2. Google Chrome never seems to experience the lost connection.
3. Firefox is a halfway house. It has the problem a little less frequently than Chromium Edge, and when it does, after the signalr connection resumes the app has recognised the event and changed its state accordingly.

There is no output to be seen in the VS Debug output window. No information, warnings or errors. Also no indication that the router wants to navigate to `/my-page`.

The `NavigationManager` call is in a one-line function in the `@code` block of a `.razor` file. When I use the debugger, I step over the call successfully but then once the function I'm debugging exits, the signalr connnection is lost.

### To Reproduce
I don't know how to reproduce this. It's in an app I'm writing for commercial purposes. I would be happy to show a Microsoft engineer what's going on.

### Further technical details
- ASP.NET Core version: **3.1**
- Include the output of `dotnet --info` **see below**
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version **16.4 and 16.5**

```
PM> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200-preview-014883
 Commit:    4e2a0ee959

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200-preview-014883\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.200-preview-014883 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### PR DESCRIPTION
**Pull request by captainsafia**
Closes #19050.

In the issue above, the user originally reported that they would see our reconnect modal when navigating away from Firefox. They pointed at inconsistent behavior through browser versions. They'll always see the reconnect modal on Firefox but only on a few version of Chrome.

While debugging this, I realized that this is because our clean-up handler that is registered to the `unload` event is never invoked in Chrome.

The `unload` event is not emitted and, consequently, the async request sent to `/disconnect` via `navigator.sendBeacon`is never emitted.

It turns out that Chrome is discouraging developers from using the `unload` event in favor of its new page navigation APIs ([ref](https://developers.google.com/web/updates/2018/07/page-lifecycle-api#the-unload-event)). Chrome made some changes to the `unload` and `beforeunload` APIs around Chrome 80, I suspect that this is when the regression happened.

I tried triggered the clean-up on a few other events (like `pagehide` and `visibilitychange`) but ultimately settled on `beforeunload` because:

* It works on the widest set of browsers (validated on Chrome, Firefox, Safari, Edge)
* The `pagehide` event isn't triggered all the time in some browsers depending on when the subsequent page is loaded
* This `visibilitychange` is triggered for too many scenarios

### CODE REVIEW

**Comment by javiercn** [comment]
@captainsafia can `onbeforeunload` be cancelled?

**Review by javiercn — APPROVED** [review]
Looks great!

I assume you've done due diligence on testing it on various situations, so signing-off.

**Comment by captainsafia** [comment]
> @captainsafia can onbeforeunload be cancelled?

Yes, if the user accepts the "Do you want to navigate away from this page?" prompt that the browser provides.

**Review by SteveSandersonMS — APPROVED** [review]
Awesome! Glad there was such a clean fix here!

Assuming there are no known drawbacks, this seems like a very strong patch candidate.

**Comment by captainsafia** [comment]
Made some modifications after testing a few more scenarios. Re-requesting reviews for this.

We register the same event handler on both the `beforeunload` and `unload` events. We track whether the `/disconnect` request has been successfully queued in the `beforeunload`. If not, we empty to send it again in the `unload`. We execute each event listener at most once.

**Comment by javiercn** [comment]
> Made some modifications after testing a few more scenarios. Re-requesting reviews for this.
> 
> We register the same event handler on both the `beforeunload` and `unload` events. We track whether the `/disconnect` request has been successfully queued in the `beforeunload`. If not, we empty to send it again in the `unload`. We execute each event listener at most once.

What motivated this change? It would be good to keep a record for the future

**Review by javiercn — APPROVED** [review]
LGTM, interested in knowing the reason for subscribing to both events

**Comment by captainsafia** [comment]
> LGTM, interested in knowing the reason for subscribing to both events

Chrome won't fire the event if the user hasn't interact with the page. This ends up happening in our CI tests because we call `Browser.Close()` without interacting with the page.

Firefox allows users to set a `disable_beforeunload` flag to disable those navigate away alerts. However, that disables `beforeunload` events and immediately emits the `unload` event.

**Comment by captainsafia** [comment]
@mkArtakMSFT Can you merge this?

**Comment by alexclarkmusa** [comment]
Just curious but... what sort of QA/unit-testing does a patch like this go through before it's unleashed on the public as a release?  This appears to have caused a fairly significant/fundamental issue with the NavigationManager opening links and it seems like this should have shown up in some simple tests.  I'm trying to make a case for Blazor at work and things like this really scare the business away from it.

**Can there be a bit more diligence before things like this get pushed to the production release please?**

**Comment by pranavkm** [comment]
@alexclarkmusa thank you for your feedback. Patches have a high bar for compatibility and go through a validation process before being released. We had tests that covered normal page navigations, but unfortunately we had a blind spot in our test \ scenario coverage for this particular use case. We will be reverting the patch shortly and we are filling the test hole. We are committed to making sure you're able to confidently pick up new patch releases without the risk of regression and we will be much more cautious making changes of this kind going forward.

**Pull request merged**
