### PR TITLE
[DO NOT MERGE] Slow things down again

### PR DESCRIPTION
**Pull request by halter73smurf**
Summary of the changes (Less than 80 chars)
 - Detail 1
 - Detail 2

Addresses #bugnumber (in this specific format)

More or less the same as #16999, but from a forked repo with a non-org-member account. It doesn't seem I can do a draft PR for this.

### CODE REVIEW

**Comment by halter73smurf** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello hello

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by anurse** [comment]
I want that sweet sweet Markdown table 😛 

| Description |     RPS | CPU (%) | Memory (MB) | Avg. Latency (ms) | Startup (ms) | Build Time (ms) | Published Size (KB) | First Request (ms) | Latency (ms) | Errors | Ratio |
| ----------- | ------- | ------- | ----------- | ----------------- | ------------ | --------------- | ------------------- | ------------------ | ------------ | ------ | ----- |
|      Before | 375,625 |      68 |          51 |              6.52 |          407 |           10004 |              118266 |             148.29 |         0.48 |      0 |  1.00 |
|       After |  23,496 |      40 |         117 |             18.51 |          371 |            7522 |              118266 |              134.1 |           11 |      0 |  0.06 |

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by sebastienros** [comment]
Still working ;)

**Comment by halter73** [comment]
@aspnet-hello benchmark http2

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark http2

**Comment by halter73** [comment]
@aspnet-hello benchmark http2

**Comment by halter73** [comment]
@aspnet-hello benchmark http2

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Pull request closed without merging**
