### PR TITLE
Try new docker image

### LINKED ISSUE #37406: Undo workarounds added to dockerfile while updating to 7.0 SDK
As part of updating the SDK in https://github.com/dotnet/aspnetcore/pull/37192, we had to add stop-gap workarounds to `eng/docker/rhel.Dockerfile` and `src/Installers/Rpm/Directory.Build.targets` to allow the build to succeed on a CentOS 7 image. We want to eventually switch to an official image that supports building RPM packages without these hacks. This is a tracking issue to remove these workarounds.

### PR DESCRIPTION
**Pull request by wtgodbe**
Attempt to fix https://github.com/dotnet/aspnetcore/issues/37406

### CODE REVIEW

**Comment by wtgodbe** [comment]
> chown: cannot access '/usr/bin/sudo': No such file or directory
The command '/bin/sh -c chown root:root /usr/bin/sudo && chmod 4755 /usr/bin/sudo' returned a non-zero code: 1

Not the same failure as last time, not sure what the fix for this would be though

https://github.com/dotnet/aspnetcore/pull/37192#issuecomment-933834768

**Comment by dougbu** [comment]
> `chown: cannot access '/usr/bin/sudo': No such file or directory`

That line has been in the Dockerfile since Nate created it 😦

**Comment by dougbu** [comment]
Excellent, we'll at least know if we use `sudo` when creating RPMs 😁

**Comment by wtgodbe** [comment]
Back to https://github.com/dotnet/aspnetcore/pull/37192#issuecomment-932620735 - so, we probably need to spin our own image

**Comment by wtgodbe** [comment]
Looks like this is working, @dotnet/aspnet-build any requests?

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
Doesn't have to be in this PR but we should use a MCR image in https://github.com/dotnet/aspnetcore/blob/main/src/Servers/Kestrel/test/SystemdActivation/Dockerfile

**Pull request merged**
