### PR TITLE
Make HTTP request methods as const strings

### PR DESCRIPTION
**Pull request by cpp11nullptr**
Make HTTP request methods as const strings as it should never be changed.

### CODE REVIEW

**Comment by Tratcher** [comment]
Thanks for looking at this, but this behavior was intentional. Using statics allows us to use ReferenceEquals for quick equality checks. Consts get embedded in the calling code and no longer ref-equal.

**Comment by anurse** [comment]
Since there's nothing in the code to make it clear that this was intentional, I filed https://github.com/aspnet/AspNetCore/pull/12441 to add a comment describing this.

**Comment by cpp11nullptr** [comment]
Thanks, @anurse.

**Comment by anurse** [comment]
No problem! Without that additional context, your proposal to switch to `const` was entirely valid! Hopefully this helps clarify things.

**Comment by Pilchie** [comment]
I thought the runtime *did* ensure that string literals and constants were interned and `ReferenceEqual` except for a few corner cases involving things in generic types.  Is that no longer the case?

**Comment by anurse** [comment]
That does appear to be the case, I did some rough testing. There may be more complicated stuff at play though. I know @benaadams did some comparison of JIT-generated ASM when he made the change in HeaderNames (https://github.com/aspnet/AspNetCore/pull/9341) and saw a noticeable performance improvement from switching `const` to `static readonly`.

In general, I think we prefer to be specific here rather than rely on runtime behavior that we can't clearly assert.

**Comment by Pilchie** [comment]
> In general, I think we prefer to be specific here rather than rely on runtime behavior that we can't clearly assert.

Definitely agree here.

**Comment by benaadams** [comment]
> I thought the runtime did ensure that string literals and constants were interned and ReferenceEqual except for a few corner cases involving things in generic types.

In the same assembly. 

Public consts are compiled directly into the il of the referencing assembly if used in default parameters or attributes, so don't share the reference across assemblies; whereas behind a `static readonly` field or method it uses a reference into the referenced assembly.

I believe the runtime can intern and dedupe across assembly but it doesn't do it aggressively (would cause start-up/jit perf impact) and a cross-assembly string const in a method body also prevents inlining https://github.com/dotnet/coreclr/issues/23969

**Comment by Pilchie** [comment]
> In general, I think we prefer to be specific here rather than rely on runtime behavior that we can't clearly assert.

Ah, know I remember the issue.  Thanks @benaadams! Glad we have a comment there now so people understand why the change was made.

**Pull request closed without merging**
