### PR TITLE
Enable trim analyzer

### LINKED ISSUE #41016: [Trimming] Consider using standard <IsTrimmable> property
Currently ASP.NET Core has a `Trimmable` property to indicate trimming. Custom MSBuild configuration then adds the `[AssemblyMetadata("IsTrimmable", "True")]` attribute to assemblies.

Consider moving to the standard `IsTrimmable` property that is built into .NET 6+ - https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming#set-istrimmable.

`IsTrimmable` should continue to drive the generation of known trimmable assemblies which are passed to the LinkabilityChecker.

### PR DESCRIPTION
**Pull request by sbomer**
I think we should be able to remove this workaround now.
Fixes https://github.com/dotnet/aspnetcore/issues/41016.

### CODE REVIEW

**Comment by dougbu** [comment]
@sbomer this looks early given dotnet/linker#2718 and #41016 remain open. But I'm adding @JamesNK as a reviewer&hellip;

**Comment by JamesNK** [comment]
I've fixed warnings in Kestrel, Http.Extensions and middleware. The remaining warnings are in components and JSInterop. I'm not familiar with that code or the existing trimming attributes.

> /home/vsts/work/1/s/src/Components/Components/src/CascadingParameterState.cs(93,30): error IL2067: 'targetType' argument does not satisfy 'DynamicallyAccessedMemberTypes.All' in call to 'Microsoft.AspNetCore.Components.Reflection.ComponentProperties.GetCandidateBindableProperties(Type)'. The parameter 'componentType' of method 'Microsoft.AspNetCore.Components.CascadingParameterState.CreateReflectedCascadingParameterInfos(Type)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [/home/vsts/work/1/s/src/Components/Components/src/Microsoft.AspNetCore.Components.csproj]
> /home/vsts/work/1/s/src/Components/Components/src/DynamicComponent.cs(70,17): error IL2072: 'value' argument does not satisfy 'DynamicallyAccessedMemberTypes.All' in call to 'Microsoft.AspNetCore.Components.DynamicComponent.Type.set'. The return value of method 'Microsoft.AspNetCore.Components.ParameterValue.Value.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [/home/vsts/work/1/s/src/Components/Components/src/Microsoft.AspNetCore.Components.csproj]
> /home/vsts/work/1/s/src/Components/Components/src/Routing/RouteTableFactory.cs(57,34): error IL2026: Using member 'System.Reflection.Assembly.ExportedTypes.get' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Types might be removed. [/home/vsts/work/1/s/src/Components/Components/src/Microsoft.AspNetCore.Components.csproj]
> /home/vsts/work/1/s/src/Components/Components/src/LayoutView.cs(59,24): error IL2072: 'layoutType' argument does not satisfy 'DynamicallyAccessedMemberTypes.All' in call to 'Microsoft.AspNetCore.Components.LayoutView.WrapInLayout(Type, RenderFragment)'. The return value of method 'Microsoft.AspNetCore.Components.LayoutView.GetParentLayoutType(Type)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [/home/vsts/work/1/s/src/Components/Components/src/Microsoft.AspNetCore.Components.csproj]
> /home/vsts/work/1/s/src/Components/Components/src/BindConverter.cs(2033,33): error IL2026: Using member 'System.ComponentModel.TypeDescriptor.GetConverter(Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Generic TypeConverters may require the generic types to be annotated. For example, NullableConverter requires the underlying type to be DynamicallyAccessedMembers All. [/home/vsts/work/1/s/src/Components/Components/src/Microsoft.AspNetCore.Components.csproj]
> /home/vsts/work/1/s/src/Components/Components/src/BindConverter.cs(1831,33): error IL2026: Using member 'System.ComponentModel.TypeDescriptor.GetConverter(Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Generic TypeConverters may require the generic types to be annotated. For example, NullableConverter requires the underlying type to be DynamicallyAccessedMembers All. [/home/vsts/work/1/s/src/Components/Components/src/Microsoft.AspNetCore.Components.csproj]
> /home/vsts/work/1/s/src/Components/Components/src/RouteView.cs(80,17): error IL2111: Method 'Microsoft.AspNetCore.Components.LayoutView.Layout.set' with parameters or return value with `DynamicallyAccessedMembersAttribute` is accessed via reflection. Trimmer can't guarantee availability of the requirements of the method. [/home/vsts/work/1/s/src/Components/Components/src/Microsoft.AspNetCore.Components.csproj]
> /home/vsts/work/1/s/src/Components/Components/src/RouteView.cs(80,17): error IL2111: Method 'Microsoft.AspNetCore.Components.LayoutView.Layout.set' with parameters or return value with `DynamicallyAccessedMembersAttribute` is accessed via reflection. Trimmer can't guarantee availability of the requirements of the method. [/home/vsts/work/1/s/src/Components/Components/src/Microsoft.AspNetCore.Components.csproj]
> /home/vsts/work/1/s/src/Components/Components/src/RouteView.cs(80,17): error IL2111: Method 'Microsoft.AspNetCore.Components.LayoutView.WrapInLayout(Type, RenderFragment)' with parameters or return value with `DynamicallyAccessedMembersAttribute` is accessed via reflection. Trimmer can't guarantee availability of the requirements of the method. [/home/vsts/work/1/s/src/Components/Components/src/Microsoft.AspNetCore.Components.csproj]
> /home/vsts/work/1/s/src/JSInterop/Microsoft.JSInterop/src/JSRuntime.cs(126,17): error IL2026: Using member 'System.Text.Json.JsonSerializer.Serialize<TValue>(TValue, JsonSerializerOptions)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved. [/home/vsts/work/1/s/src/JSInterop/Microsoft.JSInterop/src/Microsoft.JSInterop.csproj]
> /home/vsts/work/1/s/src/JSInterop/Microsoft.JSInterop/src/JSRuntime.cs(245,30): error IL2026: Using member 'System.Text.Json.JsonSerializer.Deserialize(ref Utf8JsonReader, Type, JsonSerializerOptions)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved. [/home/vsts/work/1/s/src/JSInterop/Microsoft.JSInterop/src/Microsoft.JSInterop.csproj]
> /home/vsts/work/1/s/src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs(63,16): error IL2026: Using member 'System.Text.Json.JsonSerializer.Serialize<TValue>(TValue, JsonSerializerOptions)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved. [/home/vsts/work/1/s/src/JSInterop/Microsoft.JSInterop/src/Microsoft.JSInterop.csproj]
> /home/vsts/work/1/s/src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs(133,34): error IL2026: Using member 'System.Text.Json.JsonSerializer.Serialize<TValue>(TValue, JsonSerializerOptions)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved. [/home/vsts/work/1/s/src/JSInterop/Microsoft.JSInterop/src/Microsoft.JSInterop.csproj]
> /home/vsts/work/1/s/src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs(149,26): error IL2026: Using member 'System.Text.Json.JsonSerializer.Serialize<TValue>(TValue, JsonSerializerOptions)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved. [/home/vsts/work/1/s/src/JSInterop/Microsoft.JSInterop/src/Microsoft.JSInterop.csproj]
> /home/vsts/work/1/s/src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs(242,39): error IL2026: Using member 'System.Text.Json.JsonSerializer.Deserialize(ref Utf8JsonReader, Type, JsonSerializerOptions)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved. [/home/vsts/work/1/s/src/JSInterop/Microsoft.JSInterop/src/Microsoft.JSInterop.csproj]
> /home/vsts/work/1/s/src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs(436,36): error IL2075: 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods' in call to 'System.Type.GetMethods(BindingFlags)'. The return value of method 'System.Collections.IEnumerator.Current.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [/home/vsts/work/1/s/src/JSInterop/Microsoft.JSInterop/src/Microsoft.JSInterop.csproj]

@mkArtakMSFT Could someone on the Blazor team contribute to this PR and fix up these warnings? I suggest waiting until https://github.com/dotnet/aspnetcore/pull/41610 is merged. That PR could resolve some of these warnings.

**Comment by MackinnonBuck** [comment]
Ok, I've fixed the warnings on justifiable cases, but I think the analyzer may have pointed out some real potential issues.

@SteveSandersonMS, would you be able to look over these remaining warning locations and confirm whether my concerns are valid? If so, I can do a follow-up commit with some fixes.

---

[`RouteTableFactory.cs(57,34):`](https://github.com/dotnet/aspnetcore/blob/bf50999cd8e60d4c683b772dffa9898794a8433a/src/Components/Components/src/Routing/RouteTableFactory.cs#L57) `error IL2026: Using member 'System.Reflection.Assembly.ExportedTypes.get' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Types might be removed.`

I suppose it's safe to assume that routeable component types won't get completely trimmed away, but what about their `[Parameter]` properties? Routable component types aren't passed directly into `RenderTreeBuilder.OpenComponent()` like other component types (and aren't preserved explicitly elsewhere, afaict). Do we have some other mechanism preserving routable component parameter properties that I'm not aware of? It seems if this were a real problem, we would have seen it by now.

---

[`DynamicComponent.cs(70,17):`](https://github.com/dotnet/aspnetcore/blob/bf50999cd8e60d4c683b772dffa9898794a8433a/src/Components/Components/src/DynamicComponent.cs#L70) `error IL2072: 'value' argument does not satisfy 'DynamicallyAccessedMemberTypes.All' in call to 'Microsoft.AspNetCore.Components.DynamicComponent.Type.set'. The return value of method 'Microsoft.AspNetCore.Components.ParameterValue.Value.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.`

I see we have a `[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]` on the `Type` property, but I don't think this helps because it's being assigned from the `ParameterView` entry anyway. Maybe this could be fixed by adding a `RenderTreeBuilder.AddAttribute()` overload that accepts a correctly-annotated `Type` argument, rather than relying on the overload accepting an `object`?

---

[`LayoutView.cs(59,24):`](https://github.com/dotnet/aspnetcore/blob/bf50999cd8e60d4c683b772dffa9898794a8433a/src/Components/Components/src/LayoutView.cs#L59) `error IL2072: 'layoutType' argument does not satisfy 'DynamicallyAccessedMemberTypes.All' in call to 'Microsoft.AspNetCore.Components.LayoutView.WrapInLayout(Type, RenderFragment)'. The return value of method 'Microsoft.AspNetCore.Components.LayoutView.GetParentLayoutType(Type)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.`

The `Layout` property is set using reflection, so it seems like this could be problematic. A new `RenderTreeBuilder.AddAttribute()` overload might fix this one too.

---

[`RouteView.cs(80,17):`](https://github.com/dotnet/aspnetcore/blob/bf50999cd8e60d4c683b772dffa9898794a8433a/src/Components/Components/src/RouteView.cs#L80) `error IL2111: Method 'Microsoft.AspNetCore.Components.LayoutView.Layout.set' with parameters or return value with DynamicallyAccessedMembersAttribute is accessed via reflection. Trimmer can't guarantee availability of the requirements of the method.`

It seems like there could be a legitimate issue here that could be fixed by annotating the `LayoutAttribute` constructor parameter with `[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]`.

**Comment by MackinnonBuck** [comment]
Thanks for taking a look, @SteveSandersonMS!

> Most uses with application components are fine because application assemblies aren't trimmed

Aha! This is something I wasn't aware of, and it drove a lot of the concerns I brought up in my last comment, so this is great to hear.

> [RouteTableFactory.cs(57,34)]
> If there is some way for the [Route] attribute to cause the trimmer to preserve that type, including all public API, then that would be ideal but I'm not sure the trimmer has a mechanism for this.

I'll go ahead and dismiss the warnings then since the framework doesn't contain routable components, as you stated.

> [DynamicComponent.cs(70,17)]
> The point of DynamicComponent is to use it with type values that vary at runtime, not just with fixed values.

Yeah, the AddAttribute overload wouldn't handle this case. And again, since application code doesn't get trimmed, we're probably safe here.

> [LayoutView.cs(59,24)], [RouteView.cs(80,17)]

Everything you said about these seems right to me. Annotating the `LayoutAttribute` constructor is probably the right move then.

I'll make these final changes and push a commit with them soon, possibly tomorrow.

**Comment by JamesNK** [comment]
@MackinnonBuck Please rebase this before merging. A few more projects support trimming since this PR was started. Hopefully, they don't introduce any new warnings, but we don't want to break the build if they do.

I'll handle any new trimming errors that show up.

**Review by JamesNK — APPROVED** [review]

**Comment by JamesNK** [comment]
@SteveSandersonMS Could you review the components changes?

**Review by SteveSandersonMS — APPROVED** [review]
Looks great!

**Pull request merged**
