### PR TITLE
Remove redux spa template

### LINKED ISSUE #32598: Remove the ReactRedux project template

### PR DESCRIPTION
**Pull request by HaoK**
Fixes https://github.com/dotnet/aspnetcore/issues/32598

### CODE REVIEW

**Comment by HaoK** [comment]
@phenning Other than nuking the files from the project templates build, are there any other changes I need to worry about that might affect things on the tooling side when removing a template from 6.0?

**Comment by phenning** [comment]
I don't believe so, however the pre 6.0 versions of the template will obviously still be available if installed.

**Comment by HaoK** [comment]
I think that's fine and expected I think, @mkArtakMSFT we aren't planning on removing the template for old versions are we?  I'm assuming just going forward

**Comment by javiercn** [comment]
@HaoK nope, just 6.0 and onwards

**Review by javiercn — APPROVED** [review]
LGTM!

**Comment by phenning** [comment]
If you do ever have a reason to do that, we do have a mechanism built into VS to "hide" templates by group id or even skip installing entire template nupkgs, based on a version range.

**Pull request merged**
