### PR TITLE
Make OIDC handler skip unrecognized requests

### PR DESCRIPTION
**Pull request by mderriey**
- Honor the `SkipUnrecognizedRequests` property by skipping them, as they currently throw

Addresses #10028

### CODE REVIEW

**Comment by mderriey** [comment]
I couldn't find tests against the OIDC handler for the Authenticate flow to make sure that this is not breaking existing behavior.

**Comment by Tratcher** [comment]
OIDC has some significant test gaps. https://github.com/aspnet/AspNetCore/issues/4681

**Review by Tratcher — APPROVED** [review]

**Comment by anurse** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=182662

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2303
https://github.com/aspnet/AspNetCore-Internal/issues/1929
https://github.com/aspnet/AspNetCore-Internal/issues/2494
https://github.com/aspnet/AspNetCore-Internal/issues/2250
https://github.com/aspnet/AspNetCore-Internal/issues/2451

**Comment by Tratcher** [comment]
Thanks

**Comment by mderriey** [comment]
Thank you, much appreciated!

**Pull request merged**
