### PR TITLE
Fix sign check

### PR DESCRIPTION
**Pull request by dougbu**
- most likely cause of failing official builds
- small typo in #10340

### CODE REVIEW

**Comment by dougbu** [comment]
https://dnceng.visualstudio.com/internal/_build/results?buildId=193171 is the official build to watch. Sign checks aren't done in PR validation.

**Comment by dougbu** [comment]
New trial official build is https://dnceng.visualstudio.com/internal/_build/results?buildId=193228

**Comment by dougbu** [comment]
New trial official build is https://dnceng.visualstudio.com/internal/_build/results?buildId=193489

**Review by joeloff — APPROVED** [review]

**Comment by dougbu** [comment]
https://dnceng.visualstudio.com/internal/_build/results?buildId=193489 was successful and Helix tests timed out due to a general delay in starting Windows jobs. Merging&hellip;

**Pull request merged**
