### PR TITLE
Same PR as https://github.com/aspnet/AspNetCore/pull/9001 because the build is not being triggered

### PR DESCRIPTION
**Pull request by javiercn**
Trying a different PR because the first one failed spectacurlarly

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
Project and eng/ changes _still_ look good 😸

**Review by ryanbrandenburg — APPROVED** [review]
ProjectTemplates parts seem fine.

**Comment by adrianwright109** [comment]
Looks like `src\Components\Server\ref\Microsoft.AspNetCore.Components.Server.netcoreapp3.0.cs` need re-generating.

**Comment by javiercn** [comment]
Yeah, I just pushed the update

**Review by pranavkm — APPROVED** [review]

**Comment by javiercn** [comment]
Closing as the original PR just succeded and I merged it

**Pull request closed without merging**
