### PR TITLE
Stop using optional catch binding in JSInterop

### LINKED ISSUE #39086: Net.Maui Blazor not running on Android 7.1 Tablet
### Description

The screen loading.... appears but nothing happens.
But...when i create a new project selecting net.maui app instead
of net.maui blazor the project runs just fine with Android 7.1 on
the same device.

### Steps to Reproduce

1. Create new Project and select net.maui blazor
2. Connect an Android 7.1 device mine here is a samsung tablet with lineage os 14.1
3. Simply start debugging or build the project and run it

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 7.1

### Did you find any workaround?

Nope.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by TanayParikh**
[Optional Catch Binding](https://2ality.com/2017/08/optional-catch-binding.html) was introduced in EcmaScript2019. [Some users are reporting](https://github.com/dotnet/aspnetcore/issues/39086#issue-1082703158) that this particular usage is causing the Blazor Hybrid app to crash on certain older Android devices. Given this is an _extremely_ minor change, I don't see any harm in not using this feature in one location so that we can continue to support those devices.

Fixes: https://github.com/dotnet/aspnetcore/issues/39086

### CODE REVIEW

**Review by SteveSandersonMS — APPROVED** [review]

**Comment by BrennanConroy** [comment]
I dislike changes like this because we're likely to use the feature again in the future since nothing is stopping us from using valid syntax. And it's even likely that some linter could flag this as unnecessary code and we'll remove it.

We should instead be recommending folks to transpile to older ECMA standards if they are running on old OS/platforms.

**Comment by TanayParikh** [comment]
> We should instead be recommending folks to transpile to older ECMA standards if they are running on old OS/platforms.

The tricky thing here is for something like Blazor Hybrid, we officially support anything Android 21+. Most developers won't run into this issue or even know it may be necessary to transpile to support devices which would otherwise be compatible being Android 21+. Maybe we need to add the transpilation step as part of our normal build pipelines 🤔

**Comment by BrennanConroy** [comment]
At that point we might as well just move all the code to a lower ECMA standard and compile for the lowest version we want to support. There could be other new features that will break old platforms not just the empty catch clauses.

**Comment by TanayParikh** [comment]
> Perhaps there's a linter rule we could add to ensure this syntax doesn't creep back in

Doesn't appear to be an eslint rule that specifically facilitates disallowing the optional catch binding.

> At that point we might as well just move all the code to a lower ECMA standard and compile for the lowest version we want to support

Seeing if we can compile against ES2018

**Comment by TanayParikh** [comment]
> > At that point we might as well just move all the code to a lower ECMA standard and compile for the lowest version we want to support
> 
> Seeing if we can compile against ES2018

Downgraded TSLint `compilerOptions.Target` and eslint `env` to ES2018 but still no errors interestingly. I've created https://github.com/dotnet/aspnetcore/issues/40741 to investigate further.

> There could be other new features that will break old platforms not just the empty catch clauses.

I think I'll just merge this in for now and let https://github.com/dotnet/aspnetcore/issues/40741 handle the other cases. From the user reports in the original issue (https://github.com/dotnet/aspnetcore/issues/39086#issuecomment-995700125) it was this (and only this) causing compatibility issues for them.

**Review by Eilon — APPROVED** [review]
I ain't no expert, but this change does fix the specific problem we have. And from my perspective we can try to future-proof this in a follow-up issue as others have suggested.

**Comment by SteveSandersonMS** [comment]
Since "transpile to ES2018" is tracked as a separate issue, the solution here seems like a good, focused solution in the meantime. (Already approved, but re-affirming!)

**Review by javiercn — APPROVED** [review]

**Pull request merged**
