### PR TITLE
Add build for linux-musl-arm

### PR DESCRIPTION
**Pull request by janvorli**
This change adds building of linux-musl-arm packages of ASP.NET Core.

### CODE REVIEW

**Comment by dougbu** [comment]
@janvorli what requirement is behind this PR❔ And, should it be in 5.0❔

Separately, have you tried building this job without `useHostedUbuntu: false` i.e. using the hosted agents❔

/cc @Pilchie for awareness and resource implications

**Comment by janvorli** [comment]
> what requirement is behind this PR

We want to enable end to end .NET Core support for Alpine ARM Linux. It has been requested by the community for quite some time. I have discussed it with @richlander and we have agreed that we should do it if it doesn't require too much work to enable.   So far we had only Alpine ARM64 support. So far I've created the necessary docker images and made runtime changes, so this is a next step.

> And, should it be in 5.0

It would be nice, but it is not a hard requirement.

> Separately, have you tried building this job without useHostedUbuntu: false i.e. using the hosted agents

No, can you please help me understand what is it good for? I can see that it uses ubuntu-16.04 VM and I know the build doesn't build there due to the fact that the cross building image for runtime is based on Ubuntu 18.04, so crossgen fails to execute. Is that a problem? If it is, I can add cross building ubuntu-16.04 docker images targeting Alpine ARM and switch runtime to build on that one.

**Comment by dougbu** [comment]
> No, can you please help me understand what is it good for?

That setting is useful where the build uses more disk space than hosted agents provide. But, ignore me because the Linux MUSL Arm64 probably has it for a reason.

**Review by dougbu — APPROVED** [review]
Fine w/ me. Any objection @Pilchie❔

**Comment by Pilchie** [comment]
Seems fine to me.

**Comment by janvorli** [comment]
@dougbu, @Pilchie I've incorrectly assumed that the change will automatically flow into release/5.0, since I've seen 5.0-rc2 packages generated after my change went in. But looking at the release/5.0 branch, I cannot see my commit to be there.
I wonder - given the fact that it is just an infra change, would it still be possible to get it to release/5.0 branch or will it have to wait for the next update release?

**Comment by dougbu** [comment]
@janvorli this isn't really "just an infra change" because it expands the platform. Why would we port it to the release/5.0 branch given your [earlier comment](https://github.com/dotnet/aspnetcore/pull/26281#issuecomment-698545802) about needing the change to 5.0❔
> It would be nice, but it is not a hard requirement.

**Comment by janvorli** [comment]
@dougbu - since I've seen 5.0-rc2 nuget packages were available on the nuget servers for linux-musl-arm after my change, I've assumed that it somehow made it to 5.0 and we've back ported the related runtime change to 5.0. Now there was an attempt to build docker image for linux-musl-arm, which revealed that the aspnetcore tarball doesn't actually exist.
Anyways, it is fine to get it in for the servicing release. I just wanted to know the options we have.

**Comment by Pilchie** [comment]
I think it's fine to add for 5.0.1, but I don't understand how there were packages for rc2 and not GA. The commit above looks like it was only ever in `master`, so I don't see how any packages were ever produced for rc2.

**Pull request merged**
