### PR TITLE
Update SDK, re-enable Win7

### LINKED ISSUE #21555: Enable win7 in Helix jobs
To revert https://github.com/dotnet/aspnetcore/pull/21553 once it works again

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/dotnet/aspnetcore/issues/21555

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Tested Win7 and it passed https://dev.azure.com/dnceng/public/_build/results?buildId=636904&view=ms.vss-test-web.build-test-results-tab

**Review by Pilchie — APPROVED** [review]
Doesn't this require a new runtime too?

**Comment by BrennanConroy** [comment]
I don't quite understand how it all works, but I think updating the SDK comes with a new runtime. That's how updating just the SDK caused us to consume the runtime change that broke Win7.

**Comment by Pilchie** [comment]
Okay - let's go with it if your testing shows it worked.

**Comment by BrennanConroy** [comment]
I'll make sure to keep an eye on rolling builds over the weekend.

**Comment by dougbu** [comment]
@BrennanConroy what led you to update the SDK slightly in this PR?

**Comment by BrennanConroy** [comment]
So we could consume the fix for the Win7 hangs

**Pull request merged**
