### PR TITLE
Remove extra cast for IPEndPoint

### PR DESCRIPTION
**Pull request by Kahbazi**

### CODE REVIEW

**Review by analogrelay — APPROVED** [review]
Nice little clean-up. Thanks!

**Comment by anurse** [comment]
@Kahbazi FYI, to set some context, we don't ever intend to ship the MsQuic transport in an official release. It's a stop-gap to allow us to do some prototyping/testing while the `System.Net.Quic` library is developed in dotnet/runtime. I'd expect this transport to go away fairly soon and be replaced by a "Quic" transport that uses `System.Net.Quic` directly.

Most of this code is being ported over to become an initial implementation of `System.Net.Quic`, which is happening in https://github.com/dotnet/runtime/pull/427

**Comment by anurse** [comment]
(Happy to merge this still, but just wanted to warn you before you dive deep in to contributions to this transport library)

**Comment by Kahbazi** [comment]
@anurse thanks for the info :)

**Pull request merged**
