### PR TITLE
Help details around which environment vars to set

### PR DESCRIPTION
**Pull request by avanderhoorn**
I was trying to figure out how to set override feeds and couldn't find any details on this in the console help. This describes the required keys to be set.

### CODE REVIEW

**Comment by avanderhoorn** [comment]
//cc @lodejard @davidfowl @glennc

**Comment by Eilon** [comment]
BTW to propose changes to dnvm please send PRs/issues to https://github.com/aspnet/dnvm.

**Comment by Eilon** [comment]
The dnvm in this repo is the "built" dnvm, as opposed to being the source code.

**Comment by avanderhoorn** [comment]
Thanks mate!

**Pull request closed without merging**
