### PR TITLE
Fix build on arm64 machines

### PR DESCRIPTION
**Pull request by omajid**
Building ASP.NET Core on an arm64 machine using `./build.sh -arch arm64` leads to a dependency error because crossgen2 is not listed in eng/Dependencies.props.

### CODE REVIEW

**Comment by dougbu** [comment]
This might be a valid problem to fix @omajid but I'm not seeing any difference in the `crossgen2` output near the end of the Linux_arm64 job in your validation build [20211007.33](https://dev.azure.com/dnceng/public/_build/results?buildId=1409390&view=results) and a recent build of 'main' e.g. [20211007.27](https://dev.azure.com/dnceng/public/_build/results?buildId=1409140&view=results).

Could you please describe in more detail what fails without this fix❔

**Review by mesutozturk — APPROVED** [review]
ok

**Review by dougbu — COMMENTED** [review]
Thanks very much for the added information @omajid❔ Let's at least cover all available variants of the `crossgen2` package in this PR.

I'm not positive how best to handle the code in Microsoft.AspNetCore.App.Runtime.csproj but that can wait. Likely we should make some of that understand the _actual_ OS architecture. Could you please open an issue listing the potential problems you see there❔ (mention me in it so I don't miss it 😄)

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
Up to you @Pilchie. The fix here and however we address #37400 will have minimal impact on our pipeline builds but will reduce barriers for contributors building the shared Fx on other systems. Let me know if we should backport this.

**Comment by omajid** [comment]
A little late to the party here, but thanks for backporting it to release/6.0! I ran into this bug while building source-build (including ASP.NET Core) on arm64, and it's definitely affecting us (Red Hat) for 6.0. We are carrying a patch locally for 6.0 to bypass this, so it's great to see an official fix landing.

**Pull request merged**
