### PR TITLE
Shorten test names to avoid hitting Windows path length limits

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
Should fix the issues a few people have hit in the last hour or so.

@mkArtakMSFT I've added `auto-merge` but if this needs any further manual actions to merge after CI completes, would you be able to press the button? I'm not going to be around after the 1-2 hours needed for CI checks to complete.

### CODE REVIEW

**Review by HaoK — APPROVED** [review]

**Comment by HaoK** [comment]
@SteveSandersonMS I can help you get this in

**Comment by SteveSandersonMS** [comment]
Thanks @HaoK!

**Comment by dougbu** [comment]
Retrying to pick up @wtgodbe's #30253 fix

**Pull request merged**
