### PR TITLE
Merging release branch over to master

### PR DESCRIPTION
**Pull request by analogrelay**
There are some changes needed to update 'release' to 'master'. Here's a PR for the changes for a quick review.

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@anurse__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor (Andrew Stanton-Nurse). If you're full-time, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla2.msopentech.com.
    </p>

TTYL, MSOTBOT;

**Comment by anurse** [comment]
FYI, most of the `kvm` changes are just pulling up the latest versions from aspnet/kvm. Do double check the feed used though, it should be nuget.org in both kvms.

**Comment by muratg** [comment]
:shipit:

**Comment by anurse** [comment]
This is merged. Not sure why it didn't close...

**Pull request closed without merging**
