### PR TITLE
Update CredScanSuppressions.json

### PR DESCRIPTION
**Pull request by BrennanConroy**
Moved the certs to a shared location for other SignalR tests in another PR, forgot about this file.

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Review by dougbu — APPROVED** [review]
Surprised I'm not getting code-mirror failure emails but agree this is necessary.

**Comment by dougbu** [comment]
Any reason I shouldn't set auto-squish @BrennanConroy❔

**Comment by BrennanConroy** [comment]
Go for it

**Comment by dougbu** [comment]
Oddly, I can't for some reason. Thought I'd done this elsewhere in release/7.0 but maybe not&hellip; Same for you @wtgodbe❔

**Comment by BrennanConroy** [comment]
It looks like it'll let me Squash and merge without waiting for builds. There aren't any required pipelines for release/7.0

**Comment by dougbu** [comment]
Ah, it was my bad. I changed the branch protection rules in order to clean up a couple of old branches. Forgot to reset protections ☹️. All is well now and `auto-merge (squash)` is set to go.

**Comment by dougbu** [comment]
Does this need to be backported to the rc1 branch @BrennanConroy❔

**Comment by BrennanConroy** [comment]
Why? That branch is temporary. Do we really care about CG alerts for it when we know they're going away soon?

**Comment by Pilchie** [comment]
Given these are just suppressions and not real credential issues, I'm not worried about causing more churn in the rc1 branch for this.

**Comment by BrennanConroy** [comment]
That comment can be interpreted either way 😆, yes or no to backporting to release/7.0-rc1?

**Comment by Pilchie** [comment]
Sorry - no need to backport to release/7.0-rc1.

**Comment by dougbu** [comment]
> Why?

Sorry it was an actual question, not a statement of a requirement. I was wondering if the files had been renamed in RC1 w/o this update because that would cause build breaks IIRC.

**Comment by BrennanConroy** [comment]
The files were renamed in RC1, the suppressions have been updated in RC2 and main.

What build breaks would not having the suppression cause?

**Comment by dougbu** [comment]
Not exactly "build breaks". The missing suppression should cause CredScan errors and issues filed against us and that we need to handle for RC1. If @Pilchie is fine dismissing the issues, we're good.

**Pull request merged**
