### PR TITLE
Update default project names

### PR DESCRIPTION
**Pull request by JunTaoLuo**
Addresses https://github.com/aspnet/AspNetCore/issues/11820. 

WIP testing.

### CODE REVIEW

**Review by JamesNK — APPROVED** [review]
gRPC change 👍

**Comment by JunTaoLuo** [comment]
I'll test this out in VS tomorrow.

**Review by ryanbrandenburg — APPROVED** [review]

**Comment by ryanbrandenburg** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=276829

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2617

**Comment by SteveSandersonMS** [comment]
@danroth27 I remember you were making plans about template names. Are these the template names you wanted?

**Review by danroth27 — APPROVED** [review]
LGTM

**Comment by danroth27** [comment]
@stevesandersonms This PR will clean up the default project names generated by the templates in VS. Changing the template names I believe was already done.

**Comment by JunTaoLuo** [comment]
Turns out we can't test this without VS work so I'm merging as is.

**Pull request merged**
