### PR TITLE
Build targeting pack in 5.0.2

### PR DESCRIPTION
**Pull request by wtgodbe**
In response to the API change that was introduced by https://github.com/dotnet/aspnetcore/pull/27907

### CODE REVIEW

**Review by pranavkm — APPROVED** [review]

**Comment by JunTaoLuo** [comment]
I think we'll need to get the SDK to pick up this new targeting pack too right?

**Comment by wtgodbe** [comment]
> I think we'll need to get the SDK to pick up this new targeting pack too right?

Should happen automatically, their dependency isn't pinned: https://github.com/dotnet/installer/blob/2c2ffa1ed85763da18007b54b1c2a9eb445a01a3/eng/Version.Details.xml#L50-L53

**Comment by wtgodbe** [comment]
We will need to update the template version in master, though.

**Comment by wtgodbe** [comment]
Waiting until this can be picked up by partner teams before we service it

**Comment by mmitche** [comment]
@wtgodbe Is this something for 5.0.3?

**Comment by wtgodbe** [comment]
We were going to wait until the 5.0.1 SDK had been rolled out to azure appService before patching the targeting pack - @Pilchie do you know if that's the case yet?

**Comment by Pilchie** [comment]
I don't see it yet, sent an email to follow-up on the ETA.

**Comment by dougbu** [comment]
@wtgodbe this PR can be closed (abandoned), right❔

**Pull request closed without merging**
