### PR TITLE
Add baseline test

### PR DESCRIPTION
**Pull request by mikaelm12**
Issue: https://github.com/aspnet/AspNetCore/issues/7969

### CODE REVIEW

**Comment by mikaelm12** [comment]
Updated based on feedback here: https://github.com/aspnet/AspNetCore/pull/8014#discussion_r261057170

**Review by dougbu — APPROVED** [review]

**Comment by mikaelm12** [comment]
Seems like release 2.2 is now a protected branch and I can't merge this

**Comment by dougbu** [comment]
@mikaelm12 do you want it Squash & Merged?

**Comment by mikaelm12** [comment]
> do you want it Squash & Merged?

Yup, exactly

**Pull request merged**
