### PR TITLE
Making new projects order explicit

### PR DESCRIPTION
**Pull request by mkArtakMSFT**
Addresses https://github.com/aspnet/AspNetCore/issues/9460

### CODE REVIEW

**Review by ryanbrandenburg — APPROVED** [review]

**Comment by mkArtakMSFT** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=160944&view=ms.vss-test-web.build-test-results-tab

**Comment by danroth27** [comment]
@mkArtakMSFT  What about the client-side Blazor templates?

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2328
https://github.com/aspnet/AspNetCore-Internal/issues/2300

**Comment by davidfowl** [comment]
Where's the screenshot?

**Comment by mkArtakMSFT** [comment]
You can find the new order of project templates here: https://github.com/aspnet/AspNetCore/issues/9460#issuecomment-484609060

**Pull request merged**
