### PR TITLE
Add analyzer to detect async void usage

### LINKED ISSUE #28217: Add analyzer to detect async void usage in MVC filter usage
People aren't aware that IAsync*Filters exist and instead use the synchronous ones with async void. It's pretty common and the errors you get are bizzare. Make this an error and offer a codefix to change the synchronous filter to an async one.

### PR DESCRIPTION
**Pull request by z77ma**
# Add analyzer to detect async void in controller actions, filters, razor page handlers, and signalr hub methods

Added a single analyzer to detect a misusage of the 'async void'. Created a new diagnostic description (ASP0011). 

## Description

The analyzer tracks class declarations and if a class is in a set of categories (controller, filter, razor page, signalr hub), the analyzer scans members of the class in attempt to find 'async void' statement on a member declaration. The members are filtered and only methods are processed. The analyzer scans all methods (disregarding their access modyfier, virtuality, etc.) in classes that belong to controllers, signalr hubs, and implementations of non-async filters. In case the class belongs to the razor page, only handler-like methods are scanned (to this category relate methods that follow a pattern 'On + HTTP method'.

## Open questions

* Startup.Configure/ConfigureServices is not covered within this PR. I'd appreciate suggestions on how the Startup class should be detected. Currently I see 2 options. The first one, very simple and straightforward, lookup the class by its' name and if it or one of ancestors contains a 'Startup' part in its' name, and additionally the Configure/ConfigureServices methods are present, then start 'async void' detection process. The second option is to detect an operation with the kind of the 'OperationKind.Invocation', if this is UseStartup method invocation, fetch a generic type passed and analyze this type on having 'async void' in a method declaration. Though the second option looks more reliable I doubt it is feasible.
* In either case, should the analyzer for the Startup class be present in this PR or it's possible to create a standalone later?
* With this PR only 4 HTTP mehods are considered to be valid in scope of Razor Pages (these are GET, POST, PUT, and DELETE). The method names are checked to follow the pattern 'On + HTTP method'. Should this list be extended and cover all existing?
* Should the analyzer consider all methods that are declared in a class that implements an I*Filter interface? Or it should track only methods that are implementation of the interface?
* The PR doesn't introduce a code fix for the analyzer. Is it required in this situation? If yes, could the code fix be provided in another PR?

Fixes #28217 (not completely, see questions)

### CODE REVIEW

**Comment by z77ma** [comment]
Hi, @davidfowl, @BrennanConroy, @pranavkm, apologies for the direct tagging, but since you all participated in the issue discussion I think your opinion/input to this PR would be benefitial.

**Review by sharwell — CHANGES_REQUESTED** [review]
It would be preferential to use production-ready analyzers [VSTHRD100](https://github.com/microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD100.md) and [VSTHRD101](https://github.com/microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD101.md) rather than re-implement this logic.

There are a number of issues within this implementation, but I'm leaving that discussion for after the resolution of the bigger question of whether we need this at all.

**Comment by Pilchie** [comment]
Note that there is some prior art here in the VS analyzers:

* https://github.com/microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD100.md
* https://github.com/microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD101.md

**Comment by sharwell** [comment]
We typically discourage implementing two analyzers that do the same thing for a few reasons:

1. It's difficult to coordinate bug fixes and/or performance improvements because the authors are typically operating independently
1. Users who install both analyzer packages would end up seeing two warnings for a violation, and possibly two fixes (one for each diagnostic reported)

Since we already have a well-known analyzer that flags uses of `async void`, we'd want to first show that this analyzer is insufficient before trying to create a totally different one.

**Comment by pranavkm** [comment]
@sharwell is it possible to move the VS analyzers to a Roslyn-Analyzers? Asking ASP.NET Core users to configure VS specific analyzers isn't very intuitive.

**Comment by sharwell** [comment]
We've had some discussion about moving them, but it's mostly just for the name at that point. The analyzer package should already work seamlessly in ASP.NET scenarios. Separately from that discussion, I'm interested to know if the rules implemented in that project are sufficient for adoption by ASP.NET developers (the semantics are a bit different, but I'm hoping that won't be a problem in practice).

**Comment by davidfowl** [comment]
These analyzers could give more specific suggestions about alternate APIs to use in various cases though...

**Comment by pranavkm** [comment]
> These analyzers could give more specific suggestions about alternate APIs to use in various cases though...

@davidfowl do you have a sense for what that looks like? Outside of the MVC filter ones (and I'm not sure that one is incredibly valuable), the fix is a general purpose change the signature to be `async Task`. 

My gripe is having to having to ask users to reference the VS threading package to benefit from the analysis. The users most likely to use `async void` are also less likely to read our docs and guidance for best practices.

**Comment by sharwell** [comment]
> These analyzers could give more specific suggestions about alternate APIs to use in various cases though...

One option here is updating the documentation for the VSTHRD diagnostics to include the more specific information. Users that click the diagnostic ID will be taken to the documentation page.

> My gripe is having to having to ask users to reference the VS threading package to benefit from the analysis. The users most likely to use `async void` are also less likely to read our docs and guidance for best practices.

A few options exist to resolve this.

* It may be possible to update new project templates to install these analyzers automatically with a modified "ASP.NET" specific default configuration provided through a .globalconfig.
* It may be possible to migrate one or more analyzers from vs-threading to roslyn-analyzers. This approach may still require the templates be updated to configure the default severity of the migrated analyzers.

**Comment by sharwell** [comment]
@davidfowl @pranavkm Please let me know if you have any questions or want to loop in additional people. If you decide that existing analyzers are insufficient for the repository, I need to go back and review this from a perspective of intent-to-merge.

**Comment by davidfowl** [comment]
I would want 2 things:
- The async void analyzer on by default in ASP.NET Core applications.
- This analyzer should suggest async variants of the MVC interfaces when async void is detected when using the sync variants (and if applicable anywhere else, Razor pages?)

**Comment by sharwell** [comment]
> This analyzer should suggest async variants of the MVC interfaces when async void is detected when using the sync variants (and if applicable anywhere else, Razor pages?)

Can you give a concrete example? vs-threading analyzers support some scenarios like this already, and if it doesn't cover this one already it might be possible to add.

**Comment by davidfowl** [comment]
> @davidfowl We do have precedent for using AdditionalFiles to configure or enlighten our analyzers for app-specific purposes. We could potentially add a new AdditionalFiles file for this analyzer that ASP.NET Core projects could include (via .targets in another package) that would tell the analyzer what to recommend for various interfaces.

I'm open to that. I still want it on by default for these types of apps though.

**Comment by z77ma** [comment]
Sorry for reviving this topic, but the results of the discussion are vague for me.
At first, let me add my 50 cents as a potential end-user of this enhancement. I do understand that duplication of code or functionality is a flaw that should be avoided at any price. But, as the end-user of these checks I'd like to see these analyzers a part of the framework. The reason for this is simple - less actions from the user side. This might sound "unprofessional", but actually comes from my previous experience in syncing a code-style and enforce good practices in multiple low coupled (but still operating within a one project) teams. Also, producing errors instead of warnings, is obviously more restrictive, and so that beneficial for the right usage of the framework. Cause I easily could imagine the situation where the warnings about the "async void" usage are suppressed instead e.g. a global section of the editorconfig.
Though I must admit, I'm out of the context of your ideas, or plans, or views on how things should be organized, and the above is my understanding of the proposed changes and ways how they could be used.
Disregarding all the above, is there anything I still could help you with? Should I move my changes into another repository? Adopt them somehow? Or just close this PR?

**Comment by z77ma** [comment]
@sharwell, @davidfowl, @pranavkm, I'd appreciate any comment on the question above

**Comment by mkArtakMSFT** [comment]
@davidfowl would you please drive this conversation to completion? Thanks!

**Pull request closed without merging**
