### PR TITLE
Propogate repair commands to inner bundles in Hosting Bundle

### LINKED ISSUE #33572: Hosting bundle does not propagate repair commands to inner bundles
The hosting bundle nests the .NET runtime bundles. It defines separate install commands, but does not define a repair command. When the hosting bundle is executed from the commandline with ```/quiet /repair```, it will repair ASP.NET Core and ANCM (because they are toplevel MSIs), but it won't repair the .NET runtime bundles.

The ```ExePackage``` in https://github.com/dotnet/aspnetcore/blob/963242a12c8b149caee5a9fa3215a8452a4be999/src/Installers/Windows/WindowsHostingBundle/DotNetCore.wxs#L12

needs to be modified to also include

```RepairCommand="/quiet /repair"```

### PR DESCRIPTION
**Pull request by wtgodbe**
Should fix https://github.com/dotnet/aspnetcore/issues/33572

@joeloff how can I test this once I have a build?

### CODE REVIEW

**Review by joeloff — APPROVED** [review]
Awesome, thanks for the quick turn around

**Comment by joeloff** [comment]
> Should fix #33572
> 
> @joeloff how can I test this once I have a build?

Clean machine is best, just to make it easier to find the logs. Install the hosting bundle, then from a commandline, run the bundle with ```/repair /quiet```.

In the repair log of the hosting bundle you should see it invoking the dotnet runtime bundles with /repair. But if it did, you should also see setup logs from the runtime bundle appearing in %temp%.

**Review by dougbu — APPROVED** [review]

**Pull request merged**
