### PR TITLE
Move extension method out of Microsoft.AspNetCore

### LINKED ISSUE #11022: Change namespace of StaticWebAssets extension method
It should be under the Microsoft.AspNetCore.Hosting namespace.

### PR DESCRIPTION
**Pull request by javiercn**
Fixes #11022

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]

**Review by davidfowl — APPROVED** [review]
❤️

**Comment by javiercn** [comment]
@aspnet/build The status is not getting updated in this PR and is preventing the merge.

**Comment by davidfowl** [comment]
> @aspnet/build The status is not getting updated in this PR and is preventing the merge.

On every single PR it seems.

**Comment by javiercn** [comment]
I've asked @mkArtakMSFT to use the hammer.

**Comment by mkArtakMSFT** [comment]
Merging as it seems the checks have passed, but the status isn't reflected here.

**Pull request merged**
