### PR TITLE
Reverting SDK

### PR DESCRIPTION
**Pull request by sebastienros**
CI is failing with the new version on ARM

### CODE REVIEW

**Comment by sebastienros** [comment]
Example failure https://dev.azure.com/dnceng-public/public/_build/results?buildId=355133&view=logs&j=4a1f0fe1-d87a-57fd-c29d-71ea15e38f30&t=e34518a7-7ef2-58fc-776d-024f679b17d8

**Comment by eerhardt** [comment]
Can you log an issue on either dotnet/runtime or dotnet/sdk so someone can investigate this?

**Review by eerhardt — APPROVED** [review]

**Comment by sebastienros** [comment]
https://github.com/dotnet/sdk/issues/34316

**Review by joperezr — APPROVED** [review]
Thanks for the quick turnaround Seb.

**Comment by joperezr** [comment]
There is a newer SDK build available now (8.0.100-rc.1.23377.5), but it is from the same day so of course it is very likely going to have the same issue.

**Review by wtgodbe — APPROVED** [review]

**Pull request merged**
