### PR TITLE
[release/6.0] Set aria-current for manage pages

### PR DESCRIPTION
**Pull request by HaoK**
Cherrypick of https://github.com/dotnet/aspnetcore/pull/37110 to 6.0

Fixes accessiblity issue: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1411043/

## Customer Impact

Fixes accessibility issue by adding aria-current="page" to the selected manage page to help illustrate what the current page is

## Testing
Manual using the default identity ui sample

## Risk
Low, just adds a new aria-current="page" attribute to the manage pages

### CODE REVIEW

**Comment by HaoK** [comment]
@Pilchie can we take this for 6.0?

**Comment by HaoK** [comment]
@dougbu any idea why the codecheck is failing here?  This PR does add new public surface area but its in the unshipped.txt, and it was fine in main, so not sure why its failing in release/6.0 
```
Detected modification to baseline API files. PublicAPI.Shipped.txt files should only be updated after a major release. See /docs/APIBaselines.md for more information.
```

**Comment by dougbu** [comment]
> @dougbu any idea why the codecheck is failing here?

It's failing because (a) CodeCheck.ps1 treats the release/6.0 as if we're already in servicing (we decided not to complicate the script even though this branch is currently "special") and (b) the error is misleading and should be complaining about Unshipped.txt changes (which aren't allowed when servicing).

In any case, I'll ignore the failure when getting this in after it's been servicing approved.

**Comment by HaoK** [comment]
@dotnet/aspnet-build this has been approved, can we get this merged?

**Pull request merged**
