### PR TITLE
Update Angular and React-Redux templates

### PR DESCRIPTION
**Pull request by rachelgshaffer**
There are upcoming changes to Visual Studio's default ESLint configuration. The changes to the templates here ensure that there won't be any lint warnings for these project types.

### CODE REVIEW

**Comment by javiercn** [comment]
@danroth27 Thoughts?

**Comment by mkArtakMSFT** [comment]
Thanks for the PR, @rachelgshaffer.
The way we currently build these is we create new angular/react projects using appropriate framework CLI and use the content almost as is. It looks like this is going to impact that process, will it? Or are you planning to also submit similar PRs to the third-party projects to make sure the default projects they create accounts for these too?

**Comment by rachelgshaffer** [comment]
Ah I didn't realize these were generated files, thanks for pointing that out @mkArtakMSFT 
I see there is a script for Angular here: `src\ProjectTemplates\scripts\Run-Angular-Locally.ps1` but it's not clear where it's actually invoking the Angular CLI. Could you point me to any relevant code paths so I can understand how the CLI is called? I would greatly appreciate a breadcrumb. Thanks!

**Review by ryanbrandenburg — APPROVED** [review]
@mkArtakMSFT what she's doing won't interfere with our update Angular workflow (at least not any more than it already is).

@rachelgshaffer I could have sworn I reviewed this yesterday but apparently I didn't hit submit?

Anyway, overall this looks great. My only question is what ESLint rule the Layout.tsx changes fix and if there's any behavior change due to that fairly significant alteration.

Once I understand that better I can merge this in.

**Comment by rachelgshaffer** [comment]
Thanks @ryanbrandenburg 

For `Layout.tsx` the rule is [react/display-name](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/display-name.md). Everything compiled and ran fine for me when I tested it.

**Comment by ryanbrandenburg** [comment]
Sounds good about the react/display-name thing. It does seem there's a legit failure in the tests though:
```
19:83  error  Definition for rule '@typescript-eslint/no-explicit-any' was not found  @typescript-eslint/no-explicit-any
```

Should be fixable by adding `
    "plugins": [
      "@typescript-eslint"
    ]` to the .eslintrc.json. You can check that it works locally by running `yarn install && yarn lint`.

I think it should be mergeable once that's done.

**Comment by ryanbrandenburg** [comment]
Thanks @rachelgshaffer!

**Pull request merged**
