### PR TITLE
Replace custom DateTimeFormatter with ToString("r") or TryFormat

### PR DESCRIPTION
**Pull request by khellang**
Removes some code and gives a tiny perf gain:

image

### CODE REVIEW

**Comment by khellang** [comment]
The CI build seems pretty borked... 🙈

**Comment by Tornhoof** [comment]
Is the utf8formatter actually faster than the utf16 Version? @stephentoub optimized the utf16 Version a few months ago, they are pretty much equal now.

**Comment by khellang** [comment]
Yeah, the length is fixed, but depends on whether it's quoted or not. I guess I could split it in two methods...

**Comment by Tornhoof** [comment]
I mean the normal dto.``TryFormat``.

**Comment by stephentoub** [comment]
> The UTF16 version?

DateTimeOffset.ToString("r") (or TryFormat if you want to write into a span)

**Comment by stephentoub** [comment]
Just as a point of reference, given this benchmark:
```C#
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Attributes.Jobs;
using BenchmarkDotNet.Running;
using System;
using System.Buffers;
using System.Buffers.Text;
using System.IO;
using System.Text;

[MemoryDiagnoser]
[InProcess]
public class Test
{
    private static readonly StandardFormat _dateTimeRoundtripFormat = StandardFormat.Parse("R");
    private static readonly DateTimeOffset _dto = DateTimeOffset.UtcNow;

    [Benchmark]
    public string Utf8FormatterTryFormat()
    {
        Span<byte> span = stackalloc byte[29];
        Utf8Formatter.TryFormat(_dto, span, out int bytesWritten, _dateTimeRoundtripFormat);
        return Encoding.UTF8.GetString(span);
    }

    [Benchmark]
    public string DtoToString() => _dto.ToString("r");

    [Benchmark]
    public string DtoTryFormat() =>
        string.Create(29, _dto, (span, dt) => dt.TryFormat(span, out int charsWritten, "r"));

    public static void Main() => BenchmarkRunner.Run<Test>();
}
```
I get these results locally:
```
                 Method |     Mean |     Error |    StdDev |  Gen 0 | Allocated |
----------------------- |---------:|----------:|----------:|-------:|----------:|
 Utf8FormatterTryFormat | 99.28 ns | 0.8132 ns | 0.7209 ns | 0.0190 |      80 B |
            DtoToString | 58.43 ns | 0.8340 ns | 0.7801 ns | 0.0190 |      80 B |
           DtoTryFormat | 73.03 ns | 0.6526 ns | 0.6105 ns | 0.0190 |      80 B |
```

**Comment by khellang** [comment]
Huh, so a regular `DateTimeOffset.ToString("r")` is actually the fastest and allocates the same?

That's very nice. As it should be. Back to the code from the very beginning (before https://github.com/aspnet/HttpAbstractions/pull/716) then 👌

**Comment by Tornhoof** [comment]
If you add the quotes, the String.create is probably better, instead the old version.

**Comment by Tornhoof** [comment]
Benchmark:

``` ini

BenchmarkDotNet=v0.11.3, OS=Windows 10.0.17763.194 (1809/October2018Update/Redstone5)
Intel Core i9-9900K CPU 3.60GHz, 1 CPU, 16 logical and 8 physical cores
.NET Core SDK=3.0.100-preview-009812
  [Host]     : .NET Core 3.0.0-preview-27122-01 (CoreCLR 4.6.27121.03, CoreFX 4.7.18.57103), 64bit RyuJIT
  Job-ZHKYSL : .NET Core ? (CoreCLR 4.6.27121.03, CoreFX 4.7.18.57103), 64bit RyuJIT

Toolchain=custom .NET Core  UnrollFactor=2  

```
|                  Method |      Mean |     Error |    StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|------------------------ |----------:|----------:|----------:|------------:|------------:|------------:|--------------------:|
| DtoToStringFormatQuotes | 118.11 ns | 2.4338 ns | 2.8973 ns |      0.0188 |           - |           - |               120 B |
|      DtoTryFormatQuotes |  58.70 ns | 0.2224 ns | 0.1972 ns |      0.0139 |           - |           - |                88 B |


for the following extension to @stephentoubs benchmark from above:

```csharp
[Benchmark]
public string DtoToStringFormatQuotes() => string.Format("\"{0:R}\"", _dto);

[Benchmark]
public string DtoTryFormatQuotes() =>
    string.Create(31, _dto, (span, dt) =>
    {
        span[30] = '"';
        span[0] = '"';
        dt.TryFormat(span.Slice(1), out int charsWritten, "r");
    });

**Review by stephentoub — APPROVED** [review]

**Review by pakrym — APPROVED** [review]

**Pull request merged**
