### PR TITLE
Disable SDL, increase timeout to 4.5 hours

### PR DESCRIPTION
**Pull request by wtgodbe**
1. Disable SDL while we work on https://github.com/aspnet/AspNetCore/issues/16835
2. Increase the timeout while we investigate the signing issues that have been happening recently

CC @aspnet/build

### CODE REVIEW

**Review by JunTaoLuo — APPROVED** [review]

**Comment by JunTaoLuo** [comment]
File an issue to decrease the timeout after we resolve the current issues?

**Review by dougbu — COMMENTED** [review]
I'm conflicted about disabling this check in 'release/3.1' instead of completing work on #16835. How difficult is creating the exclusion file?

Deferring to @Pilchie&hellip;

**Comment by wtgodbe** [comment]
> I'm conflicted about disabling this check in 'release/3.1' instead of completing work on #16835. How difficult is creating the exclusion file?

I want to minimize risk/build time in 3.1 while we lock down for GA, then backport a fix from master from 3.1.1. We discussed this plan at the manager sync yesterday and @Pilchie was alright with it.

**Comment by wtgodbe** [comment]
https://github.com/aspnet/AspNetCore/issues/16933

**Pull request merged**
