### PR TITLE
Add Server2022 to helix matrix & quarantine jobs

### PR DESCRIPTION
**Pull request by wtgodbe**
Part of https://github.com/dotnet/aspnetcore/issues/36032. Should backport to 6.0

### CODE REVIEW

**Review by dougbu — APPROVED** [review]

**Review by HaoK — APPROVED** [review]

**Comment by Tratcher** [comment]
Looks like Server2022 turned off TLS 1.1? The test will need to be hardened. You can skip it and file an issue.

**Comment by wtgodbe** [comment]
New helix-matrix: https://dev.azure.com/dnceng/public/_build/results?buildId=1435126&view=results

**Comment by sebastienros** [comment]
Noob question, the server and client OS share the same version prefix, so is it possible that windows 10/11 catch up with server? Or are these number incremented verry rarely. Like not on every windows update, but as a product version.

**Comment by Tratcher** [comment]
@sebastienros the OS version updates only for significant releases. For Win10 that's once or twice per year, and often it only changes by +1. Win10 won't catch up to the server. Win11 will pass it.

**Comment by wtgodbe** [comment]
https://dev.azure.com/dnceng/public/_build/results?buildId=1435419&view=results

**Pull request merged**
