### PR TITLE
Added copy parameters to enable parallel build

### PR DESCRIPTION
**Pull request by dashkodo**
PR Title
Added parameters to Copy task that is executed for setting up correct dependency environment in the tests.

PR Description
When enabling multiple msbuild nodes it could fail due to locking "xxx.deps.json" files
We have faced with this issue using latest version of microsoft.aspnetcore.mvc.testing nuget package
C:\ZZZZ\nuget\microsoft.aspnetcore.mvc.testing\7.0.1\build\net7.0\Microsoft.AspNetCore.Mvc.Testing.targets(68, 5): error MSB3027: Unable to copy file "D:\XXXX\bin\Release\YYYY.deps.json" to "bin\Release\YYYY.deps.json". The process cannot access the file 'bin\Release\YYYY.deps.json' because it is being used by another process.

Addresses https://github.com/dotnet/aspnetcore/issues/33757

### CODE REVIEW

**Review by mitchdenny — APPROVED** [review]
LGTM based on reading of linked issue/PR that was closed and @javiercn's feedback there.

**Review by captainsafia — APPROVED** [review]

**Comment by vuvarov-cantaloupe** [comment]
@captainsafia, @mitchdenny Could we do anything to speed up review by dotnet/aspnet-blazor-eng?
This issue stops us from .NET 6.0 -> 7.0 migration.

**Comment by mitchdenny** [comment]
@vuvarov-cantaloupe actually I'm not sure why we are waiting for the Blazor team's input here since this is a change to the MVC code test projects.

**Comment by captainsafia** [comment]
> @vuvarov-cantaloupe actually I'm not sure why we are waiting for the Blazor team's input here since this is a change to the MVC code test projects.

Yep, we can go ahead and merge this. I lapsed and forgot to click the green button when I last reviewed.

Sidenote: the process for backporting this to 6.0 and 7.0 is a little more involved. Amongst other things, we'll want to make sure that it's worth backporting (number of upvotes on the issue, impact and existence of workarounds, etc).

**Comment by vuvarov-cantaloupe** [comment]
Thank you for the quick response!

**Pull request merged**
