### PR TITLE
Ignore Unshipped.txt in previews

### PR DESCRIPTION
**Pull request by BrennanConroy**

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
And, yes, I agree this is `tell-mode`. But, @BrennanConroy is something blocked that's already approved for preview4❔ @Pilchie and @wtgodbe are we in a time crunch here❔

**Comment by Pilchie** [comment]
We'd like to get Preview 4 changes in hopefully by EOD today, and I expect at least these 3 are blocked.

1. https://github.com/dotnet/aspnetcore/pull/31784
2. https://github.com/dotnet/aspnetcore/pull/31816
3. https://github.com/dotnet/aspnetcore/pull/31825

**Comment by BrennanConroy** [comment]
Only one is blocked because the check is only for "modified from main", two of those are completely new files so wont be affected.

**Review by halter73 — APPROVED** [review]

**Comment by halter73** [comment]
Do we plan on doing this for every release we have ASK mode changes?

**Comment by BrennanConroy** [comment]
> Do we plan on doing this for every release we have ASK mode changes?

What do you mean? This is a permanent change to the script, so only needs to be done once.

**Comment by halter73** [comment]
I didn't look carefully enough. I assumed you just removed the `.Unshipped.txt` check altogether and approved because I want my PR merged 😆 

If all the other checks passed, do we have to rerun checks after this is merged in the other PRs? Or can we just force it?

**Review by JunTaoLuo — APPROVED** [review]

**Pull request merged**
