### PR TITLE
Update some tests

### PR DESCRIPTION
**Pull request by Pilchie**

### CODE REVIEW

**Review by dougbu — APPROVED** [review]

**Comment by Pilchie** [comment]
@anurse - looks like a set of server tests timing out, known issue?

**Comment by Pilchie** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=416594

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/3168
https://github.com/aspnet/AspNetCore-Internal/issues/2181
https://github.com/aspnet/AspNetCore-Internal/issues/3290

**Review by javiercn — APPROVED** [review]
Does this need to go into 3.1?

I'm fine either way. Ultimately you make the call :)

**Comment by anurse** [comment]
> looks like a set of server tests timing out, known issue?

I believe this is the possible sockets regression we're looking at. @halter73 or @BrennanConroy can we start investigating this? There's quite a bit of flakiness coming from these.

**Comment by anurse** [comment]
Filed https://github.com/aspnet/AspNetCore/issues/16873 for this investigation.

**Comment by halter73** [comment]
What's interesting about these test failures is that 2 of the 5 test failures (which all happened during the same run on the same agent) were all in-memory tests, and all 5 failed tests failed due to 30 second timeouts but the test runner took at least 55 seconds to report a failure each time.

I doubt the test failures are actually socket related. This reeks ThreadPool starvation.

**Comment by davidfowl** [comment]
Can we capture a dump?

**Comment by Pilchie** [comment]
@HaoK @javiercn does the work you did to capture dumps help here?

**Comment by javiercn** [comment]
@Pilchie No, in the AzDo builds its only setup for hangs. There is a current issue (already reported) with ProcDump that prevents capturing dumps effectively on managed exceptions (it doesn't prevent it, but it prevents filtering based on them).

Once that is fixed we will be able to enable it for test failures too. (Essentially capturing first-chance exceptions with a filter to just capture xUnit exceptions).

**Comment by wtgodbe** [comment]
@Pilchie is this for GA?

**Comment by Pilchie** [comment]
Yes, tell-mode for GA.

**Review by mkArtakMSFT — APPROVED** [review]

**Pull request merged**
