### PR TITLE
Reenable individual auth tests

### LINKED ISSUE #26776: [master] Get IndividualAuth template tests working on Helix
Tests may be failing on Helix because they do not have the TemplateTests.props overrides in their environment. Binary logs clearly show the published projects are building using the SDKs default, 5.0.0 version of Microsoft.AspNetCore.App and not the just-built version e.g. &hellip;\e\sdk294\x64\packs\Microsoft.AspNetCore.App.Ref\\**5.0.0-rc.2.20466.8**\ref\net5.0\Microsoft.AspNetCore.Http.Abstractions.dll. Not sure why the problem is specific to IndividualAuth tests.

Error:
``` text
...\e\Templates\BaseFolder\AspNet.jvkjhfr1m0h\Startup.cs(45,17): error CS1705: Assembly 'Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore' with identity 'Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore, Version=42.42.42.42, Culture=neutral, PublicKeyToken=adb9793829ddae60' uses 'Microsoft.AspNetCore.Http.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.AspNetCore.Http.Abstractions' with identity 'Microsoft.AspNetCore.Http.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' [...\e\Templates\BaseFolder\AspNet.jvkjhfr1m0h\AspNet.jvkjhfr1m0h.csproj]
```

Specific tests skipped in #24983:
- `Templates.Test.IdentityUIPackageTest.IdentityUIPackage_WorksWithDifferentOptions()`
- `Templates.Test.MvcTemplateTest.MvcTemplate_IndividualAuth(useLocalDB: False)`
- `Templates.Test.MvcTemplateTest.MvcTemplate_IndividualAuth(useLocalDB: True)`
- `Templates.Test.RazorPagesTemplateTest.RazorPagesTemplate_IndividualAuth(useLocalDB: False)`
- `Templates.Test.RazorPagesTemplateTest.RazorPagesTemplate_IndividualAuth(useLocalDB: True)`

Details are available in https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-pull-24983-merge-b23d059ca16f4f5fb9/ProjectTemplates.Tests--net5.0/AspNet.di2py1qzril.binlog for example. See build https://dev.azure.com/dnceng/public/_build/results?buildId=836250 for other examples.

When restoring these tests after fixing them, note all previously had `[SkipOnHelix("cert failure", Queues = "All.OSX")]` applied.

### PR DESCRIPTION
**Pull request by HaoK**
Fixes https://github.com/dotnet/aspnetcore/issues/26776

### CODE REVIEW

**Comment by HaoK** [comment]
@dotnet/aspnet-blazor-eng @dougbu how do we feel about maybe moving project template tests back to azdo for now (off helix),  that would let us unquarantine a lot of tests that are broken due to issues around installing our custom bits correctly on the helix machines.  Once the work involving moving to a model of testing against a coherent SDK, we can switch back to helix.  It doesn't seem worth trying to hack something short term if we are moving away from our current model of testing.  Thoughts?

**Comment by dougbu** [comment]
I don't think this is the right short-term solution because
1. it's essentially an admission of failure
2. it takes pressure off getting a real fix
3. we need to get more happening on Helix, not less, in order to take advantage of @davidfowl's progress making blame, dumps, et cetera widely available

Besides all that, we are basically in MQ and should spend some of that period to really fix whatever Helix infrastructure problems we've got.

**Comment by pranavkm** [comment]
@HaoK could you elaborate what it is that's problematic here and how that would be resolved in the future:

>  broken due to issues around installing our custom bits correctly on the helix machines

**Comment by HaoK** [comment]
Sure, so the main issue with testing templates is that we have to basically install the correct bits onto the helix machines.  This is fits perfectly into wider long term future goal where we test against a coherent product build as opposed to whatever it is that we generally cobble together (which is especially true for our template tests).

To summarize where we are at:
The template tests were originally written with the expectation that they would run against the built outputs, like most of our tests, so they've have had a lot of years of iteration and hardening running things the 'old' way on azdo..  I did some work in the last few years to add enough tweaks for the tests to run on helix in a few limited scenarios (non arm, no selenium, always using windows build shared runtime bits, etc).  But basically we need to continue to maintain and improve a fragile infrastructure to basically install enough of a subset of our bits on the helix machine that our template tests need.  

If the end goal is to start just pointing our tests against a version of the SDK, that removes the need to have any kind of install our private bits step on the helix machines.  The flow would just be, send the correct SDK version as part of our helix jobs that contains the coherent SDK with templates, and then run the tests.  Since things already work well enough on azdo, I'm suggesting we consider abandoning install template bits on the helix machines.  We don't lose much of the dump/hang work since most of that is part of dotnet [vs]test anyways.  

Also we will have to do work to update the template tests to work against official sdk bits anyways, irrespective of whatever short term fixes we do here.

**Comment by dougbu** [comment]
@HaoK I agree it would be nice if we were building against entire SDKs but we're not there yet and we don't know when in the 6.0 timeframe that will come. We need to be testing thoroughly long before that.

@pranavkm I also would like to call attention to dotnet/aspnetcore#26776 and my [comment here](https://github.com/dotnet/aspnetcore/issues/26776#issuecomment-706607919):
> the real problem is **all** of the template tests run against the Microsoft.AspNetCore.App assemblies included in the SDK rather than what we just built.

We have support for things like the AzDO / local template tests' TemplateTests.props for many other tests that run on Helix but nothing for the template tests ☹️

**Comment by HaoK** [comment]
>We need to be testing thoroughly long before that.

Right this actually helps my case.  So right now we have degraded testing as more tests are quarantined or skipped on helix due to it just being less functional then letting them continue to run on azdo.  So if our goal its just to have better coverage today, we should just run template tests on azdo.  It just seems like a poor investment to enhance/build new test install logic that we know is most likely going to be obsolete and nuked in 6.0.

**Comment by dougbu** [comment]
My point was we don't know when testing against full ADKs will even start. And, the issue is _not_ about moving back to AzDO. If that was enough, we'd be satisfied with the template job in PR builds.

**Review by dougbu — APPROVED** [review]

**Pull request merged**
