### PR TITLE
Update SDK

### PR DESCRIPTION
**Pull request by BrennanConroy**

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Comment by BrennanConroy** [comment]
Windows:
>##[error].dotnet\sdk\6.0.100-rc.1.21370.1\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(668,7): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Found conflicting definitions for the same asset 'Identity: D:\workspace\_work\1\s\artifacts\obj\CustomBasePathApp\Release\net6.0\build-gz\9pg2wFfO.gz, SourceType: Project, SourceId: CustomBasePathApp, ContentRoot: D:\workspace\_work\1\s\artifacts\bin\CustomBasePathApp\Release\net6.0\wwwroot\, BasePath: app, RelativePath: _framework/Microsoft.JSInterop.WebAssembly.xml.gz, AssetKind: Build, AssetMode: All, AssetRole: Alternative, RelatedAsset: D:\workspace\_work\1\s\artifacts\bin\CustomBasePathApp\Release\net6.0\wwwroot\_framework\Microsoft.JSInterop.WebAssembly.xml, AssetTraitName: Content-Encoding, AssetTraitValue: gzip, CopyToOutputDirectory: PreserveNewest, CopyToPublishDirectory: Never, OriginalItemSpec: D:\workspace\_work\1\s\artifacts\bin\CustomBasePathApp\Release\net6.0\wwwroot\_framework\Microsoft.JSInterop.WebAssembly.xml' and 'Identity: D:\workspace\_work\1\s\artifacts\obj\CustomBasePathApp\Release\net6.0\build-gz\9pg2wFfO.gz, SourceType: Project, SourceId: CustomBasePathApp, ContentRoot: D:\workspace\_work\1\s\artifacts\bin\CustomBasePathApp\Release\net6.0\wwwroot\, BasePath: app, RelativePath: _framework/Microsoft.JSInterop.WebAssembly.dll.gz, AssetKind: Build, AssetMode: All, AssetRole: Alternative, RelatedAsset: D:\workspace\_work\1\s\artifacts\bin\CustomBasePathApp\Release\net6.0\wwwroot\_framework\Microsoft.JSInterop.WebAssembly.dll, AssetTraitName: Content-Encoding, AssetTraitValue: gzip, CopyToOutputDirectory: PreserveNewest, CopyToPublishDirectory: Never, OriginalItemSpec: D:\workspace\_work\1\s\artifacts\bin\CustomBasePathApp\Release\net6.0\wwwroot\_framework\Microsoft.JSInterop.WebAssembly.dll'

Ubuntu:
```
/datadisks/disk1/workspace/_work/1/s/.dotnet/sdk/6.0.100-rc.1.21370.1/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(661,7): error : System.ArgumentException: The path is empty. (Parameter 'path') [/datadisks/disk1/workspace/_work/1/s/src/Components/WebAssembly/testassets/Wasm.Authentication.Client/Wasm.Authentication.Client.csproj]
/datadisks/disk1/workspace/_work/1/s/.dotnet/sdk/6.0.100-rc.1.21370.1/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(661,7): error :    at System.IO.Path.GetFullPath(String path) in System.Private.CoreLib.dll:token 0x6005e1e+0x3e [/datadisks/disk1/workspace/_work/1/s/src/Components/WebAssembly/testassets/Wasm.Authentication.Client/Wasm.Authentication.Client.csproj]
/datadisks/disk1/workspace/_work/1/s/.dotnet/sdk/6.0.100-rc.1.21370.1/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(661,7): error :    at Microsoft.AspNetCore.Razor.Tasks.MergeManifestProperties.FindMatchingProject(ITaskItem manifest) in Microsoft.NET.Sdk.Razor.Tasks.dll:token 0x60001a4+0xd [/datadisks/disk1/workspace/_work/1/s/src/Components/WebAssembly/testassets/Wasm.Authentication.Client/Wasm.Authentication.Client.csproj]
/datadisks/disk1/workspace/_work/1/s/.dotnet/sdk/6.0.100-rc.1.21370.1/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(661,7): error :    at Microsoft.AspNetCore.Razor.Tasks.MergeManifestProperties.Execute() in Microsoft.NET.Sdk.Razor.Tasks.dll:token 0x60001a3+0x15 [/datadisks/disk1/workspace/_work/1/s/src/Components/WebAssembly/testassets/Wasm.Authentication.Client/Wasm.Authentication.Client.csproj]
```

**Comment by BrennanConroy** [comment]
@javiercn Since you recently touched the Razor SDK

**Comment by BrennanConroy** [comment]
https://github.com/dotnet/aspnetcore/pull/34510 might be related and fix the issue?

**Comment by javiercn** [comment]
@BrennanConroy yes.

**Comment by dougbu** [comment]
@javiercn we don't automatically merge from preview or servicing branches forward. Is there a reason you didn't start in 'main' and cherry-pick to the preview7 branch❔ (That would be the normal practice.)

**Comment by javiercn** [comment]
@dougbu that this was going through ask-mode, and I forgot we changed the approach.

**Comment by dougbu** [comment]
Blocked on #34619. Should `/azp run` and remove `blocked` label once that goes in.

**Comment by dougbu** [comment]
> Blocked on #34619. Should `/azp run` and remove `blocked` label once that goes in.

Ooops, that PR also targets 'release/6.0-preview7'. @javiercn please either cherry-pick the right fixes into this PR or create a new PR targeting main and doing the static web assets magic.

**Comment by wtgodbe** [comment]
@javiercn will we be able to get the changes from https://github.com/dotnet/aspnetcore/pull/34619 into main soon to unblock this?

**Comment by JunTaoLuo** [comment]
From my understanding, we needed https://github.com/dotnet/aspnetcore/pull/34510 in main. So I've cherry-picked the change to main: https://github.com/dotnet/aspnetcore/pull/34818.

Let me know if I'm mistaken here @mkArtakMSFT @javiercn.

**Comment by JunTaoLuo** [comment]
If that cherry-pick doesn't work, I'll apply the workaround linked in https://github.com/dotnet/aspnetcore/commit/288e162d9b42e80f51277bdc16223e4f538bba01.

**Comment by JunTaoLuo** [comment]
Closing in favour of https://github.com/dotnet/aspnetcore/pull/34819/files

**Pull request closed without merging**
