### PR TITLE
[release/2.1] Include SharedFx bundle in Hosting Bundle, instead of SharedFx .msi

### PR DESCRIPTION
**Pull request by wtgodbe**
Backport of https://github.com/dotnet/aspnetcore/pull/36858

### CODE REVIEW

**Comment by dougbu** [comment]
Please ping when you get this working 😉

**Comment by wtgodbe** [comment]
> Please ping when you get this working 😉

The failures are unrelated, they were on NPM and Kestrel tests on Linux/Mac - this only touches the Windows installers

**Review by joeloff — APPROVED** [review]

**Comment by wtgodbe** [comment]
Test internal build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1384206&view=results

**Comment by wtgodbe** [comment]
New build https://dev.azure.com/dnceng/internal/_build/results?buildId=1384705&view=results

**Comment by wtgodbe** [comment]
Test build worked

**Pull request merged**
