### PR TITLE
Dynamic include DataProtectionKey.Id

### LINKED ISSUE #43187: Error: "The entity type 'DataProtectionKey' requires a primary key" when using .Net 7 previews
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have implemented `DataProtectionKey` storage using an EFCore DB context, and it has been working fine for nearly a year. 

In June, I upgraded my application to .Net 7 preview 5 and EFCore 7 preview 5, and now see the following exception:

```Migrations failed with exception: System.InvalidOperationException: The entity type 'DataProtectionKey' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.```

The webserver then terminates within `IHost.Run` with the following (similar) exception:

```
[22:03:19.707-0001-INF] Damselfly Webserver terminated with exception: The entity type 'DataProtectionKey' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.
```

I am using the SQLite DB provider.

This only happens on Linux (deployed in an Ubuntu docker container). If I run the same code, against the same .db file, on OSX, the migrations complete without issue. I have not tried Windows.

The error suggests using the `[Keyless]` attribute to resolve this error, but I don't know enough about `DataProtectionKey`s to know if it would cause any issues. 

Note that the problem persists with .Net 7 preview 6 and EFCore preview 6.

### Expected Behavior

The expected behaviour is that the `db.Database.Migrate();` call completes without issue and the application starts normally.
 

### Steps To Reproduce

I declare my `DataProtectionKeys` in my `DbContext` here: https://github.com/Webreaper/Damselfly/blob/develop/Damselfly.Core/Models/ImageContext.cs#L43

```        public DbSet<DataProtectionKey> DataProtectionKeys { get; set; }```

I add configure the DataProtection here: https://github.com/Webreaper/Damselfly/blob/master/Damselfly.Web/Startup.cs#L73

```            services.AddDataProtection().PersistKeysToDbContext<ImageContext>();```

I can't find anywhere in the documentation that suggests I need to do something explicit to create a key.

The DataProtectionKeys were added in 2021, in this Migration: https://github.com/Webreaper/Damselfly/blob/master/Damselfly.Migrations.Sqlite/Migrations/20210922112630_AddDataProtectionKeys.cs:

```
   modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xml")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });
```

### Exceptions (if any)

```
Migrations failed with exception: System.InvalidOperationException: The entity type 'DataProtectionKey' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNonNullPrimaryKeys(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Sqlite.Infrastructure.Internal.SqliteModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite, RuntimeResolverContext, ServiceProviderEngineScope, RuntimeResolverLock)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite, RuntimeResolverContext, ServiceProviderEngineScope, RuntimeResolverLock)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite, RuntimeResolverContext, ServiceProviderEngineScope, RuntimeResolverLock)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite, RuntimeResolverContext, ServiceProviderEngineScope, RuntimeResolverLock)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite, RuntimeResolverContext, ServiceProviderEngineScope, RuntimeResolverLock)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite, RuntimeResolverContext, ServiceProviderEngineScope, RuntimeResolverLock)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type, ServiceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider, Type)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider)
```

### .NET Version

.Net 7 preview 5 and preview 6

### Anything else?

The issue only happens when running the containerised deployment on Linux. Running exactly the same code on OSX works fine.

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/aspnetcore/issues/43187

### CODE REVIEW

**Comment by sebastienros** [comment]
If we change one of the functional tests to run in trimming, would we repro the bug and confirm the fix?

**Comment by sebastienros** [comment]
I assume we have other EF providers like this one. We should then do the same preemptively.

**Comment by JamesNK** [comment]
> If we change one of the functional tests to run in trimming, would we repro the bug and confirm the fix?

It's not that simple. You need to deploy an app with trimming. And the app would have to test it in isolation to be accurate. i.e. if the app news up a DataProtectionKey and sets ID itself then the test wouldn't be valid because it would no longer be trimmed because of the test.

Right now we don't have proper test coverage of a lot of trimming.

**Comment by JamesNK** [comment]
> I assume we have other EF providers like this one. We should then do the same preemptively.

Good idea. I'll check.

**Comment by JamesNK** [comment]
DataProtection and Identity are the only libraries that use EF. Identity explicitly configures its keys so should be fine as is: https://github.com/dotnet/aspnetcore/blob/9af007591a271f176cc74f374d2c239908f1ac7d/src/Identity/EntityFrameworkCore/src/IdentityUserContext.cs#L116

**Review by sebastienros — APPROVED** [review]

**Review by HaoK — APPROVED** [review]

**Comment by MichalStrehovsky** [comment]
I think there might be a bit of a misunderstanding on how trimming works based on the conversation in the issue. I'm not sure if this annotation fixes the problem.

Does this small snipped behave the way you expect it would?

```csharp
using System.Diagnostics.CodeAnalysis;

// Trimmed
Reporter.Report(typeof(ClassWithUnusedProperties));

// ***Still trimmed***, do not rely on this! It sometimes looks
// like it works because hey I use this property in code, but it
// can break the assumption any time. What you use in code is the getter method,
// not the property. This always breaks with NativeAot. It sometimes
// breaks with IL Linker (it does break here). It will likely break the assumption a
// lot more with IL Linker in the future.
ClassWithPropertiesUsedFromCode.SomeProperty.ToString();
Reporter.Report(typeof(ClassWithPropertiesUsedFromCode));

// Trimmed - we need to see a GetType call on this.
// The purpose of the attribute is making it so that callsites to GetType
// can be analyzed. If there's no GetType call, this keeps nothing.
new ClassWithDynamicallyAccessedButNotActuallyUsed();
Reporter.Report(typeof(ClassWithDynamicallyAccessedButNotActuallyUsed));

// Not trimmed 
var o = new ClassWithDynamicallyAccessed();
GrabProperties(o); // Actually use the [DAM] annotation for something
static void GrabProperties(ClassWithDynamicallyAccessed c) => c.GetType().GetProperties();
Reporter.Report(typeof(ClassWithDynamicallyAccessed));

// Not trimmed
typeof(ClassVisiblyReflectedOn).GetProperties();
Reporter.Report(typeof(ClassVisiblyReflectedOn));

static class Reporter
{
    [UnconditionalSuppressMessage("", "IL2070", Justification = "That's the point")]
    public static void Report(Type t)
    {
        Console.WriteLine($"{t}:\t{(t.GetProperties().Length == 0 ? "Trimmed" : "Not trimmed")}");
    }
}

class ClassWithUnusedProperties
{
    public static int SomeProperty => default;
}

class ClassWithPropertiesUsedFromCode
{
    public static int SomeProperty => default;
}

[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicProperties)]
class ClassWithDynamicallyAccessedButNotActuallyUsed
{
    public int SomeProperty => default;
}

[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicProperties)]
class ClassWithDynamicallyAccessed
{
    public int SomeProperty => default;
}

class ClassVisiblyReflectedOn
{
    public int SomeProperty => default;
}
```

**Comment by JamesNK** [comment]
@MichalStrehovsky Thanks for looking at this. I thought it would work based on the issue description here: https://github.com/dotnet/runtime/issues/49465

> The DynamicallyAccessedMembersAttribute [attribute ](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.dynamicallyaccessedmembersattribute)currently cannot be applied to a class or interface. Adding this support will allow developers to annotate a type to help the trimmer preserve its members that are being used. If the trimmer needs to keep the type, it will keep the required members on its derived types as well.

But I guess that is only true when the class's type is used in code the analyzer can see.

Follow up PR - https://github.com/dotnet/aspnetcore/pull/43207

**Pull request merged**
