### PR TITLE
HubConnection failures: Provide Better Opportunity Http Status Code Handling 

### PR DESCRIPTION
**Pull request by rpriest1260**
HubConnection failures: Provide Better Opportunity Http Status Code Handling 

    Adding an HttpException.  This will be returned as the
    InnerException of a HttpRequestException(that is returned on a
    HubConnection failure). This exception contains a
    StatusCode property which consumers may use to check which type of HTTP error
    is being returned. This will provide the ability to respond differently
    based on the value of the error. For example, if a 401 unauthorized is
    returned, one may deem it appropriate to retrieve a new token before the
    code proceeds. Prior to this, the HttpRequestException provided no
    modern means to detect the status code. That is, other
    than parsing the Message (string) property. This is not
    optimal.

### CODE REVIEW

**Comment by davidfowl** [comment]
@rpriest1260 can you file a feature request please?

**Comment by rpriest1260** [comment]
Sure.

**Comment by rpriest1260** [comment]
I have filed the following feature request.

https://github.com/aspnet/AspNetCore/issues/17304

Please let me know if I need to supply more information.


From: Robert Priest
Sent: Thursday, November 21, 2019 12:43 PM
To: aspnet/AspNetCore <reply@reply.github.com>; aspnet/AspNetCore <AspNetCore@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [aspnet/AspNetCore] HubConnection failures: Provide Better Opportunity Http Status Code Handling (#17302)

Sure.

**Comment by anurse** [comment]
Closing as per the comments in https://github.com/aspnet/AspNetCore/issues/17304 . Fixing this in corefx is much preferred here so we can keep using the normal pattern.

**Comment by rpriest1260** [comment]
I can see the argument in fixing this in corefx<https://github.com/dotnet/corefx/issues/26477>. But,  when you say “Fixing this in corefx is much preferred here so we can keep using the normal pattern”, how is adding the proposed HttpException as the *inner exception* to the already existing HttpRequestException, breaking the “normal” pattern?

Whoever is checking for the HttpRequestException - their code will still work, and, there is no need to catch on a different exception. In my opinion, that seems much better than a new HttpResponseException<https://github.com/dotnet/corefx/issues/26477#issue-290185071>, as is being proposed in many of the other threads on this very same issue.

Is it that you simply want to call EnsureSuccessStatusCode() instead of checking IsSuccessfuleStatusCode?

It seems as though  davidsh came to a similar solution  here<https://github.com/dotnet/corefx/issues/26477#issuecomment-392636413>, so I will monitor 26477<https://github.com/dotnet/corefx/issues/26477>.  But it does seem like a lot of people are looking for something like what I proposed – whether in the SignalR lib or in Core.

**Comment by anurse** [comment]
> breaking the “normal” pattern?

The normal pattern here being calling `EnsureStatusCode`. We should fix this so that all consumers of `HttpClient` get the fix.

We don't want SignalR to produce a different kind of exception here (even if it's in the `InnerException`).

**Pull request closed without merging**
