### PR TITLE
See what happens with blazor build in helix

### PR DESCRIPTION
**Pull request by HaoK**

### CODE REVIEW

**Comment by HaoK** [comment]
@pranavkm I reenabled these tests on helix but it looks like they will need some rejiggering to work, as they are looking for the files based on build time locations, can you see if you can make any tactical changes to make these tests work on helix (its valid to copy the test assets into the public directory, and then have the test look for them using a relative path to the runtime directory).

only 13 tests are failing:

```
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:01.14]     Microsoft.AspNetCore.Blazor.Build.ProjectDirectoryTest.ProjectDirectory_IsNotSetToBePreserved [FAIL]
[xUnit.net 00:00:01.17]     Microsoft.AspNetCore.Blazor.Build.RuntimeDependenciesResolverTest.FindsReferenceAssemblyGraph_ForStandaloneApp [SKIP]
[xUnit.net 00:00:01.19]     Microsoft.AspNetCore.Blazor.Build.BuildIncrementalismTest.Build_WithLinker_IsIncremental [FAIL]
  X Microsoft.AspNetCore.Blazor.Build.ProjectDirectoryTest.ProjectDirectory_IsNotSetToBePreserved [12ms]
  Error Message:
   System.InvalidOperationException : Could not find project at 'F:\workspace\_work\1\s\src\Components\Blazor\Build\testassets\standalone'
  Stack Trace:
     at Microsoft.AspNetCore.Blazor.Build.ProjectDirectory.Create(String projectName, String baseDirectory, String[] additionalProjects) in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/ProjectDirectory.cs:line 42
   at Microsoft.AspNetCore.Blazor.Build.ProjectDirectoryTest.ProjectDirectory_IsNotSetToBePreserved() in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/ProjectDirectoryTest.cs:line 14
  ! Microsoft.AspNetCore.Blazor.Build.RuntimeDependenciesResolverTest.FindsReferenceAssemblyGraph_ForStandaloneApp [1ms]
  X Microsoft.AspNetCore.Blazor.Build.BuildIncrementalismTest.Build_WithLinker_IsIncremental [9ms]
  Error Message:
   System.InvalidOperationException : Could not find project at 'F:\workspace\_work\1\s\src\Components\Blazor\Build\testassets\standalone'
  Stack Trace:
     at Microsoft.AspNetCore.Blazor.Build.ProjectDirectory.Create(String projectName, String baseDirectory, String[] additionalProjects) in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/ProjectDirectory.cs:line 42
   at Microsoft.AspNetCore.Blazor.Build.BuildIncrementalismTest.Build_WithLinker_IsIncremental() in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/BuildIncrementalismTest.cs:line 15
--- End of stack trace from previous location ---
[xUnit.net 00:00:05.69]     Microsoft.AspNetCore.Blazor.Build.PublishIntegrationTest.Publish_WithDefaultSettings_Works [FAIL]
[xUnit.net 00:00:05.69]     Microsoft.AspNetCore.Blazor.Build.PublishIntegrationTest.Publish_HostedApp_WithNoBuild_Works [FAIL]
[xUnit.net 00:00:05.70]     Microsoft.AspNetCore.Blazor.Build.PublishIntegrationTest.Publish_WithLinkOnBuildDisabled_Works [FAIL]
[xUnit.net 00:00:05.70]     Microsoft.AspNetCore.Blazor.Build.PublishIntegrationTest.Publish_WithNoBuild_Works [FAIL]
[xUnit.net 00:00:05.71]     Microsoft.AspNetCore.Blazor.Build.PublishIntegrationTest.Publish_SatelliteAssemblies_AreCopiedToBuildOutput [FAIL]
[xUnit.net 00:00:05.71]     Microsoft.AspNetCore.Blazor.Build.PublishIntegrationTest.Publish_HostedApp_Works [FAIL]
  X Microsoft.AspNetCore.Blazor.Build.PublishIntegrationTest.Publish_WithDefaultSettings_Works [3ms]
  Error Message:
   System.InvalidOperationException : Could not find project at 'F:\workspace\_work\1\s\src\Components\Blazor\Build\testassets\standalone'
  Stack Trace:
     at Microsoft.AspNetCore.Blazor.Build.ProjectDirectory.Create(String projectName, String baseDirectory, String[] additionalProjects) in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/ProjectDirectory.cs:line 42
   at Microsoft.AspNetCore.Blazor.Build.PublishIntegrationTest.Publish_WithDefaultSettings_Works() in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/PublishIntegrationTest.cs:line 16
--- End of stack trace from previous location ---
  X Microsoft.AspNetCore.Blazor.Build.PublishIntegrationTest.Publish_HostedApp_WithNoBuild_Works [3ms]
  Error Message:
   System.InvalidOperationException : Could not find project at 'F:\workspace\_work\1\s\src\Components\Blazor\Build\testassets\blazorhosted'
  Stack Trace:
     at Microsoft.AspNetCore.Blazor.Build.ProjectDirectory.Create(String projectName, String baseDirectory, String[] additionalProjects) in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/ProjectDirectory.cs:line 42
   at Microsoft.AspNetCore.Blazor.Build.PublishIntegrationTest.Publish_HostedApp_WithNoBuild_Works() in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/PublishIntegrationTest.cs:line 189
--- End of stack trace from previous location ---
  X Microsoft.AspNetCore.Blazor.Build.PublishIntegrationTest.Publish_WithLinkOnBuildDisabled_Works [3ms]
  Error Message:
   System.InvalidOperationException : Could not find project at 'F:\workspace\_work\1\s\src\Components\Blazor\Build\testassets\standalone'
  Stack Trace:
     at Microsoft.AspNetCore.Blazor.Build.ProjectDirectory.Create(String projectName, String baseDirectory, String[] additionalProjects) in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/ProjectDirectory.cs:line 42
   at Microsoft.AspNetCore.Blazor.Build.PublishIntegrationTest.Publish_WithLinkOnBuildDisabled_Works() in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/PublishIntegrationTest.cs:line 84
--- End of stack trace from previous location ---
  X Microsoft.AspNetCore.Blazor.Build.PublishIntegrationTest.Publish_WithNoBuild_Works [3ms]
  Error Message:
   System.InvalidOperationException : Could not find project at 'F:\workspace\_work\1\s\src\Components\Blazor\Build\testassets\standalone'
  Stack Trace:
     at Microsoft.AspNetCore.Blazor.Build.ProjectDirectory.Create(String projectName, String baseDirectory, String[] additionalProjects) in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/ProjectDirectory.cs:line 42
   at Microsoft.AspNetCore.Blazor.Build.PublishIntegrationTest.Publish_WithNoBuild_Works() in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/PublishIntegrationTest.cs:line 46
--- End of stack trace from previous location ---
  X Microsoft.AspNetCore.Blazor.Build.PublishIntegrationTest.Publish_SatelliteAssemblies_AreCopiedToBuildOutput [3ms]
  Error Message:
   System.InvalidOperationException : Could not find project at 'F:\workspace\_work\1\s\src\Components\Blazor\Build\testassets\standalone'
  Stack Trace:
     at Microsoft.AspNetCore.Blazor.Build.ProjectDirectory.Create(String projectName, String baseDirectory, String[] additionalProjects) in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/ProjectDirectory.cs:line 42
   at Microsoft.AspNetCore.Blazor.Build.PublishIntegrationTest.Publish_SatelliteAssemblies_AreCopiedToBuildOutput() in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/PublishIntegrationTest.cs:line 119
--- End of stack trace from previous location ---
  X Microsoft.AspNetCore.Blazor.Build.PublishIntegrationTest.Publish_HostedApp_Works [3ms]
  Error Message:
   System.InvalidOperationException : Could not find project at 'F:\workspace\_work\1\s\src\Components\Blazor\Build\testassets\blazorhosted'
  Stack Trace:
     at Microsoft.AspNetCore.Blazor.Build.ProjectDirectory.Create(String projectName, String baseDirectory, String[] additionalProjects) in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/ProjectDirectory.cs:line 42
   at Microsoft.AspNetCore.Blazor.Build.PublishIntegrationTest.Publish_HostedApp_Works() in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/PublishIntegrationTest.cs:line 148
--- End of stack trace from previous location ---
[xUnit.net 00:00:06.93]     Microsoft.AspNetCore.Blazor.Build.Test.ComponentRenderingRazorIntegrationTest.Render_HtmlBlock_Integration [SKIP]
  ! Microsoft.AspNetCore.Blazor.Build.Test.ComponentRenderingRazorIntegrationTest.Render_HtmlBlock_Integration [1ms]
[xUnit.net 00:00:07.23]     Microsoft.AspNetCore.Blazor.Build.Test.ComponentRenderingRazorIntegrationTest.Render_Component_HtmlEncoded [SKIP]
  ! Microsoft.AspNetCore.Blazor.Build.Test.ComponentRenderingRazorIntegrationTest.Render_Component_HtmlEncoded [1ms]
[xUnit.net 00:00:07.91]     Microsoft.AspNetCore.Blazor.Build.BuildIntegrationTest.Build_WithLinkOnBuildDisabled_Works [FAIL]
  X Microsoft.AspNetCore.Blazor.Build.BuildIntegrationTest.Build_WithLinkOnBuildDisabled_Works [3ms]
  Error Message:
   System.InvalidOperationException : Could not find project at 'F:\workspace\_work\1\s\src\Components\Blazor\Build\testassets\standalone'
  Stack Trace:
     at Microsoft.AspNetCore.Blazor.Build.ProjectDirectory.Create(String projectName, String baseDirectory, String[] additionalProjects) in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/ProjectDirectory.cs:line 42
   at Microsoft.AspNetCore.Blazor.Build.BuildIntegrationTest.Build_WithLinkOnBuildDisabled_Works() in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/BuildIntegrationTest.cs:line 54
--- End of stack trace from previous location ---
[xUnit.net 00:00:07.92]     Microsoft.AspNetCore.Blazor.Build.BuildIntegrationTest.Build_WithDefaultSettings_Works [FAIL]
[xUnit.net 00:00:07.93]     Microsoft.AspNetCore.Blazor.Build.BuildIntegrationTest.Build_WithBlazorLinkOnBuildFalse_SatelliteAssembliesAreCopiedToBuildOutput [FAIL]
[xUnit.net 00:00:07.94]     Microsoft.AspNetCore.Blazor.Build.BuildIntegrationTest.Build_Hosted_Works [FAIL]
[xUnit.net 00:00:07.94]     Microsoft.AspNetCore.Blazor.Build.BuildIntegrationTest.Build_SatelliteAssembliesAreCopiedToBuildOutput [FAIL]
  X Microsoft.AspNetCore.Blazor.Build.BuildIntegrationTest.Build_WithDefaultSettings_Works [3ms]
  Error Message:
   System.InvalidOperationException : Could not find project at 'F:\workspace\_work\1\s\src\Components\Blazor\Build\testassets\standalone'
  Stack Trace:
     at Microsoft.AspNetCore.Blazor.Build.ProjectDirectory.Create(String projectName, String baseDirectory, String[] additionalProjects) in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/ProjectDirectory.cs:line 42
   at Microsoft.AspNetCore.Blazor.Build.BuildIntegrationTest.Build_WithDefaultSettings_Works() in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/BuildIntegrationTest.cs:line 16
--- End of stack trace from previous location ---
  X Microsoft.AspNetCore.Blazor.Build.BuildIntegrationTest.Build_WithBlazorLinkOnBuildFalse_SatelliteAssembliesAreCopiedToBuildOutput [15ms]
  Error Message:
   System.InvalidOperationException : Could not find project at 'F:\workspace\_work\1\s\src\Components\Blazor\Build\testassets\standalone'
  Stack Trace:
     at Microsoft.AspNetCore.Blazor.Build.ProjectDirectory.Create(String projectName, String baseDirectory, String[] additionalProjects) in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/ProjectDirectory.cs:line 42
   at Microsoft.AspNetCore.Blazor.Build.BuildIntegrationTest.Build_WithBlazorLinkOnBuildFalse_SatelliteAssembliesAreCopiedToBuildOutput() in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/BuildIntegrationTest.cs:line 108
--- End of stack trace from previous location ---
  X Microsoft.AspNetCore.Blazor.Build.BuildIntegrationTest.Build_Hosted_Works [3ms]
  Error Message:
   System.InvalidOperationException : Could not find project at 'F:\workspace\_work\1\s\src\Components\Blazor\Build\testassets\blazorhosted'
  Stack Trace:
     at Microsoft.AspNetCore.Blazor.Build.ProjectDirectory.Create(String projectName, String baseDirectory, String[] additionalProjects) in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/ProjectDirectory.cs:line 42
   at Microsoft.AspNetCore.Blazor.Build.BuildIntegrationTest.Build_Hosted_Works() in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/BuildIntegrationTest.cs:line 35
--- End of stack trace from previous location ---
  X Microsoft.AspNetCore.Blazor.Build.BuildIntegrationTest.Build_SatelliteAssembliesAreCopiedToBuildOutput [2ms]
  Error Message:
   System.InvalidOperationException : Could not find project at 'F:\workspace\_work\1\s\src\Components\Blazor\Build\testassets\standalone'
  Stack Trace:
     at Microsoft.AspNetCore.Blazor.Build.ProjectDirectory.Create(String projectName, String baseDirectory, String[] additionalProjects) in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/ProjectDirectory.cs:line 42
   at Microsoft.AspNetCore.Blazor.Build.BuildIntegrationTest.Build_SatelliteAssembliesAreCopiedToBuildOutput() in /_/src/Components/Blazor/Build/test/BuildIntegrationTests/BuildIntegrationTest.cs:line 78
--- End of stack trace from previous location ---
Results File: C:\h\w\9EC808C7\w\BB7F09FA\e\TestResults\TestResults.xml

Test Run Failed.
Total tests: 114
     Passed: 98
     Failed: 13
    Skipped: 3
 Total time: 10.3155 Seconds

```

**Comment by HaoK** [comment]
@pranavkm I fixed some the path issues, now it looks like there are some harder ones where the test projects are referencing ReferenceBlazorBuildFromSource.props which has paths hardcoded, so its looking a non existent versions.  Any ideas how to hijack this logic to make it look for a hardcoded path since we can include the necessary files in the helix payload so relative paths would work always.

```
Microsoft.AspNetCore.Blazor.Build.Assert+BuildFailedException : Build failed.

C:\h\w\AB9C096C\p\sdk\x64\dotnet.exe msbuild /nr:false /bl /t:Publish /p:Configuration=Release

Process execution diagnostics:

Process output:

Microsoft (R) Build Engine version 16.6.0-preview-20105-01+5d872c945 for .NET Core

Copyright (C) Microsoft Corporation. All rights reserved.

C:\h\w\AB9C096C\p\sdk\x64\sdk\5.0.100-preview.2.20120.3\MSBuild.dll -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\h\w\AB9C096C\p\sdk\x64\sdk\5.0.100-preview.2.20120.3\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\h\w\AB9C096C\p\sdk\x64\sdk\5.0.100-preview.2.20120.3\dotnet.dll -maxcpucount -verbosity:m /bl /nr:false /p:Configuration=Release /t:Publish .\standalone.csproj

C:\Users\runner\AppData\Local\Temp\BlazorBuild\uahkjw3o.ftu\standalone\Directory.Build.props(17,5): error MSB4019: The imported project "F:\workspace_work\1\s\eng\Versions.props" was not found. Confirm that the expression in the Import declaration "F:\workspace_work\1\s\eng\Versions.props" is correct, and that the file exists on disk. [C:\Users\runner\AppData\Local\Temp\BlazorBuild\uahkjw3o.ftu\standalone\standalone.csproj]
```

**Comment by pranavkm** [comment]
We could make this line conditional:

https://github.com/dotnet/aspnetcore/blob/master/src/Components/Blazor/Build/testassets/Directory.Build.props#L17

```xml
-    <Import Project="$(RepoRoot)eng\Versions.props" />
+   <Import Project="$(RepoRoot)eng\Versions.props" Condition="Exists($(RepoRoot)eng\Versions.props))" />
+   <Import Project="$(SomeMagicDirThatExistsInHelix)Versions.props" Condition="Exists($(SomeMagicDirThatExistsInHelix)Versions.props))" />
```

And copy the `Versions.props` to the packaging output. Is that reasonable?

**Comment by HaoK** [comment]
@pranavkm tried your suggestion and it looks like it might cause issues with restore?  

```
src\Components\Blazor\Build\testassets\standalone\standalone.csproj(0,0): error NU1103: Unable to find a stable package Microsoft.AspNetCore.Blazor.Mono with version 
  - Found 26 version(s) in dotnet5 [ Nearest version: 3.1.0-preview4.19575.3 ]
  - Found 13 version(s) in nuget.org [ Nearest version: 0.8.0-preview-20190204.1 ]
  - Found 4 version(s) in dotnet-core [ Nearest version: 0.10.0-preview6.19273.7 ]
  - Found 0 version(s) in aspnetcore-dev
  - Found 0 version(s) in aspnetcore-tools
  - Found 0 version(s) in roslyn-tools
  - Found 0 version(s) in roslyn
  - Found 0 version(s) in dotnet-eng
  - Found 0 version(s) in dotnet5-transport
```

**Comment by docmaster2** [comment]
qtkeychain dependency frankosterfeld/qtkeychain#99
< frankosterfeld>чем можно заменить?

**Comment by captainsafia** [comment]
Rebasing to bring in the latest changes now that the blazor-wasm branch is merged. Let's see what chaos ensues....

**Comment by captainsafia** [comment]
Closing this PR.

Our build tests have change a bit now that we have a Blazor WASM SDK. Will open a new PR with changes.

**Pull request closed without merging**
