### PR TITLE
Range not satisfiable - bugfix for bad content length

### PR DESCRIPTION
**Pull request by ghost**
Setting content length to 0 when returning an empty body and a 416 RangeNotSatisfiable in FileResultExecutorBase to prevent Kestrel from issuing 500 because of a mismatch between the body length and the Content-Length header.

https://github.com/aspnet/AspNetCore/issues/4943

### CODE REVIEW

**Comment by Tratcher** [comment]
Don't worry about the CI too much, we're reorganizing a lot of things right now and it has caused many breaks. If you rebase it should be better (though not completely fixed yet).

**Review by Tratcher — APPROVED** [review]

**Comment by MatthiasLaroche** [comment]
I rebased the branch on the latest master.
Now it's only the Windows CI build that is partially broken. The linux and mac os builds pass with all tests green.

**Comment by Tratcher** [comment]
The CI failures are known issues that we're dealing with elsewhere. No need to block this PR.

@javiercn for final signoff.

**Review by javiercn — APPROVED** [review]

**Comment by mkArtakMSFT** [comment]
@javiercn, please confirm the failing tests have tracking issues and are not related to this change, and merge this.

**Comment by mkArtakMSFT** [comment]
@MatthiasLaroche, please update your PR to resolve the conflicts so we can move forward with this?

**Comment by MatthiasLaroche** [comment]
I rebased on top of the latest master.

**Pull request merged**
