### PR TITLE
Updating the SDK, hopefully fixing template tests

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
Rolling back SDK version to `7.0.100-rc.1.22375.2` as suggested at https://github.com/dotnet/aspnetcore/pull/44069#pullrequestreview-1112960681. This is to work around the build issues we've had since updating to a newer SDK.

**Update** No, that SDK version doesn't work, as it leads to [this deterministic error](https://github.com/dotnet/aspnetcore/pull/44087#issuecomment-1255082455). I'm now trying to update to the latest 7.0 SDK. The current status is that the template tests are passing locally with that SDK, so let's see if they also pass in CI.

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Comment by Tratcher** [comment]
`System.InvalidOperationException : Failed to uninstall previous templates. The template 'web' could still be found.`

At least that's a different error message 😢.

**Comment by dougbu** [comment]
> At least that's a different error message 😢.

Appears the template tests now expect something specific to a newer SDK and their failing consistently. Hoping that consistency allows you to find the problem more easily than the low frequency flakiness we had before.

**Comment by Tratcher** [comment]
#44032 was just a local refactor, it shouldn't have any dependency on SDK changes.

**Comment by SteveSandersonMS** [comment]
> https://github.com/dotnet/aspnetcore/pull/44032 was just a local refactor, it shouldn't have any dependency on SDK changes.

OK, thanks. I've reverted that reversion now. It was just a cheap way of checking of that particular change was involved, since it seemed superficially related and within the right time range.

**Comment by SteveSandersonMS** [comment]
I fixed the error with `Failed to uninstall previous templates` (just had to update the string we're looking for) but now it's failing with a different error:

```
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error : Unhandled exception. System.NotImplementedException: The method or operation is not implemented. [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.LoggingMetadataFileReferenceResolver.GetHashCode() [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Roslyn.Utilities.Hash.Combine[T](T newKeyPart, Int32 currentKey) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.CompilationOptions.GetHashCodeHelper() [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions.ComputeHashCode() [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.CompilationOptions.GetHashCode() [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at System.Collections.Generic.HashSet`1.Add(T item) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.InputNode`1.UpdateStateTable(Builder graphState, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.TransformNode`2.UpdateStateTable(Builder builder, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.CombineNode`2.UpdateStateTable(Builder graphState, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.TransformNode`2.UpdateStateTable(Builder builder, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.CombineNode`2.UpdateStateTable(Builder graphState, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.TransformNode`2.UpdateStateTable(Builder builder, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.TransformNode`2.UpdateStateTable(Builder builder, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.CombineNode`2.UpdateStateTable(Builder graphState, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.TransformNode`2.UpdateStateTable(Builder builder, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.TransformNode`2.UpdateStateTable(Builder builder, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.TransformNode`2.UpdateStateTable(Builder builder, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.TransformNode`2.UpdateStateTable(Builder builder, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.SourceOutputNode`1.UpdateStateTable(Builder graphState, NodeStateTable`1 previousTable, CancellationToken cancellationToken) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.SourceOutputNode`1.AppendOutputs(IncrementalExecutionContext context, CancellationToken cancellationToken) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.GeneratorDriver.UpdateOutputs(ImmutableArray`1 outputNodes, IncrementalGeneratorOutputKind outputKind, Builder generatorRunStateBuilder, CancellationToken cancellationToken, Builder driverStateBuilder) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.GeneratorDriver.RunGeneratorsCore(Compilation compilation, DiagnosticBag diagnosticsBag, CancellationToken cancellationToken) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.GeneratorDriver.RunGeneratorsAndUpdateCompilation(Compilation compilation, Compilation& outputCompilation, ImmutableArray`1& diagnostics, CancellationToken cancellationToken) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.RunGenerators(Compilation input, ParseOptions parseOptions, ImmutableArray`1 generators, AnalyzerConfigOptionsProvider analyzerConfigOptionsProvider, ImmutableArray`1 additionalTexts, DiagnosticBag generatorDiagnostics) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 generators, ImmutableArray`1 additionalTextFiles, AnalyzerConfigSet analyzerConfigSet, ImmutableArray`1 sourceFileAnalyzerConfigOptions, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, AnalyzerDriver& analyzerDriver, Nullable`1& generatorTimingInfo) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.CommandLine.ConsoleUtil.RunWithUtf8Output[T](Func`2 func) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter, String pipeName) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc, CompileOnServerFunc compileOnServerFunc) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.MainCore(String[] args) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
c:\aspnetcore\.dotnet\sdk\7.0.100-rc.1.22375.2\Roslyn\Microsoft.CSharp.Core.targets(79,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args) [c:\aspnetcore\src\ProjectTemplates\test\Templates.Mvc.Tests\bin\Debug\net7.0\TestTemplates\AspNet.yow1rjdux4sc\AspNet.yow1rjdux4sc.csproj]
```

This error happens in CI and reproduces locally. Since nothing in that stack trace comes from code in this repo, my initial guess is that it's a bug in this particular SDK version so I'm now trying with SDK `7.0.100-rtm.22471.17`.

**Pull request merged**
