### PR TITLE
Update template icons

### PR DESCRIPTION
**Pull request by JunTaoLuo**
Updated with latest icons. @SteveSandersonMS do you know where the templates for Blazor are? 

cc @muratg @Eilon for Ask Mode

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
I think this is low risk enough for preview 3 but it's not a critical fix and could potentially wait for preview 4

**Comment by JunTaoLuo** [comment]
@SteveSandersonMS I found the Blazor templates.

**Comment by JunTaoLuo** [comment]
Apparently there are potential CLA requirements that are not met fort the gRPC icons. Consider this PR blocked.

**Review by muratg — COMMENTED** [review]
I think we should wait for preview4. Build folks are trying to get a build out ASAP.

**Comment by shirhatti** [comment]
@JunTaoLuo See https://github.com/cncf/artwork/blob/master/LICENSE.md

Based on my reading, we can't use the gRPC logo. I'll reach to CELA

**Comment by Eilon** [comment]
@shirhatti - indeed, please follow up with CELA.

**Comment by JunTaoLuo** [comment]
Updated to latest gRPC icon. This is ready to be merged.

**Comment by Tratcher** [comment]
@aspnet/brt 
```
Microsoft.AspNetCore.Mvc.FunctionalTests.TempDataInCookiesUsingCookieConsentTest.CookieTempDataProviderCookie_SetInResponse_OnGrantingConsent
System.InvalidOperationException : 'Serializing TempDataDictionary' requires a reference to 'Microsoft.AspNetCore.Mvc.NewtonsoftJson'. Configure your application by adding a reference to the 'Microsoft.AspNetCore.Mvc.NewtonsoftJson' package and calling 'IMvcBuilder.AddNewtonsoftJson' inside the call to 'ConfigureServices(...)' in the application startup code.
```

**Review by Tratcher — APPROVED** [review]

**Comment by anurse** [comment]
Filed https://github.com/aspnet/AspNetCore/issues/8285

**Review by ryanbrandenburg — APPROVED** [review]

**Pull request merged**
