### PR TITLE
Pass through CancellationToken

### PR DESCRIPTION
**Pull request by MrXhh**
Pass through the CancellationToken when socket connect

# Pass through CancellationToken

- [ x ] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

Pass through the CancellationToken when socket connect

### CODE REVIEW

**Comment by amcasey** [comment]
That sure looks correct, but it's hard to say for certain that someone didn't omit that on purpose (without, for some reason, leaving a comment).  What prompted you to make the change?  Did something hang and this was the place cancellation didn't take effect?  Or did you just happen to notice an unused parameter?

**Comment by MrXhh** [comment]
> That sure looks correct, but it's hard to say for certain that someone didn't omit that on purpose (without, for some reason, leaving a comment). What prompted you to make the change? Did something hang and this was the place cancellation didn't take effect? Or did you just happen to notice an unused parameter?

image


```
    async Task Test(IConnectionFactory connectionFactory)
    {
        // Timeout
        CancellationTokenSource cts = new(2 * 1000);

        _ = await connectionFactory.ConnectAsync(default!, cts.Token);
    }
```

**Comment by JamesNK** [comment]
@amcasey I don't think this method has ever been used. It looks like a good change, it's just never happened because no one uses the API.

**Comment by MrXhh** [comment]
> @amcasey我认为这种方法从未被使用过。这看起来是一个很好的改变，只是从来没有发生过，因为没有人使用这个 API。

https://www.nuget.org/packages/Kestrel.Transport.Sockets.Client

https://github.com/xljiulang/SocketConnectionFactory

**Review by amcasey — APPROVED** [review]

**Pull request merged**
