### PR TITLE
Fix typo.

### PR DESCRIPTION
**Pull request by fadiksho**
# Fix typo 

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Description
Fix small typo in Microsoft.AspNetCore.Identity.UI.IdentityDefaultUIConfigureOptions

### CODE REVIEW

**Review by mitchdenny — APPROVED** [review]
Thanks. We'll merge once our build issues are unblocked.

**Comment by adityamandaleeka** [comment]
Clearly the typo was critical to ensure all the tests pass 😆.

@wtgodbe Can you please just merge this on red so we don't have to burn more CI time? I've reopened this issue for the flaky test: https://github.com/dotnet/aspnetcore/issues/36888

**Review by adityamandaleeka — APPROVED** [review]

**Pull request merged**
