### PR TITLE
[ApiAuthorization] Mark package as shipping

### PR DESCRIPTION
**Pull request by javiercn**

### CODE REVIEW

**Review by mkArtakMSFT — APPROVED** [review]

**Comment by mkArtakMSFT** [comment]
Will this automatically flow into the build/artefacts.json or should that be updated too?

**Comment by javiercn** [comment]
I believe it will flow. @dougbu can confirm

**Comment by mkArtakMSFT** [comment]
Let's get confirmation before merging this in. @dougbu ?

**Comment by javiercn** [comment]
> build/artefacts.json

There is no more artefacts.json (or artifacts.json for what matters)

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
No need for additional changes in this repo.

**Pull request merged**
