### PR TITLE
Revert "Revert "Remove downlevel runtimes from global.json""

### PR DESCRIPTION
**Pull request by wtgodbe**
Reverts dotnet/aspnetcore#40699 & adds an explicit 3.1 restore before trying to use `BinlogToSln`

### CODE REVIEW

**Comment by wtgodbe** [comment]
Should work now that we're explicitly restoring 3.1 for this step

**Comment by wtgodbe** [comment]
Test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1662820&view=results

**Review by dougbu — APPROVED** [review]
Approving but I prefer the `"rollForward": "major"` approach

**Comment by dsplaisted** [comment]
I think https://github.com/dotnet/sdk/issues/10375 was about a command-line option to enable tool roll-forward.  We never did that.  However, a tool should be able to specify "rollForward": "major" in its runtimeconfig.json file and that should work.

**Comment by wtgodbe** [comment]
I'm just going to take this as-is then since we're downloading & running the tool in the script

**Pull request merged**
