### PR TITLE
Remove test workaround for fixed issue.

### LINKED ISSUE #11206: System.IO.Pipelines.dll in the targeting pack is not a reference assembly
The versions of `System.IO.Pipelines.dll` and `System.Threading.Channels.dll` in Microsoft.AspNetCore.App.Ref aren't the actual reference assembly -- they're the implementation. This can cause problems later if there were to be a security issue with one of these since we don't plan to service the targeting pack. It also means the .dlls include unnecessary bloat.

This is happening because these packages only include a lib folder. To get the ref, we'll need to find a way to flow it from the corefx repo. (cref https://github.com/dotnet/corefx/tree/master/src/System.IO.Pipelines/ref/)

cc @davidfowl @Pilchie

### PR DESCRIPTION
**Pull request by Pilchie**
Fixes #11206

### CODE REVIEW

**Comment by Pilchie** [comment]
@JunTaoLuo does the mac timeout look like the issue you've been looking at?  Should I just re-run?

**Comment by Pilchie** [comment]
@aspnet/build can someone take a look at the change and sign off?

**Review by JunTaoLuo — APPROVED** [review]

**Comment by JunTaoLuo** [comment]
And yes, the hang was another instance of Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test.

**Comment by Pilchie** [comment]
@JunTaoLuo Is there a bug tracking that failure?  @ajcvickers Would we expect that to be fixed by the InMemory fixes you brought to tactics yesterday.

**Comment by ajcvickers** [comment]
@Pilchie @JunTaoLuo I don't see how this change is related to the in-memory Identity tests.

**Comment by Pilchie** [comment]
There was a flaky test failure in those tests which has been causing some timeouts lately.

**Comment by ajcvickers** [comment]
@Pilchie Which is the flaky test, and how does a change to `TargetingPackTests.cs` impact this?

**Comment by JunTaoLuo** [comment]
No, the "flaky" test and this change are separate issues. The "flaky" test Kevin and I are referring to is the one being tracked in https://github.com/aspnet/AspNetCore-Internal/issues/2926, specifically Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test. This caused a timeout in a build of this PR which subsequently passed on retry.

This change is for a separate change to remove an unnecessary workaround in TargetingPackTests.

**Pull request merged**
