### PR TITLE
Improved Bot Response for investigation issue

### PR DESCRIPTION
**Pull request by mkArtakMSFT**

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
@seangwright, thanks for your feedback here: https://github.com/dotnet/aspnetcore/issues/44857#issuecomment-1325554503

Do you think this would be a better response by the Bot?

**Review by TanayParikh — APPROVED** [review]

**Comment by seangwright** [comment]
Yes! This is definitely better.

Maybe this is more about process for the aspnetcore repo vs the messaging for this bot response, but seeing the `.NET 8 Planning` label get assigned has me immediately thinking "Oh, so this won't be fixed for .NET 7", which could cause confusion and frustration if a developer is reporting a show-stopper issue.

I'm guessing `.NET 8 Planning` is used to represent "these are things we are working on now vs. postponed for future"? If that's true, maybe some clarity there could help.

**Comment by mkArtakMSFT** [comment]
You're right, the `.NET 8 Planning` milestone is simply a bucket of work to be considered for .NET 8. Depending on the feedback we will receive over time on some of these issues, we will choose to also patch these for down-level releases too. We've tried our best to clarify that in our [Triage Process document](https://github.com/dotnet/aspnetcore/blob/main/docs/TriageProcess.md). Unfortunately, not everyone reads these and we found no better way so far to address this.

**Review by wtgodbe — APPROVED** [review]

**Comment by seangwright** [comment]
@mkArtakMSFT Maybe moving the triage process link earlier in the message (maybe at the top?) would get more people to click it.

I honestly never saw the link before even though I've seen this bot message many times here!

See below as an attempt to bring more focus to the link:

```
Thanks for contacting us.\n\nTo learn more about what this message means, what to expect next, and how this issue will be handled you can read more about [our triage process](https://github.com/dotnet/aspnetcore/blob/main/docs/TriageProcess.md)\n\nWe're moving this issue to the `.NET 8 Planning` milestone for future evaluation / consideration. Because it's not immediately obvious what is causing this behavior, we would like to keep this around to collect more feedback, which can later help us determine how to handle this. We will re-evaluate this issue, during our next planning meeting(s). \nIf we later determine, that the issue has no community involvement, or it's very rare and low-impact issue, we will close it - so that the team can focus on more important and high impact issues..
```

**Comment by mkArtakMSFT** [comment]
I like it and we can sure try to go with that message. Will update the PR soon.

**Pull request merged**
