### PR TITLE
Use F# task ce in worker template

### PR DESCRIPTION
**Pull request by slang25**
- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

**PR Title**
Use F# task ce in worker template

**PR Description**
We should now use the `task` computation expression in F# 6 to simplify the worker template.

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
Thanks for your PR, @slang25.
@shirhatti can you please review or find the right person to review this? Thanks!

**Comment by shirhatti** [comment]
Adding a link to [F# RFC for Task builder](https://github.com/fsharp/fslang-design/blob/main/preview/FS-1097-task-builder.md). (primarily to help folks like me who aren't familiar with F# 😅)

@halter73 are you our resident F# expert?

👀 @DamianEdwards since I know you were looking at updating all our templates to use the newest language idioms.

**Comment by DamianEdwards** [comment]
I believe @KevinRansom is our F# point-person now.

**Comment by DamianEdwards** [comment]
Also heads-up to @KathleenDollard as template changes can have rippled effects to the user experience that we need to coordinate updates to and that impacts the decision of whether we take it this late in the 6.0 cycle.

**Comment by vzarytovskii** [comment]
Since task builder is in F# 6 now, we can use it instead of async. Thanks, lgtm.

**Review by vzarytovskii — APPROVED** [review]

**Review by dsyme — APPROVED** [review]

**Comment by dsyme** [comment]
Thanks @slang25 !

**Pull request merged**
