### PR TITLE
Port ANCM installer changes to 2.1

### PR DESCRIPTION
**Pull request by jkotalik**
This will also allow us to remove the ANCM installer and Window hosting bundles steps in team city.

### CODE REVIEW

**Comment by natemcmaster** [comment]
I still see files in https://github.com/aspnet/AspNetCore/tree/jkotalik/21Installers/src/IISIntegration/src/AspNetCoreModuleV2. Should these be removed, too?

**Review by natemcmaster — APPROVED** [review]
One question, but otherwise LGTM.

cc @muratg for approval as well.

**Review by muratg — APPROVED** [review]
Approved.

**Comment by natemcmaster** [comment]
> I can go ahead and do it in this PR 

Separately or inline with this PR is fine with me. Just wanted to avoid having any confusion about what we have to service in the future when there is (inevitably) a servicing bug in ancm v2

**Comment by natemcmaster** [comment]
By the way, please hold off until we open the branch for 2.1.7. I'll let you know when that happens. Hopefully later this week.

**Comment by jkotalik** [comment]
We good: http://aspnetci/viewLog.html?buildId=590687&buildTypeId=Releases_21Public_WindowsInstallers&tab=artifacts#!fk6iluux85,-1xlv4ivii3kto

**Comment by natemcmaster** [comment]
:shipit:

**Pull request merged**
