### PR TITLE
Update branding to 2.2.8

### PR DESCRIPTION
**Pull request by dougbu**
- aspnet/AspNetCore-Internal#3153

### CODE REVIEW

**Comment by dougbu** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=362961

**Comment by dougbu** [comment]
@anurse whether or not the hello bot wakes up and creates / update issues, I'd appreciate your help. It seems this simple PR frequently hits `dotnet watch` and SignalR issues. Could you please have someone take a look?

Latest [build hit](https://dev.azure.com/dnceng/public/_build/results?buildId=362961&view=logs&j=7536d2cd-87d4-54fe-4891-bfbbf2741d83&t=32a004b5-6abc-5719-dbf1-16350e4ba258&l=6292) the following:
```
[xUnit.net 00:02:28.73]     Microsoft.DotNet.Watcher.Tools.FunctionalTests.DotNetWatcherTests.RunsWithIterationEnvVariable [FAIL]
  Failed   Microsoft.DotNet.Watcher.Tools.FunctionalTests.DotNetWatcherTests.RunsWithIterationEnvVariable
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at Microsoft.DotNet.Watcher.Tools.FunctionalTests.AwaitableProcess.GetOutputLineAsync(String predicateName, Predicate`1 predicate, CancellationToken cancellationToken) in /_/src/Tools/dotnet-watch/test/AwaitableProcess.cs:line 100
     at Microsoft.DotNet.Watcher.Tools.FunctionalTests.AwaitableProcess.GetOutputLineAsync(String message, TimeSpan timeout) in /_/src/Tools/dotnet-watch/test/AwaitableProcess.cs:line 85
     at Microsoft.DotNet.Watcher.Tools.FunctionalTests.DotNetWatcherTests.RunsWithIterationEnvVariable() in /_/src/Tools/dotnet-watch/test/DotNetWatcherTests.cs:line 44
  --- End of stack trace from previous location where exception was thrown ---
  Standard Output Messages:
   The temporary test folder is /home/vsts/work/1/s/bin/dotnet-watch.Tests/Release/netcoreapp2.2/tmp/3pxbdz12.flv
   Copying project /home/vsts/work/1/s/bin/dotnet-watch.Tests/Release/netcoreapp2.2/TestProjects/KitchenSink to /home/vsts/work/1/s/bin/dotnet-watch.Tests/Release/netcoreapp2.2/tmp/3pxbdz12.flv/KitchenSink
   Restoring msbuild project in KitchenSink
   Project directory: '/home/vsts/work/1/s/bin/dotnet-watch.Tests/Release/netcoreapp2.2/tmp/3pxbdz12.flv/KitchenSink'
   Started process 19649: /home/vsts/work/1/.dotnet/dotnet restore
     Restoring packages for /home/vsts/work/1/s/bin/dotnet-watch.Tests/Release/netcoreapp2.2/tmp/3pxbdz12.flv/KitchenSink/KitchenSink.csproj...
     Generating MSBuild file /home/vsts/work/1/s/bin/dotnet-watch.Tests/Release/netcoreapp2.2/tmp/3pxbdz12.flv/KitchenSink/.net/obj/KitchenSink.csproj.nuget.g.props.
     Generating MSBuild file /home/vsts/work/1/s/bin/dotnet-watch.Tests/Release/netcoreapp2.2/tmp/3pxbdz12.flv/KitchenSink/.net/obj/KitchenSink.csproj.nuget.g.targets.
     Restore completed in 226.98 ms for /home/vsts/work/1/s/bin/dotnet-watch.Tests/Release/netcoreapp2.2/tmp/3pxbdz12.flv/KitchenSink/KitchenSink.csproj.
```
&hellip;
```
  9/23/19 5:22:53 AM: post: 'watch : Waiting for a file to change before restarting dotnet...'
   9/23/19 5:22:53 AM: recv: 'watch : Waiting for a file to change before restarting dotnet...'. Matches condition '[msg.StartsWith('watch : Waiting for a file to change')]'.
   Waiting for output line [msg == 'Started']. Will wait for 60 sec.
   Disposing WatchableApp
```
and
```

     at Microsoft.AspNetCore.SignalR.Tests.FunctionalTestBase.MultiDisposable.Dispose() in /home/vsts/work/1/s/src/SignalR/common/testassets/Tests.Utils/FunctionalTestBase.cs:line 55
     at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.ExceptionFromStreamingSentToClient(String protocolName, HttpTransportType transportType, String path) in /_/src/SignalR/clients/csharp/Client/test/FunctionalTests/HubConnectionTests.cs:line 466
  --- End of stack trace from previous location where exception was thrown ---
  Standard Output Messages:
```
&hellip;
```
   | [0.040s] Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher Error: rzPxxc_UEZdhtLsuSqcz6g - Failed to invoke hub method 'StreamException'.
   | System.InvalidOperationException: Error occurred while streaming.
   |    at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.TestHubMethodsImpl.StreamException() in /_/src/SignalR/clients/csharp/Client/test/FunctionalTests/Hubs.cs:line 168
   |    at lambda_method(Closure , Object , Object[] )
   |    at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteHubMethod(ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments) in /_/src/SignalR/server/Core/src/Internal/DefaultHubDispatcher.cs:line 330
   |    at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.Invoke(HubMethodDescriptor descriptor, HubConnectionContext connection, HubMethodInvocationMessage hubMethodInvocationMessage, Boolean isStreamedInvocation) in /_/src/SignalR/server/Core/src/Internal/DefaultHubDispatcher.cs:line 225
```
&hellip;
```
   |    at Microsoft.AspNetCore.Http.Connections.Internal.Transports.LongPollingTransport.ProcessRequestAsync(HttpContext context, CancellationToken token)
   | [0.055s] Microsoft.AspNetCore.Server.Kestrel Error: Connection id "0HLPVT0E8KU1I", Request id "0HLPVT0E8KU1I:00000005": An unhandled exception was thrown by the application.
   | System.InvalidOperationException: Reading is not allowed after reader was completed.
   |    at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoReadingAllowed()
   |    at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   |    at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   |    at Microsoft.AspNetCore.Http.Connections.Internal.Transports.LongPollingTransport.ProcessRequestAsync(HttpContext context, CancellationToken token)
   |    at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher.ExecuteAsync(HttpContext context, ConnectionDelegate connectionDelegate, HttpConnectionDispatcherOptions options, ConnectionLogScope logScope)
   |    at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher.ExecuteAsync(HttpContext context, HttpConnectionDispatcherOptions options, ConnectionDelegate connectionDelegate)
   |    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```
&hellip;
```
 Application startup exception: System.NotSupportedException: Duplicate definitions of 'OverloadedMethod'. Overloading is not supported.
     at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.DiscoverHubMethods() in /_/src/SignalR/server/Core/src/Internal/DefaultHubDispatcher.cs:line 446
     at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1..ctor(IServiceScopeFactory serviceScopeFactory, IHubContext`1 hubContext, IOptions`1 hubOptions, IOptions`1 globalHubOptions, ILogger`1 logger) in /_/src/SignalR/server/Core/src/Internal/DefaultHubDispatcher.cs:line 38
  --- End of stack trace from previous location where exception was thrown ---
     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
     at Microsoft.Extensions.Internal.ActivatorUtilities.GetServiceOrCreateInstance[T](IServiceProvider provider)
     at Microsoft.AspNetCore.Connections.ConnectionBuilderExtensions.UseConnectionHandler[TConnectionHandler](IConnectionBuilder connectionBuilder)
     at Microsoft.AspNetCore.SignalR.HubRouteBuilder.<>c__3`1.<MapHub>b__3_0(IConnectionBuilder builder) in /_/src/SignalR/server/SignalR/src/HubRouteBuilder.cs:line 58
     at Microsoft.AspNetCore.Http.Connections.ConnectionsRouteBuilder.MapConnections(PathString path, HttpConnectionDispatcherOptions options, Action`1 configure)
     at Microsoft.AspNetCore.SignalR.HubRouteBuilder.MapHub[THub](PathString path, Action`1 configureOptions) in /_/src/SignalR/server/SignalR/src/HubRouteBuilder.cs:line 59
     at Microsoft.AspNetCore.SignalR.Tests.MapSignalRTests.<>c.<MapSignalRFailsForInvalidHub>b__0_1(HubRouteBuilder routes) in /_/src/SignalR/server/SignalR/test/MapSignalRTests.cs:line 18
     at Microsoft.AspNetCore.Builder.ConnectionsAppBuilderExtensions.UseConnections(IApplicationBuilder app, Action`1 configure)
     at Microsoft.AspNetCore.Builder.SignalRAppBuilderExtensions.UseSignalR(IApplicationBuilder app, Action`1 configure) in /_/src/SignalR/server/SignalR/src/SignalRAppBuilderExtensions.cs:line 35
     at Microsoft.AspNetCore.SignalR.Tests.MapSignalRTests.<>c__DisplayClass9_0.<BuildWebHost>b__1(IApplicationBuilder app) in /_/src/SignalR/server/SignalR/test/MapSignalRTests.cs:line 140
     at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication() in /_/src/Hosting/Hosting/src/Internal/WebHost.cs:line 219
```

**Comment by dougbu** [comment]
The test failures occurred in a pipeline that's not required to be successful However that pipeline is closer to what we do after checkin and to what we need to do when transitioning from TC to AzDO.

**Comment by anurse** [comment]
@BrennanConroy can you take a look?

**Comment by dougbu** [comment]
/bump reviewers

@anurse / @BrennanConroy looks like the failures cleared in my latest retry. So, flakiness. I'm hoping we can grab changes from later branches that harden against that flakiness.

**Review by wtgodbe — APPROVED** [review]

**Comment by BrennanConroy** [comment]
dotnet-watch test flakiness was fixed in https://github.com/aspnet/AspNetCore/pull/9649 which looks like a safe fix to backport

The SignalR test failure fix would be a lot harder to backport as it modifies public class(es)

**Comment by BrennanConroy** [comment]
If I remember correctly this failure can affect almost all tests involving LongPolling :/

We could try to add a "global" expected log filter to our tests for this specific log.

**Comment by anurse** [comment]
Hrm, I'll chat with you offline and see what we can do. Removing coverage for Long Polling entirely is probably not appropriate.

**Pull request merged**
