### PR TITLE
Use TypeCheckDelegate helper to map Delegate types

### LINKED ISSUE #23892: Fix setting nullable Action parameters on components
When passing an Action from one Component to another component if the value is null the code throws the following exception: `System.ArgumentException: 'Delegate to an instance method cannot have null 'this'.'`

This is caused by the generated code, because it tries to create an instance of the Action delegate instead of just passing the value along as it is:

**Component A - Generated Code (A.razor.g.cs)**
```
public partial class A : Microsoft.AspNetCore.Components.ComponentBase
    {
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenComponent<B>(0);
            __builder.AddAttribute(1, "When", new System.Action(When));
            __builder.CloseComponent();
        }

	[Parameter]
	public Action When { get; set; }

}
```

**Component A (A.razor)**
```
@code{

	[Parameter]
	public Action When { get; set; }

}

<B When="@When" />

```

**Component B (B.razor)**
```
@code{

	[Parameter]
	public Action When { get; set; }

}

<span>Empty</span>
```

Is there a way to override the code generation logic to stop this `__builder.AddAttribute(1, "When", new System.Action(When));` and instead do `__builder.AddAttribute(1, "When", When);`.

### PR DESCRIPTION
**Pull request by captainsafia**
Resolves https://github.com/dotnet/aspnetcore/issues/23892.

**Problem**
Prior to this change, when the Razor compiler encountered an attribute with a delegate type on a component:

```razor
// Component1.razor
@code {
  [Parameter] public Action<int> OnClick { get; set; }
  
  protected override void OnAfterRender(bool firstRender)
  {
    Console.WriteLine(OnClick(3));
  }
}

// Index.razor
<Component1 OnClick="Increment" />

@code {
  private void Increment(int value) {
    System.Console.WriteLine($"Increment by {value}");
  }
}
```

produces the following generated C#:

```csharp
__builder.AddAttribute(29, "OnClick", new System.Action(Increment));
```

This is fine and dandy  for most scenarios, unless you're trying to pass an attribute value that might be null. In which case, the resulting generated C# would effectively be:

```csharp
__builder.AddAttribute(29, "OnClick", new System.Action(null));
```

which leads to unhandled exceptions at runtime because you can't create an Action delegate from a null value:

> System.ArgumentException: 'Delegate to an instance method cannot have null 'this'.'

It would suffice to remove the `System.Action` constructor all together and just produce the following code:

```csharp
__builder.AddAttribute(29, "OnClick", Increment);
__builder.AddAttribute(29, "OnClick", null);
```

However, this causes an issue if the attribute parameter that is passed is a reference to a method group since there's no opportunity for the method group to be converted to a delegate when wrapped in a `System.Action` constructor.

**Proposed Solution**

This proposed solution uses an inline cast to complete the type conversion and validation.

I've verified that this does the right thing in runtime with a few scenarios in https://github.com/captainsafia/NullableParam. You can also view the updated generated source in the repo.

```csharp
__builder.AddAttribute(29, "OnClick", (System.Action<System.EventArgs>)(
#nullable restore
#line 27 "/Users/captainsafia/Verifications/NullableParam/Pages/Index.razor"
  IncrementWithEventArgs
#line default
#line hidden
#nullable disable
));
```

**Alternatives Considered**

I considered adding some cleverness to the compiler to only write the delegate constructor under the right conditions but its almost impossible to accurately determine this without landing into the method-group-to-delegate-conversion problem.

Another alternative considered was adding a new `TypeCheckDelegate` method to the M.A.Components.CompilerServers package that implements the functionality of the `TypeCheck` method but includes a `T assignedValue = originalValue` assignment to complete the method group conversion.

### CODE REVIEW

**Comment by davidfowl** [comment]
> I considered adding some cleverness to the compiler to only write the delegate constructor under the right conditions but its almost impossible to accurately determine this without landing into the method-group-to-delegate-conversion prblem.

I wonder if this will resolve itself with C# 10 with the work we're doing to [improve lambdas](https://github.com/dotnet/csharplang/blob/main/proposals/lambda-improvements.md)

**Comment by captainsafia** [comment]
> I wonder if this will resolve itself with C# 10 with the work we're doing to improve lambdas

I don't believe so. This has more to do with being able to determine whether an attribute value is a lambda expression (`AttributeKey="@(() => Console.WriteLine(""foo""))"`) when we are rewriting Razor to the generated C#.

**Comment by jaredpar** [comment]
Having trouble following part of this and I think it's just because I don't understand the internals of Razor well and hence getting lost. Can you help me understandwhy the following won't work here? 

```c#
__builder.AddAttribute(29, "OnClick", (Action)null);
```

**Comment by captainsafia** [comment]
> Having trouble following part of this and I think it's just because I don't understand the internals of Razor well and hence getting lost. Can you help me understandwhy the following won't work here?

🤧  Yeah, I totally didn't consider that it could be as simple as doing the cast inline. I don't see any reason that this shouldn't work but I'll give it a go.

It has the benefit of removing any new APIs that we need to add.

**Review by jaredpar — APPROVED** [review]

**Review by SteveSandersonMS — APPROVED** [review]
This looks super to me. It's really clean and simple.

I've been trying to think of any historical reasons why we might have wanted the explicit `new DelegateType(...)` rather than just `(DelegateType)...` and can't think of any. Combined with there not being any test cases that would require a `new`, my best guess is that we really don't need the `new` and it was only done originally because it looks more explicit. If anyone knows of any cases where the cast wouldn't handle something that `new` would, please say so!

I wonder if the cast will reduce allocations too. Previously if the expression was already an actual delegate instance, then `new Action(someExistingAction)` looks like it would do a further allocation which `(Action)someExistingAction` wouldn't. At least, that's how it looks in [the IL code here](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDZICYgNQA+AAgEwCMAsAFBEDMABKfQML0De19XjZJ9YATyK8k9APYwAFomEkAamggA5OAHdRE6QlkKIzaDADcnbnUYAWegFkAFAEp2J7t0Gz6AXnr2PAPnY8AThspNCg7Q3oAX2MqZ2dNGV5dFVUPegA7NR4SG1decKc4hO0kxX1YNJtZOzySGOdI6kigA).

**Comment by captainsafia** [comment]
> I've been trying to think of any historical reasons why we might have wanted the explicit new DelegateType(...) rather than just (DelegateType)... and can't think of any. 

Yeah, I wasn't able to find anything in the commit history WRT to this (albeit the code move makes it harder to grok stuff older than a few years). I think the test coverage gives us some confidence about the change here.

**Comment by ldsenow** [comment]
Just wondering is it possible to have this fix in .net 5 or via a nuget package?

**Pull request merged**
