### PR TITLE
Add a TypeForward for JsonResult

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes https://github.com/aspnet/AspNetCore/issues/7220

### CODE REVIEW

**Review by natemcmaster — APPROVED** [review]

**Comment by davidfowl** [comment]
Do you need to do it this way? Would TypeForwardFrom work? Or nah?

**Comment by pranavkm** [comment]
I thought `TypeForwardedFrom` was informational only and not used for type resolution.

**Comment by davidfowl** [comment]
Ah I see.

**Comment by davidfowl** [comment]
@pranavkm how did you test this? Should we reference the 2.1 package in one of our tests?

**Comment by pranavkm** [comment]
I added a reference to the Swashbuckle in the MvcSandbox and saw it fail as soon as I referenced `JsonResult`. Using the helper method on `Controller` worked fine. Once the type forward was in place, the error was resolved.

> Should we reference the 2.1 package in one of our tests?

Would help to test it against a real app (something that references the framework, like MusicStore), but it's really unlikely this is a scenario we would regress.

**Review by davidfowl — APPROVED** [review]

**Pull request merged**
