### PR TITLE
[ApiAuth] Update partner dependencies to their final versions

### PR DESCRIPTION
**Pull request by javiercn**
* Updates the oidc-client dependency to 1.9.4 RTM that was published last Friday.

### CODE REVIEW

**Review by ryanbrandenburg — APPROVED** [review]

**Comment by ryanbrandenburg** [comment]
Failure seems to have been transient networking stuff, should pass on re-run.

**Review by dougbu — APPROVED** [review]
Guess this is ready for Tactics _now_?

**Comment by javiercn** [comment]
No, still doesn't have the final version

**Comment by javiercn** [comment]
This is ready to go to tactics now

**Comment by Pilchie** [comment]
Thanks - looks like there are some test issues.  Once those are resolved, I'll send mail.

**Comment by javiercn** [comment]
@Pilchie I'm on it. I'll ping you here.

**Comment by Pilchie** [comment]
Looks like @mkArtakMSFT already gave them a heads up.

**Comment by javiercn** [comment]
The migrations need to be regenerated

**Pull request merged**
