### PR TITLE
Remove obsolete APIs from routing

### PR DESCRIPTION
**Pull request by JamesNK**
Addresses #7321

### CODE REVIEW

**Review by rynowak — APPROVED** [review]

**Comment by Tratcher** [comment]
`2019-02-08T08:23:05.4383470Z F:\vsagent\5\s\src\Mvc\test\Microsoft.AspNetCore.Mvc.Core.Test\Routing\AttributeRoutingTest.cs(178,48): error CS7036: There is no argument given that corresponds to the required formal parameter 'serviceProvider' of 'DefaultInlineConstraintResolver.DefaultInlineConstraintResolver(IOptions<RouteOptions>, IServiceProvider)' [F:\vsagent\5\s\src\Mvc\test\Microsoft.AspNetCore.Mvc.Core.Test\Microsoft.AspNetCore.Mvc.Core.Test.csproj]`

**Comment by JamesNK** [comment]
https://github.com/aspnet/AspNetCore-Internal/issues/1827

**Pull request merged**
