### PR TITLE
Add System.Text.Json protocol to the SignalR functional tests

### PR DESCRIPTION
**Pull request by mikaelm12**
We have another protocol to run our functional tests against.

### CODE REVIEW

**Comment by mikaelm12** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=177292&view=logs

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2457

**Comment by mikaelm12** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=177380&view=logs

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact aspnetcore-build@microsoft.com.

I've triaged the above build. I've created/commented on the following issue(s)
https://github.com/aspnet/AspNetCore-Internal/issues/2394

**Review by halter73 — APPROVED** [review]

**Review by BrennanConroy — APPROVED** [review]

**Comment by anurse** [comment]
Do we know how much this impacts test run time? When adding a significant number of new tests we should make sure we understand how it impacts the run time so we don't end up with super long test runs.

**Pull request merged**
