### PR TITLE
[release/5.0-preview3] Remove Code_check job from publish-build-assets.yml `dependsOn`…

### PR DESCRIPTION
**Pull request by mmitche**
… (#20558)

- nit: remove redundant conditions for easier reading

### CODE REVIEW

**Comment by mmitche** [comment]
Fixes currently blcoking issue for preview3

**Comment by wtgodbe** [comment]
This one is also necessary: https://github.com/dotnet/aspnetcore/pull/20615

**Review by wtgodbe — APPROVED** [review]

**Review by Anipik — APPROVED** [review]

**Comment by dougbu** [comment]
This is merged but doesn't show in the history. What's going on?

**Comment by mmitche** [comment]
I see it in the history now.

**Comment by dougbu** [comment]
`git show 96b0b000234ce7cc21cc126251409df2661a97a5` looks like a no-op merge on the command line and [here in GitHub](https://github.com/dotnet/aspnetcore/commit/96b0b000234ce7cc21cc126251409df2661a97a5). Why was it necessary?

**Comment by dougbu** [comment]
(The no-op is the reason the change didn't show up in the `git log origin/release/5.0-preview3 -- .azure/pipelines/ci.yml` history I was looking at.)

**Pull request merged**
