### PR TITLE
Use StaticWebAssetBasePath if specified to calculate blazorwasm publish paths

### PR DESCRIPTION
**Pull request by pranavkm**
In 3.2, Blazor WebAssembly had a feature which allowed prefix the relative path within the PublishDir
by configuring a StaticWebAssetBasePath property in the project file. As part of migrating to 5.0, this
feature was (accidentally) not brought forward which is remedied by this commit.

* Use StaticWebAssetBasePath to calculate asset base paths
* Add publish tests to verify hosted and standalone scenarios

Fixes https://github.com/dotnet/aspnetcore/issues/27776

### Description

We [document](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#hosted-deployment-with-multiple-blazor-webassembly-apps) using `StaticWebAssetBasePath ` to change relative paths inside the publish directory for blazor-wasm apps. However we missed porting over this feature when creating the Blazor WebAssembly SDK.

### Customer impact

Using this feature is key to being able to host multiple blazor-wasm apps side-by-side.

### Regression

Yes. Regression from 3.2

### Risk
Low. On one hand this is a SDK-only fix and the change is relatively minor. On the other hand, the implementation is different from 3.2 (code is very different) and we don't have any old tests to compare results against. There's a chance the results don't line up with what more complicated apps might expect. But at least for a app created from the project template, the outputs line up with our documentation and 3.2's outputs.

### CODE REVIEW

**Review by javiercn — APPROVED** [review]
Looks good to me based on the additional tests.

I would like however to go through the changes here to understand why some files are no longer considered static web assets.

**Comment by mkArtakMSFT** [comment]
This has been approved by Tactics.

**Comment by wtgodbe** [comment]
`Publish_WithStaticWebBasePathWorks` has been failing here:

> System.InvalidOperationException : Could not find project at '/datadisks/disk1/workspace/_work/1/s/src/Components/WebAssembly/Sdk/integrationtests/../testassets/RazorClassLibrary'

**Comment by mkArtakMSFT** [comment]
@dotnet/aspnet-blazor-eng can someone take this over given that @pranavkm is on vacation?

**Comment by HaoK** [comment]
I can take a look

**Comment by pranavkm** [comment]
@HaoK I pushed an update (it was a path casing issue). Could you wait to see if it's resolved in the next build?

**Comment by HaoK** [comment]
Thanks @pranavkm :)

**Comment by mkArtakMSFT** [comment]
@HaoK can you please address the pending issues - let's try to merge this today.

**Comment by HaoK** [comment]
I think the tests are passing now but the azdo machines keep going down failing the ci, restarting them one more time, but the failing linux test job appears fixed.  Hopefully the machines will stay up to actually finish the full aspnetccore-ci checks this time

**Comment by HaoK** [comment]
Looks like the helix machines are having issues as there have been mails saying they are having issues imaging machines, but everything else is green, and this is in the sdk which isn't being tested on helix so for all intensive purposes this PR is green.  I can keep hitting retry, but its going to be a while for helix to catch up I'd guess

**Pull request merged**
