### PR TITLE
Update PoliCheckExclusions.xml

### PR DESCRIPTION
**Pull request by BrennanConroy**
Ignore test log output

### CODE REVIEW

**Review by dougbu — APPROVED** [review]

**Comment by BrennanConroy** [comment]
FYI this is on the 3.1 branch since it looks like that's when we added the check.

**Comment by wtgodbe** [comment]
@BrennanConroy please hold off on merging until we finish builds for 3.1.1. That likely means waiting until January. Feel free to manually put up a port PR in master if you want it there earlier

**Comment by BrennanConroy** [comment]
@dotnet/aspnet-build can we merge this now?

**Comment by dougbu** [comment]
@BrennanConroy no.

The branding updates, #18151 in particular for this base branch, must go in first. @JunTaoLuo needs to update these PRs and wait for validation to completely. He's working his way through the repos.

**Comment by BrennanConroy** [comment]
@dotnet/aspnet-build please merge! 😸

**Pull request merged**
