### PR TITLE
Remove redundant site extension fix

### PR DESCRIPTION
**Pull request by JunTaoLuo**
Missed the revert of an earlier fix in https://github.com/dotnet/aspnetcore/pull/27841.

### CODE REVIEW

**Review by dougbu — APPROVED** [review]

**Comment by Pilchie** [comment]
@BrennanConroy @jkotalik - do you know if we need this for 5.0.1?

**Comment by BrennanConroy** [comment]
I assume this was just adding extra files to the package that should have no effect on users.

Since it was accidentally added in 5.0.1 I think removing it in 5.0.1 is fine.

**Comment by jkotalik** [comment]
I think we should try getting this into 5.0.1

**Comment by dougbu** [comment]
This is good cleanup but the timing isn't critical. @JunTaoLuo is removing a confusing mention of files that no longer exist and never shipped in any package.

**Comment by dougbu** [comment]
BTW, the not-in-any-package part is because `@(_TemplateFiles)` become part of a generated project, not directly part of a package.

**Comment by JunTaoLuo** [comment]
FYI, I'll withhold this cleanup PR for the next servicing release since it's not urgent.

**Pull request merged**
