### PR TITLE
Fix typo in bug report template

### PR DESCRIPTION
**Pull request by bgrainger**
Should be "its" not "it's".

### CODE REVIEW

**Review by Pilchie — APPROVED** [review]
Thanks!

**Comment by Pilchie** [comment]
@dotnet/aspnet-build - any idea why CI isn't reporting status here?

**Comment by TanayParikh** [comment]
> any idea why CI isn't reporting status here?

Hmm I'm not seeing anything apparent. Other PRs are flowing through the CI as expected: https://dev.azure.com/dnceng/public/_build?definitionId=278&_a=summary

Seeing if a close/open re-triggers it.

**Comment by TanayParikh** [comment]
Looks like that did the trick. Must've been a momentary issue.

**Comment by wtgodbe** [comment]
We don't run CI for changes to markdown files anymore: https://github.com/dotnet/aspnetcore/pull/27484

**Comment by TanayParikh** [comment]
> We don't run CI for changes to markdown files anymore: #27484

Thanks, [updated dotnet/aspnetcore-tooling with those changes as well](https://github.com/dotnet/aspnetcore-tooling/pull/2831).

**Comment by Pilchie** [comment]
But the check still shows as required, so I'm not sure how that helps?

**Comment by wtgodbe** [comment]
Ohh, interesting - I guess we didn't think of that. The check is still required, even if it doesn't run. The only other option that looks promising is "Maestro auto-merge - All Checks Successful", but that would make the quarantined job a required check too when it runs, which it isn't today. Maybe it'd be best to undo that change for now.

**Pull request merged**
