### PR TITLE
[6.0] Initialize Activity with parent ID

### PR DESCRIPTION
**Pull request by adityamandaleeka**
Opening as draft while we consider for servicing.

Fixes https://github.com/dotnet/aspnetcore/issues/37471 for 6.0

### CODE REVIEW

**Comment by dougbu** [comment]
@adityamandaleeka is this intended for 6.0.7❔ If yes, needs `Ready for review`, a team approval, and `servicing-approved`

**Comment by adityamandaleeka** [comment]
@dougbu I'm holding off on this for now.

**Comment by adityamandaleeka** [comment]
@ohadschn I was waiting for .NET 7 Preview 5 to come out so we could get validation that the fix is sufficient before putting it into 6.0 servicing. .NET 7 Preview 5 just released a few hours ago and includes this fix, so if you could try it out and let me know, that would be helpful!

**Comment by japui** [comment]
6.0] Inicialize a atividade com o ID pai

**Comment by dougbu** [comment]
@adityamandaleeka is this likely to be aimed at `6.0.10`❔

**Pull request closed without merging**
