### PR TITLE
Try make IOQueue auto-parallelizing

### PR DESCRIPTION
**Pull request by tmds**
Applies the technique from https://github.com/dotnet/runtime/pull/35330 to IOQueue.

### CODE REVIEW

**Comment by tmds** [comment]
This is an experiment for benchmarking. I'm not sure what to expect.

cc @kouvel @adamsitnik  @stephentoub @halter73 @davidfowl

**Comment by tmds** [comment]
cc @benaadams

**Comment by adamsitnik** [comment]
> Applies the technique from dotnet/runtime#35330 to IOQueue.

I was thinking about it too :D

The other (and most probably a **very stupid**) idea I had was to try to have a scheduler that in the ctor would use reflection to access the internal field of ThreadPool that stores the work items in a `ConcurrentQueue`:

https://github.com/dotnet/runtime/blob/ec2209e7360cfae481c9f6df8540dccadb02dcb4/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPool.cs#L403

and implement the `Schedule` method as a simple call to enqueue of this CQ

Again, this is a very dirty idea ;)

**Comment by adamsitnik** [comment]
@tmds could you provide the modified `.dll` so I could run some benchmarks for you?

**Comment by stephentoub** [comment]
> Again, this is a very dirty idea ;)

As an experiment it's fine. We will not ship that.

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by davidfowl** [comment]
TFMS!

**Comment by halter73** [comment]
@aspnet-hello benchmark

**Comment by benaadams** [comment]
Is there a non-pipelined benchmark that can be triggered?

**Comment by tmds** [comment]
> @tmds could you provide the modified .dll so I could run some benchmarks for you?

@adamsitnik here you to: [Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll.tar.gz](https://github.com/dotnet/aspnetcore/files/4643865/Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll.tar.gz)

**Comment by halter73** [comment]
@aspnet-hello benchmark json

**Comment by benaadams** [comment]
I was looking at the traces and sendmsg is very slow (comparatively); so thought it wasn't a good idea to have the sends on the same queue as the receives (thus blocking them).

However, didn't have great success in separating them https://github.com/dotnet/aspnetcore/pull/21981

**Comment by adamsitnik** [comment]
@tmds the results:

obraz

**Comment by tmds** [comment]
On ARM this gives some nice results. On Citrine, regression.
I'll close this based on Citrine regression.

**Comment by tmds** [comment]
An interesting observation:
```
Starting PR run on '778f8d5c3a8c90497fee6f65621544a1bed0ffde'...
| Description |     RPS | CPU (%) | Memory (MB) | Avg. Latency (ms) | Startup (ms) | Build Time (ms) | Published Size (KB) | First Request (ms) | Latency (ms) | Errors | Ratio |
| ----------- | ------- | ------- | ----------- | ----------------- | ------------ | --------------- | ------------------- | ------------------ | ------------ | ------ | ----- |
|      Before | 622,644 |      99 |         201 |               3.9 |          461 |            5504 |              120819 |             144.42 |         0.44 |      0 |  1.00 |
|       After | 605,376 |      98 |         199 |              3.94 |          470 |            5502 |              120819 |             143.89 |         0.38 |      0 |  0.97 |
```
After we use less CPU.
A hypothesis: there is contention, and parallelizing doesn't help.

**Pull request closed without merging**
