### PR TITLE
Fix #7477 by updating HttpSys readme

### LINKED ISSUE #7477: Update HttpSys README
When I went to the [HttpSys server sources](https://github.com/aspnet/AspNetCore/tree/master/src/Servers/HttpSys), I saw that the README file lists that the library has been archived and moved to the main AspNetCore repo. Of course, we are _in_ the main AspNetCore repo. This message made me confused for a moment because I thought that the HttpSys server has been deprecated, which would be annoying if true. Development on this component has continued since the README was last modified (as of this writing, #7207 was the last PR affecting this component). Would it be possible to please update this README to eliminate this confusion? Thanks!

### PR DESCRIPTION
**Pull request by analogrelay**
We changed the README to "archived" before merging this repo into mondo repo. Whoops :).

Fixes #7477

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]

**Comment by jkotalik** [comment]
Builds be slow <_<

**Comment by anurse** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=128062

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

I've triaged the above build.

**Comment by anurse** [comment]
Second attempt succeeded even though GitHub didn't update... https://dev.azure.com/dnceng/public/_build/results?buildId=128062

**Pull request merged**
