### PR TITLE
[release/5.0] Add option to `RazorPageGenerator` for `#line` preprocessor directives (#27765)

### PR DESCRIPTION
**Pull request by dougbu**
- cherry-picked from 1a241fcfc2f8 in 'master' branch

- avoid new CS1504 errors because compiler can't find the ErrorPage.cshtml file
  - we override Arcade's `$(MicrosoftCodeAnalysisCSharpVersion)`
- use new option in GeneratePage.ps1 script
  - script also did not know `RazorSyntaxGenerator` had moved to this repo
- reflect latest `RazorSyntaxGenerator` processing
  - run GeneratePage.ps1
  - update README.md

nits:
- quote all paths in GeneratePage.ps1 script
- remove passive voice in README.md

### CODE REVIEW

**Comment by dougbu** [comment]
Suggesting tell-mode for 5.0.3. Sound right @Pilchie❔

**Review by wtgodbe — APPROVED** [review]

**Comment by Pilchie** [comment]
Why tell mode?  Can you elaborate on what your fixing, where it's used, etc?  I'm not familiar with this bit of the repo.

**Comment by dougbu** [comment]
> Why tell mode?

### Short answer

It's all build infrastructure. Well, not quite but&hellip;

### More correct answer

The main changes are in a tool (`RazorSyntaxGenerator`) that does not ship and is only used manually. I am changing a single generated source file but only its contained `#line` pragmas and only to satisfy Roslyn.

### Background

The change corrects build failures I've repeatedly seen locally but aren't yet happening on the CI.

The src/Shared/ErrorPage/ErrorPage.Designer.cs file is checked into the repo and compiled into a number of our projects. Newer versions of Roslyn validate the generated `#line` pragmas in this file and complain when the ErrorPage.cshtml file isn't found because it's in the src/Shared/ErrorPage/Views sub-directory. That is, builds fail because the `#line` pragmas are wrong.

We fixed this in 'master' but haven't done the same in 'release/5.0' yet. This will soon be necessary because the Roslyn compiler ships (in part) with VS and core-eng updates VS on the build agents.

The specific fix is to correct the tool used to generate the ErrorPage.Designer.cs file (`RazorSyntaxGenerator`) and then use it to fix the `#line` pragmas.

An alternate fix would be to move the generated file into the Views sub-directory and then change the references in consuming projects. I chose the current fix because it was somewhat more localized and gave me an opportunity to fix the "script also did not know `RazorSyntaxGenerator` had moved to this repo" bit.

**Comment by Pilchie** [comment]
> This will soon be necessary because the Roslyn compiler ships (in part) with VS and core-eng updates VS on the build agents.

But we build these bits with `dotnet build` right?  So they should be isolated from the VS version?

**Comment by dougbu** [comment]
> But we build these bits with dotnet build right? So they should be isolated from the VS version?

Yup but with emphasis on the word "should".

My deeper suspicion is this problem will primarily impact local builds of the 'release/5.0' branch after switching from 'master' (or branches based on either). That comes from `dotnet build-server shutdown` clearing the problem. Seems likely the problem is just that builds in 'release/5.0' end up using the newer Roslyn bits configured in 'master' because they're held in the VB/C# compiler server.

Note our `build.ps1` and `build.sh` scripts disable node reuse. Unfortunately that affects `dotnet msbuild` processes, not the server process(es) used.

We enable the compiler server pretty much everywhere (in eng/Workarounds.props). That's identified as a workaround for dotnet/roslyn#27975 though it's probably more about the 5X performance degradation when _not_ using the compiler server.

**Comment by Pilchie** [comment]
Got it, thanks for working through the details with me.  I'm okay with Tell-Mode for this now.

**Pull request merged**
