### PR TITLE
[Blazor] Move blazor only functions to Boot.WebAssembly.ts

### PR DESCRIPTION
**Pull request by javiercn**
* Moves some functions that are only used for WASM into Boot.WebAssembly.ts
* We technically don't need the functionality at all in WASM either, as we should be using SWA, but leaving it there for now so as not not disrupt Blazor client-side unnecessarily.

### CODE REVIEW

**Review by SteveSandersonMS — APPROVED** [review]
Cool!

**Comment by pranavkm** [comment]
@javiercn do we need this?

**Comment by javiercn** [comment]
It saves some bits.

**Comment by SteveSandersonMS** [comment]
I agree this is good to do and approved the PR. @javiercn is this something you think can still be merged?

**Comment by javiercn** [comment]
Yes, I've just been busy with other stuff. I'll get it merged.

**Review by ryanbrandenburg — APPROVED** [review]

**Comment by Pilchie** [comment]
Approved for 3.1.0-preview3.

**Pull request merged**
