### PR TITLE
[release/8.0] Convert to 1ES templates

### PR DESCRIPTION
**Pull request by RussKie**
Part of https://github.com/dotnet/aspnetcore-internal/issues/4468

### CODE REVIEW

**Comment by RussKie** [comment]
NB: this is currently based on top of https://github.com/dotnet/aspnetcore/pull/54654.

**Comment by wtgodbe** [comment]
Test internal build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2410945&view=results

**Comment by wtgodbe** [comment]
Failures from the above build were Component Governance. New build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2411001&view=results

**Comment by wtgodbe** [comment]
Good to go

**Comment by radical** [comment]
Test failures will be quarantined by https://github.com/dotnet/aspnetcore/pull/54758 .

**Pull request merged**
