### PR TITLE
Support int in InputSelect.cs

### PR DESCRIPTION
**Pull request by Julien-Marpault**
Add support to int type for inputSelect

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
Thanks for your PR, @JulienM28.
Looks like there are some build breaks as well as this change is missing some tests. We will need all that to move forward with this PR.

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS can you please review this when the PR is updated with all the necessary bits? Thanks!

**Comment by JulienM28** [comment]
Ok, I'm not familiar wit hthe process it's my first.

I Will correct it soon.

Thanks.

**Comment by mkArtakMSFT** [comment]
Thanks for your PR.
We're currently busy wrapping up our upcoming Blazor WASM release, which is planned to go out in May. That forces us to delay some community PR reviews which target ASP.NET Core 5.0, so please expect some delays here. We will get to this as soon as we wrap up the Blazor work.

**Comment by MackinnonBuck** [comment]
Thank you for your submission. This has been solved by #23415.

**Comment by mrlife** [comment]
@MackinnonBuck Is this a 5.0 only release?

**Pull request closed without merging**
