### PR TITLE
PR feedback

### PR DESCRIPTION
**Pull request by davidfowl**
- Rename WebApplicationOptions to WebApplicationBuilderOptions

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]
And PublicAPI?
https://github.com/dotnet/aspnetcore/blob/cf0be8054dcd3c494f7a3d295b8b377b45b0d27e/src/DefaultBuilder/src/PublicAPI.Unshipped.txt#L37

**Comment by davidfowl** [comment]
Ugh,,

**Comment by davidfowl** [comment]
@dotnet/aspnet-api-review @halter73 is not a fan of the options rename. I'm gonna close this until we resolve that on the issue.

**Comment by halter73** [comment]
Sorry @dotnet/aspnet-api-review! I wasn't there for that part of the meeting. I think these options also could make sense for `WebApplicationBuilder.Create(WebApplicationOptions)`. It may be considered too advanced to be worth the overload, but it does configure the WebApplication. Furthermore, this is an options type you have to new up. Even with target-typed news being a thing, I don't like the longer type name.

**Pull request closed without merging**
