### PR TITLE
Make ComponentBase.StateHasChanged public

### PR DESCRIPTION
**Pull request by SimonCropp**
So when people are testing they can avoid this https://github.com/VerifyTests/Verify.Blazor/blob/master/src/Verify.Blazor/VerifyBlazor.cs#L13

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
Thanks for suggesting this. Unfortunately this change would break the ability for component authors to control when their component renders, since arbitrary other code could trigger it at any time. As that would be a breaking change and inconsistent with the design goals, we won’t be able to make this change. 

Hope that makes sense and sounds reasonable!

**Comment by SimonCropp** [comment]
@SteveSandersonMS it is reasonable. but it reinforces what i stated here https://github.com/dotnet/aspnetcore/issues/5458#issuecomment-629528663

**Comment by SimonCropp** [comment]
how about this. for testing purposes i want to be able to snapshot the current html state of a component. 

effectively this

```
  public static string RenderComponent<T>(
            ServiceProvider? provider = null,
            ILoggerFactory? loggerFactory = null,
            ParameterView? parameterView = null,
            Action<T>? beforeRender = null)
            where T : ComponentBase
```

At the moment i need to use reflection and maintain a duplicate of https://github.com/egil/bUnit/blob/main/src/bunit.web/Rendering/Internal/Htmlizer.cs

this is common functionality that anyone testing blazor would find useful. how can this be done without requiring every person to reverse engineer the internals of blazor and then need reflection and duplicate code

**Comment by SteveSandersonMS** [comment]
Perhaps bUnit would be interested in factoring out their Htmlizer class into a separate reusable package.

**Comment by SimonCropp** [comment]
Sounds good. But given that code comes from here https://source.dot.net/#Microsoft.AspNetCore.Mvc.ViewFeatures/RazorComponents/HtmlRenderer.cs does the same logic apply?

**Comment by SteveSandersonMS** [comment]
Yes, whoever wants to maintain/support a package containing such functionality is welcome to do so - the license is designed for this. If you want to do so, please go ahead. If the bUnit project wants to do so that’s great too.

**Comment by SimonCropp** [comment]
i dont want to do this because it requires making assumptions on the internal workings of blazor via reflection, and duplicate a large portion of code that needs to be kept manually in sync. IMO it seems this functionality should belong in this repository.

**Comment by egil** [comment]
@SimonCropp can you explain why you need refection in this scenario? I do not remember needing that for bUnit.

As for extracting Htmlizer out, that's not something I want to get into at the moment. Some of the planned changes for bUnit will make quite a few changes to it that will be specific to bUnit and probably not general usable.

**Pull request closed without merging**
