### PR TITLE
Backport Use CDN for .NET Assets for release/5.0

### PR DESCRIPTION
**Pull request by TanayParikh**
https://github.com/dotnet/aspnetcore/pull/39007

### CODE REVIEW

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
@MattGal does the CDN update also not apply for release/5.0❔

``` text
Problems downloading file from 'https://dotnetbuilds.azureedge.net/public/Runtime/5.0.12-servicing.21522.7/dotnet-runtime-5.0.12-linux-arm.tar.gz'. Does the resource exist on the storage? NotFound
```

**Comment by MattGal** [comment]
> @MattGal does the CDN update also not apply for release/5.0❔
> 
> ```
> Problems downloading file from 'https://dotnetbuilds.azureedge.net/public/Runtime/5.0.12-servicing.21522.7/dotnet-runtime-5.0.12-linux-arm.tar.gz'. Does the resource exist on the storage? NotFound
> ```

As noted on the other one, the change isn't present for publishing before 6.x, but you can still switch to azureedge.net for dotnetcli and get the same benefit from the other CDN.

**Comment by TanayParikh** [comment]
Not working with `dotnetcli.azureedge.net` either, leaving as is.

**Comment by TanayParikh** [comment]
@dotnet/aspnet-build requesting merge please.

**Pull request merged**
