### PR TITLE
Set new HTTPS environment variable when using out of process

### PR DESCRIPTION
**Pull request by jkotalik**
Same as https://github.com/aspnet/AspNetCore/pull/16713 except targeting 3.0

@Pilchie can we target this for 3.0.1?

### CODE REVIEW

**Comment by jkotalik** [comment]
@aspnet/build in 3.0 now, do I need to update the patch.config file if the component is in the targeting pack?

**Comment by mmitche** [comment]
@wtgodbe @JunTaoLuo For the patch config question

**Comment by wtgodbe** [comment]
> in 3.0 now, do I need to update the patch.config file if the component is in the targeting pack?

In general, yes. This time around we're explicitly building the targeting pack, but I'm not 100% sure if we also need to turn on the build of this individual component. @JunTaoLuo might have a more concrete answer on that.

**Review by Tratcher — APPROVED** [review]

**Comment by wtgodbe** [comment]
Just chatted with @dougbu & @JunTaoLuo - you should add the affected project(s) to patchConfig.props

**Comment by anurse** [comment]
This was approved over email, FYI. Updating labels. Please confirm with @aspnet/build that the branch is clear to merge in to.

**Comment by mmitche** [comment]
> This was approved over email, FYI. Updating labels. Please confirm with @aspnet/build that the branch is clear to merge in to.

Clear to merge.

**Comment by jkotalik** [comment]
@Pilchie / @aspnet/build please merge (I not authorized to).

**Pull request merged**
