### PR TITLE
[Diagnostics] Fix errors on the developer console for the Entity Framework Database Middleware

### PR DESCRIPTION
**Pull request by javiercn**
Removes the content-length and connection headers as they shouldn't be setup by the AJAX request

### CODE REVIEW

**Comment by ajcvickers** [comment]
@natemcmaster @javiercn Okay, I assume this is the real PR. :-)

**Comment by javiercn** [comment]
@ajcvickers Yes. The other one was in diagnostics which got moved here.

**Review by ajcvickers — APPROVED** [review]

**Comment by ajcvickers** [comment]
#### Description

As part of the first-time experience ASP.NET Core apps will show a "database error page" if the application is run without first creating the database. This page has a button to create the database, which does what it says, but then shows an error leading first-time users to believe that things are really broken.
		
#### Customer Impact

Impacts the first-time experience for people trying ASP.NET Core with EF Core.

#### Regression?

Yes, from 2.1.

#### Risk

Very low--fix is isolated to removing two lines that were setting inappropriate headers. This page is also only enabled in the "Developer" environment--it's not used for "Production".

**Comment by vivmishra** [comment]
Approved for 2.2.1
Confirm if the 3rd error is also removed.

**Review by natemcmaster — CHANGES_REQUESTED** [review]
A few minor infrastructure changes are also required:

1. Retarget the PR to release/2.2
2. Add the package to this list: https://github.com/aspnet/AspNetCore/blob/release/2.2/eng/PatchConfig.props

**Comment by ajcvickers** [comment]
@javiercn Question from @DamianEdwards in shiproom: is the third error shown in the repro *(The HTTP 1.1 error) also fixed by this PR?
image

**Comment by javiercn** [comment]
@ajcvickers I didn't see that error in my repro and the changes fix the other two.

**Comment by ajcvickers** [comment]
@javiercn Thanks.

@DamianEdwards Since @javiercn can't repro the third error and we know the PR as it is fixes some known errors, I suggest we merge this and then re-test end-to-end after it gets in a patch build. If that still results in errors then we create a second fix, which may or may not be in time for the first patch, but can at least go in the second.

**Review by natemcmaster — APPROVED** [review]

**Comment by Eilon** [comment]
I'd like to have @javiercn (or someone) try to repro the 3rd error ASAP, though I'm OK with checking in what we have for now.

**Comment by javiercn** [comment]
@Eilon I've already sent an email on friday about this. I believe the 3rd error is unrelated and due to a change in how VS launches EF under IIS Express. I'll add you to the thread.

**Comment by javiercn** [comment]
As per Damian, while these changes don't fix the third issue (which was already identified) he also wants this to be patched, so merging.

**Pull request merged**
