### PR TITLE
Quarantine ClosesAfterDataSent

### PR DESCRIPTION
**Pull request by BrennanConroy**
https://github.com/dotnet/aspnetcore/issues/31404

### CODE REVIEW

**Comment by halter73** [comment]
The exception from the issue looks pretty worthless:

```
Assert.DoesNotContain() Failure
Found:    (filter expression)
In value: ConcurrentQueue<WriteContext> [...
```

Can we update `StrictTestServerTests.Dispose()` to show the higher-than-information log(s)?

**Comment by BrennanConroy** [comment]
Put that comment on the issue 😄 
Or file a new issue to improve the IIS tests.

**Review by jkotalik — APPROVED** [review]

**Comment by halter73** [comment]
> Put that comment on the issue 😄

I'll do it myself if you don't before merging this.

**Review by halter73 — APPROVED** [review]

**Comment by halter73** [comment]
I thought I already approved this before making my earlier comment.

**Comment by halter73** [comment]
Don't worry about `StrictTestServerTests` @BrennanConroy. There's a bunch of tests like it, so I'm working on a change now that fixes them all.

**Pull request merged**
