### PR TITLE
Change how we resolve dotnet in tests (#16934)

### PR DESCRIPTION
**Pull request by BrennanConroy**
Cherry-pick https://github.com/aspnet/AspNetCore/pull/16934 from release/3.0

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
Please hold off 'til preview3 is out

**Comment by wtgodbe** [comment]
@wtgodbe merge this one first for GA

**Review by wtgodbe — APPROVED** [review]

**Comment by BrennanConroy** [comment]
> @wtgodbe merge this one first for GA

Are you going to take care of the merge then?

**Comment by wtgodbe** [comment]
> Are you going to take care of the merge then?

Yezzir, I'll merge this with the rest of the batch Monday morning

**Comment by anurse** [comment]
Fixes https://github.com/aspnet/AspNetCore/issues/16912 ?

**Comment by BrennanConroy** [comment]
> Fixes #16912 ?

Yes, but I don't want to put that in the summary until we un-skip the tests on master

**Pull request merged**
