### PR TITLE
Merging internal commits for release/7.0

### PR DESCRIPTION
**Pull request by vseanreesermsft**

### CODE REVIEW

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
/fyi @vseanreesermsft something went wrong w/ your merge commit. I had to redo the merge to clear corruption in ci.yml

**Comment by dougbu** [comment]
@mmitche is there documentation on the `DownloadFile` task somewhere❔ I don't know how to fill the described gap.
``` text
src\Framework\App.Runtime\src\Microsoft.AspNetCore.App.Runtime.csproj(514,5): error MSB4096: (NETCORE_ENGINEERING_TELEMETRY=Build) The item "https://dotnetcli.azureedge.net/dotnet/Runtime/7.0.0-rtm.22518.5/dotnet-runtime-7.0.0-win-arm.zip" in item list "UrisToDownload" does not define a value for metadata "DotNetRuntimeArchive".  In order to use this metadata, either qualify it by specifying %(UrisToDownload.DotNetRuntimeArchive), or ensure that all items in this list define a value for this metadata
```

**Comment by dougbu** [comment]
Thanks @mmitche I was just about to push exactly the same `!fixup!` commit 😁

**Comment by mmitche** [comment]
We've been seeing this AbandonedMutexException quite a bit in the aspnet PRs. It smells bad to me. @zivkan does this look familiar to you at all? This PR includes an upgrade to the RTM build of .NET

```
  Determining projects to restore...
/mnt/vss/_work/1/s/.dotnet/sdk/7.0.100/NuGet.targets(132,5): error MSB4018: The "RestoreTask" task failed unexpectedly. [/tmp/0a9fc532-050c-4a94-87ad-363e4687f8ce/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Tools.proj]
##[error].dotnet/sdk/7.0.100/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) The "RestoreTask" task failed unexpectedly. [/tmp/0a9fc532-050c-4a94-87ad-363e4687f8ce/restore.csproj]
/mnt/vss/_work/1/s/.dotnet/sdk/7.0.100/NuGet.targets(132,5): error MSB4018: System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex. [/tmp/0a9fc532-050c-4a94-87ad-363e4687f8ce/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Tools.proj]
##[error].dotnet/sdk/7.0.100/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex. [/tmp/0a9fc532-050c-4a94-87ad-363e4687f8ce/restore.csproj]
/mnt/vss/_work/1/s/.dotnet/sdk/7.0.100/NuGet.targets(132,5): error MSB4018: at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout) [/tmp/0a9fc532-050c-4a94-87ad-363e4687f8ce/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Tools.proj]
##[error].dotnet/sdk/7.0.100/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout) [/tmp/0a9fc532-050c-4a94-87ad-363e4687f8ce/restore.csproj]
/mnt/vss/_work/1/s/.dotnet/sdk/7.0.100/NuGet.targets(132,5): error MSB4018: at NuGet.Common.Migrations.MigrationRunner.Run() [/tmp/0a9fc532-050c-4a94-87ad-363e4687f8ce/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Tools.proj]
##[error].dotnet/sdk/7.0.100/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) at NuGet.Common.Migrations.MigrationRunner.Run() [/tmp/0a9fc532-050c-4a94-87ad-363e4687f8ce/restore.csproj]
/mnt/vss/_work/1/s/.dotnet/sdk/7.0.100/NuGet.targets(132,5): error MSB4018: at NuGet.Build.Tasks.RestoreTask.Execute() [/tmp/0a9fc532-050c-4a94-87ad-363e4687f8ce/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Tools.proj]
##[error].dotnet/sdk/7.0.100/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) at NuGet.Build.Tasks.RestoreTask.Execute() [/tmp/0a9fc532-050c-4a94-87ad-363e4687f8ce/restore.csproj]
/mnt/vss/_work/1/s/.dotnet/sdk/7.0.100/NuGet.targets(132,5): error MSB4018: at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/tmp/0a9fc532-050c-4a94-87ad-363e4687f8ce/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Tools.proj]
##[error].dotnet/sdk/7.0.100/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/tmp/0a9fc532-050c-4a94-87ad-363e4687f8ce/restore.csproj]
/mnt/vss/_work/1/s/.dotnet/sdk/7.0.100/NuGet.targets(132,5): error MSB4018: at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/tmp/0a9fc532-050c-4a94-87ad-363e4687f8ce/restore.csproj] [/mnt/vss/_work/1/s/.packages/microsoft.dotnet.arcade.sdk/7.0.0-beta.22513.4/tools/Tools.proj]
##[error].dotnet/sdk/7.0.100/NuGet.targets(132,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Restore) at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/tmp/0a9fc532-050c-4a94-87ad-363e4687f8ce/restore.csproj]
```

**Comment by wtgodbe** [comment]
@mmitche https://github.com/dotnet/aspnetcore/pull/45001, https://github.com/dotnet/aspnetcore/pull/44741

**Comment by mmitche** [comment]
WOOHOO!

**Comment by zivkan** [comment]
NuGet has a fix for the abandoned mutex exception: https://github.com/NuGet/Home/issues/12159
We're in the process of trying to service all the supported versions.

**Pull request merged**
