### PR TITLE
Merge branch 'release/2.2' -> 'master'

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Comment by dougbu** [comment]
@pranavkm please double-check how 836964a653e3 merged

@BrennanConroy Microsoft.AspNetCore.AzureAppServicesIntegration.csproj and Microsoft.AspNetCore.AzureAppServicesIntegration.csproj are in different places in 'master'.  Let me know if I should apply your `<UseProjectReferences>true</UseProjectReferences>` and `<UseLatestPackageReferences>true</UseLatestPackageReferences>` additions to the projects in their new locations as part of this merge. See d93b207485f6

**Review by BrennanConroy — APPROVED** [review]
Looks good from my side.

**Comment by dougbu** [comment]
@pranavkm just waiting for your check

**Comment by dougbu** [comment]
Added area-mvc label too: This merge brings the logging fix into 'master'.

**Review by pranavkm — APPROVED** [review]

**Pull request merged**
