### PR TITLE
Update to Alpine 3.16

### PR DESCRIPTION
**Pull request by wtgodbe**
Part of https://github.com/dotnet/aspnetcore/issues/46555

### CODE REVIEW

**Comment by wtgodbe** [comment]
Helix-matrix run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=166496&view=results

**Comment by wtgodbe** [comment]
Lots of test failures here, tagging individual owners

**Comment by wtgodbe** [comment]
Lots of ModelBinding failures, e.g. `Microsoft.AspNetCore.Mvc.ModelBinding.Binders.DecimalModelBinderTest.BindModel_ReturnsModel_IfAttemptedValueIsValid_FrenchTwelvePointFive(destinationType: typeof(decimal))`

> Assert.Equal() Failure
Expected: 12.5
Actual:   125

@brunolins16 could you take a [look](https://dev.azure.com/dnceng-public/public/_build/results?buildId=166496&view=ms.vss-test-web.build-test-results-tab&runId=3375719&resultId=117185&paneView=debug)?

**Comment by wtgodbe** [comment]
`Microsoft.AspNetCore.Html.Test.HtmlContentBuilderExtensionsTest.Builder_AppendFormat_WithDifferentCulture`

> Assert.Equal() Failure
↓ (pos 13)
Expected: HtmlEncode[[1,21]] in french!
Actual:   HtmlEncode[[1.21]] in french!
↑ (pos 13)

Not sure who owns this one - @JamesNK? [link](https://dev.azure.com/dnceng-public/public/_build/results?buildId=166496&view=ms.vss-test-web.build-test-results-tab&runId=3375719&resultId=105295&paneView=debug)

**Comment by wtgodbe** [comment]
> 2023-02-10T00:06:42.6138111Z   Failed Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatterTest.ReadAsync_WithReadJsonWithRequestCulture_DeserializesUsingRequestCulture(dateString: "15/05/2019", culture: "fr-FR") [66 ms]
2023-02-10T00:06:42.6138991Z   Error Message:
2023-02-10T00:06:42.6139493Z    Assert.False() Failure
2023-02-10T00:06:42.6139992Z Expected: False
2023-02-10T00:06:42.6140512Z Actual:   True
2023-02-10T00:06:42.6141094Z   Stack Trace:
2023-02-10T00:06:42.6141681Z      at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatterTest.ReadAsync_WithReadJsonWithRequestCulture_DeserializesUsingRequestCulture(String dateString, String culture) in /_/src/Mvc/Mvc.NewtonsoftJson/test/NewtonsoftJsonInputFormatterTest.cs:line 514

@JamesNK I guess this is you as well - [logs](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-pull-46563-merge-70d4e0045c7d4559be/Microsoft.AspNetCore.Mvc.NewtonsoftJson.Test--net8.0/1/console.66e5f538.log?helixlogtype=result)

**Comment by wtgodbe** [comment]
The failures may be related to an issue with the docker image - https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/798

**Comment by brunolins16** [comment]
> The failures may be related to an issue with the docker image - [dotnet/dotnet-buildtools-prereqs-docker#798](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/798)

IDK much about but I took a look at the ModelBinding issues and all of them are related to scenarios where we are testing formatting with different cultures and definitely could be related to this.

**Comment by wtgodbe** [comment]
I believe https://dev.azure.com/dnceng-public/public/_build/results?buildId=169872&view=results will use the updated 3.16 image

**Comment by brunolins16** [comment]
> I believe https://dev.azure.com/dnceng-public/public/_build/results?buildId=169872&view=results will use the updated 3.16 image

If it is using 3.16, I believe the change did not fix the issue :(.

**Comment by brunolins16** [comment]
@wtgodbe we were using 3.14 before, right? 

Do you know which customizations we have in `mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-local`? I am asking because the 3.16 base image is a plain `alpine:3.16`

**Comment by wtgodbe** [comment]
I might have read the docker repo wrong, going to try the staging image (I think it hasn't been rolled out yet)

**Comment by wtgodbe** [comment]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=170242&view=results

**Comment by wtgodbe** [comment]
Ok, that worked. @mthalman what day does the weekly docker image rollout happen?

**Comment by mthalman** [comment]
Wednesday or Thursday
cc @riarenas

**Comment by wtgodbe** [comment]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=174852&view=results

**Comment by wtgodbe** [comment]
@dougbu can you review

**Review by dougbu — APPROVED** [review]

**Pull request merged**
