### PR TITLE
Updated build.sh

### PR DESCRIPTION
**Pull request by ShreyasJejurkar**
Corrected explanation of option parameter.

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
Nice catch @ShreyasJejurkar❕

**Comment by ShreyasJejurkar** [comment]
@dougbu haha. Just found this, while I was trying to build aspnetcore repo on codespaces. 
Checking building on codespaces works or not!

**Comment by ShreyasJejurkar** [comment]
Can we stop CI build forcefully, as these changes are outside of code and do not affect anything much!
So that we can save our resources a little bit!!

**Comment by dougbu** [comment]
> Can we stop CI build forcefully, as these changes are outside of code and do not affect anything much!
So that we can save our resources a little bit!!

Might be nice but causes problems w/ our branch protection rules. Admin overrides (which I could have used) are slightly safer and doc-only changes in this repo are uncommon&hellip;

One build when nobody's in a rush isn't a big deal😀

**Comment by ShreyasJejurkar** [comment]
In some repos, I have seen filters for directories and files, so if there are changes in those particular files, CI won't run for those!

**Comment by dougbu** [comment]
> In some repos, I have seen filters for directories and files, so if there are changes in those particular files, CI won't run for those!

Yup. We tried that out then reverted it due to the branch protection rules we have in place and how that interacted w/ the YAML exclusions.

**Comment by ShreyasJejurkar** [comment]
Ohh ok ok. Thanks for the clarification. 😀@dougbu

**Pull request merged**
