### PR TITLE
Revert "Improve components infrastructure (#12145)"

### PR DESCRIPTION
**Pull request by JunTaoLuo**
WIP but may be taking this improvement out of preview 8 since it will regress source build.

The problem is that while the environment for source build has NodeJS and Yarn that is required to build Web.JS, it will be missing Javascript dependencies. I missed this since the source build test configuration passed but it's not mimicking the actual environment since it still has access to the network to install packages (and also downloads from packages from myget).

There are several possible approaches to resolve this though none of them seems feasible at the moment:
1. Check in node_modules. From what I can tell this is probably a non-starter. We'll be checking in way too many files and it's probably against our policy to check in source files from JS packages not written by us.
2. Use only dependencies from native package repositories. It might be possible to reduce our dependencies to only the js packages available on the distro package repositories such as https://packages.debian.org/stable/javascript/. I'll need to see how viable this approach may be.

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
@rynowak @SteveSandersonMS can someone help me test this?

**Comment by JunTaoLuo** [comment]
cc @javiercn @pranavkm as well in case you can help verify the correctness of the generated js content.

**Comment by javiercn** [comment]
@JunTaoLuo I would suggest you do the following:
* `pushd src\signalr\clients\ts; yarn install; yarn build; popd`
* `pushd src\components\web.js; yarn install; yarn build; popd`
* See if blazor.server.js changed on disk.
* Open the components solution.
* Run all the tests in VS or in the command line.

**Comment by JunTaoLuo** [comment]
Tests passed locally.

**Review by javiercn — APPROVED** [review]

**Pull request merged**
