### PR TITLE
Fix non-shared framework packages referencing transport package

### PR DESCRIPTION
**Pull request by BrennanConroy**
Fixes https://github.com/dotnet/aspnetcore/issues/43726

### CODE REVIEW

**Review by brunolins16 — APPROVED** [review]

**Comment by wtgodbe** [comment]
I also updated this so that the auto-reference to `Microsoft.Internal.Runtime.AspNetCore.Transport` is only added to SharedFx projects. This should prevent us from hitting this problem again going forward

**Comment by BrennanConroy** [comment]
@Pilchie for RC2. This fixes an issue where the user-jwt isn't usable. Sadly, RC1 will be broken, but we've root caused the issue and also fixed the root cause.

**Comment by Pilchie** [comment]
Approved for .NET 7 RC2

**Comment by BrennanConroy** [comment]
@wtgodbe Security/Negotiate and ApiAuthorization.IdentityServer were failing locally. The grpc transcoding one didn't fail locally for me, but I guessed at the reason it failed. See latest commit.

**Pull request merged**
