### PR TITLE
Resolve file logging path conflict between flaky and non flaky test runs

### PR DESCRIPTION
**Pull request by JunTaoLuo**
Addressing parts of https://github.com/aspnet/AspNetCore/issues/17243

### CODE REVIEW

**Comment by BrennanConroy** [comment]
We need this for extensions too? (and other repos?)

**Comment by BrennanConroy** [comment]
Don't think it worked

**Comment by JunTaoLuo** [comment]
Ah I see, this won't work since we don't rebuild when running the flaky tests. This will need a change in LoggedTest then.

**Comment by JunTaoLuo** [comment]
This approach is not going to work.

**Pull request closed without merging**
