### PR TITLE
Remove internal archives

### PR DESCRIPTION
**Pull request by mmitche**
Remove the -internal archives. https://github.com/dotnet/aspnetcore/issues/27686

### CODE REVIEW

**Comment by wtgodbe** [comment]
Changes look reasonable, but can you run an internal build of this branch so we can compare the outputs?

**Comment by mmitche** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=2238447&view=results

**Comment by wtgodbe** [comment]
Looks like it's still publishing the aspnetcore-runtime-internal .wixlib's

**Comment by mmitche** [comment]
> Looks like it's still publishing the aspnetcore-runtime-internal .wixlib's

https://github.com/dotnet/installer/blob/a884cf6e8c5f8c2aaa4ece91ca10fb6d380fb5b2/src/redist/targets/GenerateLayout.targets#L300-L304

That does appear to be used when generating the installer MSIs. I think it's also used in generating aspnetcore's installers, so I decided to leave it.

**Review by wtgodbe — APPROVED** [review]

**Comment by mmitche** [comment]
Artifact diff looks good

**Pull request merged**
