### PR TITLE
Switch to constants in IdentityConstants.

### LINKED ISSUE #20122: IdentityConstants aren't Constants
### Describe the bug
The Authentication Scheme strings in IdentityConstants aren't constant so they can't be used to differentiate the schemes in controllers. 

### To Reproduce
Find the example in the repo:

https://github.com/shawnwildermuth/ReproIdentityConstants

Essentially, try and add more than one Identity Provider (I used Jwt + Identity). But when I use the authorize attribute to specify the JwtBearer it's fine:

``` C#
  [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
  [Route("api/[controller]")]
  public class FooController : ControllerBase
  {
    public IActionResult Get()
    {
      return Ok(new { name = "Hello" });
    }
  }
```

But when I try to do the same with the IdentityConstants:

``` C#
  [Authorize(AuthenticationSchemes = IdentityConstants.ApplicationScheme)]
  public class HomeController : Controller
  {
    private readonly ILogger<HomeController> _logger;

```

Can't compile as The ApplicationScheme constant needs to be a constant (not just readonly static).

### Further technical details
- ASP.NET Core version
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version:

Visual Studio 16.5.0 (though it happens with just dotnet build so it's likely not related)

### PR DESCRIPTION
**Pull request by HaoK**
Fixes https://github.com/dotnet/aspnetcore/issues/20122

### CODE REVIEW

**Comment by kevinchalet** [comment]
Isn't that a (big) binary breaking change? 😮

**Comment by HaoK** [comment]
Yeah I'd imagine its a binary break, but this is for 5.0...  That said I don't think this is particularly that important, although being able to reference the values as constants in Authorize is nice.  @ajcvickers thoughts?

**Comment by ajcvickers** [comment]
@HaoK We shouldn't break this in 5.0 unless we are sure the ecosystem can handle it. In particular, breaking Identity Server is bad.

**Comment by HaoK** [comment]
Fair enough closing this and the issue

**Comment by dazinator** [comment]
Please can this be re-considered?

Having to do the following is not nice, as it makes having IdentityConstants pointless:

```
[Authorize(AuthenticationSchemes ="Identity.Application")]

```

It's also inconsistent with other schemes such as JwtBearer which does give you a proper constant.

**Comment by dazinator** [comment]
There is probably a way to do this without a breaking change - just add a new constant, and then set the existing static field from that constant.

**Comment by dazinator** [comment]
e.g

```csharp
    public partial class IdentityConstants
    {
        // Preserve for backwards compat.
        public static readonly string ApplicationScheme = ApplicationSchemeName;
        public static readonly string ExternalScheme = ExternalSchemeName;
        public static readonly string TwoFactorRememberMeScheme = TwoFactorRememberMeSchemeName;
        public static readonly string TwoFactorUserIdScheme = TwoFactorUserIdSchemeName;

        public const string ApplicationSchemeName = "Identity.Application";
        public const string ExternalSchemeName = "Identity.External";
        public const string TwoFactorRememberMeSchemeName = "Identity.TwoFactorRememberMe";
        public const string TwoFactorUserIdSchemeName = "Identity.TwoFactorUserId";
        public IdentityConstants() { }
    }


```

**Comment by springy76** [comment]
ok its 2023 (quasi) and we are on net 7.0.1 - still no constants

**Comment by springy76** [comment]
Hi @msftbot - having no expectiations the risk of (further) disappointments is low.

**Pull request closed without merging**
