### PR TITLE
gRPC JSON transcoding + Microsoft.AspNetCore.OpenApi

### PR DESCRIPTION
**Pull request by JamesNK**
Work in progress.

Note: I needed to make some changes to the `IApiDescriptionProvider`. `Microsoft.AspNetCore.OpenApi` uses `ApiParameterDescription.Type` in places that Swashbuckle used `ApiParameterDescription.ModelMetadata.ModelType`. I don't know if that change was intentional.

### CODE REVIEW

**Comment by JamesNK** [comment]
Example of Swashbuckle output:

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "My API",
    "version": "v1"
  },
  "paths": {
    "/v1/greeter/{name}": {
      "get": {
        "tags": [
          "Greeter"
        ],
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HelloReply"
                }
              }
            }
          },
          "default": {
            "description": "Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Status"
                }
              }
            }
          }
        }
      }
    },
    "/v1/greeter": {
      "post": {
        "tags": [
          "Greeter"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/HelloRequestFrom"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HelloReply"
                }
              }
            }
          },
          "default": {
            "description": "Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Status"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Any": {
        "required": [
          "@type"
        ],
        "type": "object",
        "properties": {
          "@type": {
            "type": "string"
          }
        },
        "additionalProperties": {
          "$ref": "#/components/schemas/Value"
        }
      },
      "HelloReply": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "nested": {
            "$ref": "#/components/schemas/HelloReply"
          }
        },
        "additionalProperties": false
      },
      "HelloRequestFrom": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "from": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "KindOneofCase": {
        "enum": [
          0,
          1,
          2,
          3,
          4,
          5,
          6
        ],
        "type": "integer",
        "format": "int32"
      },
      "ListValue": {
        "type": "object",
        "properties": {
          "values": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Value"
            },
            "nullable": true,
            "readOnly": true
          }
        },
        "additionalProperties": false
      },
      "NullValue": {
        "enum": [
          0
        ],
        "type": "integer",
        "format": "int32"
      },
      "Status": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "format": "int32"
          },
          "message": {
            "type": "string"
          },
          "details": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Any"
            }
          }
        },
        "additionalProperties": false
      },
      "Struct": {
        "type": "object",
        "properties": {
          "fields": {
            "type": "object",
            "additionalProperties": {
              "$ref": "#/components/schemas/Value"
            },
            "nullable": true,
            "readOnly": true
          }
        },
        "additionalProperties": false
      },
      "Value": {
        "type": "object",
        "properties": {
          "nullValue": {
            "$ref": "#/components/schemas/NullValue"
          },
          "hasNullValue": {
            "type": "boolean",
            "readOnly": true
          },
          "numberValue": {
            "type": "number",
            "format": "double"
          },
          "hasNumberValue": {
            "type": "boolean",
            "readOnly": true
          },
          "stringValue": {
            "type": "string",
            "nullable": true
          },
          "hasStringValue": {
            "type": "boolean",
            "readOnly": true
          },
          "boolValue": {
            "type": "boolean"
          },
          "hasBoolValue": {
            "type": "boolean",
            "readOnly": true
          },
          "structValue": {
            "$ref": "#/components/schemas/Struct"
          },
          "listValue": {
            "$ref": "#/components/schemas/ListValue"
          },
          "kindCase": {
            "$ref": "#/components/schemas/KindOneofCase"
          }
        },
        "additionalProperties": false
      }
    }
  }
}
```

**Comment by JamesNK** [comment]
Example of current Microsoft.AspNetCore.OpenApi:

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "Sandbox | v1",
    "version": "1.0.0"
  },
  "paths": {
    "/v1/greeter/{name}": {
      "get": {
        "tags": [
          "Greeter"
        ],
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": { }
              }
            }
          },
          "default": {
            "description": "",
            "content": {
              "application/json": {
                "schema": { }
              }
            }
          }
        }
      }
    },
    "/v1/greeter": {
      "post": {
        "tags": [
          "Greeter"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "from": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": { }
              }
            }
          },
          "default": {
            "description": "",
            "content": {
              "application/json": {
                "schema": { }
              }
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Greeter"
    }
  ]
}
```

**Comment by JamesNK** [comment]
New new json:

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "Sandbox | v1",
    "version": "1.0.0"
  },
  "paths": {
    "/v1/greeter/{name}": {
      "get": {
        "tags": [
          "Greeter"
        ],
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "nested": { }
                  }
                }
              }
            }
          },
          "default": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "format": "int32"
                    },
                    "message": {
                      "type": "string"
                    },
                    "details": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "typeUrl": {
                            "type": "string"
                          },
                          "value": {
                            "type": "array",
                            "items": {
                              "type": "string",
                              "format": "byte"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v1/greeter": {
      "post": {
        "tags": [
          "Greeter"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "from": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "nested": { }
                  }
                }
              }
            }
          },
          "default": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "format": "int32"
                    },
                    "message": {
                      "type": "string"
                    },
                    "details": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "typeUrl": {
                            "type": "string"
                          },
                          "value": {
                            "type": "array",
                            "items": {
                              "type": "string",
                              "format": "byte"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Greeter"
    }
  ]
}
```

**Comment by JamesNK** [comment]
I rebased to latest and looked at this more.

---

`JsonSchemaExporter.GetJsonSchemaAsNode` uses the type resolver. The OpenAPI integration loads it from `JsonOptions`. I updated transcoding to also set the custom type resolver onto `JsonOptions`. However, when I did this there was a regression in schema generation.

The nested property now references something that doesn't exist. I don't know why it does this.
```
          "nested": {
            "$ref": "#/components/schemas/#/properties/nested"
          }
```

---

Also, there are duplicated definitions in the references. e.g. `HelloReply1`, `HelloReply2`, `HelloReply3`, etc. I'm guessing there is something wrong with the schema comparer that causes them not to be equal.

Every time I refresh, the reference number increases. For example, ``HelloReply` starts at `HelloReply1` and quickly increases to `HelloReply12` after a few refreshes. I don't think you should cache schema references between document generations. For example, imagine there are two OpenApi docs and each have their own class called `Version`: `System.Version` and `Consoto.Version`. Each be referenced as `Version` but the number added to the reference them will depend on the order the docs are generated. IMO the documents should be independent of each other.

---

I noticed arrays are a referenced type, e.g. `ArrayOfAny`. I don't think you should try to store references to arrays. They're almost always very simple as the items are either a primitive type or a reference. e.g.

```json
{
    "type": "array",
    "items": {
        "$ref": "#/components/schemas/Value"
    },
    "nullable": true,
    "readOnly": true
}
```

If someone wants to view the JSON for a collection, having to look up an array reference to then look at the item reference makes the JSON harder to read than nessessary.

---

Current JSON:

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "Sandbox | v1",
    "version": "1.0.0"
  },
  "paths": {
    "/v1/greeter/{name}": {
      "get": {
        "tags": [
          "Greeter"
        ],
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HelloReply17"
                }
              }
            }
          },
          "default": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Status9"
                }
              }
            }
          }
        }
      }
    },
    "/v1/greeter": {
      "post": {
        "tags": [
          "Greeter"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/HelloRequestFrom9"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HelloReply17"
                }
              }
            }
          },
          "default": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Status9"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ArrayOfAny": {
        "type": "array",
        "nullable": true
      },
      "HelloReply": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "nested": {
            "$ref": "#/components/schemas/HelloReply16"
          }
        }
      },
      "HelloReply10": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "nested": {
            "$ref": "#/components/schemas/#/properties/nested"
          }
        },
        "nullable": true
      },
      "HelloReply11": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "nested": {
            "$ref": "#/components/schemas/HelloReply16"
          }
        }
      },
      "HelloReply12": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "nested": {
            "$ref": "#/components/schemas/#/properties/nested"
          }
        },
        "nullable": true
      },
      "HelloReply13": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "nested": {
            "$ref": "#/components/schemas/HelloReply16"
          }
        }
      },
      "HelloReply14": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "nested": {
            "$ref": "#/components/schemas/#/properties/nested"
          }
        },
        "nullable": true
      },
      "HelloReply15": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "nested": {
            "$ref": "#/components/schemas/HelloReply16"
          }
        }
      },
      "HelloReply16": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "nested": {
            "$ref": "#/components/schemas/#/properties/nested"
          }
        },
        "nullable": true
      },
      "HelloReply17": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "nested": {
            "$ref": "#/components/schemas/HelloReply18"
          }
        }
      },
      "HelloReply18": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "nested": {
            "$ref": "#/components/schemas/#/properties/nested"
          }
        },
        "nullable": true
      },
      "HelloReply2": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "nested": {
            "$ref": "#/components/schemas/#/properties/nested"
          }
        },
        "nullable": true
      },
      "HelloReply3": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "nested": {
            "$ref": "#/components/schemas/HelloReply16"
          }
        }
      },
      "HelloReply4": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "nested": {
            "$ref": "#/components/schemas/#/properties/nested"
          }
        },
        "nullable": true
      },
      "HelloReply5": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "nested": {
            "$ref": "#/components/schemas/HelloReply16"
          }
        }
      },
      "HelloReply6": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "nested": {
            "$ref": "#/components/schemas/#/properties/nested"
          }
        },
        "nullable": true
      },
      "HelloReply7": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "nested": {
            "$ref": "#/components/schemas/HelloReply16"
          }
        }
      },
      "HelloReply8": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "nested": {
            "$ref": "#/components/schemas/#/properties/nested"
          }
        },
        "nullable": true
      },
      "HelloReply9": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "nested": {
            "$ref": "#/components/schemas/HelloReply16"
          }
        }
      },
      "HelloRequestFrom": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "from": {
            "type": "string"
          }
        }
      },
      "HelloRequestFrom2": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "from": {
            "type": "string"
          }
        }
      },
      "HelloRequestFrom3": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "from": {
            "type": "string"
          }
        }
      },
      "HelloRequestFrom4": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "from": {
            "type": "string"
          }
        }
      },
      "HelloRequestFrom5": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "from": {
            "type": "string"
          }
        }
      },
      "HelloRequestFrom6": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "from": {
            "type": "string"
          }
        }
      },
      "HelloRequestFrom7": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "from": {
            "type": "string"
          }
        }
      },
      "HelloRequestFrom8": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "from": {
            "type": "string"
          }
        }
      },
      "HelloRequestFrom9": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "from": {
            "type": "string"
          }
        }
      },
      "Status": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "message": {
            "type": "string"
          },
          "details": {
            "$ref": "#/components/schemas/ArrayOfAny"
          }
        }
      },
      "Status2": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "message": {
            "type": "string"
          },
          "details": {
            "$ref": "#/components/schemas/ArrayOfAny"
          }
        }
      },
      "Status3": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "message": {
            "type": "string"
          },
          "details": {
            "$ref": "#/components/schemas/ArrayOfAny"
          }
        }
      },
      "Status4": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "message": {
            "type": "string"
          },
          "details": {
            "$ref": "#/components/schemas/ArrayOfAny"
          }
        }
      },
      "Status5": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "message": {
            "type": "string"
          },
          "details": {
            "$ref": "#/components/schemas/ArrayOfAny"
          }
        }
      },
      "Status6": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "message": {
            "type": "string"
          },
          "details": {
            "$ref": "#/components/schemas/ArrayOfAny"
          }
        }
      },
      "Status7": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "message": {
            "type": "string"
          },
          "details": {
            "$ref": "#/components/schemas/ArrayOfAny"
          }
        }
      },
      "Status8": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "message": {
            "type": "string"
          },
          "details": {
            "$ref": "#/components/schemas/ArrayOfAny"
          }
        }
      },
      "Status9": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "message": {
            "type": "string"
          },
          "details": {
            "$ref": "#/components/schemas/ArrayOfAny"
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Greeter"
    }
  ]
}
```

**Comment by martincostello** [comment]
> Also, there are duplicated definitions in the references. e.g. `HelloReply1`, `HelloReply2`, `HelloReply3`, etc. I'm guessing there is something wrong with the schema comparer that causes them not to be equal.
> 
> Every time I refresh the OpenAPI document on the server, the reference numbers increase. For example, `HelloReply` starts at `HelloReply1` and quickly increases to `HelloReply12` after a few refreshes. The cause is the problem above, but I also don't think you should cache schema references between document generations.

I think that's #56541.

**Comment by JamesNK** [comment]
Paused until schema generator customization improves.

**Pull request closed without merging**
