### PR TITLE
Add ToString() override for UriEndpoint

### PR DESCRIPTION
**Pull request by igor-leshkevych**
Addresses #12656

### CODE REVIEW

**Comment by anurse** [comment]
This work is not approved for 3.1 and isn't likely to be (the scope for 3.1 is very narrow and only critical fixes/changes are likely to be approved). Can you re-target this to `master`?

Otherwise I think this is good, we'd also want some tests to validate the output of `ToString` (just create some endpoints, `ToString` them and validate the output). If you can retarget this to `master` I think we can review this and get it merged in!

**Comment by igor-leshkevych** [comment]
> This work is not approved for 3.1 and isn't likely to be (the scope for 3.1 is very narrow and only critical fixes/changes are likely to be approved). Can you re-target this to `master`?
> 
> Otherwise I think this is good, we'd also want some tests to validate the output of `ToString` (just create some endpoints, `ToString` them and validate the output). If you can retarget this to `master` I think we can review this and get it merged in!

Thanks for your feedback. Sure, I will retarget that to `master` and add some tests. 

Any recommendations regarding where should I put them? I see some tests [here](../tree/master/src/Servers/test/FunctionalTests) but this looks more like servers comparison tests, so not sure that tests for `Connections.Abstractions` should live there as well.

**Comment by halter73** [comment]
There's already an open PR for this by @ste1nstone targeting `master1`: https://github.com/aspnet/AspNetCore/pull/12668. I approved it a while back, but at the time, I don't think `master` was open to 5.0 changes.

Sorry for the confusion!

**Comment by igor-leshkevych** [comment]
Ok, got it. Closing that.

**Pull request closed without merging**
