### PR TITLE
Remove Components.Server reference from templates

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes https://github.com/aspnet/AspNetCore/issues/9265

### CODE REVIEW

**Review by danroth27 — APPROVED** [review]

**Comment by natemcmaster** [comment]
👀  @aspnet/build

**Comment by natemcmaster** [comment]
QB Approval tracking item: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/844752

**Comment by dougbu** [comment]
@natemcmaster as far as I can tell, this PR was not M2 (@Eilon) or QB approved. Did I miss something?

**Comment by natemcmaster** [comment]
It was approved via email

**Comment by dougbu** [comment]
😄

**Pull request merged**
