### PR TITLE
Fix urls in ProjectTemplates/README

### PR DESCRIPTION
**Pull request by sebastienros**

### CODE REVIEW

**Review by amcasey — APPROVED** [review]
It's not obvious to me why this would be necessary, but I trust that you've actually clicked the links.

**Comment by sebastienros** [comment]
@amcasey the current links don't work because it creates a relative link to the doc page

Screenshot 2024-06-06 165427

**Comment by sebastienros** [comment]
@halter73 could use your superpowers to merge it

**Comment by sebastienros** [comment]
It's just a README, do we need the build to pass? Do we have markdown verification steps?

**Comment by halter73** [comment]
No. It's just that I've already unassigned myself from the `aspnet-build` team, and this seemed easier than hassling Javier.

**Review by captainsafia — APPROVED** [review]
LGTM!

cc: @wtgodbe for merge powers

**Pull request merged**
