### PR TITLE
fix npm flake

### PR DESCRIPTION
**Pull request by JunTaoLuo**
Thanks @BrennanConroy for the fix!

### CODE REVIEW

**Review by BrennanConroy — APPROVED** [review]

**Comment by wtgodbe** [comment]
The change to `blazor.server.js` is equivalent to what I got in https://github.com/aspnet/AspNetCore/pull/12977, I'm curious to see what happens with CodeCheck here

**Comment by BrennanConroy** [comment]
John and I took a look at it and it makes sense why it was different

**Review by dougbu — APPROVED** [review]

**Comment by JunTaoLuo** [comment]
The version number burned into the .js file requires more discussion. Disabling the codecheck step for that file to unblock builds but we need a better solution. Will send out an email to discuss this.

**Comment by BrennanConroy** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=308659&view=logs

**Pull request merged**
