### PR TITLE
Update OAuthTokenResponse.cs

### PR DESCRIPTION
**Pull request by merijndejonge**
Add IdentityToken property and initialise it from id_token in the received JSON payload.

# {PR title}

- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

{Detail}

Fixes #{bug number} (in this specific format)

### CODE REVIEW

**Comment by merijndejonge** [comment]
This addresses issue #53761

**Comment by martincostello** [comment]
Changes like this need to go through the [API review process](https://github.com/dotnet/aspnetcore/issues/new?assignees=&labels=api-suggestion&projects=&template=30_api_proposal.md&title=) and be approved.

**Comment by merijndejonge** [comment]
There it is:
https://github.com/dotnet/aspnetcore/issues/53765

**Comment by martincostello** [comment]
If the team approve it and you come back to this, the team will likely need at least one test adding to cover the change and make sure it keeps working going forwards.

**Comment by merijndejonge** [comment]
let's wait for the team to improve it first then ;-)

**Comment by martincostello** [comment]
If you close and re-open the issue the CI will run for you.

**Comment by halter73** [comment]
Thanks for your contribution @merijndejonge. We're closing this one, since the API was [not approved](https://github.com/dotnet/aspnetcore/issues/53765#issuecomment-1971622001).

**Pull request closed without merging**
