### PR TITLE
PipeThroughputBenchmark to cover more cases

### PR DESCRIPTION
**Pull request by benaadams**
```
                Method | Length | Chunks |       Mean |      Error |     StdDev |        Op/s | Allocated |
---------------------- |------- |------- |-----------:|-----------:|-----------:|------------:|----------:|
   Parse_ParallelAsync |    128 |      1 |   220.6 ns |  1.5512 ns |  1.4510 ns | 4,533,594.4 |     640 B |
   Parse_ParallelAsync |    128 |      2 |   278.5 ns |  2.7348 ns |  2.5581 ns | 3,590,931.7 |     640 B |
   Parse_ParallelAsync |    128 |      4 |   370.3 ns |  4.0975 ns |  3.4216 ns | 2,700,506.4 |     640 B |
   Parse_ParallelAsync |    128 |     16 |   740.1 ns |  8.5636 ns |  8.0104 ns | 1,351,178.2 |     640 B |
   Parse_ParallelAsync |   4096 |      1 |   594.5 ns |  6.7791 ns |  6.0095 ns | 1,682,215.5 |     640 B |
   Parse_ParallelAsync |   4096 |      2 |   664.4 ns |  9.6278 ns |  9.0058 ns | 1,505,151.6 |     640 B |
   Parse_ParallelAsync |   4096 |      4 |   692.4 ns |  6.3556 ns |  5.9450 ns | 1,444,246.2 |     640 B |
   Parse_ParallelAsync |   4096 |     16 | 1,001.6 ns | 10.5697 ns |  9.8869 ns |   998,373.3 |     640 B |
                       |        |        |            |            |            |             |           |
 Parse_SequentialAsync |    128 |      1 |   305.6 ns |  0.7858 ns |  0.6966 ns | 3,272,369.7 |       0 B |
 Parse_SequentialAsync |    128 |      2 |   320.9 ns |  1.0169 ns |  0.9015 ns | 3,116,371.4 |       0 B |
 Parse_SequentialAsync |    128 |      4 |   341.1 ns |  0.9681 ns |  0.8084 ns | 2,931,337.7 |       0 B |
 Parse_SequentialAsync |    128 |     16 |   520.9 ns | 10.0641 ns | 14.7518 ns | 1,919,708.6 |       0 B |
 Parse_SequentialAsync |   4096 |      1 |   306.4 ns |  0.5031 ns |  0.4201 ns | 3,264,029.4 |       0 B |
 Parse_SequentialAsync |   4096 |      2 |   318.5 ns |  1.2733 ns |  1.1287 ns | 3,140,166.6 |       0 B |
 Parse_SequentialAsync |   4096 |      4 |   341.5 ns |  1.6186 ns |  1.4349 ns | 2,928,156.1 |       0 B |
 Parse_SequentialAsync |   4096 |     16 |   485.1 ns |  7.7856 ns |  7.2826 ns | 2,061,508.5 |       0 B |
```

/cc @pakrym @halter73 @davidfowl

### CODE REVIEW

**Comment by davidfowl** [comment]
The number of chunks isn’t super interesting IMO. BTW @benaadams and I were doing a bunch of profiling this weekend and the locks in pipe show up big time in our scenarios (we tried the concurrencey visualizer out).

**Comment by pakrym** [comment]
@davidfowl in microbenchmark or kestrel?

**Comment by davidfowl** [comment]
> @davidfowl in microbenchmark or kestrel?

Both. The platform benchmark though, we didn't try the ones that were full stack as we were trying to measure pipelines overhead.

The async benchmarks @benaadams added above:

image

The plainttextplatform benchmark:

image

**Comment by davidfowl** [comment]
I'm going to spend some time looking at lock free and a more sharded lock approach.

**Comment by pakrym** [comment]
Does this belong to dotnet/performance?

**Comment by adamsitnik** [comment]
> Does this belong to dotnet/performance?

Great idea, especially that as of today we have no benchmarks for "System.IO.Pipelines"! Could you add it to https://github.com/dotnet/performance/tree/master/src/benchmarks/micro/corefx ? 

@davidfowl just out of curiosity did you use https://github.com/dotnet/BenchmarkDotNet/issues/964 to get the Concurrency Profiler report?

**Comment by benaadams** [comment]
Used attach to,

Looking in a bit more detail Json does hit the threadpool in simultaneous pulses:

image

**Comment by benaadams** [comment]
Output is now
```
                Method | Length | Chunks |       Mean |      Error |     StdDev |        Op/s |  Gen 0 | Allocated |
---------------------- |------- |------- |-----------:|-----------:|-----------:|------------:|-------:|----------:|
   Parse_ParallelAsync |    128 |      2 | 3,128.8 ns | 35.8871 ns | 33.5688 ns |   319,616.0 | 0.0381 |     576 B |
   Parse_ParallelAsync |    128 |      4 | 3,251.2 ns | 29.4502 ns | 27.5477 ns |   307,575.1 | 0.0420 |     576 B |
   Parse_ParallelAsync |    128 |     16 | 3,793.0 ns | 54.4082 ns | 50.8934 ns |   263,645.4 | 0.0648 |     576 B |
   Parse_ParallelAsync |   4096 |      2 | 3,247.7 ns | 28.5537 ns | 26.7092 ns |   307,912.8 | 0.0458 |     576 B |
   Parse_ParallelAsync |   4096 |      4 | 3,362.0 ns | 28.5643 ns | 26.7191 ns |   297,438.7 | 0.0420 |     576 B |
   Parse_ParallelAsync |   4096 |     16 | 3,859.4 ns | 33.2993 ns | 31.1482 ns |   259,110.6 | 0.0610 |     576 B |
   Parse_ParallelAsync |   8192 |      2 | 3,536.3 ns | 30.3224 ns | 28.3636 ns |   282,780.4 | 0.0420 |     576 B |
   Parse_ParallelAsync |   8192 |      4 | 3,704.6 ns | 46.4258 ns | 43.4267 ns |   269,934.4 | 0.0572 |     576 B |
   Parse_ParallelAsync |   8192 |     16 | 4,314.0 ns | 83.1630 ns | 73.7218 ns |   231,803.4 | 0.0534 |     576 B |
                       |        |        |            |            |            |             |        |           |
 Parse_SequentialAsync |    128 |      2 |   365.7 ns |  2.0509 ns |  1.7126 ns | 2,734,548.7 |      - |       0 B |
 Parse_SequentialAsync |    128 |      4 |   391.1 ns |  0.9741 ns |  0.8636 ns | 2,556,756.9 |      - |       0 B |
 Parse_SequentialAsync |    128 |     16 |   527.2 ns |  3.2683 ns |  2.7292 ns | 1,896,969.4 |      - |       0 B |
 Parse_SequentialAsync |   4096 |      2 |   414.9 ns |  1.5304 ns |  1.4316 ns | 2,410,363.9 |      - |       0 B |
 Parse_SequentialAsync |   4096 |      4 |   394.1 ns |  2.3205 ns |  1.9378 ns | 2,537,113.3 |      - |       0 B |
 Parse_SequentialAsync |   4096 |     16 |   529.2 ns |  4.6854 ns |  4.1535 ns | 1,889,574.0 |      - |       0 B |
 Parse_SequentialAsync |   8192 |      2 |   489.4 ns |  1.4036 ns |  1.3129 ns | 2,043,209.0 |      - |       0 B |
 Parse_SequentialAsync |   8192 |      4 |   508.7 ns |  1.6582 ns |  1.5510 ns | 1,965,830.5 |      - |       0 B |
 Parse_SequentialAsync |   8192 |     16 |   630.1 ns |  1.7526 ns |  1.5536 ns | 1,587,172.7 |      - |       0 B |
```

**Comment by benaadams** [comment]
Output betterified and properly measuring things
```
                Method | Length | Chunks |       Mean |      Error |     StdDev |        Op/s | Allocated |
---------------------- |------- |------- |-----------:|-----------:|-----------:|------------:|----------:|
   Parse_ParallelAsync |    128 |      1 |   220.6 ns |  1.5512 ns |  1.4510 ns | 4,533,594.4 |     640 B |
   Parse_ParallelAsync |    128 |      2 |   278.5 ns |  2.7348 ns |  2.5581 ns | 3,590,931.7 |     640 B |
   Parse_ParallelAsync |    128 |      4 |   370.3 ns |  4.0975 ns |  3.4216 ns | 2,700,506.4 |     640 B |
   Parse_ParallelAsync |    128 |     16 |   740.1 ns |  8.5636 ns |  8.0104 ns | 1,351,178.2 |     640 B |
   Parse_ParallelAsync |   4096 |      1 |   594.5 ns |  6.7791 ns |  6.0095 ns | 1,682,215.5 |     640 B |
   Parse_ParallelAsync |   4096 |      2 |   664.4 ns |  9.6278 ns |  9.0058 ns | 1,505,151.6 |     640 B |
   Parse_ParallelAsync |   4096 |      4 |   692.4 ns |  6.3556 ns |  5.9450 ns | 1,444,246.2 |     640 B |
   Parse_ParallelAsync |   4096 |     16 | 1,001.6 ns | 10.5697 ns |  9.8869 ns |   998,373.3 |     640 B |
                       |        |        |            |            |            |             |           |
 Parse_SequentialAsync |    128 |      1 |   305.6 ns |  0.7858 ns |  0.6966 ns | 3,272,369.7 |       0 B |
 Parse_SequentialAsync |    128 |      2 |   320.9 ns |  1.0169 ns |  0.9015 ns | 3,116,371.4 |       0 B |
 Parse_SequentialAsync |    128 |      4 |   341.1 ns |  0.9681 ns |  0.8084 ns | 2,931,337.7 |       0 B |
 Parse_SequentialAsync |    128 |     16 |   520.9 ns | 10.0641 ns | 14.7518 ns | 1,919,708.6 |       0 B |
 Parse_SequentialAsync |   4096 |      1 |   306.4 ns |  0.5031 ns |  0.4201 ns | 3,264,029.4 |       0 B |
 Parse_SequentialAsync |   4096 |      2 |   318.5 ns |  1.2733 ns |  1.1287 ns | 3,140,166.6 |       0 B |
 Parse_SequentialAsync |   4096 |      4 |   341.5 ns |  1.6186 ns |  1.4349 ns | 2,928,156.1 |       0 B |
 Parse_SequentialAsync |   4096 |     16 |   485.1 ns |  7.7856 ns |  7.2826 ns | 2,061,508.5 |       0 B |
```

**Comment by halter73** [comment]
The Parse_ParallelAsync benchmark with 4 chunks of 8192 bytes went from a 2,189.3 ns mean to a 3,704.6 ns mean. I wonder why.

**Comment by benaadams** [comment]
> The Parse_ParallelAsync benchmark with 4 chunks of 8192 bytes went from a 2,189.3 ns mean to a 3,704.6 ns mean. I wonder why.

Bad benchmark; now the results are:
```
                Method | Length | Chunks |       Mean |    Error |    StdDev |        Op/s | Allocated |
---------------------- |------- |------- |-----------:|---------:|----------:|------------:|----------:|
   Parse_ParallelAsync |   8192 |      2 |   924.0 ns | 4.181 ns | 3.4910 ns | 1,082,305.8 |     640 B |
   Parse_ParallelAsync |   8192 |      4 |   946.7 ns | 5.732 ns | 5.3619 ns | 1,056,309.6 |     640 B |
   Parse_ParallelAsync |   8192 |     16 | 1,242.2 ns | 4.923 ns | 4.6048 ns |   805,049.2 |     640 B |
                       |        |        |            |          |           |             |           |
 Parse_SequentialAsync |   8192 |      2 |   402.6 ns | 1.018 ns | 0.9522 ns | 2,483,735.9 |       0 B |
 Parse_SequentialAsync |   8192 |      4 |   421.4 ns | 1.026 ns | 0.9596 ns | 2,373,177.7 |       0 B |
 Parse_SequentialAsync |   8192 |     16 |   572.6 ns | 2.746 ns | 2.2933 ns | 1,746,375.1 |       0 B |
```

**Comment by benaadams** [comment]
Well, actually this; one above was using a variant of this PR https://github.com/dotnet/corefx/pull/35234
```
                Method | Length | Chunks |       Mean |    Error |   StdDev |        Op/s | Allocated |
---------------------- |------- |------- |-----------:|---------:|---------:|------------:|----------:|
   Parse_ParallelAsync |   8192 |      2 |   926.2 ns | 5.885 ns | 5.505 ns | 1,079,681.2 |     640 B |
   Parse_ParallelAsync |   8192 |      4 |   978.2 ns | 5.657 ns | 5.292 ns | 1,022,301.4 |     640 B |
   Parse_ParallelAsync |   8192 |     16 | 1,510.4 ns | 7.226 ns | 6.759 ns |   662,060.4 |     640 B |

**Review by halter73 — APPROVED** [review]

**Comment by halter73** [comment]
I don't like exploding the number of test cases more than necessary, but the previous test always only wrote 57 bytes per loop which wasn't very realistic.

Maybe we could remove the 4 and 8 chunk variations and just leave the 1 and 16 chunk variations.

**Comment by benaadams** [comment]
Sure, doesn't seem to be any odd behaviour the others are highlighting

**Comment by pakrym** [comment]
Are we sure we don't want this moved to 'dotnet/performance'. This is purely pipelines benchmark.

**Comment by adamsitnik** [comment]
> Are we sure we don't want this moved to 'dotnet/performance'. This is purely pipelines benchmark.

We should definitely add it to the `dotnet/performance` repo. Especially that we don't have any `System.IO.Pipelines` benchmarks there. I added an issue for that to keep track of it https://github.com/dotnet/performance/issues/317

**Comment by anurse** [comment]
Since this should go to dotnet/performance, I'll close this for now. Happy to re-open if others have a different thought :).

**Pull request closed without merging**
