### PR TITLE
Update sdk to v7.0.100-preview.3.22159.27

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Review by sebastienros — APPROVED** [review]

**Review by wtgodbe — APPROVED** [review]

**Comment by pranavkm** [comment]
Looks like some of the middleware tests are failing. I couldn't reproduce the failure locally, so I'm guessing it's something do with how we deploy tests to Helix.

@HaoK could you help here? Do we publish tests projects and then pack them using the SDK?

**Comment by HaoK** [comment]
You can get the publish directory from this zip, maybe you can reproduce it from that: https://helixde8s23ayyeko0k025g8.blob.core.windows.net/helix-job-015dd8b5-a2e8-4d54-a2ec-5bd753ba4c4caa245e00b2c4f6e8a/087bdf6a-071b-4f07-9da7-1dab11da7fd4.zip

**Comment by HaoK** [comment]
cc @dougbu in case some of his recent helix work affected anything potentially

**Comment by dougbu** [comment]
> I'm guessing it's something do with how we deploy tests to Helix.

&hellip;

> cc @dougbu in case some of his recent helix work affected anything potentially

Is a file actually missing on the Helix agents❔ I ask because the aspnetcore-components-e2e failure looks quite real and I could imagine the StaticFiles test failures are related to whatever caused that -- likely a merge ordering issue.

More generally, @HaoK provided a useful link. You can also test using eng/scripts/RunHelix.ps1 to grab a binary log of the Helix submission and examine the publish/ folder as necessary. You may want to comment out the following to avoid an actual submission because that can spin for a long while then fail (lots to upload).

https://github.com/dotnet/aspnetcore/blob/4dc82d8da6500810b3dc57adedc0eeb1dabd4b17/eng/scripts/RunHelix.ps1#L49-L52

**Comment by pranavkm** [comment]
Looks like a runtime regression. Filed https://github.com/dotnet/runtime/issues/65750 to track resolving it.

**Comment by halter73** [comment]
aspnetcore-components-e2e is still failing with the following: 

```
/home/vsts/work/1/s/src/Components/WebAssembly/testassets/Wasm.Authentication.Client/Pages/Authentication.razor(8,48): error CS1503: Argument 2: cannot convert from 'method group' to 'EventCallback' [/home/vsts/work/1/s/src/Components/WebAssembly/testassets/Wasm.Authentication.Client/Wasm.Authentication.Client.csproj]
```

@javiercn Do you have any idea what could be happening here?

**Review by wtgodbe — APPROVED** [review]

**Comment by javiercn** [comment]
FYI, I'm working on the compiler fix, it's turning out to be a bit tricky.

**Comment by javiercn** [comment]
Fix is merged on the razor-compiler side, so it'll have to trickle up to here

**Comment by TanayParikh** [comment]
> Fix is merged on the razor-compiler side, so it'll have to trickle up to here

Thanks Javier, I've triggered the subscription from razor-compiler -> sdk. Will monitor and update this PR with the updated SDK version once that dep update PR is merged.

**Comment by TanayParikh** [comment]
Updated SDK to reflect artifacts produced by https://dev.azure.com/dnceng/internal/_build/results?buildId=1655041&view=results. There's a chance this still fails due to the artifacts not having fully propagated yet.

**Review by TanayParikh — APPROVED** [review]

**Comment by wtgodbe** [comment]
@TanayParikh that's a build of dotnet/sdk, you need to wait for it to flow through to dotnet/installer then use the SDK produced by _that_ build

**Comment by TanayParikh** [comment]
> @TanayParikh that's a build of dotnet/sdk, you need to wait for it to flow through to dotnet/installer then use the SDK produced by _that_ build

Ah okay, thanks for the clarification. In that case, it'll be https://github.com/dotnet/installer/pull/13375.

**Comment by TanayParikh** [comment]
Middleware tests are still [failing](https://dev.azure.com/dnceng/public/_build/results?buildId=1655573&view=ms.vss-test-web.build-test-results-tab&runId=45630596&resultId=110005&paneView=debug) unfortunately, I believe the fix for that was https://github.com/dotnet/runtime/pull/65886. cc/ @Jozkee @carlossanlop 

The components-e2e pipeline now passes so that should be indicative of us consuming Javier's compiler fix via `v7.0.100-preview.3.22159.27`.

**Comment by TanayParikh** [comment]
@HaoK, @dougbu, @wtgodbe does anyone have context in this area? The components-e2e failures are now resolved by the middleware static files issues persist. https://github.com/dotnet/runtime/issues/65750 has also been marked resolved via https://github.com/dotnet/runtime/pull/65886.

**Comment by HaoK** [comment]
https://github.com/dotnet/runtime/issues/65750 has a good summary and all the context

**Comment by wtgodbe** [comment]
Something must have changed in runtime to cause the new behavior - whoever owns those tests should take a look and see if it's a bug, or a real behavioral change that will necessitate a reaction on our part (test update or src update)

**Comment by HaoK** [comment]
I would reopen the issue since the helix issue isn't fixed, they might have fixed some comment issue, but clearly the e2e doesn't work on helix still

**Comment by HaoK** [comment]
@Jozkee did you try the repro in https://github.com/pranavkm/zip-file with the fix to verify that the helix usage works now?

**Comment by wtgodbe** [comment]
Ah, that'll do it - we should combine this PR with https://github.com/dotnet/aspnetcore/pull/40507

**Comment by Jozkee** [comment]
@HaoK, yes, I used 7zip and winzip to verify the changes. Also added a [unit test](https://github.com/dotnet/runtime/blob/cdb1d26bcc40cd651afb5ed8898b0e7e03e95102/src/libraries/System.IO.Compression/tests/ZipArchive/zip_CreateTests.cs#L184) in dotnet/runtime.

**Comment by wtgodbe** [comment]
Updated the SDK in https://github.com/dotnet/aspnetcore/pull/40507, if that works we can close this PR

**Comment by TanayParikh** [comment]
Looks like we're making progress in https://github.com/dotnet/aspnetcore/pull/40507. Closing this out.

**Pull request closed without merging**
