### PR TITLE
Fixed typo. Removed unnecessary K. Added certificate instructions for Linux.

### PR DESCRIPTION
**Pull request by nrekretep**

### CODE REVIEW

**Comment by Eilon** [comment]
@glennc @BrennanConroy @moozzyk can one of you review?

**Comment by Eilon** [comment]
BTW the change to readme.md isn't needed anymore because that's already been fixed.

**Comment by BrennanConroy** [comment]
I've never had to do anything with certificates before.

**Comment by glennc** [comment]
Closing as I don't think this is needed anymore. Mono now adds certificates when you install the package and the K has been removed.

**Pull request closed without merging**
