### PR TITLE
Update arcade

### PR DESCRIPTION
**Pull request by JunTaoLuo**

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
Looks fine.

Just curious: Did `trigger-subscriptions` fail in some way? (Usually easier to have the bot create or update PRs because you don't need an additional reviewer.)

**Comment by natemcmaster** [comment]
Can you run the update once more? The Arcade build that has https://github.com/dotnet/arcade/pull/3026 just became available. This will unblock x86 tests.

**Review by natemcmaster — APPROVED** [review]

**Comment by JunTaoLuo** [comment]
@dougbu I wanted to make this update as part of the PR instead of directly to master and requiring rebase, etc.

**Comment by JunTaoLuo** [comment]
Also I thought this version already included that update, but updated again anyway.

**Comment by JunTaoLuo** [comment]
Going to merge this to @natemcmaster 's  branch

**Pull request merged**
