### PR TITLE
React to System.Text.Json namespace changes

### PR DESCRIPTION
**Pull request by sebastienros**

### CODE REVIEW

**Comment by sebastienros** [comment]
This app doesn't impact the CI, if someone wants to merge it so it doesn't take too much resources, and it unblocks the benchmarks, then thanks.

**Comment by benaadams** [comment]
This is why Platform benchmarks are broken?

**Comment by sebastienros** [comment]
Yep

**Comment by sebastienros** [comment]
Can someone merge it? Not sure if I can't because there is not review of the failing helix step.

**Review by davidfowl — APPROVED** [review]

**Pull request merged**
