### PR TITLE
Adding SubmitAsync() method to EditForm to allow manually triggered s…

### PR DESCRIPTION
**Pull request by FluentGuru**
…ubmit.

Summary of the changes (Less than 80 chars)
- Creates a SubmitAsync method that triggers the onsubmit handler inside the EditForm component. 

Addresses #10953

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
Please add documentation, tests and proper formatting to this change, so that we can move forward with this.

**Comment by mkArtakMSFT** [comment]
@FluentGuru do you plan to update this per comments?

**Comment by FluentGuru** [comment]
> @FluentGuru do you plan to update this per comments?

My bad. Github did not notify me for this.

Yes. I can update sometime this week when I get time. How long do I have before is rejected?

**Comment by SteveSandersonMS** [comment]
@FluentGuru Don't worry about rushing. Even if we did close this due to inactivity, you can always just reopen it at any time (or submit a new PR, as you wish).

If a PR is closed, it can just be a flag so we know not to keep doing more with it right now - it doesn't necessarily mean it's rejected permanently!

**Comment by mkArtakMSFT** [comment]
We're closing this PR as we seen no activity on this for some time now.

**Pull request closed without merging**
