### PR TITLE
Quarantine CanLaunchPhotinoWebViewAndClickButton

### PR DESCRIPTION
**Pull request by BrennanConroy**
For some reason retry isn't working for this test? Or it's still failing a lot even with a retry.

### CODE REVIEW

**Comment by Eilon** [comment]
My PR https://github.com/dotnet/aspnetcore/pull/54608 was merged yesterday into release/8.0. Does that end up going into main as well? If not, how do I make sure that happens? And if it already did, were the failures/flakiness after it was merged into main?

**Comment by BrennanConroy** [comment]
> Does that end up going into main as well?

Probably not, you'd need to manually do it.

**Review by captainsafia — APPROVED** [review]
Approving to unblock this but let's work towards getting https://github.com/dotnet/aspnetcore/pull/54608 into main.

cc: @Eilon

**Pull request merged**
