### PR TITLE
Move IServerVariablesFeature to Http.Features

### PR DESCRIPTION
**Pull request by mderriey**
- Move `IServerVariablesFeature` to `Http.Features` and forward in `Servers.IIS`
- Create `GetServerVariable` in `Http.Extensions`
- Mark `GetIISServerVariable` obsolete in `Servers.IIS`

Addresses #10167

### CODE REVIEW

**Comment by Tratcher** [comment]
"You might need to regenerate the reference assemblies ... see [docs/ReferenceAssemblies.md](https://github.com/aspnet/AspNetCore/blob/master/docs/ReferenceAssemblies.md)"

**Comment by mderriey** [comment]
Oh sorry about that, I thought I did for the projects which changed. I'll do it globally as I must have missed something.

Thanks.

**Comment by mderriey** [comment]
Errors in the latest builds

```
F:\workspace\_work\1\s\src\Servers\IIS\IIS\test\testassets\InProcessWebSite\Startup.cs(37,44): error CS0433: The type 'IServerVariablesFeature' exists in both 'Microsoft.AspNetCore.Http.Features, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Server.IIS, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' [F:\workspace\_work\1\s\src\Servers\IIS\IIS\test\testassets\InProcessForwardsCompatWebSite\InProcessForwardsCompatWebSite.csproj]
F:\workspace\_work\1\s\src\Servers\IIS\IIS\test\testassets\InProcessWebSite\Startup.cs(705,58): error CS0433: The type 'IServerVariablesFeature' exists in both 'Microsoft.AspNetCore.Http.Features, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Server.IIS, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' [F:\workspace\_work\1\s\src\Servers\IIS\IIS\test\testassets\InProcessForwardsCompatWebSite\InProcessForwardsCompatWebSite.csproj]
F:\workspace\_work\1\s\src\Servers\IIS\IIS\samples\NativeIISSample\Startup.cs(83,72): error CS0618: 'HttpContextExtensions.GetIISServerVariable(HttpContext, string)' is obsolete: 'This is obsolete and will be removed in a future version. Use GetServerVariable instead.' [F:\workspace\_work\1\s\src\Servers\IIS\IIS\samples\NativeIISSample\NativeIISSample.csproj]
```

I believe updating samples to use the new `GetServerVariable` method will fix the 3rd one.
I'm not too sure what needs to be done to fix the first two, though. I've never done type-forwarding before, so maybe I did it wrong?

**Comment by Tratcher** [comment]
@jkotalik It's pretty strange that InProcessForwardsCompatWebSite mixes package versions like that. It should be all 2.2 or all 3.0.

**Comment by mderriey** [comment]
How dumb!

They both live in the same namespace so my attempt to differentiate one from the other via namespaces obviously didn't work.

**Comment by jkotalik** [comment]
@mderriey I'm going to take a stab at fixing the namespace resolution issue you are hitting.

**Comment by jkotalik** [comment]
Closing in favor of my new PR (as I couldn't push to your fork without cloning).

**Pull request closed without merging**
