### PR TITLE
Include dependencies in Mvc.sln

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Review by natemcmaster — APPROVED** [review]

**Comment by dougbu** [comment]
@pranavkm did you do the same work for Mvc.NoFun.sln? If not, LMK because I have a PR ready to go for that solution&hellip;

**Comment by dougbu** [comment]
That was a silly question 😺 I opened #6212.

**Comment by pranavkm** [comment]
I was considering removing Mvc.NoFun after we discussed it later this week.

**Comment by dougbu** [comment]
Well, Mvc.NoFun.sln is still only 2/3 the size of Mvc.sln. It still opens faster than Mvc.sln even if the functional tests no longer bring everything to a grinding halt.

**Pull request merged**
