### PR TITLE
Add a package for source build

### PR DESCRIPTION
**Pull request by JunTaoLuo**
Waiting for confirmation from source build that we need this package but just running through the motions to make sure it works.

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
cc @crummel

**Review by dougbu — APPROVED** [review]
Looks fine if we need it

**Review by crummel — APPROVED** [review]
This fixed the F# offline web templates in source-build, thanks!

**Comment by dougbu** [comment]
@crummel should this be retargeted to 'release/3.0-preview9'? We created those branches at noon&hellip;

**Comment by crummel** [comment]
This is a pretty straightforward patch for us to have for now so I think we're fine with whatever screws with your release process the least.

**Comment by JunTaoLuo** [comment]
I think we'll do a more thorough backport of patches once the changes required for aspnetcore is finalized. I'll close this for now. No point in getting just this bit into preview 9.

**Pull request closed without merging**
