### PR TITLE
Update schema before running tests

### PR DESCRIPTION
**Pull request by pakrym**
We were lucky and tests were running on already updated machines.

### CODE REVIEW

**Review by natemcmaster — APPROVED** [review]

**Comment by jkotalik** [comment]
@pakrym can we disable application verifier on universe builds? (we are hitting a 2 hr timeout)

**Comment by pakrym** [comment]
Build hung on music store but went past IISIntegration

**Comment by pakrym** [comment]
We are not enabling it.

**Comment by jkotalik** [comment]
Looks like it didn't hang on music store; it timed out. Start time of 01:05:12.8704685Z and end time of 02:32:50.0444798Z. Music store only ran for 5 minutes.

**Pull request merged**
