### PR TITLE
Specify the current agent demands and VS version

### PR DESCRIPTION
**Pull request by dougbu**
- we require VS2022 to build native code these days
- Core-Eng really likes `1es-windows-2019[-open]` :grinning:

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Review by MattGal — APPROVED** [review]
LGTM, I'll be on point for any Microbuild failures after this on internal

**Comment by dougbu** [comment]
@MattGal the internal build is <https://dev.azure.com/dnceng/internal/_build/results?buildId=1848691&view=results>. If something fails, I expect missing VS components will be the problem. But I guess we could still see cert issues.

**Comment by MattGal** [comment]
@dougbu both legs there are already past the certificate-needing steps, so I am holding fingers crossed for your dependencies.

**Comment by dougbu** [comment]
I am more concerned about builds not starting _at all_ in aspnetcore-ci or aspnetcore-components-e2e. Other PR updates have resulted in new builds after this one should have. I don't see anything indicating what's going on.

**Comment by dougbu** [comment]
For future reference, my last comment was about the (normally very short-lived) display of the Checks status:
image

**Comment by MattGal** [comment]
> @MattGal the internal build is https://dev.azure.com/dnceng/internal/_build/results?buildId=1848691&view=results. If something fails, I expect missing VS components will be the problem. But I guess we could still see cert issues.

Yup you're right, missing SDK again.  Sorry to get your hopes up... at least signing works now.

**Comment by dougbu** [comment]
> Yup you're right, missing SDK again.

Nah. That one was on us -- using a different Windows SDK for our installers. I fixed it up.

**Review by HaoK — APPROVED** [review]

**Pull request merged**
