### PR TITLE
Fix missing using in Http3TimeoutTests

### PR DESCRIPTION
**Pull request by adityamandaleeka**
The build is broken after this PR went in: https://github.com/dotnet/aspnetcore/pull/43250

@BrennanConroy PTAL

### CODE REVIEW

**Comment by adityamandaleeka** [comment]
@dotnet/aspnet-build I assume this will be needed in the 7.0/RC1 branches as well.

**Comment by halter73** [comment]
Use my PR instead lol! https://github.com/dotnet/aspnetcore/pull/43302

**Review by sebastienros — APPROVED** [review]

**Comment by dougbu** [comment]
Anything missing in release/7.0-rc1 or release/7.0 (for RC2) will need to be backported (using the bot)

**Comment by adityamandaleeka** [comment]
Merged on red; the upload failures plaguing this and many other PRs are unrelated, and I didn't want everything to fail with this build issue when those PRs are retried.

**Comment by dougbu** [comment]
I'm confused. #43250 was green when it merged. Did something go in after CI validation in #43250 completed that conflicted❔ If not, what went wrong❔

**Comment by adityamandaleeka** [comment]
https://github.com/dotnet/aspnetcore/pull/43037 went in before #43250 and added some code that depended on this using (which #43250 removed).

**Comment by dougbu** [comment]
Since we haven't configured anything for our build process yet (right @wtgodbe❔), also backported to release/7.0.

**Comment by wtgodbe** [comment]
Correct

**Pull request merged**
