### PR TITLE
Add missing ref-assembly for header propagation

### PR DESCRIPTION
**Pull request by rynowak**
I think this was missed because the PR predates ref assemblies :)

### CODE REVIEW

**Review by Eilon — APPROVED** [review]
Looks legit.

**Comment by rynowak** [comment]
@aspnet-hello triage

**Comment by Eilon** [comment]
Looks like Ubuntu hung on Kestrel tests:

```
  Starting test group: InMemory.FunctionalTests/netcoreapp3.0
  Microsoft (R) Test Execution Command Line Tool Version 16.0.0-preview-20190124-02
  Copyright (c) Microsoft Corporation.  All rights reserved.
  
  Starting test execution, please wait...
```

**Comment by Eilon** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=138017

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

I've triaged the above build.

**Pull request merged**
