### PR TITLE
Use token expiration value from options as fallback

### PR DESCRIPTION
**Pull request by mapogolions**
Perhaps using the token expiration value from the options makes sense only if the user does not explicitly specify the ExpiresUtc property.

Example to reproduce

```csharp
builder.Services
    .AddAuthentication(BearerTokenDefaults.AuthenticationScheme)
    .AddBearerToken(BearerTokenDefaults.AuthenticationScheme, options =>
    {
        options.BearerTokenExpiration = TimeSpan.FromDays(1);
    });


var props = new AuthenticationProperties { ExpiresUtc = DateTime.UtcNow.Add(TimeSpan.FromHours(4));
await context.SignInAsync(principal, props);
```

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
Thanks for your PR, @mapogolions.
@halter73 can you please review this? Thanks!

**Comment by Tratcher** [comment]
Please add a test for this scenario.

**Comment by halter73** [comment]
@mapogolions Do you have a use case where you want to be able to control the access token per-sign-in but not the refresh token? This used to be supported in earlier previews, but I removed it because I didn't like the inconsistency of being able to configure one expiration but not the other.

I'm not sure this is something we want the `BearerTokenHandler` to support. As far as I know, the `CookieAuthenticationHandler` is the only other auth handler that supports configuring `AuthenticationProperties.ExpiresUtc`. It's also the only other `SignInAuthenticationHandler`, so maybe that should be expected, but I still don't think we should merge this without a solid use case.

If we do decide to make this change for .NET 9, you just have to revert [the `BearerTokenHandler` changes in `6241625`](https://github.com/dotnet/aspnetcore/commit/62416250c2d087e5e8230163f0552b37b7a9d754#diff-56e5ef6652a2fdf8cce52e0d4dc757cc8c37d277fe3ae421c0ddfc20cb68cd42). 

`CalculateExpiresInSeconds` compares the `ExpiresUtc` against `UtcNow + BearerTokenExpiration` and uses the `BearerTokenExpiration` directly for the `AccessTokenResponse.ExpiresInSecond` property if they match. Because the `AuthenticationProperties.ExpiresUtc` setter immediately floors the `DateTimeOffset` for later serialization, you'll see test failures like the ones in this PR if you just try to calculate `ExpiresInSecond` using `ExpiresUtc - UtcNow`.

```
[0.852s] [Microsoft.AspNetCore.Identity.FunctionalTests.MapIdentityApiTests] [Error] Test threw an exception.
Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 3600
Actual:   3599
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 96
   at Xunit.Assert.Equal[T](T expected, T actual) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 63
   at Microsoft.AspNetCore.Identity.FunctionalTests.MapIdentityApiTests.CanChangeAccessTokenResponseJsonOptions(String addIdentityMode) in /_/src/Identity/test/Identity.FunctionalTests/MapIdentityApiTests.cs:line 154
   at Microsoft.AspNetCore.Identity.FunctionalTests.MapIdentityApiTests.CanChangeAccessTokenResponseJsonOptions(String addIdentityMode) in /_/src/Identity/test/Identity.FunctionalTests/MapIdentityApiTests.cs:line 157
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
```

https://dev.azure.com/dnceng-public/public/_build/results?buildId=426588&view=ms.vss-test-web.build-test-results-tab

**Comment by mapogolions** [comment]
@halter73 
I don't have a clear opinion on what behavior should be considered correct.
I think there will always be people who decide to register bearer token authentication in this way.
```csharp
builder.Services
    .AddAuthentication(BearerTokenDefaults.AuthenticationScheme)
    .AddBearerToken();
```
And then during the sign in they will ask themselves: how to specify the expiration date?  They will look at the `AuthenticationProperties` and try to use them to solve the problem. But according to the current behavior, they will always get an expiration date that they didn't specify. It is a little confusing.

It might make sense to give users some hints (logging or throwing exception) when they pass `AuthenticationProperties` with ExpiresUtc that is not null.

**Pull request closed without merging**
