### PR TITLE
Remove unused ADAL dependency

### PR DESCRIPTION
**Pull request by Tratcher**
MicrosoftIdentityModelClientsActiveDirectoryVersion is an obsolete package and is no longer referenced in our repo. Removed from the versions list.

### CODE REVIEW

**Review by henrik-me — APPROVED** [review]
:shipit:

**Review by jennyf19 — APPROVED** [review]

**Review by wtgodbe — CHANGES_REQUESTED** [review]
Need to get rid of this too: https://github.com/dotnet/aspnetcore/blob/7ada9dc2f53a5a9ff3556984a28960d1d57d889b/eng/Dependencies.props#L118

**Comment by Tratcher** [comment]
Ah, the CI did find a usage of this in one of the samples.
https://github.com/dotnet/aspnetcore/blob/7ada9dc2f53a5a9ff3556984a28960d1d57d889b/src/Security/Authentication/OpenIdConnect/samples/OpenIdConnect.AzureAdSample/Startup.cs#L52-L63
@jennyf19 can you link me to any similar sample to replace this?

**Comment by dougbu** [comment]
> Ah, the CI did find a usage of this in one of the samples.

Yes, it's a bit confusing but we rarely use the version properties directly in this repo. Have to figure out where to put the periods to get the package name, then search for that. But, the CI helps too 😺

**Comment by Tratcher** [comment]
Yeah, but search didn't turn up any hits for the package name either.
https://github.com/dotnet/aspnetcore/search?q=Microsoft.IdentityModel.Clients.ActiveDirectory

**Comment by dougbu** [comment]
Might be a GitHub hiccup. VS Code took me right to the project and eng/Dependencies.props.

**Comment by henrik-me** [comment]
> Ah, the CI did find a usage of this in one of the samples.
> https://github.com/dotnet/aspnetcore/blob/7ada9dc2f53a5a9ff3556984a28960d1d57d889b/src/Security/Authentication/OpenIdConnect/samples/OpenIdConnect.AzureAdSample/Startup.cs#L52-L63
> 
> 
> @jennyf19 can you link me to any similar sample to replace this?

id.web handles the event:
https://github.com/AzureAD/microsoft-identity-web/blob/03175642f5ec06138bafd08843d8beeeae39fc64/src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilder.cs#L132

acquiring the token using the code with MSAL in id.web:
https://github.com/AzureAD/microsoft-identity-web/blob/03175642f5ec06138bafd08843d8beeeae39fc64/src/Microsoft.Identity.Web/TokenAcquisition.cs#L147

**Comment by Tratcher** [comment]
I've removed the outdated sample since this scenario is now covered by Identity.Web instead.

**Review by wtgodbe — APPROVED** [review]

**Pull request merged**
