### PR TITLE
Update PatchConfig.props

### PR DESCRIPTION
**Pull request by BrennanConroy**

### CODE REVIEW

**Comment by Eilon** [comment]
Added some potential reviewer candidates.

**Review by mikaelm12 — APPROVED** [review]

**Comment by mikaelm12** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=124158&view=logs

**Review by dougbu — APPROVED** [review]

**Comment by dougbu** [comment]
Not likely related to this particular change but the Linux failure looks real. Did something get messed up in the failing project?
```
error MSB3030: Could not copy the file "/datadisks/disk1/vsagent/work/6/s/src/Identity/UI/src/bin/Release/netstandard2.0/Microsoft.AspNetCore.Identity.UI.Views.V4.dll" because it was not found. [/datadisks/disk1/vsagent/work/6/s/src/Identity/ApiAuthorization.IdentityServer/samples/ApiAuthSample/ApiAuthSample.csproj]
```

**Comment by ryanbrandenburg** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

I've triaged the above build.

**Comment by ryanbrandenburg** [comment]
Thank you for being a guinea pig @mikaelm12, I've got it working now!

**Comment by mikaelm12** [comment]
Glad to help!

**Comment by Eilon** [comment]
Which one is the human and which one is the robot?!?! 😕😕😕😕😕😕😕😕😕😕😕

**Comment by ryanbrandenburg** [comment]
lol that only happened because I was testing it locally where I only have my own PAT.

**Comment by mikaelm12** [comment]
This is a github version of the Turing Test

**Review by halter73 — APPROVED** [review]

**Comment by dougbu** [comment]
Retried the Linux build because this looks like build flakiness on closer inspection. That is, the projects aren't reliably built in the right order. In the first attempt, ApiAuthSample.csproj was built before Microsoft.AspNetCore.Identity.UI.csproj:
```
  Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore -> /datadisks/disk1/vsagent/work/6/s/src/Middleware/Diagnostics.EntityFrameworkCore/src/bin/Release/netstandard2.0/Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.dll
/datadisks/disk1/vsagent/work/6/.dotnet/sdk/2.2.102/Microsoft.Common.CurrentVersion.targets(4551,5): error MSB3030: Could not copy the file "/datadisks/disk1/vsagent/work/6/s/src/Identity/UI/src/bin/Release/netstandard2.0/Microsoft.AspNetCore.Identity.UI.Views.V4.dll" because it was not found. [/datadisks/disk1/vsagent/work/6/s/src/Identity/ApiAuthorization.IdentityServer/samples/ApiAuthSample/ApiAuthSample.csproj]
/datadisks/disk1/vsagent/work/6/.dotnet/sdk/2.2.102/Microsoft.Common.CurrentVersion.targets(4551,5): error MSB3030: Could not copy the file "/datadisks/disk1/vsagent/work/6/s/src/Identity/UI/src/bin/Release/netstandard2.0/Microsoft.AspNetCore.Identity.UI.Views.V4.pdb" because it was not found. [/datadisks/disk1/vsagent/work/6/s/src/Identity/ApiAuthorization.IdentityServer/samples/ApiAuthSample/ApiAuthSample.csproj]
/datadisks/disk1/vsagent/work/6/.dotnet/sdk/2.2.102/Microsoft.Common.CurrentVersion.targets(4551,5): error MSB3030: Could not copy the file "/datadisks/disk1/vsagent/work/6/s/src/Identity/UI/src/bin/Release/netstandard2.0/Microsoft.AspNetCore.Identity.UI.Views.V3.dll" because it was not found. [/datadisks/disk1/vsagent/work/6/s/src/Identity/ApiAuthorization.IdentityServer/samples/ApiAuthSample/ApiAuthSample.csproj]
/datadisks/disk1/vsagent/work/6/.dotnet/sdk/2.2.102/Microsoft.Common.CurrentVersion.targets(4551,5): error MSB3030: Could not copy the file "/datadisks/disk1/vsagent/work/6/s/src/Identity/UI/src/bin/Release/netstandard2.0/Microsoft.AspNetCore.Identity.UI.Views.V3.pdb" because it was not found. [/datadisks/disk1/vsagent/work/6/s/src/Identity/ApiAuthorization.IdentityServer/samples/ApiAuthSample/ApiAuthSample.csproj]
  Microsoft.AspNetCore.Identity.UI -> /datadisks/disk1/vsagent/work/6/s/src/Identity/UI/src/bin/Release/netstandard2.0/Microsoft.AspNetCore.Identity.UI.Views.V3.dll
  Microsoft.AspNetCore.Identity.UI -> /datadisks/disk1/vsagent/work/6/s/src/Identity/UI/src/bin/Release/netstandard2.0/Microsoft.AspNetCore.Identity.UI.Views.V4.dll
```
What's weird is ApiAuthSample.csproj _does_ depend on Microsoft.AspNetCore.Identity.UI.csproj:
``` xml
<Reference Include="Microsoft.AspNetCore.Identity.UI" />
```
Could mean our `<Reference />` infrastructure doesn't guarantee ordering.

**Comment by dougbu** [comment]
@ryanbrandenburg / RaaS when triaging a build or test failure, please include the new / updated issue in the comment on the PR.

**Comment by ryanbrandenburg** [comment]
@dougbu file an issue against aspnet/AspNetCore-Internal with "RAAS" in the name requesting this.

**Pull request merged**
