### PR TITLE
Use Node 18 (LTS)

### PR DESCRIPTION
**Pull request by BrennanConroy**

### CODE REVIEW

**Review by adityamandaleeka — APPROVED** [review]

**Comment by BrennanConroy** [comment]
@dotnet/aspnet-blazor-eng Can someone from the blazor team investigate why using Node 18 causes the Component.E2ETests to fail?

**Comment by javiercn** [comment]
@MackinnonBuck can you take a look?

**Comment by MackinnonBuck** [comment]
The issue could be caused by https://github.com/node-fetch/node-fetch/issues/1624, which describes a breaking change where `localhost` now resolves to `::1` (IPv6) instead of `127.0.0.1` (IPv4) in Node 18. This would be consistent with what the [logs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=263677&view=logs&j=5c945968-3a2e-573b-5d84-9df2797877cd&t=e55ea776-3af2-554d-ac75-b525c50bf32a&l=32) show:

```
[xUnit.net 00:00:04.84] Microsoft.AspNetCore.Components.E2ETests:  connect ECONNREFUSED ::1:42799
```

I've pushed a potential fix, let's see if that works.

**Comment by BrennanConroy** [comment]
Looks promising, thanks 😃

**Comment by BrennanConroy** [comment]
Doesn't look like it worked sadly.

**Comment by MackinnonBuck** [comment]
Hm. I still think my guess about what the issue is could still be right, but maybe something else is using a URL with "localhost" in it. I can look into it more tomorrow.

**Comment by MackinnonBuck** [comment]
Ok, this might have fixed it 🤞

**Review by javiercn — APPROVED** [review]

**Review by MackinnonBuck — APPROVED** [review]
Yup, I think it should be good to go!

**Review by wtgodbe — APPROVED** [review]

**Pull request merged**
