### PR TITLE
Add NavigationManager.OnLocationChanging event (#15428)

### PR DESCRIPTION
**Pull request by mrpmorris**
- Added `NavigationManager.OnLocationChanging`
 - Enable navigation prevention via `OnLocationChangingEventArgs.PreventNavigation()`

Addresses #15428

### CODE REVIEW

**Comment by ShaunCurtis** [comment]
Has this actually been implemented?  I can't find PreventNavigation() anywhere.

**Comment by mrpmorris** [comment]
No.

**Comment by ShaunCurtis** [comment]
NP.  I've been working on some solutions to the navigation issues of SPAs.  Will post them when I have them in a presentable form

**Comment by cs-sketch** [comment]
Is this been released?
couldn't find in any of the versions of Microsoft.AspNetCore.Components package.

**Comment by mrpmorris** [comment]
There's a better PR, but it's marked as a candidate for v6.

https://github.com/dotnet/aspnetcore/pull/24417

**Comment by nelson-b** [comment]
Is it implemented? If yes then let us know the details
C# version
.Net core Version
Syncfusion blazor version

Also let us know any other details

**Pull request closed without merging**
