### PR TITLE
Push VS.Redist*.nupkg files to the VS package feed

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Comment by dougbu** [comment]
@anurse this (as discussed) gets rid of another leg of our release pipeline.

Separately, is the release pipeline leg that pushes signalr*.tgz files to aspnetcore-dev on MyGet still needed? Those files are automatically pushed to https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json and https://dotnetcli.blob.core.windows.net/dotnet/index.json already.

**Comment by dougbu** [comment]
Change will not affect validation builds. See https://dev.azure.com/dnceng/internal/_build/results?buildId=359103&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76&j=1b89928a-2219-5ef9-602f-f95beb3da4dc for impact.

**Review by JunTaoLuo — APPROVED** [review]

**Comment by dougbu** [comment]
/ping @anurse on the "signalr*.tgz" [question above](https://github.com/aspnet/AspNetCore/pull/14115#issuecomment-532831935)

**Comment by anurse** [comment]
> Those files are automatically pushed to [dotnetfeed.blob.core.windows.net/dotnet-core/index.json](https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json) and [dotnetcli.blob.core.windows.net/dotnet/index.json](https://dotnetcli.blob.core.windows.net/dotnet/index.json) already.

I'm confused. How can the 'tgz' files be pushed to a NuGet feed? They're NPM packages. We definitely still need to push them to the MyGet feed unless there's an alternative NPM feed we can use (such as Azure Artifacts Public Feeds, etc.).

**Comment by anurse** [comment]
I confirmed that the Arcade tasks that push assets only push NPM packages to the blob feed. They don't push them to Azure Artifacts. So until that changes we should continue to push to MyGet.

**Comment by dougbu** [comment]
> only push NPM packages to the blob feed

Yeah, as i said
> those aren't in use across our repos yet (see aspnet/AspNetCore-Internal#3152)

This will change very soon, probably w/ the next Arcade dependency update.

**Comment by anurse** [comment]
Filed https://github.com/dotnet/arcade/issues/3992 to track the changes needed.

**Pull request merged**
