### PR TITLE
Merge release/2.1

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Review by dougbu — CHANGES_REQUESTED** [review]
Please hold off on this until I get the queue changes into `release/2.2`. You're backing those changes out while making it seem as if they're already in this branch.

I'll be updating #7920 to install Chrome and that one working after lunch.

**Comment by dougbu** [comment]
@pranavkm I just merged #7920 which should unblock this. You probably need to redo the merge to avoid conflicts and correct the list of commits.

**Comment by pranavkm** [comment]
:update:

**Review by dougbu — APPROVED** [review]
Looks fine to me

**Pull request merged**
