### PR TITLE
Pass the formatter context to the CreateJsonSerializer. It gives ability to override and create serializer specific to the context

### PR DESCRIPTION
**Pull request by mnltejaswini**
Summary of the changes (Less than 80 chars)
 - Pass the formatter context to overridable CreateJsonSerializer. This allows users to override it and create serializer customized to the context.

Addresses:
  In our scenario, we need to select serializer based on the request properties like api version. With context parameter, we can just override CreateJsonSerializer and plug the custom serializer based on the request.

### CODE REVIEW

**Comment by mnltejaswini** [comment]
@davidfowl

**Comment by rynowak** [comment]
The way you're supposed to do this is by registering multiple formatters and overriding `CanWrite`/`CanRead` - does that work for you?

**Comment by mnltejaswini** [comment]
@rynowak  Yes that also works, in our case where we want serializer per request's api version, we might need one formatter per version. With this change we have one formatter per service, but hook the appropriate serializer. Which approach do you recommend?

**Comment by rynowak** [comment]
> With this change we have one formatter per service, but hook the appropriate serializer. Which approach do you recommend?

How many versions will you have? How frequently do you expect to bump up version? Basically I want to understand if you're going to have 4-5 or like 10. That would help make a decision about whether new extensibility is needed. 

Regardless, any changes here will go into 3.0 - which I assume you're not using in production yet 😆

**Comment by mnltejaswini** [comment]
@rynowak   We are planning to flight one api version per trimester , not to mention that we need to support old api versions for over an year. So we might have under 10 versions if are actively deprecating the old versions, if not more than 10

**Review by pranavkm — APPROVED** [review]

**Comment by pranavkm** [comment]
Thanks @mnltejaswini

**Pull request merged**
