### PR TITLE
[Blazor] Ports all the missing commits from 3.1 into master

### PR DESCRIPTION
**Pull request by javiercn**
I'm starting this PR, but I'm expecting everyone to collaborate on this to get it to a good place.

### CODE REVIEW

**Comment by Tratcher** [comment]
What happened to the merge bot?

**Comment by javiercn** [comment]
@Tratcher Not sure, but there are a huge amounts of missing commits. I'm porting the ones from components manually

**Review by dougbu — CHANGES_REQUESTED** [review]
Please stop. This will just get in the way of what I'm doing to resolve conflicts in #14200. (Would have created a manual PR if the bot hadn't finally woken up.)

**Comment by javiercn** [comment]
This was done separately by the merge bot.

**Pull request closed without merging**
