### PR TITLE
Use new hosted build pools

### PR DESCRIPTION
**Pull request by jonfortescue**
- [x] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

**Use new hosted build pools in release/6.0-rc1**. Part of issue https://github.com/dotnet/core-eng/issues/14276.

### CODE REVIEW

**Review by dougbu — COMMENTED** [review]
Same question about release/6.0-rc1 as in dotnet/efcore#25868

/cc @mmitche @wtgodbe @ulisesh

**Comment by ulisesh** [comment]
@dougbu, we have to move all pool before 9/30. Will rc1 branch be deleted before that?

**Comment by dougbu** [comment]
> Will rc1 branch be deleted before that?

Yes. As @wtgodbe suggested in https://github.com/dotnet/efcore/pull/25868#issuecomment-912784999, retarget to `release/6.0`. That is where we'll branch for RC2 and the branch will live on into servicing.

**Comment by jonfortescue** [comment]
This change is already in release/6.0, so I'm going to close this PR.

**Pull request closed without merging**
