### PR TITLE
Basic proposed implementation for #11013.  Opening the discussion for…

### PR DESCRIPTION
**Pull request by Mike-E-angelo**
… future edits.  I am also ascertaining if I am even in the right place as there are numerous template folders, so trying this one and see where it goes. 

Summary of the changes (Less than 80 chars)
 - Replacing `<app />` tag with `<div class="application" />`
 - Updating identified CSS to select this new tag.

Addresses #11013

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
Thanks for your effort, @Mike-EEE. @SteveSandersonMS can you please review this? Thanks!

**Comment by khellang** [comment]
As there should only be one, I'd rather see `<div id="app" />` or `<div id="root" />` than using a class.

**Comment by Mike-EEE** [comment]
That's a gooood point, @khellang.  Thank you for your feedback.  I have updated to reflect this.  Please note that I prefer `application` to `app` as it is more verbose/descriptive, but am open to further discussion around this.

**Comment by Mike-EEE** [comment]
Egads, a typo in my commit comment to one of the largest repositories on Earth.  Scratch that off my list of largest fears of life yet unrealized. 😆🤦‍♂️😞

Looks like the solution is to do an [amend with a force push](https://help.github.com/en/articles/changing-a-commit-message).  Hopefully, that doesn't escalate my fear into a new tier altogether. 🤔  Please let me know if there is anything further I need to fix/address around this.

**Comment by khellang** [comment]
Some precedents out there:

- Angular - `app-root`
- React - `#root`
- Vue - `#app`
- Riot - `#root`
- Aurelia - `app`

BTW, don't you also need to change this:

https://github.com/aspnet/AspNetCore/blob/5b2f3fb5f7f24ac3e91c5150a55cc411b2b36b76/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorServerWeb-CSharp/Startup.cs#L173

**Comment by Mike-EEE** [comment]
> BTW, don't you also need to change this

Probably. 😆  Part of the confusion on my side is that there appear to be several templates used throughout the solution.  So, I wanted to verify which ones to modify before doing so and then potentially move this PR out of `Draft` status.  

Along those lines, when I create a new Blazor application on my local machine here using Preview 8, the `MapBlazorHub` does not have a selector used.  This makes me wonder if that `Program.cs` is currently even being used at all...

**Comment by khellang** [comment]
> when I create a new Blazor application on my local machine here using Preview 8, the `MapBlazorHub` does not have a selector used. This makes me wonder if that `Program.cs` is currently even being used at all...

That can't be right. There's no overload without `selector`:

https://github.com/aspnet/AspNetCore/blob/5b2f3fb5f7f24ac3e91c5150a55cc411b2b36b76/src/Components/Server/ref/Microsoft.AspNetCore.Components.Server.netcoreapp3.0.cs#L15-L25

**Comment by Mike-EEE** [comment]
Ahhhh I said preview "8" but actually have preview _7_ installed. 😆  Guess I should update to the latest preview if I am pushing PR's to the repo, huh. 😇

**Comment by Mike-EEE** [comment]
Hmmm... the mystery deepens.  I see a parameterless `MapBlazorHub` in preview 8, too:



Also, after installing Preview 8, I only see WebAssembly Blazor, two of them:

**Comment by Mike-EEE** [comment]
Alright, apologies while I get up to speed on some aspects that were not very clear to me from the outset.  I did investigate this further, and it appears that [an extension that I had installed was no longer required](https://marketplace.visualstudio.com/items?itemName=aspnet.blazor).

From that extension's page, I did manage to find valuable instructions for installation of the latest templates here at the following location:
https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=netcore-cli

While I could not get Visual Studio to see the new templates, I was able to create one from the CLI and confirmed the selector used in `MapBlazorHub`.  I have added a new commit with this selection.

**Comment by Mike-EEE** [comment]
> Some precedents out there:

A compelling list of examples. Thank you for providing them, @khellang.  I would almost be persuaded, except that I noticed that somewhere between Preview 7 and 8, the `ComponentBase.OnInitAsync` got renamed to `ComponentBase.OnInitializedAsync` (nevermind [that async isn't actually a word](https://developercommunity.visualstudio.com/idea/583945/improve-asynchronous-programming-model.html) 😆).  These efforts basically serve as a relevant and timely example for my apprehension here, as it would seem that there is a push -- or at least an awareness -- towards being more verbose and descriptive in symbols used throughout the solution here.

Although `root` would solve this problem, I find that it deviates from the original tag which was named `app`, of course.  Also, `root` doesn't seem as authoritative (or perhaps descriptive and accurate) as `app`/`application`.

All that stated, I would prefer to get further discussion/confirmation around this from a reviewer before proceeding, as it would obviously not be ideal to rename to `app` only to have to rename it yet again to `application` if there is a current push to be more verbose and correct in naming elements, as denoted by the recent efforts around `OnInitializedAsync`.

Thank you for any further kind suggestions/input/discussion/consideration that you and/or others can provide around this. 👍

**Comment by mkArtakMSFT** [comment]
@Mike-EEE do you plan to turn this into a non-draft?

**Comment by Mike-EEE** [comment]
Ah @mkArtakMSFT my goal with having it a draft was to ascertain if I am even in the right place with the files I am editing.  I still do not know with certainty if I have targeted the right files.  If this does not matter I can certainly un-draft this sucker.  Trying to be a good repo citizen here. 😁

**Comment by mkArtakMSFT** [comment]
Thanks for your effort here, @Mike-EEE.
With the recent changes on our side we're planning to change the way how components are registered and this can result in not having `<app />` (or similar) elements needed at all.  That said, we think it's best to not take this PR at the moment and wait for these changes instead.

**Comment by Mike-EEE** [comment]
Alright, sounds like a plan... I appreciate the opportunity to try out the PR route as I could always use more experience around it.  Thank you for the update and information, and best of luck with the new magic you're developing. 👍

**Pull request closed without merging**
