### PR TITLE
chore (codespaces) : Use latest omnisharp build

### PR DESCRIPTION
**Pull request by ShreyasJejurkar**
Fetch a new omnisharp build while creating a container!

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
@TanayParikh do we use OmniSharp for Razor Tooling only?
@ShreyasJejurkar what is your motivation for this chnage?

**Comment by ShreyasJejurkar** [comment]
This will grab the latest build  (main branch) from omnisharp repository to use instead of publicly released version.
I found that latest build is quite fast and stable enough on larger solutions, so I thought why not to grab latest build always to use it!

**Comment by filipw** [comment]
This is not a change you want to make. There is a good reason behind a proper release process for OmniSharp, in which we publish official releases [here](https://github.com/OmniSharp/omnisharp-roslyn/releases).

A prerelease is published on every merge to master, and the "latest" setting pulls those prereleases. This is slow and often contains regressions (there was quite a bad one earlier this month already). On top of this, there are sometimes breaking changes between what is in OmniSharp server and the C# extension, so just pulling the latest server component, without the corresponding extension update may break the extension.

**Comment by TanayParikh** [comment]
> do we use OmniSharp for Razor Tooling only?

This change specifically impacts the devcontainer we use for GitHub Codespaces.

> so I thought why not to grab latest build always to use it!

My concern with this change is the latest changes may have stability challenges that are being worked through. Given this is for our development use, and it's configurable after container creation, I'm inclined not to take this change in to ensure we don't get bit by stability challenges. 

For those who would like the bleeding-edge it's of course always configurable after container creation. Additionally, the speed benefits with larger project's you're seeing is great news, and I anticipate would be available in the next official release which we'll pick up automatically 😄

**Comment by TanayParikh** [comment]
@filipw beat me to it, thanks for clarifying! 😄

**Pull request closed without merging**
