### PR TITLE
Make hosting request log into struct to reduce allocation

### PR DESCRIPTION
**Pull request by Kahbazi**

### CODE REVIEW

**Comment by Tratcher** [comment]
Test failures:
https://dev.azure.com/dnceng/public/_build/results?buildId=1273536&view=ms.vss-test-web.build-test-results-tab&runId=37656460&resultId=110299&paneView=debug
```
System.ObjectDisposedException : IFeatureCollection has been disposed.
Object name: 'Collection'.
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ThrowContextDisposed() in /_/src/Extensions/Features/src/FeatureReferences.cs:line 154
   at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Protocol() in /_/src/Http/Http/src/Internal/DefaultHttpRequest.cs:line 134
   at Microsoft.AspNetCore.Hosting.HostingRequestStartingLog.ToString() in /_/src/Hosting/Hosting/src/Internal/HostingRequestStartingLog.cs:line 45
   at Microsoft.Extensions.Logging.Testing.TestLogger.<>c__DisplayClass11_0`1.<Log>b__0(Object s, Exception e) in /_/src/Testing/src/Logging/TestLogger.cs:line 55
   at Microsoft.Extensions.Logging.Testing.WriteContext.get_Message() in /_/src/Testing/src/Logging/WriteContext.cs:line 28
   at Interop.FunctionalTests.HttpClientHttp2InteropTests.<>c.<ResponseHeaders_MultipleFrames_Accepted>b__25_1(WriteContext context) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/HttpClientHttp2InteropTests.cs:line 1115
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext() in System.Linq.dll:token 0x600022c+0x61
   at Interop.FunctionalTests.HttpClientHttp2InteropTests.ResponseHeaders_MultipleFrames_Accepted(String scheme) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/HttpClientHttp2InteropTests.cs:line 1115
--- End of stack trace from previous location ---
```
Did this uncover a lifetime issue in these tests?

**Comment by davidfowl** [comment]
We can't make this change because the struct is mutable (we assign ToString to the _cachedToString) every single time. It's also less efficient since we'd need to pass a copy to each provider instead of the struct instance. Each call ToString will allocate a new string per provider instead of one for all providers.

**Comment by Kahbazi** [comment]
> Did this uncover a lifetime issue in these tests?

I will investigate.

> We can't make this change because the struct is mutable (we assign ToString to the _cachedToString) every single time. It's also less efficient since we'd need to pass a copy to each provider instead of the struct instance. Each call ToString will allocate a new string per provider instead of one for all providers.

How about making them readonly struct like [FormattedLogValues](https://github.com/dotnet/runtime/blob/23601612c5088a321d6205336cd0754a59cb7dc3/src/libraries/Microsoft.Extensions.Logging.Abstractions/src/FormattedLogValues.cs#L16
)?

**Comment by Kahbazi** [comment]
> > Did this uncover a lifetime issue in these tests?
> 
> I will investigate.

@Tratcher The problem was that the assertion for the log message is being done after the request is finished but the Message property itself is being generated on each access and as @davidfowl mentioned the struct is being copied and _cachedString would be null and each call ToString will create a new string and that's when the request is no longer available.
https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Servers/Kestrel/test/Interop.FunctionalTests/HttpClientHttp2InteropTests.cs#L1115
https://github.com/dotnet/aspnetcore/blob/45222c12d944a8915ba480220de8a1f9c133c0c4/src/Testing/src/Logging/WriteContext.cs#L24-L30

I think this could be fixed by storing the result of formatter when creating an instance of `WriteContext`, but I'm not sure if it's necessary for now.

Making the `HostingRequestFinishedLog` readonly struct and moving the creation of the formatted string in the constructor fixed the tests. @davidfowl Does it also fixes the problems you've mentioned?

**Comment by davidfowl** [comment]
@Kahbazi yes it does that be allocating the string eagerly, can you show a before and after allocation profile?

**Comment by Kahbazi** [comment]
@davidfowl Here's the allocation profile for 1000 requests. I think we could also make logging scope into readonly struct as well.
Before:
| Type | Allocations|
| ------------- | ------------- |
| System.String | 15,377 |
| System.SByte[] | 10,706 |
| System.Threading.ExecutionContext | 4,126 |
| System.Byte[] | 2,742 |
| System.Threading.AsyncLocalValueMap.OneElementAsyncLocalValueMap | 2,125 |
| System.String[] | 2,121 |
| System.Threading.AsyncLocalValueMap.TwoElementAsyncLocalValueMap | 2,000 |
| System.Object | 1,810 |
| System.Collections.Concurrent.ConcurrentDictionary<,>.Node | 1,322 |
| System.Threading.CancellationTokenSource.CallbackNode | 1,228 |
| System.Threading.CancellationTokenSource.Registrations | 1,195 |
| System.IDisposable[] | 1,135 |
| Microsoft.Extensions.Logging.LoggerFactoryScopeProvider.Scope | 1,125 |
| Microsoft.Extensions.Logging.Logger.Scope | 1,125 |
| System.Runtime.CompilerServices.AsyncTaskMethodBuilder<>.AsyncStateMachineBox<> | 1,011 |
| Microsoft.AspNetCore.Hosting.HostingRequestFinishedLog | 1,000 |
| System.Diagnostics.Activity | 1,000 |
| Microsoft.AspNetCore.Hosting.HostingRequestStartingLog | 1,000 |
| Microsoft.AspNetCore.Hosting.HostingApplicationDiagnostics.Log.HostingLogScope | 1,000 |
| System.Threading.CancellationTokenSource.Linked1CancellationTokenSource | 927 |
| System.Object[] | 914 |

After:
| Type | Allocations|
| ------------- | ------------- |
|  System.String | 15,363 |
|  System.SByte[] | 10,740 |
|  System.Threading.ExecutionContext | 4,126 |
|  System.Byte[] | 2,740 |
|  System.Threading.AsyncLocalValueMap.OneElementAsyncLocalValueMap | 2,125 |
|  System.String[] | 2,121 |
|  System.Threading.AsyncLocalValueMap.TwoElementAsyncLocalValueMap | 2,000 |
|  System.Object | 1,810 |
|  System.Collections.Concurrent.ConcurrentDictionary<,>.Node | 1,324 |
|  System.Threading.CancellationTokenSource.CallbackNode | 1,219 |
|  System.Threading.CancellationTokenSource.Registrations | 1,186 |
|  System.IDisposable[] | 1,135 |
|  Microsoft.Extensions.Logging.LoggerFactoryScopeProvider.Scope | 1,125 |
|  Microsoft.Extensions.Logging.Logger.Scope | 1,125 |
|  System.Runtime.CompilerServices.AsyncTaskMethodBuilder<>.AsyncStateMachineBox<> | 1,011 |
|  System.Diagnostics.Activity | 1,000 |
|  Microsoft.AspNetCore.Hosting.HostingApplicationDiagnostics.Log.HostingLogScope | 1,000 |
|  System.Threading.CancellationTokenSource.Linked1CancellationTokenSource | 918 |
|  System.Object[] | 914 |

**Comment by Kahbazi** [comment]
@davidfowl I think turning log scope to readonly struct is reducing allocations. If so do you think it worth adding it to 6.0 in order to benefit from it sooner?

**Comment by shirhatti** [comment]
Triage: We've decided not to take this change.

**Pull request closed without merging**
