### PR TITLE
[release/3.1] Remove dependency on netstandard.library

### PR DESCRIPTION
**Pull request by wtgodbe**
This package isn't being produced out of dotnet/runtime anymore - we should just use the default version that is bundled with the SDK rather than listing a dependency on it.

CC @dagood @Pilchie @ericstj

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
To confirm: The `wtgodbe/standard` branch is based on the result of `git merge-base --octopus release/3.1 master` or (perhaps, not sure if 'blazor-wasm' branch matters in this respect) `git merge-base --octopus release/3.1 blazor-wasm master`?

And, does the 'release/2.1' branch need a similar change? What about other repos?

**Comment by dagood** [comment]
Is this the same as https://github.com/dotnet/extensions/pull/3098?

Copying my comment from https://github.com/dotnet/extensions/pull/3098#issuecomment-602246807:

> > This package isn't being produced out of dotnet/runtime anymore
> 
> dotnet/runtime isn't relevant to 3.1, and I'm not sure if the idea behind removing this dependency makes sense here. I don't know how likely we are to build a netstandard patch but I believe it would be built as part of the 3.1 product in dotnet/core-setup if it happened.

**Comment by wtgodbe** [comment]
If there's a chance we'll service netstandard.library.ref out of core-setup 3.1, it's probably better to keep the reference and the `KnownFrameworkReference` update (as opposed to needing to update the SDK to get the new netstandard.library surface area). @dougbu thoughts?

**Comment by dougbu** [comment]
> it's probably better to keep the reference and the `KnownFrameworkReference` update

I have no objection to this plan.

**Pull request closed without merging**
