### PR TITLE
Update branding to 5.0.4

### PR DESCRIPTION
**Pull request by dougbu**
- merge in 5.0.3 changes
- update to 5.0.3 SDK and bump downlevel runtimes
- update package baselines
- update branding to 5.0.4
    - move to latest Microsoft.AspNetCore.Azure.AppServices.SiteExtension.31 version

### CODE REVIEW

**Review by wtgodbe — CHANGES_REQUESTED** [review]
Still got some merge conflicts

**Comment by dougbu** [comment]
> Still got some merge conflicts

Nope, just targeting wrong base branch

**Review by wtgodbe — APPROVED** [review]

**Comment by dougbu** [comment]
@mmitche @wtgodbe help 🆘 plz
``` text
...\src\Grpc\test\testassets\InteropWebsite\InteropWebsite.csproj : error NU1101: Unable to find package Grpc.Net.ClientFactory. No packages exist with this id in source(s): ...\artifacts\packages\Release\Shipping\, dotnet-eng, dotnet-public, dotnet-tools, dotnet31-transport, dotnet5, dotnet5-transport [...\.dotnet\sdk\5.0.103\NuGet.targets]
...\src\Grpc\test\testassets\InteropClient\InteropClient.csproj : error NU1101: Unable to find package Google.Apis. No packages exist with this id in source(s): dotnet-eng, dotnet-public, dotnet-tools, dotnet31-transport, dotnet5, dotnet5-transport [...\.dotnet\sdk\5.0.103\NuGet.targets]
...\src\Grpc\test\testassets\InteropClient\InteropClient.csproj : error NU1101: Unable to find package Google.Apis.Core. No packages exist with this id in source(s): dotnet-eng, dotnet-public, dotnet-tools, dotnet31-transport, dotnet5, dotnet5-transport [...\.dotnet\sdk\5.0.103\NuGet.targets]
```

**Comment by wtgodbe** [comment]
> @wtgodbe help 🆘 plz

Pushing now

**Review by JunTaoLuo — APPROVED** [review]

**Comment by dougbu** [comment]
> Pushing now

Much appreciated. That did it❕

**Pull request merged**
