### PR TITLE
Merging internal commits for release/6.0

### PR DESCRIPTION
**Pull request by vseanreesermsft**

### CODE REVIEW

**Comment by dougbu** [comment]
@mmitche this was _not_ ready to go. Sorry I was out yesterday afternoon and didn't get this done. But merging without the rest means nothing as far as code flow goes.

**Comment by mmitche** [comment]
@dougbu What else needed done here?

**Comment by dougbu** [comment]
> @dougbu What else needed done here?

- update the package baselines
- reenable baseline validation
- update the .NET SDK
- update the downlevel site extension versions

**Comment by mmitche** [comment]
This is just the internal commit merge. That sounds more like a separate branding update?

**Comment by mmitche** [comment]
Okay. Was definitely not interpreting this as an all-clear. Note that the SDK has already been updated in a separate arcade PR.

**Pull request merged**
