### PR TITLE
Changed "log in" to "login" for wording consistency

### PR DESCRIPTION
**Pull request by ILL35T**
The _LoginPartial refers to the page as "Login" so it should be consistent throughout and be called "Login".
image

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
You also need to change "Log out" to "Logout" in Areas\Identity\Pages\Account\Logout.cshtml

I think we should wait until 6.0 and change it to Sign In/out

**Comment by pranavkm** [comment]
@Rick-Anderson is there a reason Sign In is preferred to Login?

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson is there a reason Sign In is preferred to Login?

Nothing significant. For the templates it doesn't matter.  The style guide prefers `Sign in` over `Login` or `Log in`, but that's the advice when writing about logging onto a site, it's not coding advice. 

Changing from `Log in` to `Login`  and `Log out` to `Logout` in my opinion is not a big enough improvement to justify the work.  

In https://github.com/dotnet/Scaffolding/pull/1366#issuecomment-658156819, `@blowdart` wrote:
>I'd go for login for now, and re-examine in 6.0 for sign-in.

So my vote was not change anything until 6.0, then consider `Sign in`.

**Comment by HaoK** [comment]
That sounds reasonable to me too, @blowdart thoughts on just waiting til 6.0 to change things?

**Comment by ILL35T** [comment]
@Rick-Anderson @HaoK @blowdart an alternative would be to change the LoginPartial to "Log In" until we get to changing everything to Sign In/Out. 

The "Log In"/"Log Out" change can be found here: https://github.com/dotnet/aspnetcore/pull/23980

**Comment by HaoK** [comment]
We can revisit this in 6.0

**Pull request closed without merging**
