### PR TITLE
Show user friendly error when network requests fail

### LINKED ISSUE #51618: Enhanced Navigation Silently Ignores Fetch Network Errors
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When a fetch request from enhanced navigation fails (due to the server being offline or a network issue), there is no indiction in the UI. If you look at the network inspector, you can see the failed requests.

Failed requests in the web inspector, but no indication of anything in the UI

### Expected Behavior

I would expect the UI to show some sort of error when the `fetch` requests fail like the UI below

A Blazor page showing a message saying that an unhandled problem has occurred

### Steps To Reproduce

* Create a new project with `dotnet new blazor` and run it
* Navigate to the app
* Shut down the web server
* Click the links and the UI shows nothing

### .NET Version

8.0.100-rtm.23524.4

### Anything else?

This has been tested on 8.0.100-rc.2.23502.2, 8.0.100-rtm.23524.4 (nightly), and 8.0.200-preview.23523.27 (nightly). All were fresh installs of dotnet on VMs and the nightly NuGet config was added for the nightly ones.

```
.NET SDK:
 Version:           8.0.100-rtm.23524.4
 Commit:            5bc5eecc5a
 Workload version:  8.0.100-manifests.ea856202

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.0
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.100-rtm.23524.4/

.NET workloads installed:
 Workload version: 8.0.100-manifests.ea856202
There are no installed workloads to display.

Host:
  Version:      8.0.0-rtm.23519.13
  Architecture: arm64
  Commit:       86c949374e

.NET SDKs installed:
  8.0.100-rtm.23524.4 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-rtm.23520.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0-rtm.23519.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```

### PR DESCRIPTION
**Pull request by LilahTovMoon**
# Show user friendly error when network requests fail

- [X] You've read the [Contributor Guide](https://github.com/dotnet/aspnetcore/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/dotnet/aspnetcore/blob/main/CODE-OF-CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [X] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Description

If there's a network error, there is no feedback in the UI that anything has happened. The user can keep clicking with no indication that anything is wrong.

This makes it show the `blazor-error-ui` when a network error happens and it logs it to the console.

image-3

Fixes #51618

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
@LilahTovMoon I see that you've opened two PRs for the same thing. Can you please close one of these so that we review the other?

**Comment by LilahTovMoon** [comment]
They're slightly different PRs handling two different error scenarios. This PR handles when network requests fail (the server is offline or there's a network error between the user and the server and JavaScript gets a `TypeError: NetworkError` from the `fetch` call).

https://github.com/dotnet/aspnetcore/pull/51687 handles a different case where the client receives a response from the server with a response of `<blazor-ssr><template type="error">...` because of an exception being thrown on the server.

This PR catches the `TypeError: NetworkError` from the `fetch` call and displays an error rather than doing nothing. The other modifies the handling of `<blazor-ssr><template type="error">...` so that it displays a more friendly error rather than replacing the document with the plain text of the response.

**Comment by mkArtakMSFT** [comment]
Thanks for clarification, @LilahTovMoon. I didn't pay close enough attention to see the difference. Will get somebody to review these.

**Comment by MackinnonBuck** [comment]
Thanks for the pull request, @LilahTovMoon!

Let's wait for additional feedback on https://github.com/dotnet/aspnetcore/pull/51687 before moving forward with this change.

**Comment by MackinnonBuck** [comment]
Hi @LilahTovMoon, thanks for your contribution. We're going to close this out and revisit the problem in the future so we can have an error page solution that works more consistently between enhanced and non-enhanced nav.

**Pull request closed without merging**
