### PR TITLE
Empty template tweaks

### LINKED ISSUE #43869: Blazor WebAssembly empty template minor issues
1. The indentation inside `MainLayout.razor` is nonstandard
2. We're missing the usual `h1:focus` CSS rule, so when the page first loads, there's a strange black box around everything

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
# Blazor WebAssembly empty template tweaks

The new Blazor WebAssembly empty template has a couple of minor, easily fixable issues.

## Description

1. The indentation inside `MainLayout.razor` is nonstandard
2. We're missing the usual `h1:focus` CSS rule, so when the page first loads, there's a strange black box around everything

Fixes #43869

## Customer Impact

Without these changes, the new project's output looks strange when first loaded in a browser. The fix in this PR just adds the same `h1:focus` CSS rule we use in all the other Blazor projects.

Similarly, the `MainLayout.razor` file has nonstandard layout without this PR.

## Regression?

- [ ] Yes
- [x] No - **the empty template is a new feature in 7.0**

[If yes, specify the version the behavior has regressed from]

## Risk

- [ ] High
- [ ] Medium
- [x] Low

Spectacularly low risk, as it's only a minor CSS tweak to bring this template more in line with the standard one that's been well proven already.

## Verification

- [x] Manual (required)
- [ ] Automated

## Packaging changes reviewed?

- [ ] Yes
- [ ] No
- [x] N/A

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
@kevinpi Assuming CI passes, this should be ready for review and can immediately be merged if you're OK with it. Thanks!

**Comment by Pilchie** [comment]
Approved for .NET 7 RC2.  Note - I wonder who `kevinpi` is on GitHub.  It's not me ;)

**Comment by SteveSandersonMS** [comment]
> I wonder who kevinpi is on GitHub. It's not me ;)

Oh, sorry! Thanks for finding this somehow though.

**Review by danroth27 — APPROVED** [review]
LGTM

**Comment by SteveSandersonMS** [comment]
@Pilchie Should be ready to merge now.

**Review by Eilon — APPROVED** [review]

**Review by mkArtakMSFT — APPROVED** [review]

**Review by TanayParikh — COMMENTED** [review]
👍

**Pull request merged**
