### PR TITLE
Update Versions.props to latest Microsoft.Identity.Web 2.13.4

### PR DESCRIPTION
**Pull request by jmprieur**
# Update Versions.props to latest Microsoft.Identity.Web 2.13.4

This makes sure the Microsoft Entra External ID scenarios work well with ASP.NET Core in .NET 8 rc2

### CODE REVIEW

**Review by eerhardt — APPROVED** [review]

**Comment by wtgodbe** [comment]
@MackinnonBuck can you take a look at the test failures?

**Comment by MackinnonBuck** [comment]
Each of the failures mentions package downgrades. For example:

```
error NU1605: Warning As Error: Detected package downgrade: Microsoft.AspNetCore.Authentication.JwtBearer from 8.0.0-preview.7.23375.9 to 8.0.0-ci. Reference the package directly from the project to select a different version.
```

Not sure why this didn't happen in https://github.com/dotnet/aspnetcore/pull/50582. @halter73 do you know what might be going on?

**Comment by wtgodbe** [comment]
Superseded by https://github.com/dotnet/aspnetcore/pull/51430

**Pull request closed without merging**
