### PR TITLE
Add .env file to react projecttemplates in order to run the CRA serve…

### LINKED ISSUE #7286: dotnet new react requires .env
_From @Rick-Anderson on February 1, 2019 21:38_

See https://github.com/aspnet/Docs/pull/10423 and [Use the React project template](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-2.2&tabs=visual-studio)

Add a *.env* file to the *ClientApp* subdirectory with the following setting:

     `BROWSER=none`

This will prevent your web browser from opening when starting the CRA server externally.

_Copied from original issue: dotnet/templating#1752_

### PR DESCRIPTION
**Pull request by dannyBies**
Added .env files to the react project templates in order to run the CRA server independently.

Fixes #7286

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
@ryanbrandenburg Would you be able to verify this works correctly?

**Comment by ryanbrandenburg** [comment]
@dannyBies this never replicated for me. Oughtn't this be fixed by https://github.com/aspnet/AspNetCore/blob/7269dbb73f4aa0ebf5ebb8bc07a076ee181851be/src/Middleware/SpaServices.Extensions/src/ReactDevelopmentServer/ReactDevelopmentServerMiddleware.cs#L72? If the answer is that this is "more correct" I can get behind that, but I'm still wondering how you're seeing this and I'm not.

**Comment by dannyBies** [comment]
@ryanbrandenburg 

The code in ReactDevelopmentServerMiddleware.cs only gets executed when I start the ASP.NET Core app in development mode. 
I followed [this guide](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-2.2&tabs=visual-studio#run-the-cra-server-independently) in which I run the CRA server independently from the Core app. Because I'm just running npm start the ReactDevelopmentServerMiddleware does not get executed and the environment variables are not added.

**Comment by ryanbrandenburg** [comment]
Ah, that explains it. This should be fine then.

**Review by ryanbrandenburg — APPROVED** [review]

**Comment by dannyBies** [comment]
Sorry guys, I messed up somehow :).  I've created a new PR (#13525) that only contains the relevant changes.

**Pull request closed without merging**
