### PR TITLE
Update branding for 3.1.20

### PR DESCRIPTION
**Pull request by vseanreesermsft**

### CODE REVIEW

**Comment by dougbu** [comment]
Lots failing. Assigning @wtgodbe for fixes

**Comment by wtgodbe** [comment]
@MattGal installing nginx just stopped working on OSX 10.14, but is working here after upgrading to 10.15 (failing build here: https://dev.azure.com/dnceng/public/_build/results?buildId=1347028&view=logs&j=f43b187f-6c15-531c-a59b-e4fba4e9ed20). This was working as recently as last month, any idea what might have changed? Here's what we run: https://github.com/dotnet/aspnetcore/blob/release/3.1/eng/scripts/install-nginx-mac.sh

**Comment by MattGal** [comment]
> @MattGal installing nginx just stopped working on OSX 10.14, but is working in this PR after upgrading to 10.15 (failing build on 10.14 here: https://dev.azure.com/dnceng/public/_build/results?buildId=1347028&view=logs&j=f43b187f-6c15-531c-a59b-e4fba4e9ed20). This was working as recently as last month, any idea what might have changed? Here's what we run: https://github.com/dotnet/aspnetcore/blob/release/3.1/eng/scripts/install-nginx-mac.sh

Tough to answer since that build is gone and 10.14 has been deprecated from Hosted MacOS, but in general when MacOS things change (you may want to retitle that job, it's still named 10.14?) I go to the `actions/virtual-environments` repo, e.g. https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md

The interesting bit from this readme is that it explicitly lists NGinX as present and stopped, so you could simplify your scripts possibly to just starting it:

image

**Comment by MattGal** [comment]
> I only updated from 10.14 to 10.15 in this PR to see if that would fix the issue, I'm not sure that's the solution we actually want to go with in servicing. Here's the 5.0 branding PR, where the 10.14 job fails to install nginx: #36236. I don't see anything about nginx in the 10.14 doc: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.14-Readme.md

Ah, I see they have only removed it from the landing page for now. Regardless, the history of that .md file is what's changed, and if you cannot reasonably adapt to it please file an issue on this repo about the problem, then use @dotnet/dnceng for escalation if you are stuck.

**Comment by wtgodbe** [comment]
`ContinueOnError` for installing nginx looks like the way to go, tests still pass, and that leg doesn't produce anything we publish. Filed https://github.com/actions/virtual-environments/issues/4049 for them to fix the image issue, but it isn't blocking at the moment.

**Review by wtgodbe — APPROVED** [review]

**Pull request merged**
